import {
HiAcademicCap,
HiAdjustments,
HiAnnotation,
HiArchive,
HiArrowCircleDown,
HiArrowCircleLeft,
HiArrowCircleRight,
HiArrowCircleUp,
HiArrowDown,
HiArrowLeft,
HiArrowNarrowDown,
HiArrowNarrowLeft,
HiArrowNarrowRight,
HiArrowNarrowUp,
HiArrowRight,
HiArrowSmDown,
HiArrowSmLeft,
HiArrowSmRight,
HiArrowSmUp,
HiArrowUp,
HiArrowsExpand,
HiAtSymbol,
HiBackspace,
HiBadgeCheck,
HiBan,
HiBeaker,
HiBell,
HiBookOpen,
HiBookmarkAlt,
HiBookmark,
HiBriefcase,
HiCake,
HiCalculator,
HiCalendar,
HiCamera,
HiCash,
HiChartBar,
HiChartPie,
HiChartSquareBar,
HiChatAlt2,
HiChatAlt,
HiChat,
HiCheckCircle,
HiCheck,
HiChevronDoubleDown,
HiChevronDoubleLeft,
HiChevronDoubleRight,
HiChevronDoubleUp,
HiChevronDown,
HiChevronLeft,
HiChevronRight,
HiChevronUp,
HiChip,
HiClipboardCheck,
HiClipboardCopy,
HiClipboardList,
HiClipboard,
HiClock,
HiCloudDownload,
HiCloudUpload,
HiCloud,
HiCode,
HiCog,
HiCollection,
HiColorSwatch,
HiCreditCard,
HiCubeTransparent,
HiCube,
HiCurrencyBangladeshi,
HiCurrencyDollar,
HiCurrencyEuro,
HiCurrencyPound,
HiCurrencyRupee,
HiCurrencyYen,
HiCursorClick,
HiDatabase,
HiDesktopComputer,
HiDeviceMobile,
HiDeviceTablet,
HiDocumentAdd,
HiDocumentDownload,
HiDocumentDuplicate,
HiDocumentRemove,
HiDocumentReport,
HiDocumentSearch,
HiDocumentText,
HiDocument,
HiDotsCircleHorizontal,
HiDotsHorizontal,
HiDotsVertical,
HiDownload,
HiDuplicate,
HiEmojiHappy,
HiEmojiSad,
HiExclamationCircle,
HiExclamation,
HiExternalLink,
HiEyeOff,
HiEye,
HiFastForward,
HiFilm,
HiFilter,
HiFingerPrint,
HiFire,
HiFlag,
HiFolderAdd,
HiFolderDownload,
HiFolderOpen,
HiFolderRemove,
HiFolder,
HiGift,
HiGlobeAlt,
HiGlobe,
HiHand,
HiHashtag,
HiHeart,
HiHome,
HiIdentification,
HiInboxIn,
HiInbox,
HiInformationCircle,
HiKey,
HiLibrary,
HiLightBulb,
HiLightningBolt,
HiLink,
HiLocationMarker,
HiLockClosed,
HiLockOpen,
HiLogin,
HiLogout,
HiMailOpen,
HiMail,
HiMap,
HiMenuAlt1,
HiMenuAlt2,
HiMenuAlt3,
HiMenuAlt4,
HiMenu,
HiMicrophone,
HiMinusCircle,
HiMinusSm,
HiMinus,
HiMoon,
HiMusicNote,
HiNewspaper,
HiOfficeBuilding,
HiPaperAirplane,
HiPaperClip,
HiPause,
HiPencilAlt,
HiPencil,
HiPhoneIncoming,
HiPhoneMissedCall,
HiPhoneOutgoing,
HiPhone,
HiPhotograph,
HiPlay,
HiPlusCircle,
HiPlusSm,
HiPlus,
HiPresentationChartBar,
HiPresentationChartLine,
HiPrinter,
HiPuzzle,
HiQrcode,
HiQuestionMarkCircle,
HiReceiptRefund,
HiReceiptTax,
HiRefresh,
HiReply,
HiRewind,
HiRss,
HiSaveAs,
HiSave,
HiScale,
HiScissors,
HiSearchCircle,
HiSearch,
HiSelector,
HiServer,
HiShare,
HiShieldCheck,
HiShieldExclamation,
HiShoppingBag,
HiShoppingCart,
HiSortAscending,
HiSortDescending,
HiSparkles,
HiSpeakerphone,
HiStar,
HiStatusOffline,
HiStatusOnline,
HiStop,
HiSun,
HiSupport,
HiSwitchHorizontal,
HiSwitchVertical,
HiTable,
HiTag,
HiTemplate,
HiTerminal,
HiThumbDown,
HiThumbUp,
HiTicket,
HiTranslate,
HiTrash,
HiTrendingDown,
HiTrendingUp,
HiTruck,
HiUpload,
HiUserAdd,
HiUserCircle,
HiUserGroup,
HiUserRemove,
HiUser,
HiUsers,
HiVariable,
HiVideoCamera,
HiViewBoards,
HiViewGridAdd,
HiViewGrid,
HiViewList,
HiVolumeOff,
HiVolumeUp,
HiWifi,
HiXCircle,
HiX,
HiZoomIn,
HiZoomOut,
HiOutlineAcademicCap,
HiOutlineAdjustments,
HiOutlineAnnotation,
HiOutlineArchive,
HiOutlineArrowCircleDown,
HiOutlineArrowCircleLeft,
HiOutlineArrowCircleRight,
HiOutlineArrowCircleUp,
HiOutlineArrowDown,
HiOutlineArrowLeft,
HiOutlineArrowNarrowDown,
HiOutlineArrowNarrowLeft,
HiOutlineArrowNarrowRight,
HiOutlineArrowNarrowUp,
HiOutlineArrowRight,
HiOutlineArrowSmDown,
HiOutlineArrowSmLeft,
HiOutlineArrowSmRight,
HiOutlineArrowSmUp,
HiOutlineArrowUp,
HiOutlineArrowsExpand,
HiOutlineAtSymbol,
HiOutlineBackspace,
HiOutlineBadgeCheck,
HiOutlineBan,
HiOutlineBeaker,
HiOutlineBell,
HiOutlineBookOpen,
HiOutlineBookmarkAlt,
HiOutlineBookmark,
HiOutlineBriefcase,
HiOutlineCake,
HiOutlineCalculator,
HiOutlineCalendar,
HiOutlineCamera,
HiOutlineCash,
HiOutlineChartBar,
HiOutlineChartPie,
HiOutlineChartSquareBar,
HiOutlineChatAlt2,
HiOutlineChatAlt,
HiOutlineChat,
HiOutlineCheckCircle,
HiOutlineCheck,
HiOutlineChevronDoubleDown,
HiOutlineChevronDoubleLeft,
HiOutlineChevronDoubleRight,
HiOutlineChevronDoubleUp,
HiOutlineChevronDown,
HiOutlineChevronLeft,
HiOutlineChevronRight,
HiOutlineChevronUp,
HiOutlineChip,
HiOutlineClipboardCheck,
HiOutlineClipboardCopy,
HiOutlineClipboardList,
HiOutlineClipboard,
HiOutlineClock,
HiOutlineCloudDownload,
HiOutlineCloudUpload,
HiOutlineCloud,
HiOutlineCode,
HiOutlineCog,
HiOutlineCollection,
HiOutlineColorSwatch,
HiOutlineCreditCard,
HiOutlineCubeTransparent,
HiOutlineCube,
HiOutlineCurrencyBangladeshi,
HiOutlineCurrencyDollar,
HiOutlineCurrencyEuro,
HiOutlineCurrencyPound,
HiOutlineCurrencyRupee,
HiOutlineCurrencyYen,
HiOutlineCursorClick,
HiOutlineDatabase,
HiOutlineDesktopComputer,
HiOutlineDeviceMobile,
HiOutlineDeviceTablet,
HiOutlineDocumentAdd,
HiOutlineDocumentDownload,
HiOutlineDocumentDuplicate,
HiOutlineDocumentRemove,
HiOutlineDocumentReport,
HiOutlineDocumentSearch,
HiOutlineDocumentText,
HiOutlineDocument,
HiOutlineDotsCircleHorizontal,
HiOutlineDotsHorizontal,
HiOutlineDotsVertical,
HiOutlineDownload,
HiOutlineDuplicate,
HiOutlineEmojiHappy,
HiOutlineEmojiSad,
HiOutlineExclamationCircle,
HiOutlineExclamation,
HiOutlineExternalLink,
HiOutlineEyeOff,
HiOutlineEye,
HiOutlineFastForward,
HiOutlineFilm,
HiOutlineFilter,
HiOutlineFingerPrint,
HiOutlineFire,
HiOutlineFlag,
HiOutlineFolderAdd,
HiOutlineFolderDownload,
HiOutlineFolderOpen,
HiOutlineFolderRemove,
HiOutlineFolder,
HiOutlineGift,
HiOutlineGlobeAlt,
HiOutlineGlobe,
HiOutlineHand,
HiOutlineHashtag,
HiOutlineHeart,
HiOutlineHome,
HiOutlineIdentification,
HiOutlineInboxIn,
HiOutlineInbox,
HiOutlineInformationCircle,
HiOutlineKey,
HiOutlineLibrary,
HiOutlineLightBulb,
HiOutlineLightningBolt,
HiOutlineLink,
HiOutlineLocationMarker,
HiOutlineLockClosed,
HiOutlineLockOpen,
HiOutlineLogin,
HiOutlineLogout,
HiOutlineMailOpen,
HiOutlineMail,
HiOutlineMap,
HiOutlineMenuAlt1,
HiOutlineMenuAlt2,
HiOutlineMenuAlt3,
HiOutlineMenuAlt4,
HiOutlineMenu,
HiOutlineMicrophone,
HiOutlineMinusCircle,
HiOutlineMinusSm,
HiOutlineMinus,
HiOutlineMoon,
HiOutlineMusicNote,
HiOutlineNewspaper,
HiOutlineOfficeBuilding,
HiOutlinePaperAirplane,
HiOutlinePaperClip,
HiOutlinePause,
HiOutlinePencilAlt,
HiOutlinePencil,
HiOutlinePhoneIncoming,
HiOutlinePhoneMissedCall,
HiOutlinePhoneOutgoing,
HiOutlinePhone,
HiOutlinePhotograph,
HiOutlinePlay,
HiOutlinePlusCircle,
HiOutlinePlusSm,
HiOutlinePlus,
HiOutlinePresentationChartBar,
HiOutlinePresentationChartLine,
HiOutlinePrinter,
HiOutlinePuzzle,
HiOutlineQrcode,
HiOutlineQuestionMarkCircle,
HiOutlineReceiptRefund,
HiOutlineReceiptTax,
HiOutlineRefresh,
HiOutlineReply,
HiOutlineRewind,
HiOutlineRss,
HiOutlineSaveAs,
HiOutlineSave,
HiOutlineScale,
HiOutlineScissors,
HiOutlineSearchCircle,
HiOutlineSearch,
HiOutlineSelector,
HiOutlineServer,
HiOutlineShare,
HiOutlineShieldCheck,
HiOutlineShieldExclamation,
HiOutlineShoppingBag,
HiOutlineShoppingCart,
HiOutlineSortAscending,
HiOutlineSortDescending,
HiOutlineSparkles,
HiOutlineSpeakerphone,
HiOutlineStar,
HiOutlineStatusOffline,
HiOutlineStatusOnline,
HiOutlineStop,
HiOutlineSun,
HiOutlineSupport,
HiOutlineSwitchHorizontal,
HiOutlineSwitchVertical,
HiOutlineTable,
HiOutlineTag,
HiOutlineTemplate,
HiOutlineTerminal,
HiOutlineThumbDown,
HiOutlineThumbUp,
HiOutlineTicket,
HiOutlineTranslate,
HiOutlineTrash,
HiOutlineTrendingDown,
HiOutlineTrendingUp,
HiOutlineTruck,
HiOutlineUpload,
HiOutlineUserAdd,
HiOutlineUserCircle,
HiOutlineUserGroup,
HiOutlineUserRemove,
HiOutlineUser,
HiOutlineUsers,
HiOutlineVariable,
HiOutlineVideoCamera,
HiOutlineViewBoards,
HiOutlineViewGridAdd,
HiOutlineViewGrid,
HiOutlineViewList,
HiOutlineVolumeOff,
HiOutlineVolumeUp,
HiOutlineWifi,
HiOutlineXCircle,
HiOutlineX,
HiOutlineZoomIn,
HiOutlineZoomOut,
} from "react-icons/hi";

const result = [
{ icon: HiAcademicCap, name: "HiAcademicCap" },
{ icon: HiAdjustments, name: "HiAdjustments" },
{ icon: HiAnnotation, name: "HiAnnotation" },
{ icon: HiArchive, name: "HiArchive" },
{ icon: HiArrowCircleDown, name: "HiArrowCircleDown" },
{ icon: HiArrowCircleLeft, name: "HiArrowCircleLeft" },
{ icon: HiArrowCircleRight, name: "HiArrowCircleRight" },
{ icon: HiArrowCircleUp, name: "HiArrowCircleUp" },
{ icon: HiArrowDown, name: "HiArrowDown" },
{ icon: HiArrowLeft, name: "HiArrowLeft" },
{ icon: HiArrowNarrowDown, name: "HiArrowNarrowDown" },
{ icon: HiArrowNarrowLeft, name: "HiArrowNarrowLeft" },
{ icon: HiArrowNarrowRight, name: "HiArrowNarrowRight" },
{ icon: HiArrowNarrowUp, name: "HiArrowNarrowUp" },
{ icon: HiArrowRight, name: "HiArrowRight" },
{ icon: HiArrowSmDown, name: "HiArrowSmDown" },
{ icon: HiArrowSmLeft, name: "HiArrowSmLeft" },
{ icon: HiArrowSmRight, name: "HiArrowSmRight" },
{ icon: HiArrowSmUp, name: "HiArrowSmUp" },
{ icon: HiArrowUp, name: "HiArrowUp" },
{ icon: HiArrowsExpand, name: "HiArrowsExpand" },
{ icon: HiAtSymbol, name: "HiAtSymbol" },
{ icon: HiBackspace, name: "HiBackspace" },
{ icon: HiBadgeCheck, name: "HiBadgeCheck" },
{ icon: HiBan, name: "HiBan" },
{ icon: HiBeaker, name: "HiBeaker" },
{ icon: HiBell, name: "HiBell" },
{ icon: HiBookOpen, name: "HiBookOpen" },
{ icon: HiBookmarkAlt, name: "HiBookmarkAlt" },
{ icon: HiBookmark, name: "HiBookmark" },
{ icon: HiBriefcase, name: "HiBriefcase" },
{ icon: HiCake, name: "HiCake" },
{ icon: HiCalculator, name: "HiCalculator" },
{ icon: HiCalendar, name: "HiCalendar" },
{ icon: HiCamera, name: "HiCamera" },
{ icon: HiCash, name: "HiCash" },
{ icon: HiChartBar, name: "HiChartBar" },
{ icon: HiChartPie, name: "HiChartPie" },
{ icon: HiChartSquareBar, name: "HiChartSquareBar" },
{ icon: HiChatAlt2, name: "HiChatAlt2" },
{ icon: HiChatAlt, name: "HiChatAlt" },
{ icon: HiChat, name: "HiChat" },
{ icon: HiCheckCircle, name: "HiCheckCircle" },
{ icon: HiCheck, name: "HiCheck" },
{ icon: HiChevronDoubleDown, name: "HiChevronDoubleDown" },
{ icon: HiChevronDoubleLeft, name: "HiChevronDoubleLeft" },
{ icon: HiChevronDoubleRight, name: "HiChevronDoubleRight" },
{ icon: HiChevronDoubleUp, name: "HiChevronDoubleUp" },
{ icon: HiChevronDown, name: "HiChevronDown" },
{ icon: HiChevronLeft, name: "HiChevronLeft" },
{ icon: HiChevronRight, name: "HiChevronRight" },
{ icon: HiChevronUp, name: "HiChevronUp" },
{ icon: HiChip, name: "HiChip" },
{ icon: HiClipboardCheck, name: "HiClipboardCheck" },
{ icon: HiClipboardCopy, name: "HiClipboardCopy" },
{ icon: HiClipboardList, name: "HiClipboardList" },
{ icon: HiClipboard, name: "HiClipboard" },
{ icon: HiClock, name: "HiClock" },
{ icon: HiCloudDownload, name: "HiCloudDownload" },
{ icon: HiCloudUpload, name: "HiCloudUpload" },
{ icon: HiCloud, name: "HiCloud" },
{ icon: HiCode, name: "HiCode" },
{ icon: HiCog, name: "HiCog" },
{ icon: HiCollection, name: "HiCollection" },
{ icon: HiColorSwatch, name: "HiColorSwatch" },
{ icon: HiCreditCard, name: "HiCreditCard" },
{ icon: HiCubeTransparent, name: "HiCubeTransparent" },
{ icon: HiCube, name: "HiCube" },
{ icon: HiCurrencyBangladeshi, name: "HiCurrencyBangladeshi" },
{ icon: HiCurrencyDollar, name: "HiCurrencyDollar" },
{ icon: HiCurrencyEuro, name: "HiCurrencyEuro" },
{ icon: HiCurrencyPound, name: "HiCurrencyPound" },
{ icon: HiCurrencyRupee, name: "HiCurrencyRupee" },
{ icon: HiCurrencyYen, name: "HiCurrencyYen" },
{ icon: HiCursorClick, name: "HiCursorClick" },
{ icon: HiDatabase, name: "HiDatabase" },
{ icon: HiDesktopComputer, name: "HiDesktopComputer" },
{ icon: HiDeviceMobile, name: "HiDeviceMobile" },
{ icon: HiDeviceTablet, name: "HiDeviceTablet" },
{ icon: HiDocumentAdd, name: "HiDocumentAdd" },
{ icon: HiDocumentDownload, name: "HiDocumentDownload" },
{ icon: HiDocumentDuplicate, name: "HiDocumentDuplicate" },
{ icon: HiDocumentRemove, name: "HiDocumentRemove" },
{ icon: HiDocumentReport, name: "HiDocumentReport" },
{ icon: HiDocumentSearch, name: "HiDocumentSearch" },
{ icon: HiDocumentText, name: "HiDocumentText" },
{ icon: HiDocument, name: "HiDocument" },
{ icon: HiDotsCircleHorizontal, name: "HiDotsCircleHorizontal" },
{ icon: HiDotsHorizontal, name: "HiDotsHorizontal" },
{ icon: HiDotsVertical, name: "HiDotsVertical" },
{ icon: HiDownload, name: "HiDownload" },
{ icon: HiDuplicate, name: "HiDuplicate" },
{ icon: HiEmojiHappy, name: "HiEmojiHappy" },
{ icon: HiEmojiSad, name: "HiEmojiSad" },
{ icon: HiExclamationCircle, name: "HiExclamationCircle" },
{ icon: HiExclamation, name: "HiExclamation" },
{ icon: HiExternalLink, name: "HiExternalLink" },
{ icon: HiEyeOff, name: "HiEyeOff" },
{ icon: HiEye, name: "HiEye" },
{ icon: HiFastForward, name: "HiFastForward" },
{ icon: HiFilm, name: "HiFilm" },
{ icon: HiFilter, name: "HiFilter" },
{ icon: HiFingerPrint, name: "HiFingerPrint" },
{ icon: HiFire, name: "HiFire" },
{ icon: HiFlag, name: "HiFlag" },
{ icon: HiFolderAdd, name: "HiFolderAdd" },
{ icon: HiFolderDownload, name: "HiFolderDownload" },
{ icon: HiFolderOpen, name: "HiFolderOpen" },
{ icon: HiFolderRemove, name: "HiFolderRemove" },
{ icon: HiFolder, name: "HiFolder" },
{ icon: HiGift, name: "HiGift" },
{ icon: HiGlobeAlt, name: "HiGlobeAlt" },
{ icon: HiGlobe, name: "HiGlobe" },
{ icon: HiHand, name: "HiHand" },
{ icon: HiHashtag, name: "HiHashtag" },
{ icon: HiHeart, name: "HiHeart" },
{ icon: HiHome, name: "HiHome" },
{ icon: HiIdentification, name: "HiIdentification" },
{ icon: HiInboxIn, name: "HiInboxIn" },
{ icon: HiInbox, name: "HiInbox" },
{ icon: HiInformationCircle, name: "HiInformationCircle" },
{ icon: HiKey, name: "HiKey" },
{ icon: HiLibrary, name: "HiLibrary" },
{ icon: HiLightBulb, name: "HiLightBulb" },
{ icon: HiLightningBolt, name: "HiLightningBolt" },
{ icon: HiLink, name: "HiLink" },
{ icon: HiLocationMarker, name: "HiLocationMarker" },
{ icon: HiLockClosed, name: "HiLockClosed" },
{ icon: HiLockOpen, name: "HiLockOpen" },
{ icon: HiLogin, name: "HiLogin" },
{ icon: HiLogout, name: "HiLogout" },
{ icon: HiMailOpen, name: "HiMailOpen" },
{ icon: HiMail, name: "HiMail" },
{ icon: HiMap, name: "HiMap" },
{ icon: HiMenuAlt1, name: "HiMenuAlt1" },
{ icon: HiMenuAlt2, name: "HiMenuAlt2" },
{ icon: HiMenuAlt3, name: "HiMenuAlt3" },
{ icon: HiMenuAlt4, name: "HiMenuAlt4" },
{ icon: HiMenu, name: "HiMenu" },
{ icon: HiMicrophone, name: "HiMicrophone" },
{ icon: HiMinusCircle, name: "HiMinusCircle" },
{ icon: HiMinusSm, name: "HiMinusSm" },
{ icon: HiMinus, name: "HiMinus" },
{ icon: HiMoon, name: "HiMoon" },
{ icon: HiMusicNote, name: "HiMusicNote" },
{ icon: HiNewspaper, name: "HiNewspaper" },
{ icon: HiOfficeBuilding, name: "HiOfficeBuilding" },
{ icon: HiPaperAirplane, name: "HiPaperAirplane" },
{ icon: HiPaperClip, name: "HiPaperClip" },
{ icon: HiPause, name: "HiPause" },
{ icon: HiPencilAlt, name: "HiPencilAlt" },
{ icon: HiPencil, name: "HiPencil" },
{ icon: HiPhoneIncoming, name: "HiPhoneIncoming" },
{ icon: HiPhoneMissedCall, name: "HiPhoneMissedCall" },
{ icon: HiPhoneOutgoing, name: "HiPhoneOutgoing" },
{ icon: HiPhone, name: "HiPhone" },
{ icon: HiPhotograph, name: "HiPhotograph" },
{ icon: HiPlay, name: "HiPlay" },
{ icon: HiPlusCircle, name: "HiPlusCircle" },
{ icon: HiPlusSm, name: "HiPlusSm" },
{ icon: HiPlus, name: "HiPlus" },
{ icon: HiPresentationChartBar, name: "HiPresentationChartBar" },
{ icon: HiPresentationChartLine, name: "HiPresentationChartLine" },
{ icon: HiPrinter, name: "HiPrinter" },
{ icon: HiPuzzle, name: "HiPuzzle" },
{ icon: HiQrcode, name: "HiQrcode" },
{ icon: HiQuestionMarkCircle, name: "HiQuestionMarkCircle" },
{ icon: HiReceiptRefund, name: "HiReceiptRefund" },
{ icon: HiReceiptTax, name: "HiReceiptTax" },
{ icon: HiRefresh, name: "HiRefresh" },
{ icon: HiReply, name: "HiReply" },
{ icon: HiRewind, name: "HiRewind" },
{ icon: HiRss, name: "HiRss" },
{ icon: HiSaveAs, name: "HiSaveAs" },
{ icon: HiSave, name: "HiSave" },
{ icon: HiScale, name: "HiScale" },
{ icon: HiScissors, name: "HiScissors" },
{ icon: HiSearchCircle, name: "HiSearchCircle" },
{ icon: HiSearch, name: "HiSearch" },
{ icon: HiSelector, name: "HiSelector" },
{ icon: HiServer, name: "HiServer" },
{ icon: HiShare, name: "HiShare" },
{ icon: HiShieldCheck, name: "HiShieldCheck" },
{ icon: HiShieldExclamation, name: "HiShieldExclamation" },
{ icon: HiShoppingBag, name: "HiShoppingBag" },
{ icon: HiShoppingCart, name: "HiShoppingCart" },
{ icon: HiSortAscending, name: "HiSortAscending" },
{ icon: HiSortDescending, name: "HiSortDescending" },
{ icon: HiSparkles, name: "HiSparkles" },
{ icon: HiSpeakerphone, name: "HiSpeakerphone" },
{ icon: HiStar, name: "HiStar" },
{ icon: HiStatusOffline, name: "HiStatusOffline" },
{ icon: HiStatusOnline, name: "HiStatusOnline" },
{ icon: HiStop, name: "HiStop" },
{ icon: HiSun, name: "HiSun" },
{ icon: HiSupport, name: "HiSupport" },
{ icon: HiSwitchHorizontal, name: "HiSwitchHorizontal" },
{ icon: HiSwitchVertical, name: "HiSwitchVertical" },
{ icon: HiTable, name: "HiTable" },
{ icon: HiTag, name: "HiTag" },
{ icon: HiTemplate, name: "HiTemplate" },
{ icon: HiTerminal, name: "HiTerminal" },
{ icon: HiThumbDown, name: "HiThumbDown" },
{ icon: HiThumbUp, name: "HiThumbUp" },
{ icon: HiTicket, name: "HiTicket" },
{ icon: HiTranslate, name: "HiTranslate" },
{ icon: HiTrash, name: "HiTrash" },
{ icon: HiTrendingDown, name: "HiTrendingDown" },
{ icon: HiTrendingUp, name: "HiTrendingUp" },
{ icon: HiTruck, name: "HiTruck" },
{ icon: HiUpload, name: "HiUpload" },
{ icon: HiUserAdd, name: "HiUserAdd" },
{ icon: HiUserCircle, name: "HiUserCircle" },
{ icon: HiUserGroup, name: "HiUserGroup" },
{ icon: HiUserRemove, name: "HiUserRemove" },
{ icon: HiUser, name: "HiUser" },
{ icon: HiUsers, name: "HiUsers" },
{ icon: HiVariable, name: "HiVariable" },
{ icon: HiVideoCamera, name: "HiVideoCamera" },
{ icon: HiViewBoards, name: "HiViewBoards" },
{ icon: HiViewGridAdd, name: "HiViewGridAdd" },
{ icon: HiViewGrid, name: "HiViewGrid" },
{ icon: HiViewList, name: "HiViewList" },
{ icon: HiVolumeOff, name: "HiVolumeOff" },
{ icon: HiVolumeUp, name: "HiVolumeUp" },
{ icon: HiWifi, name: "HiWifi" },
{ icon: HiXCircle, name: "HiXCircle" },
{ icon: HiX, name: "HiX" },
{ icon: HiZoomIn, name: "HiZoomIn" },
{ icon: HiZoomOut, name: "HiZoomOut" },
{ icon: HiOutlineAcademicCap, name: "HiOutlineAcademicCap" },
{ icon: HiOutlineAdjustments, name: "HiOutlineAdjustments" },
{ icon: HiOutlineAnnotation, name: "HiOutlineAnnotation" },
{ icon: HiOutlineArchive, name: "HiOutlineArchive" },
{ icon: HiOutlineArrowCircleDown, name: "HiOutlineArrowCircleDown" },
{ icon: HiOutlineArrowCircleLeft, name: "HiOutlineArrowCircleLeft" },
{ icon: HiOutlineArrowCircleRight, name: "HiOutlineArrowCircleRight" },
{ icon: HiOutlineArrowCircleUp, name: "HiOutlineArrowCircleUp" },
{ icon: HiOutlineArrowDown, name: "HiOutlineArrowDown" },
{ icon: HiOutlineArrowLeft, name: "HiOutlineArrowLeft" },
{ icon: HiOutlineArrowNarrowDown, name: "HiOutlineArrowNarrowDown" },
{ icon: HiOutlineArrowNarrowLeft, name: "HiOutlineArrowNarrowLeft" },
{ icon: HiOutlineArrowNarrowRight, name: "HiOutlineArrowNarrowRight" },
{ icon: HiOutlineArrowNarrowUp, name: "HiOutlineArrowNarrowUp" },
{ icon: HiOutlineArrowRight, name: "HiOutlineArrowRight" },
{ icon: HiOutlineArrowSmDown, name: "HiOutlineArrowSmDown" },
{ icon: HiOutlineArrowSmLeft, name: "HiOutlineArrowSmLeft" },
{ icon: HiOutlineArrowSmRight, name: "HiOutlineArrowSmRight" },
{ icon: HiOutlineArrowSmUp, name: "HiOutlineArrowSmUp" },
{ icon: HiOutlineArrowUp, name: "HiOutlineArrowUp" },
{ icon: HiOutlineArrowsExpand, name: "HiOutlineArrowsExpand" },
{ icon: HiOutlineAtSymbol, name: "HiOutlineAtSymbol" },
{ icon: HiOutlineBackspace, name: "HiOutlineBackspace" },
{ icon: HiOutlineBadgeCheck, name: "HiOutlineBadgeCheck" },
{ icon: HiOutlineBan, name: "HiOutlineBan" },
{ icon: HiOutlineBeaker, name: "HiOutlineBeaker" },
{ icon: HiOutlineBell, name: "HiOutlineBell" },
{ icon: HiOutlineBookOpen, name: "HiOutlineBookOpen" },
{ icon: HiOutlineBookmarkAlt, name: "HiOutlineBookmarkAlt" },
{ icon: HiOutlineBookmark, name: "HiOutlineBookmark" },
{ icon: HiOutlineBriefcase, name: "HiOutlineBriefcase" },
{ icon: HiOutlineCake, name: "HiOutlineCake" },
{ icon: HiOutlineCalculator, name: "HiOutlineCalculator" },
{ icon: HiOutlineCalendar, name: "HiOutlineCalendar" },
{ icon: HiOutlineCamera, name: "HiOutlineCamera" },
{ icon: HiOutlineCash, name: "HiOutlineCash" },
{ icon: HiOutlineChartBar, name: "HiOutlineChartBar" },
{ icon: HiOutlineChartPie, name: "HiOutlineChartPie" },
{ icon: HiOutlineChartSquareBar, name: "HiOutlineChartSquareBar" },
{ icon: HiOutlineChatAlt2, name: "HiOutlineChatAlt2" },
{ icon: HiOutlineChatAlt, name: "HiOutlineChatAlt" },
{ icon: HiOutlineChat, name: "HiOutlineChat" },
{ icon: HiOutlineCheckCircle, name: "HiOutlineCheckCircle" },
{ icon: HiOutlineCheck, name: "HiOutlineCheck" },
{ icon: HiOutlineChevronDoubleDown, name: "HiOutlineChevronDoubleDown" },
{ icon: HiOutlineChevronDoubleLeft, name: "HiOutlineChevronDoubleLeft" },
{ icon: HiOutlineChevronDoubleRight, name: "HiOutlineChevronDoubleRight" },
{ icon: HiOutlineChevronDoubleUp, name: "HiOutlineChevronDoubleUp" },
{ icon: HiOutlineChevronDown, name: "HiOutlineChevronDown" },
{ icon: HiOutlineChevronLeft, name: "HiOutlineChevronLeft" },
{ icon: HiOutlineChevronRight, name: "HiOutlineChevronRight" },
{ icon: HiOutlineChevronUp, name: "HiOutlineChevronUp" },
{ icon: HiOutlineChip, name: "HiOutlineChip" },
{ icon: HiOutlineClipboardCheck, name: "HiOutlineClipboardCheck" },
{ icon: HiOutlineClipboardCopy, name: "HiOutlineClipboardCopy" },
{ icon: HiOutlineClipboardList, name: "HiOutlineClipboardList" },
{ icon: HiOutlineClipboard, name: "HiOutlineClipboard" },
{ icon: HiOutlineClock, name: "HiOutlineClock" },
{ icon: HiOutlineCloudDownload, name: "HiOutlineCloudDownload" },
{ icon: HiOutlineCloudUpload, name: "HiOutlineCloudUpload" },
{ icon: HiOutlineCloud, name: "HiOutlineCloud" },
{ icon: HiOutlineCode, name: "HiOutlineCode" },
{ icon: HiOutlineCog, name: "HiOutlineCog" },
{ icon: HiOutlineCollection, name: "HiOutlineCollection" },
{ icon: HiOutlineColorSwatch, name: "HiOutlineColorSwatch" },
{ icon: HiOutlineCreditCard, name: "HiOutlineCreditCard" },
{ icon: HiOutlineCubeTransparent, name: "HiOutlineCubeTransparent" },
{ icon: HiOutlineCube, name: "HiOutlineCube" },
{ icon: HiOutlineCurrencyBangladeshi, name: "HiOutlineCurrencyBangladeshi" },
{ icon: HiOutlineCurrencyDollar, name: "HiOutlineCurrencyDollar" },
{ icon: HiOutlineCurrencyEuro, name: "HiOutlineCurrencyEuro" },
{ icon: HiOutlineCurrencyPound, name: "HiOutlineCurrencyPound" },
{ icon: HiOutlineCurrencyRupee, name: "HiOutlineCurrencyRupee" },
{ icon: HiOutlineCurrencyYen, name: "HiOutlineCurrencyYen" },
{ icon: HiOutlineCursorClick, name: "HiOutlineCursorClick" },
{ icon: HiOutlineDatabase, name: "HiOutlineDatabase" },
{ icon: HiOutlineDesktopComputer, name: "HiOutlineDesktopComputer" },
{ icon: HiOutlineDeviceMobile, name: "HiOutlineDeviceMobile" },
{ icon: HiOutlineDeviceTablet, name: "HiOutlineDeviceTablet" },
{ icon: HiOutlineDocumentAdd, name: "HiOutlineDocumentAdd" },
{ icon: HiOutlineDocumentDownload, name: "HiOutlineDocumentDownload" },
{ icon: HiOutlineDocumentDuplicate, name: "HiOutlineDocumentDuplicate" },
{ icon: HiOutlineDocumentRemove, name: "HiOutlineDocumentRemove" },
{ icon: HiOutlineDocumentReport, name: "HiOutlineDocumentReport" },
{ icon: HiOutlineDocumentSearch, name: "HiOutlineDocumentSearch" },
{ icon: HiOutlineDocumentText, name: "HiOutlineDocumentText" },
{ icon: HiOutlineDocument, name: "HiOutlineDocument" },
{ icon: HiOutlineDotsCircleHorizontal, name: "HiOutlineDotsCircleHorizontal" },
{ icon: HiOutlineDotsHorizontal, name: "HiOutlineDotsHorizontal" },
{ icon: HiOutlineDotsVertical, name: "HiOutlineDotsVertical" },
{ icon: HiOutlineDownload, name: "HiOutlineDownload" },
{ icon: HiOutlineDuplicate, name: "HiOutlineDuplicate" },
{ icon: HiOutlineEmojiHappy, name: "HiOutlineEmojiHappy" },
{ icon: HiOutlineEmojiSad, name: "HiOutlineEmojiSad" },
{ icon: HiOutlineExclamationCircle, name: "HiOutlineExclamationCircle" },
{ icon: HiOutlineExclamation, name: "HiOutlineExclamation" },
{ icon: HiOutlineExternalLink, name: "HiOutlineExternalLink" },
{ icon: HiOutlineEyeOff, name: "HiOutlineEyeOff" },
{ icon: HiOutlineEye, name: "HiOutlineEye" },
{ icon: HiOutlineFastForward, name: "HiOutlineFastForward" },
{ icon: HiOutlineFilm, name: "HiOutlineFilm" },
{ icon: HiOutlineFilter, name: "HiOutlineFilter" },
{ icon: HiOutlineFingerPrint, name: "HiOutlineFingerPrint" },
{ icon: HiOutlineFire, name: "HiOutlineFire" },
{ icon: HiOutlineFlag, name: "HiOutlineFlag" },
{ icon: HiOutlineFolderAdd, name: "HiOutlineFolderAdd" },
{ icon: HiOutlineFolderDownload, name: "HiOutlineFolderDownload" },
{ icon: HiOutlineFolderOpen, name: "HiOutlineFolderOpen" },
{ icon: HiOutlineFolderRemove, name: "HiOutlineFolderRemove" },
{ icon: HiOutlineFolder, name: "HiOutlineFolder" },
{ icon: HiOutlineGift, name: "HiOutlineGift" },
{ icon: HiOutlineGlobeAlt, name: "HiOutlineGlobeAlt" },
{ icon: HiOutlineGlobe, name: "HiOutlineGlobe" },
{ icon: HiOutlineHand, name: "HiOutlineHand" },
{ icon: HiOutlineHashtag, name: "HiOutlineHashtag" },
{ icon: HiOutlineHeart, name: "HiOutlineHeart" },
{ icon: HiOutlineHome, name: "HiOutlineHome" },
{ icon: HiOutlineIdentification, name: "HiOutlineIdentification" },
{ icon: HiOutlineInboxIn, name: "HiOutlineInboxIn" },
{ icon: HiOutlineInbox, name: "HiOutlineInbox" },
{ icon: HiOutlineInformationCircle, name: "HiOutlineInformationCircle" },
{ icon: HiOutlineKey, name: "HiOutlineKey" },
{ icon: HiOutlineLibrary, name: "HiOutlineLibrary" },
{ icon: HiOutlineLightBulb, name: "HiOutlineLightBulb" },
{ icon: HiOutlineLightningBolt, name: "HiOutlineLightningBolt" },
{ icon: HiOutlineLink, name: "HiOutlineLink" },
{ icon: HiOutlineLocationMarker, name: "HiOutlineLocationMarker" },
{ icon: HiOutlineLockClosed, name: "HiOutlineLockClosed" },
{ icon: HiOutlineLockOpen, name: "HiOutlineLockOpen" },
{ icon: HiOutlineLogin, name: "HiOutlineLogin" },
{ icon: HiOutlineLogout, name: "HiOutlineLogout" },
{ icon: HiOutlineMailOpen, name: "HiOutlineMailOpen" },
{ icon: HiOutlineMail, name: "HiOutlineMail" },
{ icon: HiOutlineMap, name: "HiOutlineMap" },
{ icon: HiOutlineMenuAlt1, name: "HiOutlineMenuAlt1" },
{ icon: HiOutlineMenuAlt2, name: "HiOutlineMenuAlt2" },
{ icon: HiOutlineMenuAlt3, name: "HiOutlineMenuAlt3" },
{ icon: HiOutlineMenuAlt4, name: "HiOutlineMenuAlt4" },
{ icon: HiOutlineMenu, name: "HiOutlineMenu" },
{ icon: HiOutlineMicrophone, name: "HiOutlineMicrophone" },
{ icon: HiOutlineMinusCircle, name: "HiOutlineMinusCircle" },
{ icon: HiOutlineMinusSm, name: "HiOutlineMinusSm" },
{ icon: HiOutlineMinus, name: "HiOutlineMinus" },
{ icon: HiOutlineMoon, name: "HiOutlineMoon" },
{ icon: HiOutlineMusicNote, name: "HiOutlineMusicNote" },
{ icon: HiOutlineNewspaper, name: "HiOutlineNewspaper" },
{ icon: HiOutlineOfficeBuilding, name: "HiOutlineOfficeBuilding" },
{ icon: HiOutlinePaperAirplane, name: "HiOutlinePaperAirplane" },
{ icon: HiOutlinePaperClip, name: "HiOutlinePaperClip" },
{ icon: HiOutlinePause, name: "HiOutlinePause" },
{ icon: HiOutlinePencilAlt, name: "HiOutlinePencilAlt" },
{ icon: HiOutlinePencil, name: "HiOutlinePencil" },
{ icon: HiOutlinePhoneIncoming, name: "HiOutlinePhoneIncoming" },
{ icon: HiOutlinePhoneMissedCall, name: "HiOutlinePhoneMissedCall" },
{ icon: HiOutlinePhoneOutgoing, name: "HiOutlinePhoneOutgoing" },
{ icon: HiOutlinePhone, name: "HiOutlinePhone" },
{ icon: HiOutlinePhotograph, name: "HiOutlinePhotograph" },
{ icon: HiOutlinePlay, name: "HiOutlinePlay" },
{ icon: HiOutlinePlusCircle, name: "HiOutlinePlusCircle" },
{ icon: HiOutlinePlusSm, name: "HiOutlinePlusSm" },
{ icon: HiOutlinePlus, name: "HiOutlinePlus" },
{ icon: HiOutlinePresentationChartBar, name: "HiOutlinePresentationChartBar" },
{ icon: HiOutlinePresentationChartLine, name: "HiOutlinePresentationChartLine" },
{ icon: HiOutlinePrinter, name: "HiOutlinePrinter" },
{ icon: HiOutlinePuzzle, name: "HiOutlinePuzzle" },
{ icon: HiOutlineQrcode, name: "HiOutlineQrcode" },
{ icon: HiOutlineQuestionMarkCircle, name: "HiOutlineQuestionMarkCircle" },
{ icon: HiOutlineReceiptRefund, name: "HiOutlineReceiptRefund" },
{ icon: HiOutlineReceiptTax, name: "HiOutlineReceiptTax" },
{ icon: HiOutlineRefresh, name: "HiOutlineRefresh" },
{ icon: HiOutlineReply, name: "HiOutlineReply" },
{ icon: HiOutlineRewind, name: "HiOutlineRewind" },
{ icon: HiOutlineRss, name: "HiOutlineRss" },
{ icon: HiOutlineSaveAs, name: "HiOutlineSaveAs" },
{ icon: HiOutlineSave, name: "HiOutlineSave" },
{ icon: HiOutlineScale, name: "HiOutlineScale" },
{ icon: HiOutlineScissors, name: "HiOutlineScissors" },
{ icon: HiOutlineSearchCircle, name: "HiOutlineSearchCircle" },
{ icon: HiOutlineSearch, name: "HiOutlineSearch" },
{ icon: HiOutlineSelector, name: "HiOutlineSelector" },
{ icon: HiOutlineServer, name: "HiOutlineServer" },
{ icon: HiOutlineShare, name: "HiOutlineShare" },
{ icon: HiOutlineShieldCheck, name: "HiOutlineShieldCheck" },
{ icon: HiOutlineShieldExclamation, name: "HiOutlineShieldExclamation" },
{ icon: HiOutlineShoppingBag, name: "HiOutlineShoppingBag" },
{ icon: HiOutlineShoppingCart, name: "HiOutlineShoppingCart" },
{ icon: HiOutlineSortAscending, name: "HiOutlineSortAscending" },
{ icon: HiOutlineSortDescending, name: "HiOutlineSortDescending" },
{ icon: HiOutlineSparkles, name: "HiOutlineSparkles" },
{ icon: HiOutlineSpeakerphone, name: "HiOutlineSpeakerphone" },
{ icon: HiOutlineStar, name: "HiOutlineStar" },
{ icon: HiOutlineStatusOffline, name: "HiOutlineStatusOffline" },
{ icon: HiOutlineStatusOnline, name: "HiOutlineStatusOnline" },
{ icon: HiOutlineStop, name: "HiOutlineStop" },
{ icon: HiOutlineSun, name: "HiOutlineSun" },
{ icon: HiOutlineSupport, name: "HiOutlineSupport" },
{ icon: HiOutlineSwitchHorizontal, name: "HiOutlineSwitchHorizontal" },
{ icon: HiOutlineSwitchVertical, name: "HiOutlineSwitchVertical" },
{ icon: HiOutlineTable, name: "HiOutlineTable" },
{ icon: HiOutlineTag, name: "HiOutlineTag" },
{ icon: HiOutlineTemplate, name: "HiOutlineTemplate" },
{ icon: HiOutlineTerminal, name: "HiOutlineTerminal" },
{ icon: HiOutlineThumbDown, name: "HiOutlineThumbDown" },
{ icon: HiOutlineThumbUp, name: "HiOutlineThumbUp" },
{ icon: HiOutlineTicket, name: "HiOutlineTicket" },
{ icon: HiOutlineTranslate, name: "HiOutlineTranslate" },
{ icon: HiOutlineTrash, name: "HiOutlineTrash" },
{ icon: HiOutlineTrendingDown, name: "HiOutlineTrendingDown" },
{ icon: HiOutlineTrendingUp, name: "HiOutlineTrendingUp" },
{ icon: HiOutlineTruck, name: "HiOutlineTruck" },
{ icon: HiOutlineUpload, name: "HiOutlineUpload" },
{ icon: HiOutlineUserAdd, name: "HiOutlineUserAdd" },
{ icon: HiOutlineUserCircle, name: "HiOutlineUserCircle" },
{ icon: HiOutlineUserGroup, name: "HiOutlineUserGroup" },
{ icon: HiOutlineUserRemove, name: "HiOutlineUserRemove" },
{ icon: HiOutlineUser, name: "HiOutlineUser" },
{ icon: HiOutlineUsers, name: "HiOutlineUsers" },
{ icon: HiOutlineVariable, name: "HiOutlineVariable" },
{ icon: HiOutlineVideoCamera, name: "HiOutlineVideoCamera" },
{ icon: HiOutlineViewBoards, name: "HiOutlineViewBoards" },
{ icon: HiOutlineViewGridAdd, name: "HiOutlineViewGridAdd" },
{ icon: HiOutlineViewGrid, name: "HiOutlineViewGrid" },
{ icon: HiOutlineViewList, name: "HiOutlineViewList" },
{ icon: HiOutlineVolumeOff, name: "HiOutlineVolumeOff" },
{ icon: HiOutlineVolumeUp, name: "HiOutlineVolumeUp" },
{ icon: HiOutlineWifi, name: "HiOutlineWifi" },
{ icon: HiOutlineXCircle, name: "HiOutlineXCircle" },
{ icon: HiOutlineX, name: "HiOutlineX" },
{ icon: HiOutlineZoomIn, name: "HiOutlineZoomIn" },
{ icon: HiOutlineZoomOut, name: "HiOutlineZoomOut" },
];

export default result