import {
	HiAcademicCap,
	HiAdjustments,
	HiAnnotation,
	HiArchive,
	HiArrowCircleDown,
	HiArrowCircleLeft,
	HiArrowCircleRight,
	HiArrowCircleUp,
	HiArrowDown,
	HiArrowLeft,
	HiArrowNarrowDown,
	HiArrowNarrowLeft,
	HiArrowNarrowRight,
	HiArrowNarrowUp,
	HiArrowRight,
	HiArrowSmDown,
	HiArrowSmLeft,
	HiArrowSmRight,
	HiArrowSmUp,
	HiArrowUp,
	HiArrowsExpand,
	HiAtSymbol,
	HiBackspace,
	HiBadgeCheck,
	HiBan,
	HiBeaker,
	HiBell,
	HiBookOpen,
	HiBookmarkAlt,
	HiBookmark,
	HiBriefcase,
	HiCake,
	HiCalculator,
	HiCalendar,
	HiCamera,
	HiCash,
	HiChartBar,
	HiChartPie,
	HiChartSquareBar,
	HiChatAlt2,
	HiChatAlt,
	HiChat,
	HiCheckCircle,
	HiCheck,
	HiChevronDoubleDown,
	HiChevronDoubleLeft,
	HiChevronDoubleRight,
	HiChevronDoubleUp,
	HiChevronDown,
	HiChevronLeft,
	HiChevronRight,
	HiChevronUp,
	HiChip,
	HiClipboardCheck,
	HiClipboardCopy,
	HiClipboardList,
	HiClipboard,
	HiClock,
	HiCloudDownload,
	HiCloudUpload,
	HiCloud,
	HiCode,
	HiCog,
	HiCollection,
	HiColorSwatch,
	HiCreditCard,
	HiCubeTransparent,
	HiCube,
	HiCurrencyBangladeshi,
	HiCurrencyDollar,
	HiCurrencyEuro,
	HiCurrencyPound,
	HiCurrencyRupee,
	HiCurrencyYen,
	HiCursorClick,
	HiDatabase,
	HiDesktopComputer,
	HiDeviceMobile,
	HiDeviceTablet,
	HiDocumentAdd,
	HiDocumentDownload,
	HiDocumentDuplicate,
	HiDocumentRemove,
	HiDocumentReport,
	HiDocumentSearch,
	HiDocumentText,
	HiDocument,
	HiDotsCircleHorizontal,
	HiDotsHorizontal,
	HiDotsVertical,
	HiDownload,
	HiDuplicate,
	HiEmojiHappy,
	HiEmojiSad,
	HiExclamationCircle,
	HiExclamation,
	HiExternalLink,
	HiEyeOff,
	HiEye,
	HiFastForward,
	HiFilm,
	HiFilter,
	HiFingerPrint,
	HiFire,
	HiFlag,
	HiFolderAdd,
	HiFolderDownload,
	HiFolderOpen,
	HiFolderRemove,
	HiFolder,
	HiGift,
	HiGlobeAlt,
	HiGlobe,
	HiHand,
	HiHashtag,
	HiHeart,
	HiHome,
	HiIdentification,
	HiInboxIn,
	HiInbox,
	HiInformationCircle,
	HiKey,
	HiLibrary,
	HiLightBulb,
	HiLightningBolt,
	HiLink,
	HiLocationMarker,
	HiLockClosed,
	HiLockOpen,
	HiLogin,
	HiLogout,
	HiMailOpen,
	HiMail,
	HiMap,
	HiMenuAlt1,
	HiMenuAlt2,
	HiMenuAlt3,
	HiMenuAlt4,
	HiMenu,
	HiMicrophone,
	HiMinusCircle,
	HiMinusSm,
	HiMinus,
	HiMoon,
	HiMusicNote,
	HiNewspaper,
	HiOfficeBuilding,
	HiPaperAirplane,
	HiPaperClip,
	HiPause,
	HiPencilAlt,
	HiPencil,
	HiPhoneIncoming,
	HiPhoneMissedCall,
	HiPhoneOutgoing,
	HiPhone,
	HiPhotograph,
	HiPlay,
	HiPlusCircle,
	HiPlusSm,
	HiPlus,
	HiPresentationChartBar,
	HiPresentationChartLine,
	HiPrinter,
	HiPuzzle,
	HiQrcode,
	HiQuestionMarkCircle,
	HiReceiptRefund,
	HiReceiptTax,
	HiRefresh,
	HiReply,
	HiRewind,
	HiRss,
	HiSaveAs,
	HiSave,
	HiScale,
	HiScissors,
	HiSearchCircle,
	HiSearch,
	HiSelector,
	HiServer,
	HiShare,
	HiShieldCheck,
	HiShieldExclamation,
	HiShoppingBag,
	HiShoppingCart,
	HiSortAscending,
	HiSortDescending,
	HiSparkles,
	HiSpeakerphone,
	HiStar,
	HiStatusOffline,
	HiStatusOnline,
	HiStop,
	HiSun,
	HiSupport,
	HiSwitchHorizontal,
	HiSwitchVertical,
	HiTable,
	HiTag,
	HiTemplate,
	HiTerminal,
	HiThumbDown,
	HiThumbUp,
	HiTicket,
	HiTranslate,
	HiTrash,
	HiTrendingDown,
	HiTrendingUp,
	HiTruck,
	HiUpload,
	HiUserAdd,
	HiUserCircle,
	HiUserGroup,
	HiUserRemove,
	HiUser,
	HiUsers,
	HiVariable,
	HiVideoCamera,
	HiViewBoards,
	HiViewGridAdd,
	HiViewGrid,
	HiViewList,
	HiVolumeOff,
	HiVolumeUp,
	HiWifi,
	HiXCircle,
	HiX,
	HiZoomIn,
	HiZoomOut,
	HiOutlineAcademicCap,
	HiOutlineAdjustments,
	HiOutlineAnnotation,
	HiOutlineArchive,
	HiOutlineArrowCircleDown,
	HiOutlineArrowCircleLeft,
	HiOutlineArrowCircleRight,
	HiOutlineArrowCircleUp,
	HiOutlineArrowDown,
	HiOutlineArrowLeft,
	HiOutlineArrowNarrowDown,
	HiOutlineArrowNarrowLeft,
	HiOutlineArrowNarrowRight,
	HiOutlineArrowNarrowUp,
	HiOutlineArrowRight,
	HiOutlineArrowSmDown,
	HiOutlineArrowSmLeft,
	HiOutlineArrowSmRight,
	HiOutlineArrowSmUp,
	HiOutlineArrowUp,
	HiOutlineArrowsExpand,
	HiOutlineAtSymbol,
	HiOutlineBackspace,
	HiOutlineBadgeCheck,
	HiOutlineBan,
	HiOutlineBeaker,
	HiOutlineBell,
	HiOutlineBookOpen,
	HiOutlineBookmarkAlt,
	HiOutlineBookmark,
	HiOutlineBriefcase,
	HiOutlineCake,
	HiOutlineCalculator,
	HiOutlineCalendar,
	HiOutlineCamera,
	HiOutlineCash,
	HiOutlineChartBar,
	HiOutlineChartPie,
	HiOutlineChartSquareBar,
	HiOutlineChatAlt2,
	HiOutlineChatAlt,
	HiOutlineChat,
	HiOutlineCheckCircle,
	HiOutlineCheck,
	HiOutlineChevronDoubleDown,
	HiOutlineChevronDoubleLeft,
	HiOutlineChevronDoubleRight,
	HiOutlineChevronDoubleUp,
	HiOutlineChevronDown,
	HiOutlineChevronLeft,
	HiOutlineChevronRight,
	HiOutlineChevronUp,
	HiOutlineChip,
	HiOutlineClipboardCheck,
	HiOutlineClipboardCopy,
	HiOutlineClipboardList,
	HiOutlineClipboard,
	HiOutlineClock,
	HiOutlineCloudDownload,
	HiOutlineCloudUpload,
	HiOutlineCloud,
	HiOutlineCode,
	HiOutlineCog,
	HiOutlineCollection,
	HiOutlineColorSwatch,
	HiOutlineCreditCard,
	HiOutlineCubeTransparent,
	HiOutlineCube,
	HiOutlineCurrencyBangladeshi,
	HiOutlineCurrencyDollar,
	HiOutlineCurrencyEuro,
	HiOutlineCurrencyPound,
	HiOutlineCurrencyRupee,
	HiOutlineCurrencyYen,
	HiOutlineCursorClick,
	HiOutlineDatabase,
	HiOutlineDesktopComputer,
	HiOutlineDeviceMobile,
	HiOutlineDeviceTablet,
	HiOutlineDocumentAdd,
	HiOutlineDocumentDownload,
	HiOutlineDocumentDuplicate,
	HiOutlineDocumentRemove,
	HiOutlineDocumentReport,
	HiOutlineDocumentSearch,
	HiOutlineDocumentText,
	HiOutlineDocument,
	HiOutlineDotsCircleHorizontal,
	HiOutlineDotsHorizontal,
	HiOutlineDotsVertical,
	HiOutlineDownload,
	HiOutlineDuplicate,
	HiOutlineEmojiHappy,
	HiOutlineEmojiSad,
	HiOutlineExclamationCircle,
	HiOutlineExclamation,
	HiOutlineExternalLink,
	HiOutlineEyeOff,
	HiOutlineEye,
	HiOutlineFastForward,
	HiOutlineFilm,
	HiOutlineFilter,
	HiOutlineFingerPrint,
	HiOutlineFire,
	HiOutlineFlag,
	HiOutlineFolderAdd,
	HiOutlineFolderDownload,
	HiOutlineFolderOpen,
	HiOutlineFolderRemove,
	HiOutlineFolder,
	HiOutlineGift,
	HiOutlineGlobeAlt,
	HiOutlineGlobe,
	HiOutlineHand,
	HiOutlineHashtag,
	HiOutlineHeart,
	HiOutlineHome,
	HiOutlineIdentification,
	HiOutlineInboxIn,
	HiOutlineInbox,
	HiOutlineInformationCircle,
	HiOutlineKey,
	HiOutlineLibrary,
	HiOutlineLightBulb,
	HiOutlineLightningBolt,
	HiOutlineLink,
	HiOutlineLocationMarker,
	HiOutlineLockClosed,
	HiOutlineLockOpen,
	HiOutlineLogin,
	HiOutlineLogout,
	HiOutlineMailOpen,
	HiOutlineMail,
	HiOutlineMap,
	HiOutlineMenuAlt1,
	HiOutlineMenuAlt2,
	HiOutlineMenuAlt3,
	HiOutlineMenuAlt4,
	HiOutlineMenu,
	HiOutlineMicrophone,
	HiOutlineMinusCircle,
	HiOutlineMinusSm,
	HiOutlineMinus,
	HiOutlineMoon,
	HiOutlineMusicNote,
	HiOutlineNewspaper,
	HiOutlineOfficeBuilding,
	HiOutlinePaperAirplane,
	HiOutlinePaperClip,
	HiOutlinePause,
	HiOutlinePencilAlt,
	HiOutlinePencil,
	HiOutlinePhoneIncoming,
	HiOutlinePhoneMissedCall,
	HiOutlinePhoneOutgoing,
	HiOutlinePhone,
	HiOutlinePhotograph,
	HiOutlinePlay,
	HiOutlinePlusCircle,
	HiOutlinePlusSm,
	HiOutlinePlus,
	HiOutlinePresentationChartBar,
	HiOutlinePresentationChartLine,
	HiOutlinePrinter,
	HiOutlinePuzzle,
	HiOutlineQrcode,
	HiOutlineQuestionMarkCircle,
	HiOutlineReceiptRefund,
	HiOutlineReceiptTax,
	HiOutlineRefresh,
	HiOutlineReply,
	HiOutlineRewind,
	HiOutlineRss,
	HiOutlineSaveAs,
	HiOutlineSave,
	HiOutlineScale,
	HiOutlineScissors,
	HiOutlineSearchCircle,
	HiOutlineSearch,
	HiOutlineSelector,
	HiOutlineServer,
	HiOutlineShare,
	HiOutlineShieldCheck,
	HiOutlineShieldExclamation,
	HiOutlineShoppingBag,
	HiOutlineShoppingCart,
	HiOutlineSortAscending,
	HiOutlineSortDescending,
	HiOutlineSparkles,
	HiOutlineSpeakerphone,
	HiOutlineStar,
	HiOutlineStatusOffline,
	HiOutlineStatusOnline,
	HiOutlineStop,
	HiOutlineSun,
	HiOutlineSupport,
	HiOutlineSwitchHorizontal,
	HiOutlineSwitchVertical,
	HiOutlineTable,
	HiOutlineTag,
	HiOutlineTemplate,
	HiOutlineTerminal,
	HiOutlineThumbDown,
	HiOutlineThumbUp,
	HiOutlineTicket,
	HiOutlineTranslate,
	HiOutlineTrash,
	HiOutlineTrendingDown,
	HiOutlineTrendingUp,
	HiOutlineTruck,
	HiOutlineUpload,
	HiOutlineUserAdd,
	HiOutlineUserCircle,
	HiOutlineUserGroup,
	HiOutlineUserRemove,
	HiOutlineUser,
	HiOutlineUsers,
	HiOutlineVariable,
	HiOutlineVideoCamera,
	HiOutlineViewBoards,
	HiOutlineViewGridAdd,
	HiOutlineViewGrid,
	HiOutlineViewList,
	HiOutlineVolumeOff,
	HiOutlineVolumeUp,
	HiOutlineWifi,
	HiOutlineXCircle,
	HiOutlineX,
	HiOutlineZoomIn,
	HiOutlineZoomOut,
} from "react-icons/hi";

const result = [
	{ icon: HiAcademicCap, name: "HiAcademicCap", library: "hi" },
	{ icon: HiAdjustments, name: "HiAdjustments", library: "hi" },
	{ icon: HiAnnotation, name: "HiAnnotation", library: "hi" },
	{ icon: HiArchive, name: "HiArchive", library: "hi" },
	{ icon: HiArrowCircleDown, name: "HiArrowCircleDown", library: "hi" },
	{ icon: HiArrowCircleLeft, name: "HiArrowCircleLeft", library: "hi" },
	{ icon: HiArrowCircleRight, name: "HiArrowCircleRight", library: "hi" },
	{ icon: HiArrowCircleUp, name: "HiArrowCircleUp", library: "hi" },
	{ icon: HiArrowDown, name: "HiArrowDown", library: "hi" },
	{ icon: HiArrowLeft, name: "HiArrowLeft", library: "hi" },
	{ icon: HiArrowNarrowDown, name: "HiArrowNarrowDown", library: "hi" },
	{ icon: HiArrowNarrowLeft, name: "HiArrowNarrowLeft", library: "hi" },
	{ icon: HiArrowNarrowRight, name: "HiArrowNarrowRight", library: "hi" },
	{ icon: HiArrowNarrowUp, name: "HiArrowNarrowUp", library: "hi" },
	{ icon: HiArrowRight, name: "HiArrowRight", library: "hi" },
	{ icon: HiArrowSmDown, name: "HiArrowSmDown", library: "hi" },
	{ icon: HiArrowSmLeft, name: "HiArrowSmLeft", library: "hi" },
	{ icon: HiArrowSmRight, name: "HiArrowSmRight", library: "hi" },
	{ icon: HiArrowSmUp, name: "HiArrowSmUp", library: "hi" },
	{ icon: HiArrowUp, name: "HiArrowUp", library: "hi" },
	{ icon: HiArrowsExpand, name: "HiArrowsExpand", library: "hi" },
	{ icon: HiAtSymbol, name: "HiAtSymbol", library: "hi" },
	{ icon: HiBackspace, name: "HiBackspace", library: "hi" },
	{ icon: HiBadgeCheck, name: "HiBadgeCheck", library: "hi" },
	{ icon: HiBan, name: "HiBan", library: "hi" },
	{ icon: HiBeaker, name: "HiBeaker", library: "hi" },
	{ icon: HiBell, name: "HiBell", library: "hi" },
	{ icon: HiBookOpen, name: "HiBookOpen", library: "hi" },
	{ icon: HiBookmarkAlt, name: "HiBookmarkAlt", library: "hi" },
	{ icon: HiBookmark, name: "HiBookmark", library: "hi" },
	{ icon: HiBriefcase, name: "HiBriefcase", library: "hi" },
	{ icon: HiCake, name: "HiCake", library: "hi" },
	{ icon: HiCalculator, name: "HiCalculator", library: "hi" },
	{ icon: HiCalendar, name: "HiCalendar", library: "hi" },
	{ icon: HiCamera, name: "HiCamera", library: "hi" },
	{ icon: HiCash, name: "HiCash", library: "hi" },
	{ icon: HiChartBar, name: "HiChartBar", library: "hi" },
	{ icon: HiChartPie, name: "HiChartPie", library: "hi" },
	{ icon: HiChartSquareBar, name: "HiChartSquareBar", library: "hi" },
	{ icon: HiChatAlt2, name: "HiChatAlt2", library: "hi" },
	{ icon: HiChatAlt, name: "HiChatAlt", library: "hi" },
	{ icon: HiChat, name: "HiChat", library: "hi" },
	{ icon: HiCheckCircle, name: "HiCheckCircle", library: "hi" },
	{ icon: HiCheck, name: "HiCheck", library: "hi" },
	{ icon: HiChevronDoubleDown, name: "HiChevronDoubleDown", library: "hi" },
	{ icon: HiChevronDoubleLeft, name: "HiChevronDoubleLeft", library: "hi" },
	{ icon: HiChevronDoubleRight, name: "HiChevronDoubleRight", library: "hi" },
	{ icon: HiChevronDoubleUp, name: "HiChevronDoubleUp", library: "hi" },
	{ icon: HiChevronDown, name: "HiChevronDown", library: "hi" },
	{ icon: HiChevronLeft, name: "HiChevronLeft", library: "hi" },
	{ icon: HiChevronRight, name: "HiChevronRight", library: "hi" },
	{ icon: HiChevronUp, name: "HiChevronUp", library: "hi" },
	{ icon: HiChip, name: "HiChip", library: "hi" },
	{ icon: HiClipboardCheck, name: "HiClipboardCheck", library: "hi" },
	{ icon: HiClipboardCopy, name: "HiClipboardCopy", library: "hi" },
	{ icon: HiClipboardList, name: "HiClipboardList", library: "hi" },
	{ icon: HiClipboard, name: "HiClipboard", library: "hi" },
	{ icon: HiClock, name: "HiClock", library: "hi" },
	{ icon: HiCloudDownload, name: "HiCloudDownload", library: "hi" },
	{ icon: HiCloudUpload, name: "HiCloudUpload", library: "hi" },
	{ icon: HiCloud, name: "HiCloud", library: "hi" },
	{ icon: HiCode, name: "HiCode", library: "hi" },
	{ icon: HiCog, name: "HiCog", library: "hi" },
	{ icon: HiCollection, name: "HiCollection", library: "hi" },
	{ icon: HiColorSwatch, name: "HiColorSwatch", library: "hi" },
	{ icon: HiCreditCard, name: "HiCreditCard", library: "hi" },
	{ icon: HiCubeTransparent, name: "HiCubeTransparent", library: "hi" },
	{ icon: HiCube, name: "HiCube", library: "hi" },
	{ icon: HiCurrencyBangladeshi, name: "HiCurrencyBangladeshi", library: "hi" },
	{ icon: HiCurrencyDollar, name: "HiCurrencyDollar", library: "hi" },
	{ icon: HiCurrencyEuro, name: "HiCurrencyEuro", library: "hi" },
	{ icon: HiCurrencyPound, name: "HiCurrencyPound", library: "hi" },
	{ icon: HiCurrencyRupee, name: "HiCurrencyRupee", library: "hi" },
	{ icon: HiCurrencyYen, name: "HiCurrencyYen", library: "hi" },
	{ icon: HiCursorClick, name: "HiCursorClick", library: "hi" },
	{ icon: HiDatabase, name: "HiDatabase", library: "hi" },
	{ icon: HiDesktopComputer, name: "HiDesktopComputer", library: "hi" },
	{ icon: HiDeviceMobile, name: "HiDeviceMobile", library: "hi" },
	{ icon: HiDeviceTablet, name: "HiDeviceTablet", library: "hi" },
	{ icon: HiDocumentAdd, name: "HiDocumentAdd", library: "hi" },
	{ icon: HiDocumentDownload, name: "HiDocumentDownload", library: "hi" },
	{ icon: HiDocumentDuplicate, name: "HiDocumentDuplicate", library: "hi" },
	{ icon: HiDocumentRemove, name: "HiDocumentRemove", library: "hi" },
	{ icon: HiDocumentReport, name: "HiDocumentReport", library: "hi" },
	{ icon: HiDocumentSearch, name: "HiDocumentSearch", library: "hi" },
	{ icon: HiDocumentText, name: "HiDocumentText", library: "hi" },
	{ icon: HiDocument, name: "HiDocument", library: "hi" },
	{ icon: HiDotsCircleHorizontal, name: "HiDotsCircleHorizontal", library: "hi" },
	{ icon: HiDotsHorizontal, name: "HiDotsHorizontal", library: "hi" },
	{ icon: HiDotsVertical, name: "HiDotsVertical", library: "hi" },
	{ icon: HiDownload, name: "HiDownload", library: "hi" },
	{ icon: HiDuplicate, name: "HiDuplicate", library: "hi" },
	{ icon: HiEmojiHappy, name: "HiEmojiHappy", library: "hi" },
	{ icon: HiEmojiSad, name: "HiEmojiSad", library: "hi" },
	{ icon: HiExclamationCircle, name: "HiExclamationCircle", library: "hi" },
	{ icon: HiExclamation, name: "HiExclamation", library: "hi" },
	{ icon: HiExternalLink, name: "HiExternalLink", library: "hi" },
	{ icon: HiEyeOff, name: "HiEyeOff", library: "hi" },
	{ icon: HiEye, name: "HiEye", library: "hi" },
	{ icon: HiFastForward, name: "HiFastForward", library: "hi" },
	{ icon: HiFilm, name: "HiFilm", library: "hi" },
	{ icon: HiFilter, name: "HiFilter", library: "hi" },
	{ icon: HiFingerPrint, name: "HiFingerPrint", library: "hi" },
	{ icon: HiFire, name: "HiFire", library: "hi" },
	{ icon: HiFlag, name: "HiFlag", library: "hi" },
	{ icon: HiFolderAdd, name: "HiFolderAdd", library: "hi" },
	{ icon: HiFolderDownload, name: "HiFolderDownload", library: "hi" },
	{ icon: HiFolderOpen, name: "HiFolderOpen", library: "hi" },
	{ icon: HiFolderRemove, name: "HiFolderRemove", library: "hi" },
	{ icon: HiFolder, name: "HiFolder", library: "hi" },
	{ icon: HiGift, name: "HiGift", library: "hi" },
	{ icon: HiGlobeAlt, name: "HiGlobeAlt", library: "hi" },
	{ icon: HiGlobe, name: "HiGlobe", library: "hi" },
	{ icon: HiHand, name: "HiHand", library: "hi" },
	{ icon: HiHashtag, name: "HiHashtag", library: "hi" },
	{ icon: HiHeart, name: "HiHeart", library: "hi" },
	{ icon: HiHome, name: "HiHome", library: "hi" },
	{ icon: HiIdentification, name: "HiIdentification", library: "hi" },
	{ icon: HiInboxIn, name: "HiInboxIn", library: "hi" },
	{ icon: HiInbox, name: "HiInbox", library: "hi" },
	{ icon: HiInformationCircle, name: "HiInformationCircle", library: "hi" },
	{ icon: HiKey, name: "HiKey", library: "hi" },
	{ icon: HiLibrary, name: "HiLibrary", library: "hi" },
	{ icon: HiLightBulb, name: "HiLightBulb", library: "hi" },
	{ icon: HiLightningBolt, name: "HiLightningBolt", library: "hi" },
	{ icon: HiLink, name: "HiLink", library: "hi" },
	{ icon: HiLocationMarker, name: "HiLocationMarker", library: "hi" },
	{ icon: HiLockClosed, name: "HiLockClosed", library: "hi" },
	{ icon: HiLockOpen, name: "HiLockOpen", library: "hi" },
	{ icon: HiLogin, name: "HiLogin", library: "hi" },
	{ icon: HiLogout, name: "HiLogout", library: "hi" },
	{ icon: HiMailOpen, name: "HiMailOpen", library: "hi" },
	{ icon: HiMail, name: "HiMail", library: "hi" },
	{ icon: HiMap, name: "HiMap", library: "hi" },
	{ icon: HiMenuAlt1, name: "HiMenuAlt1", library: "hi" },
	{ icon: HiMenuAlt2, name: "HiMenuAlt2", library: "hi" },
	{ icon: HiMenuAlt3, name: "HiMenuAlt3", library: "hi" },
	{ icon: HiMenuAlt4, name: "HiMenuAlt4", library: "hi" },
	{ icon: HiMenu, name: "HiMenu", library: "hi" },
	{ icon: HiMicrophone, name: "HiMicrophone", library: "hi" },
	{ icon: HiMinusCircle, name: "HiMinusCircle", library: "hi" },
	{ icon: HiMinusSm, name: "HiMinusSm", library: "hi" },
	{ icon: HiMinus, name: "HiMinus", library: "hi" },
	{ icon: HiMoon, name: "HiMoon", library: "hi" },
	{ icon: HiMusicNote, name: "HiMusicNote", library: "hi" },
	{ icon: HiNewspaper, name: "HiNewspaper", library: "hi" },
	{ icon: HiOfficeBuilding, name: "HiOfficeBuilding", library: "hi" },
	{ icon: HiPaperAirplane, name: "HiPaperAirplane", library: "hi" },
	{ icon: HiPaperClip, name: "HiPaperClip", library: "hi" },
	{ icon: HiPause, name: "HiPause", library: "hi" },
	{ icon: HiPencilAlt, name: "HiPencilAlt", library: "hi" },
	{ icon: HiPencil, name: "HiPencil", library: "hi" },
	{ icon: HiPhoneIncoming, name: "HiPhoneIncoming", library: "hi" },
	{ icon: HiPhoneMissedCall, name: "HiPhoneMissedCall", library: "hi" },
	{ icon: HiPhoneOutgoing, name: "HiPhoneOutgoing", library: "hi" },
	{ icon: HiPhone, name: "HiPhone", library: "hi" },
	{ icon: HiPhotograph, name: "HiPhotograph", library: "hi" },
	{ icon: HiPlay, name: "HiPlay", library: "hi" },
	{ icon: HiPlusCircle, name: "HiPlusCircle", library: "hi" },
	{ icon: HiPlusSm, name: "HiPlusSm", library: "hi" },
	{ icon: HiPlus, name: "HiPlus", library: "hi" },
	{ icon: HiPresentationChartBar, name: "HiPresentationChartBar", library: "hi" },
	{ icon: HiPresentationChartLine, name: "HiPresentationChartLine", library: "hi" },
	{ icon: HiPrinter, name: "HiPrinter", library: "hi" },
	{ icon: HiPuzzle, name: "HiPuzzle", library: "hi" },
	{ icon: HiQrcode, name: "HiQrcode", library: "hi" },
	{ icon: HiQuestionMarkCircle, name: "HiQuestionMarkCircle", library: "hi" },
	{ icon: HiReceiptRefund, name: "HiReceiptRefund", library: "hi" },
	{ icon: HiReceiptTax, name: "HiReceiptTax", library: "hi" },
	{ icon: HiRefresh, name: "HiRefresh", library: "hi" },
	{ icon: HiReply, name: "HiReply", library: "hi" },
	{ icon: HiRewind, name: "HiRewind", library: "hi" },
	{ icon: HiRss, name: "HiRss", library: "hi" },
	{ icon: HiSaveAs, name: "HiSaveAs", library: "hi" },
	{ icon: HiSave, name: "HiSave", library: "hi" },
	{ icon: HiScale, name: "HiScale", library: "hi" },
	{ icon: HiScissors, name: "HiScissors", library: "hi" },
	{ icon: HiSearchCircle, name: "HiSearchCircle", library: "hi" },
	{ icon: HiSearch, name: "HiSearch", library: "hi" },
	{ icon: HiSelector, name: "HiSelector", library: "hi" },
	{ icon: HiServer, name: "HiServer", library: "hi" },
	{ icon: HiShare, name: "HiShare", library: "hi" },
	{ icon: HiShieldCheck, name: "HiShieldCheck", library: "hi" },
	{ icon: HiShieldExclamation, name: "HiShieldExclamation", library: "hi" },
	{ icon: HiShoppingBag, name: "HiShoppingBag", library: "hi" },
	{ icon: HiShoppingCart, name: "HiShoppingCart", library: "hi" },
	{ icon: HiSortAscending, name: "HiSortAscending", library: "hi" },
	{ icon: HiSortDescending, name: "HiSortDescending", library: "hi" },
	{ icon: HiSparkles, name: "HiSparkles", library: "hi" },
	{ icon: HiSpeakerphone, name: "HiSpeakerphone", library: "hi" },
	{ icon: HiStar, name: "HiStar", library: "hi" },
	{ icon: HiStatusOffline, name: "HiStatusOffline", library: "hi" },
	{ icon: HiStatusOnline, name: "HiStatusOnline", library: "hi" },
	{ icon: HiStop, name: "HiStop", library: "hi" },
	{ icon: HiSun, name: "HiSun", library: "hi" },
	{ icon: HiSupport, name: "HiSupport", library: "hi" },
	{ icon: HiSwitchHorizontal, name: "HiSwitchHorizontal", library: "hi" },
	{ icon: HiSwitchVertical, name: "HiSwitchVertical", library: "hi" },
	{ icon: HiTable, name: "HiTable", library: "hi" },
	{ icon: HiTag, name: "HiTag", library: "hi" },
	{ icon: HiTemplate, name: "HiTemplate", library: "hi" },
	{ icon: HiTerminal, name: "HiTerminal", library: "hi" },
	{ icon: HiThumbDown, name: "HiThumbDown", library: "hi" },
	{ icon: HiThumbUp, name: "HiThumbUp", library: "hi" },
	{ icon: HiTicket, name: "HiTicket", library: "hi" },
	{ icon: HiTranslate, name: "HiTranslate", library: "hi" },
	{ icon: HiTrash, name: "HiTrash", library: "hi" },
	{ icon: HiTrendingDown, name: "HiTrendingDown", library: "hi" },
	{ icon: HiTrendingUp, name: "HiTrendingUp", library: "hi" },
	{ icon: HiTruck, name: "HiTruck", library: "hi" },
	{ icon: HiUpload, name: "HiUpload", library: "hi" },
	{ icon: HiUserAdd, name: "HiUserAdd", library: "hi" },
	{ icon: HiUserCircle, name: "HiUserCircle", library: "hi" },
	{ icon: HiUserGroup, name: "HiUserGroup", library: "hi" },
	{ icon: HiUserRemove, name: "HiUserRemove", library: "hi" },
	{ icon: HiUser, name: "HiUser", library: "hi" },
	{ icon: HiUsers, name: "HiUsers", library: "hi" },
	{ icon: HiVariable, name: "HiVariable", library: "hi" },
	{ icon: HiVideoCamera, name: "HiVideoCamera", library: "hi" },
	{ icon: HiViewBoards, name: "HiViewBoards", library: "hi" },
	{ icon: HiViewGridAdd, name: "HiViewGridAdd", library: "hi" },
	{ icon: HiViewGrid, name: "HiViewGrid", library: "hi" },
	{ icon: HiViewList, name: "HiViewList", library: "hi" },
	{ icon: HiVolumeOff, name: "HiVolumeOff", library: "hi" },
	{ icon: HiVolumeUp, name: "HiVolumeUp", library: "hi" },
	{ icon: HiWifi, name: "HiWifi", library: "hi" },
	{ icon: HiXCircle, name: "HiXCircle", library: "hi" },
	{ icon: HiX, name: "HiX", library: "hi" },
	{ icon: HiZoomIn, name: "HiZoomIn", library: "hi" },
	{ icon: HiZoomOut, name: "HiZoomOut", library: "hi" },
	{ icon: HiOutlineAcademicCap, name: "HiOutlineAcademicCap", library: "hi" },
	{ icon: HiOutlineAdjustments, name: "HiOutlineAdjustments", library: "hi" },
	{ icon: HiOutlineAnnotation, name: "HiOutlineAnnotation", library: "hi" },
	{ icon: HiOutlineArchive, name: "HiOutlineArchive", library: "hi" },
	{ icon: HiOutlineArrowCircleDown, name: "HiOutlineArrowCircleDown", library: "hi" },
	{ icon: HiOutlineArrowCircleLeft, name: "HiOutlineArrowCircleLeft", library: "hi" },
	{ icon: HiOutlineArrowCircleRight, name: "HiOutlineArrowCircleRight", library: "hi" },
	{ icon: HiOutlineArrowCircleUp, name: "HiOutlineArrowCircleUp", library: "hi" },
	{ icon: HiOutlineArrowDown, name: "HiOutlineArrowDown", library: "hi" },
	{ icon: HiOutlineArrowLeft, name: "HiOutlineArrowLeft", library: "hi" },
	{ icon: HiOutlineArrowNarrowDown, name: "HiOutlineArrowNarrowDown", library: "hi" },
	{ icon: HiOutlineArrowNarrowLeft, name: "HiOutlineArrowNarrowLeft", library: "hi" },
	{ icon: HiOutlineArrowNarrowRight, name: "HiOutlineArrowNarrowRight", library: "hi" },
	{ icon: HiOutlineArrowNarrowUp, name: "HiOutlineArrowNarrowUp", library: "hi" },
	{ icon: HiOutlineArrowRight, name: "HiOutlineArrowRight", library: "hi" },
	{ icon: HiOutlineArrowSmDown, name: "HiOutlineArrowSmDown", library: "hi" },
	{ icon: HiOutlineArrowSmLeft, name: "HiOutlineArrowSmLeft", library: "hi" },
	{ icon: HiOutlineArrowSmRight, name: "HiOutlineArrowSmRight", library: "hi" },
	{ icon: HiOutlineArrowSmUp, name: "HiOutlineArrowSmUp", library: "hi" },
	{ icon: HiOutlineArrowUp, name: "HiOutlineArrowUp", library: "hi" },
	{ icon: HiOutlineArrowsExpand, name: "HiOutlineArrowsExpand", library: "hi" },
	{ icon: HiOutlineAtSymbol, name: "HiOutlineAtSymbol", library: "hi" },
	{ icon: HiOutlineBackspace, name: "HiOutlineBackspace", library: "hi" },
	{ icon: HiOutlineBadgeCheck, name: "HiOutlineBadgeCheck", library: "hi" },
	{ icon: HiOutlineBan, name: "HiOutlineBan", library: "hi" },
	{ icon: HiOutlineBeaker, name: "HiOutlineBeaker", library: "hi" },
	{ icon: HiOutlineBell, name: "HiOutlineBell", library: "hi" },
	{ icon: HiOutlineBookOpen, name: "HiOutlineBookOpen", library: "hi" },
	{ icon: HiOutlineBookmarkAlt, name: "HiOutlineBookmarkAlt", library: "hi" },
	{ icon: HiOutlineBookmark, name: "HiOutlineBookmark", library: "hi" },
	{ icon: HiOutlineBriefcase, name: "HiOutlineBriefcase", library: "hi" },
	{ icon: HiOutlineCake, name: "HiOutlineCake", library: "hi" },
	{ icon: HiOutlineCalculator, name: "HiOutlineCalculator", library: "hi" },
	{ icon: HiOutlineCalendar, name: "HiOutlineCalendar", library: "hi" },
	{ icon: HiOutlineCamera, name: "HiOutlineCamera", library: "hi" },
	{ icon: HiOutlineCash, name: "HiOutlineCash", library: "hi" },
	{ icon: HiOutlineChartBar, name: "HiOutlineChartBar", library: "hi" },
	{ icon: HiOutlineChartPie, name: "HiOutlineChartPie", library: "hi" },
	{ icon: HiOutlineChartSquareBar, name: "HiOutlineChartSquareBar", library: "hi" },
	{ icon: HiOutlineChatAlt2, name: "HiOutlineChatAlt2", library: "hi" },
	{ icon: HiOutlineChatAlt, name: "HiOutlineChatAlt", library: "hi" },
	{ icon: HiOutlineChat, name: "HiOutlineChat", library: "hi" },
	{ icon: HiOutlineCheckCircle, name: "HiOutlineCheckCircle", library: "hi" },
	{ icon: HiOutlineCheck, name: "HiOutlineCheck", library: "hi" },
	{
		icon: HiOutlineChevronDoubleDown,
		name: "HiOutlineChevronDoubleDown",
		library: "hi",
	},
	{
		icon: HiOutlineChevronDoubleLeft,
		name: "HiOutlineChevronDoubleLeft",
		library: "hi",
	},
	{
		icon: HiOutlineChevronDoubleRight,
		name: "HiOutlineChevronDoubleRight",
		library: "hi",
	},
	{ icon: HiOutlineChevronDoubleUp, name: "HiOutlineChevronDoubleUp", library: "hi" },
	{ icon: HiOutlineChevronDown, name: "HiOutlineChevronDown", library: "hi" },
	{ icon: HiOutlineChevronLeft, name: "HiOutlineChevronLeft", library: "hi" },
	{ icon: HiOutlineChevronRight, name: "HiOutlineChevronRight", library: "hi" },
	{ icon: HiOutlineChevronUp, name: "HiOutlineChevronUp", library: "hi" },
	{ icon: HiOutlineChip, name: "HiOutlineChip", library: "hi" },
	{ icon: HiOutlineClipboardCheck, name: "HiOutlineClipboardCheck", library: "hi" },
	{ icon: HiOutlineClipboardCopy, name: "HiOutlineClipboardCopy", library: "hi" },
	{ icon: HiOutlineClipboardList, name: "HiOutlineClipboardList", library: "hi" },
	{ icon: HiOutlineClipboard, name: "HiOutlineClipboard", library: "hi" },
	{ icon: HiOutlineClock, name: "HiOutlineClock", library: "hi" },
	{ icon: HiOutlineCloudDownload, name: "HiOutlineCloudDownload", library: "hi" },
	{ icon: HiOutlineCloudUpload, name: "HiOutlineCloudUpload", library: "hi" },
	{ icon: HiOutlineCloud, name: "HiOutlineCloud", library: "hi" },
	{ icon: HiOutlineCode, name: "HiOutlineCode", library: "hi" },
	{ icon: HiOutlineCog, name: "HiOutlineCog", library: "hi" },
	{ icon: HiOutlineCollection, name: "HiOutlineCollection", library: "hi" },
	{ icon: HiOutlineColorSwatch, name: "HiOutlineColorSwatch", library: "hi" },
	{ icon: HiOutlineCreditCard, name: "HiOutlineCreditCard", library: "hi" },
	{ icon: HiOutlineCubeTransparent, name: "HiOutlineCubeTransparent", library: "hi" },
	{ icon: HiOutlineCube, name: "HiOutlineCube", library: "hi" },
	{
		icon: HiOutlineCurrencyBangladeshi,
		name: "HiOutlineCurrencyBangladeshi",
		library: "hi",
	},
	{ icon: HiOutlineCurrencyDollar, name: "HiOutlineCurrencyDollar", library: "hi" },
	{ icon: HiOutlineCurrencyEuro, name: "HiOutlineCurrencyEuro", library: "hi" },
	{ icon: HiOutlineCurrencyPound, name: "HiOutlineCurrencyPound", library: "hi" },
	{ icon: HiOutlineCurrencyRupee, name: "HiOutlineCurrencyRupee", library: "hi" },
	{ icon: HiOutlineCurrencyYen, name: "HiOutlineCurrencyYen", library: "hi" },
	{ icon: HiOutlineCursorClick, name: "HiOutlineCursorClick", library: "hi" },
	{ icon: HiOutlineDatabase, name: "HiOutlineDatabase", library: "hi" },
	{ icon: HiOutlineDesktopComputer, name: "HiOutlineDesktopComputer", library: "hi" },
	{ icon: HiOutlineDeviceMobile, name: "HiOutlineDeviceMobile", library: "hi" },
	{ icon: HiOutlineDeviceTablet, name: "HiOutlineDeviceTablet", library: "hi" },
	{ icon: HiOutlineDocumentAdd, name: "HiOutlineDocumentAdd", library: "hi" },
	{ icon: HiOutlineDocumentDownload, name: "HiOutlineDocumentDownload", library: "hi" },
	{
		icon: HiOutlineDocumentDuplicate,
		name: "HiOutlineDocumentDuplicate",
		library: "hi",
	},
	{ icon: HiOutlineDocumentRemove, name: "HiOutlineDocumentRemove", library: "hi" },
	{ icon: HiOutlineDocumentReport, name: "HiOutlineDocumentReport", library: "hi" },
	{ icon: HiOutlineDocumentSearch, name: "HiOutlineDocumentSearch", library: "hi" },
	{ icon: HiOutlineDocumentText, name: "HiOutlineDocumentText", library: "hi" },
	{ icon: HiOutlineDocument, name: "HiOutlineDocument", library: "hi" },
	{
		icon: HiOutlineDotsCircleHorizontal,
		name: "HiOutlineDotsCircleHorizontal",
		library: "hi",
	},
	{ icon: HiOutlineDotsHorizontal, name: "HiOutlineDotsHorizontal", library: "hi" },
	{ icon: HiOutlineDotsVertical, name: "HiOutlineDotsVertical", library: "hi" },
	{ icon: HiOutlineDownload, name: "HiOutlineDownload", library: "hi" },
	{ icon: HiOutlineDuplicate, name: "HiOutlineDuplicate", library: "hi" },
	{ icon: HiOutlineEmojiHappy, name: "HiOutlineEmojiHappy", library: "hi" },
	{ icon: HiOutlineEmojiSad, name: "HiOutlineEmojiSad", library: "hi" },
	{
		icon: HiOutlineExclamationCircle,
		name: "HiOutlineExclamationCircle",
		library: "hi",
	},
	{ icon: HiOutlineExclamation, name: "HiOutlineExclamation", library: "hi" },
	{ icon: HiOutlineExternalLink, name: "HiOutlineExternalLink", library: "hi" },
	{ icon: HiOutlineEyeOff, name: "HiOutlineEyeOff", library: "hi" },
	{ icon: HiOutlineEye, name: "HiOutlineEye", library: "hi" },
	{ icon: HiOutlineFastForward, name: "HiOutlineFastForward", library: "hi" },
	{ icon: HiOutlineFilm, name: "HiOutlineFilm", library: "hi" },
	{ icon: HiOutlineFilter, name: "HiOutlineFilter", library: "hi" },
	{ icon: HiOutlineFingerPrint, name: "HiOutlineFingerPrint", library: "hi" },
	{ icon: HiOutlineFire, name: "HiOutlineFire", library: "hi" },
	{ icon: HiOutlineFlag, name: "HiOutlineFlag", library: "hi" },
	{ icon: HiOutlineFolderAdd, name: "HiOutlineFolderAdd", library: "hi" },
	{ icon: HiOutlineFolderDownload, name: "HiOutlineFolderDownload", library: "hi" },
	{ icon: HiOutlineFolderOpen, name: "HiOutlineFolderOpen", library: "hi" },
	{ icon: HiOutlineFolderRemove, name: "HiOutlineFolderRemove", library: "hi" },
	{ icon: HiOutlineFolder, name: "HiOutlineFolder", library: "hi" },
	{ icon: HiOutlineGift, name: "HiOutlineGift", library: "hi" },
	{ icon: HiOutlineGlobeAlt, name: "HiOutlineGlobeAlt", library: "hi" },
	{ icon: HiOutlineGlobe, name: "HiOutlineGlobe", library: "hi" },
	{ icon: HiOutlineHand, name: "HiOutlineHand", library: "hi" },
	{ icon: HiOutlineHashtag, name: "HiOutlineHashtag", library: "hi" },
	{ icon: HiOutlineHeart, name: "HiOutlineHeart", library: "hi" },
	{ icon: HiOutlineHome, name: "HiOutlineHome", library: "hi" },
	{ icon: HiOutlineIdentification, name: "HiOutlineIdentification", library: "hi" },
	{ icon: HiOutlineInboxIn, name: "HiOutlineInboxIn", library: "hi" },
	{ icon: HiOutlineInbox, name: "HiOutlineInbox", library: "hi" },
	{
		icon: HiOutlineInformationCircle,
		name: "HiOutlineInformationCircle",
		library: "hi",
	},
	{ icon: HiOutlineKey, name: "HiOutlineKey", library: "hi" },
	{ icon: HiOutlineLibrary, name: "HiOutlineLibrary", library: "hi" },
	{ icon: HiOutlineLightBulb, name: "HiOutlineLightBulb", library: "hi" },
	{ icon: HiOutlineLightningBolt, name: "HiOutlineLightningBolt", library: "hi" },
	{ icon: HiOutlineLink, name: "HiOutlineLink", library: "hi" },
	{ icon: HiOutlineLocationMarker, name: "HiOutlineLocationMarker", library: "hi" },
	{ icon: HiOutlineLockClosed, name: "HiOutlineLockClosed", library: "hi" },
	{ icon: HiOutlineLockOpen, name: "HiOutlineLockOpen", library: "hi" },
	{ icon: HiOutlineLogin, name: "HiOutlineLogin", library: "hi" },
	{ icon: HiOutlineLogout, name: "HiOutlineLogout", library: "hi" },
	{ icon: HiOutlineMailOpen, name: "HiOutlineMailOpen", library: "hi" },
	{ icon: HiOutlineMail, name: "HiOutlineMail", library: "hi" },
	{ icon: HiOutlineMap, name: "HiOutlineMap", library: "hi" },
	{ icon: HiOutlineMenuAlt1, name: "HiOutlineMenuAlt1", library: "hi" },
	{ icon: HiOutlineMenuAlt2, name: "HiOutlineMenuAlt2", library: "hi" },
	{ icon: HiOutlineMenuAlt3, name: "HiOutlineMenuAlt3", library: "hi" },
	{ icon: HiOutlineMenuAlt4, name: "HiOutlineMenuAlt4", library: "hi" },
	{ icon: HiOutlineMenu, name: "HiOutlineMenu", library: "hi" },
	{ icon: HiOutlineMicrophone, name: "HiOutlineMicrophone", library: "hi" },
	{ icon: HiOutlineMinusCircle, name: "HiOutlineMinusCircle", library: "hi" },
	{ icon: HiOutlineMinusSm, name: "HiOutlineMinusSm", library: "hi" },
	{ icon: HiOutlineMinus, name: "HiOutlineMinus", library: "hi" },
	{ icon: HiOutlineMoon, name: "HiOutlineMoon", library: "hi" },
	{ icon: HiOutlineMusicNote, name: "HiOutlineMusicNote", library: "hi" },
	{ icon: HiOutlineNewspaper, name: "HiOutlineNewspaper", library: "hi" },
	{ icon: HiOutlineOfficeBuilding, name: "HiOutlineOfficeBuilding", library: "hi" },
	{ icon: HiOutlinePaperAirplane, name: "HiOutlinePaperAirplane", library: "hi" },
	{ icon: HiOutlinePaperClip, name: "HiOutlinePaperClip", library: "hi" },
	{ icon: HiOutlinePause, name: "HiOutlinePause", library: "hi" },
	{ icon: HiOutlinePencilAlt, name: "HiOutlinePencilAlt", library: "hi" },
	{ icon: HiOutlinePencil, name: "HiOutlinePencil", library: "hi" },
	{ icon: HiOutlinePhoneIncoming, name: "HiOutlinePhoneIncoming", library: "hi" },
	{ icon: HiOutlinePhoneMissedCall, name: "HiOutlinePhoneMissedCall", library: "hi" },
	{ icon: HiOutlinePhoneOutgoing, name: "HiOutlinePhoneOutgoing", library: "hi" },
	{ icon: HiOutlinePhone, name: "HiOutlinePhone", library: "hi" },
	{ icon: HiOutlinePhotograph, name: "HiOutlinePhotograph", library: "hi" },
	{ icon: HiOutlinePlay, name: "HiOutlinePlay", library: "hi" },
	{ icon: HiOutlinePlusCircle, name: "HiOutlinePlusCircle", library: "hi" },
	{ icon: HiOutlinePlusSm, name: "HiOutlinePlusSm", library: "hi" },
	{ icon: HiOutlinePlus, name: "HiOutlinePlus", library: "hi" },
	{
		icon: HiOutlinePresentationChartBar,
		name: "HiOutlinePresentationChartBar",
		library: "hi",
	},
	{
		icon: HiOutlinePresentationChartLine,
		name: "HiOutlinePresentationChartLine",
		library: "hi",
	},
	{ icon: HiOutlinePrinter, name: "HiOutlinePrinter", library: "hi" },
	{ icon: HiOutlinePuzzle, name: "HiOutlinePuzzle", library: "hi" },
	{ icon: HiOutlineQrcode, name: "HiOutlineQrcode", library: "hi" },
	{
		icon: HiOutlineQuestionMarkCircle,
		name: "HiOutlineQuestionMarkCircle",
		library: "hi",
	},
	{ icon: HiOutlineReceiptRefund, name: "HiOutlineReceiptRefund", library: "hi" },
	{ icon: HiOutlineReceiptTax, name: "HiOutlineReceiptTax", library: "hi" },
	{ icon: HiOutlineRefresh, name: "HiOutlineRefresh", library: "hi" },
	{ icon: HiOutlineReply, name: "HiOutlineReply", library: "hi" },
	{ icon: HiOutlineRewind, name: "HiOutlineRewind", library: "hi" },
	{ icon: HiOutlineRss, name: "HiOutlineRss", library: "hi" },
	{ icon: HiOutlineSaveAs, name: "HiOutlineSaveAs", library: "hi" },
	{ icon: HiOutlineSave, name: "HiOutlineSave", library: "hi" },
	{ icon: HiOutlineScale, name: "HiOutlineScale", library: "hi" },
	{ icon: HiOutlineScissors, name: "HiOutlineScissors", library: "hi" },
	{ icon: HiOutlineSearchCircle, name: "HiOutlineSearchCircle", library: "hi" },
	{ icon: HiOutlineSearch, name: "HiOutlineSearch", library: "hi" },
	{ icon: HiOutlineSelector, name: "HiOutlineSelector", library: "hi" },
	{ icon: HiOutlineServer, name: "HiOutlineServer", library: "hi" },
	{ icon: HiOutlineShare, name: "HiOutlineShare", library: "hi" },
	{ icon: HiOutlineShieldCheck, name: "HiOutlineShieldCheck", library: "hi" },
	{
		icon: HiOutlineShieldExclamation,
		name: "HiOutlineShieldExclamation",
		library: "hi",
	},
	{ icon: HiOutlineShoppingBag, name: "HiOutlineShoppingBag", library: "hi" },
	{ icon: HiOutlineShoppingCart, name: "HiOutlineShoppingCart", library: "hi" },
	{ icon: HiOutlineSortAscending, name: "HiOutlineSortAscending", library: "hi" },
	{ icon: HiOutlineSortDescending, name: "HiOutlineSortDescending", library: "hi" },
	{ icon: HiOutlineSparkles, name: "HiOutlineSparkles", library: "hi" },
	{ icon: HiOutlineSpeakerphone, name: "HiOutlineSpeakerphone", library: "hi" },
	{ icon: HiOutlineStar, name: "HiOutlineStar", library: "hi" },
	{ icon: HiOutlineStatusOffline, name: "HiOutlineStatusOffline", library: "hi" },
	{ icon: HiOutlineStatusOnline, name: "HiOutlineStatusOnline", library: "hi" },
	{ icon: HiOutlineStop, name: "HiOutlineStop", library: "hi" },
	{ icon: HiOutlineSun, name: "HiOutlineSun", library: "hi" },
	{ icon: HiOutlineSupport, name: "HiOutlineSupport", library: "hi" },
	{ icon: HiOutlineSwitchHorizontal, name: "HiOutlineSwitchHorizontal", library: "hi" },
	{ icon: HiOutlineSwitchVertical, name: "HiOutlineSwitchVertical", library: "hi" },
	{ icon: HiOutlineTable, name: "HiOutlineTable", library: "hi" },
	{ icon: HiOutlineTag, name: "HiOutlineTag", library: "hi" },
	{ icon: HiOutlineTemplate, name: "HiOutlineTemplate", library: "hi" },
	{ icon: HiOutlineTerminal, name: "HiOutlineTerminal", library: "hi" },
	{ icon: HiOutlineThumbDown, name: "HiOutlineThumbDown", library: "hi" },
	{ icon: HiOutlineThumbUp, name: "HiOutlineThumbUp", library: "hi" },
	{ icon: HiOutlineTicket, name: "HiOutlineTicket", library: "hi" },
	{ icon: HiOutlineTranslate, name: "HiOutlineTranslate", library: "hi" },
	{ icon: HiOutlineTrash, name: "HiOutlineTrash", library: "hi" },
	{ icon: HiOutlineTrendingDown, name: "HiOutlineTrendingDown", library: "hi" },
	{ icon: HiOutlineTrendingUp, name: "HiOutlineTrendingUp", library: "hi" },
	{ icon: HiOutlineTruck, name: "HiOutlineTruck", library: "hi" },
	{ icon: HiOutlineUpload, name: "HiOutlineUpload", library: "hi" },
	{ icon: HiOutlineUserAdd, name: "HiOutlineUserAdd", library: "hi" },
	{ icon: HiOutlineUserCircle, name: "HiOutlineUserCircle", library: "hi" },
	{ icon: HiOutlineUserGroup, name: "HiOutlineUserGroup", library: "hi" },
	{ icon: HiOutlineUserRemove, name: "HiOutlineUserRemove", library: "hi" },
	{ icon: HiOutlineUser, name: "HiOutlineUser", library: "hi" },
	{ icon: HiOutlineUsers, name: "HiOutlineUsers", library: "hi" },
	{ icon: HiOutlineVariable, name: "HiOutlineVariable", library: "hi" },
	{ icon: HiOutlineVideoCamera, name: "HiOutlineVideoCamera", library: "hi" },
	{ icon: HiOutlineViewBoards, name: "HiOutlineViewBoards", library: "hi" },
	{ icon: HiOutlineViewGridAdd, name: "HiOutlineViewGridAdd", library: "hi" },
	{ icon: HiOutlineViewGrid, name: "HiOutlineViewGrid", library: "hi" },
	{ icon: HiOutlineViewList, name: "HiOutlineViewList", library: "hi" },
	{ icon: HiOutlineVolumeOff, name: "HiOutlineVolumeOff", library: "hi" },
	{ icon: HiOutlineVolumeUp, name: "HiOutlineVolumeUp", library: "hi" },
	{ icon: HiOutlineWifi, name: "HiOutlineWifi", library: "hi" },
	{ icon: HiOutlineXCircle, name: "HiOutlineXCircle", library: "hi" },
	{ icon: HiOutlineX, name: "HiOutlineX", library: "hi" },
	{ icon: HiOutlineZoomIn, name: "HiOutlineZoomIn", library: "hi" },
	{ icon: HiOutlineZoomOut, name: "HiOutlineZoomOut", library: "hi" },
];

export default result;
