import {
AiFillAccountBook,
AiFillAlert,
AiFillAlipayCircle,
AiFillAlipaySquare,
AiFillAliwangwang,
AiFillAmazonCircle,
AiFillAmazonSquare,
AiFillAndroid,
AiFillApi,
AiFillApple,
AiFillAppstore,
AiFillAudio,
AiFillBackward,
AiFillBank,
AiFillBehanceCircle,
AiFillBehanceSquare,
AiFillBell,
AiFillBook,
AiFillBoxPlot,
AiFillBug,
AiFillBuild,
AiFillBulb,
AiFillCalculator,
AiFillCalendar,
AiFillCamera,
AiFillCar,
AiFillCaretDown,
AiFillCaretLeft,
AiFillCaretRight,
AiFillCaretUp,
AiFillCarryOut,
AiFillCheckCircle,
AiFillCheckSquare,
AiFillChrome,
AiFillCiCircle,
AiFillClockCircle,
AiFillCloseCircle,
AiFillCloseSquare,
AiFillCloud,
AiFillCodeSandboxCircle,
AiFillCodeSandboxSquare,
AiFillCode,
AiFillCodepenCircle,
AiFillCodepenSquare,
AiFillCompass,
AiFillContacts,
AiFillContainer,
AiFillControl,
AiFillCopy,
AiFillCopyrightCircle,
AiFillCreditCard,
AiFillCrown,
AiFillCustomerService,
AiFillDashboard,
AiFillDatabase,
AiFillDelete,
AiFillDiff,
AiFillDingtalkCircle,
AiFillDingtalkSquare,
AiFillDislike,
AiFillDollarCircle,
AiFillDownCircle,
AiFillDownSquare,
AiFillDribbbleCircle,
AiFillDribbbleSquare,
AiFillDropboxCircle,
AiFillDropboxSquare,
AiFillEdit,
AiFillEnvironment,
AiFillEuroCircle,
AiFillExclamationCircle,
AiFillExperiment,
AiFillEyeInvisible,
AiFillEye,
AiFillFacebook,
AiFillFastBackward,
AiFillFastForward,
AiFillFileAdd,
AiFillFileExcel,
AiFillFileExclamation,
AiFillFileImage,
AiFillFileMarkdown,
AiFillFilePdf,
AiFillFilePpt,
AiFillFileText,
AiFillFileUnknown,
AiFillFileWord,
AiFillFileZip,
AiFillFile,
AiFillFilter,
AiFillFire,
AiFillFlag,
AiFillFolderAdd,
AiFillFolderOpen,
AiFillFolder,
AiFillFormatPainter,
AiFillForward,
AiFillFrown,
AiFillFund,
AiFillFunnelPlot,
AiFillGift,
AiFillGithub,
AiFillGitlab,
AiFillGold,
AiFillGolden,
AiFillGoogleCircle,
AiFillGooglePlusCircle,
AiFillGooglePlusSquare,
AiFillGoogleSquare,
AiFillHdd,
AiFillHeart,
AiFillHighlight,
AiFillHome,
AiFillHourglass,
AiFillHtml5,
AiFillIdcard,
AiFillIeCircle,
AiFillIeSquare,
AiFillInfoCircle,
AiFillInstagram,
AiFillInsurance,
AiFillInteraction,
AiFillLayout,
AiFillLeftCircle,
AiFillLeftSquare,
AiFillLike,
AiFillLinkedin,
AiFillLock,
AiFillMacCommand,
AiFillMail,
AiFillMedicineBox,
AiFillMediumCircle,
AiFillMediumSquare,
AiFillMeh,
AiFillMessage,
AiFillMinusCircle,
AiFillMinusSquare,
AiFillMobile,
AiFillMoneyCollect,
AiFillNotification,
AiFillPauseCircle,
AiFillPayCircle,
AiFillPhone,
AiFillPicture,
AiFillPieChart,
AiFillPlayCircle,
AiFillPlaySquare,
AiFillPlusCircle,
AiFillPlusSquare,
AiFillPoundCircle,
AiFillPrinter,
AiFillProfile,
AiFillProject,
AiFillPropertySafety,
AiFillPushpin,
AiFillQqCircle,
AiFillQqSquare,
AiFillQuestionCircle,
AiFillRead,
AiFillReconciliation,
AiFillRedEnvelope,
AiFillRedditCircle,
AiFillRedditSquare,
AiFillRest,
AiFillRightCircle,
AiFillRightSquare,
AiFillRobot,
AiFillRocket,
AiFillSafetyCertificate,
AiFillSave,
AiFillSchedule,
AiFillSecurityScan,
AiFillSetting,
AiFillShop,
AiFillShopping,
AiFillSignal,
AiFillSketchCircle,
AiFillSketchSquare,
AiFillSkin,
AiFillSkype,
AiFillSlackCircle,
AiFillSlackSquare,
AiFillSliders,
AiFillSmile,
AiFillSnippets,
AiFillSound,
AiFillStar,
AiFillStepBackward,
AiFillStepForward,
AiFillStop,
AiFillSwitcher,
AiFillTablet,
AiFillTag,
AiFillTags,
AiFillTaobaoCircle,
AiFillTaobaoSquare,
AiFillThunderbolt,
AiFillTool,
AiFillTrademarkCircle,
AiFillTrophy,
AiFillTwitterCircle,
AiFillTwitterSquare,
AiFillUnlock,
AiFillUpCircle,
AiFillUpSquare,
AiFillUsb,
AiFillVideoCamera,
AiFillWallet,
AiFillWarning,
AiFillWechat,
AiFillWeiboCircle,
AiFillWeiboSquare,
AiFillWindows,
AiFillYahoo,
AiFillYoutube,
AiFillYuque,
AiFillZhihuCircle,
AiFillZhihuSquare,
AiOutlineAccountBook,
AiOutlineAim,
AiOutlineAlert,
AiOutlineAlibaba,
AiOutlineAlignCenter,
AiOutlineAlignLeft,
AiOutlineAlignRight,
AiOutlineAlipayCircle,
AiOutlineAlipay,
AiOutlineAliwangwang,
AiOutlineAliyun,
AiOutlineAmazon,
AiOutlineAndroid,
AiOutlineAntCloud,
AiOutlineAntDesign,
AiOutlineApartment,
AiOutlineApi,
AiOutlineApple,
AiOutlineAppstoreAdd,
AiOutlineAppstore,
AiOutlineAreaChart,
AiOutlineArrowDown,
AiOutlineArrowLeft,
AiOutlineArrowRight,
AiOutlineArrowUp,
AiOutlineArrowsAlt,
AiOutlineAudioMuted,
AiOutlineAudio,
AiOutlineAudit,
AiOutlineBackward,
AiOutlineBank,
AiOutlineBarChart,
AiOutlineBarcode,
AiOutlineBars,
AiOutlineBehanceSquare,
AiOutlineBehance,
AiOutlineBell,
AiOutlineBgColors,
AiOutlineBlock,
AiOutlineBold,
AiOutlineBook,
AiOutlineBorderBottom,
AiOutlineBorderHorizontal,
AiOutlineBorderInner,
AiOutlineBorderLeft,
AiOutlineBorderOuter,
AiOutlineBorderRight,
AiOutlineBorderTop,
AiOutlineBorderVerticle,
AiOutlineBorder,
AiOutlineBorderlessTable,
AiOutlineBoxPlot,
AiOutlineBranches,
AiOutlineBug,
AiOutlineBuild,
AiOutlineBulb,
AiOutlineCalculator,
AiOutlineCalendar,
AiOutlineCamera,
AiOutlineCar,
AiOutlineCaretDown,
AiOutlineCaretLeft,
AiOutlineCaretRight,
AiOutlineCaretUp,
AiOutlineCarryOut,
AiOutlineCheckCircle,
AiOutlineCheckSquare,
AiOutlineCheck,
AiOutlineChrome,
AiOutlineCiCircle,
AiOutlineCi,
AiOutlineClear,
AiOutlineClockCircle,
AiOutlineCloseCircle,
AiOutlineCloseSquare,
AiOutlineClose,
AiOutlineCloudDownload,
AiOutlineCloudServer,
AiOutlineCloudSync,
AiOutlineCloudUpload,
AiOutlineCloud,
AiOutlineCluster,
AiOutlineCodeSandbox,
AiOutlineCode,
AiOutlineCodepenCircle,
AiOutlineCodepen,
AiOutlineCoffee,
AiOutlineColumnHeight,
AiOutlineColumnWidth,
AiOutlineComment,
AiOutlineCompass,
AiOutlineCompress,
AiOutlineConsoleSql,
AiOutlineContacts,
AiOutlineContainer,
AiOutlineControl,
AiOutlineCopy,
AiOutlineCopyrightCircle,
AiOutlineCopyright,
AiOutlineCreditCard,
AiOutlineCrown,
AiOutlineCustomerService,
AiOutlineDash,
AiOutlineDashboard,
AiOutlineDatabase,
AiOutlineDeleteColumn,
AiOutlineDeleteRow,
AiOutlineDelete,
AiOutlineDeliveredProcedure,
AiOutlineDeploymentUnit,
AiOutlineDesktop,
AiOutlineDiff,
AiOutlineDingding,
AiOutlineDingtalk,
AiOutlineDisconnect,
AiOutlineDislike,
AiOutlineDollarCircle,
AiOutlineDollar,
AiOutlineDotChart,
AiOutlineDoubleLeft,
AiOutlineDoubleRight,
AiOutlineDownCircle,
AiOutlineDownSquare,
AiOutlineDown,
AiOutlineDownload,
AiOutlineDrag,
AiOutlineDribbbleSquare,
AiOutlineDribbble,
AiOutlineDropbox,
AiOutlineEdit,
AiOutlineEllipsis,
AiOutlineEnter,
AiOutlineEnvironment,
AiOutlineEuroCircle,
AiOutlineEuro,
AiOutlineException,
AiOutlineExclamationCircle,
AiOutlineExclamation,
AiOutlineExpandAlt,
AiOutlineExpand,
AiOutlineExperiment,
AiOutlineExport,
AiOutlineEyeInvisible,
AiOutlineEye,
AiOutlineFacebook,
AiOutlineFall,
AiOutlineFastBackward,
AiOutlineFastForward,
AiOutlineFieldBinary,
AiOutlineFieldNumber,
AiOutlineFieldString,
AiOutlineFieldTime,
AiOutlineFileAdd,
AiOutlineFileDone,
AiOutlineFileExcel,
AiOutlineFileExclamation,
AiOutlineFileGif,
AiOutlineFileImage,
AiOutlineFileJpg,
AiOutlineFileMarkdown,
AiOutlineFilePdf,
AiOutlineFilePpt,
AiOutlineFileProtect,
AiOutlineFileSearch,
AiOutlineFileSync,
AiOutlineFileText,
AiOutlineFileUnknown,
AiOutlineFileWord,
AiOutlineFileZip,
AiOutlineFile,
AiOutlineFilter,
AiOutlineFire,
AiOutlineFlag,
AiOutlineFolderAdd,
AiOutlineFolderOpen,
AiOutlineFolderView,
AiOutlineFolder,
AiOutlineFontColors,
AiOutlineFontSize,
AiOutlineFork,
AiOutlineForm,
AiOutlineFormatPainter,
AiOutlineForward,
AiOutlineFrown,
AiOutlineFullscreenExit,
AiOutlineFullscreen,
AiOutlineFunction,
AiOutlineFundProjectionScreen,
AiOutlineFundView,
AiOutlineFund,
AiOutlineFunnelPlot,
AiOutlineGateway,
AiOutlineGif,
AiOutlineGift,
AiOutlineGithub,
AiOutlineGitlab,
AiOutlineGlobal,
AiOutlineGold,
AiOutlineGooglePlus,
AiOutlineGoogle,
AiOutlineGroup,
AiOutlineHdd,
AiOutlineHeart,
AiOutlineHeatMap,
AiOutlineHighlight,
AiOutlineHistory,
AiOutlineHolder,
AiOutlineHome,
AiOutlineHourglass,
AiOutlineHtml5,
AiOutlineIdcard,
AiOutlineIe,
AiOutlineImport,
AiOutlineInbox,
AiOutlineInfoCircle,
AiOutlineInfo,
AiOutlineInsertRowAbove,
AiOutlineInsertRowBelow,
AiOutlineInsertRowLeft,
AiOutlineInsertRowRight,
AiOutlineInstagram,
AiOutlineInsurance,
AiOutlineInteraction,
AiOutlineIssuesClose,
AiOutlineItalic,
AiOutlineKey,
AiOutlineLaptop,
AiOutlineLayout,
AiOutlineLeftCircle,
AiOutlineLeftSquare,
AiOutlineLeft,
AiOutlineLike,
AiOutlineLineChart,
AiOutlineLineHeight,
AiOutlineLine,
AiOutlineLink,
AiOutlineLinkedin,
AiOutlineLoading3Quarters,
AiOutlineLoading,
AiOutlineLock,
AiOutlineLogin,
AiOutlineLogout,
AiOutlineMacCommand,
AiOutlineMail,
AiOutlineMan,
AiOutlineMedicineBox,
AiOutlineMediumWorkmark,
AiOutlineMedium,
AiOutlineMeh,
AiOutlineMenuFold,
AiOutlineMenuUnfold,
AiOutlineMenu,
AiOutlineMergeCells,
AiOutlineMessage,
AiOutlineMinusCircle,
AiOutlineMinusSquare,
AiOutlineMinus,
AiOutlineMobile,
AiOutlineMoneyCollect,
AiOutlineMonitor,
AiOutlineMore,
AiOutlineNodeCollapse,
AiOutlineNodeExpand,
AiOutlineNodeIndex,
AiOutlineNotification,
AiOutlineNumber,
AiOutlineOneToOne,
AiOutlineOrderedList,
AiOutlinePaperClip,
AiOutlinePartition,
AiOutlinePauseCircle,
AiOutlinePause,
AiOutlinePayCircle,
AiOutlinePercentage,
AiOutlinePhone,
AiOutlinePicCenter,
AiOutlinePicLeft,
AiOutlinePicRight,
AiOutlinePicture,
AiOutlinePieChart,
AiOutlinePlayCircle,
AiOutlinePlaySquare,
AiOutlinePlusCircle,
AiOutlinePlusSquare,
AiOutlinePlus,
AiOutlinePoundCircle,
AiOutlinePound,
AiOutlinePoweroff,
AiOutlinePrinter,
AiOutlineProfile,
AiOutlineProject,
AiOutlinePropertySafety,
AiOutlinePullRequest,
AiOutlinePushpin,
AiOutlineQq,
AiOutlineQrcode,
AiOutlineQuestionCircle,
AiOutlineQuestion,
AiOutlineRadarChart,
AiOutlineRadiusBottomleft,
AiOutlineRadiusBottomright,
AiOutlineRadiusSetting,
AiOutlineRadiusUpleft,
AiOutlineRadiusUpright,
AiOutlineRead,
AiOutlineReconciliation,
AiOutlineRedEnvelope,
AiOutlineReddit,
AiOutlineRedo,
AiOutlineReload,
AiOutlineRest,
AiOutlineRetweet,
AiOutlineRightCircle,
AiOutlineRightSquare,
AiOutlineRight,
AiOutlineRise,
AiOutlineRobot,
AiOutlineRocket,
AiOutlineRollback,
AiOutlineRotateLeft,
AiOutlineRotateRight,
AiOutlineSafetyCertificate,
AiOutlineSafety,
AiOutlineSave,
AiOutlineScan,
AiOutlineSchedule,
AiOutlineScissor,
AiOutlineSearch,
AiOutlineSecurityScan,
AiOutlineSelect,
AiOutlineSend,
AiOutlineSetting,
AiOutlineShake,
AiOutlineShareAlt,
AiOutlineShop,
AiOutlineShoppingCart,
AiOutlineShopping,
AiOutlineShrink,
AiOutlineSisternode,
AiOutlineSketch,
AiOutlineSkin,
AiOutlineSkype,
AiOutlineSlackSquare,
AiOutlineSlack,
AiOutlineSliders,
AiOutlineSmallDash,
AiOutlineSmile,
AiOutlineSnippets,
AiOutlineSolution,
AiOutlineSortAscending,
AiOutlineSortDescending,
AiOutlineSound,
AiOutlineSplitCells,
AiOutlineStar,
AiOutlineStepBackward,
AiOutlineStepForward,
AiOutlineStock,
AiOutlineStop,
AiOutlineStrikethrough,
AiOutlineSubnode,
AiOutlineSwapLeft,
AiOutlineSwapRight,
AiOutlineSwap,
AiOutlineSwitcher,
AiOutlineSync,
AiOutlineTable,
AiOutlineTablet,
AiOutlineTag,
AiOutlineTags,
AiOutlineTaobaoCircle,
AiOutlineTaobao,
AiOutlineTeam,
AiOutlineThunderbolt,
AiOutlineToTop,
AiOutlineTool,
AiOutlineTrademarkCircle,
AiOutlineTrademark,
AiOutlineTransaction,
AiOutlineTranslation,
AiOutlineTrophy,
AiOutlineTwitter,
AiOutlineUnderline,
AiOutlineUndo,
AiOutlineUngroup,
AiOutlineUnlock,
AiOutlineUnorderedList,
AiOutlineUpCircle,
AiOutlineUpSquare,
AiOutlineUp,
AiOutlineUpload,
AiOutlineUsb,
AiOutlineUserAdd,
AiOutlineUserDelete,
AiOutlineUserSwitch,
AiOutlineUser,
AiOutlineUsergroupAdd,
AiOutlineUsergroupDelete,
AiOutlineVerified,
AiOutlineVerticalAlignBottom,
AiOutlineVerticalAlignMiddle,
AiOutlineVerticalAlignTop,
AiOutlineVerticalLeft,
AiOutlineVerticalRight,
AiOutlineVideoCameraAdd,
AiOutlineVideoCamera,
AiOutlineWallet,
AiOutlineWarning,
AiOutlineWechat,
AiOutlineWeiboCircle,
AiOutlineWeiboSquare,
AiOutlineWeibo,
AiOutlineWhatsApp,
AiOutlineWifi,
AiOutlineWindows,
AiOutlineWoman,
AiOutlineYahoo,
AiOutlineYoutube,
AiOutlineYuque,
AiOutlineZhihu,
AiOutlineZoomIn,
AiOutlineZoomOut,
AiTwotoneAccountBook,
AiTwotoneAlert,
AiTwotoneApi,
AiTwotoneAppstore,
AiTwotoneAudio,
AiTwotoneBank,
AiTwotoneBell,
AiTwotoneBook,
AiTwotoneBoxPlot,
AiTwotoneBug,
AiTwotoneBuild,
AiTwotoneBulb,
AiTwotoneCalculator,
AiTwotoneCalendar,
AiTwotoneCamera,
AiTwotoneCar,
AiTwotoneCarryOut,
AiTwotoneCheckCircle,
AiTwotoneCheckSquare,
AiTwotoneCiCircle,
AiTwotoneCi,
AiTwotoneClockCircle,
AiTwotoneCloseCircle,
AiTwotoneCloseSquare,
AiTwotoneCloud,
AiTwotoneCode,
AiTwotoneCompass,
AiTwotoneContacts,
AiTwotoneContainer,
AiTwotoneControl,
AiTwotoneCopy,
AiTwotoneCopyrightCircle,
AiTwotoneCopyright,
AiTwotoneCreditCard,
AiTwotoneCrown,
AiTwotoneCustomerService,
AiTwotoneDashboard,
AiTwotoneDatabase,
AiTwotoneDelete,
AiTwotoneDiff,
AiTwotoneDislike,
AiTwotoneDollarCircle,
AiTwotoneDollar,
AiTwotoneDownCircle,
AiTwotoneDownSquare,
AiTwotoneEdit,
AiTwotoneEnvironment,
AiTwotoneEuroCircle,
AiTwotoneEuro,
AiTwotoneExclamationCircle,
AiTwotoneExperiment,
AiTwotoneEyeInvisible,
AiTwotoneEye,
AiTwotoneFileAdd,
AiTwotoneFileExcel,
AiTwotoneFileExclamation,
AiTwotoneFileImage,
AiTwotoneFileMarkdown,
AiTwotoneFilePdf,
AiTwotoneFilePpt,
AiTwotoneFileText,
AiTwotoneFileUnknown,
AiTwotoneFileWord,
AiTwotoneFileZip,
AiTwotoneFile,
AiTwotoneFilter,
AiTwotoneFire,
AiTwotoneFlag,
AiTwotoneFolderAdd,
AiTwotoneFolderOpen,
AiTwotoneFolder,
AiTwotoneFrown,
AiTwotoneFund,
AiTwotoneFunnelPlot,
AiTwotoneGift,
AiTwotoneGold,
AiTwotoneHdd,
AiTwotoneHeart,
AiTwotoneHighlight,
AiTwotoneHome,
AiTwotoneHourglass,
AiTwotoneHtml5,
AiTwotoneIdcard,
AiTwotoneInfoCircle,
AiTwotoneInsurance,
AiTwotoneInteraction,
AiTwotoneLayout,
AiTwotoneLeftCircle,
AiTwotoneLeftSquare,
AiTwotoneLike,
AiTwotoneLock,
AiTwotoneMail,
AiTwotoneMedicineBox,
AiTwotoneMeh,
AiTwotoneMessage,
AiTwotoneMinusCircle,
AiTwotoneMinusSquare,
AiTwotoneMobile,
AiTwotoneMoneyCollect,
AiTwotoneNotification,
AiTwotonePauseCircle,
AiTwotonePhone,
AiTwotonePicture,
AiTwotonePieChart,
AiTwotonePlayCircle,
AiTwotonePlaySquare,
AiTwotonePlusCircle,
AiTwotonePlusSquare,
AiTwotonePoundCircle,
AiTwotonePrinter,
AiTwotoneProfile,
AiTwotoneProject,
AiTwotonePropertySafety,
AiTwotonePushpin,
AiTwotoneQuestionCircle,
AiTwotoneReconciliation,
AiTwotoneRedEnvelope,
AiTwotoneRest,
AiTwotoneRightCircle,
AiTwotoneRightSquare,
AiTwotoneRocket,
AiTwotoneSafetyCertificate,
AiTwotoneSave,
AiTwotoneSchedule,
AiTwotoneSecurityScan,
AiTwotoneSetting,
AiTwotoneShop,
AiTwotoneShopping,
AiTwotoneSkin,
AiTwotoneSliders,
AiTwotoneSmile,
AiTwotoneSnippets,
AiTwotoneSound,
AiTwotoneStar,
AiTwotoneStop,
AiTwotoneSwitcher,
AiTwotoneTablet,
AiTwotoneTag,
AiTwotoneTags,
AiTwotoneThunderbolt,
AiTwotoneTool,
AiTwotoneTrademarkCircle,
AiTwotoneTrophy,
AiTwotoneUnlock,
AiTwotoneUpCircle,
AiTwotoneUpSquare,
AiTwotoneUsb,
AiTwotoneVideoCamera,
AiTwotoneWallet,
AiTwotoneWarning,
} from "react-icons/ai";

const result = [
{ icon: AiFillAccountBook, name: "AiFillAccountBook" },
{ icon: AiFillAlert, name: "AiFillAlert" },
{ icon: AiFillAlipayCircle, name: "AiFillAlipayCircle" },
{ icon: AiFillAlipaySquare, name: "AiFillAlipaySquare" },
{ icon: AiFillAliwangwang, name: "AiFillAliwangwang" },
{ icon: AiFillAmazonCircle, name: "AiFillAmazonCircle" },
{ icon: AiFillAmazonSquare, name: "AiFillAmazonSquare" },
{ icon: AiFillAndroid, name: "AiFillAndroid" },
{ icon: AiFillApi, name: "AiFillApi" },
{ icon: AiFillApple, name: "AiFillApple" },
{ icon: AiFillAppstore, name: "AiFillAppstore" },
{ icon: AiFillAudio, name: "AiFillAudio" },
{ icon: AiFillBackward, name: "AiFillBackward" },
{ icon: AiFillBank, name: "AiFillBank" },
{ icon: AiFillBehanceCircle, name: "AiFillBehanceCircle" },
{ icon: AiFillBehanceSquare, name: "AiFillBehanceSquare" },
{ icon: AiFillBell, name: "AiFillBell" },
{ icon: AiFillBook, name: "AiFillBook" },
{ icon: AiFillBoxPlot, name: "AiFillBoxPlot" },
{ icon: AiFillBug, name: "AiFillBug" },
{ icon: AiFillBuild, name: "AiFillBuild" },
{ icon: AiFillBulb, name: "AiFillBulb" },
{ icon: AiFillCalculator, name: "AiFillCalculator" },
{ icon: AiFillCalendar, name: "AiFillCalendar" },
{ icon: AiFillCamera, name: "AiFillCamera" },
{ icon: AiFillCar, name: "AiFillCar" },
{ icon: AiFillCaretDown, name: "AiFillCaretDown" },
{ icon: AiFillCaretLeft, name: "AiFillCaretLeft" },
{ icon: AiFillCaretRight, name: "AiFillCaretRight" },
{ icon: AiFillCaretUp, name: "AiFillCaretUp" },
{ icon: AiFillCarryOut, name: "AiFillCarryOut" },
{ icon: AiFillCheckCircle, name: "AiFillCheckCircle" },
{ icon: AiFillCheckSquare, name: "AiFillCheckSquare" },
{ icon: AiFillChrome, name: "AiFillChrome" },
{ icon: AiFillCiCircle, name: "AiFillCiCircle" },
{ icon: AiFillClockCircle, name: "AiFillClockCircle" },
{ icon: AiFillCloseCircle, name: "AiFillCloseCircle" },
{ icon: AiFillCloseSquare, name: "AiFillCloseSquare" },
{ icon: AiFillCloud, name: "AiFillCloud" },
{ icon: AiFillCodeSandboxCircle, name: "AiFillCodeSandboxCircle" },
{ icon: AiFillCodeSandboxSquare, name: "AiFillCodeSandboxSquare" },
{ icon: AiFillCode, name: "AiFillCode" },
{ icon: AiFillCodepenCircle, name: "AiFillCodepenCircle" },
{ icon: AiFillCodepenSquare, name: "AiFillCodepenSquare" },
{ icon: AiFillCompass, name: "AiFillCompass" },
{ icon: AiFillContacts, name: "AiFillContacts" },
{ icon: AiFillContainer, name: "AiFillContainer" },
{ icon: AiFillControl, name: "AiFillControl" },
{ icon: AiFillCopy, name: "AiFillCopy" },
{ icon: AiFillCopyrightCircle, name: "AiFillCopyrightCircle" },
{ icon: AiFillCreditCard, name: "AiFillCreditCard" },
{ icon: AiFillCrown, name: "AiFillCrown" },
{ icon: AiFillCustomerService, name: "AiFillCustomerService" },
{ icon: AiFillDashboard, name: "AiFillDashboard" },
{ icon: AiFillDatabase, name: "AiFillDatabase" },
{ icon: AiFillDelete, name: "AiFillDelete" },
{ icon: AiFillDiff, name: "AiFillDiff" },
{ icon: AiFillDingtalkCircle, name: "AiFillDingtalkCircle" },
{ icon: AiFillDingtalkSquare, name: "AiFillDingtalkSquare" },
{ icon: AiFillDislike, name: "AiFillDislike" },
{ icon: AiFillDollarCircle, name: "AiFillDollarCircle" },
{ icon: AiFillDownCircle, name: "AiFillDownCircle" },
{ icon: AiFillDownSquare, name: "AiFillDownSquare" },
{ icon: AiFillDribbbleCircle, name: "AiFillDribbbleCircle" },
{ icon: AiFillDribbbleSquare, name: "AiFillDribbbleSquare" },
{ icon: AiFillDropboxCircle, name: "AiFillDropboxCircle" },
{ icon: AiFillDropboxSquare, name: "AiFillDropboxSquare" },
{ icon: AiFillEdit, name: "AiFillEdit" },
{ icon: AiFillEnvironment, name: "AiFillEnvironment" },
{ icon: AiFillEuroCircle, name: "AiFillEuroCircle" },
{ icon: AiFillExclamationCircle, name: "AiFillExclamationCircle" },
{ icon: AiFillExperiment, name: "AiFillExperiment" },
{ icon: AiFillEyeInvisible, name: "AiFillEyeInvisible" },
{ icon: AiFillEye, name: "AiFillEye" },
{ icon: AiFillFacebook, name: "AiFillFacebook" },
{ icon: AiFillFastBackward, name: "AiFillFastBackward" },
{ icon: AiFillFastForward, name: "AiFillFastForward" },
{ icon: AiFillFileAdd, name: "AiFillFileAdd" },
{ icon: AiFillFileExcel, name: "AiFillFileExcel" },
{ icon: AiFillFileExclamation, name: "AiFillFileExclamation" },
{ icon: AiFillFileImage, name: "AiFillFileImage" },
{ icon: AiFillFileMarkdown, name: "AiFillFileMarkdown" },
{ icon: AiFillFilePdf, name: "AiFillFilePdf" },
{ icon: AiFillFilePpt, name: "AiFillFilePpt" },
{ icon: AiFillFileText, name: "AiFillFileText" },
{ icon: AiFillFileUnknown, name: "AiFillFileUnknown" },
{ icon: AiFillFileWord, name: "AiFillFileWord" },
{ icon: AiFillFileZip, name: "AiFillFileZip" },
{ icon: AiFillFile, name: "AiFillFile" },
{ icon: AiFillFilter, name: "AiFillFilter" },
{ icon: AiFillFire, name: "AiFillFire" },
{ icon: AiFillFlag, name: "AiFillFlag" },
{ icon: AiFillFolderAdd, name: "AiFillFolderAdd" },
{ icon: AiFillFolderOpen, name: "AiFillFolderOpen" },
{ icon: AiFillFolder, name: "AiFillFolder" },
{ icon: AiFillFormatPainter, name: "AiFillFormatPainter" },
{ icon: AiFillForward, name: "AiFillForward" },
{ icon: AiFillFrown, name: "AiFillFrown" },
{ icon: AiFillFund, name: "AiFillFund" },
{ icon: AiFillFunnelPlot, name: "AiFillFunnelPlot" },
{ icon: AiFillGift, name: "AiFillGift" },
{ icon: AiFillGithub, name: "AiFillGithub" },
{ icon: AiFillGitlab, name: "AiFillGitlab" },
{ icon: AiFillGold, name: "AiFillGold" },
{ icon: AiFillGolden, name: "AiFillGolden" },
{ icon: AiFillGoogleCircle, name: "AiFillGoogleCircle" },
{ icon: AiFillGooglePlusCircle, name: "AiFillGooglePlusCircle" },
{ icon: AiFillGooglePlusSquare, name: "AiFillGooglePlusSquare" },
{ icon: AiFillGoogleSquare, name: "AiFillGoogleSquare" },
{ icon: AiFillHdd, name: "AiFillHdd" },
{ icon: AiFillHeart, name: "AiFillHeart" },
{ icon: AiFillHighlight, name: "AiFillHighlight" },
{ icon: AiFillHome, name: "AiFillHome" },
{ icon: AiFillHourglass, name: "AiFillHourglass" },
{ icon: AiFillHtml5, name: "AiFillHtml5" },
{ icon: AiFillIdcard, name: "AiFillIdcard" },
{ icon: AiFillIeCircle, name: "AiFillIeCircle" },
{ icon: AiFillIeSquare, name: "AiFillIeSquare" },
{ icon: AiFillInfoCircle, name: "AiFillInfoCircle" },
{ icon: AiFillInstagram, name: "AiFillInstagram" },
{ icon: AiFillInsurance, name: "AiFillInsurance" },
{ icon: AiFillInteraction, name: "AiFillInteraction" },
{ icon: AiFillLayout, name: "AiFillLayout" },
{ icon: AiFillLeftCircle, name: "AiFillLeftCircle" },
{ icon: AiFillLeftSquare, name: "AiFillLeftSquare" },
{ icon: AiFillLike, name: "AiFillLike" },
{ icon: AiFillLinkedin, name: "AiFillLinkedin" },
{ icon: AiFillLock, name: "AiFillLock" },
{ icon: AiFillMacCommand, name: "AiFillMacCommand" },
{ icon: AiFillMail, name: "AiFillMail" },
{ icon: AiFillMedicineBox, name: "AiFillMedicineBox" },
{ icon: AiFillMediumCircle, name: "AiFillMediumCircle" },
{ icon: AiFillMediumSquare, name: "AiFillMediumSquare" },
{ icon: AiFillMeh, name: "AiFillMeh" },
{ icon: AiFillMessage, name: "AiFillMessage" },
{ icon: AiFillMinusCircle, name: "AiFillMinusCircle" },
{ icon: AiFillMinusSquare, name: "AiFillMinusSquare" },
{ icon: AiFillMobile, name: "AiFillMobile" },
{ icon: AiFillMoneyCollect, name: "AiFillMoneyCollect" },
{ icon: AiFillNotification, name: "AiFillNotification" },
{ icon: AiFillPauseCircle, name: "AiFillPauseCircle" },
{ icon: AiFillPayCircle, name: "AiFillPayCircle" },
{ icon: AiFillPhone, name: "AiFillPhone" },
{ icon: AiFillPicture, name: "AiFillPicture" },
{ icon: AiFillPieChart, name: "AiFillPieChart" },
{ icon: AiFillPlayCircle, name: "AiFillPlayCircle" },
{ icon: AiFillPlaySquare, name: "AiFillPlaySquare" },
{ icon: AiFillPlusCircle, name: "AiFillPlusCircle" },
{ icon: AiFillPlusSquare, name: "AiFillPlusSquare" },
{ icon: AiFillPoundCircle, name: "AiFillPoundCircle" },
{ icon: AiFillPrinter, name: "AiFillPrinter" },
{ icon: AiFillProfile, name: "AiFillProfile" },
{ icon: AiFillProject, name: "AiFillProject" },
{ icon: AiFillPropertySafety, name: "AiFillPropertySafety" },
{ icon: AiFillPushpin, name: "AiFillPushpin" },
{ icon: AiFillQqCircle, name: "AiFillQqCircle" },
{ icon: AiFillQqSquare, name: "AiFillQqSquare" },
{ icon: AiFillQuestionCircle, name: "AiFillQuestionCircle" },
{ icon: AiFillRead, name: "AiFillRead" },
{ icon: AiFillReconciliation, name: "AiFillReconciliation" },
{ icon: AiFillRedEnvelope, name: "AiFillRedEnvelope" },
{ icon: AiFillRedditCircle, name: "AiFillRedditCircle" },
{ icon: AiFillRedditSquare, name: "AiFillRedditSquare" },
{ icon: AiFillRest, name: "AiFillRest" },
{ icon: AiFillRightCircle, name: "AiFillRightCircle" },
{ icon: AiFillRightSquare, name: "AiFillRightSquare" },
{ icon: AiFillRobot, name: "AiFillRobot" },
{ icon: AiFillRocket, name: "AiFillRocket" },
{ icon: AiFillSafetyCertificate, name: "AiFillSafetyCertificate" },
{ icon: AiFillSave, name: "AiFillSave" },
{ icon: AiFillSchedule, name: "AiFillSchedule" },
{ icon: AiFillSecurityScan, name: "AiFillSecurityScan" },
{ icon: AiFillSetting, name: "AiFillSetting" },
{ icon: AiFillShop, name: "AiFillShop" },
{ icon: AiFillShopping, name: "AiFillShopping" },
{ icon: AiFillSignal, name: "AiFillSignal" },
{ icon: AiFillSketchCircle, name: "AiFillSketchCircle" },
{ icon: AiFillSketchSquare, name: "AiFillSketchSquare" },
{ icon: AiFillSkin, name: "AiFillSkin" },
{ icon: AiFillSkype, name: "AiFillSkype" },
{ icon: AiFillSlackCircle, name: "AiFillSlackCircle" },
{ icon: AiFillSlackSquare, name: "AiFillSlackSquare" },
{ icon: AiFillSliders, name: "AiFillSliders" },
{ icon: AiFillSmile, name: "AiFillSmile" },
{ icon: AiFillSnippets, name: "AiFillSnippets" },
{ icon: AiFillSound, name: "AiFillSound" },
{ icon: AiFillStar, name: "AiFillStar" },
{ icon: AiFillStepBackward, name: "AiFillStepBackward" },
{ icon: AiFillStepForward, name: "AiFillStepForward" },
{ icon: AiFillStop, name: "AiFillStop" },
{ icon: AiFillSwitcher, name: "AiFillSwitcher" },
{ icon: AiFillTablet, name: "AiFillTablet" },
{ icon: AiFillTag, name: "AiFillTag" },
{ icon: AiFillTags, name: "AiFillTags" },
{ icon: AiFillTaobaoCircle, name: "AiFillTaobaoCircle" },
{ icon: AiFillTaobaoSquare, name: "AiFillTaobaoSquare" },
{ icon: AiFillThunderbolt, name: "AiFillThunderbolt" },
{ icon: AiFillTool, name: "AiFillTool" },
{ icon: AiFillTrademarkCircle, name: "AiFillTrademarkCircle" },
{ icon: AiFillTrophy, name: "AiFillTrophy" },
{ icon: AiFillTwitterCircle, name: "AiFillTwitterCircle" },
{ icon: AiFillTwitterSquare, name: "AiFillTwitterSquare" },
{ icon: AiFillUnlock, name: "AiFillUnlock" },
{ icon: AiFillUpCircle, name: "AiFillUpCircle" },
{ icon: AiFillUpSquare, name: "AiFillUpSquare" },
{ icon: AiFillUsb, name: "AiFillUsb" },
{ icon: AiFillVideoCamera, name: "AiFillVideoCamera" },
{ icon: AiFillWallet, name: "AiFillWallet" },
{ icon: AiFillWarning, name: "AiFillWarning" },
{ icon: AiFillWechat, name: "AiFillWechat" },
{ icon: AiFillWeiboCircle, name: "AiFillWeiboCircle" },
{ icon: AiFillWeiboSquare, name: "AiFillWeiboSquare" },
{ icon: AiFillWindows, name: "AiFillWindows" },
{ icon: AiFillYahoo, name: "AiFillYahoo" },
{ icon: AiFillYoutube, name: "AiFillYoutube" },
{ icon: AiFillYuque, name: "AiFillYuque" },
{ icon: AiFillZhihuCircle, name: "AiFillZhihuCircle" },
{ icon: AiFillZhihuSquare, name: "AiFillZhihuSquare" },
{ icon: AiOutlineAccountBook, name: "AiOutlineAccountBook" },
{ icon: AiOutlineAim, name: "AiOutlineAim" },
{ icon: AiOutlineAlert, name: "AiOutlineAlert" },
{ icon: AiOutlineAlibaba, name: "AiOutlineAlibaba" },
{ icon: AiOutlineAlignCenter, name: "AiOutlineAlignCenter" },
{ icon: AiOutlineAlignLeft, name: "AiOutlineAlignLeft" },
{ icon: AiOutlineAlignRight, name: "AiOutlineAlignRight" },
{ icon: AiOutlineAlipayCircle, name: "AiOutlineAlipayCircle" },
{ icon: AiOutlineAlipay, name: "AiOutlineAlipay" },
{ icon: AiOutlineAliwangwang, name: "AiOutlineAliwangwang" },
{ icon: AiOutlineAliyun, name: "AiOutlineAliyun" },
{ icon: AiOutlineAmazon, name: "AiOutlineAmazon" },
{ icon: AiOutlineAndroid, name: "AiOutlineAndroid" },
{ icon: AiOutlineAntCloud, name: "AiOutlineAntCloud" },
{ icon: AiOutlineAntDesign, name: "AiOutlineAntDesign" },
{ icon: AiOutlineApartment, name: "AiOutlineApartment" },
{ icon: AiOutlineApi, name: "AiOutlineApi" },
{ icon: AiOutlineApple, name: "AiOutlineApple" },
{ icon: AiOutlineAppstoreAdd, name: "AiOutlineAppstoreAdd" },
{ icon: AiOutlineAppstore, name: "AiOutlineAppstore" },
{ icon: AiOutlineAreaChart, name: "AiOutlineAreaChart" },
{ icon: AiOutlineArrowDown, name: "AiOutlineArrowDown" },
{ icon: AiOutlineArrowLeft, name: "AiOutlineArrowLeft" },
{ icon: AiOutlineArrowRight, name: "AiOutlineArrowRight" },
{ icon: AiOutlineArrowUp, name: "AiOutlineArrowUp" },
{ icon: AiOutlineArrowsAlt, name: "AiOutlineArrowsAlt" },
{ icon: AiOutlineAudioMuted, name: "AiOutlineAudioMuted" },
{ icon: AiOutlineAudio, name: "AiOutlineAudio" },
{ icon: AiOutlineAudit, name: "AiOutlineAudit" },
{ icon: AiOutlineBackward, name: "AiOutlineBackward" },
{ icon: AiOutlineBank, name: "AiOutlineBank" },
{ icon: AiOutlineBarChart, name: "AiOutlineBarChart" },
{ icon: AiOutlineBarcode, name: "AiOutlineBarcode" },
{ icon: AiOutlineBars, name: "AiOutlineBars" },
{ icon: AiOutlineBehanceSquare, name: "AiOutlineBehanceSquare" },
{ icon: AiOutlineBehance, name: "AiOutlineBehance" },
{ icon: AiOutlineBell, name: "AiOutlineBell" },
{ icon: AiOutlineBgColors, name: "AiOutlineBgColors" },
{ icon: AiOutlineBlock, name: "AiOutlineBlock" },
{ icon: AiOutlineBold, name: "AiOutlineBold" },
{ icon: AiOutlineBook, name: "AiOutlineBook" },
{ icon: AiOutlineBorderBottom, name: "AiOutlineBorderBottom" },
{ icon: AiOutlineBorderHorizontal, name: "AiOutlineBorderHorizontal" },
{ icon: AiOutlineBorderInner, name: "AiOutlineBorderInner" },
{ icon: AiOutlineBorderLeft, name: "AiOutlineBorderLeft" },
{ icon: AiOutlineBorderOuter, name: "AiOutlineBorderOuter" },
{ icon: AiOutlineBorderRight, name: "AiOutlineBorderRight" },
{ icon: AiOutlineBorderTop, name: "AiOutlineBorderTop" },
{ icon: AiOutlineBorderVerticle, name: "AiOutlineBorderVerticle" },
{ icon: AiOutlineBorder, name: "AiOutlineBorder" },
{ icon: AiOutlineBorderlessTable, name: "AiOutlineBorderlessTable" },
{ icon: AiOutlineBoxPlot, name: "AiOutlineBoxPlot" },
{ icon: AiOutlineBranches, name: "AiOutlineBranches" },
{ icon: AiOutlineBug, name: "AiOutlineBug" },
{ icon: AiOutlineBuild, name: "AiOutlineBuild" },
{ icon: AiOutlineBulb, name: "AiOutlineBulb" },
{ icon: AiOutlineCalculator, name: "AiOutlineCalculator" },
{ icon: AiOutlineCalendar, name: "AiOutlineCalendar" },
{ icon: AiOutlineCamera, name: "AiOutlineCamera" },
{ icon: AiOutlineCar, name: "AiOutlineCar" },
{ icon: AiOutlineCaretDown, name: "AiOutlineCaretDown" },
{ icon: AiOutlineCaretLeft, name: "AiOutlineCaretLeft" },
{ icon: AiOutlineCaretRight, name: "AiOutlineCaretRight" },
{ icon: AiOutlineCaretUp, name: "AiOutlineCaretUp" },
{ icon: AiOutlineCarryOut, name: "AiOutlineCarryOut" },
{ icon: AiOutlineCheckCircle, name: "AiOutlineCheckCircle" },
{ icon: AiOutlineCheckSquare, name: "AiOutlineCheckSquare" },
{ icon: AiOutlineCheck, name: "AiOutlineCheck" },
{ icon: AiOutlineChrome, name: "AiOutlineChrome" },
{ icon: AiOutlineCiCircle, name: "AiOutlineCiCircle" },
{ icon: AiOutlineCi, name: "AiOutlineCi" },
{ icon: AiOutlineClear, name: "AiOutlineClear" },
{ icon: AiOutlineClockCircle, name: "AiOutlineClockCircle" },
{ icon: AiOutlineCloseCircle, name: "AiOutlineCloseCircle" },
{ icon: AiOutlineCloseSquare, name: "AiOutlineCloseSquare" },
{ icon: AiOutlineClose, name: "AiOutlineClose" },
{ icon: AiOutlineCloudDownload, name: "AiOutlineCloudDownload" },
{ icon: AiOutlineCloudServer, name: "AiOutlineCloudServer" },
{ icon: AiOutlineCloudSync, name: "AiOutlineCloudSync" },
{ icon: AiOutlineCloudUpload, name: "AiOutlineCloudUpload" },
{ icon: AiOutlineCloud, name: "AiOutlineCloud" },
{ icon: AiOutlineCluster, name: "AiOutlineCluster" },
{ icon: AiOutlineCodeSandbox, name: "AiOutlineCodeSandbox" },
{ icon: AiOutlineCode, name: "AiOutlineCode" },
{ icon: AiOutlineCodepenCircle, name: "AiOutlineCodepenCircle" },
{ icon: AiOutlineCodepen, name: "AiOutlineCodepen" },
{ icon: AiOutlineCoffee, name: "AiOutlineCoffee" },
{ icon: AiOutlineColumnHeight, name: "AiOutlineColumnHeight" },
{ icon: AiOutlineColumnWidth, name: "AiOutlineColumnWidth" },
{ icon: AiOutlineComment, name: "AiOutlineComment" },
{ icon: AiOutlineCompass, name: "AiOutlineCompass" },
{ icon: AiOutlineCompress, name: "AiOutlineCompress" },
{ icon: AiOutlineConsoleSql, name: "AiOutlineConsoleSql" },
{ icon: AiOutlineContacts, name: "AiOutlineContacts" },
{ icon: AiOutlineContainer, name: "AiOutlineContainer" },
{ icon: AiOutlineControl, name: "AiOutlineControl" },
{ icon: AiOutlineCopy, name: "AiOutlineCopy" },
{ icon: AiOutlineCopyrightCircle, name: "AiOutlineCopyrightCircle" },
{ icon: AiOutlineCopyright, name: "AiOutlineCopyright" },
{ icon: AiOutlineCreditCard, name: "AiOutlineCreditCard" },
{ icon: AiOutlineCrown, name: "AiOutlineCrown" },
{ icon: AiOutlineCustomerService, name: "AiOutlineCustomerService" },
{ icon: AiOutlineDash, name: "AiOutlineDash" },
{ icon: AiOutlineDashboard, name: "AiOutlineDashboard" },
{ icon: AiOutlineDatabase, name: "AiOutlineDatabase" },
{ icon: AiOutlineDeleteColumn, name: "AiOutlineDeleteColumn" },
{ icon: AiOutlineDeleteRow, name: "AiOutlineDeleteRow" },
{ icon: AiOutlineDelete, name: "AiOutlineDelete" },
{ icon: AiOutlineDeliveredProcedure, name: "AiOutlineDeliveredProcedure" },
{ icon: AiOutlineDeploymentUnit, name: "AiOutlineDeploymentUnit" },
{ icon: AiOutlineDesktop, name: "AiOutlineDesktop" },
{ icon: AiOutlineDiff, name: "AiOutlineDiff" },
{ icon: AiOutlineDingding, name: "AiOutlineDingding" },
{ icon: AiOutlineDingtalk, name: "AiOutlineDingtalk" },
{ icon: AiOutlineDisconnect, name: "AiOutlineDisconnect" },
{ icon: AiOutlineDislike, name: "AiOutlineDislike" },
{ icon: AiOutlineDollarCircle, name: "AiOutlineDollarCircle" },
{ icon: AiOutlineDollar, name: "AiOutlineDollar" },
{ icon: AiOutlineDotChart, name: "AiOutlineDotChart" },
{ icon: AiOutlineDoubleLeft, name: "AiOutlineDoubleLeft" },
{ icon: AiOutlineDoubleRight, name: "AiOutlineDoubleRight" },
{ icon: AiOutlineDownCircle, name: "AiOutlineDownCircle" },
{ icon: AiOutlineDownSquare, name: "AiOutlineDownSquare" },
{ icon: AiOutlineDown, name: "AiOutlineDown" },
{ icon: AiOutlineDownload, name: "AiOutlineDownload" },
{ icon: AiOutlineDrag, name: "AiOutlineDrag" },
{ icon: AiOutlineDribbbleSquare, name: "AiOutlineDribbbleSquare" },
{ icon: AiOutlineDribbble, name: "AiOutlineDribbble" },
{ icon: AiOutlineDropbox, name: "AiOutlineDropbox" },
{ icon: AiOutlineEdit, name: "AiOutlineEdit" },
{ icon: AiOutlineEllipsis, name: "AiOutlineEllipsis" },
{ icon: AiOutlineEnter, name: "AiOutlineEnter" },
{ icon: AiOutlineEnvironment, name: "AiOutlineEnvironment" },
{ icon: AiOutlineEuroCircle, name: "AiOutlineEuroCircle" },
{ icon: AiOutlineEuro, name: "AiOutlineEuro" },
{ icon: AiOutlineException, name: "AiOutlineException" },
{ icon: AiOutlineExclamationCircle, name: "AiOutlineExclamationCircle" },
{ icon: AiOutlineExclamation, name: "AiOutlineExclamation" },
{ icon: AiOutlineExpandAlt, name: "AiOutlineExpandAlt" },
{ icon: AiOutlineExpand, name: "AiOutlineExpand" },
{ icon: AiOutlineExperiment, name: "AiOutlineExperiment" },
{ icon: AiOutlineExport, name: "AiOutlineExport" },
{ icon: AiOutlineEyeInvisible, name: "AiOutlineEyeInvisible" },
{ icon: AiOutlineEye, name: "AiOutlineEye" },
{ icon: AiOutlineFacebook, name: "AiOutlineFacebook" },
{ icon: AiOutlineFall, name: "AiOutlineFall" },
{ icon: AiOutlineFastBackward, name: "AiOutlineFastBackward" },
{ icon: AiOutlineFastForward, name: "AiOutlineFastForward" },
{ icon: AiOutlineFieldBinary, name: "AiOutlineFieldBinary" },
{ icon: AiOutlineFieldNumber, name: "AiOutlineFieldNumber" },
{ icon: AiOutlineFieldString, name: "AiOutlineFieldString" },
{ icon: AiOutlineFieldTime, name: "AiOutlineFieldTime" },
{ icon: AiOutlineFileAdd, name: "AiOutlineFileAdd" },
{ icon: AiOutlineFileDone, name: "AiOutlineFileDone" },
{ icon: AiOutlineFileExcel, name: "AiOutlineFileExcel" },
{ icon: AiOutlineFileExclamation, name: "AiOutlineFileExclamation" },
{ icon: AiOutlineFileGif, name: "AiOutlineFileGif" },
{ icon: AiOutlineFileImage, name: "AiOutlineFileImage" },
{ icon: AiOutlineFileJpg, name: "AiOutlineFileJpg" },
{ icon: AiOutlineFileMarkdown, name: "AiOutlineFileMarkdown" },
{ icon: AiOutlineFilePdf, name: "AiOutlineFilePdf" },
{ icon: AiOutlineFilePpt, name: "AiOutlineFilePpt" },
{ icon: AiOutlineFileProtect, name: "AiOutlineFileProtect" },
{ icon: AiOutlineFileSearch, name: "AiOutlineFileSearch" },
{ icon: AiOutlineFileSync, name: "AiOutlineFileSync" },
{ icon: AiOutlineFileText, name: "AiOutlineFileText" },
{ icon: AiOutlineFileUnknown, name: "AiOutlineFileUnknown" },
{ icon: AiOutlineFileWord, name: "AiOutlineFileWord" },
{ icon: AiOutlineFileZip, name: "AiOutlineFileZip" },
{ icon: AiOutlineFile, name: "AiOutlineFile" },
{ icon: AiOutlineFilter, name: "AiOutlineFilter" },
{ icon: AiOutlineFire, name: "AiOutlineFire" },
{ icon: AiOutlineFlag, name: "AiOutlineFlag" },
{ icon: AiOutlineFolderAdd, name: "AiOutlineFolderAdd" },
{ icon: AiOutlineFolderOpen, name: "AiOutlineFolderOpen" },
{ icon: AiOutlineFolderView, name: "AiOutlineFolderView" },
{ icon: AiOutlineFolder, name: "AiOutlineFolder" },
{ icon: AiOutlineFontColors, name: "AiOutlineFontColors" },
{ icon: AiOutlineFontSize, name: "AiOutlineFontSize" },
{ icon: AiOutlineFork, name: "AiOutlineFork" },
{ icon: AiOutlineForm, name: "AiOutlineForm" },
{ icon: AiOutlineFormatPainter, name: "AiOutlineFormatPainter" },
{ icon: AiOutlineForward, name: "AiOutlineForward" },
{ icon: AiOutlineFrown, name: "AiOutlineFrown" },
{ icon: AiOutlineFullscreenExit, name: "AiOutlineFullscreenExit" },
{ icon: AiOutlineFullscreen, name: "AiOutlineFullscreen" },
{ icon: AiOutlineFunction, name: "AiOutlineFunction" },
{ icon: AiOutlineFundProjectionScreen, name: "AiOutlineFundProjectionScreen" },
{ icon: AiOutlineFundView, name: "AiOutlineFundView" },
{ icon: AiOutlineFund, name: "AiOutlineFund" },
{ icon: AiOutlineFunnelPlot, name: "AiOutlineFunnelPlot" },
{ icon: AiOutlineGateway, name: "AiOutlineGateway" },
{ icon: AiOutlineGif, name: "AiOutlineGif" },
{ icon: AiOutlineGift, name: "AiOutlineGift" },
{ icon: AiOutlineGithub, name: "AiOutlineGithub" },
{ icon: AiOutlineGitlab, name: "AiOutlineGitlab" },
{ icon: AiOutlineGlobal, name: "AiOutlineGlobal" },
{ icon: AiOutlineGold, name: "AiOutlineGold" },
{ icon: AiOutlineGooglePlus, name: "AiOutlineGooglePlus" },
{ icon: AiOutlineGoogle, name: "AiOutlineGoogle" },
{ icon: AiOutlineGroup, name: "AiOutlineGroup" },
{ icon: AiOutlineHdd, name: "AiOutlineHdd" },
{ icon: AiOutlineHeart, name: "AiOutlineHeart" },
{ icon: AiOutlineHeatMap, name: "AiOutlineHeatMap" },
{ icon: AiOutlineHighlight, name: "AiOutlineHighlight" },
{ icon: AiOutlineHistory, name: "AiOutlineHistory" },
{ icon: AiOutlineHolder, name: "AiOutlineHolder" },
{ icon: AiOutlineHome, name: "AiOutlineHome" },
{ icon: AiOutlineHourglass, name: "AiOutlineHourglass" },
{ icon: AiOutlineHtml5, name: "AiOutlineHtml5" },
{ icon: AiOutlineIdcard, name: "AiOutlineIdcard" },
{ icon: AiOutlineIe, name: "AiOutlineIe" },
{ icon: AiOutlineImport, name: "AiOutlineImport" },
{ icon: AiOutlineInbox, name: "AiOutlineInbox" },
{ icon: AiOutlineInfoCircle, name: "AiOutlineInfoCircle" },
{ icon: AiOutlineInfo, name: "AiOutlineInfo" },
{ icon: AiOutlineInsertRowAbove, name: "AiOutlineInsertRowAbove" },
{ icon: AiOutlineInsertRowBelow, name: "AiOutlineInsertRowBelow" },
{ icon: AiOutlineInsertRowLeft, name: "AiOutlineInsertRowLeft" },
{ icon: AiOutlineInsertRowRight, name: "AiOutlineInsertRowRight" },
{ icon: AiOutlineInstagram, name: "AiOutlineInstagram" },
{ icon: AiOutlineInsurance, name: "AiOutlineInsurance" },
{ icon: AiOutlineInteraction, name: "AiOutlineInteraction" },
{ icon: AiOutlineIssuesClose, name: "AiOutlineIssuesClose" },
{ icon: AiOutlineItalic, name: "AiOutlineItalic" },
{ icon: AiOutlineKey, name: "AiOutlineKey" },
{ icon: AiOutlineLaptop, name: "AiOutlineLaptop" },
{ icon: AiOutlineLayout, name: "AiOutlineLayout" },
{ icon: AiOutlineLeftCircle, name: "AiOutlineLeftCircle" },
{ icon: AiOutlineLeftSquare, name: "AiOutlineLeftSquare" },
{ icon: AiOutlineLeft, name: "AiOutlineLeft" },
{ icon: AiOutlineLike, name: "AiOutlineLike" },
{ icon: AiOutlineLineChart, name: "AiOutlineLineChart" },
{ icon: AiOutlineLineHeight, name: "AiOutlineLineHeight" },
{ icon: AiOutlineLine, name: "AiOutlineLine" },
{ icon: AiOutlineLink, name: "AiOutlineLink" },
{ icon: AiOutlineLinkedin, name: "AiOutlineLinkedin" },
{ icon: AiOutlineLoading3Quarters, name: "AiOutlineLoading3Quarters" },
{ icon: AiOutlineLoading, name: "AiOutlineLoading" },
{ icon: AiOutlineLock, name: "AiOutlineLock" },
{ icon: AiOutlineLogin, name: "AiOutlineLogin" },
{ icon: AiOutlineLogout, name: "AiOutlineLogout" },
{ icon: AiOutlineMacCommand, name: "AiOutlineMacCommand" },
{ icon: AiOutlineMail, name: "AiOutlineMail" },
{ icon: AiOutlineMan, name: "AiOutlineMan" },
{ icon: AiOutlineMedicineBox, name: "AiOutlineMedicineBox" },
{ icon: AiOutlineMediumWorkmark, name: "AiOutlineMediumWorkmark" },
{ icon: AiOutlineMedium, name: "AiOutlineMedium" },
{ icon: AiOutlineMeh, name: "AiOutlineMeh" },
{ icon: AiOutlineMenuFold, name: "AiOutlineMenuFold" },
{ icon: AiOutlineMenuUnfold, name: "AiOutlineMenuUnfold" },
{ icon: AiOutlineMenu, name: "AiOutlineMenu" },
{ icon: AiOutlineMergeCells, name: "AiOutlineMergeCells" },
{ icon: AiOutlineMessage, name: "AiOutlineMessage" },
{ icon: AiOutlineMinusCircle, name: "AiOutlineMinusCircle" },
{ icon: AiOutlineMinusSquare, name: "AiOutlineMinusSquare" },
{ icon: AiOutlineMinus, name: "AiOutlineMinus" },
{ icon: AiOutlineMobile, name: "AiOutlineMobile" },
{ icon: AiOutlineMoneyCollect, name: "AiOutlineMoneyCollect" },
{ icon: AiOutlineMonitor, name: "AiOutlineMonitor" },
{ icon: AiOutlineMore, name: "AiOutlineMore" },
{ icon: AiOutlineNodeCollapse, name: "AiOutlineNodeCollapse" },
{ icon: AiOutlineNodeExpand, name: "AiOutlineNodeExpand" },
{ icon: AiOutlineNodeIndex, name: "AiOutlineNodeIndex" },
{ icon: AiOutlineNotification, name: "AiOutlineNotification" },
{ icon: AiOutlineNumber, name: "AiOutlineNumber" },
{ icon: AiOutlineOneToOne, name: "AiOutlineOneToOne" },
{ icon: AiOutlineOrderedList, name: "AiOutlineOrderedList" },
{ icon: AiOutlinePaperClip, name: "AiOutlinePaperClip" },
{ icon: AiOutlinePartition, name: "AiOutlinePartition" },
{ icon: AiOutlinePauseCircle, name: "AiOutlinePauseCircle" },
{ icon: AiOutlinePause, name: "AiOutlinePause" },
{ icon: AiOutlinePayCircle, name: "AiOutlinePayCircle" },
{ icon: AiOutlinePercentage, name: "AiOutlinePercentage" },
{ icon: AiOutlinePhone, name: "AiOutlinePhone" },
{ icon: AiOutlinePicCenter, name: "AiOutlinePicCenter" },
{ icon: AiOutlinePicLeft, name: "AiOutlinePicLeft" },
{ icon: AiOutlinePicRight, name: "AiOutlinePicRight" },
{ icon: AiOutlinePicture, name: "AiOutlinePicture" },
{ icon: AiOutlinePieChart, name: "AiOutlinePieChart" },
{ icon: AiOutlinePlayCircle, name: "AiOutlinePlayCircle" },
{ icon: AiOutlinePlaySquare, name: "AiOutlinePlaySquare" },
{ icon: AiOutlinePlusCircle, name: "AiOutlinePlusCircle" },
{ icon: AiOutlinePlusSquare, name: "AiOutlinePlusSquare" },
{ icon: AiOutlinePlus, name: "AiOutlinePlus" },
{ icon: AiOutlinePoundCircle, name: "AiOutlinePoundCircle" },
{ icon: AiOutlinePound, name: "AiOutlinePound" },
{ icon: AiOutlinePoweroff, name: "AiOutlinePoweroff" },
{ icon: AiOutlinePrinter, name: "AiOutlinePrinter" },
{ icon: AiOutlineProfile, name: "AiOutlineProfile" },
{ icon: AiOutlineProject, name: "AiOutlineProject" },
{ icon: AiOutlinePropertySafety, name: "AiOutlinePropertySafety" },
{ icon: AiOutlinePullRequest, name: "AiOutlinePullRequest" },
{ icon: AiOutlinePushpin, name: "AiOutlinePushpin" },
{ icon: AiOutlineQq, name: "AiOutlineQq" },
{ icon: AiOutlineQrcode, name: "AiOutlineQrcode" },
{ icon: AiOutlineQuestionCircle, name: "AiOutlineQuestionCircle" },
{ icon: AiOutlineQuestion, name: "AiOutlineQuestion" },
{ icon: AiOutlineRadarChart, name: "AiOutlineRadarChart" },
{ icon: AiOutlineRadiusBottomleft, name: "AiOutlineRadiusBottomleft" },
{ icon: AiOutlineRadiusBottomright, name: "AiOutlineRadiusBottomright" },
{ icon: AiOutlineRadiusSetting, name: "AiOutlineRadiusSetting" },
{ icon: AiOutlineRadiusUpleft, name: "AiOutlineRadiusUpleft" },
{ icon: AiOutlineRadiusUpright, name: "AiOutlineRadiusUpright" },
{ icon: AiOutlineRead, name: "AiOutlineRead" },
{ icon: AiOutlineReconciliation, name: "AiOutlineReconciliation" },
{ icon: AiOutlineRedEnvelope, name: "AiOutlineRedEnvelope" },
{ icon: AiOutlineReddit, name: "AiOutlineReddit" },
{ icon: AiOutlineRedo, name: "AiOutlineRedo" },
{ icon: AiOutlineReload, name: "AiOutlineReload" },
{ icon: AiOutlineRest, name: "AiOutlineRest" },
{ icon: AiOutlineRetweet, name: "AiOutlineRetweet" },
{ icon: AiOutlineRightCircle, name: "AiOutlineRightCircle" },
{ icon: AiOutlineRightSquare, name: "AiOutlineRightSquare" },
{ icon: AiOutlineRight, name: "AiOutlineRight" },
{ icon: AiOutlineRise, name: "AiOutlineRise" },
{ icon: AiOutlineRobot, name: "AiOutlineRobot" },
{ icon: AiOutlineRocket, name: "AiOutlineRocket" },
{ icon: AiOutlineRollback, name: "AiOutlineRollback" },
{ icon: AiOutlineRotateLeft, name: "AiOutlineRotateLeft" },
{ icon: AiOutlineRotateRight, name: "AiOutlineRotateRight" },
{ icon: AiOutlineSafetyCertificate, name: "AiOutlineSafetyCertificate" },
{ icon: AiOutlineSafety, name: "AiOutlineSafety" },
{ icon: AiOutlineSave, name: "AiOutlineSave" },
{ icon: AiOutlineScan, name: "AiOutlineScan" },
{ icon: AiOutlineSchedule, name: "AiOutlineSchedule" },
{ icon: AiOutlineScissor, name: "AiOutlineScissor" },
{ icon: AiOutlineSearch, name: "AiOutlineSearch" },
{ icon: AiOutlineSecurityScan, name: "AiOutlineSecurityScan" },
{ icon: AiOutlineSelect, name: "AiOutlineSelect" },
{ icon: AiOutlineSend, name: "AiOutlineSend" },
{ icon: AiOutlineSetting, name: "AiOutlineSetting" },
{ icon: AiOutlineShake, name: "AiOutlineShake" },
{ icon: AiOutlineShareAlt, name: "AiOutlineShareAlt" },
{ icon: AiOutlineShop, name: "AiOutlineShop" },
{ icon: AiOutlineShoppingCart, name: "AiOutlineShoppingCart" },
{ icon: AiOutlineShopping, name: "AiOutlineShopping" },
{ icon: AiOutlineShrink, name: "AiOutlineShrink" },
{ icon: AiOutlineSisternode, name: "AiOutlineSisternode" },
{ icon: AiOutlineSketch, name: "AiOutlineSketch" },
{ icon: AiOutlineSkin, name: "AiOutlineSkin" },
{ icon: AiOutlineSkype, name: "AiOutlineSkype" },
{ icon: AiOutlineSlackSquare, name: "AiOutlineSlackSquare" },
{ icon: AiOutlineSlack, name: "AiOutlineSlack" },
{ icon: AiOutlineSliders, name: "AiOutlineSliders" },
{ icon: AiOutlineSmallDash, name: "AiOutlineSmallDash" },
{ icon: AiOutlineSmile, name: "AiOutlineSmile" },
{ icon: AiOutlineSnippets, name: "AiOutlineSnippets" },
{ icon: AiOutlineSolution, name: "AiOutlineSolution" },
{ icon: AiOutlineSortAscending, name: "AiOutlineSortAscending" },
{ icon: AiOutlineSortDescending, name: "AiOutlineSortDescending" },
{ icon: AiOutlineSound, name: "AiOutlineSound" },
{ icon: AiOutlineSplitCells, name: "AiOutlineSplitCells" },
{ icon: AiOutlineStar, name: "AiOutlineStar" },
{ icon: AiOutlineStepBackward, name: "AiOutlineStepBackward" },
{ icon: AiOutlineStepForward, name: "AiOutlineStepForward" },
{ icon: AiOutlineStock, name: "AiOutlineStock" },
{ icon: AiOutlineStop, name: "AiOutlineStop" },
{ icon: AiOutlineStrikethrough, name: "AiOutlineStrikethrough" },
{ icon: AiOutlineSubnode, name: "AiOutlineSubnode" },
{ icon: AiOutlineSwapLeft, name: "AiOutlineSwapLeft" },
{ icon: AiOutlineSwapRight, name: "AiOutlineSwapRight" },
{ icon: AiOutlineSwap, name: "AiOutlineSwap" },
{ icon: AiOutlineSwitcher, name: "AiOutlineSwitcher" },
{ icon: AiOutlineSync, name: "AiOutlineSync" },
{ icon: AiOutlineTable, name: "AiOutlineTable" },
{ icon: AiOutlineTablet, name: "AiOutlineTablet" },
{ icon: AiOutlineTag, name: "AiOutlineTag" },
{ icon: AiOutlineTags, name: "AiOutlineTags" },
{ icon: AiOutlineTaobaoCircle, name: "AiOutlineTaobaoCircle" },
{ icon: AiOutlineTaobao, name: "AiOutlineTaobao" },
{ icon: AiOutlineTeam, name: "AiOutlineTeam" },
{ icon: AiOutlineThunderbolt, name: "AiOutlineThunderbolt" },
{ icon: AiOutlineToTop, name: "AiOutlineToTop" },
{ icon: AiOutlineTool, name: "AiOutlineTool" },
{ icon: AiOutlineTrademarkCircle, name: "AiOutlineTrademarkCircle" },
{ icon: AiOutlineTrademark, name: "AiOutlineTrademark" },
{ icon: AiOutlineTransaction, name: "AiOutlineTransaction" },
{ icon: AiOutlineTranslation, name: "AiOutlineTranslation" },
{ icon: AiOutlineTrophy, name: "AiOutlineTrophy" },
{ icon: AiOutlineTwitter, name: "AiOutlineTwitter" },
{ icon: AiOutlineUnderline, name: "AiOutlineUnderline" },
{ icon: AiOutlineUndo, name: "AiOutlineUndo" },
{ icon: AiOutlineUngroup, name: "AiOutlineUngroup" },
{ icon: AiOutlineUnlock, name: "AiOutlineUnlock" },
{ icon: AiOutlineUnorderedList, name: "AiOutlineUnorderedList" },
{ icon: AiOutlineUpCircle, name: "AiOutlineUpCircle" },
{ icon: AiOutlineUpSquare, name: "AiOutlineUpSquare" },
{ icon: AiOutlineUp, name: "AiOutlineUp" },
{ icon: AiOutlineUpload, name: "AiOutlineUpload" },
{ icon: AiOutlineUsb, name: "AiOutlineUsb" },
{ icon: AiOutlineUserAdd, name: "AiOutlineUserAdd" },
{ icon: AiOutlineUserDelete, name: "AiOutlineUserDelete" },
{ icon: AiOutlineUserSwitch, name: "AiOutlineUserSwitch" },
{ icon: AiOutlineUser, name: "AiOutlineUser" },
{ icon: AiOutlineUsergroupAdd, name: "AiOutlineUsergroupAdd" },
{ icon: AiOutlineUsergroupDelete, name: "AiOutlineUsergroupDelete" },
{ icon: AiOutlineVerified, name: "AiOutlineVerified" },
{ icon: AiOutlineVerticalAlignBottom, name: "AiOutlineVerticalAlignBottom" },
{ icon: AiOutlineVerticalAlignMiddle, name: "AiOutlineVerticalAlignMiddle" },
{ icon: AiOutlineVerticalAlignTop, name: "AiOutlineVerticalAlignTop" },
{ icon: AiOutlineVerticalLeft, name: "AiOutlineVerticalLeft" },
{ icon: AiOutlineVerticalRight, name: "AiOutlineVerticalRight" },
{ icon: AiOutlineVideoCameraAdd, name: "AiOutlineVideoCameraAdd" },
{ icon: AiOutlineVideoCamera, name: "AiOutlineVideoCamera" },
{ icon: AiOutlineWallet, name: "AiOutlineWallet" },
{ icon: AiOutlineWarning, name: "AiOutlineWarning" },
{ icon: AiOutlineWechat, name: "AiOutlineWechat" },
{ icon: AiOutlineWeiboCircle, name: "AiOutlineWeiboCircle" },
{ icon: AiOutlineWeiboSquare, name: "AiOutlineWeiboSquare" },
{ icon: AiOutlineWeibo, name: "AiOutlineWeibo" },
{ icon: AiOutlineWhatsApp, name: "AiOutlineWhatsApp" },
{ icon: AiOutlineWifi, name: "AiOutlineWifi" },
{ icon: AiOutlineWindows, name: "AiOutlineWindows" },
{ icon: AiOutlineWoman, name: "AiOutlineWoman" },
{ icon: AiOutlineYahoo, name: "AiOutlineYahoo" },
{ icon: AiOutlineYoutube, name: "AiOutlineYoutube" },
{ icon: AiOutlineYuque, name: "AiOutlineYuque" },
{ icon: AiOutlineZhihu, name: "AiOutlineZhihu" },
{ icon: AiOutlineZoomIn, name: "AiOutlineZoomIn" },
{ icon: AiOutlineZoomOut, name: "AiOutlineZoomOut" },
{ icon: AiTwotoneAccountBook, name: "AiTwotoneAccountBook" },
{ icon: AiTwotoneAlert, name: "AiTwotoneAlert" },
{ icon: AiTwotoneApi, name: "AiTwotoneApi" },
{ icon: AiTwotoneAppstore, name: "AiTwotoneAppstore" },
{ icon: AiTwotoneAudio, name: "AiTwotoneAudio" },
{ icon: AiTwotoneBank, name: "AiTwotoneBank" },
{ icon: AiTwotoneBell, name: "AiTwotoneBell" },
{ icon: AiTwotoneBook, name: "AiTwotoneBook" },
{ icon: AiTwotoneBoxPlot, name: "AiTwotoneBoxPlot" },
{ icon: AiTwotoneBug, name: "AiTwotoneBug" },
{ icon: AiTwotoneBuild, name: "AiTwotoneBuild" },
{ icon: AiTwotoneBulb, name: "AiTwotoneBulb" },
{ icon: AiTwotoneCalculator, name: "AiTwotoneCalculator" },
{ icon: AiTwotoneCalendar, name: "AiTwotoneCalendar" },
{ icon: AiTwotoneCamera, name: "AiTwotoneCamera" },
{ icon: AiTwotoneCar, name: "AiTwotoneCar" },
{ icon: AiTwotoneCarryOut, name: "AiTwotoneCarryOut" },
{ icon: AiTwotoneCheckCircle, name: "AiTwotoneCheckCircle" },
{ icon: AiTwotoneCheckSquare, name: "AiTwotoneCheckSquare" },
{ icon: AiTwotoneCiCircle, name: "AiTwotoneCiCircle" },
{ icon: AiTwotoneCi, name: "AiTwotoneCi" },
{ icon: AiTwotoneClockCircle, name: "AiTwotoneClockCircle" },
{ icon: AiTwotoneCloseCircle, name: "AiTwotoneCloseCircle" },
{ icon: AiTwotoneCloseSquare, name: "AiTwotoneCloseSquare" },
{ icon: AiTwotoneCloud, name: "AiTwotoneCloud" },
{ icon: AiTwotoneCode, name: "AiTwotoneCode" },
{ icon: AiTwotoneCompass, name: "AiTwotoneCompass" },
{ icon: AiTwotoneContacts, name: "AiTwotoneContacts" },
{ icon: AiTwotoneContainer, name: "AiTwotoneContainer" },
{ icon: AiTwotoneControl, name: "AiTwotoneControl" },
{ icon: AiTwotoneCopy, name: "AiTwotoneCopy" },
{ icon: AiTwotoneCopyrightCircle, name: "AiTwotoneCopyrightCircle" },
{ icon: AiTwotoneCopyright, name: "AiTwotoneCopyright" },
{ icon: AiTwotoneCreditCard, name: "AiTwotoneCreditCard" },
{ icon: AiTwotoneCrown, name: "AiTwotoneCrown" },
{ icon: AiTwotoneCustomerService, name: "AiTwotoneCustomerService" },
{ icon: AiTwotoneDashboard, name: "AiTwotoneDashboard" },
{ icon: AiTwotoneDatabase, name: "AiTwotoneDatabase" },
{ icon: AiTwotoneDelete, name: "AiTwotoneDelete" },
{ icon: AiTwotoneDiff, name: "AiTwotoneDiff" },
{ icon: AiTwotoneDislike, name: "AiTwotoneDislike" },
{ icon: AiTwotoneDollarCircle, name: "AiTwotoneDollarCircle" },
{ icon: AiTwotoneDollar, name: "AiTwotoneDollar" },
{ icon: AiTwotoneDownCircle, name: "AiTwotoneDownCircle" },
{ icon: AiTwotoneDownSquare, name: "AiTwotoneDownSquare" },
{ icon: AiTwotoneEdit, name: "AiTwotoneEdit" },
{ icon: AiTwotoneEnvironment, name: "AiTwotoneEnvironment" },
{ icon: AiTwotoneEuroCircle, name: "AiTwotoneEuroCircle" },
{ icon: AiTwotoneEuro, name: "AiTwotoneEuro" },
{ icon: AiTwotoneExclamationCircle, name: "AiTwotoneExclamationCircle" },
{ icon: AiTwotoneExperiment, name: "AiTwotoneExperiment" },
{ icon: AiTwotoneEyeInvisible, name: "AiTwotoneEyeInvisible" },
{ icon: AiTwotoneEye, name: "AiTwotoneEye" },
{ icon: AiTwotoneFileAdd, name: "AiTwotoneFileAdd" },
{ icon: AiTwotoneFileExcel, name: "AiTwotoneFileExcel" },
{ icon: AiTwotoneFileExclamation, name: "AiTwotoneFileExclamation" },
{ icon: AiTwotoneFileImage, name: "AiTwotoneFileImage" },
{ icon: AiTwotoneFileMarkdown, name: "AiTwotoneFileMarkdown" },
{ icon: AiTwotoneFilePdf, name: "AiTwotoneFilePdf" },
{ icon: AiTwotoneFilePpt, name: "AiTwotoneFilePpt" },
{ icon: AiTwotoneFileText, name: "AiTwotoneFileText" },
{ icon: AiTwotoneFileUnknown, name: "AiTwotoneFileUnknown" },
{ icon: AiTwotoneFileWord, name: "AiTwotoneFileWord" },
{ icon: AiTwotoneFileZip, name: "AiTwotoneFileZip" },
{ icon: AiTwotoneFile, name: "AiTwotoneFile" },
{ icon: AiTwotoneFilter, name: "AiTwotoneFilter" },
{ icon: AiTwotoneFire, name: "AiTwotoneFire" },
{ icon: AiTwotoneFlag, name: "AiTwotoneFlag" },
{ icon: AiTwotoneFolderAdd, name: "AiTwotoneFolderAdd" },
{ icon: AiTwotoneFolderOpen, name: "AiTwotoneFolderOpen" },
{ icon: AiTwotoneFolder, name: "AiTwotoneFolder" },
{ icon: AiTwotoneFrown, name: "AiTwotoneFrown" },
{ icon: AiTwotoneFund, name: "AiTwotoneFund" },
{ icon: AiTwotoneFunnelPlot, name: "AiTwotoneFunnelPlot" },
{ icon: AiTwotoneGift, name: "AiTwotoneGift" },
{ icon: AiTwotoneGold, name: "AiTwotoneGold" },
{ icon: AiTwotoneHdd, name: "AiTwotoneHdd" },
{ icon: AiTwotoneHeart, name: "AiTwotoneHeart" },
{ icon: AiTwotoneHighlight, name: "AiTwotoneHighlight" },
{ icon: AiTwotoneHome, name: "AiTwotoneHome" },
{ icon: AiTwotoneHourglass, name: "AiTwotoneHourglass" },
{ icon: AiTwotoneHtml5, name: "AiTwotoneHtml5" },
{ icon: AiTwotoneIdcard, name: "AiTwotoneIdcard" },
{ icon: AiTwotoneInfoCircle, name: "AiTwotoneInfoCircle" },
{ icon: AiTwotoneInsurance, name: "AiTwotoneInsurance" },
{ icon: AiTwotoneInteraction, name: "AiTwotoneInteraction" },
{ icon: AiTwotoneLayout, name: "AiTwotoneLayout" },
{ icon: AiTwotoneLeftCircle, name: "AiTwotoneLeftCircle" },
{ icon: AiTwotoneLeftSquare, name: "AiTwotoneLeftSquare" },
{ icon: AiTwotoneLike, name: "AiTwotoneLike" },
{ icon: AiTwotoneLock, name: "AiTwotoneLock" },
{ icon: AiTwotoneMail, name: "AiTwotoneMail" },
{ icon: AiTwotoneMedicineBox, name: "AiTwotoneMedicineBox" },
{ icon: AiTwotoneMeh, name: "AiTwotoneMeh" },
{ icon: AiTwotoneMessage, name: "AiTwotoneMessage" },
{ icon: AiTwotoneMinusCircle, name: "AiTwotoneMinusCircle" },
{ icon: AiTwotoneMinusSquare, name: "AiTwotoneMinusSquare" },
{ icon: AiTwotoneMobile, name: "AiTwotoneMobile" },
{ icon: AiTwotoneMoneyCollect, name: "AiTwotoneMoneyCollect" },
{ icon: AiTwotoneNotification, name: "AiTwotoneNotification" },
{ icon: AiTwotonePauseCircle, name: "AiTwotonePauseCircle" },
{ icon: AiTwotonePhone, name: "AiTwotonePhone" },
{ icon: AiTwotonePicture, name: "AiTwotonePicture" },
{ icon: AiTwotonePieChart, name: "AiTwotonePieChart" },
{ icon: AiTwotonePlayCircle, name: "AiTwotonePlayCircle" },
{ icon: AiTwotonePlaySquare, name: "AiTwotonePlaySquare" },
{ icon: AiTwotonePlusCircle, name: "AiTwotonePlusCircle" },
{ icon: AiTwotonePlusSquare, name: "AiTwotonePlusSquare" },
{ icon: AiTwotonePoundCircle, name: "AiTwotonePoundCircle" },
{ icon: AiTwotonePrinter, name: "AiTwotonePrinter" },
{ icon: AiTwotoneProfile, name: "AiTwotoneProfile" },
{ icon: AiTwotoneProject, name: "AiTwotoneProject" },
{ icon: AiTwotonePropertySafety, name: "AiTwotonePropertySafety" },
{ icon: AiTwotonePushpin, name: "AiTwotonePushpin" },
{ icon: AiTwotoneQuestionCircle, name: "AiTwotoneQuestionCircle" },
{ icon: AiTwotoneReconciliation, name: "AiTwotoneReconciliation" },
{ icon: AiTwotoneRedEnvelope, name: "AiTwotoneRedEnvelope" },
{ icon: AiTwotoneRest, name: "AiTwotoneRest" },
{ icon: AiTwotoneRightCircle, name: "AiTwotoneRightCircle" },
{ icon: AiTwotoneRightSquare, name: "AiTwotoneRightSquare" },
{ icon: AiTwotoneRocket, name: "AiTwotoneRocket" },
{ icon: AiTwotoneSafetyCertificate, name: "AiTwotoneSafetyCertificate" },
{ icon: AiTwotoneSave, name: "AiTwotoneSave" },
{ icon: AiTwotoneSchedule, name: "AiTwotoneSchedule" },
{ icon: AiTwotoneSecurityScan, name: "AiTwotoneSecurityScan" },
{ icon: AiTwotoneSetting, name: "AiTwotoneSetting" },
{ icon: AiTwotoneShop, name: "AiTwotoneShop" },
{ icon: AiTwotoneShopping, name: "AiTwotoneShopping" },
{ icon: AiTwotoneSkin, name: "AiTwotoneSkin" },
{ icon: AiTwotoneSliders, name: "AiTwotoneSliders" },
{ icon: AiTwotoneSmile, name: "AiTwotoneSmile" },
{ icon: AiTwotoneSnippets, name: "AiTwotoneSnippets" },
{ icon: AiTwotoneSound, name: "AiTwotoneSound" },
{ icon: AiTwotoneStar, name: "AiTwotoneStar" },
{ icon: AiTwotoneStop, name: "AiTwotoneStop" },
{ icon: AiTwotoneSwitcher, name: "AiTwotoneSwitcher" },
{ icon: AiTwotoneTablet, name: "AiTwotoneTablet" },
{ icon: AiTwotoneTag, name: "AiTwotoneTag" },
{ icon: AiTwotoneTags, name: "AiTwotoneTags" },
{ icon: AiTwotoneThunderbolt, name: "AiTwotoneThunderbolt" },
{ icon: AiTwotoneTool, name: "AiTwotoneTool" },
{ icon: AiTwotoneTrademarkCircle, name: "AiTwotoneTrademarkCircle" },
{ icon: AiTwotoneTrophy, name: "AiTwotoneTrophy" },
{ icon: AiTwotoneUnlock, name: "AiTwotoneUnlock" },
{ icon: AiTwotoneUpCircle, name: "AiTwotoneUpCircle" },
{ icon: AiTwotoneUpSquare, name: "AiTwotoneUpSquare" },
{ icon: AiTwotoneUsb, name: "AiTwotoneUsb" },
{ icon: AiTwotoneVideoCamera, name: "AiTwotoneVideoCamera" },
{ icon: AiTwotoneWallet, name: "AiTwotoneWallet" },
{ icon: AiTwotoneWarning, name: "AiTwotoneWarning" },
];

export default result