import {
	AiFillAccountBook,
	AiFillAlert,
	AiFillAlipayCircle,
	AiFillAlipaySquare,
	AiFillAliwangwang,
	AiFillAmazonCircle,
	AiFillAmazonSquare,
	AiFillAndroid,
	AiFillApi,
	AiFillApple,
	AiFillAppstore,
	AiFillAudio,
	AiFillBackward,
	AiFillBank,
	AiFillBehanceCircle,
	AiFillBehanceSquare,
	AiFillBell,
	AiFillBook,
	AiFillBoxPlot,
	AiFillBug,
	AiFillBuild,
	AiFillBulb,
	AiFillCalculator,
	AiFillCalendar,
	AiFillCamera,
	AiFillCar,
	AiFillCaretDown,
	AiFillCaretLeft,
	AiFillCaretRight,
	AiFillCaretUp,
	AiFillCarryOut,
	AiFillCheckCircle,
	AiFillCheckSquare,
	AiFillChrome,
	AiFillCiCircle,
	AiFillClockCircle,
	AiFillCloseCircle,
	AiFillCloseSquare,
	AiFillCloud,
	AiFillCodeSandboxCircle,
	AiFillCodeSandboxSquare,
	AiFillCode,
	AiFillCodepenCircle,
	AiFillCodepenSquare,
	AiFillCompass,
	AiFillContacts,
	AiFillContainer,
	AiFillControl,
	AiFillCopy,
	AiFillCopyrightCircle,
	AiFillCreditCard,
	AiFillCrown,
	AiFillCustomerService,
	AiFillDashboard,
	AiFillDatabase,
	AiFillDelete,
	AiFillDiff,
	AiFillDingtalkCircle,
	AiFillDingtalkSquare,
	AiFillDislike,
	AiFillDollarCircle,
	AiFillDownCircle,
	AiFillDownSquare,
	AiFillDribbbleCircle,
	AiFillDribbbleSquare,
	AiFillDropboxCircle,
	AiFillDropboxSquare,
	AiFillEdit,
	AiFillEnvironment,
	AiFillEuroCircle,
	AiFillExclamationCircle,
	AiFillExperiment,
	AiFillEyeInvisible,
	AiFillEye,
	AiFillFacebook,
	AiFillFastBackward,
	AiFillFastForward,
	AiFillFileAdd,
	AiFillFileExcel,
	AiFillFileExclamation,
	AiFillFileImage,
	AiFillFileMarkdown,
	AiFillFilePdf,
	AiFillFilePpt,
	AiFillFileText,
	AiFillFileUnknown,
	AiFillFileWord,
	AiFillFileZip,
	AiFillFile,
	AiFillFilter,
	AiFillFire,
	AiFillFlag,
	AiFillFolderAdd,
	AiFillFolderOpen,
	AiFillFolder,
	AiFillFormatPainter,
	AiFillForward,
	AiFillFrown,
	AiFillFund,
	AiFillFunnelPlot,
	AiFillGift,
	AiFillGithub,
	AiFillGitlab,
	AiFillGold,
	AiFillGolden,
	AiFillGoogleCircle,
	AiFillGooglePlusCircle,
	AiFillGooglePlusSquare,
	AiFillGoogleSquare,
	AiFillHdd,
	AiFillHeart,
	AiFillHighlight,
	AiFillHome,
	AiFillHourglass,
	AiFillHtml5,
	AiFillIdcard,
	AiFillIeCircle,
	AiFillIeSquare,
	AiFillInfoCircle,
	AiFillInstagram,
	AiFillInsurance,
	AiFillInteraction,
	AiFillLayout,
	AiFillLeftCircle,
	AiFillLeftSquare,
	AiFillLike,
	AiFillLinkedin,
	AiFillLock,
	AiFillMacCommand,
	AiFillMail,
	AiFillMedicineBox,
	AiFillMediumCircle,
	AiFillMediumSquare,
	AiFillMeh,
	AiFillMessage,
	AiFillMinusCircle,
	AiFillMinusSquare,
	AiFillMobile,
	AiFillMoneyCollect,
	AiFillNotification,
	AiFillPauseCircle,
	AiFillPayCircle,
	AiFillPhone,
	AiFillPicture,
	AiFillPieChart,
	AiFillPlayCircle,
	AiFillPlaySquare,
	AiFillPlusCircle,
	AiFillPlusSquare,
	AiFillPoundCircle,
	AiFillPrinter,
	AiFillProfile,
	AiFillProject,
	AiFillPropertySafety,
	AiFillPushpin,
	AiFillQqCircle,
	AiFillQqSquare,
	AiFillQuestionCircle,
	AiFillRead,
	AiFillReconciliation,
	AiFillRedEnvelope,
	AiFillRedditCircle,
	AiFillRedditSquare,
	AiFillRest,
	AiFillRightCircle,
	AiFillRightSquare,
	AiFillRobot,
	AiFillRocket,
	AiFillSafetyCertificate,
	AiFillSave,
	AiFillSchedule,
	AiFillSecurityScan,
	AiFillSetting,
	AiFillShop,
	AiFillShopping,
	AiFillSignal,
	AiFillSketchCircle,
	AiFillSketchSquare,
	AiFillSkin,
	AiFillSkype,
	AiFillSlackCircle,
	AiFillSlackSquare,
	AiFillSliders,
	AiFillSmile,
	AiFillSnippets,
	AiFillSound,
	AiFillStar,
	AiFillStepBackward,
	AiFillStepForward,
	AiFillStop,
	AiFillSwitcher,
	AiFillTablet,
	AiFillTag,
	AiFillTags,
	AiFillTaobaoCircle,
	AiFillTaobaoSquare,
	AiFillThunderbolt,
	AiFillTool,
	AiFillTrademarkCircle,
	AiFillTrophy,
	AiFillTwitterCircle,
	AiFillTwitterSquare,
	AiFillUnlock,
	AiFillUpCircle,
	AiFillUpSquare,
	AiFillUsb,
	AiFillVideoCamera,
	AiFillWallet,
	AiFillWarning,
	AiFillWechat,
	AiFillWeiboCircle,
	AiFillWeiboSquare,
	AiFillWindows,
	AiFillYahoo,
	AiFillYoutube,
	AiFillYuque,
	AiFillZhihuCircle,
	AiFillZhihuSquare,
	AiOutlineAccountBook,
	AiOutlineAim,
	AiOutlineAlert,
	AiOutlineAlibaba,
	AiOutlineAlignCenter,
	AiOutlineAlignLeft,
	AiOutlineAlignRight,
	AiOutlineAlipayCircle,
	AiOutlineAlipay,
	AiOutlineAliwangwang,
	AiOutlineAliyun,
	AiOutlineAmazon,
	AiOutlineAndroid,
	AiOutlineAntCloud,
	AiOutlineAntDesign,
	AiOutlineApartment,
	AiOutlineApi,
	AiOutlineApple,
	AiOutlineAppstoreAdd,
	AiOutlineAppstore,
	AiOutlineAreaChart,
	AiOutlineArrowDown,
	AiOutlineArrowLeft,
	AiOutlineArrowRight,
	AiOutlineArrowUp,
	AiOutlineArrowsAlt,
	AiOutlineAudioMuted,
	AiOutlineAudio,
	AiOutlineAudit,
	AiOutlineBackward,
	AiOutlineBank,
	AiOutlineBarChart,
	AiOutlineBarcode,
	AiOutlineBars,
	AiOutlineBehanceSquare,
	AiOutlineBehance,
	AiOutlineBell,
	AiOutlineBgColors,
	AiOutlineBlock,
	AiOutlineBold,
	AiOutlineBook,
	AiOutlineBorderBottom,
	AiOutlineBorderHorizontal,
	AiOutlineBorderInner,
	AiOutlineBorderLeft,
	AiOutlineBorderOuter,
	AiOutlineBorderRight,
	AiOutlineBorderTop,
	AiOutlineBorderVerticle,
	AiOutlineBorder,
	AiOutlineBorderlessTable,
	AiOutlineBoxPlot,
	AiOutlineBranches,
	AiOutlineBug,
	AiOutlineBuild,
	AiOutlineBulb,
	AiOutlineCalculator,
	AiOutlineCalendar,
	AiOutlineCamera,
	AiOutlineCar,
	AiOutlineCaretDown,
	AiOutlineCaretLeft,
	AiOutlineCaretRight,
	AiOutlineCaretUp,
	AiOutlineCarryOut,
	AiOutlineCheckCircle,
	AiOutlineCheckSquare,
	AiOutlineCheck,
	AiOutlineChrome,
	AiOutlineCiCircle,
	AiOutlineCi,
	AiOutlineClear,
	AiOutlineClockCircle,
	AiOutlineCloseCircle,
	AiOutlineCloseSquare,
	AiOutlineClose,
	AiOutlineCloudDownload,
	AiOutlineCloudServer,
	AiOutlineCloudSync,
	AiOutlineCloudUpload,
	AiOutlineCloud,
	AiOutlineCluster,
	AiOutlineCodeSandbox,
	AiOutlineCode,
	AiOutlineCodepenCircle,
	AiOutlineCodepen,
	AiOutlineCoffee,
	AiOutlineColumnHeight,
	AiOutlineColumnWidth,
	AiOutlineComment,
	AiOutlineCompass,
	AiOutlineCompress,
	AiOutlineConsoleSql,
	AiOutlineContacts,
	AiOutlineContainer,
	AiOutlineControl,
	AiOutlineCopy,
	AiOutlineCopyrightCircle,
	AiOutlineCopyright,
	AiOutlineCreditCard,
	AiOutlineCrown,
	AiOutlineCustomerService,
	AiOutlineDash,
	AiOutlineDashboard,
	AiOutlineDatabase,
	AiOutlineDeleteColumn,
	AiOutlineDeleteRow,
	AiOutlineDelete,
	AiOutlineDeliveredProcedure,
	AiOutlineDeploymentUnit,
	AiOutlineDesktop,
	AiOutlineDiff,
	AiOutlineDingding,
	AiOutlineDingtalk,
	AiOutlineDisconnect,
	AiOutlineDislike,
	AiOutlineDollarCircle,
	AiOutlineDollar,
	AiOutlineDotChart,
	AiOutlineDoubleLeft,
	AiOutlineDoubleRight,
	AiOutlineDownCircle,
	AiOutlineDownSquare,
	AiOutlineDown,
	AiOutlineDownload,
	AiOutlineDrag,
	AiOutlineDribbbleSquare,
	AiOutlineDribbble,
	AiOutlineDropbox,
	AiOutlineEdit,
	AiOutlineEllipsis,
	AiOutlineEnter,
	AiOutlineEnvironment,
	AiOutlineEuroCircle,
	AiOutlineEuro,
	AiOutlineException,
	AiOutlineExclamationCircle,
	AiOutlineExclamation,
	AiOutlineExpandAlt,
	AiOutlineExpand,
	AiOutlineExperiment,
	AiOutlineExport,
	AiOutlineEyeInvisible,
	AiOutlineEye,
	AiOutlineFacebook,
	AiOutlineFall,
	AiOutlineFastBackward,
	AiOutlineFastForward,
	AiOutlineFieldBinary,
	AiOutlineFieldNumber,
	AiOutlineFieldString,
	AiOutlineFieldTime,
	AiOutlineFileAdd,
	AiOutlineFileDone,
	AiOutlineFileExcel,
	AiOutlineFileExclamation,
	AiOutlineFileGif,
	AiOutlineFileImage,
	AiOutlineFileJpg,
	AiOutlineFileMarkdown,
	AiOutlineFilePdf,
	AiOutlineFilePpt,
	AiOutlineFileProtect,
	AiOutlineFileSearch,
	AiOutlineFileSync,
	AiOutlineFileText,
	AiOutlineFileUnknown,
	AiOutlineFileWord,
	AiOutlineFileZip,
	AiOutlineFile,
	AiOutlineFilter,
	AiOutlineFire,
	AiOutlineFlag,
	AiOutlineFolderAdd,
	AiOutlineFolderOpen,
	AiOutlineFolderView,
	AiOutlineFolder,
	AiOutlineFontColors,
	AiOutlineFontSize,
	AiOutlineFork,
	AiOutlineForm,
	AiOutlineFormatPainter,
	AiOutlineForward,
	AiOutlineFrown,
	AiOutlineFullscreenExit,
	AiOutlineFullscreen,
	AiOutlineFunction,
	AiOutlineFundProjectionScreen,
	AiOutlineFundView,
	AiOutlineFund,
	AiOutlineFunnelPlot,
	AiOutlineGateway,
	AiOutlineGif,
	AiOutlineGift,
	AiOutlineGithub,
	AiOutlineGitlab,
	AiOutlineGlobal,
	AiOutlineGold,
	AiOutlineGooglePlus,
	AiOutlineGoogle,
	AiOutlineGroup,
	AiOutlineHdd,
	AiOutlineHeart,
	AiOutlineHeatMap,
	AiOutlineHighlight,
	AiOutlineHistory,
	AiOutlineHolder,
	AiOutlineHome,
	AiOutlineHourglass,
	AiOutlineHtml5,
	AiOutlineIdcard,
	AiOutlineIe,
	AiOutlineImport,
	AiOutlineInbox,
	AiOutlineInfoCircle,
	AiOutlineInfo,
	AiOutlineInsertRowAbove,
	AiOutlineInsertRowBelow,
	AiOutlineInsertRowLeft,
	AiOutlineInsertRowRight,
	AiOutlineInstagram,
	AiOutlineInsurance,
	AiOutlineInteraction,
	AiOutlineIssuesClose,
	AiOutlineItalic,
	AiOutlineKey,
	AiOutlineLaptop,
	AiOutlineLayout,
	AiOutlineLeftCircle,
	AiOutlineLeftSquare,
	AiOutlineLeft,
	AiOutlineLike,
	AiOutlineLineChart,
	AiOutlineLineHeight,
	AiOutlineLine,
	AiOutlineLink,
	AiOutlineLinkedin,
	AiOutlineLoading3Quarters,
	AiOutlineLoading,
	AiOutlineLock,
	AiOutlineLogin,
	AiOutlineLogout,
	AiOutlineMacCommand,
	AiOutlineMail,
	AiOutlineMan,
	AiOutlineMedicineBox,
	AiOutlineMediumWorkmark,
	AiOutlineMedium,
	AiOutlineMeh,
	AiOutlineMenuFold,
	AiOutlineMenuUnfold,
	AiOutlineMenu,
	AiOutlineMergeCells,
	AiOutlineMessage,
	AiOutlineMinusCircle,
	AiOutlineMinusSquare,
	AiOutlineMinus,
	AiOutlineMobile,
	AiOutlineMoneyCollect,
	AiOutlineMonitor,
	AiOutlineMore,
	AiOutlineNodeCollapse,
	AiOutlineNodeExpand,
	AiOutlineNodeIndex,
	AiOutlineNotification,
	AiOutlineNumber,
	AiOutlineOneToOne,
	AiOutlineOrderedList,
	AiOutlinePaperClip,
	AiOutlinePartition,
	AiOutlinePauseCircle,
	AiOutlinePause,
	AiOutlinePayCircle,
	AiOutlinePercentage,
	AiOutlinePhone,
	AiOutlinePicCenter,
	AiOutlinePicLeft,
	AiOutlinePicRight,
	AiOutlinePicture,
	AiOutlinePieChart,
	AiOutlinePlayCircle,
	AiOutlinePlaySquare,
	AiOutlinePlusCircle,
	AiOutlinePlusSquare,
	AiOutlinePlus,
	AiOutlinePoundCircle,
	AiOutlinePound,
	AiOutlinePoweroff,
	AiOutlinePrinter,
	AiOutlineProfile,
	AiOutlineProject,
	AiOutlinePropertySafety,
	AiOutlinePullRequest,
	AiOutlinePushpin,
	AiOutlineQq,
	AiOutlineQrcode,
	AiOutlineQuestionCircle,
	AiOutlineQuestion,
	AiOutlineRadarChart,
	AiOutlineRadiusBottomleft,
	AiOutlineRadiusBottomright,
	AiOutlineRadiusSetting,
	AiOutlineRadiusUpleft,
	AiOutlineRadiusUpright,
	AiOutlineRead,
	AiOutlineReconciliation,
	AiOutlineRedEnvelope,
	AiOutlineReddit,
	AiOutlineRedo,
	AiOutlineReload,
	AiOutlineRest,
	AiOutlineRetweet,
	AiOutlineRightCircle,
	AiOutlineRightSquare,
	AiOutlineRight,
	AiOutlineRise,
	AiOutlineRobot,
	AiOutlineRocket,
	AiOutlineRollback,
	AiOutlineRotateLeft,
	AiOutlineRotateRight,
	AiOutlineSafetyCertificate,
	AiOutlineSafety,
	AiOutlineSave,
	AiOutlineScan,
	AiOutlineSchedule,
	AiOutlineScissor,
	AiOutlineSearch,
	AiOutlineSecurityScan,
	AiOutlineSelect,
	AiOutlineSend,
	AiOutlineSetting,
	AiOutlineShake,
	AiOutlineShareAlt,
	AiOutlineShop,
	AiOutlineShoppingCart,
	AiOutlineShopping,
	AiOutlineShrink,
	AiOutlineSisternode,
	AiOutlineSketch,
	AiOutlineSkin,
	AiOutlineSkype,
	AiOutlineSlackSquare,
	AiOutlineSlack,
	AiOutlineSliders,
	AiOutlineSmallDash,
	AiOutlineSmile,
	AiOutlineSnippets,
	AiOutlineSolution,
	AiOutlineSortAscending,
	AiOutlineSortDescending,
	AiOutlineSound,
	AiOutlineSplitCells,
	AiOutlineStar,
	AiOutlineStepBackward,
	AiOutlineStepForward,
	AiOutlineStock,
	AiOutlineStop,
	AiOutlineStrikethrough,
	AiOutlineSubnode,
	AiOutlineSwapLeft,
	AiOutlineSwapRight,
	AiOutlineSwap,
	AiOutlineSwitcher,
	AiOutlineSync,
	AiOutlineTable,
	AiOutlineTablet,
	AiOutlineTag,
	AiOutlineTags,
	AiOutlineTaobaoCircle,
	AiOutlineTaobao,
	AiOutlineTeam,
	AiOutlineThunderbolt,
	AiOutlineToTop,
	AiOutlineTool,
	AiOutlineTrademarkCircle,
	AiOutlineTrademark,
	AiOutlineTransaction,
	AiOutlineTranslation,
	AiOutlineTrophy,
	AiOutlineTwitter,
	AiOutlineUnderline,
	AiOutlineUndo,
	AiOutlineUngroup,
	AiOutlineUnlock,
	AiOutlineUnorderedList,
	AiOutlineUpCircle,
	AiOutlineUpSquare,
	AiOutlineUp,
	AiOutlineUpload,
	AiOutlineUsb,
	AiOutlineUserAdd,
	AiOutlineUserDelete,
	AiOutlineUserSwitch,
	AiOutlineUser,
	AiOutlineUsergroupAdd,
	AiOutlineUsergroupDelete,
	AiOutlineVerified,
	AiOutlineVerticalAlignBottom,
	AiOutlineVerticalAlignMiddle,
	AiOutlineVerticalAlignTop,
	AiOutlineVerticalLeft,
	AiOutlineVerticalRight,
	AiOutlineVideoCameraAdd,
	AiOutlineVideoCamera,
	AiOutlineWallet,
	AiOutlineWarning,
	AiOutlineWechat,
	AiOutlineWeiboCircle,
	AiOutlineWeiboSquare,
	AiOutlineWeibo,
	AiOutlineWhatsApp,
	AiOutlineWifi,
	AiOutlineWindows,
	AiOutlineWoman,
	AiOutlineYahoo,
	AiOutlineYoutube,
	AiOutlineYuque,
	AiOutlineZhihu,
	AiOutlineZoomIn,
	AiOutlineZoomOut,
	AiTwotoneAccountBook,
	AiTwotoneAlert,
	AiTwotoneApi,
	AiTwotoneAppstore,
	AiTwotoneAudio,
	AiTwotoneBank,
	AiTwotoneBell,
	AiTwotoneBook,
	AiTwotoneBoxPlot,
	AiTwotoneBug,
	AiTwotoneBuild,
	AiTwotoneBulb,
	AiTwotoneCalculator,
	AiTwotoneCalendar,
	AiTwotoneCamera,
	AiTwotoneCar,
	AiTwotoneCarryOut,
	AiTwotoneCheckCircle,
	AiTwotoneCheckSquare,
	AiTwotoneCiCircle,
	AiTwotoneCi,
	AiTwotoneClockCircle,
	AiTwotoneCloseCircle,
	AiTwotoneCloseSquare,
	AiTwotoneCloud,
	AiTwotoneCode,
	AiTwotoneCompass,
	AiTwotoneContacts,
	AiTwotoneContainer,
	AiTwotoneControl,
	AiTwotoneCopy,
	AiTwotoneCopyrightCircle,
	AiTwotoneCopyright,
	AiTwotoneCreditCard,
	AiTwotoneCrown,
	AiTwotoneCustomerService,
	AiTwotoneDashboard,
	AiTwotoneDatabase,
	AiTwotoneDelete,
	AiTwotoneDiff,
	AiTwotoneDislike,
	AiTwotoneDollarCircle,
	AiTwotoneDollar,
	AiTwotoneDownCircle,
	AiTwotoneDownSquare,
	AiTwotoneEdit,
	AiTwotoneEnvironment,
	AiTwotoneEuroCircle,
	AiTwotoneEuro,
	AiTwotoneExclamationCircle,
	AiTwotoneExperiment,
	AiTwotoneEyeInvisible,
	AiTwotoneEye,
	AiTwotoneFileAdd,
	AiTwotoneFileExcel,
	AiTwotoneFileExclamation,
	AiTwotoneFileImage,
	AiTwotoneFileMarkdown,
	AiTwotoneFilePdf,
	AiTwotoneFilePpt,
	AiTwotoneFileText,
	AiTwotoneFileUnknown,
	AiTwotoneFileWord,
	AiTwotoneFileZip,
	AiTwotoneFile,
	AiTwotoneFilter,
	AiTwotoneFire,
	AiTwotoneFlag,
	AiTwotoneFolderAdd,
	AiTwotoneFolderOpen,
	AiTwotoneFolder,
	AiTwotoneFrown,
	AiTwotoneFund,
	AiTwotoneFunnelPlot,
	AiTwotoneGift,
	AiTwotoneGold,
	AiTwotoneHdd,
	AiTwotoneHeart,
	AiTwotoneHighlight,
	AiTwotoneHome,
	AiTwotoneHourglass,
	AiTwotoneHtml5,
	AiTwotoneIdcard,
	AiTwotoneInfoCircle,
	AiTwotoneInsurance,
	AiTwotoneInteraction,
	AiTwotoneLayout,
	AiTwotoneLeftCircle,
	AiTwotoneLeftSquare,
	AiTwotoneLike,
	AiTwotoneLock,
	AiTwotoneMail,
	AiTwotoneMedicineBox,
	AiTwotoneMeh,
	AiTwotoneMessage,
	AiTwotoneMinusCircle,
	AiTwotoneMinusSquare,
	AiTwotoneMobile,
	AiTwotoneMoneyCollect,
	AiTwotoneNotification,
	AiTwotonePauseCircle,
	AiTwotonePhone,
	AiTwotonePicture,
	AiTwotonePieChart,
	AiTwotonePlayCircle,
	AiTwotonePlaySquare,
	AiTwotonePlusCircle,
	AiTwotonePlusSquare,
	AiTwotonePoundCircle,
	AiTwotonePrinter,
	AiTwotoneProfile,
	AiTwotoneProject,
	AiTwotonePropertySafety,
	AiTwotonePushpin,
	AiTwotoneQuestionCircle,
	AiTwotoneReconciliation,
	AiTwotoneRedEnvelope,
	AiTwotoneRest,
	AiTwotoneRightCircle,
	AiTwotoneRightSquare,
	AiTwotoneRocket,
	AiTwotoneSafetyCertificate,
	AiTwotoneSave,
	AiTwotoneSchedule,
	AiTwotoneSecurityScan,
	AiTwotoneSetting,
	AiTwotoneShop,
	AiTwotoneShopping,
	AiTwotoneSkin,
	AiTwotoneSliders,
	AiTwotoneSmile,
	AiTwotoneSnippets,
	AiTwotoneSound,
	AiTwotoneStar,
	AiTwotoneStop,
	AiTwotoneSwitcher,
	AiTwotoneTablet,
	AiTwotoneTag,
	AiTwotoneTags,
	AiTwotoneThunderbolt,
	AiTwotoneTool,
	AiTwotoneTrademarkCircle,
	AiTwotoneTrophy,
	AiTwotoneUnlock,
	AiTwotoneUpCircle,
	AiTwotoneUpSquare,
	AiTwotoneUsb,
	AiTwotoneVideoCamera,
	AiTwotoneWallet,
	AiTwotoneWarning,
} from "react-icons/ai";

const result = [
	{ icon: AiFillAccountBook, name: "AiFillAccountBook", library: "ai" },
	{ icon: AiFillAlert, name: "AiFillAlert", library: "ai" },
	{ icon: AiFillAlipayCircle, name: "AiFillAlipayCircle", library: "ai" },
	{ icon: AiFillAlipaySquare, name: "AiFillAlipaySquare", library: "ai" },
	{ icon: AiFillAliwangwang, name: "AiFillAliwangwang", library: "ai" },
	{ icon: AiFillAmazonCircle, name: "AiFillAmazonCircle", library: "ai" },
	{ icon: AiFillAmazonSquare, name: "AiFillAmazonSquare", library: "ai" },
	{ icon: AiFillAndroid, name: "AiFillAndroid", library: "ai" },
	{ icon: AiFillApi, name: "AiFillApi", library: "ai" },
	{ icon: AiFillApple, name: "AiFillApple", library: "ai" },
	{ icon: AiFillAppstore, name: "AiFillAppstore", library: "ai" },
	{ icon: AiFillAudio, name: "AiFillAudio", library: "ai" },
	{ icon: AiFillBackward, name: "AiFillBackward", library: "ai" },
	{ icon: AiFillBank, name: "AiFillBank", library: "ai" },
	{ icon: AiFillBehanceCircle, name: "AiFillBehanceCircle", library: "ai" },
	{ icon: AiFillBehanceSquare, name: "AiFillBehanceSquare", library: "ai" },
	{ icon: AiFillBell, name: "AiFillBell", library: "ai" },
	{ icon: AiFillBook, name: "AiFillBook", library: "ai" },
	{ icon: AiFillBoxPlot, name: "AiFillBoxPlot", library: "ai" },
	{ icon: AiFillBug, name: "AiFillBug", library: "ai" },
	{ icon: AiFillBuild, name: "AiFillBuild", library: "ai" },
	{ icon: AiFillBulb, name: "AiFillBulb", library: "ai" },
	{ icon: AiFillCalculator, name: "AiFillCalculator", library: "ai" },
	{ icon: AiFillCalendar, name: "AiFillCalendar", library: "ai" },
	{ icon: AiFillCamera, name: "AiFillCamera", library: "ai" },
	{ icon: AiFillCar, name: "AiFillCar", library: "ai" },
	{ icon: AiFillCaretDown, name: "AiFillCaretDown", library: "ai" },
	{ icon: AiFillCaretLeft, name: "AiFillCaretLeft", library: "ai" },
	{ icon: AiFillCaretRight, name: "AiFillCaretRight", library: "ai" },
	{ icon: AiFillCaretUp, name: "AiFillCaretUp", library: "ai" },
	{ icon: AiFillCarryOut, name: "AiFillCarryOut", library: "ai" },
	{ icon: AiFillCheckCircle, name: "AiFillCheckCircle", library: "ai" },
	{ icon: AiFillCheckSquare, name: "AiFillCheckSquare", library: "ai" },
	{ icon: AiFillChrome, name: "AiFillChrome", library: "ai" },
	{ icon: AiFillCiCircle, name: "AiFillCiCircle", library: "ai" },
	{ icon: AiFillClockCircle, name: "AiFillClockCircle", library: "ai" },
	{ icon: AiFillCloseCircle, name: "AiFillCloseCircle", library: "ai" },
	{ icon: AiFillCloseSquare, name: "AiFillCloseSquare", library: "ai" },
	{ icon: AiFillCloud, name: "AiFillCloud", library: "ai" },
	{ icon: AiFillCodeSandboxCircle, name: "AiFillCodeSandboxCircle", library: "ai" },
	{ icon: AiFillCodeSandboxSquare, name: "AiFillCodeSandboxSquare", library: "ai" },
	{ icon: AiFillCode, name: "AiFillCode", library: "ai" },
	{ icon: AiFillCodepenCircle, name: "AiFillCodepenCircle", library: "ai" },
	{ icon: AiFillCodepenSquare, name: "AiFillCodepenSquare", library: "ai" },
	{ icon: AiFillCompass, name: "AiFillCompass", library: "ai" },
	{ icon: AiFillContacts, name: "AiFillContacts", library: "ai" },
	{ icon: AiFillContainer, name: "AiFillContainer", library: "ai" },
	{ icon: AiFillControl, name: "AiFillControl", library: "ai" },
	{ icon: AiFillCopy, name: "AiFillCopy", library: "ai" },
	{ icon: AiFillCopyrightCircle, name: "AiFillCopyrightCircle", library: "ai" },
	{ icon: AiFillCreditCard, name: "AiFillCreditCard", library: "ai" },
	{ icon: AiFillCrown, name: "AiFillCrown", library: "ai" },
	{ icon: AiFillCustomerService, name: "AiFillCustomerService", library: "ai" },
	{ icon: AiFillDashboard, name: "AiFillDashboard", library: "ai" },
	{ icon: AiFillDatabase, name: "AiFillDatabase", library: "ai" },
	{ icon: AiFillDelete, name: "AiFillDelete", library: "ai" },
	{ icon: AiFillDiff, name: "AiFillDiff", library: "ai" },
	{ icon: AiFillDingtalkCircle, name: "AiFillDingtalkCircle", library: "ai" },
	{ icon: AiFillDingtalkSquare, name: "AiFillDingtalkSquare", library: "ai" },
	{ icon: AiFillDislike, name: "AiFillDislike", library: "ai" },
	{ icon: AiFillDollarCircle, name: "AiFillDollarCircle", library: "ai" },
	{ icon: AiFillDownCircle, name: "AiFillDownCircle", library: "ai" },
	{ icon: AiFillDownSquare, name: "AiFillDownSquare", library: "ai" },
	{ icon: AiFillDribbbleCircle, name: "AiFillDribbbleCircle", library: "ai" },
	{ icon: AiFillDribbbleSquare, name: "AiFillDribbbleSquare", library: "ai" },
	{ icon: AiFillDropboxCircle, name: "AiFillDropboxCircle", library: "ai" },
	{ icon: AiFillDropboxSquare, name: "AiFillDropboxSquare", library: "ai" },
	{ icon: AiFillEdit, name: "AiFillEdit", library: "ai" },
	{ icon: AiFillEnvironment, name: "AiFillEnvironment", library: "ai" },
	{ icon: AiFillEuroCircle, name: "AiFillEuroCircle", library: "ai" },
	{ icon: AiFillExclamationCircle, name: "AiFillExclamationCircle", library: "ai" },
	{ icon: AiFillExperiment, name: "AiFillExperiment", library: "ai" },
	{ icon: AiFillEyeInvisible, name: "AiFillEyeInvisible", library: "ai" },
	{ icon: AiFillEye, name: "AiFillEye", library: "ai" },
	{ icon: AiFillFacebook, name: "AiFillFacebook", library: "ai" },
	{ icon: AiFillFastBackward, name: "AiFillFastBackward", library: "ai" },
	{ icon: AiFillFastForward, name: "AiFillFastForward", library: "ai" },
	{ icon: AiFillFileAdd, name: "AiFillFileAdd", library: "ai" },
	{ icon: AiFillFileExcel, name: "AiFillFileExcel", library: "ai" },
	{ icon: AiFillFileExclamation, name: "AiFillFileExclamation", library: "ai" },
	{ icon: AiFillFileImage, name: "AiFillFileImage", library: "ai" },
	{ icon: AiFillFileMarkdown, name: "AiFillFileMarkdown", library: "ai" },
	{ icon: AiFillFilePdf, name: "AiFillFilePdf", library: "ai" },
	{ icon: AiFillFilePpt, name: "AiFillFilePpt", library: "ai" },
	{ icon: AiFillFileText, name: "AiFillFileText", library: "ai" },
	{ icon: AiFillFileUnknown, name: "AiFillFileUnknown", library: "ai" },
	{ icon: AiFillFileWord, name: "AiFillFileWord", library: "ai" },
	{ icon: AiFillFileZip, name: "AiFillFileZip", library: "ai" },
	{ icon: AiFillFile, name: "AiFillFile", library: "ai" },
	{ icon: AiFillFilter, name: "AiFillFilter", library: "ai" },
	{ icon: AiFillFire, name: "AiFillFire", library: "ai" },
	{ icon: AiFillFlag, name: "AiFillFlag", library: "ai" },
	{ icon: AiFillFolderAdd, name: "AiFillFolderAdd", library: "ai" },
	{ icon: AiFillFolderOpen, name: "AiFillFolderOpen", library: "ai" },
	{ icon: AiFillFolder, name: "AiFillFolder", library: "ai" },
	{ icon: AiFillFormatPainter, name: "AiFillFormatPainter", library: "ai" },
	{ icon: AiFillForward, name: "AiFillForward", library: "ai" },
	{ icon: AiFillFrown, name: "AiFillFrown", library: "ai" },
	{ icon: AiFillFund, name: "AiFillFund", library: "ai" },
	{ icon: AiFillFunnelPlot, name: "AiFillFunnelPlot", library: "ai" },
	{ icon: AiFillGift, name: "AiFillGift", library: "ai" },
	{ icon: AiFillGithub, name: "AiFillGithub", library: "ai" },
	{ icon: AiFillGitlab, name: "AiFillGitlab", library: "ai" },
	{ icon: AiFillGold, name: "AiFillGold", library: "ai" },
	{ icon: AiFillGolden, name: "AiFillGolden", library: "ai" },
	{ icon: AiFillGoogleCircle, name: "AiFillGoogleCircle", library: "ai" },
	{ icon: AiFillGooglePlusCircle, name: "AiFillGooglePlusCircle", library: "ai" },
	{ icon: AiFillGooglePlusSquare, name: "AiFillGooglePlusSquare", library: "ai" },
	{ icon: AiFillGoogleSquare, name: "AiFillGoogleSquare", library: "ai" },
	{ icon: AiFillHdd, name: "AiFillHdd", library: "ai" },
	{ icon: AiFillHeart, name: "AiFillHeart", library: "ai" },
	{ icon: AiFillHighlight, name: "AiFillHighlight", library: "ai" },
	{ icon: AiFillHome, name: "AiFillHome", library: "ai" },
	{ icon: AiFillHourglass, name: "AiFillHourglass", library: "ai" },
	{ icon: AiFillHtml5, name: "AiFillHtml5", library: "ai" },
	{ icon: AiFillIdcard, name: "AiFillIdcard", library: "ai" },
	{ icon: AiFillIeCircle, name: "AiFillIeCircle", library: "ai" },
	{ icon: AiFillIeSquare, name: "AiFillIeSquare", library: "ai" },
	{ icon: AiFillInfoCircle, name: "AiFillInfoCircle", library: "ai" },
	{ icon: AiFillInstagram, name: "AiFillInstagram", library: "ai" },
	{ icon: AiFillInsurance, name: "AiFillInsurance", library: "ai" },
	{ icon: AiFillInteraction, name: "AiFillInteraction", library: "ai" },
	{ icon: AiFillLayout, name: "AiFillLayout", library: "ai" },
	{ icon: AiFillLeftCircle, name: "AiFillLeftCircle", library: "ai" },
	{ icon: AiFillLeftSquare, name: "AiFillLeftSquare", library: "ai" },
	{ icon: AiFillLike, name: "AiFillLike", library: "ai" },
	{ icon: AiFillLinkedin, name: "AiFillLinkedin", library: "ai" },
	{ icon: AiFillLock, name: "AiFillLock", library: "ai" },
	{ icon: AiFillMacCommand, name: "AiFillMacCommand", library: "ai" },
	{ icon: AiFillMail, name: "AiFillMail", library: "ai" },
	{ icon: AiFillMedicineBox, name: "AiFillMedicineBox", library: "ai" },
	{ icon: AiFillMediumCircle, name: "AiFillMediumCircle", library: "ai" },
	{ icon: AiFillMediumSquare, name: "AiFillMediumSquare", library: "ai" },
	{ icon: AiFillMeh, name: "AiFillMeh", library: "ai" },
	{ icon: AiFillMessage, name: "AiFillMessage", library: "ai" },
	{ icon: AiFillMinusCircle, name: "AiFillMinusCircle", library: "ai" },
	{ icon: AiFillMinusSquare, name: "AiFillMinusSquare", library: "ai" },
	{ icon: AiFillMobile, name: "AiFillMobile", library: "ai" },
	{ icon: AiFillMoneyCollect, name: "AiFillMoneyCollect", library: "ai" },
	{ icon: AiFillNotification, name: "AiFillNotification", library: "ai" },
	{ icon: AiFillPauseCircle, name: "AiFillPauseCircle", library: "ai" },
	{ icon: AiFillPayCircle, name: "AiFillPayCircle", library: "ai" },
	{ icon: AiFillPhone, name: "AiFillPhone", library: "ai" },
	{ icon: AiFillPicture, name: "AiFillPicture", library: "ai" },
	{ icon: AiFillPieChart, name: "AiFillPieChart", library: "ai" },
	{ icon: AiFillPlayCircle, name: "AiFillPlayCircle", library: "ai" },
	{ icon: AiFillPlaySquare, name: "AiFillPlaySquare", library: "ai" },
	{ icon: AiFillPlusCircle, name: "AiFillPlusCircle", library: "ai" },
	{ icon: AiFillPlusSquare, name: "AiFillPlusSquare", library: "ai" },
	{ icon: AiFillPoundCircle, name: "AiFillPoundCircle", library: "ai" },
	{ icon: AiFillPrinter, name: "AiFillPrinter", library: "ai" },
	{ icon: AiFillProfile, name: "AiFillProfile", library: "ai" },
	{ icon: AiFillProject, name: "AiFillProject", library: "ai" },
	{ icon: AiFillPropertySafety, name: "AiFillPropertySafety", library: "ai" },
	{ icon: AiFillPushpin, name: "AiFillPushpin", library: "ai" },
	{ icon: AiFillQqCircle, name: "AiFillQqCircle", library: "ai" },
	{ icon: AiFillQqSquare, name: "AiFillQqSquare", library: "ai" },
	{ icon: AiFillQuestionCircle, name: "AiFillQuestionCircle", library: "ai" },
	{ icon: AiFillRead, name: "AiFillRead", library: "ai" },
	{ icon: AiFillReconciliation, name: "AiFillReconciliation", library: "ai" },
	{ icon: AiFillRedEnvelope, name: "AiFillRedEnvelope", library: "ai" },
	{ icon: AiFillRedditCircle, name: "AiFillRedditCircle", library: "ai" },
	{ icon: AiFillRedditSquare, name: "AiFillRedditSquare", library: "ai" },
	{ icon: AiFillRest, name: "AiFillRest", library: "ai" },
	{ icon: AiFillRightCircle, name: "AiFillRightCircle", library: "ai" },
	{ icon: AiFillRightSquare, name: "AiFillRightSquare", library: "ai" },
	{ icon: AiFillRobot, name: "AiFillRobot", library: "ai" },
	{ icon: AiFillRocket, name: "AiFillRocket", library: "ai" },
	{ icon: AiFillSafetyCertificate, name: "AiFillSafetyCertificate", library: "ai" },
	{ icon: AiFillSave, name: "AiFillSave", library: "ai" },
	{ icon: AiFillSchedule, name: "AiFillSchedule", library: "ai" },
	{ icon: AiFillSecurityScan, name: "AiFillSecurityScan", library: "ai" },
	{ icon: AiFillSetting, name: "AiFillSetting", library: "ai" },
	{ icon: AiFillShop, name: "AiFillShop", library: "ai" },
	{ icon: AiFillShopping, name: "AiFillShopping", library: "ai" },
	{ icon: AiFillSignal, name: "AiFillSignal", library: "ai" },
	{ icon: AiFillSketchCircle, name: "AiFillSketchCircle", library: "ai" },
	{ icon: AiFillSketchSquare, name: "AiFillSketchSquare", library: "ai" },
	{ icon: AiFillSkin, name: "AiFillSkin", library: "ai" },
	{ icon: AiFillSkype, name: "AiFillSkype", library: "ai" },
	{ icon: AiFillSlackCircle, name: "AiFillSlackCircle", library: "ai" },
	{ icon: AiFillSlackSquare, name: "AiFillSlackSquare", library: "ai" },
	{ icon: AiFillSliders, name: "AiFillSliders", library: "ai" },
	{ icon: AiFillSmile, name: "AiFillSmile", library: "ai" },
	{ icon: AiFillSnippets, name: "AiFillSnippets", library: "ai" },
	{ icon: AiFillSound, name: "AiFillSound", library: "ai" },
	{ icon: AiFillStar, name: "AiFillStar", library: "ai" },
	{ icon: AiFillStepBackward, name: "AiFillStepBackward", library: "ai" },
	{ icon: AiFillStepForward, name: "AiFillStepForward", library: "ai" },
	{ icon: AiFillStop, name: "AiFillStop", library: "ai" },
	{ icon: AiFillSwitcher, name: "AiFillSwitcher", library: "ai" },
	{ icon: AiFillTablet, name: "AiFillTablet", library: "ai" },
	{ icon: AiFillTag, name: "AiFillTag", library: "ai" },
	{ icon: AiFillTags, name: "AiFillTags", library: "ai" },
	{ icon: AiFillTaobaoCircle, name: "AiFillTaobaoCircle", library: "ai" },
	{ icon: AiFillTaobaoSquare, name: "AiFillTaobaoSquare", library: "ai" },
	{ icon: AiFillThunderbolt, name: "AiFillThunderbolt", library: "ai" },
	{ icon: AiFillTool, name: "AiFillTool", library: "ai" },
	{ icon: AiFillTrademarkCircle, name: "AiFillTrademarkCircle", library: "ai" },
	{ icon: AiFillTrophy, name: "AiFillTrophy", library: "ai" },
	{ icon: AiFillTwitterCircle, name: "AiFillTwitterCircle", library: "ai" },
	{ icon: AiFillTwitterSquare, name: "AiFillTwitterSquare", library: "ai" },
	{ icon: AiFillUnlock, name: "AiFillUnlock", library: "ai" },
	{ icon: AiFillUpCircle, name: "AiFillUpCircle", library: "ai" },
	{ icon: AiFillUpSquare, name: "AiFillUpSquare", library: "ai" },
	{ icon: AiFillUsb, name: "AiFillUsb", library: "ai" },
	{ icon: AiFillVideoCamera, name: "AiFillVideoCamera", library: "ai" },
	{ icon: AiFillWallet, name: "AiFillWallet", library: "ai" },
	{ icon: AiFillWarning, name: "AiFillWarning", library: "ai" },
	{ icon: AiFillWechat, name: "AiFillWechat", library: "ai" },
	{ icon: AiFillWeiboCircle, name: "AiFillWeiboCircle", library: "ai" },
	{ icon: AiFillWeiboSquare, name: "AiFillWeiboSquare", library: "ai" },
	{ icon: AiFillWindows, name: "AiFillWindows", library: "ai" },
	{ icon: AiFillYahoo, name: "AiFillYahoo", library: "ai" },
	{ icon: AiFillYoutube, name: "AiFillYoutube", library: "ai" },
	{ icon: AiFillYuque, name: "AiFillYuque", library: "ai" },
	{ icon: AiFillZhihuCircle, name: "AiFillZhihuCircle", library: "ai" },
	{ icon: AiFillZhihuSquare, name: "AiFillZhihuSquare", library: "ai" },
	{ icon: AiOutlineAccountBook, name: "AiOutlineAccountBook", library: "ai" },
	{ icon: AiOutlineAim, name: "AiOutlineAim", library: "ai" },
	{ icon: AiOutlineAlert, name: "AiOutlineAlert", library: "ai" },
	{ icon: AiOutlineAlibaba, name: "AiOutlineAlibaba", library: "ai" },
	{ icon: AiOutlineAlignCenter, name: "AiOutlineAlignCenter", library: "ai" },
	{ icon: AiOutlineAlignLeft, name: "AiOutlineAlignLeft", library: "ai" },
	{ icon: AiOutlineAlignRight, name: "AiOutlineAlignRight", library: "ai" },
	{ icon: AiOutlineAlipayCircle, name: "AiOutlineAlipayCircle", library: "ai" },
	{ icon: AiOutlineAlipay, name: "AiOutlineAlipay", library: "ai" },
	{ icon: AiOutlineAliwangwang, name: "AiOutlineAliwangwang", library: "ai" },
	{ icon: AiOutlineAliyun, name: "AiOutlineAliyun", library: "ai" },
	{ icon: AiOutlineAmazon, name: "AiOutlineAmazon", library: "ai" },
	{ icon: AiOutlineAndroid, name: "AiOutlineAndroid", library: "ai" },
	{ icon: AiOutlineAntCloud, name: "AiOutlineAntCloud", library: "ai" },
	{ icon: AiOutlineAntDesign, name: "AiOutlineAntDesign", library: "ai" },
	{ icon: AiOutlineApartment, name: "AiOutlineApartment", library: "ai" },
	{ icon: AiOutlineApi, name: "AiOutlineApi", library: "ai" },
	{ icon: AiOutlineApple, name: "AiOutlineApple", library: "ai" },
	{ icon: AiOutlineAppstoreAdd, name: "AiOutlineAppstoreAdd", library: "ai" },
	{ icon: AiOutlineAppstore, name: "AiOutlineAppstore", library: "ai" },
	{ icon: AiOutlineAreaChart, name: "AiOutlineAreaChart", library: "ai" },
	{ icon: AiOutlineArrowDown, name: "AiOutlineArrowDown", library: "ai" },
	{ icon: AiOutlineArrowLeft, name: "AiOutlineArrowLeft", library: "ai" },
	{ icon: AiOutlineArrowRight, name: "AiOutlineArrowRight", library: "ai" },
	{ icon: AiOutlineArrowUp, name: "AiOutlineArrowUp", library: "ai" },
	{ icon: AiOutlineArrowsAlt, name: "AiOutlineArrowsAlt", library: "ai" },
	{ icon: AiOutlineAudioMuted, name: "AiOutlineAudioMuted", library: "ai" },
	{ icon: AiOutlineAudio, name: "AiOutlineAudio", library: "ai" },
	{ icon: AiOutlineAudit, name: "AiOutlineAudit", library: "ai" },
	{ icon: AiOutlineBackward, name: "AiOutlineBackward", library: "ai" },
	{ icon: AiOutlineBank, name: "AiOutlineBank", library: "ai" },
	{ icon: AiOutlineBarChart, name: "AiOutlineBarChart", library: "ai" },
	{ icon: AiOutlineBarcode, name: "AiOutlineBarcode", library: "ai" },
	{ icon: AiOutlineBars, name: "AiOutlineBars", library: "ai" },
	{ icon: AiOutlineBehanceSquare, name: "AiOutlineBehanceSquare", library: "ai" },
	{ icon: AiOutlineBehance, name: "AiOutlineBehance", library: "ai" },
	{ icon: AiOutlineBell, name: "AiOutlineBell", library: "ai" },
	{ icon: AiOutlineBgColors, name: "AiOutlineBgColors", library: "ai" },
	{ icon: AiOutlineBlock, name: "AiOutlineBlock", library: "ai" },
	{ icon: AiOutlineBold, name: "AiOutlineBold", library: "ai" },
	{ icon: AiOutlineBook, name: "AiOutlineBook", library: "ai" },
	{ icon: AiOutlineBorderBottom, name: "AiOutlineBorderBottom", library: "ai" },
	{ icon: AiOutlineBorderHorizontal, name: "AiOutlineBorderHorizontal", library: "ai" },
	{ icon: AiOutlineBorderInner, name: "AiOutlineBorderInner", library: "ai" },
	{ icon: AiOutlineBorderLeft, name: "AiOutlineBorderLeft", library: "ai" },
	{ icon: AiOutlineBorderOuter, name: "AiOutlineBorderOuter", library: "ai" },
	{ icon: AiOutlineBorderRight, name: "AiOutlineBorderRight", library: "ai" },
	{ icon: AiOutlineBorderTop, name: "AiOutlineBorderTop", library: "ai" },
	{ icon: AiOutlineBorderVerticle, name: "AiOutlineBorderVerticle", library: "ai" },
	{ icon: AiOutlineBorder, name: "AiOutlineBorder", library: "ai" },
	{ icon: AiOutlineBorderlessTable, name: "AiOutlineBorderlessTable", library: "ai" },
	{ icon: AiOutlineBoxPlot, name: "AiOutlineBoxPlot", library: "ai" },
	{ icon: AiOutlineBranches, name: "AiOutlineBranches", library: "ai" },
	{ icon: AiOutlineBug, name: "AiOutlineBug", library: "ai" },
	{ icon: AiOutlineBuild, name: "AiOutlineBuild", library: "ai" },
	{ icon: AiOutlineBulb, name: "AiOutlineBulb", library: "ai" },
	{ icon: AiOutlineCalculator, name: "AiOutlineCalculator", library: "ai" },
	{ icon: AiOutlineCalendar, name: "AiOutlineCalendar", library: "ai" },
	{ icon: AiOutlineCamera, name: "AiOutlineCamera", library: "ai" },
	{ icon: AiOutlineCar, name: "AiOutlineCar", library: "ai" },
	{ icon: AiOutlineCaretDown, name: "AiOutlineCaretDown", library: "ai" },
	{ icon: AiOutlineCaretLeft, name: "AiOutlineCaretLeft", library: "ai" },
	{ icon: AiOutlineCaretRight, name: "AiOutlineCaretRight", library: "ai" },
	{ icon: AiOutlineCaretUp, name: "AiOutlineCaretUp", library: "ai" },
	{ icon: AiOutlineCarryOut, name: "AiOutlineCarryOut", library: "ai" },
	{ icon: AiOutlineCheckCircle, name: "AiOutlineCheckCircle", library: "ai" },
	{ icon: AiOutlineCheckSquare, name: "AiOutlineCheckSquare", library: "ai" },
	{ icon: AiOutlineCheck, name: "AiOutlineCheck", library: "ai" },
	{ icon: AiOutlineChrome, name: "AiOutlineChrome", library: "ai" },
	{ icon: AiOutlineCiCircle, name: "AiOutlineCiCircle", library: "ai" },
	{ icon: AiOutlineCi, name: "AiOutlineCi", library: "ai" },
	{ icon: AiOutlineClear, name: "AiOutlineClear", library: "ai" },
	{ icon: AiOutlineClockCircle, name: "AiOutlineClockCircle", library: "ai" },
	{ icon: AiOutlineCloseCircle, name: "AiOutlineCloseCircle", library: "ai" },
	{ icon: AiOutlineCloseSquare, name: "AiOutlineCloseSquare", library: "ai" },
	{ icon: AiOutlineClose, name: "AiOutlineClose", library: "ai" },
	{ icon: AiOutlineCloudDownload, name: "AiOutlineCloudDownload", library: "ai" },
	{ icon: AiOutlineCloudServer, name: "AiOutlineCloudServer", library: "ai" },
	{ icon: AiOutlineCloudSync, name: "AiOutlineCloudSync", library: "ai" },
	{ icon: AiOutlineCloudUpload, name: "AiOutlineCloudUpload", library: "ai" },
	{ icon: AiOutlineCloud, name: "AiOutlineCloud", library: "ai" },
	{ icon: AiOutlineCluster, name: "AiOutlineCluster", library: "ai" },
	{ icon: AiOutlineCodeSandbox, name: "AiOutlineCodeSandbox", library: "ai" },
	{ icon: AiOutlineCode, name: "AiOutlineCode", library: "ai" },
	{ icon: AiOutlineCodepenCircle, name: "AiOutlineCodepenCircle", library: "ai" },
	{ icon: AiOutlineCodepen, name: "AiOutlineCodepen", library: "ai" },
	{ icon: AiOutlineCoffee, name: "AiOutlineCoffee", library: "ai" },
	{ icon: AiOutlineColumnHeight, name: "AiOutlineColumnHeight", library: "ai" },
	{ icon: AiOutlineColumnWidth, name: "AiOutlineColumnWidth", library: "ai" },
	{ icon: AiOutlineComment, name: "AiOutlineComment", library: "ai" },
	{ icon: AiOutlineCompass, name: "AiOutlineCompass", library: "ai" },
	{ icon: AiOutlineCompress, name: "AiOutlineCompress", library: "ai" },
	{ icon: AiOutlineConsoleSql, name: "AiOutlineConsoleSql", library: "ai" },
	{ icon: AiOutlineContacts, name: "AiOutlineContacts", library: "ai" },
	{ icon: AiOutlineContainer, name: "AiOutlineContainer", library: "ai" },
	{ icon: AiOutlineControl, name: "AiOutlineControl", library: "ai" },
	{ icon: AiOutlineCopy, name: "AiOutlineCopy", library: "ai" },
	{ icon: AiOutlineCopyrightCircle, name: "AiOutlineCopyrightCircle", library: "ai" },
	{ icon: AiOutlineCopyright, name: "AiOutlineCopyright", library: "ai" },
	{ icon: AiOutlineCreditCard, name: "AiOutlineCreditCard", library: "ai" },
	{ icon: AiOutlineCrown, name: "AiOutlineCrown", library: "ai" },
	{ icon: AiOutlineCustomerService, name: "AiOutlineCustomerService", library: "ai" },
	{ icon: AiOutlineDash, name: "AiOutlineDash", library: "ai" },
	{ icon: AiOutlineDashboard, name: "AiOutlineDashboard", library: "ai" },
	{ icon: AiOutlineDatabase, name: "AiOutlineDatabase", library: "ai" },
	{ icon: AiOutlineDeleteColumn, name: "AiOutlineDeleteColumn", library: "ai" },
	{ icon: AiOutlineDeleteRow, name: "AiOutlineDeleteRow", library: "ai" },
	{ icon: AiOutlineDelete, name: "AiOutlineDelete", library: "ai" },
	{
		icon: AiOutlineDeliveredProcedure,
		name: "AiOutlineDeliveredProcedure",
		library: "ai",
	},
	{ icon: AiOutlineDeploymentUnit, name: "AiOutlineDeploymentUnit", library: "ai" },
	{ icon: AiOutlineDesktop, name: "AiOutlineDesktop", library: "ai" },
	{ icon: AiOutlineDiff, name: "AiOutlineDiff", library: "ai" },
	{ icon: AiOutlineDingding, name: "AiOutlineDingding", library: "ai" },
	{ icon: AiOutlineDingtalk, name: "AiOutlineDingtalk", library: "ai" },
	{ icon: AiOutlineDisconnect, name: "AiOutlineDisconnect", library: "ai" },
	{ icon: AiOutlineDislike, name: "AiOutlineDislike", library: "ai" },
	{ icon: AiOutlineDollarCircle, name: "AiOutlineDollarCircle", library: "ai" },
	{ icon: AiOutlineDollar, name: "AiOutlineDollar", library: "ai" },
	{ icon: AiOutlineDotChart, name: "AiOutlineDotChart", library: "ai" },
	{ icon: AiOutlineDoubleLeft, name: "AiOutlineDoubleLeft", library: "ai" },
	{ icon: AiOutlineDoubleRight, name: "AiOutlineDoubleRight", library: "ai" },
	{ icon: AiOutlineDownCircle, name: "AiOutlineDownCircle", library: "ai" },
	{ icon: AiOutlineDownSquare, name: "AiOutlineDownSquare", library: "ai" },
	{ icon: AiOutlineDown, name: "AiOutlineDown", library: "ai" },
	{ icon: AiOutlineDownload, name: "AiOutlineDownload", library: "ai" },
	{ icon: AiOutlineDrag, name: "AiOutlineDrag", library: "ai" },
	{ icon: AiOutlineDribbbleSquare, name: "AiOutlineDribbbleSquare", library: "ai" },
	{ icon: AiOutlineDribbble, name: "AiOutlineDribbble", library: "ai" },
	{ icon: AiOutlineDropbox, name: "AiOutlineDropbox", library: "ai" },
	{ icon: AiOutlineEdit, name: "AiOutlineEdit", library: "ai" },
	{ icon: AiOutlineEllipsis, name: "AiOutlineEllipsis", library: "ai" },
	{ icon: AiOutlineEnter, name: "AiOutlineEnter", library: "ai" },
	{ icon: AiOutlineEnvironment, name: "AiOutlineEnvironment", library: "ai" },
	{ icon: AiOutlineEuroCircle, name: "AiOutlineEuroCircle", library: "ai" },
	{ icon: AiOutlineEuro, name: "AiOutlineEuro", library: "ai" },
	{ icon: AiOutlineException, name: "AiOutlineException", library: "ai" },
	{
		icon: AiOutlineExclamationCircle,
		name: "AiOutlineExclamationCircle",
		library: "ai",
	},
	{ icon: AiOutlineExclamation, name: "AiOutlineExclamation", library: "ai" },
	{ icon: AiOutlineExpandAlt, name: "AiOutlineExpandAlt", library: "ai" },
	{ icon: AiOutlineExpand, name: "AiOutlineExpand", library: "ai" },
	{ icon: AiOutlineExperiment, name: "AiOutlineExperiment", library: "ai" },
	{ icon: AiOutlineExport, name: "AiOutlineExport", library: "ai" },
	{ icon: AiOutlineEyeInvisible, name: "AiOutlineEyeInvisible", library: "ai" },
	{ icon: AiOutlineEye, name: "AiOutlineEye", library: "ai" },
	{ icon: AiOutlineFacebook, name: "AiOutlineFacebook", library: "ai" },
	{ icon: AiOutlineFall, name: "AiOutlineFall", library: "ai" },
	{ icon: AiOutlineFastBackward, name: "AiOutlineFastBackward", library: "ai" },
	{ icon: AiOutlineFastForward, name: "AiOutlineFastForward", library: "ai" },
	{ icon: AiOutlineFieldBinary, name: "AiOutlineFieldBinary", library: "ai" },
	{ icon: AiOutlineFieldNumber, name: "AiOutlineFieldNumber", library: "ai" },
	{ icon: AiOutlineFieldString, name: "AiOutlineFieldString", library: "ai" },
	{ icon: AiOutlineFieldTime, name: "AiOutlineFieldTime", library: "ai" },
	{ icon: AiOutlineFileAdd, name: "AiOutlineFileAdd", library: "ai" },
	{ icon: AiOutlineFileDone, name: "AiOutlineFileDone", library: "ai" },
	{ icon: AiOutlineFileExcel, name: "AiOutlineFileExcel", library: "ai" },
	{ icon: AiOutlineFileExclamation, name: "AiOutlineFileExclamation", library: "ai" },
	{ icon: AiOutlineFileGif, name: "AiOutlineFileGif", library: "ai" },
	{ icon: AiOutlineFileImage, name: "AiOutlineFileImage", library: "ai" },
	{ icon: AiOutlineFileJpg, name: "AiOutlineFileJpg", library: "ai" },
	{ icon: AiOutlineFileMarkdown, name: "AiOutlineFileMarkdown", library: "ai" },
	{ icon: AiOutlineFilePdf, name: "AiOutlineFilePdf", library: "ai" },
	{ icon: AiOutlineFilePpt, name: "AiOutlineFilePpt", library: "ai" },
	{ icon: AiOutlineFileProtect, name: "AiOutlineFileProtect", library: "ai" },
	{ icon: AiOutlineFileSearch, name: "AiOutlineFileSearch", library: "ai" },
	{ icon: AiOutlineFileSync, name: "AiOutlineFileSync", library: "ai" },
	{ icon: AiOutlineFileText, name: "AiOutlineFileText", library: "ai" },
	{ icon: AiOutlineFileUnknown, name: "AiOutlineFileUnknown", library: "ai" },
	{ icon: AiOutlineFileWord, name: "AiOutlineFileWord", library: "ai" },
	{ icon: AiOutlineFileZip, name: "AiOutlineFileZip", library: "ai" },
	{ icon: AiOutlineFile, name: "AiOutlineFile", library: "ai" },
	{ icon: AiOutlineFilter, name: "AiOutlineFilter", library: "ai" },
	{ icon: AiOutlineFire, name: "AiOutlineFire", library: "ai" },
	{ icon: AiOutlineFlag, name: "AiOutlineFlag", library: "ai" },
	{ icon: AiOutlineFolderAdd, name: "AiOutlineFolderAdd", library: "ai" },
	{ icon: AiOutlineFolderOpen, name: "AiOutlineFolderOpen", library: "ai" },
	{ icon: AiOutlineFolderView, name: "AiOutlineFolderView", library: "ai" },
	{ icon: AiOutlineFolder, name: "AiOutlineFolder", library: "ai" },
	{ icon: AiOutlineFontColors, name: "AiOutlineFontColors", library: "ai" },
	{ icon: AiOutlineFontSize, name: "AiOutlineFontSize", library: "ai" },
	{ icon: AiOutlineFork, name: "AiOutlineFork", library: "ai" },
	{ icon: AiOutlineForm, name: "AiOutlineForm", library: "ai" },
	{ icon: AiOutlineFormatPainter, name: "AiOutlineFormatPainter", library: "ai" },
	{ icon: AiOutlineForward, name: "AiOutlineForward", library: "ai" },
	{ icon: AiOutlineFrown, name: "AiOutlineFrown", library: "ai" },
	{ icon: AiOutlineFullscreenExit, name: "AiOutlineFullscreenExit", library: "ai" },
	{ icon: AiOutlineFullscreen, name: "AiOutlineFullscreen", library: "ai" },
	{ icon: AiOutlineFunction, name: "AiOutlineFunction", library: "ai" },
	{
		icon: AiOutlineFundProjectionScreen,
		name: "AiOutlineFundProjectionScreen",
		library: "ai",
	},
	{ icon: AiOutlineFundView, name: "AiOutlineFundView", library: "ai" },
	{ icon: AiOutlineFund, name: "AiOutlineFund", library: "ai" },
	{ icon: AiOutlineFunnelPlot, name: "AiOutlineFunnelPlot", library: "ai" },
	{ icon: AiOutlineGateway, name: "AiOutlineGateway", library: "ai" },
	{ icon: AiOutlineGif, name: "AiOutlineGif", library: "ai" },
	{ icon: AiOutlineGift, name: "AiOutlineGift", library: "ai" },
	{ icon: AiOutlineGithub, name: "AiOutlineGithub", library: "ai" },
	{ icon: AiOutlineGitlab, name: "AiOutlineGitlab", library: "ai" },
	{ icon: AiOutlineGlobal, name: "AiOutlineGlobal", library: "ai" },
	{ icon: AiOutlineGold, name: "AiOutlineGold", library: "ai" },
	{ icon: AiOutlineGooglePlus, name: "AiOutlineGooglePlus", library: "ai" },
	{ icon: AiOutlineGoogle, name: "AiOutlineGoogle", library: "ai" },
	{ icon: AiOutlineGroup, name: "AiOutlineGroup", library: "ai" },
	{ icon: AiOutlineHdd, name: "AiOutlineHdd", library: "ai" },
	{ icon: AiOutlineHeart, name: "AiOutlineHeart", library: "ai" },
	{ icon: AiOutlineHeatMap, name: "AiOutlineHeatMap", library: "ai" },
	{ icon: AiOutlineHighlight, name: "AiOutlineHighlight", library: "ai" },
	{ icon: AiOutlineHistory, name: "AiOutlineHistory", library: "ai" },
	{ icon: AiOutlineHolder, name: "AiOutlineHolder", library: "ai" },
	{ icon: AiOutlineHome, name: "AiOutlineHome", library: "ai" },
	{ icon: AiOutlineHourglass, name: "AiOutlineHourglass", library: "ai" },
	{ icon: AiOutlineHtml5, name: "AiOutlineHtml5", library: "ai" },
	{ icon: AiOutlineIdcard, name: "AiOutlineIdcard", library: "ai" },
	{ icon: AiOutlineIe, name: "AiOutlineIe", library: "ai" },
	{ icon: AiOutlineImport, name: "AiOutlineImport", library: "ai" },
	{ icon: AiOutlineInbox, name: "AiOutlineInbox", library: "ai" },
	{ icon: AiOutlineInfoCircle, name: "AiOutlineInfoCircle", library: "ai" },
	{ icon: AiOutlineInfo, name: "AiOutlineInfo", library: "ai" },
	{ icon: AiOutlineInsertRowAbove, name: "AiOutlineInsertRowAbove", library: "ai" },
	{ icon: AiOutlineInsertRowBelow, name: "AiOutlineInsertRowBelow", library: "ai" },
	{ icon: AiOutlineInsertRowLeft, name: "AiOutlineInsertRowLeft", library: "ai" },
	{ icon: AiOutlineInsertRowRight, name: "AiOutlineInsertRowRight", library: "ai" },
	{ icon: AiOutlineInstagram, name: "AiOutlineInstagram", library: "ai" },
	{ icon: AiOutlineInsurance, name: "AiOutlineInsurance", library: "ai" },
	{ icon: AiOutlineInteraction, name: "AiOutlineInteraction", library: "ai" },
	{ icon: AiOutlineIssuesClose, name: "AiOutlineIssuesClose", library: "ai" },
	{ icon: AiOutlineItalic, name: "AiOutlineItalic", library: "ai" },
	{ icon: AiOutlineKey, name: "AiOutlineKey", library: "ai" },
	{ icon: AiOutlineLaptop, name: "AiOutlineLaptop", library: "ai" },
	{ icon: AiOutlineLayout, name: "AiOutlineLayout", library: "ai" },
	{ icon: AiOutlineLeftCircle, name: "AiOutlineLeftCircle", library: "ai" },
	{ icon: AiOutlineLeftSquare, name: "AiOutlineLeftSquare", library: "ai" },
	{ icon: AiOutlineLeft, name: "AiOutlineLeft", library: "ai" },
	{ icon: AiOutlineLike, name: "AiOutlineLike", library: "ai" },
	{ icon: AiOutlineLineChart, name: "AiOutlineLineChart", library: "ai" },
	{ icon: AiOutlineLineHeight, name: "AiOutlineLineHeight", library: "ai" },
	{ icon: AiOutlineLine, name: "AiOutlineLine", library: "ai" },
	{ icon: AiOutlineLink, name: "AiOutlineLink", library: "ai" },
	{ icon: AiOutlineLinkedin, name: "AiOutlineLinkedin", library: "ai" },
	{ icon: AiOutlineLoading3Quarters, name: "AiOutlineLoading3Quarters", library: "ai" },
	{ icon: AiOutlineLoading, name: "AiOutlineLoading", library: "ai" },
	{ icon: AiOutlineLock, name: "AiOutlineLock", library: "ai" },
	{ icon: AiOutlineLogin, name: "AiOutlineLogin", library: "ai" },
	{ icon: AiOutlineLogout, name: "AiOutlineLogout", library: "ai" },
	{ icon: AiOutlineMacCommand, name: "AiOutlineMacCommand", library: "ai" },
	{ icon: AiOutlineMail, name: "AiOutlineMail", library: "ai" },
	{ icon: AiOutlineMan, name: "AiOutlineMan", library: "ai" },
	{ icon: AiOutlineMedicineBox, name: "AiOutlineMedicineBox", library: "ai" },
	{ icon: AiOutlineMediumWorkmark, name: "AiOutlineMediumWorkmark", library: "ai" },
	{ icon: AiOutlineMedium, name: "AiOutlineMedium", library: "ai" },
	{ icon: AiOutlineMeh, name: "AiOutlineMeh", library: "ai" },
	{ icon: AiOutlineMenuFold, name: "AiOutlineMenuFold", library: "ai" },
	{ icon: AiOutlineMenuUnfold, name: "AiOutlineMenuUnfold", library: "ai" },
	{ icon: AiOutlineMenu, name: "AiOutlineMenu", library: "ai" },
	{ icon: AiOutlineMergeCells, name: "AiOutlineMergeCells", library: "ai" },
	{ icon: AiOutlineMessage, name: "AiOutlineMessage", library: "ai" },
	{ icon: AiOutlineMinusCircle, name: "AiOutlineMinusCircle", library: "ai" },
	{ icon: AiOutlineMinusSquare, name: "AiOutlineMinusSquare", library: "ai" },
	{ icon: AiOutlineMinus, name: "AiOutlineMinus", library: "ai" },
	{ icon: AiOutlineMobile, name: "AiOutlineMobile", library: "ai" },
	{ icon: AiOutlineMoneyCollect, name: "AiOutlineMoneyCollect", library: "ai" },
	{ icon: AiOutlineMonitor, name: "AiOutlineMonitor", library: "ai" },
	{ icon: AiOutlineMore, name: "AiOutlineMore", library: "ai" },
	{ icon: AiOutlineNodeCollapse, name: "AiOutlineNodeCollapse", library: "ai" },
	{ icon: AiOutlineNodeExpand, name: "AiOutlineNodeExpand", library: "ai" },
	{ icon: AiOutlineNodeIndex, name: "AiOutlineNodeIndex", library: "ai" },
	{ icon: AiOutlineNotification, name: "AiOutlineNotification", library: "ai" },
	{ icon: AiOutlineNumber, name: "AiOutlineNumber", library: "ai" },
	{ icon: AiOutlineOneToOne, name: "AiOutlineOneToOne", library: "ai" },
	{ icon: AiOutlineOrderedList, name: "AiOutlineOrderedList", library: "ai" },
	{ icon: AiOutlinePaperClip, name: "AiOutlinePaperClip", library: "ai" },
	{ icon: AiOutlinePartition, name: "AiOutlinePartition", library: "ai" },
	{ icon: AiOutlinePauseCircle, name: "AiOutlinePauseCircle", library: "ai" },
	{ icon: AiOutlinePause, name: "AiOutlinePause", library: "ai" },
	{ icon: AiOutlinePayCircle, name: "AiOutlinePayCircle", library: "ai" },
	{ icon: AiOutlinePercentage, name: "AiOutlinePercentage", library: "ai" },
	{ icon: AiOutlinePhone, name: "AiOutlinePhone", library: "ai" },
	{ icon: AiOutlinePicCenter, name: "AiOutlinePicCenter", library: "ai" },
	{ icon: AiOutlinePicLeft, name: "AiOutlinePicLeft", library: "ai" },
	{ icon: AiOutlinePicRight, name: "AiOutlinePicRight", library: "ai" },
	{ icon: AiOutlinePicture, name: "AiOutlinePicture", library: "ai" },
	{ icon: AiOutlinePieChart, name: "AiOutlinePieChart", library: "ai" },
	{ icon: AiOutlinePlayCircle, name: "AiOutlinePlayCircle", library: "ai" },
	{ icon: AiOutlinePlaySquare, name: "AiOutlinePlaySquare", library: "ai" },
	{ icon: AiOutlinePlusCircle, name: "AiOutlinePlusCircle", library: "ai" },
	{ icon: AiOutlinePlusSquare, name: "AiOutlinePlusSquare", library: "ai" },
	{ icon: AiOutlinePlus, name: "AiOutlinePlus", library: "ai" },
	{ icon: AiOutlinePoundCircle, name: "AiOutlinePoundCircle", library: "ai" },
	{ icon: AiOutlinePound, name: "AiOutlinePound", library: "ai" },
	{ icon: AiOutlinePoweroff, name: "AiOutlinePoweroff", library: "ai" },
	{ icon: AiOutlinePrinter, name: "AiOutlinePrinter", library: "ai" },
	{ icon: AiOutlineProfile, name: "AiOutlineProfile", library: "ai" },
	{ icon: AiOutlineProject, name: "AiOutlineProject", library: "ai" },
	{ icon: AiOutlinePropertySafety, name: "AiOutlinePropertySafety", library: "ai" },
	{ icon: AiOutlinePullRequest, name: "AiOutlinePullRequest", library: "ai" },
	{ icon: AiOutlinePushpin, name: "AiOutlinePushpin", library: "ai" },
	{ icon: AiOutlineQq, name: "AiOutlineQq", library: "ai" },
	{ icon: AiOutlineQrcode, name: "AiOutlineQrcode", library: "ai" },
	{ icon: AiOutlineQuestionCircle, name: "AiOutlineQuestionCircle", library: "ai" },
	{ icon: AiOutlineQuestion, name: "AiOutlineQuestion", library: "ai" },
	{ icon: AiOutlineRadarChart, name: "AiOutlineRadarChart", library: "ai" },
	{ icon: AiOutlineRadiusBottomleft, name: "AiOutlineRadiusBottomleft", library: "ai" },
	{
		icon: AiOutlineRadiusBottomright,
		name: "AiOutlineRadiusBottomright",
		library: "ai",
	},
	{ icon: AiOutlineRadiusSetting, name: "AiOutlineRadiusSetting", library: "ai" },
	{ icon: AiOutlineRadiusUpleft, name: "AiOutlineRadiusUpleft", library: "ai" },
	{ icon: AiOutlineRadiusUpright, name: "AiOutlineRadiusUpright", library: "ai" },
	{ icon: AiOutlineRead, name: "AiOutlineRead", library: "ai" },
	{ icon: AiOutlineReconciliation, name: "AiOutlineReconciliation", library: "ai" },
	{ icon: AiOutlineRedEnvelope, name: "AiOutlineRedEnvelope", library: "ai" },
	{ icon: AiOutlineReddit, name: "AiOutlineReddit", library: "ai" },
	{ icon: AiOutlineRedo, name: "AiOutlineRedo", library: "ai" },
	{ icon: AiOutlineReload, name: "AiOutlineReload", library: "ai" },
	{ icon: AiOutlineRest, name: "AiOutlineRest", library: "ai" },
	{ icon: AiOutlineRetweet, name: "AiOutlineRetweet", library: "ai" },
	{ icon: AiOutlineRightCircle, name: "AiOutlineRightCircle", library: "ai" },
	{ icon: AiOutlineRightSquare, name: "AiOutlineRightSquare", library: "ai" },
	{ icon: AiOutlineRight, name: "AiOutlineRight", library: "ai" },
	{ icon: AiOutlineRise, name: "AiOutlineRise", library: "ai" },
	{ icon: AiOutlineRobot, name: "AiOutlineRobot", library: "ai" },
	{ icon: AiOutlineRocket, name: "AiOutlineRocket", library: "ai" },
	{ icon: AiOutlineRollback, name: "AiOutlineRollback", library: "ai" },
	{ icon: AiOutlineRotateLeft, name: "AiOutlineRotateLeft", library: "ai" },
	{ icon: AiOutlineRotateRight, name: "AiOutlineRotateRight", library: "ai" },
	{
		icon: AiOutlineSafetyCertificate,
		name: "AiOutlineSafetyCertificate",
		library: "ai",
	},
	{ icon: AiOutlineSafety, name: "AiOutlineSafety", library: "ai" },
	{ icon: AiOutlineSave, name: "AiOutlineSave", library: "ai" },
	{ icon: AiOutlineScan, name: "AiOutlineScan", library: "ai" },
	{ icon: AiOutlineSchedule, name: "AiOutlineSchedule", library: "ai" },
	{ icon: AiOutlineScissor, name: "AiOutlineScissor", library: "ai" },
	{ icon: AiOutlineSearch, name: "AiOutlineSearch", library: "ai" },
	{ icon: AiOutlineSecurityScan, name: "AiOutlineSecurityScan", library: "ai" },
	{ icon: AiOutlineSelect, name: "AiOutlineSelect", library: "ai" },
	{ icon: AiOutlineSend, name: "AiOutlineSend", library: "ai" },
	{ icon: AiOutlineSetting, name: "AiOutlineSetting", library: "ai" },
	{ icon: AiOutlineShake, name: "AiOutlineShake", library: "ai" },
	{ icon: AiOutlineShareAlt, name: "AiOutlineShareAlt", library: "ai" },
	{ icon: AiOutlineShop, name: "AiOutlineShop", library: "ai" },
	{ icon: AiOutlineShoppingCart, name: "AiOutlineShoppingCart", library: "ai" },
	{ icon: AiOutlineShopping, name: "AiOutlineShopping", library: "ai" },
	{ icon: AiOutlineShrink, name: "AiOutlineShrink", library: "ai" },
	{ icon: AiOutlineSisternode, name: "AiOutlineSisternode", library: "ai" },
	{ icon: AiOutlineSketch, name: "AiOutlineSketch", library: "ai" },
	{ icon: AiOutlineSkin, name: "AiOutlineSkin", library: "ai" },
	{ icon: AiOutlineSkype, name: "AiOutlineSkype", library: "ai" },
	{ icon: AiOutlineSlackSquare, name: "AiOutlineSlackSquare", library: "ai" },
	{ icon: AiOutlineSlack, name: "AiOutlineSlack", library: "ai" },
	{ icon: AiOutlineSliders, name: "AiOutlineSliders", library: "ai" },
	{ icon: AiOutlineSmallDash, name: "AiOutlineSmallDash", library: "ai" },
	{ icon: AiOutlineSmile, name: "AiOutlineSmile", library: "ai" },
	{ icon: AiOutlineSnippets, name: "AiOutlineSnippets", library: "ai" },
	{ icon: AiOutlineSolution, name: "AiOutlineSolution", library: "ai" },
	{ icon: AiOutlineSortAscending, name: "AiOutlineSortAscending", library: "ai" },
	{ icon: AiOutlineSortDescending, name: "AiOutlineSortDescending", library: "ai" },
	{ icon: AiOutlineSound, name: "AiOutlineSound", library: "ai" },
	{ icon: AiOutlineSplitCells, name: "AiOutlineSplitCells", library: "ai" },
	{ icon: AiOutlineStar, name: "AiOutlineStar", library: "ai" },
	{ icon: AiOutlineStepBackward, name: "AiOutlineStepBackward", library: "ai" },
	{ icon: AiOutlineStepForward, name: "AiOutlineStepForward", library: "ai" },
	{ icon: AiOutlineStock, name: "AiOutlineStock", library: "ai" },
	{ icon: AiOutlineStop, name: "AiOutlineStop", library: "ai" },
	{ icon: AiOutlineStrikethrough, name: "AiOutlineStrikethrough", library: "ai" },
	{ icon: AiOutlineSubnode, name: "AiOutlineSubnode", library: "ai" },
	{ icon: AiOutlineSwapLeft, name: "AiOutlineSwapLeft", library: "ai" },
	{ icon: AiOutlineSwapRight, name: "AiOutlineSwapRight", library: "ai" },
	{ icon: AiOutlineSwap, name: "AiOutlineSwap", library: "ai" },
	{ icon: AiOutlineSwitcher, name: "AiOutlineSwitcher", library: "ai" },
	{ icon: AiOutlineSync, name: "AiOutlineSync", library: "ai" },
	{ icon: AiOutlineTable, name: "AiOutlineTable", library: "ai" },
	{ icon: AiOutlineTablet, name: "AiOutlineTablet", library: "ai" },
	{ icon: AiOutlineTag, name: "AiOutlineTag", library: "ai" },
	{ icon: AiOutlineTags, name: "AiOutlineTags", library: "ai" },
	{ icon: AiOutlineTaobaoCircle, name: "AiOutlineTaobaoCircle", library: "ai" },
	{ icon: AiOutlineTaobao, name: "AiOutlineTaobao", library: "ai" },
	{ icon: AiOutlineTeam, name: "AiOutlineTeam", library: "ai" },
	{ icon: AiOutlineThunderbolt, name: "AiOutlineThunderbolt", library: "ai" },
	{ icon: AiOutlineToTop, name: "AiOutlineToTop", library: "ai" },
	{ icon: AiOutlineTool, name: "AiOutlineTool", library: "ai" },
	{ icon: AiOutlineTrademarkCircle, name: "AiOutlineTrademarkCircle", library: "ai" },
	{ icon: AiOutlineTrademark, name: "AiOutlineTrademark", library: "ai" },
	{ icon: AiOutlineTransaction, name: "AiOutlineTransaction", library: "ai" },
	{ icon: AiOutlineTranslation, name: "AiOutlineTranslation", library: "ai" },
	{ icon: AiOutlineTrophy, name: "AiOutlineTrophy", library: "ai" },
	{ icon: AiOutlineTwitter, name: "AiOutlineTwitter", library: "ai" },
	{ icon: AiOutlineUnderline, name: "AiOutlineUnderline", library: "ai" },
	{ icon: AiOutlineUndo, name: "AiOutlineUndo", library: "ai" },
	{ icon: AiOutlineUngroup, name: "AiOutlineUngroup", library: "ai" },
	{ icon: AiOutlineUnlock, name: "AiOutlineUnlock", library: "ai" },
	{ icon: AiOutlineUnorderedList, name: "AiOutlineUnorderedList", library: "ai" },
	{ icon: AiOutlineUpCircle, name: "AiOutlineUpCircle", library: "ai" },
	{ icon: AiOutlineUpSquare, name: "AiOutlineUpSquare", library: "ai" },
	{ icon: AiOutlineUp, name: "AiOutlineUp", library: "ai" },
	{ icon: AiOutlineUpload, name: "AiOutlineUpload", library: "ai" },
	{ icon: AiOutlineUsb, name: "AiOutlineUsb", library: "ai" },
	{ icon: AiOutlineUserAdd, name: "AiOutlineUserAdd", library: "ai" },
	{ icon: AiOutlineUserDelete, name: "AiOutlineUserDelete", library: "ai" },
	{ icon: AiOutlineUserSwitch, name: "AiOutlineUserSwitch", library: "ai" },
	{ icon: AiOutlineUser, name: "AiOutlineUser", library: "ai" },
	{ icon: AiOutlineUsergroupAdd, name: "AiOutlineUsergroupAdd", library: "ai" },
	{ icon: AiOutlineUsergroupDelete, name: "AiOutlineUsergroupDelete", library: "ai" },
	{ icon: AiOutlineVerified, name: "AiOutlineVerified", library: "ai" },
	{
		icon: AiOutlineVerticalAlignBottom,
		name: "AiOutlineVerticalAlignBottom",
		library: "ai",
	},
	{
		icon: AiOutlineVerticalAlignMiddle,
		name: "AiOutlineVerticalAlignMiddle",
		library: "ai",
	},
	{ icon: AiOutlineVerticalAlignTop, name: "AiOutlineVerticalAlignTop", library: "ai" },
	{ icon: AiOutlineVerticalLeft, name: "AiOutlineVerticalLeft", library: "ai" },
	{ icon: AiOutlineVerticalRight, name: "AiOutlineVerticalRight", library: "ai" },
	{ icon: AiOutlineVideoCameraAdd, name: "AiOutlineVideoCameraAdd", library: "ai" },
	{ icon: AiOutlineVideoCamera, name: "AiOutlineVideoCamera", library: "ai" },
	{ icon: AiOutlineWallet, name: "AiOutlineWallet", library: "ai" },
	{ icon: AiOutlineWarning, name: "AiOutlineWarning", library: "ai" },
	{ icon: AiOutlineWechat, name: "AiOutlineWechat", library: "ai" },
	{ icon: AiOutlineWeiboCircle, name: "AiOutlineWeiboCircle", library: "ai" },
	{ icon: AiOutlineWeiboSquare, name: "AiOutlineWeiboSquare", library: "ai" },
	{ icon: AiOutlineWeibo, name: "AiOutlineWeibo", library: "ai" },
	{ icon: AiOutlineWhatsApp, name: "AiOutlineWhatsApp", library: "ai" },
	{ icon: AiOutlineWifi, name: "AiOutlineWifi", library: "ai" },
	{ icon: AiOutlineWindows, name: "AiOutlineWindows", library: "ai" },
	{ icon: AiOutlineWoman, name: "AiOutlineWoman", library: "ai" },
	{ icon: AiOutlineYahoo, name: "AiOutlineYahoo", library: "ai" },
	{ icon: AiOutlineYoutube, name: "AiOutlineYoutube", library: "ai" },
	{ icon: AiOutlineYuque, name: "AiOutlineYuque", library: "ai" },
	{ icon: AiOutlineZhihu, name: "AiOutlineZhihu", library: "ai" },
	{ icon: AiOutlineZoomIn, name: "AiOutlineZoomIn", library: "ai" },
	{ icon: AiOutlineZoomOut, name: "AiOutlineZoomOut", library: "ai" },
	{ icon: AiTwotoneAccountBook, name: "AiTwotoneAccountBook", library: "ai" },
	{ icon: AiTwotoneAlert, name: "AiTwotoneAlert", library: "ai" },
	{ icon: AiTwotoneApi, name: "AiTwotoneApi", library: "ai" },
	{ icon: AiTwotoneAppstore, name: "AiTwotoneAppstore", library: "ai" },
	{ icon: AiTwotoneAudio, name: "AiTwotoneAudio", library: "ai" },
	{ icon: AiTwotoneBank, name: "AiTwotoneBank", library: "ai" },
	{ icon: AiTwotoneBell, name: "AiTwotoneBell", library: "ai" },
	{ icon: AiTwotoneBook, name: "AiTwotoneBook", library: "ai" },
	{ icon: AiTwotoneBoxPlot, name: "AiTwotoneBoxPlot", library: "ai" },
	{ icon: AiTwotoneBug, name: "AiTwotoneBug", library: "ai" },
	{ icon: AiTwotoneBuild, name: "AiTwotoneBuild", library: "ai" },
	{ icon: AiTwotoneBulb, name: "AiTwotoneBulb", library: "ai" },
	{ icon: AiTwotoneCalculator, name: "AiTwotoneCalculator", library: "ai" },
	{ icon: AiTwotoneCalendar, name: "AiTwotoneCalendar", library: "ai" },
	{ icon: AiTwotoneCamera, name: "AiTwotoneCamera", library: "ai" },
	{ icon: AiTwotoneCar, name: "AiTwotoneCar", library: "ai" },
	{ icon: AiTwotoneCarryOut, name: "AiTwotoneCarryOut", library: "ai" },
	{ icon: AiTwotoneCheckCircle, name: "AiTwotoneCheckCircle", library: "ai" },
	{ icon: AiTwotoneCheckSquare, name: "AiTwotoneCheckSquare", library: "ai" },
	{ icon: AiTwotoneCiCircle, name: "AiTwotoneCiCircle", library: "ai" },
	{ icon: AiTwotoneCi, name: "AiTwotoneCi", library: "ai" },
	{ icon: AiTwotoneClockCircle, name: "AiTwotoneClockCircle", library: "ai" },
	{ icon: AiTwotoneCloseCircle, name: "AiTwotoneCloseCircle", library: "ai" },
	{ icon: AiTwotoneCloseSquare, name: "AiTwotoneCloseSquare", library: "ai" },
	{ icon: AiTwotoneCloud, name: "AiTwotoneCloud", library: "ai" },
	{ icon: AiTwotoneCode, name: "AiTwotoneCode", library: "ai" },
	{ icon: AiTwotoneCompass, name: "AiTwotoneCompass", library: "ai" },
	{ icon: AiTwotoneContacts, name: "AiTwotoneContacts", library: "ai" },
	{ icon: AiTwotoneContainer, name: "AiTwotoneContainer", library: "ai" },
	{ icon: AiTwotoneControl, name: "AiTwotoneControl", library: "ai" },
	{ icon: AiTwotoneCopy, name: "AiTwotoneCopy", library: "ai" },
	{ icon: AiTwotoneCopyrightCircle, name: "AiTwotoneCopyrightCircle", library: "ai" },
	{ icon: AiTwotoneCopyright, name: "AiTwotoneCopyright", library: "ai" },
	{ icon: AiTwotoneCreditCard, name: "AiTwotoneCreditCard", library: "ai" },
	{ icon: AiTwotoneCrown, name: "AiTwotoneCrown", library: "ai" },
	{ icon: AiTwotoneCustomerService, name: "AiTwotoneCustomerService", library: "ai" },
	{ icon: AiTwotoneDashboard, name: "AiTwotoneDashboard", library: "ai" },
	{ icon: AiTwotoneDatabase, name: "AiTwotoneDatabase", library: "ai" },
	{ icon: AiTwotoneDelete, name: "AiTwotoneDelete", library: "ai" },
	{ icon: AiTwotoneDiff, name: "AiTwotoneDiff", library: "ai" },
	{ icon: AiTwotoneDislike, name: "AiTwotoneDislike", library: "ai" },
	{ icon: AiTwotoneDollarCircle, name: "AiTwotoneDollarCircle", library: "ai" },
	{ icon: AiTwotoneDollar, name: "AiTwotoneDollar", library: "ai" },
	{ icon: AiTwotoneDownCircle, name: "AiTwotoneDownCircle", library: "ai" },
	{ icon: AiTwotoneDownSquare, name: "AiTwotoneDownSquare", library: "ai" },
	{ icon: AiTwotoneEdit, name: "AiTwotoneEdit", library: "ai" },
	{ icon: AiTwotoneEnvironment, name: "AiTwotoneEnvironment", library: "ai" },
	{ icon: AiTwotoneEuroCircle, name: "AiTwotoneEuroCircle", library: "ai" },
	{ icon: AiTwotoneEuro, name: "AiTwotoneEuro", library: "ai" },
	{
		icon: AiTwotoneExclamationCircle,
		name: "AiTwotoneExclamationCircle",
		library: "ai",
	},
	{ icon: AiTwotoneExperiment, name: "AiTwotoneExperiment", library: "ai" },
	{ icon: AiTwotoneEyeInvisible, name: "AiTwotoneEyeInvisible", library: "ai" },
	{ icon: AiTwotoneEye, name: "AiTwotoneEye", library: "ai" },
	{ icon: AiTwotoneFileAdd, name: "AiTwotoneFileAdd", library: "ai" },
	{ icon: AiTwotoneFileExcel, name: "AiTwotoneFileExcel", library: "ai" },
	{ icon: AiTwotoneFileExclamation, name: "AiTwotoneFileExclamation", library: "ai" },
	{ icon: AiTwotoneFileImage, name: "AiTwotoneFileImage", library: "ai" },
	{ icon: AiTwotoneFileMarkdown, name: "AiTwotoneFileMarkdown", library: "ai" },
	{ icon: AiTwotoneFilePdf, name: "AiTwotoneFilePdf", library: "ai" },
	{ icon: AiTwotoneFilePpt, name: "AiTwotoneFilePpt", library: "ai" },
	{ icon: AiTwotoneFileText, name: "AiTwotoneFileText", library: "ai" },
	{ icon: AiTwotoneFileUnknown, name: "AiTwotoneFileUnknown", library: "ai" },
	{ icon: AiTwotoneFileWord, name: "AiTwotoneFileWord", library: "ai" },
	{ icon: AiTwotoneFileZip, name: "AiTwotoneFileZip", library: "ai" },
	{ icon: AiTwotoneFile, name: "AiTwotoneFile", library: "ai" },
	{ icon: AiTwotoneFilter, name: "AiTwotoneFilter", library: "ai" },
	{ icon: AiTwotoneFire, name: "AiTwotoneFire", library: "ai" },
	{ icon: AiTwotoneFlag, name: "AiTwotoneFlag", library: "ai" },
	{ icon: AiTwotoneFolderAdd, name: "AiTwotoneFolderAdd", library: "ai" },
	{ icon: AiTwotoneFolderOpen, name: "AiTwotoneFolderOpen", library: "ai" },
	{ icon: AiTwotoneFolder, name: "AiTwotoneFolder", library: "ai" },
	{ icon: AiTwotoneFrown, name: "AiTwotoneFrown", library: "ai" },
	{ icon: AiTwotoneFund, name: "AiTwotoneFund", library: "ai" },
	{ icon: AiTwotoneFunnelPlot, name: "AiTwotoneFunnelPlot", library: "ai" },
	{ icon: AiTwotoneGift, name: "AiTwotoneGift", library: "ai" },
	{ icon: AiTwotoneGold, name: "AiTwotoneGold", library: "ai" },
	{ icon: AiTwotoneHdd, name: "AiTwotoneHdd", library: "ai" },
	{ icon: AiTwotoneHeart, name: "AiTwotoneHeart", library: "ai" },
	{ icon: AiTwotoneHighlight, name: "AiTwotoneHighlight", library: "ai" },
	{ icon: AiTwotoneHome, name: "AiTwotoneHome", library: "ai" },
	{ icon: AiTwotoneHourglass, name: "AiTwotoneHourglass", library: "ai" },
	{ icon: AiTwotoneHtml5, name: "AiTwotoneHtml5", library: "ai" },
	{ icon: AiTwotoneIdcard, name: "AiTwotoneIdcard", library: "ai" },
	{ icon: AiTwotoneInfoCircle, name: "AiTwotoneInfoCircle", library: "ai" },
	{ icon: AiTwotoneInsurance, name: "AiTwotoneInsurance", library: "ai" },
	{ icon: AiTwotoneInteraction, name: "AiTwotoneInteraction", library: "ai" },
	{ icon: AiTwotoneLayout, name: "AiTwotoneLayout", library: "ai" },
	{ icon: AiTwotoneLeftCircle, name: "AiTwotoneLeftCircle", library: "ai" },
	{ icon: AiTwotoneLeftSquare, name: "AiTwotoneLeftSquare", library: "ai" },
	{ icon: AiTwotoneLike, name: "AiTwotoneLike", library: "ai" },
	{ icon: AiTwotoneLock, name: "AiTwotoneLock", library: "ai" },
	{ icon: AiTwotoneMail, name: "AiTwotoneMail", library: "ai" },
	{ icon: AiTwotoneMedicineBox, name: "AiTwotoneMedicineBox", library: "ai" },
	{ icon: AiTwotoneMeh, name: "AiTwotoneMeh", library: "ai" },
	{ icon: AiTwotoneMessage, name: "AiTwotoneMessage", library: "ai" },
	{ icon: AiTwotoneMinusCircle, name: "AiTwotoneMinusCircle", library: "ai" },
	{ icon: AiTwotoneMinusSquare, name: "AiTwotoneMinusSquare", library: "ai" },
	{ icon: AiTwotoneMobile, name: "AiTwotoneMobile", library: "ai" },
	{ icon: AiTwotoneMoneyCollect, name: "AiTwotoneMoneyCollect", library: "ai" },
	{ icon: AiTwotoneNotification, name: "AiTwotoneNotification", library: "ai" },
	{ icon: AiTwotonePauseCircle, name: "AiTwotonePauseCircle", library: "ai" },
	{ icon: AiTwotonePhone, name: "AiTwotonePhone", library: "ai" },
	{ icon: AiTwotonePicture, name: "AiTwotonePicture", library: "ai" },
	{ icon: AiTwotonePieChart, name: "AiTwotonePieChart", library: "ai" },
	{ icon: AiTwotonePlayCircle, name: "AiTwotonePlayCircle", library: "ai" },
	{ icon: AiTwotonePlaySquare, name: "AiTwotonePlaySquare", library: "ai" },
	{ icon: AiTwotonePlusCircle, name: "AiTwotonePlusCircle", library: "ai" },
	{ icon: AiTwotonePlusSquare, name: "AiTwotonePlusSquare", library: "ai" },
	{ icon: AiTwotonePoundCircle, name: "AiTwotonePoundCircle", library: "ai" },
	{ icon: AiTwotonePrinter, name: "AiTwotonePrinter", library: "ai" },
	{ icon: AiTwotoneProfile, name: "AiTwotoneProfile", library: "ai" },
	{ icon: AiTwotoneProject, name: "AiTwotoneProject", library: "ai" },
	{ icon: AiTwotonePropertySafety, name: "AiTwotonePropertySafety", library: "ai" },
	{ icon: AiTwotonePushpin, name: "AiTwotonePushpin", library: "ai" },
	{ icon: AiTwotoneQuestionCircle, name: "AiTwotoneQuestionCircle", library: "ai" },
	{ icon: AiTwotoneReconciliation, name: "AiTwotoneReconciliation", library: "ai" },
	{ icon: AiTwotoneRedEnvelope, name: "AiTwotoneRedEnvelope", library: "ai" },
	{ icon: AiTwotoneRest, name: "AiTwotoneRest", library: "ai" },
	{ icon: AiTwotoneRightCircle, name: "AiTwotoneRightCircle", library: "ai" },
	{ icon: AiTwotoneRightSquare, name: "AiTwotoneRightSquare", library: "ai" },
	{ icon: AiTwotoneRocket, name: "AiTwotoneRocket", library: "ai" },
	{
		icon: AiTwotoneSafetyCertificate,
		name: "AiTwotoneSafetyCertificate",
		library: "ai",
	},
	{ icon: AiTwotoneSave, name: "AiTwotoneSave", library: "ai" },
	{ icon: AiTwotoneSchedule, name: "AiTwotoneSchedule", library: "ai" },
	{ icon: AiTwotoneSecurityScan, name: "AiTwotoneSecurityScan", library: "ai" },
	{ icon: AiTwotoneSetting, name: "AiTwotoneSetting", library: "ai" },
	{ icon: AiTwotoneShop, name: "AiTwotoneShop", library: "ai" },
	{ icon: AiTwotoneShopping, name: "AiTwotoneShopping", library: "ai" },
	{ icon: AiTwotoneSkin, name: "AiTwotoneSkin", library: "ai" },
	{ icon: AiTwotoneSliders, name: "AiTwotoneSliders", library: "ai" },
	{ icon: AiTwotoneSmile, name: "AiTwotoneSmile", library: "ai" },
	{ icon: AiTwotoneSnippets, name: "AiTwotoneSnippets", library: "ai" },
	{ icon: AiTwotoneSound, name: "AiTwotoneSound", library: "ai" },
	{ icon: AiTwotoneStar, name: "AiTwotoneStar", library: "ai" },
	{ icon: AiTwotoneStop, name: "AiTwotoneStop", library: "ai" },
	{ icon: AiTwotoneSwitcher, name: "AiTwotoneSwitcher", library: "ai" },
	{ icon: AiTwotoneTablet, name: "AiTwotoneTablet", library: "ai" },
	{ icon: AiTwotoneTag, name: "AiTwotoneTag", library: "ai" },
	{ icon: AiTwotoneTags, name: "AiTwotoneTags", library: "ai" },
	{ icon: AiTwotoneThunderbolt, name: "AiTwotoneThunderbolt", library: "ai" },
	{ icon: AiTwotoneTool, name: "AiTwotoneTool", library: "ai" },
	{ icon: AiTwotoneTrademarkCircle, name: "AiTwotoneTrademarkCircle", library: "ai" },
	{ icon: AiTwotoneTrophy, name: "AiTwotoneTrophy", library: "ai" },
	{ icon: AiTwotoneUnlock, name: "AiTwotoneUnlock", library: "ai" },
	{ icon: AiTwotoneUpCircle, name: "AiTwotoneUpCircle", library: "ai" },
	{ icon: AiTwotoneUpSquare, name: "AiTwotoneUpSquare", library: "ai" },
	{ icon: AiTwotoneUsb, name: "AiTwotoneUsb", library: "ai" },
	{ icon: AiTwotoneVideoCamera, name: "AiTwotoneVideoCamera", library: "ai" },
	{ icon: AiTwotoneWallet, name: "AiTwotoneWallet", library: "ai" },
	{ icon: AiTwotoneWarning, name: "AiTwotoneWarning", library: "ai" },
];

export default result;
