import {
Fa500Px,
FaAccessibleIcon,
FaAccusoft,
FaAcquisitionsIncorporated,
FaAdn,
FaAdversal,
FaAffiliatetheme,
FaAirbnb,
FaAlgolia,
FaAlipay,
FaAmazonPay,
FaAmazon,
FaAmilia,
FaAndroid,
FaAngellist,
FaAngrycreative,
FaAngular,
FaAppStoreIos,
FaAppStore,
FaApper,
FaApplePay,
FaApple,
FaArtstation,
FaAsymmetrik,
FaAtlassian,
FaAudible,
FaAutoprefixer,
FaAvianex,
FaAviato,
FaAws,
FaBandcamp,
FaBattleNet,
FaBehanceSquare,
FaBehance,
FaBimobject,
FaBitbucket,
FaBitcoin,
FaBity,
FaBlackTie,
FaBlackberry,
FaBloggerB,
FaBlogger,
FaBluetoothB,
FaBluetooth,
FaBootstrap,
FaBtc,
FaBuffer,
FaBuromobelexperte,
FaBuyNLarge,
FaBuysellads,
FaCanadianMapleLeaf,
FaCcAmazonPay,
FaCcAmex,
FaCcApplePay,
FaCcDinersClub,
FaCcDiscover,
FaCcJcb,
FaCcMastercard,
FaCcPaypal,
FaCcStripe,
FaCcVisa,
FaCentercode,
FaCentos,
FaChrome,
FaChromecast,
FaCloudflare,
FaCloudscale,
FaCloudsmith,
FaCloudversify,
FaCodepen,
FaCodiepie,
FaConfluence,
FaConnectdevelop,
FaContao,
FaCottonBureau,
FaCpanel,
FaCreativeCommonsBy,
FaCreativeCommonsNcEu,
FaCreativeCommonsNcJp,
FaCreativeCommonsNc,
FaCreativeCommonsNd,
FaCreativeCommonsPdAlt,
FaCreativeCommonsPd,
FaCreativeCommonsRemix,
FaCreativeCommonsSa,
FaCreativeCommonsSamplingPlus,
FaCreativeCommonsSampling,
FaCreativeCommonsShare,
FaCreativeCommonsZero,
FaCreativeCommons,
FaCriticalRole,
FaCss3Alt,
FaCss3,
FaCuttlefish,
FaDAndDBeyond,
FaDAndD,
FaDailymotion,
FaDashcube,
FaDeezer,
FaDelicious,
FaDeploydog,
FaDeskpro,
FaDev,
FaDeviantart,
FaDhl,
FaDiaspora,
FaDigg,
FaDigitalOcean,
FaDiscord,
FaDiscourse,
FaDochub,
FaDocker,
FaDraft2Digital,
FaDribbbleSquare,
FaDribbble,
FaDropbox,
FaDrupal,
FaDyalog,
FaEarlybirds,
FaEbay,
FaEdgeLegacy,
FaEdge,
FaElementor,
FaEllo,
FaEmber,
FaEmpire,
FaEnvira,
FaErlang,
FaEthereum,
FaEtsy,
FaEvernote,
FaExpeditedssl,
FaFacebookF,
FaFacebookMessenger,
FaFacebookSquare,
FaFacebook,
FaFantasyFlightGames,
FaFedex,
FaFedora,
FaFigma,
FaFirefoxBrowser,
FaFirefox,
FaFirstOrderAlt,
FaFirstOrder,
FaFirstdraft,
FaFlickr,
FaFlipboard,
FaFly,
FaFontAwesomeAlt,
FaFontAwesomeFlag,
FaFontAwesomeLogoFull,
FaFontAwesome,
FaFonticonsFi,
FaFonticons,
FaFortAwesomeAlt,
FaFortAwesome,
FaForumbee,
FaFoursquare,
FaFreeCodeCamp,
FaFreebsd,
FaFulcrum,
FaGalacticRepublic,
FaGalacticSenate,
FaGetPocket,
FaGgCircle,
FaGg,
FaGitAlt,
FaGitSquare,
FaGit,
FaGithubAlt,
FaGithubSquare,
FaGithub,
FaGitkraken,
FaGitlab,
FaGitter,
FaGlideG,
FaGlide,
FaGofore,
FaGoodreadsG,
FaGoodreads,
FaGoogleDrive,
FaGooglePay,
FaGooglePlay,
FaGooglePlusG,
FaGooglePlusSquare,
FaGooglePlus,
FaGoogleWallet,
FaGoogle,
FaGratipay,
FaGrav,
FaGripfire,
FaGrunt,
FaGuilded,
FaGulp,
FaHackerNewsSquare,
FaHackerNews,
FaHackerrank,
FaHips,
FaHireAHelper,
FaHive,
FaHooli,
FaHornbill,
FaHotjar,
FaHouzz,
FaHtml5,
FaHubspot,
FaIdeal,
FaImdb,
FaInnosoft,
FaInstagramSquare,
FaInstagram,
FaInstalod,
FaIntercom,
FaInternetExplorer,
FaInvision,
FaIoxhost,
FaItchIo,
FaItunesNote,
FaItunes,
FaJava,
FaJediOrder,
FaJenkins,
FaJira,
FaJoget,
FaJoomla,
FaJsSquare,
FaJs,
FaJsfiddle,
FaKaggle,
FaKeybase,
FaKeycdn,
FaKickstarterK,
FaKickstarter,
FaKorvue,
FaLaravel,
FaLastfmSquare,
FaLastfm,
FaLeanpub,
FaLess,
FaLine,
FaLinkedinIn,
FaLinkedin,
FaLinode,
FaLinux,
FaLyft,
FaMagento,
FaMailchimp,
FaMandalorian,
FaMarkdown,
FaMastodon,
FaMaxcdn,
FaMdb,
FaMedapps,
FaMediumM,
FaMedium,
FaMedrt,
FaMeetup,
FaMegaport,
FaMendeley,
FaMicroblog,
FaMicrosoft,
FaMix,
FaMixcloud,
FaMixer,
FaMizuni,
FaModx,
FaMonero,
FaNapster,
FaNeos,
FaNimblr,
FaNodeJs,
FaNode,
FaNpm,
FaNs8,
FaNutritionix,
FaOctopusDeploy,
FaOdnoklassnikiSquare,
FaOdnoklassniki,
FaOldRepublic,
FaOpencart,
FaOpenid,
FaOpera,
FaOptinMonster,
FaOrcid,
FaOsi,
FaPage4,
FaPagelines,
FaPalfed,
FaPatreon,
FaPaypal,
FaPennyArcade,
FaPerbyte,
FaPeriscope,
FaPhabricator,
FaPhoenixFramework,
FaPhoenixSquadron,
FaPhp,
FaPiedPiperAlt,
FaPiedPiperHat,
FaPiedPiperPp,
FaPiedPiperSquare,
FaPiedPiper,
FaPinterestP,
FaPinterestSquare,
FaPinterest,
FaPlaystation,
FaProductHunt,
FaPushed,
FaPython,
FaQq,
FaQuinscape,
FaQuora,
FaRProject,
FaRaspberryPi,
FaRavelry,
FaReact,
FaReacteurope,
FaReadme,
FaRebel,
FaRedRiver,
FaRedditAlien,
FaRedditSquare,
FaReddit,
FaRedhat,
FaRenren,
FaReplyd,
FaResearchgate,
FaResolving,
FaRev,
FaRocketchat,
FaRockrms,
FaRust,
FaSafari,
FaSalesforce,
FaSass,
FaSchlix,
FaScribd,
FaSearchengin,
FaSellcast,
FaSellsy,
FaServicestack,
FaShirtsinbulk,
FaShopify,
FaShopware,
FaSimplybuilt,
FaSistrix,
FaSith,
FaSketch,
FaSkyatlas,
FaSkype,
FaSlackHash,
FaSlack,
FaSlideshare,
FaSnapchatGhost,
FaSnapchatSquare,
FaSnapchat,
FaSoundcloud,
FaSourcetree,
FaSpeakap,
FaSpeakerDeck,
FaSpotify,
FaSquarespace,
FaStackExchange,
FaStackOverflow,
FaStackpath,
FaStaylinked,
FaSteamSquare,
FaSteamSymbol,
FaSteam,
FaStickerMule,
FaStrava,
FaStripeS,
FaStripe,
FaStudiovinari,
FaStumbleuponCircle,
FaStumbleupon,
FaSuperpowers,
FaSupple,
FaSuse,
FaSwift,
FaSymfony,
FaTeamspeak,
FaTelegramPlane,
FaTelegram,
FaTencentWeibo,
FaTheRedYeti,
FaThemeco,
FaThemeisle,
FaThinkPeaks,
FaTiktok,
FaTradeFederation,
FaTrello,
FaTripadvisor,
FaTumblrSquare,
FaTumblr,
FaTwitch,
FaTwitterSquare,
FaTwitter,
FaTypo3,
FaUber,
FaUbuntu,
FaUikit,
FaUmbraco,
FaUncharted,
FaUniregistry,
FaUnity,
FaUnsplash,
FaUntappd,
FaUps,
FaUsb,
FaUsps,
FaUssunnah,
FaVaadin,
FaViacoin,
FaViadeoSquare,
FaViadeo,
FaViber,
FaVimeoSquare,
FaVimeoV,
FaVimeo,
FaVine,
FaVk,
FaVnv,
FaVuejs,
FaWatchmanMonitoring,
FaWaze,
FaWeebly,
FaWeibo,
FaWeixin,
FaWhatsappSquare,
FaWhatsapp,
FaWhmcs,
FaWikipediaW,
FaWindows,
FaWix,
FaWizardsOfTheCoast,
FaWodu,
FaWolfPackBattalion,
FaWordpressSimple,
FaWordpress,
FaWpbeginner,
FaWpexplorer,
FaWpforms,
FaWpressr,
FaXbox,
FaXingSquare,
FaXing,
FaYCombinator,
FaYahoo,
FaYammer,
FaYandexInternational,
FaYandex,
FaYarn,
FaYelp,
FaYoast,
FaYoutubeSquare,
FaYoutube,
FaZhihu,
FaAd,
FaAddressBook,
FaAddressCard,
FaAdjust,
FaAirFreshener,
FaAlignCenter,
FaAlignJustify,
FaAlignLeft,
FaAlignRight,
FaAllergies,
FaAmbulance,
FaAmericanSignLanguageInterpreting,
FaAnchor,
FaAngleDoubleDown,
FaAngleDoubleLeft,
FaAngleDoubleRight,
FaAngleDoubleUp,
FaAngleDown,
FaAngleLeft,
FaAngleRight,
FaAngleUp,
FaAngry,
FaAnkh,
FaAppleAlt,
FaArchive,
FaArchway,
FaArrowAltCircleDown,
FaArrowAltCircleLeft,
FaArrowAltCircleRight,
FaArrowAltCircleUp,
FaArrowCircleDown,
FaArrowCircleLeft,
FaArrowCircleRight,
FaArrowCircleUp,
FaArrowDown,
FaArrowLeft,
FaArrowRight,
FaArrowUp,
FaArrowsAltH,
FaArrowsAltV,
FaArrowsAlt,
FaAssistiveListeningSystems,
FaAsterisk,
FaAt,
FaAtlas,
FaAtom,
FaAudioDescription,
FaAward,
FaBabyCarriage,
FaBaby,
FaBackspace,
FaBackward,
FaBacon,
FaBacteria,
FaBacterium,
FaBahai,
FaBalanceScaleLeft,
FaBalanceScaleRight,
FaBalanceScale,
FaBan,
FaBandAid,
FaBarcode,
FaBars,
FaBaseballBall,
FaBasketballBall,
FaBath,
FaBatteryEmpty,
FaBatteryFull,
FaBatteryHalf,
FaBatteryQuarter,
FaBatteryThreeQuarters,
FaBed,
FaBeer,
FaBellSlash,
FaBell,
FaBezierCurve,
FaBible,
FaBicycle,
FaBiking,
FaBinoculars,
FaBiohazard,
FaBirthdayCake,
FaBlenderPhone,
FaBlender,
FaBlind,
FaBlog,
FaBold,
FaBolt,
FaBomb,
FaBone,
FaBong,
FaBookDead,
FaBookMedical,
FaBookOpen,
FaBookReader,
FaBook,
FaBookmark,
FaBorderAll,
FaBorderNone,
FaBorderStyle,
FaBowlingBall,
FaBoxOpen,
FaBoxTissue,
FaBox,
FaBoxes,
FaBraille,
FaBrain,
FaBreadSlice,
FaBriefcaseMedical,
FaBriefcase,
FaBroadcastTower,
FaBroom,
FaBrush,
FaBug,
FaBuilding,
FaBullhorn,
FaBullseye,
FaBurn,
FaBusAlt,
FaBus,
FaBusinessTime,
FaCalculator,
FaCalendarAlt,
FaCalendarCheck,
FaCalendarDay,
FaCalendarMinus,
FaCalendarPlus,
FaCalendarTimes,
FaCalendarWeek,
FaCalendar,
FaCameraRetro,
FaCamera,
FaCampground,
FaCandyCane,
FaCannabis,
FaCapsules,
FaCarAlt,
FaCarBattery,
FaCarCrash,
FaCarSide,
FaCar,
FaCaravan,
FaCaretDown,
FaCaretLeft,
FaCaretRight,
FaCaretSquareDown,
FaCaretSquareLeft,
FaCaretSquareRight,
FaCaretSquareUp,
FaCaretUp,
FaCarrot,
FaCartArrowDown,
FaCartPlus,
FaCashRegister,
FaCat,
FaCertificate,
FaChair,
FaChalkboardTeacher,
FaChalkboard,
FaChargingStation,
FaChartArea,
FaChartBar,
FaChartLine,
FaChartPie,
FaCheckCircle,
FaCheckDouble,
FaCheckSquare,
FaCheck,
FaCheese,
FaChessBishop,
FaChessBoard,
FaChessKing,
FaChessKnight,
FaChessPawn,
FaChessQueen,
FaChessRook,
FaChess,
FaChevronCircleDown,
FaChevronCircleLeft,
FaChevronCircleRight,
FaChevronCircleUp,
FaChevronDown,
FaChevronLeft,
FaChevronRight,
FaChevronUp,
FaChild,
FaChurch,
FaCircleNotch,
FaCircle,
FaCity,
FaClinicMedical,
FaClipboardCheck,
FaClipboardList,
FaClipboard,
FaClock,
FaClone,
FaClosedCaptioning,
FaCloudDownloadAlt,
FaCloudMeatball,
FaCloudMoonRain,
FaCloudMoon,
FaCloudRain,
FaCloudShowersHeavy,
FaCloudSunRain,
FaCloudSun,
FaCloudUploadAlt,
FaCloud,
FaCocktail,
FaCodeBranch,
FaCode,
FaCoffee,
FaCog,
FaCogs,
FaCoins,
FaColumns,
FaCommentAlt,
FaCommentDollar,
FaCommentDots,
FaCommentMedical,
FaCommentSlash,
FaComment,
FaCommentsDollar,
FaComments,
FaCompactDisc,
FaCompass,
FaCompressAlt,
FaCompressArrowsAlt,
FaCompress,
FaConciergeBell,
FaCookieBite,
FaCookie,
FaCopy,
FaCopyright,
FaCouch,
FaCreditCard,
FaCropAlt,
FaCrop,
FaCross,
FaCrosshairs,
FaCrow,
FaCrown,
FaCrutch,
FaCube,
FaCubes,
FaCut,
FaDatabase,
FaDeaf,
FaDemocrat,
FaDesktop,
FaDharmachakra,
FaDiagnoses,
FaDiceD20,
FaDiceD6,
FaDiceFive,
FaDiceFour,
FaDiceOne,
FaDiceSix,
FaDiceThree,
FaDiceTwo,
FaDice,
FaDigitalTachograph,
FaDirections,
FaDisease,
FaDivide,
FaDizzy,
FaDna,
FaDog,
FaDollarSign,
FaDollyFlatbed,
FaDolly,
FaDonate,
FaDoorClosed,
FaDoorOpen,
FaDotCircle,
FaDove,
FaDownload,
FaDraftingCompass,
FaDragon,
FaDrawPolygon,
FaDrumSteelpan,
FaDrum,
FaDrumstickBite,
FaDumbbell,
FaDumpsterFire,
FaDumpster,
FaDungeon,
FaEdit,
FaEgg,
FaEject,
FaEllipsisH,
FaEllipsisV,
FaEnvelopeOpenText,
FaEnvelopeOpen,
FaEnvelopeSquare,
FaEnvelope,
FaEquals,
FaEraser,
FaEthernet,
FaEuroSign,
FaExchangeAlt,
FaExclamationCircle,
FaExclamationTriangle,
FaExclamation,
FaExpandAlt,
FaExpandArrowsAlt,
FaExpand,
FaExternalLinkAlt,
FaExternalLinkSquareAlt,
FaEyeDropper,
FaEyeSlash,
FaEye,
FaFan,
FaFastBackward,
FaFastForward,
FaFaucet,
FaFax,
FaFeatherAlt,
FaFeather,
FaFemale,
FaFighterJet,
FaFileAlt,
FaFileArchive,
FaFileAudio,
FaFileCode,
FaFileContract,
FaFileCsv,
FaFileDownload,
FaFileExcel,
FaFileExport,
FaFileImage,
FaFileImport,
FaFileInvoiceDollar,
FaFileInvoice,
FaFileMedicalAlt,
FaFileMedical,
FaFilePdf,
FaFilePowerpoint,
FaFilePrescription,
FaFileSignature,
FaFileUpload,
FaFileVideo,
FaFileWord,
FaFile,
FaFillDrip,
FaFill,
FaFilm,
FaFilter,
FaFingerprint,
FaFireAlt,
FaFireExtinguisher,
FaFire,
FaFirstAid,
FaFish,
FaFistRaised,
FaFlagCheckered,
FaFlagUsa,
FaFlag,
FaFlask,
FaFlushed,
FaFolderMinus,
FaFolderOpen,
FaFolderPlus,
FaFolder,
FaFont,
FaFootballBall,
FaForward,
FaFrog,
FaFrownOpen,
FaFrown,
FaFunnelDollar,
FaFutbol,
FaGamepad,
FaGasPump,
FaGavel,
FaGem,
FaGenderless,
FaGhost,
FaGift,
FaGifts,
FaGlassCheers,
FaGlassMartiniAlt,
FaGlassMartini,
FaGlassWhiskey,
FaGlasses,
FaGlobeAfrica,
FaGlobeAmericas,
FaGlobeAsia,
FaGlobeEurope,
FaGlobe,
FaGolfBall,
FaGopuram,
FaGraduationCap,
FaGreaterThanEqual,
FaGreaterThan,
FaGrimace,
FaGrinAlt,
FaGrinBeamSweat,
FaGrinBeam,
FaGrinHearts,
FaGrinSquintTears,
FaGrinSquint,
FaGrinStars,
FaGrinTears,
FaGrinTongueSquint,
FaGrinTongueWink,
FaGrinTongue,
FaGrinWink,
FaGrin,
FaGripHorizontal,
FaGripLinesVertical,
FaGripLines,
FaGripVertical,
FaGuitar,
FaHSquare,
FaHamburger,
FaHammer,
FaHamsa,
FaHandHoldingHeart,
FaHandHoldingMedical,
FaHandHoldingUsd,
FaHandHoldingWater,
FaHandHolding,
FaHandLizard,
FaHandMiddleFinger,
FaHandPaper,
FaHandPeace,
FaHandPointDown,
FaHandPointLeft,
FaHandPointRight,
FaHandPointUp,
FaHandPointer,
FaHandRock,
FaHandScissors,
FaHandSparkles,
FaHandSpock,
FaHandsHelping,
FaHandsWash,
FaHands,
FaHandshakeAltSlash,
FaHandshakeSlash,
FaHandshake,
FaHanukiah,
FaHardHat,
FaHashtag,
FaHatCowboySide,
FaHatCowboy,
FaHatWizard,
FaHdd,
FaHeadSideCoughSlash,
FaHeadSideCough,
FaHeadSideMask,
FaHeadSideVirus,
FaHeading,
FaHeadphonesAlt,
FaHeadphones,
FaHeadset,
FaHeartBroken,
FaHeart,
FaHeartbeat,
FaHelicopter,
FaHighlighter,
FaHiking,
FaHippo,
FaHistory,
FaHockeyPuck,
FaHollyBerry,
FaHome,
FaHorseHead,
FaHorse,
FaHospitalAlt,
FaHospitalSymbol,
FaHospitalUser,
FaHospital,
FaHotTub,
FaHotdog,
FaHotel,
FaHourglassEnd,
FaHourglassHalf,
FaHourglassStart,
FaHourglass,
FaHouseDamage,
FaHouseUser,
FaHryvnia,
FaICursor,
FaIceCream,
FaIcicles,
FaIcons,
FaIdBadge,
FaIdCardAlt,
FaIdCard,
FaIgloo,
FaImage,
FaImages,
FaInbox,
FaIndent,
FaIndustry,
FaInfinity,
FaInfoCircle,
FaInfo,
FaItalic,
FaJedi,
FaJoint,
FaJournalWhills,
FaKaaba,
FaKey,
FaKeyboard,
FaKhanda,
FaKissBeam,
FaKissWinkHeart,
FaKiss,
FaKiwiBird,
FaLandmark,
FaLanguage,
FaLaptopCode,
FaLaptopHouse,
FaLaptopMedical,
FaLaptop,
FaLaughBeam,
FaLaughSquint,
FaLaughWink,
FaLaugh,
FaLayerGroup,
FaLeaf,
FaLemon,
FaLessThanEqual,
FaLessThan,
FaLevelDownAlt,
FaLevelUpAlt,
FaLifeRing,
FaLightbulb,
FaLink,
FaLiraSign,
FaListAlt,
FaListOl,
FaListUl,
FaList,
FaLocationArrow,
FaLockOpen,
FaLock,
FaLongArrowAltDown,
FaLongArrowAltLeft,
FaLongArrowAltRight,
FaLongArrowAltUp,
FaLowVision,
FaLuggageCart,
FaLungsVirus,
FaLungs,
FaMagic,
FaMagnet,
FaMailBulk,
FaMale,
FaMapMarkedAlt,
FaMapMarked,
FaMapMarkerAlt,
FaMapMarker,
FaMapPin,
FaMapSigns,
FaMap,
FaMarker,
FaMarsDouble,
FaMarsStrokeH,
FaMarsStrokeV,
FaMarsStroke,
FaMars,
FaMask,
FaMedal,
FaMedkit,
FaMehBlank,
FaMehRollingEyes,
FaMeh,
FaMemory,
FaMenorah,
FaMercury,
FaMeteor,
FaMicrochip,
FaMicrophoneAltSlash,
FaMicrophoneAlt,
FaMicrophoneSlash,
FaMicrophone,
FaMicroscope,
FaMinusCircle,
FaMinusSquare,
FaMinus,
FaMitten,
FaMobileAlt,
FaMobile,
FaMoneyBillAlt,
FaMoneyBillWaveAlt,
FaMoneyBillWave,
FaMoneyBill,
FaMoneyCheckAlt,
FaMoneyCheck,
FaMonument,
FaMoon,
FaMortarPestle,
FaMosque,
FaMotorcycle,
FaMountain,
FaMousePointer,
FaMouse,
FaMugHot,
FaMusic,
FaNetworkWired,
FaNeuter,
FaNewspaper,
FaNotEqual,
FaNotesMedical,
FaObjectGroup,
FaObjectUngroup,
FaOilCan,
FaOm,
FaOtter,
FaOutdent,
FaPager,
FaPaintBrush,
FaPaintRoller,
FaPalette,
FaPallet,
FaPaperPlane,
FaPaperclip,
FaParachuteBox,
FaParagraph,
FaParking,
FaPassport,
FaPastafarianism,
FaPaste,
FaPauseCircle,
FaPause,
FaPaw,
FaPeace,
FaPenAlt,
FaPenFancy,
FaPenNib,
FaPenSquare,
FaPen,
FaPencilAlt,
FaPencilRuler,
FaPeopleArrows,
FaPeopleCarry,
FaPepperHot,
FaPercent,
FaPercentage,
FaPersonBooth,
FaPhoneAlt,
FaPhoneSlash,
FaPhoneSquareAlt,
FaPhoneSquare,
FaPhoneVolume,
FaPhone,
FaPhotoVideo,
FaPiggyBank,
FaPills,
FaPizzaSlice,
FaPlaceOfWorship,
FaPlaneArrival,
FaPlaneDeparture,
FaPlaneSlash,
FaPlane,
FaPlayCircle,
FaPlay,
FaPlug,
FaPlusCircle,
FaPlusSquare,
FaPlus,
FaPodcast,
FaPollH,
FaPoll,
FaPooStorm,
FaPoo,
FaPoop,
FaPortrait,
FaPoundSign,
FaPowerOff,
FaPray,
FaPrayingHands,
FaPrescriptionBottleAlt,
FaPrescriptionBottle,
FaPrescription,
FaPrint,
FaProcedures,
FaProjectDiagram,
FaPumpMedical,
FaPumpSoap,
FaPuzzlePiece,
FaQrcode,
FaQuestionCircle,
FaQuestion,
FaQuidditch,
FaQuoteLeft,
FaQuoteRight,
FaQuran,
FaRadiationAlt,
FaRadiation,
FaRainbow,
FaRandom,
FaReceipt,
FaRecordVinyl,
FaRecycle,
FaRedoAlt,
FaRedo,
FaRegistered,
FaRemoveFormat,
FaReplyAll,
FaReply,
FaRepublican,
FaRestroom,
FaRetweet,
FaRibbon,
FaRing,
FaRoad,
FaRobot,
FaRocket,
FaRoute,
FaRssSquare,
FaRss,
FaRubleSign,
FaRulerCombined,
FaRulerHorizontal,
FaRulerVertical,
FaRuler,
FaRunning,
FaRupeeSign,
FaSadCry,
FaSadTear,
FaSatelliteDish,
FaSatellite,
FaSave,
FaSchool,
FaScrewdriver,
FaScroll,
FaSdCard,
FaSearchDollar,
FaSearchLocation,
FaSearchMinus,
FaSearchPlus,
FaSearch,
FaSeedling,
FaServer,
FaShapes,
FaShareAltSquare,
FaShareAlt,
FaShareSquare,
FaShare,
FaShekelSign,
FaShieldAlt,
FaShieldVirus,
FaShip,
FaShippingFast,
FaShoePrints,
FaShoppingBag,
FaShoppingBasket,
FaShoppingCart,
FaShower,
FaShuttleVan,
FaSignInAlt,
FaSignLanguage,
FaSignOutAlt,
FaSign,
FaSignal,
FaSignature,
FaSimCard,
FaSink,
FaSitemap,
FaSkating,
FaSkiingNordic,
FaSkiing,
FaSkullCrossbones,
FaSkull,
FaSlash,
FaSleigh,
FaSlidersH,
FaSmileBeam,
FaSmileWink,
FaSmile,
FaSmog,
FaSmokingBan,
FaSmoking,
FaSms,
FaSnowboarding,
FaSnowflake,
FaSnowman,
FaSnowplow,
FaSoap,
FaSocks,
FaSolarPanel,
FaSortAlphaDownAlt,
FaSortAlphaDown,
FaSortAlphaUpAlt,
FaSortAlphaUp,
FaSortAmountDownAlt,
FaSortAmountDown,
FaSortAmountUpAlt,
FaSortAmountUp,
FaSortDown,
FaSortNumericDownAlt,
FaSortNumericDown,
FaSortNumericUpAlt,
FaSortNumericUp,
FaSortUp,
FaSort,
FaSpa,
FaSpaceShuttle,
FaSpellCheck,
FaSpider,
FaSpinner,
FaSplotch,
FaSprayCan,
FaSquareFull,
FaSquareRootAlt,
FaSquare,
FaStamp,
FaStarAndCrescent,
FaStarHalfAlt,
FaStarHalf,
FaStarOfDavid,
FaStarOfLife,
FaStar,
FaStepBackward,
FaStepForward,
FaStethoscope,
FaStickyNote,
FaStopCircle,
FaStop,
FaStopwatch20,
FaStopwatch,
FaStoreAltSlash,
FaStoreAlt,
FaStoreSlash,
FaStore,
FaStream,
FaStreetView,
FaStrikethrough,
FaStroopwafel,
FaSubscript,
FaSubway,
FaSuitcaseRolling,
FaSuitcase,
FaSun,
FaSuperscript,
FaSurprise,
FaSwatchbook,
FaSwimmer,
FaSwimmingPool,
FaSynagogue,
FaSyncAlt,
FaSync,
FaSyringe,
FaTableTennis,
FaTable,
FaTabletAlt,
FaTablet,
FaTablets,
FaTachometerAlt,
FaTag,
FaTags,
FaTape,
FaTasks,
FaTaxi,
FaTeethOpen,
FaTeeth,
FaTemperatureHigh,
FaTemperatureLow,
FaTenge,
FaTerminal,
FaTextHeight,
FaTextWidth,
FaThLarge,
FaThList,
FaTh,
FaTheaterMasks,
FaThermometerEmpty,
FaThermometerFull,
FaThermometerHalf,
FaThermometerQuarter,
FaThermometerThreeQuarters,
FaThermometer,
FaThumbsDown,
FaThumbsUp,
FaThumbtack,
FaTicketAlt,
FaTimesCircle,
FaTimes,
FaTintSlash,
FaTint,
FaTired,
FaToggleOff,
FaToggleOn,
FaToiletPaperSlash,
FaToiletPaper,
FaToilet,
FaToolbox,
FaTools,
FaTooth,
FaTorah,
FaToriiGate,
FaTractor,
FaTrademark,
FaTrafficLight,
FaTrailer,
FaTrain,
FaTram,
FaTransgenderAlt,
FaTransgender,
FaTrashAlt,
FaTrashRestoreAlt,
FaTrashRestore,
FaTrash,
FaTree,
FaTrophy,
FaTruckLoading,
FaTruckMonster,
FaTruckMoving,
FaTruckPickup,
FaTruck,
FaTshirt,
FaTty,
FaTv,
FaUmbrellaBeach,
FaUmbrella,
FaUnderline,
FaUndoAlt,
FaUndo,
FaUniversalAccess,
FaUniversity,
FaUnlink,
FaUnlockAlt,
FaUnlock,
FaUpload,
FaUserAltSlash,
FaUserAlt,
FaUserAstronaut,
FaUserCheck,
FaUserCircle,
FaUserClock,
FaUserCog,
FaUserEdit,
FaUserFriends,
FaUserGraduate,
FaUserInjured,
FaUserLock,
FaUserMd,
FaUserMinus,
FaUserNinja,
FaUserNurse,
FaUserPlus,
FaUserSecret,
FaUserShield,
FaUserSlash,
FaUserTag,
FaUserTie,
FaUserTimes,
FaUser,
FaUsersCog,
FaUsersSlash,
FaUsers,
FaUtensilSpoon,
FaUtensils,
FaVectorSquare,
FaVenusDouble,
FaVenusMars,
FaVenus,
FaVestPatches,
FaVest,
FaVial,
FaVials,
FaVideoSlash,
FaVideo,
FaVihara,
FaVirusSlash,
FaVirus,
FaViruses,
FaVoicemail,
FaVolleyballBall,
FaVolumeDown,
FaVolumeMute,
FaVolumeOff,
FaVolumeUp,
FaVoteYea,
FaVrCardboard,
FaWalking,
FaWallet,
FaWarehouse,
FaWater,
FaWaveSquare,
FaWeightHanging,
FaWeight,
FaWheelchair,
FaWifi,
FaWind,
FaWindowClose,
FaWindowMaximize,
FaWindowMinimize,
FaWindowRestore,
FaWineBottle,
FaWineGlassAlt,
FaWineGlass,
FaWonSign,
FaWrench,
FaXRay,
FaYenSign,
FaYinYang,
FaRegAddressBook,
FaRegAddressCard,
FaRegAngry,
FaRegArrowAltCircleDown,
FaRegArrowAltCircleLeft,
FaRegArrowAltCircleRight,
FaRegArrowAltCircleUp,
FaRegBellSlash,
FaRegBell,
FaRegBookmark,
FaRegBuilding,
FaRegCalendarAlt,
FaRegCalendarCheck,
FaRegCalendarMinus,
FaRegCalendarPlus,
FaRegCalendarTimes,
FaRegCalendar,
FaRegCaretSquareDown,
FaRegCaretSquareLeft,
FaRegCaretSquareRight,
FaRegCaretSquareUp,
FaRegChartBar,
FaRegCheckCircle,
FaRegCheckSquare,
FaRegCircle,
FaRegClipboard,
FaRegClock,
FaRegClone,
FaRegClosedCaptioning,
FaRegCommentAlt,
FaRegCommentDots,
FaRegComment,
FaRegComments,
FaRegCompass,
FaRegCopy,
FaRegCopyright,
FaRegCreditCard,
FaRegDizzy,
FaRegDotCircle,
FaRegEdit,
FaRegEnvelopeOpen,
FaRegEnvelope,
FaRegEyeSlash,
FaRegEye,
FaRegFileAlt,
FaRegFileArchive,
FaRegFileAudio,
FaRegFileCode,
FaRegFileExcel,
FaRegFileImage,
FaRegFilePdf,
FaRegFilePowerpoint,
FaRegFileVideo,
FaRegFileWord,
FaRegFile,
FaRegFlag,
FaRegFlushed,
FaRegFolderOpen,
FaRegFolder,
FaRegFontAwesomeLogoFull,
FaRegFrownOpen,
FaRegFrown,
FaRegFutbol,
FaRegGem,
FaRegGrimace,
FaRegGrinAlt,
FaRegGrinBeamSweat,
FaRegGrinBeam,
FaRegGrinHearts,
FaRegGrinSquintTears,
FaRegGrinSquint,
FaRegGrinStars,
FaRegGrinTears,
FaRegGrinTongueSquint,
FaRegGrinTongueWink,
FaRegGrinTongue,
FaRegGrinWink,
FaRegGrin,
FaRegHandLizard,
FaRegHandPaper,
FaRegHandPeace,
FaRegHandPointDown,
FaRegHandPointLeft,
FaRegHandPointRight,
FaRegHandPointUp,
FaRegHandPointer,
FaRegHandRock,
FaRegHandScissors,
FaRegHandSpock,
FaRegHandshake,
FaRegHdd,
FaRegHeart,
FaRegHospital,
FaRegHourglass,
FaRegIdBadge,
FaRegIdCard,
FaRegImage,
FaRegImages,
FaRegKeyboard,
FaRegKissBeam,
FaRegKissWinkHeart,
FaRegKiss,
FaRegLaughBeam,
FaRegLaughSquint,
FaRegLaughWink,
FaRegLaugh,
FaRegLemon,
FaRegLifeRing,
FaRegLightbulb,
FaRegListAlt,
FaRegMap,
FaRegMehBlank,
FaRegMehRollingEyes,
FaRegMeh,
FaRegMinusSquare,
FaRegMoneyBillAlt,
FaRegMoon,
FaRegNewspaper,
FaRegObjectGroup,
FaRegObjectUngroup,
FaRegPaperPlane,
FaRegPauseCircle,
FaRegPlayCircle,
FaRegPlusSquare,
FaRegQuestionCircle,
FaRegRegistered,
FaRegSadCry,
FaRegSadTear,
FaRegSave,
FaRegShareSquare,
FaRegSmileBeam,
FaRegSmileWink,
FaRegSmile,
FaRegSnowflake,
FaRegSquare,
FaRegStarHalf,
FaRegStar,
FaRegStickyNote,
FaRegStopCircle,
FaRegSun,
FaRegSurprise,
FaRegThumbsDown,
FaRegThumbsUp,
FaRegTimesCircle,
FaRegTired,
FaRegTrashAlt,
FaRegUserCircle,
FaRegUser,
FaRegWindowClose,
FaRegWindowMaximize,
FaRegWindowMinimize,
FaRegWindowRestore,
} from "react-icons/fa";

const result = [
{ icon: Fa500Px, name: "Fa500Px" },
{ icon: FaAccessibleIcon, name: "FaAccessibleIcon" },
{ icon: FaAccusoft, name: "FaAccusoft" },
{ icon: FaAcquisitionsIncorporated, name: "FaAcquisitionsIncorporated" },
{ icon: FaAdn, name: "FaAdn" },
{ icon: FaAdversal, name: "FaAdversal" },
{ icon: FaAffiliatetheme, name: "FaAffiliatetheme" },
{ icon: FaAirbnb, name: "FaAirbnb" },
{ icon: FaAlgolia, name: "FaAlgolia" },
{ icon: FaAlipay, name: "FaAlipay" },
{ icon: FaAmazonPay, name: "FaAmazonPay" },
{ icon: FaAmazon, name: "FaAmazon" },
{ icon: FaAmilia, name: "FaAmilia" },
{ icon: FaAndroid, name: "FaAndroid" },
{ icon: FaAngellist, name: "FaAngellist" },
{ icon: FaAngrycreative, name: "FaAngrycreative" },
{ icon: FaAngular, name: "FaAngular" },
{ icon: FaAppStoreIos, name: "FaAppStoreIos" },
{ icon: FaAppStore, name: "FaAppStore" },
{ icon: FaApper, name: "FaApper" },
{ icon: FaApplePay, name: "FaApplePay" },
{ icon: FaApple, name: "FaApple" },
{ icon: FaArtstation, name: "FaArtstation" },
{ icon: FaAsymmetrik, name: "FaAsymmetrik" },
{ icon: FaAtlassian, name: "FaAtlassian" },
{ icon: FaAudible, name: "FaAudible" },
{ icon: FaAutoprefixer, name: "FaAutoprefixer" },
{ icon: FaAvianex, name: "FaAvianex" },
{ icon: FaAviato, name: "FaAviato" },
{ icon: FaAws, name: "FaAws" },
{ icon: FaBandcamp, name: "FaBandcamp" },
{ icon: FaBattleNet, name: "FaBattleNet" },
{ icon: FaBehanceSquare, name: "FaBehanceSquare" },
{ icon: FaBehance, name: "FaBehance" },
{ icon: FaBimobject, name: "FaBimobject" },
{ icon: FaBitbucket, name: "FaBitbucket" },
{ icon: FaBitcoin, name: "FaBitcoin" },
{ icon: FaBity, name: "FaBity" },
{ icon: FaBlackTie, name: "FaBlackTie" },
{ icon: FaBlackberry, name: "FaBlackberry" },
{ icon: FaBloggerB, name: "FaBloggerB" },
{ icon: FaBlogger, name: "FaBlogger" },
{ icon: FaBluetoothB, name: "FaBluetoothB" },
{ icon: FaBluetooth, name: "FaBluetooth" },
{ icon: FaBootstrap, name: "FaBootstrap" },
{ icon: FaBtc, name: "FaBtc" },
{ icon: FaBuffer, name: "FaBuffer" },
{ icon: FaBuromobelexperte, name: "FaBuromobelexperte" },
{ icon: FaBuyNLarge, name: "FaBuyNLarge" },
{ icon: FaBuysellads, name: "FaBuysellads" },
{ icon: FaCanadianMapleLeaf, name: "FaCanadianMapleLeaf" },
{ icon: FaCcAmazonPay, name: "FaCcAmazonPay" },
{ icon: FaCcAmex, name: "FaCcAmex" },
{ icon: FaCcApplePay, name: "FaCcApplePay" },
{ icon: FaCcDinersClub, name: "FaCcDinersClub" },
{ icon: FaCcDiscover, name: "FaCcDiscover" },
{ icon: FaCcJcb, name: "FaCcJcb" },
{ icon: FaCcMastercard, name: "FaCcMastercard" },
{ icon: FaCcPaypal, name: "FaCcPaypal" },
{ icon: FaCcStripe, name: "FaCcStripe" },
{ icon: FaCcVisa, name: "FaCcVisa" },
{ icon: FaCentercode, name: "FaCentercode" },
{ icon: FaCentos, name: "FaCentos" },
{ icon: FaChrome, name: "FaChrome" },
{ icon: FaChromecast, name: "FaChromecast" },
{ icon: FaCloudflare, name: "FaCloudflare" },
{ icon: FaCloudscale, name: "FaCloudscale" },
{ icon: FaCloudsmith, name: "FaCloudsmith" },
{ icon: FaCloudversify, name: "FaCloudversify" },
{ icon: FaCodepen, name: "FaCodepen" },
{ icon: FaCodiepie, name: "FaCodiepie" },
{ icon: FaConfluence, name: "FaConfluence" },
{ icon: FaConnectdevelop, name: "FaConnectdevelop" },
{ icon: FaContao, name: "FaContao" },
{ icon: FaCottonBureau, name: "FaCottonBureau" },
{ icon: FaCpanel, name: "FaCpanel" },
{ icon: FaCreativeCommonsBy, name: "FaCreativeCommonsBy" },
{ icon: FaCreativeCommonsNcEu, name: "FaCreativeCommonsNcEu" },
{ icon: FaCreativeCommonsNcJp, name: "FaCreativeCommonsNcJp" },
{ icon: FaCreativeCommonsNc, name: "FaCreativeCommonsNc" },
{ icon: FaCreativeCommonsNd, name: "FaCreativeCommonsNd" },
{ icon: FaCreativeCommonsPdAlt, name: "FaCreativeCommonsPdAlt" },
{ icon: FaCreativeCommonsPd, name: "FaCreativeCommonsPd" },
{ icon: FaCreativeCommonsRemix, name: "FaCreativeCommonsRemix" },
{ icon: FaCreativeCommonsSa, name: "FaCreativeCommonsSa" },
{ icon: FaCreativeCommonsSamplingPlus, name: "FaCreativeCommonsSamplingPlus" },
{ icon: FaCreativeCommonsSampling, name: "FaCreativeCommonsSampling" },
{ icon: FaCreativeCommonsShare, name: "FaCreativeCommonsShare" },
{ icon: FaCreativeCommonsZero, name: "FaCreativeCommonsZero" },
{ icon: FaCreativeCommons, name: "FaCreativeCommons" },
{ icon: FaCriticalRole, name: "FaCriticalRole" },
{ icon: FaCss3Alt, name: "FaCss3Alt" },
{ icon: FaCss3, name: "FaCss3" },
{ icon: FaCuttlefish, name: "FaCuttlefish" },
{ icon: FaDAndDBeyond, name: "FaDAndDBeyond" },
{ icon: FaDAndD, name: "FaDAndD" },
{ icon: FaDailymotion, name: "FaDailymotion" },
{ icon: FaDashcube, name: "FaDashcube" },
{ icon: FaDeezer, name: "FaDeezer" },
{ icon: FaDelicious, name: "FaDelicious" },
{ icon: FaDeploydog, name: "FaDeploydog" },
{ icon: FaDeskpro, name: "FaDeskpro" },
{ icon: FaDev, name: "FaDev" },
{ icon: FaDeviantart, name: "FaDeviantart" },
{ icon: FaDhl, name: "FaDhl" },
{ icon: FaDiaspora, name: "FaDiaspora" },
{ icon: FaDigg, name: "FaDigg" },
{ icon: FaDigitalOcean, name: "FaDigitalOcean" },
{ icon: FaDiscord, name: "FaDiscord" },
{ icon: FaDiscourse, name: "FaDiscourse" },
{ icon: FaDochub, name: "FaDochub" },
{ icon: FaDocker, name: "FaDocker" },
{ icon: FaDraft2Digital, name: "FaDraft2Digital" },
{ icon: FaDribbbleSquare, name: "FaDribbbleSquare" },
{ icon: FaDribbble, name: "FaDribbble" },
{ icon: FaDropbox, name: "FaDropbox" },
{ icon: FaDrupal, name: "FaDrupal" },
{ icon: FaDyalog, name: "FaDyalog" },
{ icon: FaEarlybirds, name: "FaEarlybirds" },
{ icon: FaEbay, name: "FaEbay" },
{ icon: FaEdgeLegacy, name: "FaEdgeLegacy" },
{ icon: FaEdge, name: "FaEdge" },
{ icon: FaElementor, name: "FaElementor" },
{ icon: FaEllo, name: "FaEllo" },
{ icon: FaEmber, name: "FaEmber" },
{ icon: FaEmpire, name: "FaEmpire" },
{ icon: FaEnvira, name: "FaEnvira" },
{ icon: FaErlang, name: "FaErlang" },
{ icon: FaEthereum, name: "FaEthereum" },
{ icon: FaEtsy, name: "FaEtsy" },
{ icon: FaEvernote, name: "FaEvernote" },
{ icon: FaExpeditedssl, name: "FaExpeditedssl" },
{ icon: FaFacebookF, name: "FaFacebookF" },
{ icon: FaFacebookMessenger, name: "FaFacebookMessenger" },
{ icon: FaFacebookSquare, name: "FaFacebookSquare" },
{ icon: FaFacebook, name: "FaFacebook" },
{ icon: FaFantasyFlightGames, name: "FaFantasyFlightGames" },
{ icon: FaFedex, name: "FaFedex" },
{ icon: FaFedora, name: "FaFedora" },
{ icon: FaFigma, name: "FaFigma" },
{ icon: FaFirefoxBrowser, name: "FaFirefoxBrowser" },
{ icon: FaFirefox, name: "FaFirefox" },
{ icon: FaFirstOrderAlt, name: "FaFirstOrderAlt" },
{ icon: FaFirstOrder, name: "FaFirstOrder" },
{ icon: FaFirstdraft, name: "FaFirstdraft" },
{ icon: FaFlickr, name: "FaFlickr" },
{ icon: FaFlipboard, name: "FaFlipboard" },
{ icon: FaFly, name: "FaFly" },
{ icon: FaFontAwesomeAlt, name: "FaFontAwesomeAlt" },
{ icon: FaFontAwesomeFlag, name: "FaFontAwesomeFlag" },
{ icon: FaFontAwesomeLogoFull, name: "FaFontAwesomeLogoFull" },
{ icon: FaFontAwesome, name: "FaFontAwesome" },
{ icon: FaFonticonsFi, name: "FaFonticonsFi" },
{ icon: FaFonticons, name: "FaFonticons" },
{ icon: FaFortAwesomeAlt, name: "FaFortAwesomeAlt" },
{ icon: FaFortAwesome, name: "FaFortAwesome" },
{ icon: FaForumbee, name: "FaForumbee" },
{ icon: FaFoursquare, name: "FaFoursquare" },
{ icon: FaFreeCodeCamp, name: "FaFreeCodeCamp" },
{ icon: FaFreebsd, name: "FaFreebsd" },
{ icon: FaFulcrum, name: "FaFulcrum" },
{ icon: FaGalacticRepublic, name: "FaGalacticRepublic" },
{ icon: FaGalacticSenate, name: "FaGalacticSenate" },
{ icon: FaGetPocket, name: "FaGetPocket" },
{ icon: FaGgCircle, name: "FaGgCircle" },
{ icon: FaGg, name: "FaGg" },
{ icon: FaGitAlt, name: "FaGitAlt" },
{ icon: FaGitSquare, name: "FaGitSquare" },
{ icon: FaGit, name: "FaGit" },
{ icon: FaGithubAlt, name: "FaGithubAlt" },
{ icon: FaGithubSquare, name: "FaGithubSquare" },
{ icon: FaGithub, name: "FaGithub" },
{ icon: FaGitkraken, name: "FaGitkraken" },
{ icon: FaGitlab, name: "FaGitlab" },
{ icon: FaGitter, name: "FaGitter" },
{ icon: FaGlideG, name: "FaGlideG" },
{ icon: FaGlide, name: "FaGlide" },
{ icon: FaGofore, name: "FaGofore" },
{ icon: FaGoodreadsG, name: "FaGoodreadsG" },
{ icon: FaGoodreads, name: "FaGoodreads" },
{ icon: FaGoogleDrive, name: "FaGoogleDrive" },
{ icon: FaGooglePay, name: "FaGooglePay" },
{ icon: FaGooglePlay, name: "FaGooglePlay" },
{ icon: FaGooglePlusG, name: "FaGooglePlusG" },
{ icon: FaGooglePlusSquare, name: "FaGooglePlusSquare" },
{ icon: FaGooglePlus, name: "FaGooglePlus" },
{ icon: FaGoogleWallet, name: "FaGoogleWallet" },
{ icon: FaGoogle, name: "FaGoogle" },
{ icon: FaGratipay, name: "FaGratipay" },
{ icon: FaGrav, name: "FaGrav" },
{ icon: FaGripfire, name: "FaGripfire" },
{ icon: FaGrunt, name: "FaGrunt" },
{ icon: FaGuilded, name: "FaGuilded" },
{ icon: FaGulp, name: "FaGulp" },
{ icon: FaHackerNewsSquare, name: "FaHackerNewsSquare" },
{ icon: FaHackerNews, name: "FaHackerNews" },
{ icon: FaHackerrank, name: "FaHackerrank" },
{ icon: FaHips, name: "FaHips" },
{ icon: FaHireAHelper, name: "FaHireAHelper" },
{ icon: FaHive, name: "FaHive" },
{ icon: FaHooli, name: "FaHooli" },
{ icon: FaHornbill, name: "FaHornbill" },
{ icon: FaHotjar, name: "FaHotjar" },
{ icon: FaHouzz, name: "FaHouzz" },
{ icon: FaHtml5, name: "FaHtml5" },
{ icon: FaHubspot, name: "FaHubspot" },
{ icon: FaIdeal, name: "FaIdeal" },
{ icon: FaImdb, name: "FaImdb" },
{ icon: FaInnosoft, name: "FaInnosoft" },
{ icon: FaInstagramSquare, name: "FaInstagramSquare" },
{ icon: FaInstagram, name: "FaInstagram" },
{ icon: FaInstalod, name: "FaInstalod" },
{ icon: FaIntercom, name: "FaIntercom" },
{ icon: FaInternetExplorer, name: "FaInternetExplorer" },
{ icon: FaInvision, name: "FaInvision" },
{ icon: FaIoxhost, name: "FaIoxhost" },
{ icon: FaItchIo, name: "FaItchIo" },
{ icon: FaItunesNote, name: "FaItunesNote" },
{ icon: FaItunes, name: "FaItunes" },
{ icon: FaJava, name: "FaJava" },
{ icon: FaJediOrder, name: "FaJediOrder" },
{ icon: FaJenkins, name: "FaJenkins" },
{ icon: FaJira, name: "FaJira" },
{ icon: FaJoget, name: "FaJoget" },
{ icon: FaJoomla, name: "FaJoomla" },
{ icon: FaJsSquare, name: "FaJsSquare" },
{ icon: FaJs, name: "FaJs" },
{ icon: FaJsfiddle, name: "FaJsfiddle" },
{ icon: FaKaggle, name: "FaKaggle" },
{ icon: FaKeybase, name: "FaKeybase" },
{ icon: FaKeycdn, name: "FaKeycdn" },
{ icon: FaKickstarterK, name: "FaKickstarterK" },
{ icon: FaKickstarter, name: "FaKickstarter" },
{ icon: FaKorvue, name: "FaKorvue" },
{ icon: FaLaravel, name: "FaLaravel" },
{ icon: FaLastfmSquare, name: "FaLastfmSquare" },
{ icon: FaLastfm, name: "FaLastfm" },
{ icon: FaLeanpub, name: "FaLeanpub" },
{ icon: FaLess, name: "FaLess" },
{ icon: FaLine, name: "FaLine" },
{ icon: FaLinkedinIn, name: "FaLinkedinIn" },
{ icon: FaLinkedin, name: "FaLinkedin" },
{ icon: FaLinode, name: "FaLinode" },
{ icon: FaLinux, name: "FaLinux" },
{ icon: FaLyft, name: "FaLyft" },
{ icon: FaMagento, name: "FaMagento" },
{ icon: FaMailchimp, name: "FaMailchimp" },
{ icon: FaMandalorian, name: "FaMandalorian" },
{ icon: FaMarkdown, name: "FaMarkdown" },
{ icon: FaMastodon, name: "FaMastodon" },
{ icon: FaMaxcdn, name: "FaMaxcdn" },
{ icon: FaMdb, name: "FaMdb" },
{ icon: FaMedapps, name: "FaMedapps" },
{ icon: FaMediumM, name: "FaMediumM" },
{ icon: FaMedium, name: "FaMedium" },
{ icon: FaMedrt, name: "FaMedrt" },
{ icon: FaMeetup, name: "FaMeetup" },
{ icon: FaMegaport, name: "FaMegaport" },
{ icon: FaMendeley, name: "FaMendeley" },
{ icon: FaMicroblog, name: "FaMicroblog" },
{ icon: FaMicrosoft, name: "FaMicrosoft" },
{ icon: FaMix, name: "FaMix" },
{ icon: FaMixcloud, name: "FaMixcloud" },
{ icon: FaMixer, name: "FaMixer" },
{ icon: FaMizuni, name: "FaMizuni" },
{ icon: FaModx, name: "FaModx" },
{ icon: FaMonero, name: "FaMonero" },
{ icon: FaNapster, name: "FaNapster" },
{ icon: FaNeos, name: "FaNeos" },
{ icon: FaNimblr, name: "FaNimblr" },
{ icon: FaNodeJs, name: "FaNodeJs" },
{ icon: FaNode, name: "FaNode" },
{ icon: FaNpm, name: "FaNpm" },
{ icon: FaNs8, name: "FaNs8" },
{ icon: FaNutritionix, name: "FaNutritionix" },
{ icon: FaOctopusDeploy, name: "FaOctopusDeploy" },
{ icon: FaOdnoklassnikiSquare, name: "FaOdnoklassnikiSquare" },
{ icon: FaOdnoklassniki, name: "FaOdnoklassniki" },
{ icon: FaOldRepublic, name: "FaOldRepublic" },
{ icon: FaOpencart, name: "FaOpencart" },
{ icon: FaOpenid, name: "FaOpenid" },
{ icon: FaOpera, name: "FaOpera" },
{ icon: FaOptinMonster, name: "FaOptinMonster" },
{ icon: FaOrcid, name: "FaOrcid" },
{ icon: FaOsi, name: "FaOsi" },
{ icon: FaPage4, name: "FaPage4" },
{ icon: FaPagelines, name: "FaPagelines" },
{ icon: FaPalfed, name: "FaPalfed" },
{ icon: FaPatreon, name: "FaPatreon" },
{ icon: FaPaypal, name: "FaPaypal" },
{ icon: FaPennyArcade, name: "FaPennyArcade" },
{ icon: FaPerbyte, name: "FaPerbyte" },
{ icon: FaPeriscope, name: "FaPeriscope" },
{ icon: FaPhabricator, name: "FaPhabricator" },
{ icon: FaPhoenixFramework, name: "FaPhoenixFramework" },
{ icon: FaPhoenixSquadron, name: "FaPhoenixSquadron" },
{ icon: FaPhp, name: "FaPhp" },
{ icon: FaPiedPiperAlt, name: "FaPiedPiperAlt" },
{ icon: FaPiedPiperHat, name: "FaPiedPiperHat" },
{ icon: FaPiedPiperPp, name: "FaPiedPiperPp" },
{ icon: FaPiedPiperSquare, name: "FaPiedPiperSquare" },
{ icon: FaPiedPiper, name: "FaPiedPiper" },
{ icon: FaPinterestP, name: "FaPinterestP" },
{ icon: FaPinterestSquare, name: "FaPinterestSquare" },
{ icon: FaPinterest, name: "FaPinterest" },
{ icon: FaPlaystation, name: "FaPlaystation" },
{ icon: FaProductHunt, name: "FaProductHunt" },
{ icon: FaPushed, name: "FaPushed" },
{ icon: FaPython, name: "FaPython" },
{ icon: FaQq, name: "FaQq" },
{ icon: FaQuinscape, name: "FaQuinscape" },
{ icon: FaQuora, name: "FaQuora" },
{ icon: FaRProject, name: "FaRProject" },
{ icon: FaRaspberryPi, name: "FaRaspberryPi" },
{ icon: FaRavelry, name: "FaRavelry" },
{ icon: FaReact, name: "FaReact" },
{ icon: FaReacteurope, name: "FaReacteurope" },
{ icon: FaReadme, name: "FaReadme" },
{ icon: FaRebel, name: "FaRebel" },
{ icon: FaRedRiver, name: "FaRedRiver" },
{ icon: FaRedditAlien, name: "FaRedditAlien" },
{ icon: FaRedditSquare, name: "FaRedditSquare" },
{ icon: FaReddit, name: "FaReddit" },
{ icon: FaRedhat, name: "FaRedhat" },
{ icon: FaRenren, name: "FaRenren" },
{ icon: FaReplyd, name: "FaReplyd" },
{ icon: FaResearchgate, name: "FaResearchgate" },
{ icon: FaResolving, name: "FaResolving" },
{ icon: FaRev, name: "FaRev" },
{ icon: FaRocketchat, name: "FaRocketchat" },
{ icon: FaRockrms, name: "FaRockrms" },
{ icon: FaRust, name: "FaRust" },
{ icon: FaSafari, name: "FaSafari" },
{ icon: FaSalesforce, name: "FaSalesforce" },
{ icon: FaSass, name: "FaSass" },
{ icon: FaSchlix, name: "FaSchlix" },
{ icon: FaScribd, name: "FaScribd" },
{ icon: FaSearchengin, name: "FaSearchengin" },
{ icon: FaSellcast, name: "FaSellcast" },
{ icon: FaSellsy, name: "FaSellsy" },
{ icon: FaServicestack, name: "FaServicestack" },
{ icon: FaShirtsinbulk, name: "FaShirtsinbulk" },
{ icon: FaShopify, name: "FaShopify" },
{ icon: FaShopware, name: "FaShopware" },
{ icon: FaSimplybuilt, name: "FaSimplybuilt" },
{ icon: FaSistrix, name: "FaSistrix" },
{ icon: FaSith, name: "FaSith" },
{ icon: FaSketch, name: "FaSketch" },
{ icon: FaSkyatlas, name: "FaSkyatlas" },
{ icon: FaSkype, name: "FaSkype" },
{ icon: FaSlackHash, name: "FaSlackHash" },
{ icon: FaSlack, name: "FaSlack" },
{ icon: FaSlideshare, name: "FaSlideshare" },
{ icon: FaSnapchatGhost, name: "FaSnapchatGhost" },
{ icon: FaSnapchatSquare, name: "FaSnapchatSquare" },
{ icon: FaSnapchat, name: "FaSnapchat" },
{ icon: FaSoundcloud, name: "FaSoundcloud" },
{ icon: FaSourcetree, name: "FaSourcetree" },
{ icon: FaSpeakap, name: "FaSpeakap" },
{ icon: FaSpeakerDeck, name: "FaSpeakerDeck" },
{ icon: FaSpotify, name: "FaSpotify" },
{ icon: FaSquarespace, name: "FaSquarespace" },
{ icon: FaStackExchange, name: "FaStackExchange" },
{ icon: FaStackOverflow, name: "FaStackOverflow" },
{ icon: FaStackpath, name: "FaStackpath" },
{ icon: FaStaylinked, name: "FaStaylinked" },
{ icon: FaSteamSquare, name: "FaSteamSquare" },
{ icon: FaSteamSymbol, name: "FaSteamSymbol" },
{ icon: FaSteam, name: "FaSteam" },
{ icon: FaStickerMule, name: "FaStickerMule" },
{ icon: FaStrava, name: "FaStrava" },
{ icon: FaStripeS, name: "FaStripeS" },
{ icon: FaStripe, name: "FaStripe" },
{ icon: FaStudiovinari, name: "FaStudiovinari" },
{ icon: FaStumbleuponCircle, name: "FaStumbleuponCircle" },
{ icon: FaStumbleupon, name: "FaStumbleupon" },
{ icon: FaSuperpowers, name: "FaSuperpowers" },
{ icon: FaSupple, name: "FaSupple" },
{ icon: FaSuse, name: "FaSuse" },
{ icon: FaSwift, name: "FaSwift" },
{ icon: FaSymfony, name: "FaSymfony" },
{ icon: FaTeamspeak, name: "FaTeamspeak" },
{ icon: FaTelegramPlane, name: "FaTelegramPlane" },
{ icon: FaTelegram, name: "FaTelegram" },
{ icon: FaTencentWeibo, name: "FaTencentWeibo" },
{ icon: FaTheRedYeti, name: "FaTheRedYeti" },
{ icon: FaThemeco, name: "FaThemeco" },
{ icon: FaThemeisle, name: "FaThemeisle" },
{ icon: FaThinkPeaks, name: "FaThinkPeaks" },
{ icon: FaTiktok, name: "FaTiktok" },
{ icon: FaTradeFederation, name: "FaTradeFederation" },
{ icon: FaTrello, name: "FaTrello" },
{ icon: FaTripadvisor, name: "FaTripadvisor" },
{ icon: FaTumblrSquare, name: "FaTumblrSquare" },
{ icon: FaTumblr, name: "FaTumblr" },
{ icon: FaTwitch, name: "FaTwitch" },
{ icon: FaTwitterSquare, name: "FaTwitterSquare" },
{ icon: FaTwitter, name: "FaTwitter" },
{ icon: FaTypo3, name: "FaTypo3" },
{ icon: FaUber, name: "FaUber" },
{ icon: FaUbuntu, name: "FaUbuntu" },
{ icon: FaUikit, name: "FaUikit" },
{ icon: FaUmbraco, name: "FaUmbraco" },
{ icon: FaUncharted, name: "FaUncharted" },
{ icon: FaUniregistry, name: "FaUniregistry" },
{ icon: FaUnity, name: "FaUnity" },
{ icon: FaUnsplash, name: "FaUnsplash" },
{ icon: FaUntappd, name: "FaUntappd" },
{ icon: FaUps, name: "FaUps" },
{ icon: FaUsb, name: "FaUsb" },
{ icon: FaUsps, name: "FaUsps" },
{ icon: FaUssunnah, name: "FaUssunnah" },
{ icon: FaVaadin, name: "FaVaadin" },
{ icon: FaViacoin, name: "FaViacoin" },
{ icon: FaViadeoSquare, name: "FaViadeoSquare" },
{ icon: FaViadeo, name: "FaViadeo" },
{ icon: FaViber, name: "FaViber" },
{ icon: FaVimeoSquare, name: "FaVimeoSquare" },
{ icon: FaVimeoV, name: "FaVimeoV" },
{ icon: FaVimeo, name: "FaVimeo" },
{ icon: FaVine, name: "FaVine" },
{ icon: FaVk, name: "FaVk" },
{ icon: FaVnv, name: "FaVnv" },
{ icon: FaVuejs, name: "FaVuejs" },
{ icon: FaWatchmanMonitoring, name: "FaWatchmanMonitoring" },
{ icon: FaWaze, name: "FaWaze" },
{ icon: FaWeebly, name: "FaWeebly" },
{ icon: FaWeibo, name: "FaWeibo" },
{ icon: FaWeixin, name: "FaWeixin" },
{ icon: FaWhatsappSquare, name: "FaWhatsappSquare" },
{ icon: FaWhatsapp, name: "FaWhatsapp" },
{ icon: FaWhmcs, name: "FaWhmcs" },
{ icon: FaWikipediaW, name: "FaWikipediaW" },
{ icon: FaWindows, name: "FaWindows" },
{ icon: FaWix, name: "FaWix" },
{ icon: FaWizardsOfTheCoast, name: "FaWizardsOfTheCoast" },
{ icon: FaWodu, name: "FaWodu" },
{ icon: FaWolfPackBattalion, name: "FaWolfPackBattalion" },
{ icon: FaWordpressSimple, name: "FaWordpressSimple" },
{ icon: FaWordpress, name: "FaWordpress" },
{ icon: FaWpbeginner, name: "FaWpbeginner" },
{ icon: FaWpexplorer, name: "FaWpexplorer" },
{ icon: FaWpforms, name: "FaWpforms" },
{ icon: FaWpressr, name: "FaWpressr" },
{ icon: FaXbox, name: "FaXbox" },
{ icon: FaXingSquare, name: "FaXingSquare" },
{ icon: FaXing, name: "FaXing" },
{ icon: FaYCombinator, name: "FaYCombinator" },
{ icon: FaYahoo, name: "FaYahoo" },
{ icon: FaYammer, name: "FaYammer" },
{ icon: FaYandexInternational, name: "FaYandexInternational" },
{ icon: FaYandex, name: "FaYandex" },
{ icon: FaYarn, name: "FaYarn" },
{ icon: FaYelp, name: "FaYelp" },
{ icon: FaYoast, name: "FaYoast" },
{ icon: FaYoutubeSquare, name: "FaYoutubeSquare" },
{ icon: FaYoutube, name: "FaYoutube" },
{ icon: FaZhihu, name: "FaZhihu" },
{ icon: FaAd, name: "FaAd" },
{ icon: FaAddressBook, name: "FaAddressBook" },
{ icon: FaAddressCard, name: "FaAddressCard" },
{ icon: FaAdjust, name: "FaAdjust" },
{ icon: FaAirFreshener, name: "FaAirFreshener" },
{ icon: FaAlignCenter, name: "FaAlignCenter" },
{ icon: FaAlignJustify, name: "FaAlignJustify" },
{ icon: FaAlignLeft, name: "FaAlignLeft" },
{ icon: FaAlignRight, name: "FaAlignRight" },
{ icon: FaAllergies, name: "FaAllergies" },
{ icon: FaAmbulance, name: "FaAmbulance" },
{ icon: FaAmericanSignLanguageInterpreting, name: "FaAmericanSignLanguageInterpreting" },
{ icon: FaAnchor, name: "FaAnchor" },
{ icon: FaAngleDoubleDown, name: "FaAngleDoubleDown" },
{ icon: FaAngleDoubleLeft, name: "FaAngleDoubleLeft" },
{ icon: FaAngleDoubleRight, name: "FaAngleDoubleRight" },
{ icon: FaAngleDoubleUp, name: "FaAngleDoubleUp" },
{ icon: FaAngleDown, name: "FaAngleDown" },
{ icon: FaAngleLeft, name: "FaAngleLeft" },
{ icon: FaAngleRight, name: "FaAngleRight" },
{ icon: FaAngleUp, name: "FaAngleUp" },
{ icon: FaAngry, name: "FaAngry" },
{ icon: FaAnkh, name: "FaAnkh" },
{ icon: FaAppleAlt, name: "FaAppleAlt" },
{ icon: FaArchive, name: "FaArchive" },
{ icon: FaArchway, name: "FaArchway" },
{ icon: FaArrowAltCircleDown, name: "FaArrowAltCircleDown" },
{ icon: FaArrowAltCircleLeft, name: "FaArrowAltCircleLeft" },
{ icon: FaArrowAltCircleRight, name: "FaArrowAltCircleRight" },
{ icon: FaArrowAltCircleUp, name: "FaArrowAltCircleUp" },
{ icon: FaArrowCircleDown, name: "FaArrowCircleDown" },
{ icon: FaArrowCircleLeft, name: "FaArrowCircleLeft" },
{ icon: FaArrowCircleRight, name: "FaArrowCircleRight" },
{ icon: FaArrowCircleUp, name: "FaArrowCircleUp" },
{ icon: FaArrowDown, name: "FaArrowDown" },
{ icon: FaArrowLeft, name: "FaArrowLeft" },
{ icon: FaArrowRight, name: "FaArrowRight" },
{ icon: FaArrowUp, name: "FaArrowUp" },
{ icon: FaArrowsAltH, name: "FaArrowsAltH" },
{ icon: FaArrowsAltV, name: "FaArrowsAltV" },
{ icon: FaArrowsAlt, name: "FaArrowsAlt" },
{ icon: FaAssistiveListeningSystems, name: "FaAssistiveListeningSystems" },
{ icon: FaAsterisk, name: "FaAsterisk" },
{ icon: FaAt, name: "FaAt" },
{ icon: FaAtlas, name: "FaAtlas" },
{ icon: FaAtom, name: "FaAtom" },
{ icon: FaAudioDescription, name: "FaAudioDescription" },
{ icon: FaAward, name: "FaAward" },
{ icon: FaBabyCarriage, name: "FaBabyCarriage" },
{ icon: FaBaby, name: "FaBaby" },
{ icon: FaBackspace, name: "FaBackspace" },
{ icon: FaBackward, name: "FaBackward" },
{ icon: FaBacon, name: "FaBacon" },
{ icon: FaBacteria, name: "FaBacteria" },
{ icon: FaBacterium, name: "FaBacterium" },
{ icon: FaBahai, name: "FaBahai" },
{ icon: FaBalanceScaleLeft, name: "FaBalanceScaleLeft" },
{ icon: FaBalanceScaleRight, name: "FaBalanceScaleRight" },
{ icon: FaBalanceScale, name: "FaBalanceScale" },
{ icon: FaBan, name: "FaBan" },
{ icon: FaBandAid, name: "FaBandAid" },
{ icon: FaBarcode, name: "FaBarcode" },
{ icon: FaBars, name: "FaBars" },
{ icon: FaBaseballBall, name: "FaBaseballBall" },
{ icon: FaBasketballBall, name: "FaBasketballBall" },
{ icon: FaBath, name: "FaBath" },
{ icon: FaBatteryEmpty, name: "FaBatteryEmpty" },
{ icon: FaBatteryFull, name: "FaBatteryFull" },
{ icon: FaBatteryHalf, name: "FaBatteryHalf" },
{ icon: FaBatteryQuarter, name: "FaBatteryQuarter" },
{ icon: FaBatteryThreeQuarters, name: "FaBatteryThreeQuarters" },
{ icon: FaBed, name: "FaBed" },
{ icon: FaBeer, name: "FaBeer" },
{ icon: FaBellSlash, name: "FaBellSlash" },
{ icon: FaBell, name: "FaBell" },
{ icon: FaBezierCurve, name: "FaBezierCurve" },
{ icon: FaBible, name: "FaBible" },
{ icon: FaBicycle, name: "FaBicycle" },
{ icon: FaBiking, name: "FaBiking" },
{ icon: FaBinoculars, name: "FaBinoculars" },
{ icon: FaBiohazard, name: "FaBiohazard" },
{ icon: FaBirthdayCake, name: "FaBirthdayCake" },
{ icon: FaBlenderPhone, name: "FaBlenderPhone" },
{ icon: FaBlender, name: "FaBlender" },
{ icon: FaBlind, name: "FaBlind" },
{ icon: FaBlog, name: "FaBlog" },
{ icon: FaBold, name: "FaBold" },
{ icon: FaBolt, name: "FaBolt" },
{ icon: FaBomb, name: "FaBomb" },
{ icon: FaBone, name: "FaBone" },
{ icon: FaBong, name: "FaBong" },
{ icon: FaBookDead, name: "FaBookDead" },
{ icon: FaBookMedical, name: "FaBookMedical" },
{ icon: FaBookOpen, name: "FaBookOpen" },
{ icon: FaBookReader, name: "FaBookReader" },
{ icon: FaBook, name: "FaBook" },
{ icon: FaBookmark, name: "FaBookmark" },
{ icon: FaBorderAll, name: "FaBorderAll" },
{ icon: FaBorderNone, name: "FaBorderNone" },
{ icon: FaBorderStyle, name: "FaBorderStyle" },
{ icon: FaBowlingBall, name: "FaBowlingBall" },
{ icon: FaBoxOpen, name: "FaBoxOpen" },
{ icon: FaBoxTissue, name: "FaBoxTissue" },
{ icon: FaBox, name: "FaBox" },
{ icon: FaBoxes, name: "FaBoxes" },
{ icon: FaBraille, name: "FaBraille" },
{ icon: FaBrain, name: "FaBrain" },
{ icon: FaBreadSlice, name: "FaBreadSlice" },
{ icon: FaBriefcaseMedical, name: "FaBriefcaseMedical" },
{ icon: FaBriefcase, name: "FaBriefcase" },
{ icon: FaBroadcastTower, name: "FaBroadcastTower" },
{ icon: FaBroom, name: "FaBroom" },
{ icon: FaBrush, name: "FaBrush" },
{ icon: FaBug, name: "FaBug" },
{ icon: FaBuilding, name: "FaBuilding" },
{ icon: FaBullhorn, name: "FaBullhorn" },
{ icon: FaBullseye, name: "FaBullseye" },
{ icon: FaBurn, name: "FaBurn" },
{ icon: FaBusAlt, name: "FaBusAlt" },
{ icon: FaBus, name: "FaBus" },
{ icon: FaBusinessTime, name: "FaBusinessTime" },
{ icon: FaCalculator, name: "FaCalculator" },
{ icon: FaCalendarAlt, name: "FaCalendarAlt" },
{ icon: FaCalendarCheck, name: "FaCalendarCheck" },
{ icon: FaCalendarDay, name: "FaCalendarDay" },
{ icon: FaCalendarMinus, name: "FaCalendarMinus" },
{ icon: FaCalendarPlus, name: "FaCalendarPlus" },
{ icon: FaCalendarTimes, name: "FaCalendarTimes" },
{ icon: FaCalendarWeek, name: "FaCalendarWeek" },
{ icon: FaCalendar, name: "FaCalendar" },
{ icon: FaCameraRetro, name: "FaCameraRetro" },
{ icon: FaCamera, name: "FaCamera" },
{ icon: FaCampground, name: "FaCampground" },
{ icon: FaCandyCane, name: "FaCandyCane" },
{ icon: FaCannabis, name: "FaCannabis" },
{ icon: FaCapsules, name: "FaCapsules" },
{ icon: FaCarAlt, name: "FaCarAlt" },
{ icon: FaCarBattery, name: "FaCarBattery" },
{ icon: FaCarCrash, name: "FaCarCrash" },
{ icon: FaCarSide, name: "FaCarSide" },
{ icon: FaCar, name: "FaCar" },
{ icon: FaCaravan, name: "FaCaravan" },
{ icon: FaCaretDown, name: "FaCaretDown" },
{ icon: FaCaretLeft, name: "FaCaretLeft" },
{ icon: FaCaretRight, name: "FaCaretRight" },
{ icon: FaCaretSquareDown, name: "FaCaretSquareDown" },
{ icon: FaCaretSquareLeft, name: "FaCaretSquareLeft" },
{ icon: FaCaretSquareRight, name: "FaCaretSquareRight" },
{ icon: FaCaretSquareUp, name: "FaCaretSquareUp" },
{ icon: FaCaretUp, name: "FaCaretUp" },
{ icon: FaCarrot, name: "FaCarrot" },
{ icon: FaCartArrowDown, name: "FaCartArrowDown" },
{ icon: FaCartPlus, name: "FaCartPlus" },
{ icon: FaCashRegister, name: "FaCashRegister" },
{ icon: FaCat, name: "FaCat" },
{ icon: FaCertificate, name: "FaCertificate" },
{ icon: FaChair, name: "FaChair" },
{ icon: FaChalkboardTeacher, name: "FaChalkboardTeacher" },
{ icon: FaChalkboard, name: "FaChalkboard" },
{ icon: FaChargingStation, name: "FaChargingStation" },
{ icon: FaChartArea, name: "FaChartArea" },
{ icon: FaChartBar, name: "FaChartBar" },
{ icon: FaChartLine, name: "FaChartLine" },
{ icon: FaChartPie, name: "FaChartPie" },
{ icon: FaCheckCircle, name: "FaCheckCircle" },
{ icon: FaCheckDouble, name: "FaCheckDouble" },
{ icon: FaCheckSquare, name: "FaCheckSquare" },
{ icon: FaCheck, name: "FaCheck" },
{ icon: FaCheese, name: "FaCheese" },
{ icon: FaChessBishop, name: "FaChessBishop" },
{ icon: FaChessBoard, name: "FaChessBoard" },
{ icon: FaChessKing, name: "FaChessKing" },
{ icon: FaChessKnight, name: "FaChessKnight" },
{ icon: FaChessPawn, name: "FaChessPawn" },
{ icon: FaChessQueen, name: "FaChessQueen" },
{ icon: FaChessRook, name: "FaChessRook" },
{ icon: FaChess, name: "FaChess" },
{ icon: FaChevronCircleDown, name: "FaChevronCircleDown" },
{ icon: FaChevronCircleLeft, name: "FaChevronCircleLeft" },
{ icon: FaChevronCircleRight, name: "FaChevronCircleRight" },
{ icon: FaChevronCircleUp, name: "FaChevronCircleUp" },
{ icon: FaChevronDown, name: "FaChevronDown" },
{ icon: FaChevronLeft, name: "FaChevronLeft" },
{ icon: FaChevronRight, name: "FaChevronRight" },
{ icon: FaChevronUp, name: "FaChevronUp" },
{ icon: FaChild, name: "FaChild" },
{ icon: FaChurch, name: "FaChurch" },
{ icon: FaCircleNotch, name: "FaCircleNotch" },
{ icon: FaCircle, name: "FaCircle" },
{ icon: FaCity, name: "FaCity" },
{ icon: FaClinicMedical, name: "FaClinicMedical" },
{ icon: FaClipboardCheck, name: "FaClipboardCheck" },
{ icon: FaClipboardList, name: "FaClipboardList" },
{ icon: FaClipboard, name: "FaClipboard" },
{ icon: FaClock, name: "FaClock" },
{ icon: FaClone, name: "FaClone" },
{ icon: FaClosedCaptioning, name: "FaClosedCaptioning" },
{ icon: FaCloudDownloadAlt, name: "FaCloudDownloadAlt" },
{ icon: FaCloudMeatball, name: "FaCloudMeatball" },
{ icon: FaCloudMoonRain, name: "FaCloudMoonRain" },
{ icon: FaCloudMoon, name: "FaCloudMoon" },
{ icon: FaCloudRain, name: "FaCloudRain" },
{ icon: FaCloudShowersHeavy, name: "FaCloudShowersHeavy" },
{ icon: FaCloudSunRain, name: "FaCloudSunRain" },
{ icon: FaCloudSun, name: "FaCloudSun" },
{ icon: FaCloudUploadAlt, name: "FaCloudUploadAlt" },
{ icon: FaCloud, name: "FaCloud" },
{ icon: FaCocktail, name: "FaCocktail" },
{ icon: FaCodeBranch, name: "FaCodeBranch" },
{ icon: FaCode, name: "FaCode" },
{ icon: FaCoffee, name: "FaCoffee" },
{ icon: FaCog, name: "FaCog" },
{ icon: FaCogs, name: "FaCogs" },
{ icon: FaCoins, name: "FaCoins" },
{ icon: FaColumns, name: "FaColumns" },
{ icon: FaCommentAlt, name: "FaCommentAlt" },
{ icon: FaCommentDollar, name: "FaCommentDollar" },
{ icon: FaCommentDots, name: "FaCommentDots" },
{ icon: FaCommentMedical, name: "FaCommentMedical" },
{ icon: FaCommentSlash, name: "FaCommentSlash" },
{ icon: FaComment, name: "FaComment" },
{ icon: FaCommentsDollar, name: "FaCommentsDollar" },
{ icon: FaComments, name: "FaComments" },
{ icon: FaCompactDisc, name: "FaCompactDisc" },
{ icon: FaCompass, name: "FaCompass" },
{ icon: FaCompressAlt, name: "FaCompressAlt" },
{ icon: FaCompressArrowsAlt, name: "FaCompressArrowsAlt" },
{ icon: FaCompress, name: "FaCompress" },
{ icon: FaConciergeBell, name: "FaConciergeBell" },
{ icon: FaCookieBite, name: "FaCookieBite" },
{ icon: FaCookie, name: "FaCookie" },
{ icon: FaCopy, name: "FaCopy" },
{ icon: FaCopyright, name: "FaCopyright" },
{ icon: FaCouch, name: "FaCouch" },
{ icon: FaCreditCard, name: "FaCreditCard" },
{ icon: FaCropAlt, name: "FaCropAlt" },
{ icon: FaCrop, name: "FaCrop" },
{ icon: FaCross, name: "FaCross" },
{ icon: FaCrosshairs, name: "FaCrosshairs" },
{ icon: FaCrow, name: "FaCrow" },
{ icon: FaCrown, name: "FaCrown" },
{ icon: FaCrutch, name: "FaCrutch" },
{ icon: FaCube, name: "FaCube" },
{ icon: FaCubes, name: "FaCubes" },
{ icon: FaCut, name: "FaCut" },
{ icon: FaDatabase, name: "FaDatabase" },
{ icon: FaDeaf, name: "FaDeaf" },
{ icon: FaDemocrat, name: "FaDemocrat" },
{ icon: FaDesktop, name: "FaDesktop" },
{ icon: FaDharmachakra, name: "FaDharmachakra" },
{ icon: FaDiagnoses, name: "FaDiagnoses" },
{ icon: FaDiceD20, name: "FaDiceD20" },
{ icon: FaDiceD6, name: "FaDiceD6" },
{ icon: FaDiceFive, name: "FaDiceFive" },
{ icon: FaDiceFour, name: "FaDiceFour" },
{ icon: FaDiceOne, name: "FaDiceOne" },
{ icon: FaDiceSix, name: "FaDiceSix" },
{ icon: FaDiceThree, name: "FaDiceThree" },
{ icon: FaDiceTwo, name: "FaDiceTwo" },
{ icon: FaDice, name: "FaDice" },
{ icon: FaDigitalTachograph, name: "FaDigitalTachograph" },
{ icon: FaDirections, name: "FaDirections" },
{ icon: FaDisease, name: "FaDisease" },
{ icon: FaDivide, name: "FaDivide" },
{ icon: FaDizzy, name: "FaDizzy" },
{ icon: FaDna, name: "FaDna" },
{ icon: FaDog, name: "FaDog" },
{ icon: FaDollarSign, name: "FaDollarSign" },
{ icon: FaDollyFlatbed, name: "FaDollyFlatbed" },
{ icon: FaDolly, name: "FaDolly" },
{ icon: FaDonate, name: "FaDonate" },
{ icon: FaDoorClosed, name: "FaDoorClosed" },
{ icon: FaDoorOpen, name: "FaDoorOpen" },
{ icon: FaDotCircle, name: "FaDotCircle" },
{ icon: FaDove, name: "FaDove" },
{ icon: FaDownload, name: "FaDownload" },
{ icon: FaDraftingCompass, name: "FaDraftingCompass" },
{ icon: FaDragon, name: "FaDragon" },
{ icon: FaDrawPolygon, name: "FaDrawPolygon" },
{ icon: FaDrumSteelpan, name: "FaDrumSteelpan" },
{ icon: FaDrum, name: "FaDrum" },
{ icon: FaDrumstickBite, name: "FaDrumstickBite" },
{ icon: FaDumbbell, name: "FaDumbbell" },
{ icon: FaDumpsterFire, name: "FaDumpsterFire" },
{ icon: FaDumpster, name: "FaDumpster" },
{ icon: FaDungeon, name: "FaDungeon" },
{ icon: FaEdit, name: "FaEdit" },
{ icon: FaEgg, name: "FaEgg" },
{ icon: FaEject, name: "FaEject" },
{ icon: FaEllipsisH, name: "FaEllipsisH" },
{ icon: FaEllipsisV, name: "FaEllipsisV" },
{ icon: FaEnvelopeOpenText, name: "FaEnvelopeOpenText" },
{ icon: FaEnvelopeOpen, name: "FaEnvelopeOpen" },
{ icon: FaEnvelopeSquare, name: "FaEnvelopeSquare" },
{ icon: FaEnvelope, name: "FaEnvelope" },
{ icon: FaEquals, name: "FaEquals" },
{ icon: FaEraser, name: "FaEraser" },
{ icon: FaEthernet, name: "FaEthernet" },
{ icon: FaEuroSign, name: "FaEuroSign" },
{ icon: FaExchangeAlt, name: "FaExchangeAlt" },
{ icon: FaExclamationCircle, name: "FaExclamationCircle" },
{ icon: FaExclamationTriangle, name: "FaExclamationTriangle" },
{ icon: FaExclamation, name: "FaExclamation" },
{ icon: FaExpandAlt, name: "FaExpandAlt" },
{ icon: FaExpandArrowsAlt, name: "FaExpandArrowsAlt" },
{ icon: FaExpand, name: "FaExpand" },
{ icon: FaExternalLinkAlt, name: "FaExternalLinkAlt" },
{ icon: FaExternalLinkSquareAlt, name: "FaExternalLinkSquareAlt" },
{ icon: FaEyeDropper, name: "FaEyeDropper" },
{ icon: FaEyeSlash, name: "FaEyeSlash" },
{ icon: FaEye, name: "FaEye" },
{ icon: FaFan, name: "FaFan" },
{ icon: FaFastBackward, name: "FaFastBackward" },
{ icon: FaFastForward, name: "FaFastForward" },
{ icon: FaFaucet, name: "FaFaucet" },
{ icon: FaFax, name: "FaFax" },
{ icon: FaFeatherAlt, name: "FaFeatherAlt" },
{ icon: FaFeather, name: "FaFeather" },
{ icon: FaFemale, name: "FaFemale" },
{ icon: FaFighterJet, name: "FaFighterJet" },
{ icon: FaFileAlt, name: "FaFileAlt" },
{ icon: FaFileArchive, name: "FaFileArchive" },
{ icon: FaFileAudio, name: "FaFileAudio" },
{ icon: FaFileCode, name: "FaFileCode" },
{ icon: FaFileContract, name: "FaFileContract" },
{ icon: FaFileCsv, name: "FaFileCsv" },
{ icon: FaFileDownload, name: "FaFileDownload" },
{ icon: FaFileExcel, name: "FaFileExcel" },
{ icon: FaFileExport, name: "FaFileExport" },
{ icon: FaFileImage, name: "FaFileImage" },
{ icon: FaFileImport, name: "FaFileImport" },
{ icon: FaFileInvoiceDollar, name: "FaFileInvoiceDollar" },
{ icon: FaFileInvoice, name: "FaFileInvoice" },
{ icon: FaFileMedicalAlt, name: "FaFileMedicalAlt" },
{ icon: FaFileMedical, name: "FaFileMedical" },
{ icon: FaFilePdf, name: "FaFilePdf" },
{ icon: FaFilePowerpoint, name: "FaFilePowerpoint" },
{ icon: FaFilePrescription, name: "FaFilePrescription" },
{ icon: FaFileSignature, name: "FaFileSignature" },
{ icon: FaFileUpload, name: "FaFileUpload" },
{ icon: FaFileVideo, name: "FaFileVideo" },
{ icon: FaFileWord, name: "FaFileWord" },
{ icon: FaFile, name: "FaFile" },
{ icon: FaFillDrip, name: "FaFillDrip" },
{ icon: FaFill, name: "FaFill" },
{ icon: FaFilm, name: "FaFilm" },
{ icon: FaFilter, name: "FaFilter" },
{ icon: FaFingerprint, name: "FaFingerprint" },
{ icon: FaFireAlt, name: "FaFireAlt" },
{ icon: FaFireExtinguisher, name: "FaFireExtinguisher" },
{ icon: FaFire, name: "FaFire" },
{ icon: FaFirstAid, name: "FaFirstAid" },
{ icon: FaFish, name: "FaFish" },
{ icon: FaFistRaised, name: "FaFistRaised" },
{ icon: FaFlagCheckered, name: "FaFlagCheckered" },
{ icon: FaFlagUsa, name: "FaFlagUsa" },
{ icon: FaFlag, name: "FaFlag" },
{ icon: FaFlask, name: "FaFlask" },
{ icon: FaFlushed, name: "FaFlushed" },
{ icon: FaFolderMinus, name: "FaFolderMinus" },
{ icon: FaFolderOpen, name: "FaFolderOpen" },
{ icon: FaFolderPlus, name: "FaFolderPlus" },
{ icon: FaFolder, name: "FaFolder" },
{ icon: FaFont, name: "FaFont" },
{ icon: FaFootballBall, name: "FaFootballBall" },
{ icon: FaForward, name: "FaForward" },
{ icon: FaFrog, name: "FaFrog" },
{ icon: FaFrownOpen, name: "FaFrownOpen" },
{ icon: FaFrown, name: "FaFrown" },
{ icon: FaFunnelDollar, name: "FaFunnelDollar" },
{ icon: FaFutbol, name: "FaFutbol" },
{ icon: FaGamepad, name: "FaGamepad" },
{ icon: FaGasPump, name: "FaGasPump" },
{ icon: FaGavel, name: "FaGavel" },
{ icon: FaGem, name: "FaGem" },
{ icon: FaGenderless, name: "FaGenderless" },
{ icon: FaGhost, name: "FaGhost" },
{ icon: FaGift, name: "FaGift" },
{ icon: FaGifts, name: "FaGifts" },
{ icon: FaGlassCheers, name: "FaGlassCheers" },
{ icon: FaGlassMartiniAlt, name: "FaGlassMartiniAlt" },
{ icon: FaGlassMartini, name: "FaGlassMartini" },
{ icon: FaGlassWhiskey, name: "FaGlassWhiskey" },
{ icon: FaGlasses, name: "FaGlasses" },
{ icon: FaGlobeAfrica, name: "FaGlobeAfrica" },
{ icon: FaGlobeAmericas, name: "FaGlobeAmericas" },
{ icon: FaGlobeAsia, name: "FaGlobeAsia" },
{ icon: FaGlobeEurope, name: "FaGlobeEurope" },
{ icon: FaGlobe, name: "FaGlobe" },
{ icon: FaGolfBall, name: "FaGolfBall" },
{ icon: FaGopuram, name: "FaGopuram" },
{ icon: FaGraduationCap, name: "FaGraduationCap" },
{ icon: FaGreaterThanEqual, name: "FaGreaterThanEqual" },
{ icon: FaGreaterThan, name: "FaGreaterThan" },
{ icon: FaGrimace, name: "FaGrimace" },
{ icon: FaGrinAlt, name: "FaGrinAlt" },
{ icon: FaGrinBeamSweat, name: "FaGrinBeamSweat" },
{ icon: FaGrinBeam, name: "FaGrinBeam" },
{ icon: FaGrinHearts, name: "FaGrinHearts" },
{ icon: FaGrinSquintTears, name: "FaGrinSquintTears" },
{ icon: FaGrinSquint, name: "FaGrinSquint" },
{ icon: FaGrinStars, name: "FaGrinStars" },
{ icon: FaGrinTears, name: "FaGrinTears" },
{ icon: FaGrinTongueSquint, name: "FaGrinTongueSquint" },
{ icon: FaGrinTongueWink, name: "FaGrinTongueWink" },
{ icon: FaGrinTongue, name: "FaGrinTongue" },
{ icon: FaGrinWink, name: "FaGrinWink" },
{ icon: FaGrin, name: "FaGrin" },
{ icon: FaGripHorizontal, name: "FaGripHorizontal" },
{ icon: FaGripLinesVertical, name: "FaGripLinesVertical" },
{ icon: FaGripLines, name: "FaGripLines" },
{ icon: FaGripVertical, name: "FaGripVertical" },
{ icon: FaGuitar, name: "FaGuitar" },
{ icon: FaHSquare, name: "FaHSquare" },
{ icon: FaHamburger, name: "FaHamburger" },
{ icon: FaHammer, name: "FaHammer" },
{ icon: FaHamsa, name: "FaHamsa" },
{ icon: FaHandHoldingHeart, name: "FaHandHoldingHeart" },
{ icon: FaHandHoldingMedical, name: "FaHandHoldingMedical" },
{ icon: FaHandHoldingUsd, name: "FaHandHoldingUsd" },
{ icon: FaHandHoldingWater, name: "FaHandHoldingWater" },
{ icon: FaHandHolding, name: "FaHandHolding" },
{ icon: FaHandLizard, name: "FaHandLizard" },
{ icon: FaHandMiddleFinger, name: "FaHandMiddleFinger" },
{ icon: FaHandPaper, name: "FaHandPaper" },
{ icon: FaHandPeace, name: "FaHandPeace" },
{ icon: FaHandPointDown, name: "FaHandPointDown" },
{ icon: FaHandPointLeft, name: "FaHandPointLeft" },
{ icon: FaHandPointRight, name: "FaHandPointRight" },
{ icon: FaHandPointUp, name: "FaHandPointUp" },
{ icon: FaHandPointer, name: "FaHandPointer" },
{ icon: FaHandRock, name: "FaHandRock" },
{ icon: FaHandScissors, name: "FaHandScissors" },
{ icon: FaHandSparkles, name: "FaHandSparkles" },
{ icon: FaHandSpock, name: "FaHandSpock" },
{ icon: FaHandsHelping, name: "FaHandsHelping" },
{ icon: FaHandsWash, name: "FaHandsWash" },
{ icon: FaHands, name: "FaHands" },
{ icon: FaHandshakeAltSlash, name: "FaHandshakeAltSlash" },
{ icon: FaHandshakeSlash, name: "FaHandshakeSlash" },
{ icon: FaHandshake, name: "FaHandshake" },
{ icon: FaHanukiah, name: "FaHanukiah" },
{ icon: FaHardHat, name: "FaHardHat" },
{ icon: FaHashtag, name: "FaHashtag" },
{ icon: FaHatCowboySide, name: "FaHatCowboySide" },
{ icon: FaHatCowboy, name: "FaHatCowboy" },
{ icon: FaHatWizard, name: "FaHatWizard" },
{ icon: FaHdd, name: "FaHdd" },
{ icon: FaHeadSideCoughSlash, name: "FaHeadSideCoughSlash" },
{ icon: FaHeadSideCough, name: "FaHeadSideCough" },
{ icon: FaHeadSideMask, name: "FaHeadSideMask" },
{ icon: FaHeadSideVirus, name: "FaHeadSideVirus" },
{ icon: FaHeading, name: "FaHeading" },
{ icon: FaHeadphonesAlt, name: "FaHeadphonesAlt" },
{ icon: FaHeadphones, name: "FaHeadphones" },
{ icon: FaHeadset, name: "FaHeadset" },
{ icon: FaHeartBroken, name: "FaHeartBroken" },
{ icon: FaHeart, name: "FaHeart" },
{ icon: FaHeartbeat, name: "FaHeartbeat" },
{ icon: FaHelicopter, name: "FaHelicopter" },
{ icon: FaHighlighter, name: "FaHighlighter" },
{ icon: FaHiking, name: "FaHiking" },
{ icon: FaHippo, name: "FaHippo" },
{ icon: FaHistory, name: "FaHistory" },
{ icon: FaHockeyPuck, name: "FaHockeyPuck" },
{ icon: FaHollyBerry, name: "FaHollyBerry" },
{ icon: FaHome, name: "FaHome" },
{ icon: FaHorseHead, name: "FaHorseHead" },
{ icon: FaHorse, name: "FaHorse" },
{ icon: FaHospitalAlt, name: "FaHospitalAlt" },
{ icon: FaHospitalSymbol, name: "FaHospitalSymbol" },
{ icon: FaHospitalUser, name: "FaHospitalUser" },
{ icon: FaHospital, name: "FaHospital" },
{ icon: FaHotTub, name: "FaHotTub" },
{ icon: FaHotdog, name: "FaHotdog" },
{ icon: FaHotel, name: "FaHotel" },
{ icon: FaHourglassEnd, name: "FaHourglassEnd" },
{ icon: FaHourglassHalf, name: "FaHourglassHalf" },
{ icon: FaHourglassStart, name: "FaHourglassStart" },
{ icon: FaHourglass, name: "FaHourglass" },
{ icon: FaHouseDamage, name: "FaHouseDamage" },
{ icon: FaHouseUser, name: "FaHouseUser" },
{ icon: FaHryvnia, name: "FaHryvnia" },
{ icon: FaICursor, name: "FaICursor" },
{ icon: FaIceCream, name: "FaIceCream" },
{ icon: FaIcicles, name: "FaIcicles" },
{ icon: FaIcons, name: "FaIcons" },
{ icon: FaIdBadge, name: "FaIdBadge" },
{ icon: FaIdCardAlt, name: "FaIdCardAlt" },
{ icon: FaIdCard, name: "FaIdCard" },
{ icon: FaIgloo, name: "FaIgloo" },
{ icon: FaImage, name: "FaImage" },
{ icon: FaImages, name: "FaImages" },
{ icon: FaInbox, name: "FaInbox" },
{ icon: FaIndent, name: "FaIndent" },
{ icon: FaIndustry, name: "FaIndustry" },
{ icon: FaInfinity, name: "FaInfinity" },
{ icon: FaInfoCircle, name: "FaInfoCircle" },
{ icon: FaInfo, name: "FaInfo" },
{ icon: FaItalic, name: "FaItalic" },
{ icon: FaJedi, name: "FaJedi" },
{ icon: FaJoint, name: "FaJoint" },
{ icon: FaJournalWhills, name: "FaJournalWhills" },
{ icon: FaKaaba, name: "FaKaaba" },
{ icon: FaKey, name: "FaKey" },
{ icon: FaKeyboard, name: "FaKeyboard" },
{ icon: FaKhanda, name: "FaKhanda" },
{ icon: FaKissBeam, name: "FaKissBeam" },
{ icon: FaKissWinkHeart, name: "FaKissWinkHeart" },
{ icon: FaKiss, name: "FaKiss" },
{ icon: FaKiwiBird, name: "FaKiwiBird" },
{ icon: FaLandmark, name: "FaLandmark" },
{ icon: FaLanguage, name: "FaLanguage" },
{ icon: FaLaptopCode, name: "FaLaptopCode" },
{ icon: FaLaptopHouse, name: "FaLaptopHouse" },
{ icon: FaLaptopMedical, name: "FaLaptopMedical" },
{ icon: FaLaptop, name: "FaLaptop" },
{ icon: FaLaughBeam, name: "FaLaughBeam" },
{ icon: FaLaughSquint, name: "FaLaughSquint" },
{ icon: FaLaughWink, name: "FaLaughWink" },
{ icon: FaLaugh, name: "FaLaugh" },
{ icon: FaLayerGroup, name: "FaLayerGroup" },
{ icon: FaLeaf, name: "FaLeaf" },
{ icon: FaLemon, name: "FaLemon" },
{ icon: FaLessThanEqual, name: "FaLessThanEqual" },
{ icon: FaLessThan, name: "FaLessThan" },
{ icon: FaLevelDownAlt, name: "FaLevelDownAlt" },
{ icon: FaLevelUpAlt, name: "FaLevelUpAlt" },
{ icon: FaLifeRing, name: "FaLifeRing" },
{ icon: FaLightbulb, name: "FaLightbulb" },
{ icon: FaLink, name: "FaLink" },
{ icon: FaLiraSign, name: "FaLiraSign" },
{ icon: FaListAlt, name: "FaListAlt" },
{ icon: FaListOl, name: "FaListOl" },
{ icon: FaListUl, name: "FaListUl" },
{ icon: FaList, name: "FaList" },
{ icon: FaLocationArrow, name: "FaLocationArrow" },
{ icon: FaLockOpen, name: "FaLockOpen" },
{ icon: FaLock, name: "FaLock" },
{ icon: FaLongArrowAltDown, name: "FaLongArrowAltDown" },
{ icon: FaLongArrowAltLeft, name: "FaLongArrowAltLeft" },
{ icon: FaLongArrowAltRight, name: "FaLongArrowAltRight" },
{ icon: FaLongArrowAltUp, name: "FaLongArrowAltUp" },
{ icon: FaLowVision, name: "FaLowVision" },
{ icon: FaLuggageCart, name: "FaLuggageCart" },
{ icon: FaLungsVirus, name: "FaLungsVirus" },
{ icon: FaLungs, name: "FaLungs" },
{ icon: FaMagic, name: "FaMagic" },
{ icon: FaMagnet, name: "FaMagnet" },
{ icon: FaMailBulk, name: "FaMailBulk" },
{ icon: FaMale, name: "FaMale" },
{ icon: FaMapMarkedAlt, name: "FaMapMarkedAlt" },
{ icon: FaMapMarked, name: "FaMapMarked" },
{ icon: FaMapMarkerAlt, name: "FaMapMarkerAlt" },
{ icon: FaMapMarker, name: "FaMapMarker" },
{ icon: FaMapPin, name: "FaMapPin" },
{ icon: FaMapSigns, name: "FaMapSigns" },
{ icon: FaMap, name: "FaMap" },
{ icon: FaMarker, name: "FaMarker" },
{ icon: FaMarsDouble, name: "FaMarsDouble" },
{ icon: FaMarsStrokeH, name: "FaMarsStrokeH" },
{ icon: FaMarsStrokeV, name: "FaMarsStrokeV" },
{ icon: FaMarsStroke, name: "FaMarsStroke" },
{ icon: FaMars, name: "FaMars" },
{ icon: FaMask, name: "FaMask" },
{ icon: FaMedal, name: "FaMedal" },
{ icon: FaMedkit, name: "FaMedkit" },
{ icon: FaMehBlank, name: "FaMehBlank" },
{ icon: FaMehRollingEyes, name: "FaMehRollingEyes" },
{ icon: FaMeh, name: "FaMeh" },
{ icon: FaMemory, name: "FaMemory" },
{ icon: FaMenorah, name: "FaMenorah" },
{ icon: FaMercury, name: "FaMercury" },
{ icon: FaMeteor, name: "FaMeteor" },
{ icon: FaMicrochip, name: "FaMicrochip" },
{ icon: FaMicrophoneAltSlash, name: "FaMicrophoneAltSlash" },
{ icon: FaMicrophoneAlt, name: "FaMicrophoneAlt" },
{ icon: FaMicrophoneSlash, name: "FaMicrophoneSlash" },
{ icon: FaMicrophone, name: "FaMicrophone" },
{ icon: FaMicroscope, name: "FaMicroscope" },
{ icon: FaMinusCircle, name: "FaMinusCircle" },
{ icon: FaMinusSquare, name: "FaMinusSquare" },
{ icon: FaMinus, name: "FaMinus" },
{ icon: FaMitten, name: "FaMitten" },
{ icon: FaMobileAlt, name: "FaMobileAlt" },
{ icon: FaMobile, name: "FaMobile" },
{ icon: FaMoneyBillAlt, name: "FaMoneyBillAlt" },
{ icon: FaMoneyBillWaveAlt, name: "FaMoneyBillWaveAlt" },
{ icon: FaMoneyBillWave, name: "FaMoneyBillWave" },
{ icon: FaMoneyBill, name: "FaMoneyBill" },
{ icon: FaMoneyCheckAlt, name: "FaMoneyCheckAlt" },
{ icon: FaMoneyCheck, name: "FaMoneyCheck" },
{ icon: FaMonument, name: "FaMonument" },
{ icon: FaMoon, name: "FaMoon" },
{ icon: FaMortarPestle, name: "FaMortarPestle" },
{ icon: FaMosque, name: "FaMosque" },
{ icon: FaMotorcycle, name: "FaMotorcycle" },
{ icon: FaMountain, name: "FaMountain" },
{ icon: FaMousePointer, name: "FaMousePointer" },
{ icon: FaMouse, name: "FaMouse" },
{ icon: FaMugHot, name: "FaMugHot" },
{ icon: FaMusic, name: "FaMusic" },
{ icon: FaNetworkWired, name: "FaNetworkWired" },
{ icon: FaNeuter, name: "FaNeuter" },
{ icon: FaNewspaper, name: "FaNewspaper" },
{ icon: FaNotEqual, name: "FaNotEqual" },
{ icon: FaNotesMedical, name: "FaNotesMedical" },
{ icon: FaObjectGroup, name: "FaObjectGroup" },
{ icon: FaObjectUngroup, name: "FaObjectUngroup" },
{ icon: FaOilCan, name: "FaOilCan" },
{ icon: FaOm, name: "FaOm" },
{ icon: FaOtter, name: "FaOtter" },
{ icon: FaOutdent, name: "FaOutdent" },
{ icon: FaPager, name: "FaPager" },
{ icon: FaPaintBrush, name: "FaPaintBrush" },
{ icon: FaPaintRoller, name: "FaPaintRoller" },
{ icon: FaPalette, name: "FaPalette" },
{ icon: FaPallet, name: "FaPallet" },
{ icon: FaPaperPlane, name: "FaPaperPlane" },
{ icon: FaPaperclip, name: "FaPaperclip" },
{ icon: FaParachuteBox, name: "FaParachuteBox" },
{ icon: FaParagraph, name: "FaParagraph" },
{ icon: FaParking, name: "FaParking" },
{ icon: FaPassport, name: "FaPassport" },
{ icon: FaPastafarianism, name: "FaPastafarianism" },
{ icon: FaPaste, name: "FaPaste" },
{ icon: FaPauseCircle, name: "FaPauseCircle" },
{ icon: FaPause, name: "FaPause" },
{ icon: FaPaw, name: "FaPaw" },
{ icon: FaPeace, name: "FaPeace" },
{ icon: FaPenAlt, name: "FaPenAlt" },
{ icon: FaPenFancy, name: "FaPenFancy" },
{ icon: FaPenNib, name: "FaPenNib" },
{ icon: FaPenSquare, name: "FaPenSquare" },
{ icon: FaPen, name: "FaPen" },
{ icon: FaPencilAlt, name: "FaPencilAlt" },
{ icon: FaPencilRuler, name: "FaPencilRuler" },
{ icon: FaPeopleArrows, name: "FaPeopleArrows" },
{ icon: FaPeopleCarry, name: "FaPeopleCarry" },
{ icon: FaPepperHot, name: "FaPepperHot" },
{ icon: FaPercent, name: "FaPercent" },
{ icon: FaPercentage, name: "FaPercentage" },
{ icon: FaPersonBooth, name: "FaPersonBooth" },
{ icon: FaPhoneAlt, name: "FaPhoneAlt" },
{ icon: FaPhoneSlash, name: "FaPhoneSlash" },
{ icon: FaPhoneSquareAlt, name: "FaPhoneSquareAlt" },
{ icon: FaPhoneSquare, name: "FaPhoneSquare" },
{ icon: FaPhoneVolume, name: "FaPhoneVolume" },
{ icon: FaPhone, name: "FaPhone" },
{ icon: FaPhotoVideo, name: "FaPhotoVideo" },
{ icon: FaPiggyBank, name: "FaPiggyBank" },
{ icon: FaPills, name: "FaPills" },
{ icon: FaPizzaSlice, name: "FaPizzaSlice" },
{ icon: FaPlaceOfWorship, name: "FaPlaceOfWorship" },
{ icon: FaPlaneArrival, name: "FaPlaneArrival" },
{ icon: FaPlaneDeparture, name: "FaPlaneDeparture" },
{ icon: FaPlaneSlash, name: "FaPlaneSlash" },
{ icon: FaPlane, name: "FaPlane" },
{ icon: FaPlayCircle, name: "FaPlayCircle" },
{ icon: FaPlay, name: "FaPlay" },
{ icon: FaPlug, name: "FaPlug" },
{ icon: FaPlusCircle, name: "FaPlusCircle" },
{ icon: FaPlusSquare, name: "FaPlusSquare" },
{ icon: FaPlus, name: "FaPlus" },
{ icon: FaPodcast, name: "FaPodcast" },
{ icon: FaPollH, name: "FaPollH" },
{ icon: FaPoll, name: "FaPoll" },
{ icon: FaPooStorm, name: "FaPooStorm" },
{ icon: FaPoo, name: "FaPoo" },
{ icon: FaPoop, name: "FaPoop" },
{ icon: FaPortrait, name: "FaPortrait" },
{ icon: FaPoundSign, name: "FaPoundSign" },
{ icon: FaPowerOff, name: "FaPowerOff" },
{ icon: FaPray, name: "FaPray" },
{ icon: FaPrayingHands, name: "FaPrayingHands" },
{ icon: FaPrescriptionBottleAlt, name: "FaPrescriptionBottleAlt" },
{ icon: FaPrescriptionBottle, name: "FaPrescriptionBottle" },
{ icon: FaPrescription, name: "FaPrescription" },
{ icon: FaPrint, name: "FaPrint" },
{ icon: FaProcedures, name: "FaProcedures" },
{ icon: FaProjectDiagram, name: "FaProjectDiagram" },
{ icon: FaPumpMedical, name: "FaPumpMedical" },
{ icon: FaPumpSoap, name: "FaPumpSoap" },
{ icon: FaPuzzlePiece, name: "FaPuzzlePiece" },
{ icon: FaQrcode, name: "FaQrcode" },
{ icon: FaQuestionCircle, name: "FaQuestionCircle" },
{ icon: FaQuestion, name: "FaQuestion" },
{ icon: FaQuidditch, name: "FaQuidditch" },
{ icon: FaQuoteLeft, name: "FaQuoteLeft" },
{ icon: FaQuoteRight, name: "FaQuoteRight" },
{ icon: FaQuran, name: "FaQuran" },
{ icon: FaRadiationAlt, name: "FaRadiationAlt" },
{ icon: FaRadiation, name: "FaRadiation" },
{ icon: FaRainbow, name: "FaRainbow" },
{ icon: FaRandom, name: "FaRandom" },
{ icon: FaReceipt, name: "FaReceipt" },
{ icon: FaRecordVinyl, name: "FaRecordVinyl" },
{ icon: FaRecycle, name: "FaRecycle" },
{ icon: FaRedoAlt, name: "FaRedoAlt" },
{ icon: FaRedo, name: "FaRedo" },
{ icon: FaRegistered, name: "FaRegistered" },
{ icon: FaRemoveFormat, name: "FaRemoveFormat" },
{ icon: FaReplyAll, name: "FaReplyAll" },
{ icon: FaReply, name: "FaReply" },
{ icon: FaRepublican, name: "FaRepublican" },
{ icon: FaRestroom, name: "FaRestroom" },
{ icon: FaRetweet, name: "FaRetweet" },
{ icon: FaRibbon, name: "FaRibbon" },
{ icon: FaRing, name: "FaRing" },
{ icon: FaRoad, name: "FaRoad" },
{ icon: FaRobot, name: "FaRobot" },
{ icon: FaRocket, name: "FaRocket" },
{ icon: FaRoute, name: "FaRoute" },
{ icon: FaRssSquare, name: "FaRssSquare" },
{ icon: FaRss, name: "FaRss" },
{ icon: FaRubleSign, name: "FaRubleSign" },
{ icon: FaRulerCombined, name: "FaRulerCombined" },
{ icon: FaRulerHorizontal, name: "FaRulerHorizontal" },
{ icon: FaRulerVertical, name: "FaRulerVertical" },
{ icon: FaRuler, name: "FaRuler" },
{ icon: FaRunning, name: "FaRunning" },
{ icon: FaRupeeSign, name: "FaRupeeSign" },
{ icon: FaSadCry, name: "FaSadCry" },
{ icon: FaSadTear, name: "FaSadTear" },
{ icon: FaSatelliteDish, name: "FaSatelliteDish" },
{ icon: FaSatellite, name: "FaSatellite" },
{ icon: FaSave, name: "FaSave" },
{ icon: FaSchool, name: "FaSchool" },
{ icon: FaScrewdriver, name: "FaScrewdriver" },
{ icon: FaScroll, name: "FaScroll" },
{ icon: FaSdCard, name: "FaSdCard" },
{ icon: FaSearchDollar, name: "FaSearchDollar" },
{ icon: FaSearchLocation, name: "FaSearchLocation" },
{ icon: FaSearchMinus, name: "FaSearchMinus" },
{ icon: FaSearchPlus, name: "FaSearchPlus" },
{ icon: FaSearch, name: "FaSearch" },
{ icon: FaSeedling, name: "FaSeedling" },
{ icon: FaServer, name: "FaServer" },
{ icon: FaShapes, name: "FaShapes" },
{ icon: FaShareAltSquare, name: "FaShareAltSquare" },
{ icon: FaShareAlt, name: "FaShareAlt" },
{ icon: FaShareSquare, name: "FaShareSquare" },
{ icon: FaShare, name: "FaShare" },
{ icon: FaShekelSign, name: "FaShekelSign" },
{ icon: FaShieldAlt, name: "FaShieldAlt" },
{ icon: FaShieldVirus, name: "FaShieldVirus" },
{ icon: FaShip, name: "FaShip" },
{ icon: FaShippingFast, name: "FaShippingFast" },
{ icon: FaShoePrints, name: "FaShoePrints" },
{ icon: FaShoppingBag, name: "FaShoppingBag" },
{ icon: FaShoppingBasket, name: "FaShoppingBasket" },
{ icon: FaShoppingCart, name: "FaShoppingCart" },
{ icon: FaShower, name: "FaShower" },
{ icon: FaShuttleVan, name: "FaShuttleVan" },
{ icon: FaSignInAlt, name: "FaSignInAlt" },
{ icon: FaSignLanguage, name: "FaSignLanguage" },
{ icon: FaSignOutAlt, name: "FaSignOutAlt" },
{ icon: FaSign, name: "FaSign" },
{ icon: FaSignal, name: "FaSignal" },
{ icon: FaSignature, name: "FaSignature" },
{ icon: FaSimCard, name: "FaSimCard" },
{ icon: FaSink, name: "FaSink" },
{ icon: FaSitemap, name: "FaSitemap" },
{ icon: FaSkating, name: "FaSkating" },
{ icon: FaSkiingNordic, name: "FaSkiingNordic" },
{ icon: FaSkiing, name: "FaSkiing" },
{ icon: FaSkullCrossbones, name: "FaSkullCrossbones" },
{ icon: FaSkull, name: "FaSkull" },
{ icon: FaSlash, name: "FaSlash" },
{ icon: FaSleigh, name: "FaSleigh" },
{ icon: FaSlidersH, name: "FaSlidersH" },
{ icon: FaSmileBeam, name: "FaSmileBeam" },
{ icon: FaSmileWink, name: "FaSmileWink" },
{ icon: FaSmile, name: "FaSmile" },
{ icon: FaSmog, name: "FaSmog" },
{ icon: FaSmokingBan, name: "FaSmokingBan" },
{ icon: FaSmoking, name: "FaSmoking" },
{ icon: FaSms, name: "FaSms" },
{ icon: FaSnowboarding, name: "FaSnowboarding" },
{ icon: FaSnowflake, name: "FaSnowflake" },
{ icon: FaSnowman, name: "FaSnowman" },
{ icon: FaSnowplow, name: "FaSnowplow" },
{ icon: FaSoap, name: "FaSoap" },
{ icon: FaSocks, name: "FaSocks" },
{ icon: FaSolarPanel, name: "FaSolarPanel" },
{ icon: FaSortAlphaDownAlt, name: "FaSortAlphaDownAlt" },
{ icon: FaSortAlphaDown, name: "FaSortAlphaDown" },
{ icon: FaSortAlphaUpAlt, name: "FaSortAlphaUpAlt" },
{ icon: FaSortAlphaUp, name: "FaSortAlphaUp" },
{ icon: FaSortAmountDownAlt, name: "FaSortAmountDownAlt" },
{ icon: FaSortAmountDown, name: "FaSortAmountDown" },
{ icon: FaSortAmountUpAlt, name: "FaSortAmountUpAlt" },
{ icon: FaSortAmountUp, name: "FaSortAmountUp" },
{ icon: FaSortDown, name: "FaSortDown" },
{ icon: FaSortNumericDownAlt, name: "FaSortNumericDownAlt" },
{ icon: FaSortNumericDown, name: "FaSortNumericDown" },
{ icon: FaSortNumericUpAlt, name: "FaSortNumericUpAlt" },
{ icon: FaSortNumericUp, name: "FaSortNumericUp" },
{ icon: FaSortUp, name: "FaSortUp" },
{ icon: FaSort, name: "FaSort" },
{ icon: FaSpa, name: "FaSpa" },
{ icon: FaSpaceShuttle, name: "FaSpaceShuttle" },
{ icon: FaSpellCheck, name: "FaSpellCheck" },
{ icon: FaSpider, name: "FaSpider" },
{ icon: FaSpinner, name: "FaSpinner" },
{ icon: FaSplotch, name: "FaSplotch" },
{ icon: FaSprayCan, name: "FaSprayCan" },
{ icon: FaSquareFull, name: "FaSquareFull" },
{ icon: FaSquareRootAlt, name: "FaSquareRootAlt" },
{ icon: FaSquare, name: "FaSquare" },
{ icon: FaStamp, name: "FaStamp" },
{ icon: FaStarAndCrescent, name: "FaStarAndCrescent" },
{ icon: FaStarHalfAlt, name: "FaStarHalfAlt" },
{ icon: FaStarHalf, name: "FaStarHalf" },
{ icon: FaStarOfDavid, name: "FaStarOfDavid" },
{ icon: FaStarOfLife, name: "FaStarOfLife" },
{ icon: FaStar, name: "FaStar" },
{ icon: FaStepBackward, name: "FaStepBackward" },
{ icon: FaStepForward, name: "FaStepForward" },
{ icon: FaStethoscope, name: "FaStethoscope" },
{ icon: FaStickyNote, name: "FaStickyNote" },
{ icon: FaStopCircle, name: "FaStopCircle" },
{ icon: FaStop, name: "FaStop" },
{ icon: FaStopwatch20, name: "FaStopwatch20" },
{ icon: FaStopwatch, name: "FaStopwatch" },
{ icon: FaStoreAltSlash, name: "FaStoreAltSlash" },
{ icon: FaStoreAlt, name: "FaStoreAlt" },
{ icon: FaStoreSlash, name: "FaStoreSlash" },
{ icon: FaStore, name: "FaStore" },
{ icon: FaStream, name: "FaStream" },
{ icon: FaStreetView, name: "FaStreetView" },
{ icon: FaStrikethrough, name: "FaStrikethrough" },
{ icon: FaStroopwafel, name: "FaStroopwafel" },
{ icon: FaSubscript, name: "FaSubscript" },
{ icon: FaSubway, name: "FaSubway" },
{ icon: FaSuitcaseRolling, name: "FaSuitcaseRolling" },
{ icon: FaSuitcase, name: "FaSuitcase" },
{ icon: FaSun, name: "FaSun" },
{ icon: FaSuperscript, name: "FaSuperscript" },
{ icon: FaSurprise, name: "FaSurprise" },
{ icon: FaSwatchbook, name: "FaSwatchbook" },
{ icon: FaSwimmer, name: "FaSwimmer" },
{ icon: FaSwimmingPool, name: "FaSwimmingPool" },
{ icon: FaSynagogue, name: "FaSynagogue" },
{ icon: FaSyncAlt, name: "FaSyncAlt" },
{ icon: FaSync, name: "FaSync" },
{ icon: FaSyringe, name: "FaSyringe" },
{ icon: FaTableTennis, name: "FaTableTennis" },
{ icon: FaTable, name: "FaTable" },
{ icon: FaTabletAlt, name: "FaTabletAlt" },
{ icon: FaTablet, name: "FaTablet" },
{ icon: FaTablets, name: "FaTablets" },
{ icon: FaTachometerAlt, name: "FaTachometerAlt" },
{ icon: FaTag, name: "FaTag" },
{ icon: FaTags, name: "FaTags" },
{ icon: FaTape, name: "FaTape" },
{ icon: FaTasks, name: "FaTasks" },
{ icon: FaTaxi, name: "FaTaxi" },
{ icon: FaTeethOpen, name: "FaTeethOpen" },
{ icon: FaTeeth, name: "FaTeeth" },
{ icon: FaTemperatureHigh, name: "FaTemperatureHigh" },
{ icon: FaTemperatureLow, name: "FaTemperatureLow" },
{ icon: FaTenge, name: "FaTenge" },
{ icon: FaTerminal, name: "FaTerminal" },
{ icon: FaTextHeight, name: "FaTextHeight" },
{ icon: FaTextWidth, name: "FaTextWidth" },
{ icon: FaThLarge, name: "FaThLarge" },
{ icon: FaThList, name: "FaThList" },
{ icon: FaTh, name: "FaTh" },
{ icon: FaTheaterMasks, name: "FaTheaterMasks" },
{ icon: FaThermometerEmpty, name: "FaThermometerEmpty" },
{ icon: FaThermometerFull, name: "FaThermometerFull" },
{ icon: FaThermometerHalf, name: "FaThermometerHalf" },
{ icon: FaThermometerQuarter, name: "FaThermometerQuarter" },
{ icon: FaThermometerThreeQuarters, name: "FaThermometerThreeQuarters" },
{ icon: FaThermometer, name: "FaThermometer" },
{ icon: FaThumbsDown, name: "FaThumbsDown" },
{ icon: FaThumbsUp, name: "FaThumbsUp" },
{ icon: FaThumbtack, name: "FaThumbtack" },
{ icon: FaTicketAlt, name: "FaTicketAlt" },
{ icon: FaTimesCircle, name: "FaTimesCircle" },
{ icon: FaTimes, name: "FaTimes" },
{ icon: FaTintSlash, name: "FaTintSlash" },
{ icon: FaTint, name: "FaTint" },
{ icon: FaTired, name: "FaTired" },
{ icon: FaToggleOff, name: "FaToggleOff" },
{ icon: FaToggleOn, name: "FaToggleOn" },
{ icon: FaToiletPaperSlash, name: "FaToiletPaperSlash" },
{ icon: FaToiletPaper, name: "FaToiletPaper" },
{ icon: FaToilet, name: "FaToilet" },
{ icon: FaToolbox, name: "FaToolbox" },
{ icon: FaTools, name: "FaTools" },
{ icon: FaTooth, name: "FaTooth" },
{ icon: FaTorah, name: "FaTorah" },
{ icon: FaToriiGate, name: "FaToriiGate" },
{ icon: FaTractor, name: "FaTractor" },
{ icon: FaTrademark, name: "FaTrademark" },
{ icon: FaTrafficLight, name: "FaTrafficLight" },
{ icon: FaTrailer, name: "FaTrailer" },
{ icon: FaTrain, name: "FaTrain" },
{ icon: FaTram, name: "FaTram" },
{ icon: FaTransgenderAlt, name: "FaTransgenderAlt" },
{ icon: FaTransgender, name: "FaTransgender" },
{ icon: FaTrashAlt, name: "FaTrashAlt" },
{ icon: FaTrashRestoreAlt, name: "FaTrashRestoreAlt" },
{ icon: FaTrashRestore, name: "FaTrashRestore" },
{ icon: FaTrash, name: "FaTrash" },
{ icon: FaTree, name: "FaTree" },
{ icon: FaTrophy, name: "FaTrophy" },
{ icon: FaTruckLoading, name: "FaTruckLoading" },
{ icon: FaTruckMonster, name: "FaTruckMonster" },
{ icon: FaTruckMoving, name: "FaTruckMoving" },
{ icon: FaTruckPickup, name: "FaTruckPickup" },
{ icon: FaTruck, name: "FaTruck" },
{ icon: FaTshirt, name: "FaTshirt" },
{ icon: FaTty, name: "FaTty" },
{ icon: FaTv, name: "FaTv" },
{ icon: FaUmbrellaBeach, name: "FaUmbrellaBeach" },
{ icon: FaUmbrella, name: "FaUmbrella" },
{ icon: FaUnderline, name: "FaUnderline" },
{ icon: FaUndoAlt, name: "FaUndoAlt" },
{ icon: FaUndo, name: "FaUndo" },
{ icon: FaUniversalAccess, name: "FaUniversalAccess" },
{ icon: FaUniversity, name: "FaUniversity" },
{ icon: FaUnlink, name: "FaUnlink" },
{ icon: FaUnlockAlt, name: "FaUnlockAlt" },
{ icon: FaUnlock, name: "FaUnlock" },
{ icon: FaUpload, name: "FaUpload" },
{ icon: FaUserAltSlash, name: "FaUserAltSlash" },
{ icon: FaUserAlt, name: "FaUserAlt" },
{ icon: FaUserAstronaut, name: "FaUserAstronaut" },
{ icon: FaUserCheck, name: "FaUserCheck" },
{ icon: FaUserCircle, name: "FaUserCircle" },
{ icon: FaUserClock, name: "FaUserClock" },
{ icon: FaUserCog, name: "FaUserCog" },
{ icon: FaUserEdit, name: "FaUserEdit" },
{ icon: FaUserFriends, name: "FaUserFriends" },
{ icon: FaUserGraduate, name: "FaUserGraduate" },
{ icon: FaUserInjured, name: "FaUserInjured" },
{ icon: FaUserLock, name: "FaUserLock" },
{ icon: FaUserMd, name: "FaUserMd" },
{ icon: FaUserMinus, name: "FaUserMinus" },
{ icon: FaUserNinja, name: "FaUserNinja" },
{ icon: FaUserNurse, name: "FaUserNurse" },
{ icon: FaUserPlus, name: "FaUserPlus" },
{ icon: FaUserSecret, name: "FaUserSecret" },
{ icon: FaUserShield, name: "FaUserShield" },
{ icon: FaUserSlash, name: "FaUserSlash" },
{ icon: FaUserTag, name: "FaUserTag" },
{ icon: FaUserTie, name: "FaUserTie" },
{ icon: FaUserTimes, name: "FaUserTimes" },
{ icon: FaUser, name: "FaUser" },
{ icon: FaUsersCog, name: "FaUsersCog" },
{ icon: FaUsersSlash, name: "FaUsersSlash" },
{ icon: FaUsers, name: "FaUsers" },
{ icon: FaUtensilSpoon, name: "FaUtensilSpoon" },
{ icon: FaUtensils, name: "FaUtensils" },
{ icon: FaVectorSquare, name: "FaVectorSquare" },
{ icon: FaVenusDouble, name: "FaVenusDouble" },
{ icon: FaVenusMars, name: "FaVenusMars" },
{ icon: FaVenus, name: "FaVenus" },
{ icon: FaVestPatches, name: "FaVestPatches" },
{ icon: FaVest, name: "FaVest" },
{ icon: FaVial, name: "FaVial" },
{ icon: FaVials, name: "FaVials" },
{ icon: FaVideoSlash, name: "FaVideoSlash" },
{ icon: FaVideo, name: "FaVideo" },
{ icon: FaVihara, name: "FaVihara" },
{ icon: FaVirusSlash, name: "FaVirusSlash" },
{ icon: FaVirus, name: "FaVirus" },
{ icon: FaViruses, name: "FaViruses" },
{ icon: FaVoicemail, name: "FaVoicemail" },
{ icon: FaVolleyballBall, name: "FaVolleyballBall" },
{ icon: FaVolumeDown, name: "FaVolumeDown" },
{ icon: FaVolumeMute, name: "FaVolumeMute" },
{ icon: FaVolumeOff, name: "FaVolumeOff" },
{ icon: FaVolumeUp, name: "FaVolumeUp" },
{ icon: FaVoteYea, name: "FaVoteYea" },
{ icon: FaVrCardboard, name: "FaVrCardboard" },
{ icon: FaWalking, name: "FaWalking" },
{ icon: FaWallet, name: "FaWallet" },
{ icon: FaWarehouse, name: "FaWarehouse" },
{ icon: FaWater, name: "FaWater" },
{ icon: FaWaveSquare, name: "FaWaveSquare" },
{ icon: FaWeightHanging, name: "FaWeightHanging" },
{ icon: FaWeight, name: "FaWeight" },
{ icon: FaWheelchair, name: "FaWheelchair" },
{ icon: FaWifi, name: "FaWifi" },
{ icon: FaWind, name: "FaWind" },
{ icon: FaWindowClose, name: "FaWindowClose" },
{ icon: FaWindowMaximize, name: "FaWindowMaximize" },
{ icon: FaWindowMinimize, name: "FaWindowMinimize" },
{ icon: FaWindowRestore, name: "FaWindowRestore" },
{ icon: FaWineBottle, name: "FaWineBottle" },
{ icon: FaWineGlassAlt, name: "FaWineGlassAlt" },
{ icon: FaWineGlass, name: "FaWineGlass" },
{ icon: FaWonSign, name: "FaWonSign" },
{ icon: FaWrench, name: "FaWrench" },
{ icon: FaXRay, name: "FaXRay" },
{ icon: FaYenSign, name: "FaYenSign" },
{ icon: FaYinYang, name: "FaYinYang" },
{ icon: FaRegAddressBook, name: "FaRegAddressBook" },
{ icon: FaRegAddressCard, name: "FaRegAddressCard" },
{ icon: FaRegAngry, name: "FaRegAngry" },
{ icon: FaRegArrowAltCircleDown, name: "FaRegArrowAltCircleDown" },
{ icon: FaRegArrowAltCircleLeft, name: "FaRegArrowAltCircleLeft" },
{ icon: FaRegArrowAltCircleRight, name: "FaRegArrowAltCircleRight" },
{ icon: FaRegArrowAltCircleUp, name: "FaRegArrowAltCircleUp" },
{ icon: FaRegBellSlash, name: "FaRegBellSlash" },
{ icon: FaRegBell, name: "FaRegBell" },
{ icon: FaRegBookmark, name: "FaRegBookmark" },
{ icon: FaRegBuilding, name: "FaRegBuilding" },
{ icon: FaRegCalendarAlt, name: "FaRegCalendarAlt" },
{ icon: FaRegCalendarCheck, name: "FaRegCalendarCheck" },
{ icon: FaRegCalendarMinus, name: "FaRegCalendarMinus" },
{ icon: FaRegCalendarPlus, name: "FaRegCalendarPlus" },
{ icon: FaRegCalendarTimes, name: "FaRegCalendarTimes" },
{ icon: FaRegCalendar, name: "FaRegCalendar" },
{ icon: FaRegCaretSquareDown, name: "FaRegCaretSquareDown" },
{ icon: FaRegCaretSquareLeft, name: "FaRegCaretSquareLeft" },
{ icon: FaRegCaretSquareRight, name: "FaRegCaretSquareRight" },
{ icon: FaRegCaretSquareUp, name: "FaRegCaretSquareUp" },
{ icon: FaRegChartBar, name: "FaRegChartBar" },
{ icon: FaRegCheckCircle, name: "FaRegCheckCircle" },
{ icon: FaRegCheckSquare, name: "FaRegCheckSquare" },
{ icon: FaRegCircle, name: "FaRegCircle" },
{ icon: FaRegClipboard, name: "FaRegClipboard" },
{ icon: FaRegClock, name: "FaRegClock" },
{ icon: FaRegClone, name: "FaRegClone" },
{ icon: FaRegClosedCaptioning, name: "FaRegClosedCaptioning" },
{ icon: FaRegCommentAlt, name: "FaRegCommentAlt" },
{ icon: FaRegCommentDots, name: "FaRegCommentDots" },
{ icon: FaRegComment, name: "FaRegComment" },
{ icon: FaRegComments, name: "FaRegComments" },
{ icon: FaRegCompass, name: "FaRegCompass" },
{ icon: FaRegCopy, name: "FaRegCopy" },
{ icon: FaRegCopyright, name: "FaRegCopyright" },
{ icon: FaRegCreditCard, name: "FaRegCreditCard" },
{ icon: FaRegDizzy, name: "FaRegDizzy" },
{ icon: FaRegDotCircle, name: "FaRegDotCircle" },
{ icon: FaRegEdit, name: "FaRegEdit" },
{ icon: FaRegEnvelopeOpen, name: "FaRegEnvelopeOpen" },
{ icon: FaRegEnvelope, name: "FaRegEnvelope" },
{ icon: FaRegEyeSlash, name: "FaRegEyeSlash" },
{ icon: FaRegEye, name: "FaRegEye" },
{ icon: FaRegFileAlt, name: "FaRegFileAlt" },
{ icon: FaRegFileArchive, name: "FaRegFileArchive" },
{ icon: FaRegFileAudio, name: "FaRegFileAudio" },
{ icon: FaRegFileCode, name: "FaRegFileCode" },
{ icon: FaRegFileExcel, name: "FaRegFileExcel" },
{ icon: FaRegFileImage, name: "FaRegFileImage" },
{ icon: FaRegFilePdf, name: "FaRegFilePdf" },
{ icon: FaRegFilePowerpoint, name: "FaRegFilePowerpoint" },
{ icon: FaRegFileVideo, name: "FaRegFileVideo" },
{ icon: FaRegFileWord, name: "FaRegFileWord" },
{ icon: FaRegFile, name: "FaRegFile" },
{ icon: FaRegFlag, name: "FaRegFlag" },
{ icon: FaRegFlushed, name: "FaRegFlushed" },
{ icon: FaRegFolderOpen, name: "FaRegFolderOpen" },
{ icon: FaRegFolder, name: "FaRegFolder" },
{ icon: FaRegFontAwesomeLogoFull, name: "FaRegFontAwesomeLogoFull" },
{ icon: FaRegFrownOpen, name: "FaRegFrownOpen" },
{ icon: FaRegFrown, name: "FaRegFrown" },
{ icon: FaRegFutbol, name: "FaRegFutbol" },
{ icon: FaRegGem, name: "FaRegGem" },
{ icon: FaRegGrimace, name: "FaRegGrimace" },
{ icon: FaRegGrinAlt, name: "FaRegGrinAlt" },
{ icon: FaRegGrinBeamSweat, name: "FaRegGrinBeamSweat" },
{ icon: FaRegGrinBeam, name: "FaRegGrinBeam" },
{ icon: FaRegGrinHearts, name: "FaRegGrinHearts" },
{ icon: FaRegGrinSquintTears, name: "FaRegGrinSquintTears" },
{ icon: FaRegGrinSquint, name: "FaRegGrinSquint" },
{ icon: FaRegGrinStars, name: "FaRegGrinStars" },
{ icon: FaRegGrinTears, name: "FaRegGrinTears" },
{ icon: FaRegGrinTongueSquint, name: "FaRegGrinTongueSquint" },
{ icon: FaRegGrinTongueWink, name: "FaRegGrinTongueWink" },
{ icon: FaRegGrinTongue, name: "FaRegGrinTongue" },
{ icon: FaRegGrinWink, name: "FaRegGrinWink" },
{ icon: FaRegGrin, name: "FaRegGrin" },
{ icon: FaRegHandLizard, name: "FaRegHandLizard" },
{ icon: FaRegHandPaper, name: "FaRegHandPaper" },
{ icon: FaRegHandPeace, name: "FaRegHandPeace" },
{ icon: FaRegHandPointDown, name: "FaRegHandPointDown" },
{ icon: FaRegHandPointLeft, name: "FaRegHandPointLeft" },
{ icon: FaRegHandPointRight, name: "FaRegHandPointRight" },
{ icon: FaRegHandPointUp, name: "FaRegHandPointUp" },
{ icon: FaRegHandPointer, name: "FaRegHandPointer" },
{ icon: FaRegHandRock, name: "FaRegHandRock" },
{ icon: FaRegHandScissors, name: "FaRegHandScissors" },
{ icon: FaRegHandSpock, name: "FaRegHandSpock" },
{ icon: FaRegHandshake, name: "FaRegHandshake" },
{ icon: FaRegHdd, name: "FaRegHdd" },
{ icon: FaRegHeart, name: "FaRegHeart" },
{ icon: FaRegHospital, name: "FaRegHospital" },
{ icon: FaRegHourglass, name: "FaRegHourglass" },
{ icon: FaRegIdBadge, name: "FaRegIdBadge" },
{ icon: FaRegIdCard, name: "FaRegIdCard" },
{ icon: FaRegImage, name: "FaRegImage" },
{ icon: FaRegImages, name: "FaRegImages" },
{ icon: FaRegKeyboard, name: "FaRegKeyboard" },
{ icon: FaRegKissBeam, name: "FaRegKissBeam" },
{ icon: FaRegKissWinkHeart, name: "FaRegKissWinkHeart" },
{ icon: FaRegKiss, name: "FaRegKiss" },
{ icon: FaRegLaughBeam, name: "FaRegLaughBeam" },
{ icon: FaRegLaughSquint, name: "FaRegLaughSquint" },
{ icon: FaRegLaughWink, name: "FaRegLaughWink" },
{ icon: FaRegLaugh, name: "FaRegLaugh" },
{ icon: FaRegLemon, name: "FaRegLemon" },
{ icon: FaRegLifeRing, name: "FaRegLifeRing" },
{ icon: FaRegLightbulb, name: "FaRegLightbulb" },
{ icon: FaRegListAlt, name: "FaRegListAlt" },
{ icon: FaRegMap, name: "FaRegMap" },
{ icon: FaRegMehBlank, name: "FaRegMehBlank" },
{ icon: FaRegMehRollingEyes, name: "FaRegMehRollingEyes" },
{ icon: FaRegMeh, name: "FaRegMeh" },
{ icon: FaRegMinusSquare, name: "FaRegMinusSquare" },
{ icon: FaRegMoneyBillAlt, name: "FaRegMoneyBillAlt" },
{ icon: FaRegMoon, name: "FaRegMoon" },
{ icon: FaRegNewspaper, name: "FaRegNewspaper" },
{ icon: FaRegObjectGroup, name: "FaRegObjectGroup" },
{ icon: FaRegObjectUngroup, name: "FaRegObjectUngroup" },
{ icon: FaRegPaperPlane, name: "FaRegPaperPlane" },
{ icon: FaRegPauseCircle, name: "FaRegPauseCircle" },
{ icon: FaRegPlayCircle, name: "FaRegPlayCircle" },
{ icon: FaRegPlusSquare, name: "FaRegPlusSquare" },
{ icon: FaRegQuestionCircle, name: "FaRegQuestionCircle" },
{ icon: FaRegRegistered, name: "FaRegRegistered" },
{ icon: FaRegSadCry, name: "FaRegSadCry" },
{ icon: FaRegSadTear, name: "FaRegSadTear" },
{ icon: FaRegSave, name: "FaRegSave" },
{ icon: FaRegShareSquare, name: "FaRegShareSquare" },
{ icon: FaRegSmileBeam, name: "FaRegSmileBeam" },
{ icon: FaRegSmileWink, name: "FaRegSmileWink" },
{ icon: FaRegSmile, name: "FaRegSmile" },
{ icon: FaRegSnowflake, name: "FaRegSnowflake" },
{ icon: FaRegSquare, name: "FaRegSquare" },
{ icon: FaRegStarHalf, name: "FaRegStarHalf" },
{ icon: FaRegStar, name: "FaRegStar" },
{ icon: FaRegStickyNote, name: "FaRegStickyNote" },
{ icon: FaRegStopCircle, name: "FaRegStopCircle" },
{ icon: FaRegSun, name: "FaRegSun" },
{ icon: FaRegSurprise, name: "FaRegSurprise" },
{ icon: FaRegThumbsDown, name: "FaRegThumbsDown" },
{ icon: FaRegThumbsUp, name: "FaRegThumbsUp" },
{ icon: FaRegTimesCircle, name: "FaRegTimesCircle" },
{ icon: FaRegTired, name: "FaRegTired" },
{ icon: FaRegTrashAlt, name: "FaRegTrashAlt" },
{ icon: FaRegUserCircle, name: "FaRegUserCircle" },
{ icon: FaRegUser, name: "FaRegUser" },
{ icon: FaRegWindowClose, name: "FaRegWindowClose" },
{ icon: FaRegWindowMaximize, name: "FaRegWindowMaximize" },
{ icon: FaRegWindowMinimize, name: "FaRegWindowMinimize" },
{ icon: FaRegWindowRestore, name: "FaRegWindowRestore" },
];

export default result