import {
IoAccessibilityOutline,
IoAccessibilitySharp,
IoAccessibility,
IoAddCircleOutline,
IoAddCircleSharp,
IoAddCircle,
IoAddOutline,
IoAddSharp,
IoAdd,
IoAirplaneOutline,
IoAirplaneSharp,
IoAirplane,
IoAlarmOutline,
IoAlarmSharp,
IoAlarm,
IoAlbumsOutline,
IoAlbumsSharp,
IoAlbums,
IoAlertCircleOutline,
IoAlertCircleSharp,
IoAlertCircle,
IoAlertOutline,
IoAlertSharp,
IoAlert,
IoAmericanFootballOutline,
IoAmericanFootballSharp,
IoAmericanFootball,
IoAnalyticsOutline,
IoAnalyticsSharp,
IoAnalytics,
IoApertureOutline,
IoApertureSharp,
IoAperture,
IoAppsOutline,
IoAppsSharp,
IoApps,
IoArchiveOutline,
IoArchiveSharp,
IoArchive,
IoArrowBackCircleOutline,
IoArrowBackCircleSharp,
IoArrowBackCircle,
IoArrowBackOutline,
IoArrowBackSharp,
IoArrowBack,
IoArrowDownCircleOutline,
IoArrowDownCircleSharp,
IoArrowDownCircle,
IoArrowDownOutline,
IoArrowDownSharp,
IoArrowDown,
IoArrowForwardCircleOutline,
IoArrowForwardCircleSharp,
IoArrowForwardCircle,
IoArrowForwardOutline,
IoArrowForwardSharp,
IoArrowForward,
IoArrowRedoCircleOutline,
IoArrowRedoCircleSharp,
IoArrowRedoCircle,
IoArrowRedoOutline,
IoArrowRedoSharp,
IoArrowRedo,
IoArrowUndoCircleOutline,
IoArrowUndoCircleSharp,
IoArrowUndoCircle,
IoArrowUndoOutline,
IoArrowUndoSharp,
IoArrowUndo,
IoArrowUpCircleOutline,
IoArrowUpCircleSharp,
IoArrowUpCircle,
IoArrowUpOutline,
IoArrowUpSharp,
IoArrowUp,
IoAtCircleOutline,
IoAtCircleSharp,
IoAtCircle,
IoAtOutline,
IoAtSharp,
IoAt,
IoAttachOutline,
IoAttachSharp,
IoAttach,
IoBackspaceOutline,
IoBackspaceSharp,
IoBackspace,
IoBagAddOutline,
IoBagAddSharp,
IoBagAdd,
IoBagCheckOutline,
IoBagCheckSharp,
IoBagCheck,
IoBagHandleOutline,
IoBagHandleSharp,
IoBagHandle,
IoBagOutline,
IoBagRemoveOutline,
IoBagRemoveSharp,
IoBagRemove,
IoBagSharp,
IoBag,
IoBalloonOutline,
IoBalloonSharp,
IoBalloon,
IoBanOutline,
IoBanSharp,
IoBan,
IoBandageOutline,
IoBandageSharp,
IoBandage,
IoBarChartOutline,
IoBarChartSharp,
IoBarChart,
IoBarbellOutline,
IoBarbellSharp,
IoBarbell,
IoBarcodeOutline,
IoBarcodeSharp,
IoBarcode,
IoBaseballOutline,
IoBaseballSharp,
IoBaseball,
IoBasketOutline,
IoBasketSharp,
IoBasket,
IoBasketballOutline,
IoBasketballSharp,
IoBasketball,
IoBatteryChargingOutline,
IoBatteryChargingSharp,
IoBatteryCharging,
IoBatteryDeadOutline,
IoBatteryDeadSharp,
IoBatteryDead,
IoBatteryFullOutline,
IoBatteryFullSharp,
IoBatteryFull,
IoBatteryHalfOutline,
IoBatteryHalfSharp,
IoBatteryHalf,
IoBeakerOutline,
IoBeakerSharp,
IoBeaker,
IoBedOutline,
IoBedSharp,
IoBed,
IoBeerOutline,
IoBeerSharp,
IoBeer,
IoBicycleOutline,
IoBicycleSharp,
IoBicycle,
IoBluetoothOutline,
IoBluetoothSharp,
IoBluetooth,
IoBoatOutline,
IoBoatSharp,
IoBoat,
IoBodyOutline,
IoBodySharp,
IoBody,
IoBonfireOutline,
IoBonfireSharp,
IoBonfire,
IoBookOutline,
IoBookSharp,
IoBook,
IoBookmarkOutline,
IoBookmarkSharp,
IoBookmark,
IoBookmarksOutline,
IoBookmarksSharp,
IoBookmarks,
IoBowlingBallOutline,
IoBowlingBallSharp,
IoBowlingBall,
IoBriefcaseOutline,
IoBriefcaseSharp,
IoBriefcase,
IoBrowsersOutline,
IoBrowsersSharp,
IoBrowsers,
IoBrushOutline,
IoBrushSharp,
IoBrush,
IoBugOutline,
IoBugSharp,
IoBug,
IoBuildOutline,
IoBuildSharp,
IoBuild,
IoBulbOutline,
IoBulbSharp,
IoBulb,
IoBusOutline,
IoBusSharp,
IoBus,
IoBusinessOutline,
IoBusinessSharp,
IoBusiness,
IoCafeOutline,
IoCafeSharp,
IoCafe,
IoCalculatorOutline,
IoCalculatorSharp,
IoCalculator,
IoCalendarClearOutline,
IoCalendarClearSharp,
IoCalendarClear,
IoCalendarNumberOutline,
IoCalendarNumberSharp,
IoCalendarNumber,
IoCalendarOutline,
IoCalendarSharp,
IoCalendar,
IoCallOutline,
IoCallSharp,
IoCall,
IoCameraOutline,
IoCameraReverseOutline,
IoCameraReverseSharp,
IoCameraReverse,
IoCameraSharp,
IoCamera,
IoCarOutline,
IoCarSharp,
IoCarSportOutline,
IoCarSportSharp,
IoCarSport,
IoCar,
IoCardOutline,
IoCardSharp,
IoCard,
IoCaretBackCircleOutline,
IoCaretBackCircleSharp,
IoCaretBackCircle,
IoCaretBackOutline,
IoCaretBackSharp,
IoCaretBack,
IoCaretDownCircleOutline,
IoCaretDownCircleSharp,
IoCaretDownCircle,
IoCaretDownOutline,
IoCaretDownSharp,
IoCaretDown,
IoCaretForwardCircleOutline,
IoCaretForwardCircleSharp,
IoCaretForwardCircle,
IoCaretForwardOutline,
IoCaretForwardSharp,
IoCaretForward,
IoCaretUpCircleOutline,
IoCaretUpCircleSharp,
IoCaretUpCircle,
IoCaretUpOutline,
IoCaretUpSharp,
IoCaretUp,
IoCartOutline,
IoCartSharp,
IoCart,
IoCashOutline,
IoCashSharp,
IoCash,
IoCellularOutline,
IoCellularSharp,
IoCellular,
IoChatboxEllipsesOutline,
IoChatboxEllipsesSharp,
IoChatboxEllipses,
IoChatboxOutline,
IoChatboxSharp,
IoChatbox,
IoChatbubbleEllipsesOutline,
IoChatbubbleEllipsesSharp,
IoChatbubbleEllipses,
IoChatbubbleOutline,
IoChatbubbleSharp,
IoChatbubble,
IoChatbubblesOutline,
IoChatbubblesSharp,
IoChatbubbles,
IoCheckboxOutline,
IoCheckboxSharp,
IoCheckbox,
IoCheckmarkCircleOutline,
IoCheckmarkCircleSharp,
IoCheckmarkCircle,
IoCheckmarkDoneCircleOutline,
IoCheckmarkDoneCircleSharp,
IoCheckmarkDoneCircle,
IoCheckmarkDoneOutline,
IoCheckmarkDoneSharp,
IoCheckmarkDone,
IoCheckmarkOutline,
IoCheckmarkSharp,
IoCheckmark,
IoChevronBackCircleOutline,
IoChevronBackCircleSharp,
IoChevronBackCircle,
IoChevronBackOutline,
IoChevronBackSharp,
IoChevronBack,
IoChevronDownCircleOutline,
IoChevronDownCircleSharp,
IoChevronDownCircle,
IoChevronDownOutline,
IoChevronDownSharp,
IoChevronDown,
IoChevronForwardCircleOutline,
IoChevronForwardCircleSharp,
IoChevronForwardCircle,
IoChevronForwardOutline,
IoChevronForwardSharp,
IoChevronForward,
IoChevronUpCircleOutline,
IoChevronUpCircleSharp,
IoChevronUpCircle,
IoChevronUpOutline,
IoChevronUpSharp,
IoChevronUp,
IoClipboardOutline,
IoClipboardSharp,
IoClipboard,
IoCloseCircleOutline,
IoCloseCircleSharp,
IoCloseCircle,
IoCloseOutline,
IoCloseSharp,
IoClose,
IoCloudCircleOutline,
IoCloudCircleSharp,
IoCloudCircle,
IoCloudDoneOutline,
IoCloudDoneSharp,
IoCloudDone,
IoCloudDownloadOutline,
IoCloudDownloadSharp,
IoCloudDownload,
IoCloudOfflineOutline,
IoCloudOfflineSharp,
IoCloudOffline,
IoCloudOutline,
IoCloudSharp,
IoCloudUploadOutline,
IoCloudUploadSharp,
IoCloudUpload,
IoCloud,
IoCloudyNightOutline,
IoCloudyNightSharp,
IoCloudyNight,
IoCloudyOutline,
IoCloudySharp,
IoCloudy,
IoCodeDownloadOutline,
IoCodeDownloadSharp,
IoCodeDownload,
IoCodeOutline,
IoCodeSharp,
IoCodeSlashOutline,
IoCodeSlashSharp,
IoCodeSlash,
IoCodeWorkingOutline,
IoCodeWorkingSharp,
IoCodeWorking,
IoCode,
IoCogOutline,
IoCogSharp,
IoCog,
IoColorFillOutline,
IoColorFillSharp,
IoColorFill,
IoColorFilterOutline,
IoColorFilterSharp,
IoColorFilter,
IoColorPaletteOutline,
IoColorPaletteSharp,
IoColorPalette,
IoColorWandOutline,
IoColorWandSharp,
IoColorWand,
IoCompassOutline,
IoCompassSharp,
IoCompass,
IoConstructOutline,
IoConstructSharp,
IoConstruct,
IoContractOutline,
IoContractSharp,
IoContract,
IoContrastOutline,
IoContrastSharp,
IoContrast,
IoCopyOutline,
IoCopySharp,
IoCopy,
IoCreateOutline,
IoCreateSharp,
IoCreate,
IoCropOutline,
IoCropSharp,
IoCrop,
IoCubeOutline,
IoCubeSharp,
IoCube,
IoCutOutline,
IoCutSharp,
IoCut,
IoDesktopOutline,
IoDesktopSharp,
IoDesktop,
IoDiamondOutline,
IoDiamondSharp,
IoDiamond,
IoDiceOutline,
IoDiceSharp,
IoDice,
IoDiscOutline,
IoDiscSharp,
IoDisc,
IoDocumentAttachOutline,
IoDocumentAttachSharp,
IoDocumentAttach,
IoDocumentLockOutline,
IoDocumentLockSharp,
IoDocumentLock,
IoDocumentOutline,
IoDocumentSharp,
IoDocumentTextOutline,
IoDocumentTextSharp,
IoDocumentText,
IoDocument,
IoDocumentsOutline,
IoDocumentsSharp,
IoDocuments,
IoDownloadOutline,
IoDownloadSharp,
IoDownload,
IoDuplicateOutline,
IoDuplicateSharp,
IoDuplicate,
IoEarOutline,
IoEarSharp,
IoEar,
IoEarthOutline,
IoEarthSharp,
IoEarth,
IoEaselOutline,
IoEaselSharp,
IoEasel,
IoEggOutline,
IoEggSharp,
IoEgg,
IoEllipseOutline,
IoEllipseSharp,
IoEllipse,
IoEllipsisHorizontalCircleOutline,
IoEllipsisHorizontalCircleSharp,
IoEllipsisHorizontalCircle,
IoEllipsisHorizontalOutline,
IoEllipsisHorizontalSharp,
IoEllipsisHorizontal,
IoEllipsisVerticalCircleOutline,
IoEllipsisVerticalCircleSharp,
IoEllipsisVerticalCircle,
IoEllipsisVerticalOutline,
IoEllipsisVerticalSharp,
IoEllipsisVertical,
IoEnterOutline,
IoEnterSharp,
IoEnter,
IoExitOutline,
IoExitSharp,
IoExit,
IoExpandOutline,
IoExpandSharp,
IoExpand,
IoExtensionPuzzleOutline,
IoExtensionPuzzleSharp,
IoExtensionPuzzle,
IoEyeOffOutline,
IoEyeOffSharp,
IoEyeOff,
IoEyeOutline,
IoEyeSharp,
IoEye,
IoEyedropOutline,
IoEyedropSharp,
IoEyedrop,
IoFastFoodOutline,
IoFastFoodSharp,
IoFastFood,
IoFemaleOutline,
IoFemaleSharp,
IoFemale,
IoFileTrayFullOutline,
IoFileTrayFullSharp,
IoFileTrayFull,
IoFileTrayOutline,
IoFileTraySharp,
IoFileTrayStackedOutline,
IoFileTrayStackedSharp,
IoFileTrayStacked,
IoFileTray,
IoFilmOutline,
IoFilmSharp,
IoFilm,
IoFilterCircleOutline,
IoFilterCircleSharp,
IoFilterCircle,
IoFilterOutline,
IoFilterSharp,
IoFilter,
IoFingerPrintOutline,
IoFingerPrintSharp,
IoFingerPrint,
IoFishOutline,
IoFishSharp,
IoFish,
IoFitnessOutline,
IoFitnessSharp,
IoFitness,
IoFlagOutline,
IoFlagSharp,
IoFlag,
IoFlameOutline,
IoFlameSharp,
IoFlame,
IoFlashOffOutline,
IoFlashOffSharp,
IoFlashOff,
IoFlashOutline,
IoFlashSharp,
IoFlash,
IoFlashlightOutline,
IoFlashlightSharp,
IoFlashlight,
IoFlaskOutline,
IoFlaskSharp,
IoFlask,
IoFlowerOutline,
IoFlowerSharp,
IoFlower,
IoFolderOpenOutline,
IoFolderOpenSharp,
IoFolderOpen,
IoFolderOutline,
IoFolderSharp,
IoFolder,
IoFootballOutline,
IoFootballSharp,
IoFootball,
IoFootstepsOutline,
IoFootstepsSharp,
IoFootsteps,
IoFunnelOutline,
IoFunnelSharp,
IoFunnel,
IoGameControllerOutline,
IoGameControllerSharp,
IoGameController,
IoGiftOutline,
IoGiftSharp,
IoGift,
IoGitBranchOutline,
IoGitBranchSharp,
IoGitBranch,
IoGitCommitOutline,
IoGitCommitSharp,
IoGitCommit,
IoGitCompareOutline,
IoGitCompareSharp,
IoGitCompare,
IoGitMergeOutline,
IoGitMergeSharp,
IoGitMerge,
IoGitNetworkOutline,
IoGitNetworkSharp,
IoGitNetwork,
IoGitPullRequestOutline,
IoGitPullRequestSharp,
IoGitPullRequest,
IoGlassesOutline,
IoGlassesSharp,
IoGlasses,
IoGlobeOutline,
IoGlobeSharp,
IoGlobe,
IoGolfOutline,
IoGolfSharp,
IoGolf,
IoGridOutline,
IoGridSharp,
IoGrid,
IoHammerOutline,
IoHammerSharp,
IoHammer,
IoHandLeftOutline,
IoHandLeftSharp,
IoHandLeft,
IoHandRightOutline,
IoHandRightSharp,
IoHandRight,
IoHappyOutline,
IoHappySharp,
IoHappy,
IoHardwareChipOutline,
IoHardwareChipSharp,
IoHardwareChip,
IoHeadsetOutline,
IoHeadsetSharp,
IoHeadset,
IoHeartCircleOutline,
IoHeartCircleSharp,
IoHeartCircle,
IoHeartDislikeCircleOutline,
IoHeartDislikeCircleSharp,
IoHeartDislikeCircle,
IoHeartDislikeOutline,
IoHeartDislikeSharp,
IoHeartDislike,
IoHeartHalfOutline,
IoHeartHalfSharp,
IoHeartHalf,
IoHeartOutline,
IoHeartSharp,
IoHeart,
IoHelpBuoyOutline,
IoHelpBuoySharp,
IoHelpBuoy,
IoHelpCircleOutline,
IoHelpCircleSharp,
IoHelpCircle,
IoHelpOutline,
IoHelpSharp,
IoHelp,
IoHomeOutline,
IoHomeSharp,
IoHome,
IoHourglassOutline,
IoHourglassSharp,
IoHourglass,
IoIceCreamOutline,
IoIceCreamSharp,
IoIceCream,
IoIdCardOutline,
IoIdCardSharp,
IoIdCard,
IoImageOutline,
IoImageSharp,
IoImage,
IoImagesOutline,
IoImagesSharp,
IoImages,
IoInfiniteOutline,
IoInfiniteSharp,
IoInfinite,
IoInformationCircleOutline,
IoInformationCircleSharp,
IoInformationCircle,
IoInformationOutline,
IoInformationSharp,
IoInformation,
IoInvertModeOutline,
IoInvertModeSharp,
IoInvertMode,
IoJournalOutline,
IoJournalSharp,
IoJournal,
IoKeyOutline,
IoKeySharp,
IoKey,
IoKeypadOutline,
IoKeypadSharp,
IoKeypad,
IoLanguageOutline,
IoLanguageSharp,
IoLanguage,
IoLaptopOutline,
IoLaptopSharp,
IoLaptop,
IoLayersOutline,
IoLayersSharp,
IoLayers,
IoLeafOutline,
IoLeafSharp,
IoLeaf,
IoLibraryOutline,
IoLibrarySharp,
IoLibrary,
IoLinkOutline,
IoLinkSharp,
IoLink,
IoListCircleOutline,
IoListCircleSharp,
IoListCircle,
IoListOutline,
IoListSharp,
IoList,
IoLocateOutline,
IoLocateSharp,
IoLocate,
IoLocationOutline,
IoLocationSharp,
IoLocation,
IoLockClosedOutline,
IoLockClosedSharp,
IoLockClosed,
IoLockOpenOutline,
IoLockOpenSharp,
IoLockOpen,
IoLogInOutline,
IoLogInSharp,
IoLogIn,
IoLogOutOutline,
IoLogOutSharp,
IoLogOut,
IoLogoAlipay,
IoLogoAmazon,
IoLogoAmplify,
IoLogoAndroid,
IoLogoAngular,
IoLogoAppleAppstore,
IoLogoAppleAr,
IoLogoApple,
IoLogoBehance,
IoLogoBitbucket,
IoLogoBitcoin,
IoLogoBuffer,
IoLogoCapacitor,
IoLogoChrome,
IoLogoClosedCaptioning,
IoLogoCodepen,
IoLogoCss3,
IoLogoDesignernews,
IoLogoDeviantart,
IoLogoDiscord,
IoLogoDocker,
IoLogoDribbble,
IoLogoDropbox,
IoLogoEdge,
IoLogoElectron,
IoLogoEuro,
IoLogoFacebook,
IoLogoFigma,
IoLogoFirebase,
IoLogoFirefox,
IoLogoFlickr,
IoLogoFoursquare,
IoLogoGithub,
IoLogoGitlab,
IoLogoGooglePlaystore,
IoLogoGoogle,
IoLogoHackernews,
IoLogoHtml5,
IoLogoInstagram,
IoLogoIonic,
IoLogoIonitron,
IoLogoJavascript,
IoLogoLaravel,
IoLogoLinkedin,
IoLogoMarkdown,
IoLogoMastodon,
IoLogoMedium,
IoLogoMicrosoft,
IoLogoNoSmoking,
IoLogoNodejs,
IoLogoNpm,
IoLogoOctocat,
IoLogoPaypal,
IoLogoPinterest,
IoLogoPlaystation,
IoLogoPwa,
IoLogoPython,
IoLogoReact,
IoLogoReddit,
IoLogoRss,
IoLogoSass,
IoLogoSkype,
IoLogoSlack,
IoLogoSnapchat,
IoLogoSoundcloud,
IoLogoStackoverflow,
IoLogoSteam,
IoLogoStencil,
IoLogoTableau,
IoLogoTiktok,
IoLogoTumblr,
IoLogoTux,
IoLogoTwitch,
IoLogoTwitter,
IoLogoUsd,
IoLogoVenmo,
IoLogoVercel,
IoLogoVimeo,
IoLogoVk,
IoLogoVue,
IoLogoWebComponent,
IoLogoWechat,
IoLogoWhatsapp,
IoLogoWindows,
IoLogoWordpress,
IoLogoXbox,
IoLogoXing,
IoLogoYahoo,
IoLogoYen,
IoLogoYoutube,
IoMagnetOutline,
IoMagnetSharp,
IoMagnet,
IoMailOpenOutline,
IoMailOpenSharp,
IoMailOpen,
IoMailOutline,
IoMailSharp,
IoMailUnreadOutline,
IoMailUnreadSharp,
IoMailUnread,
IoMail,
IoMaleFemaleOutline,
IoMaleFemaleSharp,
IoMaleFemale,
IoMaleOutline,
IoMaleSharp,
IoMale,
IoManOutline,
IoManSharp,
IoMan,
IoMapOutline,
IoMapSharp,
IoMap,
IoMedalOutline,
IoMedalSharp,
IoMedal,
IoMedicalOutline,
IoMedicalSharp,
IoMedical,
IoMedkitOutline,
IoMedkitSharp,
IoMedkit,
IoMegaphoneOutline,
IoMegaphoneSharp,
IoMegaphone,
IoMenuOutline,
IoMenuSharp,
IoMenu,
IoMicCircleOutline,
IoMicCircleSharp,
IoMicCircle,
IoMicOffCircleOutline,
IoMicOffCircleSharp,
IoMicOffCircle,
IoMicOffOutline,
IoMicOffSharp,
IoMicOff,
IoMicOutline,
IoMicSharp,
IoMic,
IoMoonOutline,
IoMoonSharp,
IoMoon,
IoMoveOutline,
IoMoveSharp,
IoMove,
IoMusicalNoteOutline,
IoMusicalNoteSharp,
IoMusicalNote,
IoMusicalNotesOutline,
IoMusicalNotesSharp,
IoMusicalNotes,
IoNavigateCircleOutline,
IoNavigateCircleSharp,
IoNavigateCircle,
IoNavigateOutline,
IoNavigateSharp,
IoNavigate,
IoNewspaperOutline,
IoNewspaperSharp,
IoNewspaper,
IoNotificationsCircleOutline,
IoNotificationsCircleSharp,
IoNotificationsCircle,
IoNotificationsOffCircleOutline,
IoNotificationsOffCircleSharp,
IoNotificationsOffCircle,
IoNotificationsOffOutline,
IoNotificationsOffSharp,
IoNotificationsOff,
IoNotificationsOutline,
IoNotificationsSharp,
IoNotifications,
IoNuclearOutline,
IoNuclearSharp,
IoNuclear,
IoNutritionOutline,
IoNutritionSharp,
IoNutrition,
IoOpenOutline,
IoOpenSharp,
IoOpen,
IoOptionsOutline,
IoOptionsSharp,
IoOptions,
IoPaperPlaneOutline,
IoPaperPlaneSharp,
IoPaperPlane,
IoPartlySunnyOutline,
IoPartlySunnySharp,
IoPartlySunny,
IoPauseCircleOutline,
IoPauseCircleSharp,
IoPauseCircle,
IoPauseOutline,
IoPauseSharp,
IoPause,
IoPawOutline,
IoPawSharp,
IoPaw,
IoPencilOutline,
IoPencilSharp,
IoPencil,
IoPeopleCircleOutline,
IoPeopleCircleSharp,
IoPeopleCircle,
IoPeopleOutline,
IoPeopleSharp,
IoPeople,
IoPersonAddOutline,
IoPersonAddSharp,
IoPersonAdd,
IoPersonCircleOutline,
IoPersonCircleSharp,
IoPersonCircle,
IoPersonOutline,
IoPersonRemoveOutline,
IoPersonRemoveSharp,
IoPersonRemove,
IoPersonSharp,
IoPerson,
IoPhoneLandscapeOutline,
IoPhoneLandscapeSharp,
IoPhoneLandscape,
IoPhonePortraitOutline,
IoPhonePortraitSharp,
IoPhonePortrait,
IoPieChartOutline,
IoPieChartSharp,
IoPieChart,
IoPinOutline,
IoPinSharp,
IoPin,
IoPintOutline,
IoPintSharp,
IoPint,
IoPizzaOutline,
IoPizzaSharp,
IoPizza,
IoPlanetOutline,
IoPlanetSharp,
IoPlanet,
IoPlayBackCircleOutline,
IoPlayBackCircleSharp,
IoPlayBackCircle,
IoPlayBackOutline,
IoPlayBackSharp,
IoPlayBack,
IoPlayCircleOutline,
IoPlayCircleSharp,
IoPlayCircle,
IoPlayForwardCircleOutline,
IoPlayForwardCircleSharp,
IoPlayForwardCircle,
IoPlayForwardOutline,
IoPlayForwardSharp,
IoPlayForward,
IoPlayOutline,
IoPlaySharp,
IoPlaySkipBackCircleOutline,
IoPlaySkipBackCircleSharp,
IoPlaySkipBackCircle,
IoPlaySkipBackOutline,
IoPlaySkipBackSharp,
IoPlaySkipBack,
IoPlaySkipForwardCircleOutline,
IoPlaySkipForwardCircleSharp,
IoPlaySkipForwardCircle,
IoPlaySkipForwardOutline,
IoPlaySkipForwardSharp,
IoPlaySkipForward,
IoPlay,
IoPodiumOutline,
IoPodiumSharp,
IoPodium,
IoPowerOutline,
IoPowerSharp,
IoPower,
IoPricetagOutline,
IoPricetagSharp,
IoPricetag,
IoPricetagsOutline,
IoPricetagsSharp,
IoPricetags,
IoPrintOutline,
IoPrintSharp,
IoPrint,
IoPrismOutline,
IoPrismSharp,
IoPrism,
IoPulseOutline,
IoPulseSharp,
IoPulse,
IoPushOutline,
IoPushSharp,
IoPush,
IoQrCodeOutline,
IoQrCodeSharp,
IoQrCode,
IoRadioButtonOffOutline,
IoRadioButtonOffSharp,
IoRadioButtonOff,
IoRadioButtonOnOutline,
IoRadioButtonOnSharp,
IoRadioButtonOn,
IoRadioOutline,
IoRadioSharp,
IoRadio,
IoRainyOutline,
IoRainySharp,
IoRainy,
IoReaderOutline,
IoReaderSharp,
IoReader,
IoReceiptOutline,
IoReceiptSharp,
IoReceipt,
IoRecordingOutline,
IoRecordingSharp,
IoRecording,
IoRefreshCircleOutline,
IoRefreshCircleSharp,
IoRefreshCircle,
IoRefreshOutline,
IoRefreshSharp,
IoRefresh,
IoReloadCircleOutline,
IoReloadCircleSharp,
IoReloadCircle,
IoReloadOutline,
IoReloadSharp,
IoReload,
IoRemoveCircleOutline,
IoRemoveCircleSharp,
IoRemoveCircle,
IoRemoveOutline,
IoRemoveSharp,
IoRemove,
IoReorderFourOutline,
IoReorderFourSharp,
IoReorderFour,
IoReorderThreeOutline,
IoReorderThreeSharp,
IoReorderThree,
IoReorderTwoOutline,
IoReorderTwoSharp,
IoReorderTwo,
IoRepeatOutline,
IoRepeatSharp,
IoRepeat,
IoResizeOutline,
IoResizeSharp,
IoResize,
IoRestaurantOutline,
IoRestaurantSharp,
IoRestaurant,
IoReturnDownBackOutline,
IoReturnDownBackSharp,
IoReturnDownBack,
IoReturnDownForwardOutline,
IoReturnDownForwardSharp,
IoReturnDownForward,
IoReturnUpBackOutline,
IoReturnUpBackSharp,
IoReturnUpBack,
IoReturnUpForwardOutline,
IoReturnUpForwardSharp,
IoReturnUpForward,
IoRibbonOutline,
IoRibbonSharp,
IoRibbon,
IoRocketOutline,
IoRocketSharp,
IoRocket,
IoRoseOutline,
IoRoseSharp,
IoRose,
IoSadOutline,
IoSadSharp,
IoSad,
IoSaveOutline,
IoSaveSharp,
IoSave,
IoScaleOutline,
IoScaleSharp,
IoScale,
IoScanCircleOutline,
IoScanCircleSharp,
IoScanCircle,
IoScanOutline,
IoScanSharp,
IoScan,
IoSchoolOutline,
IoSchoolSharp,
IoSchool,
IoSearchCircleOutline,
IoSearchCircleSharp,
IoSearchCircle,
IoSearchOutline,
IoSearchSharp,
IoSearch,
IoSendOutline,
IoSendSharp,
IoSend,
IoServerOutline,
IoServerSharp,
IoServer,
IoSettingsOutline,
IoSettingsSharp,
IoSettings,
IoShapesOutline,
IoShapesSharp,
IoShapes,
IoShareOutline,
IoShareSharp,
IoShareSocialOutline,
IoShareSocialSharp,
IoShareSocial,
IoShare,
IoShieldCheckmarkOutline,
IoShieldCheckmarkSharp,
IoShieldCheckmark,
IoShieldHalfOutline,
IoShieldHalfSharp,
IoShieldHalf,
IoShieldOutline,
IoShieldSharp,
IoShield,
IoShirtOutline,
IoShirtSharp,
IoShirt,
IoShuffleOutline,
IoShuffleSharp,
IoShuffle,
IoSkullOutline,
IoSkullSharp,
IoSkull,
IoSnowOutline,
IoSnowSharp,
IoSnow,
IoSparklesOutline,
IoSparklesSharp,
IoSparkles,
IoSpeedometerOutline,
IoSpeedometerSharp,
IoSpeedometer,
IoSquareOutline,
IoSquareSharp,
IoSquare,
IoStarHalfOutline,
IoStarHalfSharp,
IoStarHalf,
IoStarOutline,
IoStarSharp,
IoStar,
IoStatsChartOutline,
IoStatsChartSharp,
IoStatsChart,
IoStopCircleOutline,
IoStopCircleSharp,
IoStopCircle,
IoStopOutline,
IoStopSharp,
IoStop,
IoStopwatchOutline,
IoStopwatchSharp,
IoStopwatch,
IoStorefrontOutline,
IoStorefrontSharp,
IoStorefront,
IoSubwayOutline,
IoSubwaySharp,
IoSubway,
IoSunnyOutline,
IoSunnySharp,
IoSunny,
IoSwapHorizontalOutline,
IoSwapHorizontalSharp,
IoSwapHorizontal,
IoSwapVerticalOutline,
IoSwapVerticalSharp,
IoSwapVertical,
IoSyncCircleOutline,
IoSyncCircleSharp,
IoSyncCircle,
IoSyncOutline,
IoSyncSharp,
IoSync,
IoTabletLandscapeOutline,
IoTabletLandscapeSharp,
IoTabletLandscape,
IoTabletPortraitOutline,
IoTabletPortraitSharp,
IoTabletPortrait,
IoTelescopeOutline,
IoTelescopeSharp,
IoTelescope,
IoTennisballOutline,
IoTennisballSharp,
IoTennisball,
IoTerminalOutline,
IoTerminalSharp,
IoTerminal,
IoTextOutline,
IoTextSharp,
IoText,
IoThermometerOutline,
IoThermometerSharp,
IoThermometer,
IoThumbsDownOutline,
IoThumbsDownSharp,
IoThumbsDown,
IoThumbsUpOutline,
IoThumbsUpSharp,
IoThumbsUp,
IoThunderstormOutline,
IoThunderstormSharp,
IoThunderstorm,
IoTicketOutline,
IoTicketSharp,
IoTicket,
IoTimeOutline,
IoTimeSharp,
IoTime,
IoTimerOutline,
IoTimerSharp,
IoTimer,
IoTodayOutline,
IoTodaySharp,
IoToday,
IoToggleOutline,
IoToggleSharp,
IoToggle,
IoTrailSignOutline,
IoTrailSignSharp,
IoTrailSign,
IoTrainOutline,
IoTrainSharp,
IoTrain,
IoTransgenderOutline,
IoTransgenderSharp,
IoTransgender,
IoTrashBinOutline,
IoTrashBinSharp,
IoTrashBin,
IoTrashOutline,
IoTrashSharp,
IoTrash,
IoTrendingDownOutline,
IoTrendingDownSharp,
IoTrendingDown,
IoTrendingUpOutline,
IoTrendingUpSharp,
IoTrendingUp,
IoTriangleOutline,
IoTriangleSharp,
IoTriangle,
IoTrophyOutline,
IoTrophySharp,
IoTrophy,
IoTvOutline,
IoTvSharp,
IoTv,
IoUmbrellaOutline,
IoUmbrellaSharp,
IoUmbrella,
IoUnlinkOutline,
IoUnlinkSharp,
IoUnlink,
IoVideocamOffOutline,
IoVideocamOffSharp,
IoVideocamOff,
IoVideocamOutline,
IoVideocamSharp,
IoVideocam,
IoVolumeHighOutline,
IoVolumeHighSharp,
IoVolumeHigh,
IoVolumeLowOutline,
IoVolumeLowSharp,
IoVolumeLow,
IoVolumeMediumOutline,
IoVolumeMediumSharp,
IoVolumeMedium,
IoVolumeMuteOutline,
IoVolumeMuteSharp,
IoVolumeMute,
IoVolumeOffOutline,
IoVolumeOffSharp,
IoVolumeOff,
IoWalkOutline,
IoWalkSharp,
IoWalk,
IoWalletOutline,
IoWalletSharp,
IoWallet,
IoWarningOutline,
IoWarningSharp,
IoWarning,
IoWatchOutline,
IoWatchSharp,
IoWatch,
IoWaterOutline,
IoWaterSharp,
IoWater,
IoWifiOutline,
IoWifiSharp,
IoWifi,
IoWineOutline,
IoWineSharp,
IoWine,
IoWomanOutline,
IoWomanSharp,
IoWoman,
} from "react-icons/io5";

const result = [
{ icon: IoAccessibilityOutline, name: "IoAccessibilityOutline" },
{ icon: IoAccessibilitySharp, name: "IoAccessibilitySharp" },
{ icon: IoAccessibility, name: "IoAccessibility" },
{ icon: IoAddCircleOutline, name: "IoAddCircleOutline" },
{ icon: IoAddCircleSharp, name: "IoAddCircleSharp" },
{ icon: IoAddCircle, name: "IoAddCircle" },
{ icon: IoAddOutline, name: "IoAddOutline" },
{ icon: IoAddSharp, name: "IoAddSharp" },
{ icon: IoAdd, name: "IoAdd" },
{ icon: IoAirplaneOutline, name: "IoAirplaneOutline" },
{ icon: IoAirplaneSharp, name: "IoAirplaneSharp" },
{ icon: IoAirplane, name: "IoAirplane" },
{ icon: IoAlarmOutline, name: "IoAlarmOutline" },
{ icon: IoAlarmSharp, name: "IoAlarmSharp" },
{ icon: IoAlarm, name: "IoAlarm" },
{ icon: IoAlbumsOutline, name: "IoAlbumsOutline" },
{ icon: IoAlbumsSharp, name: "IoAlbumsSharp" },
{ icon: IoAlbums, name: "IoAlbums" },
{ icon: IoAlertCircleOutline, name: "IoAlertCircleOutline" },
{ icon: IoAlertCircleSharp, name: "IoAlertCircleSharp" },
{ icon: IoAlertCircle, name: "IoAlertCircle" },
{ icon: IoAlertOutline, name: "IoAlertOutline" },
{ icon: IoAlertSharp, name: "IoAlertSharp" },
{ icon: IoAlert, name: "IoAlert" },
{ icon: IoAmericanFootballOutline, name: "IoAmericanFootballOutline" },
{ icon: IoAmericanFootballSharp, name: "IoAmericanFootballSharp" },
{ icon: IoAmericanFootball, name: "IoAmericanFootball" },
{ icon: IoAnalyticsOutline, name: "IoAnalyticsOutline" },
{ icon: IoAnalyticsSharp, name: "IoAnalyticsSharp" },
{ icon: IoAnalytics, name: "IoAnalytics" },
{ icon: IoApertureOutline, name: "IoApertureOutline" },
{ icon: IoApertureSharp, name: "IoApertureSharp" },
{ icon: IoAperture, name: "IoAperture" },
{ icon: IoAppsOutline, name: "IoAppsOutline" },
{ icon: IoAppsSharp, name: "IoAppsSharp" },
{ icon: IoApps, name: "IoApps" },
{ icon: IoArchiveOutline, name: "IoArchiveOutline" },
{ icon: IoArchiveSharp, name: "IoArchiveSharp" },
{ icon: IoArchive, name: "IoArchive" },
{ icon: IoArrowBackCircleOutline, name: "IoArrowBackCircleOutline" },
{ icon: IoArrowBackCircleSharp, name: "IoArrowBackCircleSharp" },
{ icon: IoArrowBackCircle, name: "IoArrowBackCircle" },
{ icon: IoArrowBackOutline, name: "IoArrowBackOutline" },
{ icon: IoArrowBackSharp, name: "IoArrowBackSharp" },
{ icon: IoArrowBack, name: "IoArrowBack" },
{ icon: IoArrowDownCircleOutline, name: "IoArrowDownCircleOutline" },
{ icon: IoArrowDownCircleSharp, name: "IoArrowDownCircleSharp" },
{ icon: IoArrowDownCircle, name: "IoArrowDownCircle" },
{ icon: IoArrowDownOutline, name: "IoArrowDownOutline" },
{ icon: IoArrowDownSharp, name: "IoArrowDownSharp" },
{ icon: IoArrowDown, name: "IoArrowDown" },
{ icon: IoArrowForwardCircleOutline, name: "IoArrowForwardCircleOutline" },
{ icon: IoArrowForwardCircleSharp, name: "IoArrowForwardCircleSharp" },
{ icon: IoArrowForwardCircle, name: "IoArrowForwardCircle" },
{ icon: IoArrowForwardOutline, name: "IoArrowForwardOutline" },
{ icon: IoArrowForwardSharp, name: "IoArrowForwardSharp" },
{ icon: IoArrowForward, name: "IoArrowForward" },
{ icon: IoArrowRedoCircleOutline, name: "IoArrowRedoCircleOutline" },
{ icon: IoArrowRedoCircleSharp, name: "IoArrowRedoCircleSharp" },
{ icon: IoArrowRedoCircle, name: "IoArrowRedoCircle" },
{ icon: IoArrowRedoOutline, name: "IoArrowRedoOutline" },
{ icon: IoArrowRedoSharp, name: "IoArrowRedoSharp" },
{ icon: IoArrowRedo, name: "IoArrowRedo" },
{ icon: IoArrowUndoCircleOutline, name: "IoArrowUndoCircleOutline" },
{ icon: IoArrowUndoCircleSharp, name: "IoArrowUndoCircleSharp" },
{ icon: IoArrowUndoCircle, name: "IoArrowUndoCircle" },
{ icon: IoArrowUndoOutline, name: "IoArrowUndoOutline" },
{ icon: IoArrowUndoSharp, name: "IoArrowUndoSharp" },
{ icon: IoArrowUndo, name: "IoArrowUndo" },
{ icon: IoArrowUpCircleOutline, name: "IoArrowUpCircleOutline" },
{ icon: IoArrowUpCircleSharp, name: "IoArrowUpCircleSharp" },
{ icon: IoArrowUpCircle, name: "IoArrowUpCircle" },
{ icon: IoArrowUpOutline, name: "IoArrowUpOutline" },
{ icon: IoArrowUpSharp, name: "IoArrowUpSharp" },
{ icon: IoArrowUp, name: "IoArrowUp" },
{ icon: IoAtCircleOutline, name: "IoAtCircleOutline" },
{ icon: IoAtCircleSharp, name: "IoAtCircleSharp" },
{ icon: IoAtCircle, name: "IoAtCircle" },
{ icon: IoAtOutline, name: "IoAtOutline" },
{ icon: IoAtSharp, name: "IoAtSharp" },
{ icon: IoAt, name: "IoAt" },
{ icon: IoAttachOutline, name: "IoAttachOutline" },
{ icon: IoAttachSharp, name: "IoAttachSharp" },
{ icon: IoAttach, name: "IoAttach" },
{ icon: IoBackspaceOutline, name: "IoBackspaceOutline" },
{ icon: IoBackspaceSharp, name: "IoBackspaceSharp" },
{ icon: IoBackspace, name: "IoBackspace" },
{ icon: IoBagAddOutline, name: "IoBagAddOutline" },
{ icon: IoBagAddSharp, name: "IoBagAddSharp" },
{ icon: IoBagAdd, name: "IoBagAdd" },
{ icon: IoBagCheckOutline, name: "IoBagCheckOutline" },
{ icon: IoBagCheckSharp, name: "IoBagCheckSharp" },
{ icon: IoBagCheck, name: "IoBagCheck" },
{ icon: IoBagHandleOutline, name: "IoBagHandleOutline" },
{ icon: IoBagHandleSharp, name: "IoBagHandleSharp" },
{ icon: IoBagHandle, name: "IoBagHandle" },
{ icon: IoBagOutline, name: "IoBagOutline" },
{ icon: IoBagRemoveOutline, name: "IoBagRemoveOutline" },
{ icon: IoBagRemoveSharp, name: "IoBagRemoveSharp" },
{ icon: IoBagRemove, name: "IoBagRemove" },
{ icon: IoBagSharp, name: "IoBagSharp" },
{ icon: IoBag, name: "IoBag" },
{ icon: IoBalloonOutline, name: "IoBalloonOutline" },
{ icon: IoBalloonSharp, name: "IoBalloonSharp" },
{ icon: IoBalloon, name: "IoBalloon" },
{ icon: IoBanOutline, name: "IoBanOutline" },
{ icon: IoBanSharp, name: "IoBanSharp" },
{ icon: IoBan, name: "IoBan" },
{ icon: IoBandageOutline, name: "IoBandageOutline" },
{ icon: IoBandageSharp, name: "IoBandageSharp" },
{ icon: IoBandage, name: "IoBandage" },
{ icon: IoBarChartOutline, name: "IoBarChartOutline" },
{ icon: IoBarChartSharp, name: "IoBarChartSharp" },
{ icon: IoBarChart, name: "IoBarChart" },
{ icon: IoBarbellOutline, name: "IoBarbellOutline" },
{ icon: IoBarbellSharp, name: "IoBarbellSharp" },
{ icon: IoBarbell, name: "IoBarbell" },
{ icon: IoBarcodeOutline, name: "IoBarcodeOutline" },
{ icon: IoBarcodeSharp, name: "IoBarcodeSharp" },
{ icon: IoBarcode, name: "IoBarcode" },
{ icon: IoBaseballOutline, name: "IoBaseballOutline" },
{ icon: IoBaseballSharp, name: "IoBaseballSharp" },
{ icon: IoBaseball, name: "IoBaseball" },
{ icon: IoBasketOutline, name: "IoBasketOutline" },
{ icon: IoBasketSharp, name: "IoBasketSharp" },
{ icon: IoBasket, name: "IoBasket" },
{ icon: IoBasketballOutline, name: "IoBasketballOutline" },
{ icon: IoBasketballSharp, name: "IoBasketballSharp" },
{ icon: IoBasketball, name: "IoBasketball" },
{ icon: IoBatteryChargingOutline, name: "IoBatteryChargingOutline" },
{ icon: IoBatteryChargingSharp, name: "IoBatteryChargingSharp" },
{ icon: IoBatteryCharging, name: "IoBatteryCharging" },
{ icon: IoBatteryDeadOutline, name: "IoBatteryDeadOutline" },
{ icon: IoBatteryDeadSharp, name: "IoBatteryDeadSharp" },
{ icon: IoBatteryDead, name: "IoBatteryDead" },
{ icon: IoBatteryFullOutline, name: "IoBatteryFullOutline" },
{ icon: IoBatteryFullSharp, name: "IoBatteryFullSharp" },
{ icon: IoBatteryFull, name: "IoBatteryFull" },
{ icon: IoBatteryHalfOutline, name: "IoBatteryHalfOutline" },
{ icon: IoBatteryHalfSharp, name: "IoBatteryHalfSharp" },
{ icon: IoBatteryHalf, name: "IoBatteryHalf" },
{ icon: IoBeakerOutline, name: "IoBeakerOutline" },
{ icon: IoBeakerSharp, name: "IoBeakerSharp" },
{ icon: IoBeaker, name: "IoBeaker" },
{ icon: IoBedOutline, name: "IoBedOutline" },
{ icon: IoBedSharp, name: "IoBedSharp" },
{ icon: IoBed, name: "IoBed" },
{ icon: IoBeerOutline, name: "IoBeerOutline" },
{ icon: IoBeerSharp, name: "IoBeerSharp" },
{ icon: IoBeer, name: "IoBeer" },
{ icon: IoBicycleOutline, name: "IoBicycleOutline" },
{ icon: IoBicycleSharp, name: "IoBicycleSharp" },
{ icon: IoBicycle, name: "IoBicycle" },
{ icon: IoBluetoothOutline, name: "IoBluetoothOutline" },
{ icon: IoBluetoothSharp, name: "IoBluetoothSharp" },
{ icon: IoBluetooth, name: "IoBluetooth" },
{ icon: IoBoatOutline, name: "IoBoatOutline" },
{ icon: IoBoatSharp, name: "IoBoatSharp" },
{ icon: IoBoat, name: "IoBoat" },
{ icon: IoBodyOutline, name: "IoBodyOutline" },
{ icon: IoBodySharp, name: "IoBodySharp" },
{ icon: IoBody, name: "IoBody" },
{ icon: IoBonfireOutline, name: "IoBonfireOutline" },
{ icon: IoBonfireSharp, name: "IoBonfireSharp" },
{ icon: IoBonfire, name: "IoBonfire" },
{ icon: IoBookOutline, name: "IoBookOutline" },
{ icon: IoBookSharp, name: "IoBookSharp" },
{ icon: IoBook, name: "IoBook" },
{ icon: IoBookmarkOutline, name: "IoBookmarkOutline" },
{ icon: IoBookmarkSharp, name: "IoBookmarkSharp" },
{ icon: IoBookmark, name: "IoBookmark" },
{ icon: IoBookmarksOutline, name: "IoBookmarksOutline" },
{ icon: IoBookmarksSharp, name: "IoBookmarksSharp" },
{ icon: IoBookmarks, name: "IoBookmarks" },
{ icon: IoBowlingBallOutline, name: "IoBowlingBallOutline" },
{ icon: IoBowlingBallSharp, name: "IoBowlingBallSharp" },
{ icon: IoBowlingBall, name: "IoBowlingBall" },
{ icon: IoBriefcaseOutline, name: "IoBriefcaseOutline" },
{ icon: IoBriefcaseSharp, name: "IoBriefcaseSharp" },
{ icon: IoBriefcase, name: "IoBriefcase" },
{ icon: IoBrowsersOutline, name: "IoBrowsersOutline" },
{ icon: IoBrowsersSharp, name: "IoBrowsersSharp" },
{ icon: IoBrowsers, name: "IoBrowsers" },
{ icon: IoBrushOutline, name: "IoBrushOutline" },
{ icon: IoBrushSharp, name: "IoBrushSharp" },
{ icon: IoBrush, name: "IoBrush" },
{ icon: IoBugOutline, name: "IoBugOutline" },
{ icon: IoBugSharp, name: "IoBugSharp" },
{ icon: IoBug, name: "IoBug" },
{ icon: IoBuildOutline, name: "IoBuildOutline" },
{ icon: IoBuildSharp, name: "IoBuildSharp" },
{ icon: IoBuild, name: "IoBuild" },
{ icon: IoBulbOutline, name: "IoBulbOutline" },
{ icon: IoBulbSharp, name: "IoBulbSharp" },
{ icon: IoBulb, name: "IoBulb" },
{ icon: IoBusOutline, name: "IoBusOutline" },
{ icon: IoBusSharp, name: "IoBusSharp" },
{ icon: IoBus, name: "IoBus" },
{ icon: IoBusinessOutline, name: "IoBusinessOutline" },
{ icon: IoBusinessSharp, name: "IoBusinessSharp" },
{ icon: IoBusiness, name: "IoBusiness" },
{ icon: IoCafeOutline, name: "IoCafeOutline" },
{ icon: IoCafeSharp, name: "IoCafeSharp" },
{ icon: IoCafe, name: "IoCafe" },
{ icon: IoCalculatorOutline, name: "IoCalculatorOutline" },
{ icon: IoCalculatorSharp, name: "IoCalculatorSharp" },
{ icon: IoCalculator, name: "IoCalculator" },
{ icon: IoCalendarClearOutline, name: "IoCalendarClearOutline" },
{ icon: IoCalendarClearSharp, name: "IoCalendarClearSharp" },
{ icon: IoCalendarClear, name: "IoCalendarClear" },
{ icon: IoCalendarNumberOutline, name: "IoCalendarNumberOutline" },
{ icon: IoCalendarNumberSharp, name: "IoCalendarNumberSharp" },
{ icon: IoCalendarNumber, name: "IoCalendarNumber" },
{ icon: IoCalendarOutline, name: "IoCalendarOutline" },
{ icon: IoCalendarSharp, name: "IoCalendarSharp" },
{ icon: IoCalendar, name: "IoCalendar" },
{ icon: IoCallOutline, name: "IoCallOutline" },
{ icon: IoCallSharp, name: "IoCallSharp" },
{ icon: IoCall, name: "IoCall" },
{ icon: IoCameraOutline, name: "IoCameraOutline" },
{ icon: IoCameraReverseOutline, name: "IoCameraReverseOutline" },
{ icon: IoCameraReverseSharp, name: "IoCameraReverseSharp" },
{ icon: IoCameraReverse, name: "IoCameraReverse" },
{ icon: IoCameraSharp, name: "IoCameraSharp" },
{ icon: IoCamera, name: "IoCamera" },
{ icon: IoCarOutline, name: "IoCarOutline" },
{ icon: IoCarSharp, name: "IoCarSharp" },
{ icon: IoCarSportOutline, name: "IoCarSportOutline" },
{ icon: IoCarSportSharp, name: "IoCarSportSharp" },
{ icon: IoCarSport, name: "IoCarSport" },
{ icon: IoCar, name: "IoCar" },
{ icon: IoCardOutline, name: "IoCardOutline" },
{ icon: IoCardSharp, name: "IoCardSharp" },
{ icon: IoCard, name: "IoCard" },
{ icon: IoCaretBackCircleOutline, name: "IoCaretBackCircleOutline" },
{ icon: IoCaretBackCircleSharp, name: "IoCaretBackCircleSharp" },
{ icon: IoCaretBackCircle, name: "IoCaretBackCircle" },
{ icon: IoCaretBackOutline, name: "IoCaretBackOutline" },
{ icon: IoCaretBackSharp, name: "IoCaretBackSharp" },
{ icon: IoCaretBack, name: "IoCaretBack" },
{ icon: IoCaretDownCircleOutline, name: "IoCaretDownCircleOutline" },
{ icon: IoCaretDownCircleSharp, name: "IoCaretDownCircleSharp" },
{ icon: IoCaretDownCircle, name: "IoCaretDownCircle" },
{ icon: IoCaretDownOutline, name: "IoCaretDownOutline" },
{ icon: IoCaretDownSharp, name: "IoCaretDownSharp" },
{ icon: IoCaretDown, name: "IoCaretDown" },
{ icon: IoCaretForwardCircleOutline, name: "IoCaretForwardCircleOutline" },
{ icon: IoCaretForwardCircleSharp, name: "IoCaretForwardCircleSharp" },
{ icon: IoCaretForwardCircle, name: "IoCaretForwardCircle" },
{ icon: IoCaretForwardOutline, name: "IoCaretForwardOutline" },
{ icon: IoCaretForwardSharp, name: "IoCaretForwardSharp" },
{ icon: IoCaretForward, name: "IoCaretForward" },
{ icon: IoCaretUpCircleOutline, name: "IoCaretUpCircleOutline" },
{ icon: IoCaretUpCircleSharp, name: "IoCaretUpCircleSharp" },
{ icon: IoCaretUpCircle, name: "IoCaretUpCircle" },
{ icon: IoCaretUpOutline, name: "IoCaretUpOutline" },
{ icon: IoCaretUpSharp, name: "IoCaretUpSharp" },
{ icon: IoCaretUp, name: "IoCaretUp" },
{ icon: IoCartOutline, name: "IoCartOutline" },
{ icon: IoCartSharp, name: "IoCartSharp" },
{ icon: IoCart, name: "IoCart" },
{ icon: IoCashOutline, name: "IoCashOutline" },
{ icon: IoCashSharp, name: "IoCashSharp" },
{ icon: IoCash, name: "IoCash" },
{ icon: IoCellularOutline, name: "IoCellularOutline" },
{ icon: IoCellularSharp, name: "IoCellularSharp" },
{ icon: IoCellular, name: "IoCellular" },
{ icon: IoChatboxEllipsesOutline, name: "IoChatboxEllipsesOutline" },
{ icon: IoChatboxEllipsesSharp, name: "IoChatboxEllipsesSharp" },
{ icon: IoChatboxEllipses, name: "IoChatboxEllipses" },
{ icon: IoChatboxOutline, name: "IoChatboxOutline" },
{ icon: IoChatboxSharp, name: "IoChatboxSharp" },
{ icon: IoChatbox, name: "IoChatbox" },
{ icon: IoChatbubbleEllipsesOutline, name: "IoChatbubbleEllipsesOutline" },
{ icon: IoChatbubbleEllipsesSharp, name: "IoChatbubbleEllipsesSharp" },
{ icon: IoChatbubbleEllipses, name: "IoChatbubbleEllipses" },
{ icon: IoChatbubbleOutline, name: "IoChatbubbleOutline" },
{ icon: IoChatbubbleSharp, name: "IoChatbubbleSharp" },
{ icon: IoChatbubble, name: "IoChatbubble" },
{ icon: IoChatbubblesOutline, name: "IoChatbubblesOutline" },
{ icon: IoChatbubblesSharp, name: "IoChatbubblesSharp" },
{ icon: IoChatbubbles, name: "IoChatbubbles" },
{ icon: IoCheckboxOutline, name: "IoCheckboxOutline" },
{ icon: IoCheckboxSharp, name: "IoCheckboxSharp" },
{ icon: IoCheckbox, name: "IoCheckbox" },
{ icon: IoCheckmarkCircleOutline, name: "IoCheckmarkCircleOutline" },
{ icon: IoCheckmarkCircleSharp, name: "IoCheckmarkCircleSharp" },
{ icon: IoCheckmarkCircle, name: "IoCheckmarkCircle" },
{ icon: IoCheckmarkDoneCircleOutline, name: "IoCheckmarkDoneCircleOutline" },
{ icon: IoCheckmarkDoneCircleSharp, name: "IoCheckmarkDoneCircleSharp" },
{ icon: IoCheckmarkDoneCircle, name: "IoCheckmarkDoneCircle" },
{ icon: IoCheckmarkDoneOutline, name: "IoCheckmarkDoneOutline" },
{ icon: IoCheckmarkDoneSharp, name: "IoCheckmarkDoneSharp" },
{ icon: IoCheckmarkDone, name: "IoCheckmarkDone" },
{ icon: IoCheckmarkOutline, name: "IoCheckmarkOutline" },
{ icon: IoCheckmarkSharp, name: "IoCheckmarkSharp" },
{ icon: IoCheckmark, name: "IoCheckmark" },
{ icon: IoChevronBackCircleOutline, name: "IoChevronBackCircleOutline" },
{ icon: IoChevronBackCircleSharp, name: "IoChevronBackCircleSharp" },
{ icon: IoChevronBackCircle, name: "IoChevronBackCircle" },
{ icon: IoChevronBackOutline, name: "IoChevronBackOutline" },
{ icon: IoChevronBackSharp, name: "IoChevronBackSharp" },
{ icon: IoChevronBack, name: "IoChevronBack" },
{ icon: IoChevronDownCircleOutline, name: "IoChevronDownCircleOutline" },
{ icon: IoChevronDownCircleSharp, name: "IoChevronDownCircleSharp" },
{ icon: IoChevronDownCircle, name: "IoChevronDownCircle" },
{ icon: IoChevronDownOutline, name: "IoChevronDownOutline" },
{ icon: IoChevronDownSharp, name: "IoChevronDownSharp" },
{ icon: IoChevronDown, name: "IoChevronDown" },
{ icon: IoChevronForwardCircleOutline, name: "IoChevronForwardCircleOutline" },
{ icon: IoChevronForwardCircleSharp, name: "IoChevronForwardCircleSharp" },
{ icon: IoChevronForwardCircle, name: "IoChevronForwardCircle" },
{ icon: IoChevronForwardOutline, name: "IoChevronForwardOutline" },
{ icon: IoChevronForwardSharp, name: "IoChevronForwardSharp" },
{ icon: IoChevronForward, name: "IoChevronForward" },
{ icon: IoChevronUpCircleOutline, name: "IoChevronUpCircleOutline" },
{ icon: IoChevronUpCircleSharp, name: "IoChevronUpCircleSharp" },
{ icon: IoChevronUpCircle, name: "IoChevronUpCircle" },
{ icon: IoChevronUpOutline, name: "IoChevronUpOutline" },
{ icon: IoChevronUpSharp, name: "IoChevronUpSharp" },
{ icon: IoChevronUp, name: "IoChevronUp" },
{ icon: IoClipboardOutline, name: "IoClipboardOutline" },
{ icon: IoClipboardSharp, name: "IoClipboardSharp" },
{ icon: IoClipboard, name: "IoClipboard" },
{ icon: IoCloseCircleOutline, name: "IoCloseCircleOutline" },
{ icon: IoCloseCircleSharp, name: "IoCloseCircleSharp" },
{ icon: IoCloseCircle, name: "IoCloseCircle" },
{ icon: IoCloseOutline, name: "IoCloseOutline" },
{ icon: IoCloseSharp, name: "IoCloseSharp" },
{ icon: IoClose, name: "IoClose" },
{ icon: IoCloudCircleOutline, name: "IoCloudCircleOutline" },
{ icon: IoCloudCircleSharp, name: "IoCloudCircleSharp" },
{ icon: IoCloudCircle, name: "IoCloudCircle" },
{ icon: IoCloudDoneOutline, name: "IoCloudDoneOutline" },
{ icon: IoCloudDoneSharp, name: "IoCloudDoneSharp" },
{ icon: IoCloudDone, name: "IoCloudDone" },
{ icon: IoCloudDownloadOutline, name: "IoCloudDownloadOutline" },
{ icon: IoCloudDownloadSharp, name: "IoCloudDownloadSharp" },
{ icon: IoCloudDownload, name: "IoCloudDownload" },
{ icon: IoCloudOfflineOutline, name: "IoCloudOfflineOutline" },
{ icon: IoCloudOfflineSharp, name: "IoCloudOfflineSharp" },
{ icon: IoCloudOffline, name: "IoCloudOffline" },
{ icon: IoCloudOutline, name: "IoCloudOutline" },
{ icon: IoCloudSharp, name: "IoCloudSharp" },
{ icon: IoCloudUploadOutline, name: "IoCloudUploadOutline" },
{ icon: IoCloudUploadSharp, name: "IoCloudUploadSharp" },
{ icon: IoCloudUpload, name: "IoCloudUpload" },
{ icon: IoCloud, name: "IoCloud" },
{ icon: IoCloudyNightOutline, name: "IoCloudyNightOutline" },
{ icon: IoCloudyNightSharp, name: "IoCloudyNightSharp" },
{ icon: IoCloudyNight, name: "IoCloudyNight" },
{ icon: IoCloudyOutline, name: "IoCloudyOutline" },
{ icon: IoCloudySharp, name: "IoCloudySharp" },
{ icon: IoCloudy, name: "IoCloudy" },
{ icon: IoCodeDownloadOutline, name: "IoCodeDownloadOutline" },
{ icon: IoCodeDownloadSharp, name: "IoCodeDownloadSharp" },
{ icon: IoCodeDownload, name: "IoCodeDownload" },
{ icon: IoCodeOutline, name: "IoCodeOutline" },
{ icon: IoCodeSharp, name: "IoCodeSharp" },
{ icon: IoCodeSlashOutline, name: "IoCodeSlashOutline" },
{ icon: IoCodeSlashSharp, name: "IoCodeSlashSharp" },
{ icon: IoCodeSlash, name: "IoCodeSlash" },
{ icon: IoCodeWorkingOutline, name: "IoCodeWorkingOutline" },
{ icon: IoCodeWorkingSharp, name: "IoCodeWorkingSharp" },
{ icon: IoCodeWorking, name: "IoCodeWorking" },
{ icon: IoCode, name: "IoCode" },
{ icon: IoCogOutline, name: "IoCogOutline" },
{ icon: IoCogSharp, name: "IoCogSharp" },
{ icon: IoCog, name: "IoCog" },
{ icon: IoColorFillOutline, name: "IoColorFillOutline" },
{ icon: IoColorFillSharp, name: "IoColorFillSharp" },
{ icon: IoColorFill, name: "IoColorFill" },
{ icon: IoColorFilterOutline, name: "IoColorFilterOutline" },
{ icon: IoColorFilterSharp, name: "IoColorFilterSharp" },
{ icon: IoColorFilter, name: "IoColorFilter" },
{ icon: IoColorPaletteOutline, name: "IoColorPaletteOutline" },
{ icon: IoColorPaletteSharp, name: "IoColorPaletteSharp" },
{ icon: IoColorPalette, name: "IoColorPalette" },
{ icon: IoColorWandOutline, name: "IoColorWandOutline" },
{ icon: IoColorWandSharp, name: "IoColorWandSharp" },
{ icon: IoColorWand, name: "IoColorWand" },
{ icon: IoCompassOutline, name: "IoCompassOutline" },
{ icon: IoCompassSharp, name: "IoCompassSharp" },
{ icon: IoCompass, name: "IoCompass" },
{ icon: IoConstructOutline, name: "IoConstructOutline" },
{ icon: IoConstructSharp, name: "IoConstructSharp" },
{ icon: IoConstruct, name: "IoConstruct" },
{ icon: IoContractOutline, name: "IoContractOutline" },
{ icon: IoContractSharp, name: "IoContractSharp" },
{ icon: IoContract, name: "IoContract" },
{ icon: IoContrastOutline, name: "IoContrastOutline" },
{ icon: IoContrastSharp, name: "IoContrastSharp" },
{ icon: IoContrast, name: "IoContrast" },
{ icon: IoCopyOutline, name: "IoCopyOutline" },
{ icon: IoCopySharp, name: "IoCopySharp" },
{ icon: IoCopy, name: "IoCopy" },
{ icon: IoCreateOutline, name: "IoCreateOutline" },
{ icon: IoCreateSharp, name: "IoCreateSharp" },
{ icon: IoCreate, name: "IoCreate" },
{ icon: IoCropOutline, name: "IoCropOutline" },
{ icon: IoCropSharp, name: "IoCropSharp" },
{ icon: IoCrop, name: "IoCrop" },
{ icon: IoCubeOutline, name: "IoCubeOutline" },
{ icon: IoCubeSharp, name: "IoCubeSharp" },
{ icon: IoCube, name: "IoCube" },
{ icon: IoCutOutline, name: "IoCutOutline" },
{ icon: IoCutSharp, name: "IoCutSharp" },
{ icon: IoCut, name: "IoCut" },
{ icon: IoDesktopOutline, name: "IoDesktopOutline" },
{ icon: IoDesktopSharp, name: "IoDesktopSharp" },
{ icon: IoDesktop, name: "IoDesktop" },
{ icon: IoDiamondOutline, name: "IoDiamondOutline" },
{ icon: IoDiamondSharp, name: "IoDiamondSharp" },
{ icon: IoDiamond, name: "IoDiamond" },
{ icon: IoDiceOutline, name: "IoDiceOutline" },
{ icon: IoDiceSharp, name: "IoDiceSharp" },
{ icon: IoDice, name: "IoDice" },
{ icon: IoDiscOutline, name: "IoDiscOutline" },
{ icon: IoDiscSharp, name: "IoDiscSharp" },
{ icon: IoDisc, name: "IoDisc" },
{ icon: IoDocumentAttachOutline, name: "IoDocumentAttachOutline" },
{ icon: IoDocumentAttachSharp, name: "IoDocumentAttachSharp" },
{ icon: IoDocumentAttach, name: "IoDocumentAttach" },
{ icon: IoDocumentLockOutline, name: "IoDocumentLockOutline" },
{ icon: IoDocumentLockSharp, name: "IoDocumentLockSharp" },
{ icon: IoDocumentLock, name: "IoDocumentLock" },
{ icon: IoDocumentOutline, name: "IoDocumentOutline" },
{ icon: IoDocumentSharp, name: "IoDocumentSharp" },
{ icon: IoDocumentTextOutline, name: "IoDocumentTextOutline" },
{ icon: IoDocumentTextSharp, name: "IoDocumentTextSharp" },
{ icon: IoDocumentText, name: "IoDocumentText" },
{ icon: IoDocument, name: "IoDocument" },
{ icon: IoDocumentsOutline, name: "IoDocumentsOutline" },
{ icon: IoDocumentsSharp, name: "IoDocumentsSharp" },
{ icon: IoDocuments, name: "IoDocuments" },
{ icon: IoDownloadOutline, name: "IoDownloadOutline" },
{ icon: IoDownloadSharp, name: "IoDownloadSharp" },
{ icon: IoDownload, name: "IoDownload" },
{ icon: IoDuplicateOutline, name: "IoDuplicateOutline" },
{ icon: IoDuplicateSharp, name: "IoDuplicateSharp" },
{ icon: IoDuplicate, name: "IoDuplicate" },
{ icon: IoEarOutline, name: "IoEarOutline" },
{ icon: IoEarSharp, name: "IoEarSharp" },
{ icon: IoEar, name: "IoEar" },
{ icon: IoEarthOutline, name: "IoEarthOutline" },
{ icon: IoEarthSharp, name: "IoEarthSharp" },
{ icon: IoEarth, name: "IoEarth" },
{ icon: IoEaselOutline, name: "IoEaselOutline" },
{ icon: IoEaselSharp, name: "IoEaselSharp" },
{ icon: IoEasel, name: "IoEasel" },
{ icon: IoEggOutline, name: "IoEggOutline" },
{ icon: IoEggSharp, name: "IoEggSharp" },
{ icon: IoEgg, name: "IoEgg" },
{ icon: IoEllipseOutline, name: "IoEllipseOutline" },
{ icon: IoEllipseSharp, name: "IoEllipseSharp" },
{ icon: IoEllipse, name: "IoEllipse" },
{ icon: IoEllipsisHorizontalCircleOutline, name: "IoEllipsisHorizontalCircleOutline" },
{ icon: IoEllipsisHorizontalCircleSharp, name: "IoEllipsisHorizontalCircleSharp" },
{ icon: IoEllipsisHorizontalCircle, name: "IoEllipsisHorizontalCircle" },
{ icon: IoEllipsisHorizontalOutline, name: "IoEllipsisHorizontalOutline" },
{ icon: IoEllipsisHorizontalSharp, name: "IoEllipsisHorizontalSharp" },
{ icon: IoEllipsisHorizontal, name: "IoEllipsisHorizontal" },
{ icon: IoEllipsisVerticalCircleOutline, name: "IoEllipsisVerticalCircleOutline" },
{ icon: IoEllipsisVerticalCircleSharp, name: "IoEllipsisVerticalCircleSharp" },
{ icon: IoEllipsisVerticalCircle, name: "IoEllipsisVerticalCircle" },
{ icon: IoEllipsisVerticalOutline, name: "IoEllipsisVerticalOutline" },
{ icon: IoEllipsisVerticalSharp, name: "IoEllipsisVerticalSharp" },
{ icon: IoEllipsisVertical, name: "IoEllipsisVertical" },
{ icon: IoEnterOutline, name: "IoEnterOutline" },
{ icon: IoEnterSharp, name: "IoEnterSharp" },
{ icon: IoEnter, name: "IoEnter" },
{ icon: IoExitOutline, name: "IoExitOutline" },
{ icon: IoExitSharp, name: "IoExitSharp" },
{ icon: IoExit, name: "IoExit" },
{ icon: IoExpandOutline, name: "IoExpandOutline" },
{ icon: IoExpandSharp, name: "IoExpandSharp" },
{ icon: IoExpand, name: "IoExpand" },
{ icon: IoExtensionPuzzleOutline, name: "IoExtensionPuzzleOutline" },
{ icon: IoExtensionPuzzleSharp, name: "IoExtensionPuzzleSharp" },
{ icon: IoExtensionPuzzle, name: "IoExtensionPuzzle" },
{ icon: IoEyeOffOutline, name: "IoEyeOffOutline" },
{ icon: IoEyeOffSharp, name: "IoEyeOffSharp" },
{ icon: IoEyeOff, name: "IoEyeOff" },
{ icon: IoEyeOutline, name: "IoEyeOutline" },
{ icon: IoEyeSharp, name: "IoEyeSharp" },
{ icon: IoEye, name: "IoEye" },
{ icon: IoEyedropOutline, name: "IoEyedropOutline" },
{ icon: IoEyedropSharp, name: "IoEyedropSharp" },
{ icon: IoEyedrop, name: "IoEyedrop" },
{ icon: IoFastFoodOutline, name: "IoFastFoodOutline" },
{ icon: IoFastFoodSharp, name: "IoFastFoodSharp" },
{ icon: IoFastFood, name: "IoFastFood" },
{ icon: IoFemaleOutline, name: "IoFemaleOutline" },
{ icon: IoFemaleSharp, name: "IoFemaleSharp" },
{ icon: IoFemale, name: "IoFemale" },
{ icon: IoFileTrayFullOutline, name: "IoFileTrayFullOutline" },
{ icon: IoFileTrayFullSharp, name: "IoFileTrayFullSharp" },
{ icon: IoFileTrayFull, name: "IoFileTrayFull" },
{ icon: IoFileTrayOutline, name: "IoFileTrayOutline" },
{ icon: IoFileTraySharp, name: "IoFileTraySharp" },
{ icon: IoFileTrayStackedOutline, name: "IoFileTrayStackedOutline" },
{ icon: IoFileTrayStackedSharp, name: "IoFileTrayStackedSharp" },
{ icon: IoFileTrayStacked, name: "IoFileTrayStacked" },
{ icon: IoFileTray, name: "IoFileTray" },
{ icon: IoFilmOutline, name: "IoFilmOutline" },
{ icon: IoFilmSharp, name: "IoFilmSharp" },
{ icon: IoFilm, name: "IoFilm" },
{ icon: IoFilterCircleOutline, name: "IoFilterCircleOutline" },
{ icon: IoFilterCircleSharp, name: "IoFilterCircleSharp" },
{ icon: IoFilterCircle, name: "IoFilterCircle" },
{ icon: IoFilterOutline, name: "IoFilterOutline" },
{ icon: IoFilterSharp, name: "IoFilterSharp" },
{ icon: IoFilter, name: "IoFilter" },
{ icon: IoFingerPrintOutline, name: "IoFingerPrintOutline" },
{ icon: IoFingerPrintSharp, name: "IoFingerPrintSharp" },
{ icon: IoFingerPrint, name: "IoFingerPrint" },
{ icon: IoFishOutline, name: "IoFishOutline" },
{ icon: IoFishSharp, name: "IoFishSharp" },
{ icon: IoFish, name: "IoFish" },
{ icon: IoFitnessOutline, name: "IoFitnessOutline" },
{ icon: IoFitnessSharp, name: "IoFitnessSharp" },
{ icon: IoFitness, name: "IoFitness" },
{ icon: IoFlagOutline, name: "IoFlagOutline" },
{ icon: IoFlagSharp, name: "IoFlagSharp" },
{ icon: IoFlag, name: "IoFlag" },
{ icon: IoFlameOutline, name: "IoFlameOutline" },
{ icon: IoFlameSharp, name: "IoFlameSharp" },
{ icon: IoFlame, name: "IoFlame" },
{ icon: IoFlashOffOutline, name: "IoFlashOffOutline" },
{ icon: IoFlashOffSharp, name: "IoFlashOffSharp" },
{ icon: IoFlashOff, name: "IoFlashOff" },
{ icon: IoFlashOutline, name: "IoFlashOutline" },
{ icon: IoFlashSharp, name: "IoFlashSharp" },
{ icon: IoFlash, name: "IoFlash" },
{ icon: IoFlashlightOutline, name: "IoFlashlightOutline" },
{ icon: IoFlashlightSharp, name: "IoFlashlightSharp" },
{ icon: IoFlashlight, name: "IoFlashlight" },
{ icon: IoFlaskOutline, name: "IoFlaskOutline" },
{ icon: IoFlaskSharp, name: "IoFlaskSharp" },
{ icon: IoFlask, name: "IoFlask" },
{ icon: IoFlowerOutline, name: "IoFlowerOutline" },
{ icon: IoFlowerSharp, name: "IoFlowerSharp" },
{ icon: IoFlower, name: "IoFlower" },
{ icon: IoFolderOpenOutline, name: "IoFolderOpenOutline" },
{ icon: IoFolderOpenSharp, name: "IoFolderOpenSharp" },
{ icon: IoFolderOpen, name: "IoFolderOpen" },
{ icon: IoFolderOutline, name: "IoFolderOutline" },
{ icon: IoFolderSharp, name: "IoFolderSharp" },
{ icon: IoFolder, name: "IoFolder" },
{ icon: IoFootballOutline, name: "IoFootballOutline" },
{ icon: IoFootballSharp, name: "IoFootballSharp" },
{ icon: IoFootball, name: "IoFootball" },
{ icon: IoFootstepsOutline, name: "IoFootstepsOutline" },
{ icon: IoFootstepsSharp, name: "IoFootstepsSharp" },
{ icon: IoFootsteps, name: "IoFootsteps" },
{ icon: IoFunnelOutline, name: "IoFunnelOutline" },
{ icon: IoFunnelSharp, name: "IoFunnelSharp" },
{ icon: IoFunnel, name: "IoFunnel" },
{ icon: IoGameControllerOutline, name: "IoGameControllerOutline" },
{ icon: IoGameControllerSharp, name: "IoGameControllerSharp" },
{ icon: IoGameController, name: "IoGameController" },
{ icon: IoGiftOutline, name: "IoGiftOutline" },
{ icon: IoGiftSharp, name: "IoGiftSharp" },
{ icon: IoGift, name: "IoGift" },
{ icon: IoGitBranchOutline, name: "IoGitBranchOutline" },
{ icon: IoGitBranchSharp, name: "IoGitBranchSharp" },
{ icon: IoGitBranch, name: "IoGitBranch" },
{ icon: IoGitCommitOutline, name: "IoGitCommitOutline" },
{ icon: IoGitCommitSharp, name: "IoGitCommitSharp" },
{ icon: IoGitCommit, name: "IoGitCommit" },
{ icon: IoGitCompareOutline, name: "IoGitCompareOutline" },
{ icon: IoGitCompareSharp, name: "IoGitCompareSharp" },
{ icon: IoGitCompare, name: "IoGitCompare" },
{ icon: IoGitMergeOutline, name: "IoGitMergeOutline" },
{ icon: IoGitMergeSharp, name: "IoGitMergeSharp" },
{ icon: IoGitMerge, name: "IoGitMerge" },
{ icon: IoGitNetworkOutline, name: "IoGitNetworkOutline" },
{ icon: IoGitNetworkSharp, name: "IoGitNetworkSharp" },
{ icon: IoGitNetwork, name: "IoGitNetwork" },
{ icon: IoGitPullRequestOutline, name: "IoGitPullRequestOutline" },
{ icon: IoGitPullRequestSharp, name: "IoGitPullRequestSharp" },
{ icon: IoGitPullRequest, name: "IoGitPullRequest" },
{ icon: IoGlassesOutline, name: "IoGlassesOutline" },
{ icon: IoGlassesSharp, name: "IoGlassesSharp" },
{ icon: IoGlasses, name: "IoGlasses" },
{ icon: IoGlobeOutline, name: "IoGlobeOutline" },
{ icon: IoGlobeSharp, name: "IoGlobeSharp" },
{ icon: IoGlobe, name: "IoGlobe" },
{ icon: IoGolfOutline, name: "IoGolfOutline" },
{ icon: IoGolfSharp, name: "IoGolfSharp" },
{ icon: IoGolf, name: "IoGolf" },
{ icon: IoGridOutline, name: "IoGridOutline" },
{ icon: IoGridSharp, name: "IoGridSharp" },
{ icon: IoGrid, name: "IoGrid" },
{ icon: IoHammerOutline, name: "IoHammerOutline" },
{ icon: IoHammerSharp, name: "IoHammerSharp" },
{ icon: IoHammer, name: "IoHammer" },
{ icon: IoHandLeftOutline, name: "IoHandLeftOutline" },
{ icon: IoHandLeftSharp, name: "IoHandLeftSharp" },
{ icon: IoHandLeft, name: "IoHandLeft" },
{ icon: IoHandRightOutline, name: "IoHandRightOutline" },
{ icon: IoHandRightSharp, name: "IoHandRightSharp" },
{ icon: IoHandRight, name: "IoHandRight" },
{ icon: IoHappyOutline, name: "IoHappyOutline" },
{ icon: IoHappySharp, name: "IoHappySharp" },
{ icon: IoHappy, name: "IoHappy" },
{ icon: IoHardwareChipOutline, name: "IoHardwareChipOutline" },
{ icon: IoHardwareChipSharp, name: "IoHardwareChipSharp" },
{ icon: IoHardwareChip, name: "IoHardwareChip" },
{ icon: IoHeadsetOutline, name: "IoHeadsetOutline" },
{ icon: IoHeadsetSharp, name: "IoHeadsetSharp" },
{ icon: IoHeadset, name: "IoHeadset" },
{ icon: IoHeartCircleOutline, name: "IoHeartCircleOutline" },
{ icon: IoHeartCircleSharp, name: "IoHeartCircleSharp" },
{ icon: IoHeartCircle, name: "IoHeartCircle" },
{ icon: IoHeartDislikeCircleOutline, name: "IoHeartDislikeCircleOutline" },
{ icon: IoHeartDislikeCircleSharp, name: "IoHeartDislikeCircleSharp" },
{ icon: IoHeartDislikeCircle, name: "IoHeartDislikeCircle" },
{ icon: IoHeartDislikeOutline, name: "IoHeartDislikeOutline" },
{ icon: IoHeartDislikeSharp, name: "IoHeartDislikeSharp" },
{ icon: IoHeartDislike, name: "IoHeartDislike" },
{ icon: IoHeartHalfOutline, name: "IoHeartHalfOutline" },
{ icon: IoHeartHalfSharp, name: "IoHeartHalfSharp" },
{ icon: IoHeartHalf, name: "IoHeartHalf" },
{ icon: IoHeartOutline, name: "IoHeartOutline" },
{ icon: IoHeartSharp, name: "IoHeartSharp" },
{ icon: IoHeart, name: "IoHeart" },
{ icon: IoHelpBuoyOutline, name: "IoHelpBuoyOutline" },
{ icon: IoHelpBuoySharp, name: "IoHelpBuoySharp" },
{ icon: IoHelpBuoy, name: "IoHelpBuoy" },
{ icon: IoHelpCircleOutline, name: "IoHelpCircleOutline" },
{ icon: IoHelpCircleSharp, name: "IoHelpCircleSharp" },
{ icon: IoHelpCircle, name: "IoHelpCircle" },
{ icon: IoHelpOutline, name: "IoHelpOutline" },
{ icon: IoHelpSharp, name: "IoHelpSharp" },
{ icon: IoHelp, name: "IoHelp" },
{ icon: IoHomeOutline, name: "IoHomeOutline" },
{ icon: IoHomeSharp, name: "IoHomeSharp" },
{ icon: IoHome, name: "IoHome" },
{ icon: IoHourglassOutline, name: "IoHourglassOutline" },
{ icon: IoHourglassSharp, name: "IoHourglassSharp" },
{ icon: IoHourglass, name: "IoHourglass" },
{ icon: IoIceCreamOutline, name: "IoIceCreamOutline" },
{ icon: IoIceCreamSharp, name: "IoIceCreamSharp" },
{ icon: IoIceCream, name: "IoIceCream" },
{ icon: IoIdCardOutline, name: "IoIdCardOutline" },
{ icon: IoIdCardSharp, name: "IoIdCardSharp" },
{ icon: IoIdCard, name: "IoIdCard" },
{ icon: IoImageOutline, name: "IoImageOutline" },
{ icon: IoImageSharp, name: "IoImageSharp" },
{ icon: IoImage, name: "IoImage" },
{ icon: IoImagesOutline, name: "IoImagesOutline" },
{ icon: IoImagesSharp, name: "IoImagesSharp" },
{ icon: IoImages, name: "IoImages" },
{ icon: IoInfiniteOutline, name: "IoInfiniteOutline" },
{ icon: IoInfiniteSharp, name: "IoInfiniteSharp" },
{ icon: IoInfinite, name: "IoInfinite" },
{ icon: IoInformationCircleOutline, name: "IoInformationCircleOutline" },
{ icon: IoInformationCircleSharp, name: "IoInformationCircleSharp" },
{ icon: IoInformationCircle, name: "IoInformationCircle" },
{ icon: IoInformationOutline, name: "IoInformationOutline" },
{ icon: IoInformationSharp, name: "IoInformationSharp" },
{ icon: IoInformation, name: "IoInformation" },
{ icon: IoInvertModeOutline, name: "IoInvertModeOutline" },
{ icon: IoInvertModeSharp, name: "IoInvertModeSharp" },
{ icon: IoInvertMode, name: "IoInvertMode" },
{ icon: IoJournalOutline, name: "IoJournalOutline" },
{ icon: IoJournalSharp, name: "IoJournalSharp" },
{ icon: IoJournal, name: "IoJournal" },
{ icon: IoKeyOutline, name: "IoKeyOutline" },
{ icon: IoKeySharp, name: "IoKeySharp" },
{ icon: IoKey, name: "IoKey" },
{ icon: IoKeypadOutline, name: "IoKeypadOutline" },
{ icon: IoKeypadSharp, name: "IoKeypadSharp" },
{ icon: IoKeypad, name: "IoKeypad" },
{ icon: IoLanguageOutline, name: "IoLanguageOutline" },
{ icon: IoLanguageSharp, name: "IoLanguageSharp" },
{ icon: IoLanguage, name: "IoLanguage" },
{ icon: IoLaptopOutline, name: "IoLaptopOutline" },
{ icon: IoLaptopSharp, name: "IoLaptopSharp" },
{ icon: IoLaptop, name: "IoLaptop" },
{ icon: IoLayersOutline, name: "IoLayersOutline" },
{ icon: IoLayersSharp, name: "IoLayersSharp" },
{ icon: IoLayers, name: "IoLayers" },
{ icon: IoLeafOutline, name: "IoLeafOutline" },
{ icon: IoLeafSharp, name: "IoLeafSharp" },
{ icon: IoLeaf, name: "IoLeaf" },
{ icon: IoLibraryOutline, name: "IoLibraryOutline" },
{ icon: IoLibrarySharp, name: "IoLibrarySharp" },
{ icon: IoLibrary, name: "IoLibrary" },
{ icon: IoLinkOutline, name: "IoLinkOutline" },
{ icon: IoLinkSharp, name: "IoLinkSharp" },
{ icon: IoLink, name: "IoLink" },
{ icon: IoListCircleOutline, name: "IoListCircleOutline" },
{ icon: IoListCircleSharp, name: "IoListCircleSharp" },
{ icon: IoListCircle, name: "IoListCircle" },
{ icon: IoListOutline, name: "IoListOutline" },
{ icon: IoListSharp, name: "IoListSharp" },
{ icon: IoList, name: "IoList" },
{ icon: IoLocateOutline, name: "IoLocateOutline" },
{ icon: IoLocateSharp, name: "IoLocateSharp" },
{ icon: IoLocate, name: "IoLocate" },
{ icon: IoLocationOutline, name: "IoLocationOutline" },
{ icon: IoLocationSharp, name: "IoLocationSharp" },
{ icon: IoLocation, name: "IoLocation" },
{ icon: IoLockClosedOutline, name: "IoLockClosedOutline" },
{ icon: IoLockClosedSharp, name: "IoLockClosedSharp" },
{ icon: IoLockClosed, name: "IoLockClosed" },
{ icon: IoLockOpenOutline, name: "IoLockOpenOutline" },
{ icon: IoLockOpenSharp, name: "IoLockOpenSharp" },
{ icon: IoLockOpen, name: "IoLockOpen" },
{ icon: IoLogInOutline, name: "IoLogInOutline" },
{ icon: IoLogInSharp, name: "IoLogInSharp" },
{ icon: IoLogIn, name: "IoLogIn" },
{ icon: IoLogOutOutline, name: "IoLogOutOutline" },
{ icon: IoLogOutSharp, name: "IoLogOutSharp" },
{ icon: IoLogOut, name: "IoLogOut" },
{ icon: IoLogoAlipay, name: "IoLogoAlipay" },
{ icon: IoLogoAmazon, name: "IoLogoAmazon" },
{ icon: IoLogoAmplify, name: "IoLogoAmplify" },
{ icon: IoLogoAndroid, name: "IoLogoAndroid" },
{ icon: IoLogoAngular, name: "IoLogoAngular" },
{ icon: IoLogoAppleAppstore, name: "IoLogoAppleAppstore" },
{ icon: IoLogoAppleAr, name: "IoLogoAppleAr" },
{ icon: IoLogoApple, name: "IoLogoApple" },
{ icon: IoLogoBehance, name: "IoLogoBehance" },
{ icon: IoLogoBitbucket, name: "IoLogoBitbucket" },
{ icon: IoLogoBitcoin, name: "IoLogoBitcoin" },
{ icon: IoLogoBuffer, name: "IoLogoBuffer" },
{ icon: IoLogoCapacitor, name: "IoLogoCapacitor" },
{ icon: IoLogoChrome, name: "IoLogoChrome" },
{ icon: IoLogoClosedCaptioning, name: "IoLogoClosedCaptioning" },
{ icon: IoLogoCodepen, name: "IoLogoCodepen" },
{ icon: IoLogoCss3, name: "IoLogoCss3" },
{ icon: IoLogoDesignernews, name: "IoLogoDesignernews" },
{ icon: IoLogoDeviantart, name: "IoLogoDeviantart" },
{ icon: IoLogoDiscord, name: "IoLogoDiscord" },
{ icon: IoLogoDocker, name: "IoLogoDocker" },
{ icon: IoLogoDribbble, name: "IoLogoDribbble" },
{ icon: IoLogoDropbox, name: "IoLogoDropbox" },
{ icon: IoLogoEdge, name: "IoLogoEdge" },
{ icon: IoLogoElectron, name: "IoLogoElectron" },
{ icon: IoLogoEuro, name: "IoLogoEuro" },
{ icon: IoLogoFacebook, name: "IoLogoFacebook" },
{ icon: IoLogoFigma, name: "IoLogoFigma" },
{ icon: IoLogoFirebase, name: "IoLogoFirebase" },
{ icon: IoLogoFirefox, name: "IoLogoFirefox" },
{ icon: IoLogoFlickr, name: "IoLogoFlickr" },
{ icon: IoLogoFoursquare, name: "IoLogoFoursquare" },
{ icon: IoLogoGithub, name: "IoLogoGithub" },
{ icon: IoLogoGitlab, name: "IoLogoGitlab" },
{ icon: IoLogoGooglePlaystore, name: "IoLogoGooglePlaystore" },
{ icon: IoLogoGoogle, name: "IoLogoGoogle" },
{ icon: IoLogoHackernews, name: "IoLogoHackernews" },
{ icon: IoLogoHtml5, name: "IoLogoHtml5" },
{ icon: IoLogoInstagram, name: "IoLogoInstagram" },
{ icon: IoLogoIonic, name: "IoLogoIonic" },
{ icon: IoLogoIonitron, name: "IoLogoIonitron" },
{ icon: IoLogoJavascript, name: "IoLogoJavascript" },
{ icon: IoLogoLaravel, name: "IoLogoLaravel" },
{ icon: IoLogoLinkedin, name: "IoLogoLinkedin" },
{ icon: IoLogoMarkdown, name: "IoLogoMarkdown" },
{ icon: IoLogoMastodon, name: "IoLogoMastodon" },
{ icon: IoLogoMedium, name: "IoLogoMedium" },
{ icon: IoLogoMicrosoft, name: "IoLogoMicrosoft" },
{ icon: IoLogoNoSmoking, name: "IoLogoNoSmoking" },
{ icon: IoLogoNodejs, name: "IoLogoNodejs" },
{ icon: IoLogoNpm, name: "IoLogoNpm" },
{ icon: IoLogoOctocat, name: "IoLogoOctocat" },
{ icon: IoLogoPaypal, name: "IoLogoPaypal" },
{ icon: IoLogoPinterest, name: "IoLogoPinterest" },
{ icon: IoLogoPlaystation, name: "IoLogoPlaystation" },
{ icon: IoLogoPwa, name: "IoLogoPwa" },
{ icon: IoLogoPython, name: "IoLogoPython" },
{ icon: IoLogoReact, name: "IoLogoReact" },
{ icon: IoLogoReddit, name: "IoLogoReddit" },
{ icon: IoLogoRss, name: "IoLogoRss" },
{ icon: IoLogoSass, name: "IoLogoSass" },
{ icon: IoLogoSkype, name: "IoLogoSkype" },
{ icon: IoLogoSlack, name: "IoLogoSlack" },
{ icon: IoLogoSnapchat, name: "IoLogoSnapchat" },
{ icon: IoLogoSoundcloud, name: "IoLogoSoundcloud" },
{ icon: IoLogoStackoverflow, name: "IoLogoStackoverflow" },
{ icon: IoLogoSteam, name: "IoLogoSteam" },
{ icon: IoLogoStencil, name: "IoLogoStencil" },
{ icon: IoLogoTableau, name: "IoLogoTableau" },
{ icon: IoLogoTiktok, name: "IoLogoTiktok" },
{ icon: IoLogoTumblr, name: "IoLogoTumblr" },
{ icon: IoLogoTux, name: "IoLogoTux" },
{ icon: IoLogoTwitch, name: "IoLogoTwitch" },
{ icon: IoLogoTwitter, name: "IoLogoTwitter" },
{ icon: IoLogoUsd, name: "IoLogoUsd" },
{ icon: IoLogoVenmo, name: "IoLogoVenmo" },
{ icon: IoLogoVercel, name: "IoLogoVercel" },
{ icon: IoLogoVimeo, name: "IoLogoVimeo" },
{ icon: IoLogoVk, name: "IoLogoVk" },
{ icon: IoLogoVue, name: "IoLogoVue" },
{ icon: IoLogoWebComponent, name: "IoLogoWebComponent" },
{ icon: IoLogoWechat, name: "IoLogoWechat" },
{ icon: IoLogoWhatsapp, name: "IoLogoWhatsapp" },
{ icon: IoLogoWindows, name: "IoLogoWindows" },
{ icon: IoLogoWordpress, name: "IoLogoWordpress" },
{ icon: IoLogoXbox, name: "IoLogoXbox" },
{ icon: IoLogoXing, name: "IoLogoXing" },
{ icon: IoLogoYahoo, name: "IoLogoYahoo" },
{ icon: IoLogoYen, name: "IoLogoYen" },
{ icon: IoLogoYoutube, name: "IoLogoYoutube" },
{ icon: IoMagnetOutline, name: "IoMagnetOutline" },
{ icon: IoMagnetSharp, name: "IoMagnetSharp" },
{ icon: IoMagnet, name: "IoMagnet" },
{ icon: IoMailOpenOutline, name: "IoMailOpenOutline" },
{ icon: IoMailOpenSharp, name: "IoMailOpenSharp" },
{ icon: IoMailOpen, name: "IoMailOpen" },
{ icon: IoMailOutline, name: "IoMailOutline" },
{ icon: IoMailSharp, name: "IoMailSharp" },
{ icon: IoMailUnreadOutline, name: "IoMailUnreadOutline" },
{ icon: IoMailUnreadSharp, name: "IoMailUnreadSharp" },
{ icon: IoMailUnread, name: "IoMailUnread" },
{ icon: IoMail, name: "IoMail" },
{ icon: IoMaleFemaleOutline, name: "IoMaleFemaleOutline" },
{ icon: IoMaleFemaleSharp, name: "IoMaleFemaleSharp" },
{ icon: IoMaleFemale, name: "IoMaleFemale" },
{ icon: IoMaleOutline, name: "IoMaleOutline" },
{ icon: IoMaleSharp, name: "IoMaleSharp" },
{ icon: IoMale, name: "IoMale" },
{ icon: IoManOutline, name: "IoManOutline" },
{ icon: IoManSharp, name: "IoManSharp" },
{ icon: IoMan, name: "IoMan" },
{ icon: IoMapOutline, name: "IoMapOutline" },
{ icon: IoMapSharp, name: "IoMapSharp" },
{ icon: IoMap, name: "IoMap" },
{ icon: IoMedalOutline, name: "IoMedalOutline" },
{ icon: IoMedalSharp, name: "IoMedalSharp" },
{ icon: IoMedal, name: "IoMedal" },
{ icon: IoMedicalOutline, name: "IoMedicalOutline" },
{ icon: IoMedicalSharp, name: "IoMedicalSharp" },
{ icon: IoMedical, name: "IoMedical" },
{ icon: IoMedkitOutline, name: "IoMedkitOutline" },
{ icon: IoMedkitSharp, name: "IoMedkitSharp" },
{ icon: IoMedkit, name: "IoMedkit" },
{ icon: IoMegaphoneOutline, name: "IoMegaphoneOutline" },
{ icon: IoMegaphoneSharp, name: "IoMegaphoneSharp" },
{ icon: IoMegaphone, name: "IoMegaphone" },
{ icon: IoMenuOutline, name: "IoMenuOutline" },
{ icon: IoMenuSharp, name: "IoMenuSharp" },
{ icon: IoMenu, name: "IoMenu" },
{ icon: IoMicCircleOutline, name: "IoMicCircleOutline" },
{ icon: IoMicCircleSharp, name: "IoMicCircleSharp" },
{ icon: IoMicCircle, name: "IoMicCircle" },
{ icon: IoMicOffCircleOutline, name: "IoMicOffCircleOutline" },
{ icon: IoMicOffCircleSharp, name: "IoMicOffCircleSharp" },
{ icon: IoMicOffCircle, name: "IoMicOffCircle" },
{ icon: IoMicOffOutline, name: "IoMicOffOutline" },
{ icon: IoMicOffSharp, name: "IoMicOffSharp" },
{ icon: IoMicOff, name: "IoMicOff" },
{ icon: IoMicOutline, name: "IoMicOutline" },
{ icon: IoMicSharp, name: "IoMicSharp" },
{ icon: IoMic, name: "IoMic" },
{ icon: IoMoonOutline, name: "IoMoonOutline" },
{ icon: IoMoonSharp, name: "IoMoonSharp" },
{ icon: IoMoon, name: "IoMoon" },
{ icon: IoMoveOutline, name: "IoMoveOutline" },
{ icon: IoMoveSharp, name: "IoMoveSharp" },
{ icon: IoMove, name: "IoMove" },
{ icon: IoMusicalNoteOutline, name: "IoMusicalNoteOutline" },
{ icon: IoMusicalNoteSharp, name: "IoMusicalNoteSharp" },
{ icon: IoMusicalNote, name: "IoMusicalNote" },
{ icon: IoMusicalNotesOutline, name: "IoMusicalNotesOutline" },
{ icon: IoMusicalNotesSharp, name: "IoMusicalNotesSharp" },
{ icon: IoMusicalNotes, name: "IoMusicalNotes" },
{ icon: IoNavigateCircleOutline, name: "IoNavigateCircleOutline" },
{ icon: IoNavigateCircleSharp, name: "IoNavigateCircleSharp" },
{ icon: IoNavigateCircle, name: "IoNavigateCircle" },
{ icon: IoNavigateOutline, name: "IoNavigateOutline" },
{ icon: IoNavigateSharp, name: "IoNavigateSharp" },
{ icon: IoNavigate, name: "IoNavigate" },
{ icon: IoNewspaperOutline, name: "IoNewspaperOutline" },
{ icon: IoNewspaperSharp, name: "IoNewspaperSharp" },
{ icon: IoNewspaper, name: "IoNewspaper" },
{ icon: IoNotificationsCircleOutline, name: "IoNotificationsCircleOutline" },
{ icon: IoNotificationsCircleSharp, name: "IoNotificationsCircleSharp" },
{ icon: IoNotificationsCircle, name: "IoNotificationsCircle" },
{ icon: IoNotificationsOffCircleOutline, name: "IoNotificationsOffCircleOutline" },
{ icon: IoNotificationsOffCircleSharp, name: "IoNotificationsOffCircleSharp" },
{ icon: IoNotificationsOffCircle, name: "IoNotificationsOffCircle" },
{ icon: IoNotificationsOffOutline, name: "IoNotificationsOffOutline" },
{ icon: IoNotificationsOffSharp, name: "IoNotificationsOffSharp" },
{ icon: IoNotificationsOff, name: "IoNotificationsOff" },
{ icon: IoNotificationsOutline, name: "IoNotificationsOutline" },
{ icon: IoNotificationsSharp, name: "IoNotificationsSharp" },
{ icon: IoNotifications, name: "IoNotifications" },
{ icon: IoNuclearOutline, name: "IoNuclearOutline" },
{ icon: IoNuclearSharp, name: "IoNuclearSharp" },
{ icon: IoNuclear, name: "IoNuclear" },
{ icon: IoNutritionOutline, name: "IoNutritionOutline" },
{ icon: IoNutritionSharp, name: "IoNutritionSharp" },
{ icon: IoNutrition, name: "IoNutrition" },
{ icon: IoOpenOutline, name: "IoOpenOutline" },
{ icon: IoOpenSharp, name: "IoOpenSharp" },
{ icon: IoOpen, name: "IoOpen" },
{ icon: IoOptionsOutline, name: "IoOptionsOutline" },
{ icon: IoOptionsSharp, name: "IoOptionsSharp" },
{ icon: IoOptions, name: "IoOptions" },
{ icon: IoPaperPlaneOutline, name: "IoPaperPlaneOutline" },
{ icon: IoPaperPlaneSharp, name: "IoPaperPlaneSharp" },
{ icon: IoPaperPlane, name: "IoPaperPlane" },
{ icon: IoPartlySunnyOutline, name: "IoPartlySunnyOutline" },
{ icon: IoPartlySunnySharp, name: "IoPartlySunnySharp" },
{ icon: IoPartlySunny, name: "IoPartlySunny" },
{ icon: IoPauseCircleOutline, name: "IoPauseCircleOutline" },
{ icon: IoPauseCircleSharp, name: "IoPauseCircleSharp" },
{ icon: IoPauseCircle, name: "IoPauseCircle" },
{ icon: IoPauseOutline, name: "IoPauseOutline" },
{ icon: IoPauseSharp, name: "IoPauseSharp" },
{ icon: IoPause, name: "IoPause" },
{ icon: IoPawOutline, name: "IoPawOutline" },
{ icon: IoPawSharp, name: "IoPawSharp" },
{ icon: IoPaw, name: "IoPaw" },
{ icon: IoPencilOutline, name: "IoPencilOutline" },
{ icon: IoPencilSharp, name: "IoPencilSharp" },
{ icon: IoPencil, name: "IoPencil" },
{ icon: IoPeopleCircleOutline, name: "IoPeopleCircleOutline" },
{ icon: IoPeopleCircleSharp, name: "IoPeopleCircleSharp" },
{ icon: IoPeopleCircle, name: "IoPeopleCircle" },
{ icon: IoPeopleOutline, name: "IoPeopleOutline" },
{ icon: IoPeopleSharp, name: "IoPeopleSharp" },
{ icon: IoPeople, name: "IoPeople" },
{ icon: IoPersonAddOutline, name: "IoPersonAddOutline" },
{ icon: IoPersonAddSharp, name: "IoPersonAddSharp" },
{ icon: IoPersonAdd, name: "IoPersonAdd" },
{ icon: IoPersonCircleOutline, name: "IoPersonCircleOutline" },
{ icon: IoPersonCircleSharp, name: "IoPersonCircleSharp" },
{ icon: IoPersonCircle, name: "IoPersonCircle" },
{ icon: IoPersonOutline, name: "IoPersonOutline" },
{ icon: IoPersonRemoveOutline, name: "IoPersonRemoveOutline" },
{ icon: IoPersonRemoveSharp, name: "IoPersonRemoveSharp" },
{ icon: IoPersonRemove, name: "IoPersonRemove" },
{ icon: IoPersonSharp, name: "IoPersonSharp" },
{ icon: IoPerson, name: "IoPerson" },
{ icon: IoPhoneLandscapeOutline, name: "IoPhoneLandscapeOutline" },
{ icon: IoPhoneLandscapeSharp, name: "IoPhoneLandscapeSharp" },
{ icon: IoPhoneLandscape, name: "IoPhoneLandscape" },
{ icon: IoPhonePortraitOutline, name: "IoPhonePortraitOutline" },
{ icon: IoPhonePortraitSharp, name: "IoPhonePortraitSharp" },
{ icon: IoPhonePortrait, name: "IoPhonePortrait" },
{ icon: IoPieChartOutline, name: "IoPieChartOutline" },
{ icon: IoPieChartSharp, name: "IoPieChartSharp" },
{ icon: IoPieChart, name: "IoPieChart" },
{ icon: IoPinOutline, name: "IoPinOutline" },
{ icon: IoPinSharp, name: "IoPinSharp" },
{ icon: IoPin, name: "IoPin" },
{ icon: IoPintOutline, name: "IoPintOutline" },
{ icon: IoPintSharp, name: "IoPintSharp" },
{ icon: IoPint, name: "IoPint" },
{ icon: IoPizzaOutline, name: "IoPizzaOutline" },
{ icon: IoPizzaSharp, name: "IoPizzaSharp" },
{ icon: IoPizza, name: "IoPizza" },
{ icon: IoPlanetOutline, name: "IoPlanetOutline" },
{ icon: IoPlanetSharp, name: "IoPlanetSharp" },
{ icon: IoPlanet, name: "IoPlanet" },
{ icon: IoPlayBackCircleOutline, name: "IoPlayBackCircleOutline" },
{ icon: IoPlayBackCircleSharp, name: "IoPlayBackCircleSharp" },
{ icon: IoPlayBackCircle, name: "IoPlayBackCircle" },
{ icon: IoPlayBackOutline, name: "IoPlayBackOutline" },
{ icon: IoPlayBackSharp, name: "IoPlayBackSharp" },
{ icon: IoPlayBack, name: "IoPlayBack" },
{ icon: IoPlayCircleOutline, name: "IoPlayCircleOutline" },
{ icon: IoPlayCircleSharp, name: "IoPlayCircleSharp" },
{ icon: IoPlayCircle, name: "IoPlayCircle" },
{ icon: IoPlayForwardCircleOutline, name: "IoPlayForwardCircleOutline" },
{ icon: IoPlayForwardCircleSharp, name: "IoPlayForwardCircleSharp" },
{ icon: IoPlayForwardCircle, name: "IoPlayForwardCircle" },
{ icon: IoPlayForwardOutline, name: "IoPlayForwardOutline" },
{ icon: IoPlayForwardSharp, name: "IoPlayForwardSharp" },
{ icon: IoPlayForward, name: "IoPlayForward" },
{ icon: IoPlayOutline, name: "IoPlayOutline" },
{ icon: IoPlaySharp, name: "IoPlaySharp" },
{ icon: IoPlaySkipBackCircleOutline, name: "IoPlaySkipBackCircleOutline" },
{ icon: IoPlaySkipBackCircleSharp, name: "IoPlaySkipBackCircleSharp" },
{ icon: IoPlaySkipBackCircle, name: "IoPlaySkipBackCircle" },
{ icon: IoPlaySkipBackOutline, name: "IoPlaySkipBackOutline" },
{ icon: IoPlaySkipBackSharp, name: "IoPlaySkipBackSharp" },
{ icon: IoPlaySkipBack, name: "IoPlaySkipBack" },
{ icon: IoPlaySkipForwardCircleOutline, name: "IoPlaySkipForwardCircleOutline" },
{ icon: IoPlaySkipForwardCircleSharp, name: "IoPlaySkipForwardCircleSharp" },
{ icon: IoPlaySkipForwardCircle, name: "IoPlaySkipForwardCircle" },
{ icon: IoPlaySkipForwardOutline, name: "IoPlaySkipForwardOutline" },
{ icon: IoPlaySkipForwardSharp, name: "IoPlaySkipForwardSharp" },
{ icon: IoPlaySkipForward, name: "IoPlaySkipForward" },
{ icon: IoPlay, name: "IoPlay" },
{ icon: IoPodiumOutline, name: "IoPodiumOutline" },
{ icon: IoPodiumSharp, name: "IoPodiumSharp" },
{ icon: IoPodium, name: "IoPodium" },
{ icon: IoPowerOutline, name: "IoPowerOutline" },
{ icon: IoPowerSharp, name: "IoPowerSharp" },
{ icon: IoPower, name: "IoPower" },
{ icon: IoPricetagOutline, name: "IoPricetagOutline" },
{ icon: IoPricetagSharp, name: "IoPricetagSharp" },
{ icon: IoPricetag, name: "IoPricetag" },
{ icon: IoPricetagsOutline, name: "IoPricetagsOutline" },
{ icon: IoPricetagsSharp, name: "IoPricetagsSharp" },
{ icon: IoPricetags, name: "IoPricetags" },
{ icon: IoPrintOutline, name: "IoPrintOutline" },
{ icon: IoPrintSharp, name: "IoPrintSharp" },
{ icon: IoPrint, name: "IoPrint" },
{ icon: IoPrismOutline, name: "IoPrismOutline" },
{ icon: IoPrismSharp, name: "IoPrismSharp" },
{ icon: IoPrism, name: "IoPrism" },
{ icon: IoPulseOutline, name: "IoPulseOutline" },
{ icon: IoPulseSharp, name: "IoPulseSharp" },
{ icon: IoPulse, name: "IoPulse" },
{ icon: IoPushOutline, name: "IoPushOutline" },
{ icon: IoPushSharp, name: "IoPushSharp" },
{ icon: IoPush, name: "IoPush" },
{ icon: IoQrCodeOutline, name: "IoQrCodeOutline" },
{ icon: IoQrCodeSharp, name: "IoQrCodeSharp" },
{ icon: IoQrCode, name: "IoQrCode" },
{ icon: IoRadioButtonOffOutline, name: "IoRadioButtonOffOutline" },
{ icon: IoRadioButtonOffSharp, name: "IoRadioButtonOffSharp" },
{ icon: IoRadioButtonOff, name: "IoRadioButtonOff" },
{ icon: IoRadioButtonOnOutline, name: "IoRadioButtonOnOutline" },
{ icon: IoRadioButtonOnSharp, name: "IoRadioButtonOnSharp" },
{ icon: IoRadioButtonOn, name: "IoRadioButtonOn" },
{ icon: IoRadioOutline, name: "IoRadioOutline" },
{ icon: IoRadioSharp, name: "IoRadioSharp" },
{ icon: IoRadio, name: "IoRadio" },
{ icon: IoRainyOutline, name: "IoRainyOutline" },
{ icon: IoRainySharp, name: "IoRainySharp" },
{ icon: IoRainy, name: "IoRainy" },
{ icon: IoReaderOutline, name: "IoReaderOutline" },
{ icon: IoReaderSharp, name: "IoReaderSharp" },
{ icon: IoReader, name: "IoReader" },
{ icon: IoReceiptOutline, name: "IoReceiptOutline" },
{ icon: IoReceiptSharp, name: "IoReceiptSharp" },
{ icon: IoReceipt, name: "IoReceipt" },
{ icon: IoRecordingOutline, name: "IoRecordingOutline" },
{ icon: IoRecordingSharp, name: "IoRecordingSharp" },
{ icon: IoRecording, name: "IoRecording" },
{ icon: IoRefreshCircleOutline, name: "IoRefreshCircleOutline" },
{ icon: IoRefreshCircleSharp, name: "IoRefreshCircleSharp" },
{ icon: IoRefreshCircle, name: "IoRefreshCircle" },
{ icon: IoRefreshOutline, name: "IoRefreshOutline" },
{ icon: IoRefreshSharp, name: "IoRefreshSharp" },
{ icon: IoRefresh, name: "IoRefresh" },
{ icon: IoReloadCircleOutline, name: "IoReloadCircleOutline" },
{ icon: IoReloadCircleSharp, name: "IoReloadCircleSharp" },
{ icon: IoReloadCircle, name: "IoReloadCircle" },
{ icon: IoReloadOutline, name: "IoReloadOutline" },
{ icon: IoReloadSharp, name: "IoReloadSharp" },
{ icon: IoReload, name: "IoReload" },
{ icon: IoRemoveCircleOutline, name: "IoRemoveCircleOutline" },
{ icon: IoRemoveCircleSharp, name: "IoRemoveCircleSharp" },
{ icon: IoRemoveCircle, name: "IoRemoveCircle" },
{ icon: IoRemoveOutline, name: "IoRemoveOutline" },
{ icon: IoRemoveSharp, name: "IoRemoveSharp" },
{ icon: IoRemove, name: "IoRemove" },
{ icon: IoReorderFourOutline, name: "IoReorderFourOutline" },
{ icon: IoReorderFourSharp, name: "IoReorderFourSharp" },
{ icon: IoReorderFour, name: "IoReorderFour" },
{ icon: IoReorderThreeOutline, name: "IoReorderThreeOutline" },
{ icon: IoReorderThreeSharp, name: "IoReorderThreeSharp" },
{ icon: IoReorderThree, name: "IoReorderThree" },
{ icon: IoReorderTwoOutline, name: "IoReorderTwoOutline" },
{ icon: IoReorderTwoSharp, name: "IoReorderTwoSharp" },
{ icon: IoReorderTwo, name: "IoReorderTwo" },
{ icon: IoRepeatOutline, name: "IoRepeatOutline" },
{ icon: IoRepeatSharp, name: "IoRepeatSharp" },
{ icon: IoRepeat, name: "IoRepeat" },
{ icon: IoResizeOutline, name: "IoResizeOutline" },
{ icon: IoResizeSharp, name: "IoResizeSharp" },
{ icon: IoResize, name: "IoResize" },
{ icon: IoRestaurantOutline, name: "IoRestaurantOutline" },
{ icon: IoRestaurantSharp, name: "IoRestaurantSharp" },
{ icon: IoRestaurant, name: "IoRestaurant" },
{ icon: IoReturnDownBackOutline, name: "IoReturnDownBackOutline" },
{ icon: IoReturnDownBackSharp, name: "IoReturnDownBackSharp" },
{ icon: IoReturnDownBack, name: "IoReturnDownBack" },
{ icon: IoReturnDownForwardOutline, name: "IoReturnDownForwardOutline" },
{ icon: IoReturnDownForwardSharp, name: "IoReturnDownForwardSharp" },
{ icon: IoReturnDownForward, name: "IoReturnDownForward" },
{ icon: IoReturnUpBackOutline, name: "IoReturnUpBackOutline" },
{ icon: IoReturnUpBackSharp, name: "IoReturnUpBackSharp" },
{ icon: IoReturnUpBack, name: "IoReturnUpBack" },
{ icon: IoReturnUpForwardOutline, name: "IoReturnUpForwardOutline" },
{ icon: IoReturnUpForwardSharp, name: "IoReturnUpForwardSharp" },
{ icon: IoReturnUpForward, name: "IoReturnUpForward" },
{ icon: IoRibbonOutline, name: "IoRibbonOutline" },
{ icon: IoRibbonSharp, name: "IoRibbonSharp" },
{ icon: IoRibbon, name: "IoRibbon" },
{ icon: IoRocketOutline, name: "IoRocketOutline" },
{ icon: IoRocketSharp, name: "IoRocketSharp" },
{ icon: IoRocket, name: "IoRocket" },
{ icon: IoRoseOutline, name: "IoRoseOutline" },
{ icon: IoRoseSharp, name: "IoRoseSharp" },
{ icon: IoRose, name: "IoRose" },
{ icon: IoSadOutline, name: "IoSadOutline" },
{ icon: IoSadSharp, name: "IoSadSharp" },
{ icon: IoSad, name: "IoSad" },
{ icon: IoSaveOutline, name: "IoSaveOutline" },
{ icon: IoSaveSharp, name: "IoSaveSharp" },
{ icon: IoSave, name: "IoSave" },
{ icon: IoScaleOutline, name: "IoScaleOutline" },
{ icon: IoScaleSharp, name: "IoScaleSharp" },
{ icon: IoScale, name: "IoScale" },
{ icon: IoScanCircleOutline, name: "IoScanCircleOutline" },
{ icon: IoScanCircleSharp, name: "IoScanCircleSharp" },
{ icon: IoScanCircle, name: "IoScanCircle" },
{ icon: IoScanOutline, name: "IoScanOutline" },
{ icon: IoScanSharp, name: "IoScanSharp" },
{ icon: IoScan, name: "IoScan" },
{ icon: IoSchoolOutline, name: "IoSchoolOutline" },
{ icon: IoSchoolSharp, name: "IoSchoolSharp" },
{ icon: IoSchool, name: "IoSchool" },
{ icon: IoSearchCircleOutline, name: "IoSearchCircleOutline" },
{ icon: IoSearchCircleSharp, name: "IoSearchCircleSharp" },
{ icon: IoSearchCircle, name: "IoSearchCircle" },
{ icon: IoSearchOutline, name: "IoSearchOutline" },
{ icon: IoSearchSharp, name: "IoSearchSharp" },
{ icon: IoSearch, name: "IoSearch" },
{ icon: IoSendOutline, name: "IoSendOutline" },
{ icon: IoSendSharp, name: "IoSendSharp" },
{ icon: IoSend, name: "IoSend" },
{ icon: IoServerOutline, name: "IoServerOutline" },
{ icon: IoServerSharp, name: "IoServerSharp" },
{ icon: IoServer, name: "IoServer" },
{ icon: IoSettingsOutline, name: "IoSettingsOutline" },
{ icon: IoSettingsSharp, name: "IoSettingsSharp" },
{ icon: IoSettings, name: "IoSettings" },
{ icon: IoShapesOutline, name: "IoShapesOutline" },
{ icon: IoShapesSharp, name: "IoShapesSharp" },
{ icon: IoShapes, name: "IoShapes" },
{ icon: IoShareOutline, name: "IoShareOutline" },
{ icon: IoShareSharp, name: "IoShareSharp" },
{ icon: IoShareSocialOutline, name: "IoShareSocialOutline" },
{ icon: IoShareSocialSharp, name: "IoShareSocialSharp" },
{ icon: IoShareSocial, name: "IoShareSocial" },
{ icon: IoShare, name: "IoShare" },
{ icon: IoShieldCheckmarkOutline, name: "IoShieldCheckmarkOutline" },
{ icon: IoShieldCheckmarkSharp, name: "IoShieldCheckmarkSharp" },
{ icon: IoShieldCheckmark, name: "IoShieldCheckmark" },
{ icon: IoShieldHalfOutline, name: "IoShieldHalfOutline" },
{ icon: IoShieldHalfSharp, name: "IoShieldHalfSharp" },
{ icon: IoShieldHalf, name: "IoShieldHalf" },
{ icon: IoShieldOutline, name: "IoShieldOutline" },
{ icon: IoShieldSharp, name: "IoShieldSharp" },
{ icon: IoShield, name: "IoShield" },
{ icon: IoShirtOutline, name: "IoShirtOutline" },
{ icon: IoShirtSharp, name: "IoShirtSharp" },
{ icon: IoShirt, name: "IoShirt" },
{ icon: IoShuffleOutline, name: "IoShuffleOutline" },
{ icon: IoShuffleSharp, name: "IoShuffleSharp" },
{ icon: IoShuffle, name: "IoShuffle" },
{ icon: IoSkullOutline, name: "IoSkullOutline" },
{ icon: IoSkullSharp, name: "IoSkullSharp" },
{ icon: IoSkull, name: "IoSkull" },
{ icon: IoSnowOutline, name: "IoSnowOutline" },
{ icon: IoSnowSharp, name: "IoSnowSharp" },
{ icon: IoSnow, name: "IoSnow" },
{ icon: IoSparklesOutline, name: "IoSparklesOutline" },
{ icon: IoSparklesSharp, name: "IoSparklesSharp" },
{ icon: IoSparkles, name: "IoSparkles" },
{ icon: IoSpeedometerOutline, name: "IoSpeedometerOutline" },
{ icon: IoSpeedometerSharp, name: "IoSpeedometerSharp" },
{ icon: IoSpeedometer, name: "IoSpeedometer" },
{ icon: IoSquareOutline, name: "IoSquareOutline" },
{ icon: IoSquareSharp, name: "IoSquareSharp" },
{ icon: IoSquare, name: "IoSquare" },
{ icon: IoStarHalfOutline, name: "IoStarHalfOutline" },
{ icon: IoStarHalfSharp, name: "IoStarHalfSharp" },
{ icon: IoStarHalf, name: "IoStarHalf" },
{ icon: IoStarOutline, name: "IoStarOutline" },
{ icon: IoStarSharp, name: "IoStarSharp" },
{ icon: IoStar, name: "IoStar" },
{ icon: IoStatsChartOutline, name: "IoStatsChartOutline" },
{ icon: IoStatsChartSharp, name: "IoStatsChartSharp" },
{ icon: IoStatsChart, name: "IoStatsChart" },
{ icon: IoStopCircleOutline, name: "IoStopCircleOutline" },
{ icon: IoStopCircleSharp, name: "IoStopCircleSharp" },
{ icon: IoStopCircle, name: "IoStopCircle" },
{ icon: IoStopOutline, name: "IoStopOutline" },
{ icon: IoStopSharp, name: "IoStopSharp" },
{ icon: IoStop, name: "IoStop" },
{ icon: IoStopwatchOutline, name: "IoStopwatchOutline" },
{ icon: IoStopwatchSharp, name: "IoStopwatchSharp" },
{ icon: IoStopwatch, name: "IoStopwatch" },
{ icon: IoStorefrontOutline, name: "IoStorefrontOutline" },
{ icon: IoStorefrontSharp, name: "IoStorefrontSharp" },
{ icon: IoStorefront, name: "IoStorefront" },
{ icon: IoSubwayOutline, name: "IoSubwayOutline" },
{ icon: IoSubwaySharp, name: "IoSubwaySharp" },
{ icon: IoSubway, name: "IoSubway" },
{ icon: IoSunnyOutline, name: "IoSunnyOutline" },
{ icon: IoSunnySharp, name: "IoSunnySharp" },
{ icon: IoSunny, name: "IoSunny" },
{ icon: IoSwapHorizontalOutline, name: "IoSwapHorizontalOutline" },
{ icon: IoSwapHorizontalSharp, name: "IoSwapHorizontalSharp" },
{ icon: IoSwapHorizontal, name: "IoSwapHorizontal" },
{ icon: IoSwapVerticalOutline, name: "IoSwapVerticalOutline" },
{ icon: IoSwapVerticalSharp, name: "IoSwapVerticalSharp" },
{ icon: IoSwapVertical, name: "IoSwapVertical" },
{ icon: IoSyncCircleOutline, name: "IoSyncCircleOutline" },
{ icon: IoSyncCircleSharp, name: "IoSyncCircleSharp" },
{ icon: IoSyncCircle, name: "IoSyncCircle" },
{ icon: IoSyncOutline, name: "IoSyncOutline" },
{ icon: IoSyncSharp, name: "IoSyncSharp" },
{ icon: IoSync, name: "IoSync" },
{ icon: IoTabletLandscapeOutline, name: "IoTabletLandscapeOutline" },
{ icon: IoTabletLandscapeSharp, name: "IoTabletLandscapeSharp" },
{ icon: IoTabletLandscape, name: "IoTabletLandscape" },
{ icon: IoTabletPortraitOutline, name: "IoTabletPortraitOutline" },
{ icon: IoTabletPortraitSharp, name: "IoTabletPortraitSharp" },
{ icon: IoTabletPortrait, name: "IoTabletPortrait" },
{ icon: IoTelescopeOutline, name: "IoTelescopeOutline" },
{ icon: IoTelescopeSharp, name: "IoTelescopeSharp" },
{ icon: IoTelescope, name: "IoTelescope" },
{ icon: IoTennisballOutline, name: "IoTennisballOutline" },
{ icon: IoTennisballSharp, name: "IoTennisballSharp" },
{ icon: IoTennisball, name: "IoTennisball" },
{ icon: IoTerminalOutline, name: "IoTerminalOutline" },
{ icon: IoTerminalSharp, name: "IoTerminalSharp" },
{ icon: IoTerminal, name: "IoTerminal" },
{ icon: IoTextOutline, name: "IoTextOutline" },
{ icon: IoTextSharp, name: "IoTextSharp" },
{ icon: IoText, name: "IoText" },
{ icon: IoThermometerOutline, name: "IoThermometerOutline" },
{ icon: IoThermometerSharp, name: "IoThermometerSharp" },
{ icon: IoThermometer, name: "IoThermometer" },
{ icon: IoThumbsDownOutline, name: "IoThumbsDownOutline" },
{ icon: IoThumbsDownSharp, name: "IoThumbsDownSharp" },
{ icon: IoThumbsDown, name: "IoThumbsDown" },
{ icon: IoThumbsUpOutline, name: "IoThumbsUpOutline" },
{ icon: IoThumbsUpSharp, name: "IoThumbsUpSharp" },
{ icon: IoThumbsUp, name: "IoThumbsUp" },
{ icon: IoThunderstormOutline, name: "IoThunderstormOutline" },
{ icon: IoThunderstormSharp, name: "IoThunderstormSharp" },
{ icon: IoThunderstorm, name: "IoThunderstorm" },
{ icon: IoTicketOutline, name: "IoTicketOutline" },
{ icon: IoTicketSharp, name: "IoTicketSharp" },
{ icon: IoTicket, name: "IoTicket" },
{ icon: IoTimeOutline, name: "IoTimeOutline" },
{ icon: IoTimeSharp, name: "IoTimeSharp" },
{ icon: IoTime, name: "IoTime" },
{ icon: IoTimerOutline, name: "IoTimerOutline" },
{ icon: IoTimerSharp, name: "IoTimerSharp" },
{ icon: IoTimer, name: "IoTimer" },
{ icon: IoTodayOutline, name: "IoTodayOutline" },
{ icon: IoTodaySharp, name: "IoTodaySharp" },
{ icon: IoToday, name: "IoToday" },
{ icon: IoToggleOutline, name: "IoToggleOutline" },
{ icon: IoToggleSharp, name: "IoToggleSharp" },
{ icon: IoToggle, name: "IoToggle" },
{ icon: IoTrailSignOutline, name: "IoTrailSignOutline" },
{ icon: IoTrailSignSharp, name: "IoTrailSignSharp" },
{ icon: IoTrailSign, name: "IoTrailSign" },
{ icon: IoTrainOutline, name: "IoTrainOutline" },
{ icon: IoTrainSharp, name: "IoTrainSharp" },
{ icon: IoTrain, name: "IoTrain" },
{ icon: IoTransgenderOutline, name: "IoTransgenderOutline" },
{ icon: IoTransgenderSharp, name: "IoTransgenderSharp" },
{ icon: IoTransgender, name: "IoTransgender" },
{ icon: IoTrashBinOutline, name: "IoTrashBinOutline" },
{ icon: IoTrashBinSharp, name: "IoTrashBinSharp" },
{ icon: IoTrashBin, name: "IoTrashBin" },
{ icon: IoTrashOutline, name: "IoTrashOutline" },
{ icon: IoTrashSharp, name: "IoTrashSharp" },
{ icon: IoTrash, name: "IoTrash" },
{ icon: IoTrendingDownOutline, name: "IoTrendingDownOutline" },
{ icon: IoTrendingDownSharp, name: "IoTrendingDownSharp" },
{ icon: IoTrendingDown, name: "IoTrendingDown" },
{ icon: IoTrendingUpOutline, name: "IoTrendingUpOutline" },
{ icon: IoTrendingUpSharp, name: "IoTrendingUpSharp" },
{ icon: IoTrendingUp, name: "IoTrendingUp" },
{ icon: IoTriangleOutline, name: "IoTriangleOutline" },
{ icon: IoTriangleSharp, name: "IoTriangleSharp" },
{ icon: IoTriangle, name: "IoTriangle" },
{ icon: IoTrophyOutline, name: "IoTrophyOutline" },
{ icon: IoTrophySharp, name: "IoTrophySharp" },
{ icon: IoTrophy, name: "IoTrophy" },
{ icon: IoTvOutline, name: "IoTvOutline" },
{ icon: IoTvSharp, name: "IoTvSharp" },
{ icon: IoTv, name: "IoTv" },
{ icon: IoUmbrellaOutline, name: "IoUmbrellaOutline" },
{ icon: IoUmbrellaSharp, name: "IoUmbrellaSharp" },
{ icon: IoUmbrella, name: "IoUmbrella" },
{ icon: IoUnlinkOutline, name: "IoUnlinkOutline" },
{ icon: IoUnlinkSharp, name: "IoUnlinkSharp" },
{ icon: IoUnlink, name: "IoUnlink" },
{ icon: IoVideocamOffOutline, name: "IoVideocamOffOutline" },
{ icon: IoVideocamOffSharp, name: "IoVideocamOffSharp" },
{ icon: IoVideocamOff, name: "IoVideocamOff" },
{ icon: IoVideocamOutline, name: "IoVideocamOutline" },
{ icon: IoVideocamSharp, name: "IoVideocamSharp" },
{ icon: IoVideocam, name: "IoVideocam" },
{ icon: IoVolumeHighOutline, name: "IoVolumeHighOutline" },
{ icon: IoVolumeHighSharp, name: "IoVolumeHighSharp" },
{ icon: IoVolumeHigh, name: "IoVolumeHigh" },
{ icon: IoVolumeLowOutline, name: "IoVolumeLowOutline" },
{ icon: IoVolumeLowSharp, name: "IoVolumeLowSharp" },
{ icon: IoVolumeLow, name: "IoVolumeLow" },
{ icon: IoVolumeMediumOutline, name: "IoVolumeMediumOutline" },
{ icon: IoVolumeMediumSharp, name: "IoVolumeMediumSharp" },
{ icon: IoVolumeMedium, name: "IoVolumeMedium" },
{ icon: IoVolumeMuteOutline, name: "IoVolumeMuteOutline" },
{ icon: IoVolumeMuteSharp, name: "IoVolumeMuteSharp" },
{ icon: IoVolumeMute, name: "IoVolumeMute" },
{ icon: IoVolumeOffOutline, name: "IoVolumeOffOutline" },
{ icon: IoVolumeOffSharp, name: "IoVolumeOffSharp" },
{ icon: IoVolumeOff, name: "IoVolumeOff" },
{ icon: IoWalkOutline, name: "IoWalkOutline" },
{ icon: IoWalkSharp, name: "IoWalkSharp" },
{ icon: IoWalk, name: "IoWalk" },
{ icon: IoWalletOutline, name: "IoWalletOutline" },
{ icon: IoWalletSharp, name: "IoWalletSharp" },
{ icon: IoWallet, name: "IoWallet" },
{ icon: IoWarningOutline, name: "IoWarningOutline" },
{ icon: IoWarningSharp, name: "IoWarningSharp" },
{ icon: IoWarning, name: "IoWarning" },
{ icon: IoWatchOutline, name: "IoWatchOutline" },
{ icon: IoWatchSharp, name: "IoWatchSharp" },
{ icon: IoWatch, name: "IoWatch" },
{ icon: IoWaterOutline, name: "IoWaterOutline" },
{ icon: IoWaterSharp, name: "IoWaterSharp" },
{ icon: IoWater, name: "IoWater" },
{ icon: IoWifiOutline, name: "IoWifiOutline" },
{ icon: IoWifiSharp, name: "IoWifiSharp" },
{ icon: IoWifi, name: "IoWifi" },
{ icon: IoWineOutline, name: "IoWineOutline" },
{ icon: IoWineSharp, name: "IoWineSharp" },
{ icon: IoWine, name: "IoWine" },
{ icon: IoWomanOutline, name: "IoWomanOutline" },
{ icon: IoWomanSharp, name: "IoWomanSharp" },
{ icon: IoWoman, name: "IoWoman" },
];

export default result