import {
WiAlien,
WiBarometer,
WiCelsius,
WiCloudDown,
WiCloudRefresh,
WiCloudUp,
WiCloud,
WiCloudyGusts,
WiCloudyWindy,
WiCloudy,
WiDayCloudyGusts,
WiDayCloudyHigh,
WiDayCloudyWindy,
WiDayCloudy,
WiDayFog,
WiDayHail,
WiDayHaze,
WiDayLightWind,
WiDayLightning,
WiDayRainMix,
WiDayRainWind,
WiDayRain,
WiDayShowers,
WiDaySleetStorm,
WiDaySleet,
WiDaySnowThunderstorm,
WiDaySnowWind,
WiDaySnow,
WiDaySprinkle,
WiDayStormShowers,
WiDaySunnyOvercast,
WiDaySunny,
WiDayThunderstorm,
WiDayWindy,
WiDegrees,
WiDirectionDownLeft,
WiDirectionDownRight,
WiDirectionDown,
WiDirectionLeft,
WiDirectionRight,
WiDirectionUpLeft,
WiDirectionUpRight,
WiDirectionUp,
WiDust,
WiEarthquake,
WiFahrenheit,
WiFire,
WiFlood,
WiFog,
WiGaleWarning,
WiHail,
WiHorizonAlt,
WiHorizon,
WiHot,
WiHumidity,
WiHurricaneWarning,
WiHurricane,
WiLightning,
WiLunarEclipse,
WiMeteor,
WiMoonAltFirstQuarter,
WiMoonAltFull,
WiMoonAltNew,
WiMoonAltThirdQuarter,
WiMoonAltWaningCrescent1,
WiMoonAltWaningCrescent2,
WiMoonAltWaningCrescent3,
WiMoonAltWaningCrescent4,
WiMoonAltWaningCrescent5,
WiMoonAltWaningCrescent6,
WiMoonAltWaningGibbous1,
WiMoonAltWaningGibbous2,
WiMoonAltWaningGibbous3,
WiMoonAltWaningGibbous4,
WiMoonAltWaningGibbous5,
WiMoonAltWaningGibbous6,
WiMoonAltWaxingCrescent1,
WiMoonAltWaxingCrescent2,
WiMoonAltWaxingCrescent3,
WiMoonAltWaxingCrescent4,
WiMoonAltWaxingCrescent5,
WiMoonAltWaxingCrescent6,
WiMoonAltWaxingGibbous1,
WiMoonAltWaxingGibbous2,
WiMoonAltWaxingGibbous3,
WiMoonAltWaxingGibbous4,
WiMoonAltWaxingGibbous5,
WiMoonAltWaxingGibbous6,
WiMoonFirstQuarter,
WiMoonFull,
WiMoonNew,
WiMoonThirdQuarter,
WiMoonWaningCrescent1,
WiMoonWaningCrescent2,
WiMoonWaningCrescent3,
WiMoonWaningCrescent4,
WiMoonWaningCrescent5,
WiMoonWaningCrescent6,
WiMoonWaningGibbous1,
WiMoonWaningGibbous2,
WiMoonWaningGibbous3,
WiMoonWaningGibbous4,
WiMoonWaningGibbous5,
WiMoonWaningGibbous6,
WiMoonWaxing6,
WiMoonWaxingCrescent1,
WiMoonWaxingCrescent2,
WiMoonWaxingCrescent3,
WiMoonWaxingCrescent4,
WiMoonWaxingCrescent5,
WiMoonWaxingGibbous1,
WiMoonWaxingGibbous2,
WiMoonWaxingGibbous3,
WiMoonWaxingGibbous4,
WiMoonWaxingGibbous5,
WiMoonWaxingGibbous6,
WiMoonrise,
WiMoonset,
WiNa,
WiNightAltCloudyGusts,
WiNightAltCloudyHigh,
WiNightAltCloudyWindy,
WiNightAltCloudy,
WiNightAltHail,
WiNightAltLightning,
WiNightAltPartlyCloudy,
WiNightAltRainMix,
WiNightAltRainWind,
WiNightAltRain,
WiNightAltShowers,
WiNightAltSleetStorm,
WiNightAltSleet,
WiNightAltSnowThunderstorm,
WiNightAltSnowWind,
WiNightAltSnow,
WiNightAltSprinkle,
WiNightAltStormShowers,
WiNightAltThunderstorm,
WiNightClear,
WiNightCloudyGusts,
WiNightCloudyHigh,
WiNightCloudyWindy,
WiNightCloudy,
WiNightFog,
WiNightHail,
WiNightLightning,
WiNightPartlyCloudy,
WiNightRainMix,
WiNightRainWind,
WiNightRain,
WiNightShowers,
WiNightSleetStorm,
WiNightSleet,
WiNightSnowThunderstorm,
WiNightSnowWind,
WiNightSnow,
WiNightSprinkle,
WiNightStormShowers,
WiNightThunderstorm,
WiRainMix,
WiRainWind,
WiRain,
WiRaindrop,
WiRaindrops,
WiRefreshAlt,
WiRefresh,
WiSandstorm,
WiShowers,
WiSleet,
WiSmallCraftAdvisory,
WiSmog,
WiSmoke,
WiSnowWind,
WiSnow,
WiSnowflakeCold,
WiSolarEclipse,
WiSprinkle,
WiStars,
WiStormShowers,
WiStormWarning,
WiStrongWind,
WiSunrise,
WiSunset,
WiThermometerExterior,
WiThermometerInternal,
WiThermometer,
WiThunderstorm,
WiTime1,
WiTime10,
WiTime11,
WiTime12,
WiTime2,
WiTime3,
WiTime4,
WiTime5,
WiTime6,
WiTime7,
WiTime8,
WiTime9,
WiTornado,
WiTrain,
WiTsunami,
WiUmbrella,
WiVolcano,
WiWindBeaufort0,
WiWindBeaufort1,
WiWindBeaufort10,
WiWindBeaufort11,
WiWindBeaufort12,
WiWindBeaufort2,
WiWindBeaufort3,
WiWindBeaufort4,
WiWindBeaufort5,
WiWindBeaufort6,
WiWindBeaufort7,
WiWindBeaufort8,
WiWindBeaufort9,
WiWindDeg,
WiWindy,
} from "react-icons/wi";

const result = [
{ icon: WiAlien, name: "WiAlien" },
{ icon: WiBarometer, name: "WiBarometer" },
{ icon: WiCelsius, name: "WiCelsius" },
{ icon: WiCloudDown, name: "WiCloudDown" },
{ icon: WiCloudRefresh, name: "WiCloudRefresh" },
{ icon: WiCloudUp, name: "WiCloudUp" },
{ icon: WiCloud, name: "WiCloud" },
{ icon: WiCloudyGusts, name: "WiCloudyGusts" },
{ icon: WiCloudyWindy, name: "WiCloudyWindy" },
{ icon: WiCloudy, name: "WiCloudy" },
{ icon: WiDayCloudyGusts, name: "WiDayCloudyGusts" },
{ icon: WiDayCloudyHigh, name: "WiDayCloudyHigh" },
{ icon: WiDayCloudyWindy, name: "WiDayCloudyWindy" },
{ icon: WiDayCloudy, name: "WiDayCloudy" },
{ icon: WiDayFog, name: "WiDayFog" },
{ icon: WiDayHail, name: "WiDayHail" },
{ icon: WiDayHaze, name: "WiDayHaze" },
{ icon: WiDayLightWind, name: "WiDayLightWind" },
{ icon: WiDayLightning, name: "WiDayLightning" },
{ icon: WiDayRainMix, name: "WiDayRainMix" },
{ icon: WiDayRainWind, name: "WiDayRainWind" },
{ icon: WiDayRain, name: "WiDayRain" },
{ icon: WiDayShowers, name: "WiDayShowers" },
{ icon: WiDaySleetStorm, name: "WiDaySleetStorm" },
{ icon: WiDaySleet, name: "WiDaySleet" },
{ icon: WiDaySnowThunderstorm, name: "WiDaySnowThunderstorm" },
{ icon: WiDaySnowWind, name: "WiDaySnowWind" },
{ icon: WiDaySnow, name: "WiDaySnow" },
{ icon: WiDaySprinkle, name: "WiDaySprinkle" },
{ icon: WiDayStormShowers, name: "WiDayStormShowers" },
{ icon: WiDaySunnyOvercast, name: "WiDaySunnyOvercast" },
{ icon: WiDaySunny, name: "WiDaySunny" },
{ icon: WiDayThunderstorm, name: "WiDayThunderstorm" },
{ icon: WiDayWindy, name: "WiDayWindy" },
{ icon: WiDegrees, name: "WiDegrees" },
{ icon: WiDirectionDownLeft, name: "WiDirectionDownLeft" },
{ icon: WiDirectionDownRight, name: "WiDirectionDownRight" },
{ icon: WiDirectionDown, name: "WiDirectionDown" },
{ icon: WiDirectionLeft, name: "WiDirectionLeft" },
{ icon: WiDirectionRight, name: "WiDirectionRight" },
{ icon: WiDirectionUpLeft, name: "WiDirectionUpLeft" },
{ icon: WiDirectionUpRight, name: "WiDirectionUpRight" },
{ icon: WiDirectionUp, name: "WiDirectionUp" },
{ icon: WiDust, name: "WiDust" },
{ icon: WiEarthquake, name: "WiEarthquake" },
{ icon: WiFahrenheit, name: "WiFahrenheit" },
{ icon: WiFire, name: "WiFire" },
{ icon: WiFlood, name: "WiFlood" },
{ icon: WiFog, name: "WiFog" },
{ icon: WiGaleWarning, name: "WiGaleWarning" },
{ icon: WiHail, name: "WiHail" },
{ icon: WiHorizonAlt, name: "WiHorizonAlt" },
{ icon: WiHorizon, name: "WiHorizon" },
{ icon: WiHot, name: "WiHot" },
{ icon: WiHumidity, name: "WiHumidity" },
{ icon: WiHurricaneWarning, name: "WiHurricaneWarning" },
{ icon: WiHurricane, name: "WiHurricane" },
{ icon: WiLightning, name: "WiLightning" },
{ icon: WiLunarEclipse, name: "WiLunarEclipse" },
{ icon: WiMeteor, name: "WiMeteor" },
{ icon: WiMoonAltFirstQuarter, name: "WiMoonAltFirstQuarter" },
{ icon: WiMoonAltFull, name: "WiMoonAltFull" },
{ icon: WiMoonAltNew, name: "WiMoonAltNew" },
{ icon: WiMoonAltThirdQuarter, name: "WiMoonAltThirdQuarter" },
{ icon: WiMoonAltWaningCrescent1, name: "WiMoonAltWaningCrescent1" },
{ icon: WiMoonAltWaningCrescent2, name: "WiMoonAltWaningCrescent2" },
{ icon: WiMoonAltWaningCrescent3, name: "WiMoonAltWaningCrescent3" },
{ icon: WiMoonAltWaningCrescent4, name: "WiMoonAltWaningCrescent4" },
{ icon: WiMoonAltWaningCrescent5, name: "WiMoonAltWaningCrescent5" },
{ icon: WiMoonAltWaningCrescent6, name: "WiMoonAltWaningCrescent6" },
{ icon: WiMoonAltWaningGibbous1, name: "WiMoonAltWaningGibbous1" },
{ icon: WiMoonAltWaningGibbous2, name: "WiMoonAltWaningGibbous2" },
{ icon: WiMoonAltWaningGibbous3, name: "WiMoonAltWaningGibbous3" },
{ icon: WiMoonAltWaningGibbous4, name: "WiMoonAltWaningGibbous4" },
{ icon: WiMoonAltWaningGibbous5, name: "WiMoonAltWaningGibbous5" },
{ icon: WiMoonAltWaningGibbous6, name: "WiMoonAltWaningGibbous6" },
{ icon: WiMoonAltWaxingCrescent1, name: "WiMoonAltWaxingCrescent1" },
{ icon: WiMoonAltWaxingCrescent2, name: "WiMoonAltWaxingCrescent2" },
{ icon: WiMoonAltWaxingCrescent3, name: "WiMoonAltWaxingCrescent3" },
{ icon: WiMoonAltWaxingCrescent4, name: "WiMoonAltWaxingCrescent4" },
{ icon: WiMoonAltWaxingCrescent5, name: "WiMoonAltWaxingCrescent5" },
{ icon: WiMoonAltWaxingCrescent6, name: "WiMoonAltWaxingCrescent6" },
{ icon: WiMoonAltWaxingGibbous1, name: "WiMoonAltWaxingGibbous1" },
{ icon: WiMoonAltWaxingGibbous2, name: "WiMoonAltWaxingGibbous2" },
{ icon: WiMoonAltWaxingGibbous3, name: "WiMoonAltWaxingGibbous3" },
{ icon: WiMoonAltWaxingGibbous4, name: "WiMoonAltWaxingGibbous4" },
{ icon: WiMoonAltWaxingGibbous5, name: "WiMoonAltWaxingGibbous5" },
{ icon: WiMoonAltWaxingGibbous6, name: "WiMoonAltWaxingGibbous6" },
{ icon: WiMoonFirstQuarter, name: "WiMoonFirstQuarter" },
{ icon: WiMoonFull, name: "WiMoonFull" },
{ icon: WiMoonNew, name: "WiMoonNew" },
{ icon: WiMoonThirdQuarter, name: "WiMoonThirdQuarter" },
{ icon: WiMoonWaningCrescent1, name: "WiMoonWaningCrescent1" },
{ icon: WiMoonWaningCrescent2, name: "WiMoonWaningCrescent2" },
{ icon: WiMoonWaningCrescent3, name: "WiMoonWaningCrescent3" },
{ icon: WiMoonWaningCrescent4, name: "WiMoonWaningCrescent4" },
{ icon: WiMoonWaningCrescent5, name: "WiMoonWaningCrescent5" },
{ icon: WiMoonWaningCrescent6, name: "WiMoonWaningCrescent6" },
{ icon: WiMoonWaningGibbous1, name: "WiMoonWaningGibbous1" },
{ icon: WiMoonWaningGibbous2, name: "WiMoonWaningGibbous2" },
{ icon: WiMoonWaningGibbous3, name: "WiMoonWaningGibbous3" },
{ icon: WiMoonWaningGibbous4, name: "WiMoonWaningGibbous4" },
{ icon: WiMoonWaningGibbous5, name: "WiMoonWaningGibbous5" },
{ icon: WiMoonWaningGibbous6, name: "WiMoonWaningGibbous6" },
{ icon: WiMoonWaxing6, name: "WiMoonWaxing6" },
{ icon: WiMoonWaxingCrescent1, name: "WiMoonWaxingCrescent1" },
{ icon: WiMoonWaxingCrescent2, name: "WiMoonWaxingCrescent2" },
{ icon: WiMoonWaxingCrescent3, name: "WiMoonWaxingCrescent3" },
{ icon: WiMoonWaxingCrescent4, name: "WiMoonWaxingCrescent4" },
{ icon: WiMoonWaxingCrescent5, name: "WiMoonWaxingCrescent5" },
{ icon: WiMoonWaxingGibbous1, name: "WiMoonWaxingGibbous1" },
{ icon: WiMoonWaxingGibbous2, name: "WiMoonWaxingGibbous2" },
{ icon: WiMoonWaxingGibbous3, name: "WiMoonWaxingGibbous3" },
{ icon: WiMoonWaxingGibbous4, name: "WiMoonWaxingGibbous4" },
{ icon: WiMoonWaxingGibbous5, name: "WiMoonWaxingGibbous5" },
{ icon: WiMoonWaxingGibbous6, name: "WiMoonWaxingGibbous6" },
{ icon: WiMoonrise, name: "WiMoonrise" },
{ icon: WiMoonset, name: "WiMoonset" },
{ icon: WiNa, name: "WiNa" },
{ icon: WiNightAltCloudyGusts, name: "WiNightAltCloudyGusts" },
{ icon: WiNightAltCloudyHigh, name: "WiNightAltCloudyHigh" },
{ icon: WiNightAltCloudyWindy, name: "WiNightAltCloudyWindy" },
{ icon: WiNightAltCloudy, name: "WiNightAltCloudy" },
{ icon: WiNightAltHail, name: "WiNightAltHail" },
{ icon: WiNightAltLightning, name: "WiNightAltLightning" },
{ icon: WiNightAltPartlyCloudy, name: "WiNightAltPartlyCloudy" },
{ icon: WiNightAltRainMix, name: "WiNightAltRainMix" },
{ icon: WiNightAltRainWind, name: "WiNightAltRainWind" },
{ icon: WiNightAltRain, name: "WiNightAltRain" },
{ icon: WiNightAltShowers, name: "WiNightAltShowers" },
{ icon: WiNightAltSleetStorm, name: "WiNightAltSleetStorm" },
{ icon: WiNightAltSleet, name: "WiNightAltSleet" },
{ icon: WiNightAltSnowThunderstorm, name: "WiNightAltSnowThunderstorm" },
{ icon: WiNightAltSnowWind, name: "WiNightAltSnowWind" },
{ icon: WiNightAltSnow, name: "WiNightAltSnow" },
{ icon: WiNightAltSprinkle, name: "WiNightAltSprinkle" },
{ icon: WiNightAltStormShowers, name: "WiNightAltStormShowers" },
{ icon: WiNightAltThunderstorm, name: "WiNightAltThunderstorm" },
{ icon: WiNightClear, name: "WiNightClear" },
{ icon: WiNightCloudyGusts, name: "WiNightCloudyGusts" },
{ icon: WiNightCloudyHigh, name: "WiNightCloudyHigh" },
{ icon: WiNightCloudyWindy, name: "WiNightCloudyWindy" },
{ icon: WiNightCloudy, name: "WiNightCloudy" },
{ icon: WiNightFog, name: "WiNightFog" },
{ icon: WiNightHail, name: "WiNightHail" },
{ icon: WiNightLightning, name: "WiNightLightning" },
{ icon: WiNightPartlyCloudy, name: "WiNightPartlyCloudy" },
{ icon: WiNightRainMix, name: "WiNightRainMix" },
{ icon: WiNightRainWind, name: "WiNightRainWind" },
{ icon: WiNightRain, name: "WiNightRain" },
{ icon: WiNightShowers, name: "WiNightShowers" },
{ icon: WiNightSleetStorm, name: "WiNightSleetStorm" },
{ icon: WiNightSleet, name: "WiNightSleet" },
{ icon: WiNightSnowThunderstorm, name: "WiNightSnowThunderstorm" },
{ icon: WiNightSnowWind, name: "WiNightSnowWind" },
{ icon: WiNightSnow, name: "WiNightSnow" },
{ icon: WiNightSprinkle, name: "WiNightSprinkle" },
{ icon: WiNightStormShowers, name: "WiNightStormShowers" },
{ icon: WiNightThunderstorm, name: "WiNightThunderstorm" },
{ icon: WiRainMix, name: "WiRainMix" },
{ icon: WiRainWind, name: "WiRainWind" },
{ icon: WiRain, name: "WiRain" },
{ icon: WiRaindrop, name: "WiRaindrop" },
{ icon: WiRaindrops, name: "WiRaindrops" },
{ icon: WiRefreshAlt, name: "WiRefreshAlt" },
{ icon: WiRefresh, name: "WiRefresh" },
{ icon: WiSandstorm, name: "WiSandstorm" },
{ icon: WiShowers, name: "WiShowers" },
{ icon: WiSleet, name: "WiSleet" },
{ icon: WiSmallCraftAdvisory, name: "WiSmallCraftAdvisory" },
{ icon: WiSmog, name: "WiSmog" },
{ icon: WiSmoke, name: "WiSmoke" },
{ icon: WiSnowWind, name: "WiSnowWind" },
{ icon: WiSnow, name: "WiSnow" },
{ icon: WiSnowflakeCold, name: "WiSnowflakeCold" },
{ icon: WiSolarEclipse, name: "WiSolarEclipse" },
{ icon: WiSprinkle, name: "WiSprinkle" },
{ icon: WiStars, name: "WiStars" },
{ icon: WiStormShowers, name: "WiStormShowers" },
{ icon: WiStormWarning, name: "WiStormWarning" },
{ icon: WiStrongWind, name: "WiStrongWind" },
{ icon: WiSunrise, name: "WiSunrise" },
{ icon: WiSunset, name: "WiSunset" },
{ icon: WiThermometerExterior, name: "WiThermometerExterior" },
{ icon: WiThermometerInternal, name: "WiThermometerInternal" },
{ icon: WiThermometer, name: "WiThermometer" },
{ icon: WiThunderstorm, name: "WiThunderstorm" },
{ icon: WiTime1, name: "WiTime1" },
{ icon: WiTime10, name: "WiTime10" },
{ icon: WiTime11, name: "WiTime11" },
{ icon: WiTime12, name: "WiTime12" },
{ icon: WiTime2, name: "WiTime2" },
{ icon: WiTime3, name: "WiTime3" },
{ icon: WiTime4, name: "WiTime4" },
{ icon: WiTime5, name: "WiTime5" },
{ icon: WiTime6, name: "WiTime6" },
{ icon: WiTime7, name: "WiTime7" },
{ icon: WiTime8, name: "WiTime8" },
{ icon: WiTime9, name: "WiTime9" },
{ icon: WiTornado, name: "WiTornado" },
{ icon: WiTrain, name: "WiTrain" },
{ icon: WiTsunami, name: "WiTsunami" },
{ icon: WiUmbrella, name: "WiUmbrella" },
{ icon: WiVolcano, name: "WiVolcano" },
{ icon: WiWindBeaufort0, name: "WiWindBeaufort0" },
{ icon: WiWindBeaufort1, name: "WiWindBeaufort1" },
{ icon: WiWindBeaufort10, name: "WiWindBeaufort10" },
{ icon: WiWindBeaufort11, name: "WiWindBeaufort11" },
{ icon: WiWindBeaufort12, name: "WiWindBeaufort12" },
{ icon: WiWindBeaufort2, name: "WiWindBeaufort2" },
{ icon: WiWindBeaufort3, name: "WiWindBeaufort3" },
{ icon: WiWindBeaufort4, name: "WiWindBeaufort4" },
{ icon: WiWindBeaufort5, name: "WiWindBeaufort5" },
{ icon: WiWindBeaufort6, name: "WiWindBeaufort6" },
{ icon: WiWindBeaufort7, name: "WiWindBeaufort7" },
{ icon: WiWindBeaufort8, name: "WiWindBeaufort8" },
{ icon: WiWindBeaufort9, name: "WiWindBeaufort9" },
{ icon: WiWindDeg, name: "WiWindDeg" },
{ icon: WiWindy, name: "WiWindy" },
];

export default result