import {
	WiAlien,
	WiBarometer,
	WiCelsius,
	WiCloudDown,
	WiCloudRefresh,
	WiCloudUp,
	WiCloud,
	WiCloudyGusts,
	WiCloudyWindy,
	WiCloudy,
	WiDayCloudyGusts,
	WiDayCloudyHigh,
	WiDayCloudyWindy,
	WiDayCloudy,
	WiDayFog,
	WiDayHail,
	WiDayHaze,
	WiDayLightWind,
	WiDayLightning,
	WiDayRainMix,
	WiDayRainWind,
	WiDayRain,
	WiDayShowers,
	WiDaySleetStorm,
	WiDaySleet,
	WiDaySnowThunderstorm,
	WiDaySnowWind,
	WiDaySnow,
	WiDaySprinkle,
	WiDayStormShowers,
	WiDaySunnyOvercast,
	WiDaySunny,
	WiDayThunderstorm,
	WiDayWindy,
	WiDegrees,
	WiDirectionDownLeft,
	WiDirectionDownRight,
	WiDirectionDown,
	WiDirectionLeft,
	WiDirectionRight,
	WiDirectionUpLeft,
	WiDirectionUpRight,
	WiDirectionUp,
	WiDust,
	WiEarthquake,
	WiFahrenheit,
	WiFire,
	WiFlood,
	WiFog,
	WiGaleWarning,
	WiHail,
	WiHorizonAlt,
	WiHorizon,
	WiHot,
	WiHumidity,
	WiHurricaneWarning,
	WiHurricane,
	WiLightning,
	WiLunarEclipse,
	WiMeteor,
	WiMoonAltFirstQuarter,
	WiMoonAltFull,
	WiMoonAltNew,
	WiMoonAltThirdQuarter,
	WiMoonAltWaningCrescent1,
	WiMoonAltWaningCrescent2,
	WiMoonAltWaningCrescent3,
	WiMoonAltWaningCrescent4,
	WiMoonAltWaningCrescent5,
	WiMoonAltWaningCrescent6,
	WiMoonAltWaningGibbous1,
	WiMoonAltWaningGibbous2,
	WiMoonAltWaningGibbous3,
	WiMoonAltWaningGibbous4,
	WiMoonAltWaningGibbous5,
	WiMoonAltWaningGibbous6,
	WiMoonAltWaxingCrescent1,
	WiMoonAltWaxingCrescent2,
	WiMoonAltWaxingCrescent3,
	WiMoonAltWaxingCrescent4,
	WiMoonAltWaxingCrescent5,
	WiMoonAltWaxingCrescent6,
	WiMoonAltWaxingGibbous1,
	WiMoonAltWaxingGibbous2,
	WiMoonAltWaxingGibbous3,
	WiMoonAltWaxingGibbous4,
	WiMoonAltWaxingGibbous5,
	WiMoonAltWaxingGibbous6,
	WiMoonFirstQuarter,
	WiMoonFull,
	WiMoonNew,
	WiMoonThirdQuarter,
	WiMoonWaningCrescent1,
	WiMoonWaningCrescent2,
	WiMoonWaningCrescent3,
	WiMoonWaningCrescent4,
	WiMoonWaningCrescent5,
	WiMoonWaningCrescent6,
	WiMoonWaningGibbous1,
	WiMoonWaningGibbous2,
	WiMoonWaningGibbous3,
	WiMoonWaningGibbous4,
	WiMoonWaningGibbous5,
	WiMoonWaningGibbous6,
	WiMoonWaxing6,
	WiMoonWaxingCrescent1,
	WiMoonWaxingCrescent2,
	WiMoonWaxingCrescent3,
	WiMoonWaxingCrescent4,
	WiMoonWaxingCrescent5,
	WiMoonWaxingGibbous1,
	WiMoonWaxingGibbous2,
	WiMoonWaxingGibbous3,
	WiMoonWaxingGibbous4,
	WiMoonWaxingGibbous5,
	WiMoonWaxingGibbous6,
	WiMoonrise,
	WiMoonset,
	WiNa,
	WiNightAltCloudyGusts,
	WiNightAltCloudyHigh,
	WiNightAltCloudyWindy,
	WiNightAltCloudy,
	WiNightAltHail,
	WiNightAltLightning,
	WiNightAltPartlyCloudy,
	WiNightAltRainMix,
	WiNightAltRainWind,
	WiNightAltRain,
	WiNightAltShowers,
	WiNightAltSleetStorm,
	WiNightAltSleet,
	WiNightAltSnowThunderstorm,
	WiNightAltSnowWind,
	WiNightAltSnow,
	WiNightAltSprinkle,
	WiNightAltStormShowers,
	WiNightAltThunderstorm,
	WiNightClear,
	WiNightCloudyGusts,
	WiNightCloudyHigh,
	WiNightCloudyWindy,
	WiNightCloudy,
	WiNightFog,
	WiNightHail,
	WiNightLightning,
	WiNightPartlyCloudy,
	WiNightRainMix,
	WiNightRainWind,
	WiNightRain,
	WiNightShowers,
	WiNightSleetStorm,
	WiNightSleet,
	WiNightSnowThunderstorm,
	WiNightSnowWind,
	WiNightSnow,
	WiNightSprinkle,
	WiNightStormShowers,
	WiNightThunderstorm,
	WiRainMix,
	WiRainWind,
	WiRain,
	WiRaindrop,
	WiRaindrops,
	WiRefreshAlt,
	WiRefresh,
	WiSandstorm,
	WiShowers,
	WiSleet,
	WiSmallCraftAdvisory,
	WiSmog,
	WiSmoke,
	WiSnowWind,
	WiSnow,
	WiSnowflakeCold,
	WiSolarEclipse,
	WiSprinkle,
	WiStars,
	WiStormShowers,
	WiStormWarning,
	WiStrongWind,
	WiSunrise,
	WiSunset,
	WiThermometerExterior,
	WiThermometerInternal,
	WiThermometer,
	WiThunderstorm,
	WiTime1,
	WiTime10,
	WiTime11,
	WiTime12,
	WiTime2,
	WiTime3,
	WiTime4,
	WiTime5,
	WiTime6,
	WiTime7,
	WiTime8,
	WiTime9,
	WiTornado,
	WiTrain,
	WiTsunami,
	WiUmbrella,
	WiVolcano,
	WiWindBeaufort0,
	WiWindBeaufort1,
	WiWindBeaufort10,
	WiWindBeaufort11,
	WiWindBeaufort12,
	WiWindBeaufort2,
	WiWindBeaufort3,
	WiWindBeaufort4,
	WiWindBeaufort5,
	WiWindBeaufort6,
	WiWindBeaufort7,
	WiWindBeaufort8,
	WiWindBeaufort9,
	WiWindDeg,
	WiWindy,
} from "react-icons/wi";

const result = [
	{ icon: WiAlien, name: "WiAlien", library: "wi" },
	{ icon: WiBarometer, name: "WiBarometer", library: "wi" },
	{ icon: WiCelsius, name: "WiCelsius", library: "wi" },
	{ icon: WiCloudDown, name: "WiCloudDown", library: "wi" },
	{ icon: WiCloudRefresh, name: "WiCloudRefresh", library: "wi" },
	{ icon: WiCloudUp, name: "WiCloudUp", library: "wi" },
	{ icon: WiCloud, name: "WiCloud", library: "wi" },
	{ icon: WiCloudyGusts, name: "WiCloudyGusts", library: "wi" },
	{ icon: WiCloudyWindy, name: "WiCloudyWindy", library: "wi" },
	{ icon: WiCloudy, name: "WiCloudy", library: "wi" },
	{ icon: WiDayCloudyGusts, name: "WiDayCloudyGusts", library: "wi" },
	{ icon: WiDayCloudyHigh, name: "WiDayCloudyHigh", library: "wi" },
	{ icon: WiDayCloudyWindy, name: "WiDayCloudyWindy", library: "wi" },
	{ icon: WiDayCloudy, name: "WiDayCloudy", library: "wi" },
	{ icon: WiDayFog, name: "WiDayFog", library: "wi" },
	{ icon: WiDayHail, name: "WiDayHail", library: "wi" },
	{ icon: WiDayHaze, name: "WiDayHaze", library: "wi" },
	{ icon: WiDayLightWind, name: "WiDayLightWind", library: "wi" },
	{ icon: WiDayLightning, name: "WiDayLightning", library: "wi" },
	{ icon: WiDayRainMix, name: "WiDayRainMix", library: "wi" },
	{ icon: WiDayRainWind, name: "WiDayRainWind", library: "wi" },
	{ icon: WiDayRain, name: "WiDayRain", library: "wi" },
	{ icon: WiDayShowers, name: "WiDayShowers", library: "wi" },
	{ icon: WiDaySleetStorm, name: "WiDaySleetStorm", library: "wi" },
	{ icon: WiDaySleet, name: "WiDaySleet", library: "wi" },
	{ icon: WiDaySnowThunderstorm, name: "WiDaySnowThunderstorm", library: "wi" },
	{ icon: WiDaySnowWind, name: "WiDaySnowWind", library: "wi" },
	{ icon: WiDaySnow, name: "WiDaySnow", library: "wi" },
	{ icon: WiDaySprinkle, name: "WiDaySprinkle", library: "wi" },
	{ icon: WiDayStormShowers, name: "WiDayStormShowers", library: "wi" },
	{ icon: WiDaySunnyOvercast, name: "WiDaySunnyOvercast", library: "wi" },
	{ icon: WiDaySunny, name: "WiDaySunny", library: "wi" },
	{ icon: WiDayThunderstorm, name: "WiDayThunderstorm", library: "wi" },
	{ icon: WiDayWindy, name: "WiDayWindy", library: "wi" },
	{ icon: WiDegrees, name: "WiDegrees", library: "wi" },
	{ icon: WiDirectionDownLeft, name: "WiDirectionDownLeft", library: "wi" },
	{ icon: WiDirectionDownRight, name: "WiDirectionDownRight", library: "wi" },
	{ icon: WiDirectionDown, name: "WiDirectionDown", library: "wi" },
	{ icon: WiDirectionLeft, name: "WiDirectionLeft", library: "wi" },
	{ icon: WiDirectionRight, name: "WiDirectionRight", library: "wi" },
	{ icon: WiDirectionUpLeft, name: "WiDirectionUpLeft", library: "wi" },
	{ icon: WiDirectionUpRight, name: "WiDirectionUpRight", library: "wi" },
	{ icon: WiDirectionUp, name: "WiDirectionUp", library: "wi" },
	{ icon: WiDust, name: "WiDust", library: "wi" },
	{ icon: WiEarthquake, name: "WiEarthquake", library: "wi" },
	{ icon: WiFahrenheit, name: "WiFahrenheit", library: "wi" },
	{ icon: WiFire, name: "WiFire", library: "wi" },
	{ icon: WiFlood, name: "WiFlood", library: "wi" },
	{ icon: WiFog, name: "WiFog", library: "wi" },
	{ icon: WiGaleWarning, name: "WiGaleWarning", library: "wi" },
	{ icon: WiHail, name: "WiHail", library: "wi" },
	{ icon: WiHorizonAlt, name: "WiHorizonAlt", library: "wi" },
	{ icon: WiHorizon, name: "WiHorizon", library: "wi" },
	{ icon: WiHot, name: "WiHot", library: "wi" },
	{ icon: WiHumidity, name: "WiHumidity", library: "wi" },
	{ icon: WiHurricaneWarning, name: "WiHurricaneWarning", library: "wi" },
	{ icon: WiHurricane, name: "WiHurricane", library: "wi" },
	{ icon: WiLightning, name: "WiLightning", library: "wi" },
	{ icon: WiLunarEclipse, name: "WiLunarEclipse", library: "wi" },
	{ icon: WiMeteor, name: "WiMeteor", library: "wi" },
	{ icon: WiMoonAltFirstQuarter, name: "WiMoonAltFirstQuarter", library: "wi" },
	{ icon: WiMoonAltFull, name: "WiMoonAltFull", library: "wi" },
	{ icon: WiMoonAltNew, name: "WiMoonAltNew", library: "wi" },
	{ icon: WiMoonAltThirdQuarter, name: "WiMoonAltThirdQuarter", library: "wi" },
	{ icon: WiMoonAltWaningCrescent1, name: "WiMoonAltWaningCrescent1", library: "wi" },
	{ icon: WiMoonAltWaningCrescent2, name: "WiMoonAltWaningCrescent2", library: "wi" },
	{ icon: WiMoonAltWaningCrescent3, name: "WiMoonAltWaningCrescent3", library: "wi" },
	{ icon: WiMoonAltWaningCrescent4, name: "WiMoonAltWaningCrescent4", library: "wi" },
	{ icon: WiMoonAltWaningCrescent5, name: "WiMoonAltWaningCrescent5", library: "wi" },
	{ icon: WiMoonAltWaningCrescent6, name: "WiMoonAltWaningCrescent6", library: "wi" },
	{ icon: WiMoonAltWaningGibbous1, name: "WiMoonAltWaningGibbous1", library: "wi" },
	{ icon: WiMoonAltWaningGibbous2, name: "WiMoonAltWaningGibbous2", library: "wi" },
	{ icon: WiMoonAltWaningGibbous3, name: "WiMoonAltWaningGibbous3", library: "wi" },
	{ icon: WiMoonAltWaningGibbous4, name: "WiMoonAltWaningGibbous4", library: "wi" },
	{ icon: WiMoonAltWaningGibbous5, name: "WiMoonAltWaningGibbous5", library: "wi" },
	{ icon: WiMoonAltWaningGibbous6, name: "WiMoonAltWaningGibbous6", library: "wi" },
	{ icon: WiMoonAltWaxingCrescent1, name: "WiMoonAltWaxingCrescent1", library: "wi" },
	{ icon: WiMoonAltWaxingCrescent2, name: "WiMoonAltWaxingCrescent2", library: "wi" },
	{ icon: WiMoonAltWaxingCrescent3, name: "WiMoonAltWaxingCrescent3", library: "wi" },
	{ icon: WiMoonAltWaxingCrescent4, name: "WiMoonAltWaxingCrescent4", library: "wi" },
	{ icon: WiMoonAltWaxingCrescent5, name: "WiMoonAltWaxingCrescent5", library: "wi" },
	{ icon: WiMoonAltWaxingCrescent6, name: "WiMoonAltWaxingCrescent6", library: "wi" },
	{ icon: WiMoonAltWaxingGibbous1, name: "WiMoonAltWaxingGibbous1", library: "wi" },
	{ icon: WiMoonAltWaxingGibbous2, name: "WiMoonAltWaxingGibbous2", library: "wi" },
	{ icon: WiMoonAltWaxingGibbous3, name: "WiMoonAltWaxingGibbous3", library: "wi" },
	{ icon: WiMoonAltWaxingGibbous4, name: "WiMoonAltWaxingGibbous4", library: "wi" },
	{ icon: WiMoonAltWaxingGibbous5, name: "WiMoonAltWaxingGibbous5", library: "wi" },
	{ icon: WiMoonAltWaxingGibbous6, name: "WiMoonAltWaxingGibbous6", library: "wi" },
	{ icon: WiMoonFirstQuarter, name: "WiMoonFirstQuarter", library: "wi" },
	{ icon: WiMoonFull, name: "WiMoonFull", library: "wi" },
	{ icon: WiMoonNew, name: "WiMoonNew", library: "wi" },
	{ icon: WiMoonThirdQuarter, name: "WiMoonThirdQuarter", library: "wi" },
	{ icon: WiMoonWaningCrescent1, name: "WiMoonWaningCrescent1", library: "wi" },
	{ icon: WiMoonWaningCrescent2, name: "WiMoonWaningCrescent2", library: "wi" },
	{ icon: WiMoonWaningCrescent3, name: "WiMoonWaningCrescent3", library: "wi" },
	{ icon: WiMoonWaningCrescent4, name: "WiMoonWaningCrescent4", library: "wi" },
	{ icon: WiMoonWaningCrescent5, name: "WiMoonWaningCrescent5", library: "wi" },
	{ icon: WiMoonWaningCrescent6, name: "WiMoonWaningCrescent6", library: "wi" },
	{ icon: WiMoonWaningGibbous1, name: "WiMoonWaningGibbous1", library: "wi" },
	{ icon: WiMoonWaningGibbous2, name: "WiMoonWaningGibbous2", library: "wi" },
	{ icon: WiMoonWaningGibbous3, name: "WiMoonWaningGibbous3", library: "wi" },
	{ icon: WiMoonWaningGibbous4, name: "WiMoonWaningGibbous4", library: "wi" },
	{ icon: WiMoonWaningGibbous5, name: "WiMoonWaningGibbous5", library: "wi" },
	{ icon: WiMoonWaningGibbous6, name: "WiMoonWaningGibbous6", library: "wi" },
	{ icon: WiMoonWaxing6, name: "WiMoonWaxing6", library: "wi" },
	{ icon: WiMoonWaxingCrescent1, name: "WiMoonWaxingCrescent1", library: "wi" },
	{ icon: WiMoonWaxingCrescent2, name: "WiMoonWaxingCrescent2", library: "wi" },
	{ icon: WiMoonWaxingCrescent3, name: "WiMoonWaxingCrescent3", library: "wi" },
	{ icon: WiMoonWaxingCrescent4, name: "WiMoonWaxingCrescent4", library: "wi" },
	{ icon: WiMoonWaxingCrescent5, name: "WiMoonWaxingCrescent5", library: "wi" },
	{ icon: WiMoonWaxingGibbous1, name: "WiMoonWaxingGibbous1", library: "wi" },
	{ icon: WiMoonWaxingGibbous2, name: "WiMoonWaxingGibbous2", library: "wi" },
	{ icon: WiMoonWaxingGibbous3, name: "WiMoonWaxingGibbous3", library: "wi" },
	{ icon: WiMoonWaxingGibbous4, name: "WiMoonWaxingGibbous4", library: "wi" },
	{ icon: WiMoonWaxingGibbous5, name: "WiMoonWaxingGibbous5", library: "wi" },
	{ icon: WiMoonWaxingGibbous6, name: "WiMoonWaxingGibbous6", library: "wi" },
	{ icon: WiMoonrise, name: "WiMoonrise", library: "wi" },
	{ icon: WiMoonset, name: "WiMoonset", library: "wi" },
	{ icon: WiNa, name: "WiNa", library: "wi" },
	{ icon: WiNightAltCloudyGusts, name: "WiNightAltCloudyGusts", library: "wi" },
	{ icon: WiNightAltCloudyHigh, name: "WiNightAltCloudyHigh", library: "wi" },
	{ icon: WiNightAltCloudyWindy, name: "WiNightAltCloudyWindy", library: "wi" },
	{ icon: WiNightAltCloudy, name: "WiNightAltCloudy", library: "wi" },
	{ icon: WiNightAltHail, name: "WiNightAltHail", library: "wi" },
	{ icon: WiNightAltLightning, name: "WiNightAltLightning", library: "wi" },
	{ icon: WiNightAltPartlyCloudy, name: "WiNightAltPartlyCloudy", library: "wi" },
	{ icon: WiNightAltRainMix, name: "WiNightAltRainMix", library: "wi" },
	{ icon: WiNightAltRainWind, name: "WiNightAltRainWind", library: "wi" },
	{ icon: WiNightAltRain, name: "WiNightAltRain", library: "wi" },
	{ icon: WiNightAltShowers, name: "WiNightAltShowers", library: "wi" },
	{ icon: WiNightAltSleetStorm, name: "WiNightAltSleetStorm", library: "wi" },
	{ icon: WiNightAltSleet, name: "WiNightAltSleet", library: "wi" },
	{
		icon: WiNightAltSnowThunderstorm,
		name: "WiNightAltSnowThunderstorm",
		library: "wi",
	},
	{ icon: WiNightAltSnowWind, name: "WiNightAltSnowWind", library: "wi" },
	{ icon: WiNightAltSnow, name: "WiNightAltSnow", library: "wi" },
	{ icon: WiNightAltSprinkle, name: "WiNightAltSprinkle", library: "wi" },
	{ icon: WiNightAltStormShowers, name: "WiNightAltStormShowers", library: "wi" },
	{ icon: WiNightAltThunderstorm, name: "WiNightAltThunderstorm", library: "wi" },
	{ icon: WiNightClear, name: "WiNightClear", library: "wi" },
	{ icon: WiNightCloudyGusts, name: "WiNightCloudyGusts", library: "wi" },
	{ icon: WiNightCloudyHigh, name: "WiNightCloudyHigh", library: "wi" },
	{ icon: WiNightCloudyWindy, name: "WiNightCloudyWindy", library: "wi" },
	{ icon: WiNightCloudy, name: "WiNightCloudy", library: "wi" },
	{ icon: WiNightFog, name: "WiNightFog", library: "wi" },
	{ icon: WiNightHail, name: "WiNightHail", library: "wi" },
	{ icon: WiNightLightning, name: "WiNightLightning", library: "wi" },
	{ icon: WiNightPartlyCloudy, name: "WiNightPartlyCloudy", library: "wi" },
	{ icon: WiNightRainMix, name: "WiNightRainMix", library: "wi" },
	{ icon: WiNightRainWind, name: "WiNightRainWind", library: "wi" },
	{ icon: WiNightRain, name: "WiNightRain", library: "wi" },
	{ icon: WiNightShowers, name: "WiNightShowers", library: "wi" },
	{ icon: WiNightSleetStorm, name: "WiNightSleetStorm", library: "wi" },
	{ icon: WiNightSleet, name: "WiNightSleet", library: "wi" },
	{ icon: WiNightSnowThunderstorm, name: "WiNightSnowThunderstorm", library: "wi" },
	{ icon: WiNightSnowWind, name: "WiNightSnowWind", library: "wi" },
	{ icon: WiNightSnow, name: "WiNightSnow", library: "wi" },
	{ icon: WiNightSprinkle, name: "WiNightSprinkle", library: "wi" },
	{ icon: WiNightStormShowers, name: "WiNightStormShowers", library: "wi" },
	{ icon: WiNightThunderstorm, name: "WiNightThunderstorm", library: "wi" },
	{ icon: WiRainMix, name: "WiRainMix", library: "wi" },
	{ icon: WiRainWind, name: "WiRainWind", library: "wi" },
	{ icon: WiRain, name: "WiRain", library: "wi" },
	{ icon: WiRaindrop, name: "WiRaindrop", library: "wi" },
	{ icon: WiRaindrops, name: "WiRaindrops", library: "wi" },
	{ icon: WiRefreshAlt, name: "WiRefreshAlt", library: "wi" },
	{ icon: WiRefresh, name: "WiRefresh", library: "wi" },
	{ icon: WiSandstorm, name: "WiSandstorm", library: "wi" },
	{ icon: WiShowers, name: "WiShowers", library: "wi" },
	{ icon: WiSleet, name: "WiSleet", library: "wi" },
	{ icon: WiSmallCraftAdvisory, name: "WiSmallCraftAdvisory", library: "wi" },
	{ icon: WiSmog, name: "WiSmog", library: "wi" },
	{ icon: WiSmoke, name: "WiSmoke", library: "wi" },
	{ icon: WiSnowWind, name: "WiSnowWind", library: "wi" },
	{ icon: WiSnow, name: "WiSnow", library: "wi" },
	{ icon: WiSnowflakeCold, name: "WiSnowflakeCold", library: "wi" },
	{ icon: WiSolarEclipse, name: "WiSolarEclipse", library: "wi" },
	{ icon: WiSprinkle, name: "WiSprinkle", library: "wi" },
	{ icon: WiStars, name: "WiStars", library: "wi" },
	{ icon: WiStormShowers, name: "WiStormShowers", library: "wi" },
	{ icon: WiStormWarning, name: "WiStormWarning", library: "wi" },
	{ icon: WiStrongWind, name: "WiStrongWind", library: "wi" },
	{ icon: WiSunrise, name: "WiSunrise", library: "wi" },
	{ icon: WiSunset, name: "WiSunset", library: "wi" },
	{ icon: WiThermometerExterior, name: "WiThermometerExterior", library: "wi" },
	{ icon: WiThermometerInternal, name: "WiThermometerInternal", library: "wi" },
	{ icon: WiThermometer, name: "WiThermometer", library: "wi" },
	{ icon: WiThunderstorm, name: "WiThunderstorm", library: "wi" },
	{ icon: WiTime1, name: "WiTime1", library: "wi" },
	{ icon: WiTime10, name: "WiTime10", library: "wi" },
	{ icon: WiTime11, name: "WiTime11", library: "wi" },
	{ icon: WiTime12, name: "WiTime12", library: "wi" },
	{ icon: WiTime2, name: "WiTime2", library: "wi" },
	{ icon: WiTime3, name: "WiTime3", library: "wi" },
	{ icon: WiTime4, name: "WiTime4", library: "wi" },
	{ icon: WiTime5, name: "WiTime5", library: "wi" },
	{ icon: WiTime6, name: "WiTime6", library: "wi" },
	{ icon: WiTime7, name: "WiTime7", library: "wi" },
	{ icon: WiTime8, name: "WiTime8", library: "wi" },
	{ icon: WiTime9, name: "WiTime9", library: "wi" },
	{ icon: WiTornado, name: "WiTornado", library: "wi" },
	{ icon: WiTrain, name: "WiTrain", library: "wi" },
	{ icon: WiTsunami, name: "WiTsunami", library: "wi" },
	{ icon: WiUmbrella, name: "WiUmbrella", library: "wi" },
	{ icon: WiVolcano, name: "WiVolcano", library: "wi" },
	{ icon: WiWindBeaufort0, name: "WiWindBeaufort0", library: "wi" },
	{ icon: WiWindBeaufort1, name: "WiWindBeaufort1", library: "wi" },
	{ icon: WiWindBeaufort10, name: "WiWindBeaufort10", library: "wi" },
	{ icon: WiWindBeaufort11, name: "WiWindBeaufort11", library: "wi" },
	{ icon: WiWindBeaufort12, name: "WiWindBeaufort12", library: "wi" },
	{ icon: WiWindBeaufort2, name: "WiWindBeaufort2", library: "wi" },
	{ icon: WiWindBeaufort3, name: "WiWindBeaufort3", library: "wi" },
	{ icon: WiWindBeaufort4, name: "WiWindBeaufort4", library: "wi" },
	{ icon: WiWindBeaufort5, name: "WiWindBeaufort5", library: "wi" },
	{ icon: WiWindBeaufort6, name: "WiWindBeaufort6", library: "wi" },
	{ icon: WiWindBeaufort7, name: "WiWindBeaufort7", library: "wi" },
	{ icon: WiWindBeaufort8, name: "WiWindBeaufort8", library: "wi" },
	{ icon: WiWindBeaufort9, name: "WiWindBeaufort9", library: "wi" },
	{ icon: WiWindDeg, name: "WiWindDeg", library: "wi" },
	{ icon: WiWindy, name: "WiWindy", library: "wi" },
];

export default result;
