import {
BiAbacus,
BiAccessibility,
BiAddToQueue,
BiAdjust,
BiAlarmAdd,
BiAlarmExclamation,
BiAlarmOff,
BiAlarmSnooze,
BiAlarm,
BiAlbum,
BiAlignJustify,
BiAlignLeft,
BiAlignMiddle,
BiAlignRight,
BiAnalyse,
BiAnchor,
BiAngry,
BiAperture,
BiArch,
BiArchiveIn,
BiArchiveOut,
BiArchive,
BiArea,
BiArrowBack,
BiArrowFromBottom,
BiArrowFromLeft,
BiArrowFromRight,
BiArrowFromTop,
BiArrowToBottom,
BiArrowToLeft,
BiArrowToRight,
BiArrowToTop,
BiAt,
BiAtom,
BiAward,
BiBadgeCheck,
BiBadge,
BiBall,
BiBandAid,
BiBarChartAlt2,
BiBarChartAlt,
BiBarChartSquare,
BiBarChart,
BiBarcodeReader,
BiBarcode,
BiBaseball,
BiBasket,
BiBasketball,
BiBath,
BiBattery,
BiBed,
BiBeenHere,
BiBeer,
BiBellMinus,
BiBellOff,
BiBellPlus,
BiBell,
BiBible,
BiBitcoin,
BiBlanket,
BiBlock,
BiBluetooth,
BiBody,
BiBold,
BiBoltCircle,
BiBomb,
BiBone,
BiBong,
BiBookAdd,
BiBookAlt,
BiBookBookmark,
BiBookContent,
BiBookHeart,
BiBookOpen,
BiBookReader,
BiBook,
BiBookmarkAltMinus,
BiBookmarkAltPlus,
BiBookmarkAlt,
BiBookmarkHeart,
BiBookmarkMinus,
BiBookmarkPlus,
BiBookmark,
BiBookmarks,
BiBorderAll,
BiBorderBottom,
BiBorderInner,
BiBorderLeft,
BiBorderNone,
BiBorderOuter,
BiBorderRadius,
BiBorderRight,
BiBorderTop,
BiBot,
BiBowlingBall,
BiBox,
BiBracket,
BiBraille,
BiBrain,
BiBriefcaseAlt2,
BiBriefcaseAlt,
BiBriefcase,
BiBrightnessHalf,
BiBrightness,
BiBroadcast,
BiBrushAlt,
BiBrush,
BiBugAlt,
BiBug,
BiBuildingHouse,
BiBuilding,
BiBuildings,
BiBulb,
BiBullseye,
BiBuoy,
BiBusSchool,
BiBus,
BiCabinet,
BiCake,
BiCalculator,
BiCalendarAlt,
BiCalendarCheck,
BiCalendarEdit,
BiCalendarEvent,
BiCalendarExclamation,
BiCalendarHeart,
BiCalendarMinus,
BiCalendarPlus,
BiCalendarStar,
BiCalendarWeek,
BiCalendarX,
BiCalendar,
BiCameraHome,
BiCameraMovie,
BiCameraOff,
BiCamera,
BiCapsule,
BiCaptions,
BiCar,
BiCard,
BiCaretDownCircle,
BiCaretDownSquare,
BiCaretDown,
BiCaretLeftCircle,
BiCaretLeftSquare,
BiCaretLeft,
BiCaretRightCircle,
BiCaretRightSquare,
BiCaretRight,
BiCaretUpCircle,
BiCaretUpSquare,
BiCaretUp,
BiCarousel,
BiCartAlt,
BiCart,
BiCast,
BiCategoryAlt,
BiCategory,
BiCctv,
BiCertification,
BiChair,
BiChalkboard,
BiChart,
BiChat,
BiCheckCircle,
BiCheckDouble,
BiCheckShield,
BiCheckSquare,
BiCheck,
BiCheckboxChecked,
BiCheckboxMinus,
BiCheckboxSquare,
BiCheckbox,
BiChevronDownCircle,
BiChevronDownSquare,
BiChevronDown,
BiChevronLeftCircle,
BiChevronLeftSquare,
BiChevronLeft,
BiChevronRightCircle,
BiChevronRightSquare,
BiChevronRight,
BiChevronUpCircle,
BiChevronUpSquare,
BiChevronUp,
BiChevronsDown,
BiChevronsLeft,
BiChevronsRight,
BiChevronsUp,
BiChip,
BiChurch,
BiCircle,
BiClinic,
BiClipboard,
BiCloset,
BiCloudDownload,
BiCloudDrizzle,
BiCloudLightRain,
BiCloudLightning,
BiCloudRain,
BiCloudSnow,
BiCloudUpload,
BiCloud,
BiCodeAlt,
BiCodeBlock,
BiCodeCurly,
BiCode,
BiCoffeeTogo,
BiCoffee,
BiCog,
BiCoinStack,
BiCoin,
BiCollapse,
BiCollection,
BiColorFill,
BiColumns,
BiCommand,
BiCommentAdd,
BiCommentCheck,
BiCommentDetail,
BiCommentDots,
BiCommentEdit,
BiCommentError,
BiCommentMinus,
BiCommentX,
BiComment,
BiCompass,
BiConfused,
BiConversation,
BiCookie,
BiCool,
BiCopyAlt,
BiCopy,
BiCopyright,
BiCreditCardAlt,
BiCreditCardFront,
BiCreditCard,
BiCrop,
BiCrosshair,
BiCrown,
BiCubeAlt,
BiCube,
BiCuboid,
BiCurrentLocation,
BiCustomize,
BiCut,
BiCycling,
BiCylinder,
BiData,
BiDesktop,
BiDetail,
BiDevices,
BiDialpadAlt,
BiDialpad,
BiDiamond,
BiDice1,
BiDice2,
BiDice3,
BiDice4,
BiDice5,
BiDice6,
BiDirections,
BiDisc,
BiDish,
BiDislike,
BiDizzy,
BiDna,
BiDockBottom,
BiDockLeft,
BiDockRight,
BiDockTop,
BiDollarCircle,
BiDollar,
BiDonateBlood,
BiDonateHeart,
BiDoorOpen,
BiDotsHorizontalRounded,
BiDotsHorizontal,
BiDotsVerticalRounded,
BiDotsVertical,
BiDoughnutChart,
BiDownArrowAlt,
BiDownArrowCircle,
BiDownArrow,
BiDownload,
BiDownvote,
BiDrink,
BiDroplet,
BiDumbbell,
BiDuplicate,
BiEditAlt,
BiEdit,
BiEnvelopeOpen,
BiEnvelope,
BiEqualizer,
BiEraser,
BiErrorAlt,
BiErrorCircle,
BiError,
BiEuro,
BiExclude,
BiExitFullscreen,
BiExit,
BiExpandAlt,
BiExpand,
BiExport,
BiExtension,
BiFace,
BiFastForwardCircle,
BiFastForward,
BiFemaleSign,
BiFemale,
BiFileBlank,
BiFileFind,
BiFile,
BiFilm,
BiFilterAlt,
BiFilter,
BiFingerprint,
BiFirstAid,
BiFirstPage,
BiFlag,
BiFolderMinus,
BiFolderOpen,
BiFolderPlus,
BiFolder,
BiFontColor,
BiFontFamily,
BiFontSize,
BiFont,
BiFoodMenu,
BiFoodTag,
BiFootball,
BiFridge,
BiFullscreen,
BiGame,
BiGasPump,
BiGhost,
BiGift,
BiGitBranch,
BiGitCommit,
BiGitCompare,
BiGitMerge,
BiGitPullRequest,
BiGitRepoForked,
BiGlassesAlt,
BiGlasses,
BiGlobeAlt,
BiGlobe,
BiGridAlt,
BiGridHorizontal,
BiGridSmall,
BiGridVertical,
BiGrid,
BiGroup,
BiHandicap,
BiHappyAlt,
BiHappyBeaming,
BiHappyHeartEyes,
BiHappy,
BiHash,
BiHdd,
BiHeading,
BiHeadphone,
BiHealth,
BiHeartCircle,
BiHeartSquare,
BiHeart,
BiHelpCircle,
BiHide,
BiHighlight,
BiHistory,
BiHive,
BiHomeAlt,
BiHomeCircle,
BiHomeHeart,
BiHomeSmile,
BiHome,
BiHorizontalCenter,
BiHotel,
BiHourglass,
BiIdCard,
BiImageAdd,
BiImageAlt,
BiImage,
BiImages,
BiImport,
BiInfinite,
BiInfoCircle,
BiInfoSquare,
BiIntersect,
BiItalic,
BiJoystickAlt,
BiJoystickButton,
BiJoystick,
BiKey,
BiLabel,
BiLandscape,
BiLaptop,
BiLastPage,
BiLaugh,
BiLayerMinus,
BiLayerPlus,
BiLayer,
BiLayout,
BiLeftArrowAlt,
BiLeftArrowCircle,
BiLeftArrow,
BiLeftDownArrowCircle,
BiLeftIndent,
BiLeftTopArrowCircle,
BiLibrary,
BiLike,
BiLineChartDown,
BiLineChart,
BiLinkAlt,
BiLinkExternal,
BiLink,
BiLira,
BiListCheck,
BiListMinus,
BiListOl,
BiListPlus,
BiListUl,
BiLoaderAlt,
BiLoaderCircle,
BiLoader,
BiLocationPlus,
BiLockAlt,
BiLockOpenAlt,
BiLockOpen,
BiLock,
BiLogInCircle,
BiLogIn,
BiLogOutCircle,
BiLogOut,
BiLowVision,
BiMagnet,
BiMailSend,
BiMaleSign,
BiMale,
BiMapAlt,
BiMapPin,
BiMap,
BiMask,
BiMedal,
BiMehAlt,
BiMehBlank,
BiMeh,
BiMemoryCard,
BiMenuAltLeft,
BiMenuAltRight,
BiMenu,
BiMerge,
BiMessageAdd,
BiMessageAltAdd,
BiMessageAltCheck,
BiMessageAltDetail,
BiMessageAltDots,
BiMessageAltEdit,
BiMessageAltError,
BiMessageAltMinus,
BiMessageAltX,
BiMessageAlt,
BiMessageCheck,
BiMessageDetail,
BiMessageDots,
BiMessageEdit,
BiMessageError,
BiMessageMinus,
BiMessageRoundedAdd,
BiMessageRoundedCheck,
BiMessageRoundedDetail,
BiMessageRoundedDots,
BiMessageRoundedEdit,
BiMessageRoundedError,
BiMessageRoundedMinus,
BiMessageRoundedX,
BiMessageRounded,
BiMessageSquareAdd,
BiMessageSquareCheck,
BiMessageSquareDetail,
BiMessageSquareDots,
BiMessageSquareEdit,
BiMessageSquareError,
BiMessageSquareMinus,
BiMessageSquareX,
BiMessageSquare,
BiMessageX,
BiMessage,
BiMeteor,
BiMicrochip,
BiMicrophoneOff,
BiMicrophone,
BiMinusBack,
BiMinusCircle,
BiMinusFront,
BiMinus,
BiMobileAlt,
BiMobileLandscape,
BiMobileVibration,
BiMobile,
BiMoney,
BiMoon,
BiMouseAlt,
BiMouse,
BiMoveHorizontal,
BiMoveVertical,
BiMove,
BiMoviePlay,
BiMovie,
BiMusic,
BiNavigation,
BiNetworkChart,
BiNews,
BiNoEntry,
BiNote,
BiNotepad,
BiNotificationOff,
BiNotification,
BiOutline,
BiPackage,
BiPaintRoll,
BiPaint,
BiPalette,
BiPaperPlane,
BiPaperclip,
BiParagraph,
BiPaste,
BiPauseCircle,
BiPause,
BiPen,
BiPencil,
BiPhoneCall,
BiPhoneIncoming,
BiPhoneOff,
BiPhoneOutgoing,
BiPhone,
BiPhotoAlbum,
BiPieChartAlt2,
BiPieChartAlt,
BiPieChart,
BiPin,
BiPlanet,
BiPlayCircle,
BiPlay,
BiPlug,
BiPlusCircle,
BiPlusMedical,
BiPlus,
BiPodcast,
BiPointer,
BiPoll,
BiPolygon,
BiPound,
BiPowerOff,
BiPrinter,
BiPulse,
BiPurchaseTagAlt,
BiPurchaseTag,
BiPyramid,
BiQrScan,
BiQr,
BiQuestionMark,
BiRadar,
BiRadioCircleMarked,
BiRadioCircle,
BiRadio,
BiReceipt,
BiRectangle,
BiRecycle,
BiRedo,
BiRefresh,
BiRegistered,
BiRename,
BiRepeat,
BiReplyAll,
BiReply,
BiRepost,
BiReset,
BiRestaurant,
BiRevision,
BiRewindCircle,
BiRewind,
BiRightArrowAlt,
BiRightArrowCircle,
BiRightArrow,
BiRightDownArrowCircle,
BiRightIndent,
BiRightTopArrowCircle,
BiRocket,
BiRotateLeft,
BiRotateRight,
BiRss,
BiRuble,
BiRuler,
BiRun,
BiRupee,
BiSad,
BiSave,
BiScan,
BiScreenshot,
BiSearchAlt2,
BiSearchAlt,
BiSearch,
BiSelectMultiple,
BiSelection,
BiSend,
BiServer,
BiShapeCircle,
BiShapePolygon,
BiShapeSquare,
BiShapeTriangle,
BiShareAlt,
BiShare,
BiShekel,
BiShieldAlt2,
BiShieldAlt,
BiShieldQuarter,
BiShieldX,
BiShield,
BiShocked,
BiShoppingBag,
BiShowAlt,
BiShow,
BiShuffle,
BiSidebar,
BiSitemap,
BiSkipNextCircle,
BiSkipNext,
BiSkipPreviousCircle,
BiSkipPrevious,
BiSleepy,
BiSliderAlt,
BiSlider,
BiSlideshow,
BiSmile,
BiSortAZ,
BiSortAlt2,
BiSortDown,
BiSortUp,
BiSortZA,
BiSort,
BiSpa,
BiSpaceBar,
BiSpeaker,
BiSprayCan,
BiSpreadsheet,
BiSquareRounded,
BiSquare,
BiStar,
BiStation,
BiStats,
BiSticker,
BiStopCircle,
BiStop,
BiStopwatch,
BiStoreAlt,
BiStore,
BiStreetView,
BiStrikethrough,
BiSubdirectoryLeft,
BiSubdirectoryRight,
BiSun,
BiSupport,
BiSwim,
BiSync,
BiTab,
BiTable,
BiTachometer,
BiTagAlt,
BiTag,
BiTargetLock,
BiTaskX,
BiTask,
BiTaxi,
BiTennisBall,
BiTerminal,
BiTestTube,
BiText,
BiTimeFive,
BiTime,
BiTimer,
BiTired,
BiToggleLeft,
BiToggleRight,
BiTone,
BiTrafficCone,
BiTrain,
BiTransferAlt,
BiTransfer,
BiTrashAlt,
BiTrash,
BiTrendingDown,
BiTrendingUp,
BiTrim,
BiTrip,
BiTrophy,
BiTv,
BiUnderline,
BiUndo,
BiUnite,
BiUnlink,
BiUpArrowAlt,
BiUpArrowCircle,
BiUpArrow,
BiUpload,
BiUpsideDown,
BiUpvote,
BiUsb,
BiUserCheck,
BiUserCircle,
BiUserMinus,
BiUserPin,
BiUserPlus,
BiUserVoice,
BiUserX,
BiUser,
BiVector,
BiVerticalCenter,
BiVial,
BiVideoOff,
BiVideoPlus,
BiVideoRecording,
BiVideo,
BiVoicemail,
BiVolumeFull,
BiVolumeLow,
BiVolumeMute,
BiVolume,
BiWalk,
BiWalletAlt,
BiWallet,
BiWater,
BiWebcam,
BiWifi0,
BiWifi1,
BiWifi2,
BiWifiOff,
BiWifi,
BiWind,
BiWindowAlt,
BiWindowClose,
BiWindowOpen,
BiWindow,
BiWindows,
BiWine,
BiWinkSmile,
BiWinkTongue,
BiWon,
BiWorld,
BiWrench,
BiXCircle,
BiX,
BiYen,
BiZoomIn,
BiZoomOut,
} from "react-icons/bi";

const result = [
{ icon: BiAbacus, name: "BiAbacus" },
{ icon: BiAccessibility, name: "BiAccessibility" },
{ icon: BiAddToQueue, name: "BiAddToQueue" },
{ icon: BiAdjust, name: "BiAdjust" },
{ icon: BiAlarmAdd, name: "BiAlarmAdd" },
{ icon: BiAlarmExclamation, name: "BiAlarmExclamation" },
{ icon: BiAlarmOff, name: "BiAlarmOff" },
{ icon: BiAlarmSnooze, name: "BiAlarmSnooze" },
{ icon: BiAlarm, name: "BiAlarm" },
{ icon: BiAlbum, name: "BiAlbum" },
{ icon: BiAlignJustify, name: "BiAlignJustify" },
{ icon: BiAlignLeft, name: "BiAlignLeft" },
{ icon: BiAlignMiddle, name: "BiAlignMiddle" },
{ icon: BiAlignRight, name: "BiAlignRight" },
{ icon: BiAnalyse, name: "BiAnalyse" },
{ icon: BiAnchor, name: "BiAnchor" },
{ icon: BiAngry, name: "BiAngry" },
{ icon: BiAperture, name: "BiAperture" },
{ icon: BiArch, name: "BiArch" },
{ icon: BiArchiveIn, name: "BiArchiveIn" },
{ icon: BiArchiveOut, name: "BiArchiveOut" },
{ icon: BiArchive, name: "BiArchive" },
{ icon: BiArea, name: "BiArea" },
{ icon: BiArrowBack, name: "BiArrowBack" },
{ icon: BiArrowFromBottom, name: "BiArrowFromBottom" },
{ icon: BiArrowFromLeft, name: "BiArrowFromLeft" },
{ icon: BiArrowFromRight, name: "BiArrowFromRight" },
{ icon: BiArrowFromTop, name: "BiArrowFromTop" },
{ icon: BiArrowToBottom, name: "BiArrowToBottom" },
{ icon: BiArrowToLeft, name: "BiArrowToLeft" },
{ icon: BiArrowToRight, name: "BiArrowToRight" },
{ icon: BiArrowToTop, name: "BiArrowToTop" },
{ icon: BiAt, name: "BiAt" },
{ icon: BiAtom, name: "BiAtom" },
{ icon: BiAward, name: "BiAward" },
{ icon: BiBadgeCheck, name: "BiBadgeCheck" },
{ icon: BiBadge, name: "BiBadge" },
{ icon: BiBall, name: "BiBall" },
{ icon: BiBandAid, name: "BiBandAid" },
{ icon: BiBarChartAlt2, name: "BiBarChartAlt2" },
{ icon: BiBarChartAlt, name: "BiBarChartAlt" },
{ icon: BiBarChartSquare, name: "BiBarChartSquare" },
{ icon: BiBarChart, name: "BiBarChart" },
{ icon: BiBarcodeReader, name: "BiBarcodeReader" },
{ icon: BiBarcode, name: "BiBarcode" },
{ icon: BiBaseball, name: "BiBaseball" },
{ icon: BiBasket, name: "BiBasket" },
{ icon: BiBasketball, name: "BiBasketball" },
{ icon: BiBath, name: "BiBath" },
{ icon: BiBattery, name: "BiBattery" },
{ icon: BiBed, name: "BiBed" },
{ icon: BiBeenHere, name: "BiBeenHere" },
{ icon: BiBeer, name: "BiBeer" },
{ icon: BiBellMinus, name: "BiBellMinus" },
{ icon: BiBellOff, name: "BiBellOff" },
{ icon: BiBellPlus, name: "BiBellPlus" },
{ icon: BiBell, name: "BiBell" },
{ icon: BiBible, name: "BiBible" },
{ icon: BiBitcoin, name: "BiBitcoin" },
{ icon: BiBlanket, name: "BiBlanket" },
{ icon: BiBlock, name: "BiBlock" },
{ icon: BiBluetooth, name: "BiBluetooth" },
{ icon: BiBody, name: "BiBody" },
{ icon: BiBold, name: "BiBold" },
{ icon: BiBoltCircle, name: "BiBoltCircle" },
{ icon: BiBomb, name: "BiBomb" },
{ icon: BiBone, name: "BiBone" },
{ icon: BiBong, name: "BiBong" },
{ icon: BiBookAdd, name: "BiBookAdd" },
{ icon: BiBookAlt, name: "BiBookAlt" },
{ icon: BiBookBookmark, name: "BiBookBookmark" },
{ icon: BiBookContent, name: "BiBookContent" },
{ icon: BiBookHeart, name: "BiBookHeart" },
{ icon: BiBookOpen, name: "BiBookOpen" },
{ icon: BiBookReader, name: "BiBookReader" },
{ icon: BiBook, name: "BiBook" },
{ icon: BiBookmarkAltMinus, name: "BiBookmarkAltMinus" },
{ icon: BiBookmarkAltPlus, name: "BiBookmarkAltPlus" },
{ icon: BiBookmarkAlt, name: "BiBookmarkAlt" },
{ icon: BiBookmarkHeart, name: "BiBookmarkHeart" },
{ icon: BiBookmarkMinus, name: "BiBookmarkMinus" },
{ icon: BiBookmarkPlus, name: "BiBookmarkPlus" },
{ icon: BiBookmark, name: "BiBookmark" },
{ icon: BiBookmarks, name: "BiBookmarks" },
{ icon: BiBorderAll, name: "BiBorderAll" },
{ icon: BiBorderBottom, name: "BiBorderBottom" },
{ icon: BiBorderInner, name: "BiBorderInner" },
{ icon: BiBorderLeft, name: "BiBorderLeft" },
{ icon: BiBorderNone, name: "BiBorderNone" },
{ icon: BiBorderOuter, name: "BiBorderOuter" },
{ icon: BiBorderRadius, name: "BiBorderRadius" },
{ icon: BiBorderRight, name: "BiBorderRight" },
{ icon: BiBorderTop, name: "BiBorderTop" },
{ icon: BiBot, name: "BiBot" },
{ icon: BiBowlingBall, name: "BiBowlingBall" },
{ icon: BiBox, name: "BiBox" },
{ icon: BiBracket, name: "BiBracket" },
{ icon: BiBraille, name: "BiBraille" },
{ icon: BiBrain, name: "BiBrain" },
{ icon: BiBriefcaseAlt2, name: "BiBriefcaseAlt2" },
{ icon: BiBriefcaseAlt, name: "BiBriefcaseAlt" },
{ icon: BiBriefcase, name: "BiBriefcase" },
{ icon: BiBrightnessHalf, name: "BiBrightnessHalf" },
{ icon: BiBrightness, name: "BiBrightness" },
{ icon: BiBroadcast, name: "BiBroadcast" },
{ icon: BiBrushAlt, name: "BiBrushAlt" },
{ icon: BiBrush, name: "BiBrush" },
{ icon: BiBugAlt, name: "BiBugAlt" },
{ icon: BiBug, name: "BiBug" },
{ icon: BiBuildingHouse, name: "BiBuildingHouse" },
{ icon: BiBuilding, name: "BiBuilding" },
{ icon: BiBuildings, name: "BiBuildings" },
{ icon: BiBulb, name: "BiBulb" },
{ icon: BiBullseye, name: "BiBullseye" },
{ icon: BiBuoy, name: "BiBuoy" },
{ icon: BiBusSchool, name: "BiBusSchool" },
{ icon: BiBus, name: "BiBus" },
{ icon: BiCabinet, name: "BiCabinet" },
{ icon: BiCake, name: "BiCake" },
{ icon: BiCalculator, name: "BiCalculator" },
{ icon: BiCalendarAlt, name: "BiCalendarAlt" },
{ icon: BiCalendarCheck, name: "BiCalendarCheck" },
{ icon: BiCalendarEdit, name: "BiCalendarEdit" },
{ icon: BiCalendarEvent, name: "BiCalendarEvent" },
{ icon: BiCalendarExclamation, name: "BiCalendarExclamation" },
{ icon: BiCalendarHeart, name: "BiCalendarHeart" },
{ icon: BiCalendarMinus, name: "BiCalendarMinus" },
{ icon: BiCalendarPlus, name: "BiCalendarPlus" },
{ icon: BiCalendarStar, name: "BiCalendarStar" },
{ icon: BiCalendarWeek, name: "BiCalendarWeek" },
{ icon: BiCalendarX, name: "BiCalendarX" },
{ icon: BiCalendar, name: "BiCalendar" },
{ icon: BiCameraHome, name: "BiCameraHome" },
{ icon: BiCameraMovie, name: "BiCameraMovie" },
{ icon: BiCameraOff, name: "BiCameraOff" },
{ icon: BiCamera, name: "BiCamera" },
{ icon: BiCapsule, name: "BiCapsule" },
{ icon: BiCaptions, name: "BiCaptions" },
{ icon: BiCar, name: "BiCar" },
{ icon: BiCard, name: "BiCard" },
{ icon: BiCaretDownCircle, name: "BiCaretDownCircle" },
{ icon: BiCaretDownSquare, name: "BiCaretDownSquare" },
{ icon: BiCaretDown, name: "BiCaretDown" },
{ icon: BiCaretLeftCircle, name: "BiCaretLeftCircle" },
{ icon: BiCaretLeftSquare, name: "BiCaretLeftSquare" },
{ icon: BiCaretLeft, name: "BiCaretLeft" },
{ icon: BiCaretRightCircle, name: "BiCaretRightCircle" },
{ icon: BiCaretRightSquare, name: "BiCaretRightSquare" },
{ icon: BiCaretRight, name: "BiCaretRight" },
{ icon: BiCaretUpCircle, name: "BiCaretUpCircle" },
{ icon: BiCaretUpSquare, name: "BiCaretUpSquare" },
{ icon: BiCaretUp, name: "BiCaretUp" },
{ icon: BiCarousel, name: "BiCarousel" },
{ icon: BiCartAlt, name: "BiCartAlt" },
{ icon: BiCart, name: "BiCart" },
{ icon: BiCast, name: "BiCast" },
{ icon: BiCategoryAlt, name: "BiCategoryAlt" },
{ icon: BiCategory, name: "BiCategory" },
{ icon: BiCctv, name: "BiCctv" },
{ icon: BiCertification, name: "BiCertification" },
{ icon: BiChair, name: "BiChair" },
{ icon: BiChalkboard, name: "BiChalkboard" },
{ icon: BiChart, name: "BiChart" },
{ icon: BiChat, name: "BiChat" },
{ icon: BiCheckCircle, name: "BiCheckCircle" },
{ icon: BiCheckDouble, name: "BiCheckDouble" },
{ icon: BiCheckShield, name: "BiCheckShield" },
{ icon: BiCheckSquare, name: "BiCheckSquare" },
{ icon: BiCheck, name: "BiCheck" },
{ icon: BiCheckboxChecked, name: "BiCheckboxChecked" },
{ icon: BiCheckboxMinus, name: "BiCheckboxMinus" },
{ icon: BiCheckboxSquare, name: "BiCheckboxSquare" },
{ icon: BiCheckbox, name: "BiCheckbox" },
{ icon: BiChevronDownCircle, name: "BiChevronDownCircle" },
{ icon: BiChevronDownSquare, name: "BiChevronDownSquare" },
{ icon: BiChevronDown, name: "BiChevronDown" },
{ icon: BiChevronLeftCircle, name: "BiChevronLeftCircle" },
{ icon: BiChevronLeftSquare, name: "BiChevronLeftSquare" },
{ icon: BiChevronLeft, name: "BiChevronLeft" },
{ icon: BiChevronRightCircle, name: "BiChevronRightCircle" },
{ icon: BiChevronRightSquare, name: "BiChevronRightSquare" },
{ icon: BiChevronRight, name: "BiChevronRight" },
{ icon: BiChevronUpCircle, name: "BiChevronUpCircle" },
{ icon: BiChevronUpSquare, name: "BiChevronUpSquare" },
{ icon: BiChevronUp, name: "BiChevronUp" },
{ icon: BiChevronsDown, name: "BiChevronsDown" },
{ icon: BiChevronsLeft, name: "BiChevronsLeft" },
{ icon: BiChevronsRight, name: "BiChevronsRight" },
{ icon: BiChevronsUp, name: "BiChevronsUp" },
{ icon: BiChip, name: "BiChip" },
{ icon: BiChurch, name: "BiChurch" },
{ icon: BiCircle, name: "BiCircle" },
{ icon: BiClinic, name: "BiClinic" },
{ icon: BiClipboard, name: "BiClipboard" },
{ icon: BiCloset, name: "BiCloset" },
{ icon: BiCloudDownload, name: "BiCloudDownload" },
{ icon: BiCloudDrizzle, name: "BiCloudDrizzle" },
{ icon: BiCloudLightRain, name: "BiCloudLightRain" },
{ icon: BiCloudLightning, name: "BiCloudLightning" },
{ icon: BiCloudRain, name: "BiCloudRain" },
{ icon: BiCloudSnow, name: "BiCloudSnow" },
{ icon: BiCloudUpload, name: "BiCloudUpload" },
{ icon: BiCloud, name: "BiCloud" },
{ icon: BiCodeAlt, name: "BiCodeAlt" },
{ icon: BiCodeBlock, name: "BiCodeBlock" },
{ icon: BiCodeCurly, name: "BiCodeCurly" },
{ icon: BiCode, name: "BiCode" },
{ icon: BiCoffeeTogo, name: "BiCoffeeTogo" },
{ icon: BiCoffee, name: "BiCoffee" },
{ icon: BiCog, name: "BiCog" },
{ icon: BiCoinStack, name: "BiCoinStack" },
{ icon: BiCoin, name: "BiCoin" },
{ icon: BiCollapse, name: "BiCollapse" },
{ icon: BiCollection, name: "BiCollection" },
{ icon: BiColorFill, name: "BiColorFill" },
{ icon: BiColumns, name: "BiColumns" },
{ icon: BiCommand, name: "BiCommand" },
{ icon: BiCommentAdd, name: "BiCommentAdd" },
{ icon: BiCommentCheck, name: "BiCommentCheck" },
{ icon: BiCommentDetail, name: "BiCommentDetail" },
{ icon: BiCommentDots, name: "BiCommentDots" },
{ icon: BiCommentEdit, name: "BiCommentEdit" },
{ icon: BiCommentError, name: "BiCommentError" },
{ icon: BiCommentMinus, name: "BiCommentMinus" },
{ icon: BiCommentX, name: "BiCommentX" },
{ icon: BiComment, name: "BiComment" },
{ icon: BiCompass, name: "BiCompass" },
{ icon: BiConfused, name: "BiConfused" },
{ icon: BiConversation, name: "BiConversation" },
{ icon: BiCookie, name: "BiCookie" },
{ icon: BiCool, name: "BiCool" },
{ icon: BiCopyAlt, name: "BiCopyAlt" },
{ icon: BiCopy, name: "BiCopy" },
{ icon: BiCopyright, name: "BiCopyright" },
{ icon: BiCreditCardAlt, name: "BiCreditCardAlt" },
{ icon: BiCreditCardFront, name: "BiCreditCardFront" },
{ icon: BiCreditCard, name: "BiCreditCard" },
{ icon: BiCrop, name: "BiCrop" },
{ icon: BiCrosshair, name: "BiCrosshair" },
{ icon: BiCrown, name: "BiCrown" },
{ icon: BiCubeAlt, name: "BiCubeAlt" },
{ icon: BiCube, name: "BiCube" },
{ icon: BiCuboid, name: "BiCuboid" },
{ icon: BiCurrentLocation, name: "BiCurrentLocation" },
{ icon: BiCustomize, name: "BiCustomize" },
{ icon: BiCut, name: "BiCut" },
{ icon: BiCycling, name: "BiCycling" },
{ icon: BiCylinder, name: "BiCylinder" },
{ icon: BiData, name: "BiData" },
{ icon: BiDesktop, name: "BiDesktop" },
{ icon: BiDetail, name: "BiDetail" },
{ icon: BiDevices, name: "BiDevices" },
{ icon: BiDialpadAlt, name: "BiDialpadAlt" },
{ icon: BiDialpad, name: "BiDialpad" },
{ icon: BiDiamond, name: "BiDiamond" },
{ icon: BiDice1, name: "BiDice1" },
{ icon: BiDice2, name: "BiDice2" },
{ icon: BiDice3, name: "BiDice3" },
{ icon: BiDice4, name: "BiDice4" },
{ icon: BiDice5, name: "BiDice5" },
{ icon: BiDice6, name: "BiDice6" },
{ icon: BiDirections, name: "BiDirections" },
{ icon: BiDisc, name: "BiDisc" },
{ icon: BiDish, name: "BiDish" },
{ icon: BiDislike, name: "BiDislike" },
{ icon: BiDizzy, name: "BiDizzy" },
{ icon: BiDna, name: "BiDna" },
{ icon: BiDockBottom, name: "BiDockBottom" },
{ icon: BiDockLeft, name: "BiDockLeft" },
{ icon: BiDockRight, name: "BiDockRight" },
{ icon: BiDockTop, name: "BiDockTop" },
{ icon: BiDollarCircle, name: "BiDollarCircle" },
{ icon: BiDollar, name: "BiDollar" },
{ icon: BiDonateBlood, name: "BiDonateBlood" },
{ icon: BiDonateHeart, name: "BiDonateHeart" },
{ icon: BiDoorOpen, name: "BiDoorOpen" },
{ icon: BiDotsHorizontalRounded, name: "BiDotsHorizontalRounded" },
{ icon: BiDotsHorizontal, name: "BiDotsHorizontal" },
{ icon: BiDotsVerticalRounded, name: "BiDotsVerticalRounded" },
{ icon: BiDotsVertical, name: "BiDotsVertical" },
{ icon: BiDoughnutChart, name: "BiDoughnutChart" },
{ icon: BiDownArrowAlt, name: "BiDownArrowAlt" },
{ icon: BiDownArrowCircle, name: "BiDownArrowCircle" },
{ icon: BiDownArrow, name: "BiDownArrow" },
{ icon: BiDownload, name: "BiDownload" },
{ icon: BiDownvote, name: "BiDownvote" },
{ icon: BiDrink, name: "BiDrink" },
{ icon: BiDroplet, name: "BiDroplet" },
{ icon: BiDumbbell, name: "BiDumbbell" },
{ icon: BiDuplicate, name: "BiDuplicate" },
{ icon: BiEditAlt, name: "BiEditAlt" },
{ icon: BiEdit, name: "BiEdit" },
{ icon: BiEnvelopeOpen, name: "BiEnvelopeOpen" },
{ icon: BiEnvelope, name: "BiEnvelope" },
{ icon: BiEqualizer, name: "BiEqualizer" },
{ icon: BiEraser, name: "BiEraser" },
{ icon: BiErrorAlt, name: "BiErrorAlt" },
{ icon: BiErrorCircle, name: "BiErrorCircle" },
{ icon: BiError, name: "BiError" },
{ icon: BiEuro, name: "BiEuro" },
{ icon: BiExclude, name: "BiExclude" },
{ icon: BiExitFullscreen, name: "BiExitFullscreen" },
{ icon: BiExit, name: "BiExit" },
{ icon: BiExpandAlt, name: "BiExpandAlt" },
{ icon: BiExpand, name: "BiExpand" },
{ icon: BiExport, name: "BiExport" },
{ icon: BiExtension, name: "BiExtension" },
{ icon: BiFace, name: "BiFace" },
{ icon: BiFastForwardCircle, name: "BiFastForwardCircle" },
{ icon: BiFastForward, name: "BiFastForward" },
{ icon: BiFemaleSign, name: "BiFemaleSign" },
{ icon: BiFemale, name: "BiFemale" },
{ icon: BiFileBlank, name: "BiFileBlank" },
{ icon: BiFileFind, name: "BiFileFind" },
{ icon: BiFile, name: "BiFile" },
{ icon: BiFilm, name: "BiFilm" },
{ icon: BiFilterAlt, name: "BiFilterAlt" },
{ icon: BiFilter, name: "BiFilter" },
{ icon: BiFingerprint, name: "BiFingerprint" },
{ icon: BiFirstAid, name: "BiFirstAid" },
{ icon: BiFirstPage, name: "BiFirstPage" },
{ icon: BiFlag, name: "BiFlag" },
{ icon: BiFolderMinus, name: "BiFolderMinus" },
{ icon: BiFolderOpen, name: "BiFolderOpen" },
{ icon: BiFolderPlus, name: "BiFolderPlus" },
{ icon: BiFolder, name: "BiFolder" },
{ icon: BiFontColor, name: "BiFontColor" },
{ icon: BiFontFamily, name: "BiFontFamily" },
{ icon: BiFontSize, name: "BiFontSize" },
{ icon: BiFont, name: "BiFont" },
{ icon: BiFoodMenu, name: "BiFoodMenu" },
{ icon: BiFoodTag, name: "BiFoodTag" },
{ icon: BiFootball, name: "BiFootball" },
{ icon: BiFridge, name: "BiFridge" },
{ icon: BiFullscreen, name: "BiFullscreen" },
{ icon: BiGame, name: "BiGame" },
{ icon: BiGasPump, name: "BiGasPump" },
{ icon: BiGhost, name: "BiGhost" },
{ icon: BiGift, name: "BiGift" },
{ icon: BiGitBranch, name: "BiGitBranch" },
{ icon: BiGitCommit, name: "BiGitCommit" },
{ icon: BiGitCompare, name: "BiGitCompare" },
{ icon: BiGitMerge, name: "BiGitMerge" },
{ icon: BiGitPullRequest, name: "BiGitPullRequest" },
{ icon: BiGitRepoForked, name: "BiGitRepoForked" },
{ icon: BiGlassesAlt, name: "BiGlassesAlt" },
{ icon: BiGlasses, name: "BiGlasses" },
{ icon: BiGlobeAlt, name: "BiGlobeAlt" },
{ icon: BiGlobe, name: "BiGlobe" },
{ icon: BiGridAlt, name: "BiGridAlt" },
{ icon: BiGridHorizontal, name: "BiGridHorizontal" },
{ icon: BiGridSmall, name: "BiGridSmall" },
{ icon: BiGridVertical, name: "BiGridVertical" },
{ icon: BiGrid, name: "BiGrid" },
{ icon: BiGroup, name: "BiGroup" },
{ icon: BiHandicap, name: "BiHandicap" },
{ icon: BiHappyAlt, name: "BiHappyAlt" },
{ icon: BiHappyBeaming, name: "BiHappyBeaming" },
{ icon: BiHappyHeartEyes, name: "BiHappyHeartEyes" },
{ icon: BiHappy, name: "BiHappy" },
{ icon: BiHash, name: "BiHash" },
{ icon: BiHdd, name: "BiHdd" },
{ icon: BiHeading, name: "BiHeading" },
{ icon: BiHeadphone, name: "BiHeadphone" },
{ icon: BiHealth, name: "BiHealth" },
{ icon: BiHeartCircle, name: "BiHeartCircle" },
{ icon: BiHeartSquare, name: "BiHeartSquare" },
{ icon: BiHeart, name: "BiHeart" },
{ icon: BiHelpCircle, name: "BiHelpCircle" },
{ icon: BiHide, name: "BiHide" },
{ icon: BiHighlight, name: "BiHighlight" },
{ icon: BiHistory, name: "BiHistory" },
{ icon: BiHive, name: "BiHive" },
{ icon: BiHomeAlt, name: "BiHomeAlt" },
{ icon: BiHomeCircle, name: "BiHomeCircle" },
{ icon: BiHomeHeart, name: "BiHomeHeart" },
{ icon: BiHomeSmile, name: "BiHomeSmile" },
{ icon: BiHome, name: "BiHome" },
{ icon: BiHorizontalCenter, name: "BiHorizontalCenter" },
{ icon: BiHotel, name: "BiHotel" },
{ icon: BiHourglass, name: "BiHourglass" },
{ icon: BiIdCard, name: "BiIdCard" },
{ icon: BiImageAdd, name: "BiImageAdd" },
{ icon: BiImageAlt, name: "BiImageAlt" },
{ icon: BiImage, name: "BiImage" },
{ icon: BiImages, name: "BiImages" },
{ icon: BiImport, name: "BiImport" },
{ icon: BiInfinite, name: "BiInfinite" },
{ icon: BiInfoCircle, name: "BiInfoCircle" },
{ icon: BiInfoSquare, name: "BiInfoSquare" },
{ icon: BiIntersect, name: "BiIntersect" },
{ icon: BiItalic, name: "BiItalic" },
{ icon: BiJoystickAlt, name: "BiJoystickAlt" },
{ icon: BiJoystickButton, name: "BiJoystickButton" },
{ icon: BiJoystick, name: "BiJoystick" },
{ icon: BiKey, name: "BiKey" },
{ icon: BiLabel, name: "BiLabel" },
{ icon: BiLandscape, name: "BiLandscape" },
{ icon: BiLaptop, name: "BiLaptop" },
{ icon: BiLastPage, name: "BiLastPage" },
{ icon: BiLaugh, name: "BiLaugh" },
{ icon: BiLayerMinus, name: "BiLayerMinus" },
{ icon: BiLayerPlus, name: "BiLayerPlus" },
{ icon: BiLayer, name: "BiLayer" },
{ icon: BiLayout, name: "BiLayout" },
{ icon: BiLeftArrowAlt, name: "BiLeftArrowAlt" },
{ icon: BiLeftArrowCircle, name: "BiLeftArrowCircle" },
{ icon: BiLeftArrow, name: "BiLeftArrow" },
{ icon: BiLeftDownArrowCircle, name: "BiLeftDownArrowCircle" },
{ icon: BiLeftIndent, name: "BiLeftIndent" },
{ icon: BiLeftTopArrowCircle, name: "BiLeftTopArrowCircle" },
{ icon: BiLibrary, name: "BiLibrary" },
{ icon: BiLike, name: "BiLike" },
{ icon: BiLineChartDown, name: "BiLineChartDown" },
{ icon: BiLineChart, name: "BiLineChart" },
{ icon: BiLinkAlt, name: "BiLinkAlt" },
{ icon: BiLinkExternal, name: "BiLinkExternal" },
{ icon: BiLink, name: "BiLink" },
{ icon: BiLira, name: "BiLira" },
{ icon: BiListCheck, name: "BiListCheck" },
{ icon: BiListMinus, name: "BiListMinus" },
{ icon: BiListOl, name: "BiListOl" },
{ icon: BiListPlus, name: "BiListPlus" },
{ icon: BiListUl, name: "BiListUl" },
{ icon: BiLoaderAlt, name: "BiLoaderAlt" },
{ icon: BiLoaderCircle, name: "BiLoaderCircle" },
{ icon: BiLoader, name: "BiLoader" },
{ icon: BiLocationPlus, name: "BiLocationPlus" },
{ icon: BiLockAlt, name: "BiLockAlt" },
{ icon: BiLockOpenAlt, name: "BiLockOpenAlt" },
{ icon: BiLockOpen, name: "BiLockOpen" },
{ icon: BiLock, name: "BiLock" },
{ icon: BiLogInCircle, name: "BiLogInCircle" },
{ icon: BiLogIn, name: "BiLogIn" },
{ icon: BiLogOutCircle, name: "BiLogOutCircle" },
{ icon: BiLogOut, name: "BiLogOut" },
{ icon: BiLowVision, name: "BiLowVision" },
{ icon: BiMagnet, name: "BiMagnet" },
{ icon: BiMailSend, name: "BiMailSend" },
{ icon: BiMaleSign, name: "BiMaleSign" },
{ icon: BiMale, name: "BiMale" },
{ icon: BiMapAlt, name: "BiMapAlt" },
{ icon: BiMapPin, name: "BiMapPin" },
{ icon: BiMap, name: "BiMap" },
{ icon: BiMask, name: "BiMask" },
{ icon: BiMedal, name: "BiMedal" },
{ icon: BiMehAlt, name: "BiMehAlt" },
{ icon: BiMehBlank, name: "BiMehBlank" },
{ icon: BiMeh, name: "BiMeh" },
{ icon: BiMemoryCard, name: "BiMemoryCard" },
{ icon: BiMenuAltLeft, name: "BiMenuAltLeft" },
{ icon: BiMenuAltRight, name: "BiMenuAltRight" },
{ icon: BiMenu, name: "BiMenu" },
{ icon: BiMerge, name: "BiMerge" },
{ icon: BiMessageAdd, name: "BiMessageAdd" },
{ icon: BiMessageAltAdd, name: "BiMessageAltAdd" },
{ icon: BiMessageAltCheck, name: "BiMessageAltCheck" },
{ icon: BiMessageAltDetail, name: "BiMessageAltDetail" },
{ icon: BiMessageAltDots, name: "BiMessageAltDots" },
{ icon: BiMessageAltEdit, name: "BiMessageAltEdit" },
{ icon: BiMessageAltError, name: "BiMessageAltError" },
{ icon: BiMessageAltMinus, name: "BiMessageAltMinus" },
{ icon: BiMessageAltX, name: "BiMessageAltX" },
{ icon: BiMessageAlt, name: "BiMessageAlt" },
{ icon: BiMessageCheck, name: "BiMessageCheck" },
{ icon: BiMessageDetail, name: "BiMessageDetail" },
{ icon: BiMessageDots, name: "BiMessageDots" },
{ icon: BiMessageEdit, name: "BiMessageEdit" },
{ icon: BiMessageError, name: "BiMessageError" },
{ icon: BiMessageMinus, name: "BiMessageMinus" },
{ icon: BiMessageRoundedAdd, name: "BiMessageRoundedAdd" },
{ icon: BiMessageRoundedCheck, name: "BiMessageRoundedCheck" },
{ icon: BiMessageRoundedDetail, name: "BiMessageRoundedDetail" },
{ icon: BiMessageRoundedDots, name: "BiMessageRoundedDots" },
{ icon: BiMessageRoundedEdit, name: "BiMessageRoundedEdit" },
{ icon: BiMessageRoundedError, name: "BiMessageRoundedError" },
{ icon: BiMessageRoundedMinus, name: "BiMessageRoundedMinus" },
{ icon: BiMessageRoundedX, name: "BiMessageRoundedX" },
{ icon: BiMessageRounded, name: "BiMessageRounded" },
{ icon: BiMessageSquareAdd, name: "BiMessageSquareAdd" },
{ icon: BiMessageSquareCheck, name: "BiMessageSquareCheck" },
{ icon: BiMessageSquareDetail, name: "BiMessageSquareDetail" },
{ icon: BiMessageSquareDots, name: "BiMessageSquareDots" },
{ icon: BiMessageSquareEdit, name: "BiMessageSquareEdit" },
{ icon: BiMessageSquareError, name: "BiMessageSquareError" },
{ icon: BiMessageSquareMinus, name: "BiMessageSquareMinus" },
{ icon: BiMessageSquareX, name: "BiMessageSquareX" },
{ icon: BiMessageSquare, name: "BiMessageSquare" },
{ icon: BiMessageX, name: "BiMessageX" },
{ icon: BiMessage, name: "BiMessage" },
{ icon: BiMeteor, name: "BiMeteor" },
{ icon: BiMicrochip, name: "BiMicrochip" },
{ icon: BiMicrophoneOff, name: "BiMicrophoneOff" },
{ icon: BiMicrophone, name: "BiMicrophone" },
{ icon: BiMinusBack, name: "BiMinusBack" },
{ icon: BiMinusCircle, name: "BiMinusCircle" },
{ icon: BiMinusFront, name: "BiMinusFront" },
{ icon: BiMinus, name: "BiMinus" },
{ icon: BiMobileAlt, name: "BiMobileAlt" },
{ icon: BiMobileLandscape, name: "BiMobileLandscape" },
{ icon: BiMobileVibration, name: "BiMobileVibration" },
{ icon: BiMobile, name: "BiMobile" },
{ icon: BiMoney, name: "BiMoney" },
{ icon: BiMoon, name: "BiMoon" },
{ icon: BiMouseAlt, name: "BiMouseAlt" },
{ icon: BiMouse, name: "BiMouse" },
{ icon: BiMoveHorizontal, name: "BiMoveHorizontal" },
{ icon: BiMoveVertical, name: "BiMoveVertical" },
{ icon: BiMove, name: "BiMove" },
{ icon: BiMoviePlay, name: "BiMoviePlay" },
{ icon: BiMovie, name: "BiMovie" },
{ icon: BiMusic, name: "BiMusic" },
{ icon: BiNavigation, name: "BiNavigation" },
{ icon: BiNetworkChart, name: "BiNetworkChart" },
{ icon: BiNews, name: "BiNews" },
{ icon: BiNoEntry, name: "BiNoEntry" },
{ icon: BiNote, name: "BiNote" },
{ icon: BiNotepad, name: "BiNotepad" },
{ icon: BiNotificationOff, name: "BiNotificationOff" },
{ icon: BiNotification, name: "BiNotification" },
{ icon: BiOutline, name: "BiOutline" },
{ icon: BiPackage, name: "BiPackage" },
{ icon: BiPaintRoll, name: "BiPaintRoll" },
{ icon: BiPaint, name: "BiPaint" },
{ icon: BiPalette, name: "BiPalette" },
{ icon: BiPaperPlane, name: "BiPaperPlane" },
{ icon: BiPaperclip, name: "BiPaperclip" },
{ icon: BiParagraph, name: "BiParagraph" },
{ icon: BiPaste, name: "BiPaste" },
{ icon: BiPauseCircle, name: "BiPauseCircle" },
{ icon: BiPause, name: "BiPause" },
{ icon: BiPen, name: "BiPen" },
{ icon: BiPencil, name: "BiPencil" },
{ icon: BiPhoneCall, name: "BiPhoneCall" },
{ icon: BiPhoneIncoming, name: "BiPhoneIncoming" },
{ icon: BiPhoneOff, name: "BiPhoneOff" },
{ icon: BiPhoneOutgoing, name: "BiPhoneOutgoing" },
{ icon: BiPhone, name: "BiPhone" },
{ icon: BiPhotoAlbum, name: "BiPhotoAlbum" },
{ icon: BiPieChartAlt2, name: "BiPieChartAlt2" },
{ icon: BiPieChartAlt, name: "BiPieChartAlt" },
{ icon: BiPieChart, name: "BiPieChart" },
{ icon: BiPin, name: "BiPin" },
{ icon: BiPlanet, name: "BiPlanet" },
{ icon: BiPlayCircle, name: "BiPlayCircle" },
{ icon: BiPlay, name: "BiPlay" },
{ icon: BiPlug, name: "BiPlug" },
{ icon: BiPlusCircle, name: "BiPlusCircle" },
{ icon: BiPlusMedical, name: "BiPlusMedical" },
{ icon: BiPlus, name: "BiPlus" },
{ icon: BiPodcast, name: "BiPodcast" },
{ icon: BiPointer, name: "BiPointer" },
{ icon: BiPoll, name: "BiPoll" },
{ icon: BiPolygon, name: "BiPolygon" },
{ icon: BiPound, name: "BiPound" },
{ icon: BiPowerOff, name: "BiPowerOff" },
{ icon: BiPrinter, name: "BiPrinter" },
{ icon: BiPulse, name: "BiPulse" },
{ icon: BiPurchaseTagAlt, name: "BiPurchaseTagAlt" },
{ icon: BiPurchaseTag, name: "BiPurchaseTag" },
{ icon: BiPyramid, name: "BiPyramid" },
{ icon: BiQrScan, name: "BiQrScan" },
{ icon: BiQr, name: "BiQr" },
{ icon: BiQuestionMark, name: "BiQuestionMark" },
{ icon: BiRadar, name: "BiRadar" },
{ icon: BiRadioCircleMarked, name: "BiRadioCircleMarked" },
{ icon: BiRadioCircle, name: "BiRadioCircle" },
{ icon: BiRadio, name: "BiRadio" },
{ icon: BiReceipt, name: "BiReceipt" },
{ icon: BiRectangle, name: "BiRectangle" },
{ icon: BiRecycle, name: "BiRecycle" },
{ icon: BiRedo, name: "BiRedo" },
{ icon: BiRefresh, name: "BiRefresh" },
{ icon: BiRegistered, name: "BiRegistered" },
{ icon: BiRename, name: "BiRename" },
{ icon: BiRepeat, name: "BiRepeat" },
{ icon: BiReplyAll, name: "BiReplyAll" },
{ icon: BiReply, name: "BiReply" },
{ icon: BiRepost, name: "BiRepost" },
{ icon: BiReset, name: "BiReset" },
{ icon: BiRestaurant, name: "BiRestaurant" },
{ icon: BiRevision, name: "BiRevision" },
{ icon: BiRewindCircle, name: "BiRewindCircle" },
{ icon: BiRewind, name: "BiRewind" },
{ icon: BiRightArrowAlt, name: "BiRightArrowAlt" },
{ icon: BiRightArrowCircle, name: "BiRightArrowCircle" },
{ icon: BiRightArrow, name: "BiRightArrow" },
{ icon: BiRightDownArrowCircle, name: "BiRightDownArrowCircle" },
{ icon: BiRightIndent, name: "BiRightIndent" },
{ icon: BiRightTopArrowCircle, name: "BiRightTopArrowCircle" },
{ icon: BiRocket, name: "BiRocket" },
{ icon: BiRotateLeft, name: "BiRotateLeft" },
{ icon: BiRotateRight, name: "BiRotateRight" },
{ icon: BiRss, name: "BiRss" },
{ icon: BiRuble, name: "BiRuble" },
{ icon: BiRuler, name: "BiRuler" },
{ icon: BiRun, name: "BiRun" },
{ icon: BiRupee, name: "BiRupee" },
{ icon: BiSad, name: "BiSad" },
{ icon: BiSave, name: "BiSave" },
{ icon: BiScan, name: "BiScan" },
{ icon: BiScreenshot, name: "BiScreenshot" },
{ icon: BiSearchAlt2, name: "BiSearchAlt2" },
{ icon: BiSearchAlt, name: "BiSearchAlt" },
{ icon: BiSearch, name: "BiSearch" },
{ icon: BiSelectMultiple, name: "BiSelectMultiple" },
{ icon: BiSelection, name: "BiSelection" },
{ icon: BiSend, name: "BiSend" },
{ icon: BiServer, name: "BiServer" },
{ icon: BiShapeCircle, name: "BiShapeCircle" },
{ icon: BiShapePolygon, name: "BiShapePolygon" },
{ icon: BiShapeSquare, name: "BiShapeSquare" },
{ icon: BiShapeTriangle, name: "BiShapeTriangle" },
{ icon: BiShareAlt, name: "BiShareAlt" },
{ icon: BiShare, name: "BiShare" },
{ icon: BiShekel, name: "BiShekel" },
{ icon: BiShieldAlt2, name: "BiShieldAlt2" },
{ icon: BiShieldAlt, name: "BiShieldAlt" },
{ icon: BiShieldQuarter, name: "BiShieldQuarter" },
{ icon: BiShieldX, name: "BiShieldX" },
{ icon: BiShield, name: "BiShield" },
{ icon: BiShocked, name: "BiShocked" },
{ icon: BiShoppingBag, name: "BiShoppingBag" },
{ icon: BiShowAlt, name: "BiShowAlt" },
{ icon: BiShow, name: "BiShow" },
{ icon: BiShuffle, name: "BiShuffle" },
{ icon: BiSidebar, name: "BiSidebar" },
{ icon: BiSitemap, name: "BiSitemap" },
{ icon: BiSkipNextCircle, name: "BiSkipNextCircle" },
{ icon: BiSkipNext, name: "BiSkipNext" },
{ icon: BiSkipPreviousCircle, name: "BiSkipPreviousCircle" },
{ icon: BiSkipPrevious, name: "BiSkipPrevious" },
{ icon: BiSleepy, name: "BiSleepy" },
{ icon: BiSliderAlt, name: "BiSliderAlt" },
{ icon: BiSlider, name: "BiSlider" },
{ icon: BiSlideshow, name: "BiSlideshow" },
{ icon: BiSmile, name: "BiSmile" },
{ icon: BiSortAZ, name: "BiSortAZ" },
{ icon: BiSortAlt2, name: "BiSortAlt2" },
{ icon: BiSortDown, name: "BiSortDown" },
{ icon: BiSortUp, name: "BiSortUp" },
{ icon: BiSortZA, name: "BiSortZA" },
{ icon: BiSort, name: "BiSort" },
{ icon: BiSpa, name: "BiSpa" },
{ icon: BiSpaceBar, name: "BiSpaceBar" },
{ icon: BiSpeaker, name: "BiSpeaker" },
{ icon: BiSprayCan, name: "BiSprayCan" },
{ icon: BiSpreadsheet, name: "BiSpreadsheet" },
{ icon: BiSquareRounded, name: "BiSquareRounded" },
{ icon: BiSquare, name: "BiSquare" },
{ icon: BiStar, name: "BiStar" },
{ icon: BiStation, name: "BiStation" },
{ icon: BiStats, name: "BiStats" },
{ icon: BiSticker, name: "BiSticker" },
{ icon: BiStopCircle, name: "BiStopCircle" },
{ icon: BiStop, name: "BiStop" },
{ icon: BiStopwatch, name: "BiStopwatch" },
{ icon: BiStoreAlt, name: "BiStoreAlt" },
{ icon: BiStore, name: "BiStore" },
{ icon: BiStreetView, name: "BiStreetView" },
{ icon: BiStrikethrough, name: "BiStrikethrough" },
{ icon: BiSubdirectoryLeft, name: "BiSubdirectoryLeft" },
{ icon: BiSubdirectoryRight, name: "BiSubdirectoryRight" },
{ icon: BiSun, name: "BiSun" },
{ icon: BiSupport, name: "BiSupport" },
{ icon: BiSwim, name: "BiSwim" },
{ icon: BiSync, name: "BiSync" },
{ icon: BiTab, name: "BiTab" },
{ icon: BiTable, name: "BiTable" },
{ icon: BiTachometer, name: "BiTachometer" },
{ icon: BiTagAlt, name: "BiTagAlt" },
{ icon: BiTag, name: "BiTag" },
{ icon: BiTargetLock, name: "BiTargetLock" },
{ icon: BiTaskX, name: "BiTaskX" },
{ icon: BiTask, name: "BiTask" },
{ icon: BiTaxi, name: "BiTaxi" },
{ icon: BiTennisBall, name: "BiTennisBall" },
{ icon: BiTerminal, name: "BiTerminal" },
{ icon: BiTestTube, name: "BiTestTube" },
{ icon: BiText, name: "BiText" },
{ icon: BiTimeFive, name: "BiTimeFive" },
{ icon: BiTime, name: "BiTime" },
{ icon: BiTimer, name: "BiTimer" },
{ icon: BiTired, name: "BiTired" },
{ icon: BiToggleLeft, name: "BiToggleLeft" },
{ icon: BiToggleRight, name: "BiToggleRight" },
{ icon: BiTone, name: "BiTone" },
{ icon: BiTrafficCone, name: "BiTrafficCone" },
{ icon: BiTrain, name: "BiTrain" },
{ icon: BiTransferAlt, name: "BiTransferAlt" },
{ icon: BiTransfer, name: "BiTransfer" },
{ icon: BiTrashAlt, name: "BiTrashAlt" },
{ icon: BiTrash, name: "BiTrash" },
{ icon: BiTrendingDown, name: "BiTrendingDown" },
{ icon: BiTrendingUp, name: "BiTrendingUp" },
{ icon: BiTrim, name: "BiTrim" },
{ icon: BiTrip, name: "BiTrip" },
{ icon: BiTrophy, name: "BiTrophy" },
{ icon: BiTv, name: "BiTv" },
{ icon: BiUnderline, name: "BiUnderline" },
{ icon: BiUndo, name: "BiUndo" },
{ icon: BiUnite, name: "BiUnite" },
{ icon: BiUnlink, name: "BiUnlink" },
{ icon: BiUpArrowAlt, name: "BiUpArrowAlt" },
{ icon: BiUpArrowCircle, name: "BiUpArrowCircle" },
{ icon: BiUpArrow, name: "BiUpArrow" },
{ icon: BiUpload, name: "BiUpload" },
{ icon: BiUpsideDown, name: "BiUpsideDown" },
{ icon: BiUpvote, name: "BiUpvote" },
{ icon: BiUsb, name: "BiUsb" },
{ icon: BiUserCheck, name: "BiUserCheck" },
{ icon: BiUserCircle, name: "BiUserCircle" },
{ icon: BiUserMinus, name: "BiUserMinus" },
{ icon: BiUserPin, name: "BiUserPin" },
{ icon: BiUserPlus, name: "BiUserPlus" },
{ icon: BiUserVoice, name: "BiUserVoice" },
{ icon: BiUserX, name: "BiUserX" },
{ icon: BiUser, name: "BiUser" },
{ icon: BiVector, name: "BiVector" },
{ icon: BiVerticalCenter, name: "BiVerticalCenter" },
{ icon: BiVial, name: "BiVial" },
{ icon: BiVideoOff, name: "BiVideoOff" },
{ icon: BiVideoPlus, name: "BiVideoPlus" },
{ icon: BiVideoRecording, name: "BiVideoRecording" },
{ icon: BiVideo, name: "BiVideo" },
{ icon: BiVoicemail, name: "BiVoicemail" },
{ icon: BiVolumeFull, name: "BiVolumeFull" },
{ icon: BiVolumeLow, name: "BiVolumeLow" },
{ icon: BiVolumeMute, name: "BiVolumeMute" },
{ icon: BiVolume, name: "BiVolume" },
{ icon: BiWalk, name: "BiWalk" },
{ icon: BiWalletAlt, name: "BiWalletAlt" },
{ icon: BiWallet, name: "BiWallet" },
{ icon: BiWater, name: "BiWater" },
{ icon: BiWebcam, name: "BiWebcam" },
{ icon: BiWifi0, name: "BiWifi0" },
{ icon: BiWifi1, name: "BiWifi1" },
{ icon: BiWifi2, name: "BiWifi2" },
{ icon: BiWifiOff, name: "BiWifiOff" },
{ icon: BiWifi, name: "BiWifi" },
{ icon: BiWind, name: "BiWind" },
{ icon: BiWindowAlt, name: "BiWindowAlt" },
{ icon: BiWindowClose, name: "BiWindowClose" },
{ icon: BiWindowOpen, name: "BiWindowOpen" },
{ icon: BiWindow, name: "BiWindow" },
{ icon: BiWindows, name: "BiWindows" },
{ icon: BiWine, name: "BiWine" },
{ icon: BiWinkSmile, name: "BiWinkSmile" },
{ icon: BiWinkTongue, name: "BiWinkTongue" },
{ icon: BiWon, name: "BiWon" },
{ icon: BiWorld, name: "BiWorld" },
{ icon: BiWrench, name: "BiWrench" },
{ icon: BiXCircle, name: "BiXCircle" },
{ icon: BiX, name: "BiX" },
{ icon: BiYen, name: "BiYen" },
{ icon: BiZoomIn, name: "BiZoomIn" },
{ icon: BiZoomOut, name: "BiZoomOut" },
];

export default result