import {
	BiAbacus,
	BiAccessibility,
	BiAddToQueue,
	BiAdjust,
	BiAlarmAdd,
	BiAlarmExclamation,
	BiAlarmOff,
	BiAlarmSnooze,
	BiAlarm,
	BiAlbum,
	BiAlignJustify,
	BiAlignLeft,
	BiAlignMiddle,
	BiAlignRight,
	BiAnalyse,
	BiAnchor,
	BiAngry,
	BiAperture,
	BiArch,
	BiArchiveIn,
	BiArchiveOut,
	BiArchive,
	BiArea,
	BiArrowBack,
	BiArrowFromBottom,
	BiArrowFromLeft,
	BiArrowFromRight,
	BiArrowFromTop,
	BiArrowToBottom,
	BiArrowToLeft,
	BiArrowToRight,
	BiArrowToTop,
	BiAt,
	BiAtom,
	BiAward,
	BiBadgeCheck,
	BiBadge,
	BiBall,
	BiBandAid,
	BiBarChartAlt2,
	BiBarChartAlt,
	BiBarChartSquare,
	BiBarChart,
	BiBarcodeReader,
	BiBarcode,
	BiBaseball,
	BiBasket,
	BiBasketball,
	BiBath,
	BiBattery,
	BiBed,
	BiBeenHere,
	BiBeer,
	BiBellMinus,
	BiBellOff,
	BiBellPlus,
	BiBell,
	BiBible,
	BiBitcoin,
	BiBlanket,
	BiBlock,
	BiBluetooth,
	BiBody,
	BiBold,
	BiBoltCircle,
	BiBomb,
	BiBone,
	BiBong,
	BiBookAdd,
	BiBookAlt,
	BiBookBookmark,
	BiBookContent,
	BiBookHeart,
	BiBookOpen,
	BiBookReader,
	BiBook,
	BiBookmarkAltMinus,
	BiBookmarkAltPlus,
	BiBookmarkAlt,
	BiBookmarkHeart,
	BiBookmarkMinus,
	BiBookmarkPlus,
	BiBookmark,
	BiBookmarks,
	BiBorderAll,
	BiBorderBottom,
	BiBorderInner,
	BiBorderLeft,
	BiBorderNone,
	BiBorderOuter,
	BiBorderRadius,
	BiBorderRight,
	BiBorderTop,
	BiBot,
	BiBowlingBall,
	BiBox,
	BiBracket,
	BiBraille,
	BiBrain,
	BiBriefcaseAlt2,
	BiBriefcaseAlt,
	BiBriefcase,
	BiBrightnessHalf,
	BiBrightness,
	BiBroadcast,
	BiBrushAlt,
	BiBrush,
	BiBugAlt,
	BiBug,
	BiBuildingHouse,
	BiBuilding,
	BiBuildings,
	BiBulb,
	BiBullseye,
	BiBuoy,
	BiBusSchool,
	BiBus,
	BiCabinet,
	BiCake,
	BiCalculator,
	BiCalendarAlt,
	BiCalendarCheck,
	BiCalendarEdit,
	BiCalendarEvent,
	BiCalendarExclamation,
	BiCalendarHeart,
	BiCalendarMinus,
	BiCalendarPlus,
	BiCalendarStar,
	BiCalendarWeek,
	BiCalendarX,
	BiCalendar,
	BiCameraHome,
	BiCameraMovie,
	BiCameraOff,
	BiCamera,
	BiCapsule,
	BiCaptions,
	BiCar,
	BiCard,
	BiCaretDownCircle,
	BiCaretDownSquare,
	BiCaretDown,
	BiCaretLeftCircle,
	BiCaretLeftSquare,
	BiCaretLeft,
	BiCaretRightCircle,
	BiCaretRightSquare,
	BiCaretRight,
	BiCaretUpCircle,
	BiCaretUpSquare,
	BiCaretUp,
	BiCarousel,
	BiCartAlt,
	BiCart,
	BiCast,
	BiCategoryAlt,
	BiCategory,
	BiCctv,
	BiCertification,
	BiChair,
	BiChalkboard,
	BiChart,
	BiChat,
	BiCheckCircle,
	BiCheckDouble,
	BiCheckShield,
	BiCheckSquare,
	BiCheck,
	BiCheckboxChecked,
	BiCheckboxMinus,
	BiCheckboxSquare,
	BiCheckbox,
	BiChevronDownCircle,
	BiChevronDownSquare,
	BiChevronDown,
	BiChevronLeftCircle,
	BiChevronLeftSquare,
	BiChevronLeft,
	BiChevronRightCircle,
	BiChevronRightSquare,
	BiChevronRight,
	BiChevronUpCircle,
	BiChevronUpSquare,
	BiChevronUp,
	BiChevronsDown,
	BiChevronsLeft,
	BiChevronsRight,
	BiChevronsUp,
	BiChip,
	BiChurch,
	BiCircle,
	BiClinic,
	BiClipboard,
	BiCloset,
	BiCloudDownload,
	BiCloudDrizzle,
	BiCloudLightRain,
	BiCloudLightning,
	BiCloudRain,
	BiCloudSnow,
	BiCloudUpload,
	BiCloud,
	BiCodeAlt,
	BiCodeBlock,
	BiCodeCurly,
	BiCode,
	BiCoffeeTogo,
	BiCoffee,
	BiCog,
	BiCoinStack,
	BiCoin,
	BiCollapse,
	BiCollection,
	BiColorFill,
	BiColumns,
	BiCommand,
	BiCommentAdd,
	BiCommentCheck,
	BiCommentDetail,
	BiCommentDots,
	BiCommentEdit,
	BiCommentError,
	BiCommentMinus,
	BiCommentX,
	BiComment,
	BiCompass,
	BiConfused,
	BiConversation,
	BiCookie,
	BiCool,
	BiCopyAlt,
	BiCopy,
	BiCopyright,
	BiCreditCardAlt,
	BiCreditCardFront,
	BiCreditCard,
	BiCrop,
	BiCrosshair,
	BiCrown,
	BiCubeAlt,
	BiCube,
	BiCuboid,
	BiCurrentLocation,
	BiCustomize,
	BiCut,
	BiCycling,
	BiCylinder,
	BiData,
	BiDesktop,
	BiDetail,
	BiDevices,
	BiDialpadAlt,
	BiDialpad,
	BiDiamond,
	BiDice1,
	BiDice2,
	BiDice3,
	BiDice4,
	BiDice5,
	BiDice6,
	BiDirections,
	BiDisc,
	BiDish,
	BiDislike,
	BiDizzy,
	BiDna,
	BiDockBottom,
	BiDockLeft,
	BiDockRight,
	BiDockTop,
	BiDollarCircle,
	BiDollar,
	BiDonateBlood,
	BiDonateHeart,
	BiDoorOpen,
	BiDotsHorizontalRounded,
	BiDotsHorizontal,
	BiDotsVerticalRounded,
	BiDotsVertical,
	BiDoughnutChart,
	BiDownArrowAlt,
	BiDownArrowCircle,
	BiDownArrow,
	BiDownload,
	BiDownvote,
	BiDrink,
	BiDroplet,
	BiDumbbell,
	BiDuplicate,
	BiEditAlt,
	BiEdit,
	BiEnvelopeOpen,
	BiEnvelope,
	BiEqualizer,
	BiEraser,
	BiErrorAlt,
	BiErrorCircle,
	BiError,
	BiEuro,
	BiExclude,
	BiExitFullscreen,
	BiExit,
	BiExpandAlt,
	BiExpand,
	BiExport,
	BiExtension,
	BiFace,
	BiFastForwardCircle,
	BiFastForward,
	BiFemaleSign,
	BiFemale,
	BiFileBlank,
	BiFileFind,
	BiFile,
	BiFilm,
	BiFilterAlt,
	BiFilter,
	BiFingerprint,
	BiFirstAid,
	BiFirstPage,
	BiFlag,
	BiFolderMinus,
	BiFolderOpen,
	BiFolderPlus,
	BiFolder,
	BiFontColor,
	BiFontFamily,
	BiFontSize,
	BiFont,
	BiFoodMenu,
	BiFoodTag,
	BiFootball,
	BiFridge,
	BiFullscreen,
	BiGame,
	BiGasPump,
	BiGhost,
	BiGift,
	BiGitBranch,
	BiGitCommit,
	BiGitCompare,
	BiGitMerge,
	BiGitPullRequest,
	BiGitRepoForked,
	BiGlassesAlt,
	BiGlasses,
	BiGlobeAlt,
	BiGlobe,
	BiGridAlt,
	BiGridHorizontal,
	BiGridSmall,
	BiGridVertical,
	BiGrid,
	BiGroup,
	BiHandicap,
	BiHappyAlt,
	BiHappyBeaming,
	BiHappyHeartEyes,
	BiHappy,
	BiHash,
	BiHdd,
	BiHeading,
	BiHeadphone,
	BiHealth,
	BiHeartCircle,
	BiHeartSquare,
	BiHeart,
	BiHelpCircle,
	BiHide,
	BiHighlight,
	BiHistory,
	BiHive,
	BiHomeAlt,
	BiHomeCircle,
	BiHomeHeart,
	BiHomeSmile,
	BiHome,
	BiHorizontalCenter,
	BiHotel,
	BiHourglass,
	BiIdCard,
	BiImageAdd,
	BiImageAlt,
	BiImage,
	BiImages,
	BiImport,
	BiInfinite,
	BiInfoCircle,
	BiInfoSquare,
	BiIntersect,
	BiItalic,
	BiJoystickAlt,
	BiJoystickButton,
	BiJoystick,
	BiKey,
	BiLabel,
	BiLandscape,
	BiLaptop,
	BiLastPage,
	BiLaugh,
	BiLayerMinus,
	BiLayerPlus,
	BiLayer,
	BiLayout,
	BiLeftArrowAlt,
	BiLeftArrowCircle,
	BiLeftArrow,
	BiLeftDownArrowCircle,
	BiLeftIndent,
	BiLeftTopArrowCircle,
	BiLibrary,
	BiLike,
	BiLineChartDown,
	BiLineChart,
	BiLinkAlt,
	BiLinkExternal,
	BiLink,
	BiLira,
	BiListCheck,
	BiListMinus,
	BiListOl,
	BiListPlus,
	BiListUl,
	BiLoaderAlt,
	BiLoaderCircle,
	BiLoader,
	BiLocationPlus,
	BiLockAlt,
	BiLockOpenAlt,
	BiLockOpen,
	BiLock,
	BiLogInCircle,
	BiLogIn,
	BiLogOutCircle,
	BiLogOut,
	BiLowVision,
	BiMagnet,
	BiMailSend,
	BiMaleSign,
	BiMale,
	BiMapAlt,
	BiMapPin,
	BiMap,
	BiMask,
	BiMedal,
	BiMehAlt,
	BiMehBlank,
	BiMeh,
	BiMemoryCard,
	BiMenuAltLeft,
	BiMenuAltRight,
	BiMenu,
	BiMerge,
	BiMessageAdd,
	BiMessageAltAdd,
	BiMessageAltCheck,
	BiMessageAltDetail,
	BiMessageAltDots,
	BiMessageAltEdit,
	BiMessageAltError,
	BiMessageAltMinus,
	BiMessageAltX,
	BiMessageAlt,
	BiMessageCheck,
	BiMessageDetail,
	BiMessageDots,
	BiMessageEdit,
	BiMessageError,
	BiMessageMinus,
	BiMessageRoundedAdd,
	BiMessageRoundedCheck,
	BiMessageRoundedDetail,
	BiMessageRoundedDots,
	BiMessageRoundedEdit,
	BiMessageRoundedError,
	BiMessageRoundedMinus,
	BiMessageRoundedX,
	BiMessageRounded,
	BiMessageSquareAdd,
	BiMessageSquareCheck,
	BiMessageSquareDetail,
	BiMessageSquareDots,
	BiMessageSquareEdit,
	BiMessageSquareError,
	BiMessageSquareMinus,
	BiMessageSquareX,
	BiMessageSquare,
	BiMessageX,
	BiMessage,
	BiMeteor,
	BiMicrochip,
	BiMicrophoneOff,
	BiMicrophone,
	BiMinusBack,
	BiMinusCircle,
	BiMinusFront,
	BiMinus,
	BiMobileAlt,
	BiMobileLandscape,
	BiMobileVibration,
	BiMobile,
	BiMoney,
	BiMoon,
	BiMouseAlt,
	BiMouse,
	BiMoveHorizontal,
	BiMoveVertical,
	BiMove,
	BiMoviePlay,
	BiMovie,
	BiMusic,
	BiNavigation,
	BiNetworkChart,
	BiNews,
	BiNoEntry,
	BiNote,
	BiNotepad,
	BiNotificationOff,
	BiNotification,
	BiOutline,
	BiPackage,
	BiPaintRoll,
	BiPaint,
	BiPalette,
	BiPaperPlane,
	BiPaperclip,
	BiParagraph,
	BiPaste,
	BiPauseCircle,
	BiPause,
	BiPen,
	BiPencil,
	BiPhoneCall,
	BiPhoneIncoming,
	BiPhoneOff,
	BiPhoneOutgoing,
	BiPhone,
	BiPhotoAlbum,
	BiPieChartAlt2,
	BiPieChartAlt,
	BiPieChart,
	BiPin,
	BiPlanet,
	BiPlayCircle,
	BiPlay,
	BiPlug,
	BiPlusCircle,
	BiPlusMedical,
	BiPlus,
	BiPodcast,
	BiPointer,
	BiPoll,
	BiPolygon,
	BiPound,
	BiPowerOff,
	BiPrinter,
	BiPulse,
	BiPurchaseTagAlt,
	BiPurchaseTag,
	BiPyramid,
	BiQrScan,
	BiQr,
	BiQuestionMark,
	BiRadar,
	BiRadioCircleMarked,
	BiRadioCircle,
	BiRadio,
	BiReceipt,
	BiRectangle,
	BiRecycle,
	BiRedo,
	BiRefresh,
	BiRegistered,
	BiRename,
	BiRepeat,
	BiReplyAll,
	BiReply,
	BiRepost,
	BiReset,
	BiRestaurant,
	BiRevision,
	BiRewindCircle,
	BiRewind,
	BiRightArrowAlt,
	BiRightArrowCircle,
	BiRightArrow,
	BiRightDownArrowCircle,
	BiRightIndent,
	BiRightTopArrowCircle,
	BiRocket,
	BiRotateLeft,
	BiRotateRight,
	BiRss,
	BiRuble,
	BiRuler,
	BiRun,
	BiRupee,
	BiSad,
	BiSave,
	BiScan,
	BiScreenshot,
	BiSearchAlt2,
	BiSearchAlt,
	BiSearch,
	BiSelectMultiple,
	BiSelection,
	BiSend,
	BiServer,
	BiShapeCircle,
	BiShapePolygon,
	BiShapeSquare,
	BiShapeTriangle,
	BiShareAlt,
	BiShare,
	BiShekel,
	BiShieldAlt2,
	BiShieldAlt,
	BiShieldQuarter,
	BiShieldX,
	BiShield,
	BiShocked,
	BiShoppingBag,
	BiShowAlt,
	BiShow,
	BiShuffle,
	BiSidebar,
	BiSitemap,
	BiSkipNextCircle,
	BiSkipNext,
	BiSkipPreviousCircle,
	BiSkipPrevious,
	BiSleepy,
	BiSliderAlt,
	BiSlider,
	BiSlideshow,
	BiSmile,
	BiSortAZ,
	BiSortAlt2,
	BiSortDown,
	BiSortUp,
	BiSortZA,
	BiSort,
	BiSpa,
	BiSpaceBar,
	BiSpeaker,
	BiSprayCan,
	BiSpreadsheet,
	BiSquareRounded,
	BiSquare,
	BiStar,
	BiStation,
	BiStats,
	BiSticker,
	BiStopCircle,
	BiStop,
	BiStopwatch,
	BiStoreAlt,
	BiStore,
	BiStreetView,
	BiStrikethrough,
	BiSubdirectoryLeft,
	BiSubdirectoryRight,
	BiSun,
	BiSupport,
	BiSwim,
	BiSync,
	BiTab,
	BiTable,
	BiTachometer,
	BiTagAlt,
	BiTag,
	BiTargetLock,
	BiTaskX,
	BiTask,
	BiTaxi,
	BiTennisBall,
	BiTerminal,
	BiTestTube,
	BiText,
	BiTimeFive,
	BiTime,
	BiTimer,
	BiTired,
	BiToggleLeft,
	BiToggleRight,
	BiTone,
	BiTrafficCone,
	BiTrain,
	BiTransferAlt,
	BiTransfer,
	BiTrashAlt,
	BiTrash,
	BiTrendingDown,
	BiTrendingUp,
	BiTrim,
	BiTrip,
	BiTrophy,
	BiTv,
	BiUnderline,
	BiUndo,
	BiUnite,
	BiUnlink,
	BiUpArrowAlt,
	BiUpArrowCircle,
	BiUpArrow,
	BiUpload,
	BiUpsideDown,
	BiUpvote,
	BiUsb,
	BiUserCheck,
	BiUserCircle,
	BiUserMinus,
	BiUserPin,
	BiUserPlus,
	BiUserVoice,
	BiUserX,
	BiUser,
	BiVector,
	BiVerticalCenter,
	BiVial,
	BiVideoOff,
	BiVideoPlus,
	BiVideoRecording,
	BiVideo,
	BiVoicemail,
	BiVolumeFull,
	BiVolumeLow,
	BiVolumeMute,
	BiVolume,
	BiWalk,
	BiWalletAlt,
	BiWallet,
	BiWater,
	BiWebcam,
	BiWifi0,
	BiWifi1,
	BiWifi2,
	BiWifiOff,
	BiWifi,
	BiWind,
	BiWindowAlt,
	BiWindowClose,
	BiWindowOpen,
	BiWindow,
	BiWindows,
	BiWine,
	BiWinkSmile,
	BiWinkTongue,
	BiWon,
	BiWorld,
	BiWrench,
	BiXCircle,
	BiX,
	BiYen,
	BiZoomIn,
	BiZoomOut,
} from "react-icons/bi";

const result = [
	{ icon: BiAbacus, name: "BiAbacus", library: "bi" },
	{ icon: BiAccessibility, name: "BiAccessibility", library: "bi" },
	{ icon: BiAddToQueue, name: "BiAddToQueue", library: "bi" },
	{ icon: BiAdjust, name: "BiAdjust", library: "bi" },
	{ icon: BiAlarmAdd, name: "BiAlarmAdd", library: "bi" },
	{ icon: BiAlarmExclamation, name: "BiAlarmExclamation", library: "bi" },
	{ icon: BiAlarmOff, name: "BiAlarmOff", library: "bi" },
	{ icon: BiAlarmSnooze, name: "BiAlarmSnooze", library: "bi" },
	{ icon: BiAlarm, name: "BiAlarm", library: "bi" },
	{ icon: BiAlbum, name: "BiAlbum", library: "bi" },
	{ icon: BiAlignJustify, name: "BiAlignJustify", library: "bi" },
	{ icon: BiAlignLeft, name: "BiAlignLeft", library: "bi" },
	{ icon: BiAlignMiddle, name: "BiAlignMiddle", library: "bi" },
	{ icon: BiAlignRight, name: "BiAlignRight", library: "bi" },
	{ icon: BiAnalyse, name: "BiAnalyse", library: "bi" },
	{ icon: BiAnchor, name: "BiAnchor", library: "bi" },
	{ icon: BiAngry, name: "BiAngry", library: "bi" },
	{ icon: BiAperture, name: "BiAperture", library: "bi" },
	{ icon: BiArch, name: "BiArch", library: "bi" },
	{ icon: BiArchiveIn, name: "BiArchiveIn", library: "bi" },
	{ icon: BiArchiveOut, name: "BiArchiveOut", library: "bi" },
	{ icon: BiArchive, name: "BiArchive", library: "bi" },
	{ icon: BiArea, name: "BiArea", library: "bi" },
	{ icon: BiArrowBack, name: "BiArrowBack", library: "bi" },
	{ icon: BiArrowFromBottom, name: "BiArrowFromBottom", library: "bi" },
	{ icon: BiArrowFromLeft, name: "BiArrowFromLeft", library: "bi" },
	{ icon: BiArrowFromRight, name: "BiArrowFromRight", library: "bi" },
	{ icon: BiArrowFromTop, name: "BiArrowFromTop", library: "bi" },
	{ icon: BiArrowToBottom, name: "BiArrowToBottom", library: "bi" },
	{ icon: BiArrowToLeft, name: "BiArrowToLeft", library: "bi" },
	{ icon: BiArrowToRight, name: "BiArrowToRight", library: "bi" },
	{ icon: BiArrowToTop, name: "BiArrowToTop", library: "bi" },
	{ icon: BiAt, name: "BiAt", library: "bi" },
	{ icon: BiAtom, name: "BiAtom", library: "bi" },
	{ icon: BiAward, name: "BiAward", library: "bi" },
	{ icon: BiBadgeCheck, name: "BiBadgeCheck", library: "bi" },
	{ icon: BiBadge, name: "BiBadge", library: "bi" },
	{ icon: BiBall, name: "BiBall", library: "bi" },
	{ icon: BiBandAid, name: "BiBandAid", library: "bi" },
	{ icon: BiBarChartAlt2, name: "BiBarChartAlt2", library: "bi" },
	{ icon: BiBarChartAlt, name: "BiBarChartAlt", library: "bi" },
	{ icon: BiBarChartSquare, name: "BiBarChartSquare", library: "bi" },
	{ icon: BiBarChart, name: "BiBarChart", library: "bi" },
	{ icon: BiBarcodeReader, name: "BiBarcodeReader", library: "bi" },
	{ icon: BiBarcode, name: "BiBarcode", library: "bi" },
	{ icon: BiBaseball, name: "BiBaseball", library: "bi" },
	{ icon: BiBasket, name: "BiBasket", library: "bi" },
	{ icon: BiBasketball, name: "BiBasketball", library: "bi" },
	{ icon: BiBath, name: "BiBath", library: "bi" },
	{ icon: BiBattery, name: "BiBattery", library: "bi" },
	{ icon: BiBed, name: "BiBed", library: "bi" },
	{ icon: BiBeenHere, name: "BiBeenHere", library: "bi" },
	{ icon: BiBeer, name: "BiBeer", library: "bi" },
	{ icon: BiBellMinus, name: "BiBellMinus", library: "bi" },
	{ icon: BiBellOff, name: "BiBellOff", library: "bi" },
	{ icon: BiBellPlus, name: "BiBellPlus", library: "bi" },
	{ icon: BiBell, name: "BiBell", library: "bi" },
	{ icon: BiBible, name: "BiBible", library: "bi" },
	{ icon: BiBitcoin, name: "BiBitcoin", library: "bi" },
	{ icon: BiBlanket, name: "BiBlanket", library: "bi" },
	{ icon: BiBlock, name: "BiBlock", library: "bi" },
	{ icon: BiBluetooth, name: "BiBluetooth", library: "bi" },
	{ icon: BiBody, name: "BiBody", library: "bi" },
	{ icon: BiBold, name: "BiBold", library: "bi" },
	{ icon: BiBoltCircle, name: "BiBoltCircle", library: "bi" },
	{ icon: BiBomb, name: "BiBomb", library: "bi" },
	{ icon: BiBone, name: "BiBone", library: "bi" },
	{ icon: BiBong, name: "BiBong", library: "bi" },
	{ icon: BiBookAdd, name: "BiBookAdd", library: "bi" },
	{ icon: BiBookAlt, name: "BiBookAlt", library: "bi" },
	{ icon: BiBookBookmark, name: "BiBookBookmark", library: "bi" },
	{ icon: BiBookContent, name: "BiBookContent", library: "bi" },
	{ icon: BiBookHeart, name: "BiBookHeart", library: "bi" },
	{ icon: BiBookOpen, name: "BiBookOpen", library: "bi" },
	{ icon: BiBookReader, name: "BiBookReader", library: "bi" },
	{ icon: BiBook, name: "BiBook", library: "bi" },
	{ icon: BiBookmarkAltMinus, name: "BiBookmarkAltMinus", library: "bi" },
	{ icon: BiBookmarkAltPlus, name: "BiBookmarkAltPlus", library: "bi" },
	{ icon: BiBookmarkAlt, name: "BiBookmarkAlt", library: "bi" },
	{ icon: BiBookmarkHeart, name: "BiBookmarkHeart", library: "bi" },
	{ icon: BiBookmarkMinus, name: "BiBookmarkMinus", library: "bi" },
	{ icon: BiBookmarkPlus, name: "BiBookmarkPlus", library: "bi" },
	{ icon: BiBookmark, name: "BiBookmark", library: "bi" },
	{ icon: BiBookmarks, name: "BiBookmarks", library: "bi" },
	{ icon: BiBorderAll, name: "BiBorderAll", library: "bi" },
	{ icon: BiBorderBottom, name: "BiBorderBottom", library: "bi" },
	{ icon: BiBorderInner, name: "BiBorderInner", library: "bi" },
	{ icon: BiBorderLeft, name: "BiBorderLeft", library: "bi" },
	{ icon: BiBorderNone, name: "BiBorderNone", library: "bi" },
	{ icon: BiBorderOuter, name: "BiBorderOuter", library: "bi" },
	{ icon: BiBorderRadius, name: "BiBorderRadius", library: "bi" },
	{ icon: BiBorderRight, name: "BiBorderRight", library: "bi" },
	{ icon: BiBorderTop, name: "BiBorderTop", library: "bi" },
	{ icon: BiBot, name: "BiBot", library: "bi" },
	{ icon: BiBowlingBall, name: "BiBowlingBall", library: "bi" },
	{ icon: BiBox, name: "BiBox", library: "bi" },
	{ icon: BiBracket, name: "BiBracket", library: "bi" },
	{ icon: BiBraille, name: "BiBraille", library: "bi" },
	{ icon: BiBrain, name: "BiBrain", library: "bi" },
	{ icon: BiBriefcaseAlt2, name: "BiBriefcaseAlt2", library: "bi" },
	{ icon: BiBriefcaseAlt, name: "BiBriefcaseAlt", library: "bi" },
	{ icon: BiBriefcase, name: "BiBriefcase", library: "bi" },
	{ icon: BiBrightnessHalf, name: "BiBrightnessHalf", library: "bi" },
	{ icon: BiBrightness, name: "BiBrightness", library: "bi" },
	{ icon: BiBroadcast, name: "BiBroadcast", library: "bi" },
	{ icon: BiBrushAlt, name: "BiBrushAlt", library: "bi" },
	{ icon: BiBrush, name: "BiBrush", library: "bi" },
	{ icon: BiBugAlt, name: "BiBugAlt", library: "bi" },
	{ icon: BiBug, name: "BiBug", library: "bi" },
	{ icon: BiBuildingHouse, name: "BiBuildingHouse", library: "bi" },
	{ icon: BiBuilding, name: "BiBuilding", library: "bi" },
	{ icon: BiBuildings, name: "BiBuildings", library: "bi" },
	{ icon: BiBulb, name: "BiBulb", library: "bi" },
	{ icon: BiBullseye, name: "BiBullseye", library: "bi" },
	{ icon: BiBuoy, name: "BiBuoy", library: "bi" },
	{ icon: BiBusSchool, name: "BiBusSchool", library: "bi" },
	{ icon: BiBus, name: "BiBus", library: "bi" },
	{ icon: BiCabinet, name: "BiCabinet", library: "bi" },
	{ icon: BiCake, name: "BiCake", library: "bi" },
	{ icon: BiCalculator, name: "BiCalculator", library: "bi" },
	{ icon: BiCalendarAlt, name: "BiCalendarAlt", library: "bi" },
	{ icon: BiCalendarCheck, name: "BiCalendarCheck", library: "bi" },
	{ icon: BiCalendarEdit, name: "BiCalendarEdit", library: "bi" },
	{ icon: BiCalendarEvent, name: "BiCalendarEvent", library: "bi" },
	{ icon: BiCalendarExclamation, name: "BiCalendarExclamation", library: "bi" },
	{ icon: BiCalendarHeart, name: "BiCalendarHeart", library: "bi" },
	{ icon: BiCalendarMinus, name: "BiCalendarMinus", library: "bi" },
	{ icon: BiCalendarPlus, name: "BiCalendarPlus", library: "bi" },
	{ icon: BiCalendarStar, name: "BiCalendarStar", library: "bi" },
	{ icon: BiCalendarWeek, name: "BiCalendarWeek", library: "bi" },
	{ icon: BiCalendarX, name: "BiCalendarX", library: "bi" },
	{ icon: BiCalendar, name: "BiCalendar", library: "bi" },
	{ icon: BiCameraHome, name: "BiCameraHome", library: "bi" },
	{ icon: BiCameraMovie, name: "BiCameraMovie", library: "bi" },
	{ icon: BiCameraOff, name: "BiCameraOff", library: "bi" },
	{ icon: BiCamera, name: "BiCamera", library: "bi" },
	{ icon: BiCapsule, name: "BiCapsule", library: "bi" },
	{ icon: BiCaptions, name: "BiCaptions", library: "bi" },
	{ icon: BiCar, name: "BiCar", library: "bi" },
	{ icon: BiCard, name: "BiCard", library: "bi" },
	{ icon: BiCaretDownCircle, name: "BiCaretDownCircle", library: "bi" },
	{ icon: BiCaretDownSquare, name: "BiCaretDownSquare", library: "bi" },
	{ icon: BiCaretDown, name: "BiCaretDown", library: "bi" },
	{ icon: BiCaretLeftCircle, name: "BiCaretLeftCircle", library: "bi" },
	{ icon: BiCaretLeftSquare, name: "BiCaretLeftSquare", library: "bi" },
	{ icon: BiCaretLeft, name: "BiCaretLeft", library: "bi" },
	{ icon: BiCaretRightCircle, name: "BiCaretRightCircle", library: "bi" },
	{ icon: BiCaretRightSquare, name: "BiCaretRightSquare", library: "bi" },
	{ icon: BiCaretRight, name: "BiCaretRight", library: "bi" },
	{ icon: BiCaretUpCircle, name: "BiCaretUpCircle", library: "bi" },
	{ icon: BiCaretUpSquare, name: "BiCaretUpSquare", library: "bi" },
	{ icon: BiCaretUp, name: "BiCaretUp", library: "bi" },
	{ icon: BiCarousel, name: "BiCarousel", library: "bi" },
	{ icon: BiCartAlt, name: "BiCartAlt", library: "bi" },
	{ icon: BiCart, name: "BiCart", library: "bi" },
	{ icon: BiCast, name: "BiCast", library: "bi" },
	{ icon: BiCategoryAlt, name: "BiCategoryAlt", library: "bi" },
	{ icon: BiCategory, name: "BiCategory", library: "bi" },
	{ icon: BiCctv, name: "BiCctv", library: "bi" },
	{ icon: BiCertification, name: "BiCertification", library: "bi" },
	{ icon: BiChair, name: "BiChair", library: "bi" },
	{ icon: BiChalkboard, name: "BiChalkboard", library: "bi" },
	{ icon: BiChart, name: "BiChart", library: "bi" },
	{ icon: BiChat, name: "BiChat", library: "bi" },
	{ icon: BiCheckCircle, name: "BiCheckCircle", library: "bi" },
	{ icon: BiCheckDouble, name: "BiCheckDouble", library: "bi" },
	{ icon: BiCheckShield, name: "BiCheckShield", library: "bi" },
	{ icon: BiCheckSquare, name: "BiCheckSquare", library: "bi" },
	{ icon: BiCheck, name: "BiCheck", library: "bi" },
	{ icon: BiCheckboxChecked, name: "BiCheckboxChecked", library: "bi" },
	{ icon: BiCheckboxMinus, name: "BiCheckboxMinus", library: "bi" },
	{ icon: BiCheckboxSquare, name: "BiCheckboxSquare", library: "bi" },
	{ icon: BiCheckbox, name: "BiCheckbox", library: "bi" },
	{ icon: BiChevronDownCircle, name: "BiChevronDownCircle", library: "bi" },
	{ icon: BiChevronDownSquare, name: "BiChevronDownSquare", library: "bi" },
	{ icon: BiChevronDown, name: "BiChevronDown", library: "bi" },
	{ icon: BiChevronLeftCircle, name: "BiChevronLeftCircle", library: "bi" },
	{ icon: BiChevronLeftSquare, name: "BiChevronLeftSquare", library: "bi" },
	{ icon: BiChevronLeft, name: "BiChevronLeft", library: "bi" },
	{ icon: BiChevronRightCircle, name: "BiChevronRightCircle", library: "bi" },
	{ icon: BiChevronRightSquare, name: "BiChevronRightSquare", library: "bi" },
	{ icon: BiChevronRight, name: "BiChevronRight", library: "bi" },
	{ icon: BiChevronUpCircle, name: "BiChevronUpCircle", library: "bi" },
	{ icon: BiChevronUpSquare, name: "BiChevronUpSquare", library: "bi" },
	{ icon: BiChevronUp, name: "BiChevronUp", library: "bi" },
	{ icon: BiChevronsDown, name: "BiChevronsDown", library: "bi" },
	{ icon: BiChevronsLeft, name: "BiChevronsLeft", library: "bi" },
	{ icon: BiChevronsRight, name: "BiChevronsRight", library: "bi" },
	{ icon: BiChevronsUp, name: "BiChevronsUp", library: "bi" },
	{ icon: BiChip, name: "BiChip", library: "bi" },
	{ icon: BiChurch, name: "BiChurch", library: "bi" },
	{ icon: BiCircle, name: "BiCircle", library: "bi" },
	{ icon: BiClinic, name: "BiClinic", library: "bi" },
	{ icon: BiClipboard, name: "BiClipboard", library: "bi" },
	{ icon: BiCloset, name: "BiCloset", library: "bi" },
	{ icon: BiCloudDownload, name: "BiCloudDownload", library: "bi" },
	{ icon: BiCloudDrizzle, name: "BiCloudDrizzle", library: "bi" },
	{ icon: BiCloudLightRain, name: "BiCloudLightRain", library: "bi" },
	{ icon: BiCloudLightning, name: "BiCloudLightning", library: "bi" },
	{ icon: BiCloudRain, name: "BiCloudRain", library: "bi" },
	{ icon: BiCloudSnow, name: "BiCloudSnow", library: "bi" },
	{ icon: BiCloudUpload, name: "BiCloudUpload", library: "bi" },
	{ icon: BiCloud, name: "BiCloud", library: "bi" },
	{ icon: BiCodeAlt, name: "BiCodeAlt", library: "bi" },
	{ icon: BiCodeBlock, name: "BiCodeBlock", library: "bi" },
	{ icon: BiCodeCurly, name: "BiCodeCurly", library: "bi" },
	{ icon: BiCode, name: "BiCode", library: "bi" },
	{ icon: BiCoffeeTogo, name: "BiCoffeeTogo", library: "bi" },
	{ icon: BiCoffee, name: "BiCoffee", library: "bi" },
	{ icon: BiCog, name: "BiCog", library: "bi" },
	{ icon: BiCoinStack, name: "BiCoinStack", library: "bi" },
	{ icon: BiCoin, name: "BiCoin", library: "bi" },
	{ icon: BiCollapse, name: "BiCollapse", library: "bi" },
	{ icon: BiCollection, name: "BiCollection", library: "bi" },
	{ icon: BiColorFill, name: "BiColorFill", library: "bi" },
	{ icon: BiColumns, name: "BiColumns", library: "bi" },
	{ icon: BiCommand, name: "BiCommand", library: "bi" },
	{ icon: BiCommentAdd, name: "BiCommentAdd", library: "bi" },
	{ icon: BiCommentCheck, name: "BiCommentCheck", library: "bi" },
	{ icon: BiCommentDetail, name: "BiCommentDetail", library: "bi" },
	{ icon: BiCommentDots, name: "BiCommentDots", library: "bi" },
	{ icon: BiCommentEdit, name: "BiCommentEdit", library: "bi" },
	{ icon: BiCommentError, name: "BiCommentError", library: "bi" },
	{ icon: BiCommentMinus, name: "BiCommentMinus", library: "bi" },
	{ icon: BiCommentX, name: "BiCommentX", library: "bi" },
	{ icon: BiComment, name: "BiComment", library: "bi" },
	{ icon: BiCompass, name: "BiCompass", library: "bi" },
	{ icon: BiConfused, name: "BiConfused", library: "bi" },
	{ icon: BiConversation, name: "BiConversation", library: "bi" },
	{ icon: BiCookie, name: "BiCookie", library: "bi" },
	{ icon: BiCool, name: "BiCool", library: "bi" },
	{ icon: BiCopyAlt, name: "BiCopyAlt", library: "bi" },
	{ icon: BiCopy, name: "BiCopy", library: "bi" },
	{ icon: BiCopyright, name: "BiCopyright", library: "bi" },
	{ icon: BiCreditCardAlt, name: "BiCreditCardAlt", library: "bi" },
	{ icon: BiCreditCardFront, name: "BiCreditCardFront", library: "bi" },
	{ icon: BiCreditCard, name: "BiCreditCard", library: "bi" },
	{ icon: BiCrop, name: "BiCrop", library: "bi" },
	{ icon: BiCrosshair, name: "BiCrosshair", library: "bi" },
	{ icon: BiCrown, name: "BiCrown", library: "bi" },
	{ icon: BiCubeAlt, name: "BiCubeAlt", library: "bi" },
	{ icon: BiCube, name: "BiCube", library: "bi" },
	{ icon: BiCuboid, name: "BiCuboid", library: "bi" },
	{ icon: BiCurrentLocation, name: "BiCurrentLocation", library: "bi" },
	{ icon: BiCustomize, name: "BiCustomize", library: "bi" },
	{ icon: BiCut, name: "BiCut", library: "bi" },
	{ icon: BiCycling, name: "BiCycling", library: "bi" },
	{ icon: BiCylinder, name: "BiCylinder", library: "bi" },
	{ icon: BiData, name: "BiData", library: "bi" },
	{ icon: BiDesktop, name: "BiDesktop", library: "bi" },
	{ icon: BiDetail, name: "BiDetail", library: "bi" },
	{ icon: BiDevices, name: "BiDevices", library: "bi" },
	{ icon: BiDialpadAlt, name: "BiDialpadAlt", library: "bi" },
	{ icon: BiDialpad, name: "BiDialpad", library: "bi" },
	{ icon: BiDiamond, name: "BiDiamond", library: "bi" },
	{ icon: BiDice1, name: "BiDice1", library: "bi" },
	{ icon: BiDice2, name: "BiDice2", library: "bi" },
	{ icon: BiDice3, name: "BiDice3", library: "bi" },
	{ icon: BiDice4, name: "BiDice4", library: "bi" },
	{ icon: BiDice5, name: "BiDice5", library: "bi" },
	{ icon: BiDice6, name: "BiDice6", library: "bi" },
	{ icon: BiDirections, name: "BiDirections", library: "bi" },
	{ icon: BiDisc, name: "BiDisc", library: "bi" },
	{ icon: BiDish, name: "BiDish", library: "bi" },
	{ icon: BiDislike, name: "BiDislike", library: "bi" },
	{ icon: BiDizzy, name: "BiDizzy", library: "bi" },
	{ icon: BiDna, name: "BiDna", library: "bi" },
	{ icon: BiDockBottom, name: "BiDockBottom", library: "bi" },
	{ icon: BiDockLeft, name: "BiDockLeft", library: "bi" },
	{ icon: BiDockRight, name: "BiDockRight", library: "bi" },
	{ icon: BiDockTop, name: "BiDockTop", library: "bi" },
	{ icon: BiDollarCircle, name: "BiDollarCircle", library: "bi" },
	{ icon: BiDollar, name: "BiDollar", library: "bi" },
	{ icon: BiDonateBlood, name: "BiDonateBlood", library: "bi" },
	{ icon: BiDonateHeart, name: "BiDonateHeart", library: "bi" },
	{ icon: BiDoorOpen, name: "BiDoorOpen", library: "bi" },
	{ icon: BiDotsHorizontalRounded, name: "BiDotsHorizontalRounded", library: "bi" },
	{ icon: BiDotsHorizontal, name: "BiDotsHorizontal", library: "bi" },
	{ icon: BiDotsVerticalRounded, name: "BiDotsVerticalRounded", library: "bi" },
	{ icon: BiDotsVertical, name: "BiDotsVertical", library: "bi" },
	{ icon: BiDoughnutChart, name: "BiDoughnutChart", library: "bi" },
	{ icon: BiDownArrowAlt, name: "BiDownArrowAlt", library: "bi" },
	{ icon: BiDownArrowCircle, name: "BiDownArrowCircle", library: "bi" },
	{ icon: BiDownArrow, name: "BiDownArrow", library: "bi" },
	{ icon: BiDownload, name: "BiDownload", library: "bi" },
	{ icon: BiDownvote, name: "BiDownvote", library: "bi" },
	{ icon: BiDrink, name: "BiDrink", library: "bi" },
	{ icon: BiDroplet, name: "BiDroplet", library: "bi" },
	{ icon: BiDumbbell, name: "BiDumbbell", library: "bi" },
	{ icon: BiDuplicate, name: "BiDuplicate", library: "bi" },
	{ icon: BiEditAlt, name: "BiEditAlt", library: "bi" },
	{ icon: BiEdit, name: "BiEdit", library: "bi" },
	{ icon: BiEnvelopeOpen, name: "BiEnvelopeOpen", library: "bi" },
	{ icon: BiEnvelope, name: "BiEnvelope", library: "bi" },
	{ icon: BiEqualizer, name: "BiEqualizer", library: "bi" },
	{ icon: BiEraser, name: "BiEraser", library: "bi" },
	{ icon: BiErrorAlt, name: "BiErrorAlt", library: "bi" },
	{ icon: BiErrorCircle, name: "BiErrorCircle", library: "bi" },
	{ icon: BiError, name: "BiError", library: "bi" },
	{ icon: BiEuro, name: "BiEuro", library: "bi" },
	{ icon: BiExclude, name: "BiExclude", library: "bi" },
	{ icon: BiExitFullscreen, name: "BiExitFullscreen", library: "bi" },
	{ icon: BiExit, name: "BiExit", library: "bi" },
	{ icon: BiExpandAlt, name: "BiExpandAlt", library: "bi" },
	{ icon: BiExpand, name: "BiExpand", library: "bi" },
	{ icon: BiExport, name: "BiExport", library: "bi" },
	{ icon: BiExtension, name: "BiExtension", library: "bi" },
	{ icon: BiFace, name: "BiFace", library: "bi" },
	{ icon: BiFastForwardCircle, name: "BiFastForwardCircle", library: "bi" },
	{ icon: BiFastForward, name: "BiFastForward", library: "bi" },
	{ icon: BiFemaleSign, name: "BiFemaleSign", library: "bi" },
	{ icon: BiFemale, name: "BiFemale", library: "bi" },
	{ icon: BiFileBlank, name: "BiFileBlank", library: "bi" },
	{ icon: BiFileFind, name: "BiFileFind", library: "bi" },
	{ icon: BiFile, name: "BiFile", library: "bi" },
	{ icon: BiFilm, name: "BiFilm", library: "bi" },
	{ icon: BiFilterAlt, name: "BiFilterAlt", library: "bi" },
	{ icon: BiFilter, name: "BiFilter", library: "bi" },
	{ icon: BiFingerprint, name: "BiFingerprint", library: "bi" },
	{ icon: BiFirstAid, name: "BiFirstAid", library: "bi" },
	{ icon: BiFirstPage, name: "BiFirstPage", library: "bi" },
	{ icon: BiFlag, name: "BiFlag", library: "bi" },
	{ icon: BiFolderMinus, name: "BiFolderMinus", library: "bi" },
	{ icon: BiFolderOpen, name: "BiFolderOpen", library: "bi" },
	{ icon: BiFolderPlus, name: "BiFolderPlus", library: "bi" },
	{ icon: BiFolder, name: "BiFolder", library: "bi" },
	{ icon: BiFontColor, name: "BiFontColor", library: "bi" },
	{ icon: BiFontFamily, name: "BiFontFamily", library: "bi" },
	{ icon: BiFontSize, name: "BiFontSize", library: "bi" },
	{ icon: BiFont, name: "BiFont", library: "bi" },
	{ icon: BiFoodMenu, name: "BiFoodMenu", library: "bi" },
	{ icon: BiFoodTag, name: "BiFoodTag", library: "bi" },
	{ icon: BiFootball, name: "BiFootball", library: "bi" },
	{ icon: BiFridge, name: "BiFridge", library: "bi" },
	{ icon: BiFullscreen, name: "BiFullscreen", library: "bi" },
	{ icon: BiGame, name: "BiGame", library: "bi" },
	{ icon: BiGasPump, name: "BiGasPump", library: "bi" },
	{ icon: BiGhost, name: "BiGhost", library: "bi" },
	{ icon: BiGift, name: "BiGift", library: "bi" },
	{ icon: BiGitBranch, name: "BiGitBranch", library: "bi" },
	{ icon: BiGitCommit, name: "BiGitCommit", library: "bi" },
	{ icon: BiGitCompare, name: "BiGitCompare", library: "bi" },
	{ icon: BiGitMerge, name: "BiGitMerge", library: "bi" },
	{ icon: BiGitPullRequest, name: "BiGitPullRequest", library: "bi" },
	{ icon: BiGitRepoForked, name: "BiGitRepoForked", library: "bi" },
	{ icon: BiGlassesAlt, name: "BiGlassesAlt", library: "bi" },
	{ icon: BiGlasses, name: "BiGlasses", library: "bi" },
	{ icon: BiGlobeAlt, name: "BiGlobeAlt", library: "bi" },
	{ icon: BiGlobe, name: "BiGlobe", library: "bi" },
	{ icon: BiGridAlt, name: "BiGridAlt", library: "bi" },
	{ icon: BiGridHorizontal, name: "BiGridHorizontal", library: "bi" },
	{ icon: BiGridSmall, name: "BiGridSmall", library: "bi" },
	{ icon: BiGridVertical, name: "BiGridVertical", library: "bi" },
	{ icon: BiGrid, name: "BiGrid", library: "bi" },
	{ icon: BiGroup, name: "BiGroup", library: "bi" },
	{ icon: BiHandicap, name: "BiHandicap", library: "bi" },
	{ icon: BiHappyAlt, name: "BiHappyAlt", library: "bi" },
	{ icon: BiHappyBeaming, name: "BiHappyBeaming", library: "bi" },
	{ icon: BiHappyHeartEyes, name: "BiHappyHeartEyes", library: "bi" },
	{ icon: BiHappy, name: "BiHappy", library: "bi" },
	{ icon: BiHash, name: "BiHash", library: "bi" },
	{ icon: BiHdd, name: "BiHdd", library: "bi" },
	{ icon: BiHeading, name: "BiHeading", library: "bi" },
	{ icon: BiHeadphone, name: "BiHeadphone", library: "bi" },
	{ icon: BiHealth, name: "BiHealth", library: "bi" },
	{ icon: BiHeartCircle, name: "BiHeartCircle", library: "bi" },
	{ icon: BiHeartSquare, name: "BiHeartSquare", library: "bi" },
	{ icon: BiHeart, name: "BiHeart", library: "bi" },
	{ icon: BiHelpCircle, name: "BiHelpCircle", library: "bi" },
	{ icon: BiHide, name: "BiHide", library: "bi" },
	{ icon: BiHighlight, name: "BiHighlight", library: "bi" },
	{ icon: BiHistory, name: "BiHistory", library: "bi" },
	{ icon: BiHive, name: "BiHive", library: "bi" },
	{ icon: BiHomeAlt, name: "BiHomeAlt", library: "bi" },
	{ icon: BiHomeCircle, name: "BiHomeCircle", library: "bi" },
	{ icon: BiHomeHeart, name: "BiHomeHeart", library: "bi" },
	{ icon: BiHomeSmile, name: "BiHomeSmile", library: "bi" },
	{ icon: BiHome, name: "BiHome", library: "bi" },
	{ icon: BiHorizontalCenter, name: "BiHorizontalCenter", library: "bi" },
	{ icon: BiHotel, name: "BiHotel", library: "bi" },
	{ icon: BiHourglass, name: "BiHourglass", library: "bi" },
	{ icon: BiIdCard, name: "BiIdCard", library: "bi" },
	{ icon: BiImageAdd, name: "BiImageAdd", library: "bi" },
	{ icon: BiImageAlt, name: "BiImageAlt", library: "bi" },
	{ icon: BiImage, name: "BiImage", library: "bi" },
	{ icon: BiImages, name: "BiImages", library: "bi" },
	{ icon: BiImport, name: "BiImport", library: "bi" },
	{ icon: BiInfinite, name: "BiInfinite", library: "bi" },
	{ icon: BiInfoCircle, name: "BiInfoCircle", library: "bi" },
	{ icon: BiInfoSquare, name: "BiInfoSquare", library: "bi" },
	{ icon: BiIntersect, name: "BiIntersect", library: "bi" },
	{ icon: BiItalic, name: "BiItalic", library: "bi" },
	{ icon: BiJoystickAlt, name: "BiJoystickAlt", library: "bi" },
	{ icon: BiJoystickButton, name: "BiJoystickButton", library: "bi" },
	{ icon: BiJoystick, name: "BiJoystick", library: "bi" },
	{ icon: BiKey, name: "BiKey", library: "bi" },
	{ icon: BiLabel, name: "BiLabel", library: "bi" },
	{ icon: BiLandscape, name: "BiLandscape", library: "bi" },
	{ icon: BiLaptop, name: "BiLaptop", library: "bi" },
	{ icon: BiLastPage, name: "BiLastPage", library: "bi" },
	{ icon: BiLaugh, name: "BiLaugh", library: "bi" },
	{ icon: BiLayerMinus, name: "BiLayerMinus", library: "bi" },
	{ icon: BiLayerPlus, name: "BiLayerPlus", library: "bi" },
	{ icon: BiLayer, name: "BiLayer", library: "bi" },
	{ icon: BiLayout, name: "BiLayout", library: "bi" },
	{ icon: BiLeftArrowAlt, name: "BiLeftArrowAlt", library: "bi" },
	{ icon: BiLeftArrowCircle, name: "BiLeftArrowCircle", library: "bi" },
	{ icon: BiLeftArrow, name: "BiLeftArrow", library: "bi" },
	{ icon: BiLeftDownArrowCircle, name: "BiLeftDownArrowCircle", library: "bi" },
	{ icon: BiLeftIndent, name: "BiLeftIndent", library: "bi" },
	{ icon: BiLeftTopArrowCircle, name: "BiLeftTopArrowCircle", library: "bi" },
	{ icon: BiLibrary, name: "BiLibrary", library: "bi" },
	{ icon: BiLike, name: "BiLike", library: "bi" },
	{ icon: BiLineChartDown, name: "BiLineChartDown", library: "bi" },
	{ icon: BiLineChart, name: "BiLineChart", library: "bi" },
	{ icon: BiLinkAlt, name: "BiLinkAlt", library: "bi" },
	{ icon: BiLinkExternal, name: "BiLinkExternal", library: "bi" },
	{ icon: BiLink, name: "BiLink", library: "bi" },
	{ icon: BiLira, name: "BiLira", library: "bi" },
	{ icon: BiListCheck, name: "BiListCheck", library: "bi" },
	{ icon: BiListMinus, name: "BiListMinus", library: "bi" },
	{ icon: BiListOl, name: "BiListOl", library: "bi" },
	{ icon: BiListPlus, name: "BiListPlus", library: "bi" },
	{ icon: BiListUl, name: "BiListUl", library: "bi" },
	{ icon: BiLoaderAlt, name: "BiLoaderAlt", library: "bi" },
	{ icon: BiLoaderCircle, name: "BiLoaderCircle", library: "bi" },
	{ icon: BiLoader, name: "BiLoader", library: "bi" },
	{ icon: BiLocationPlus, name: "BiLocationPlus", library: "bi" },
	{ icon: BiLockAlt, name: "BiLockAlt", library: "bi" },
	{ icon: BiLockOpenAlt, name: "BiLockOpenAlt", library: "bi" },
	{ icon: BiLockOpen, name: "BiLockOpen", library: "bi" },
	{ icon: BiLock, name: "BiLock", library: "bi" },
	{ icon: BiLogInCircle, name: "BiLogInCircle", library: "bi" },
	{ icon: BiLogIn, name: "BiLogIn", library: "bi" },
	{ icon: BiLogOutCircle, name: "BiLogOutCircle", library: "bi" },
	{ icon: BiLogOut, name: "BiLogOut", library: "bi" },
	{ icon: BiLowVision, name: "BiLowVision", library: "bi" },
	{ icon: BiMagnet, name: "BiMagnet", library: "bi" },
	{ icon: BiMailSend, name: "BiMailSend", library: "bi" },
	{ icon: BiMaleSign, name: "BiMaleSign", library: "bi" },
	{ icon: BiMale, name: "BiMale", library: "bi" },
	{ icon: BiMapAlt, name: "BiMapAlt", library: "bi" },
	{ icon: BiMapPin, name: "BiMapPin", library: "bi" },
	{ icon: BiMap, name: "BiMap", library: "bi" },
	{ icon: BiMask, name: "BiMask", library: "bi" },
	{ icon: BiMedal, name: "BiMedal", library: "bi" },
	{ icon: BiMehAlt, name: "BiMehAlt", library: "bi" },
	{ icon: BiMehBlank, name: "BiMehBlank", library: "bi" },
	{ icon: BiMeh, name: "BiMeh", library: "bi" },
	{ icon: BiMemoryCard, name: "BiMemoryCard", library: "bi" },
	{ icon: BiMenuAltLeft, name: "BiMenuAltLeft", library: "bi" },
	{ icon: BiMenuAltRight, name: "BiMenuAltRight", library: "bi" },
	{ icon: BiMenu, name: "BiMenu", library: "bi" },
	{ icon: BiMerge, name: "BiMerge", library: "bi" },
	{ icon: BiMessageAdd, name: "BiMessageAdd", library: "bi" },
	{ icon: BiMessageAltAdd, name: "BiMessageAltAdd", library: "bi" },
	{ icon: BiMessageAltCheck, name: "BiMessageAltCheck", library: "bi" },
	{ icon: BiMessageAltDetail, name: "BiMessageAltDetail", library: "bi" },
	{ icon: BiMessageAltDots, name: "BiMessageAltDots", library: "bi" },
	{ icon: BiMessageAltEdit, name: "BiMessageAltEdit", library: "bi" },
	{ icon: BiMessageAltError, name: "BiMessageAltError", library: "bi" },
	{ icon: BiMessageAltMinus, name: "BiMessageAltMinus", library: "bi" },
	{ icon: BiMessageAltX, name: "BiMessageAltX", library: "bi" },
	{ icon: BiMessageAlt, name: "BiMessageAlt", library: "bi" },
	{ icon: BiMessageCheck, name: "BiMessageCheck", library: "bi" },
	{ icon: BiMessageDetail, name: "BiMessageDetail", library: "bi" },
	{ icon: BiMessageDots, name: "BiMessageDots", library: "bi" },
	{ icon: BiMessageEdit, name: "BiMessageEdit", library: "bi" },
	{ icon: BiMessageError, name: "BiMessageError", library: "bi" },
	{ icon: BiMessageMinus, name: "BiMessageMinus", library: "bi" },
	{ icon: BiMessageRoundedAdd, name: "BiMessageRoundedAdd", library: "bi" },
	{ icon: BiMessageRoundedCheck, name: "BiMessageRoundedCheck", library: "bi" },
	{ icon: BiMessageRoundedDetail, name: "BiMessageRoundedDetail", library: "bi" },
	{ icon: BiMessageRoundedDots, name: "BiMessageRoundedDots", library: "bi" },
	{ icon: BiMessageRoundedEdit, name: "BiMessageRoundedEdit", library: "bi" },
	{ icon: BiMessageRoundedError, name: "BiMessageRoundedError", library: "bi" },
	{ icon: BiMessageRoundedMinus, name: "BiMessageRoundedMinus", library: "bi" },
	{ icon: BiMessageRoundedX, name: "BiMessageRoundedX", library: "bi" },
	{ icon: BiMessageRounded, name: "BiMessageRounded", library: "bi" },
	{ icon: BiMessageSquareAdd, name: "BiMessageSquareAdd", library: "bi" },
	{ icon: BiMessageSquareCheck, name: "BiMessageSquareCheck", library: "bi" },
	{ icon: BiMessageSquareDetail, name: "BiMessageSquareDetail", library: "bi" },
	{ icon: BiMessageSquareDots, name: "BiMessageSquareDots", library: "bi" },
	{ icon: BiMessageSquareEdit, name: "BiMessageSquareEdit", library: "bi" },
	{ icon: BiMessageSquareError, name: "BiMessageSquareError", library: "bi" },
	{ icon: BiMessageSquareMinus, name: "BiMessageSquareMinus", library: "bi" },
	{ icon: BiMessageSquareX, name: "BiMessageSquareX", library: "bi" },
	{ icon: BiMessageSquare, name: "BiMessageSquare", library: "bi" },
	{ icon: BiMessageX, name: "BiMessageX", library: "bi" },
	{ icon: BiMessage, name: "BiMessage", library: "bi" },
	{ icon: BiMeteor, name: "BiMeteor", library: "bi" },
	{ icon: BiMicrochip, name: "BiMicrochip", library: "bi" },
	{ icon: BiMicrophoneOff, name: "BiMicrophoneOff", library: "bi" },
	{ icon: BiMicrophone, name: "BiMicrophone", library: "bi" },
	{ icon: BiMinusBack, name: "BiMinusBack", library: "bi" },
	{ icon: BiMinusCircle, name: "BiMinusCircle", library: "bi" },
	{ icon: BiMinusFront, name: "BiMinusFront", library: "bi" },
	{ icon: BiMinus, name: "BiMinus", library: "bi" },
	{ icon: BiMobileAlt, name: "BiMobileAlt", library: "bi" },
	{ icon: BiMobileLandscape, name: "BiMobileLandscape", library: "bi" },
	{ icon: BiMobileVibration, name: "BiMobileVibration", library: "bi" },
	{ icon: BiMobile, name: "BiMobile", library: "bi" },
	{ icon: BiMoney, name: "BiMoney", library: "bi" },
	{ icon: BiMoon, name: "BiMoon", library: "bi" },
	{ icon: BiMouseAlt, name: "BiMouseAlt", library: "bi" },
	{ icon: BiMouse, name: "BiMouse", library: "bi" },
	{ icon: BiMoveHorizontal, name: "BiMoveHorizontal", library: "bi" },
	{ icon: BiMoveVertical, name: "BiMoveVertical", library: "bi" },
	{ icon: BiMove, name: "BiMove", library: "bi" },
	{ icon: BiMoviePlay, name: "BiMoviePlay", library: "bi" },
	{ icon: BiMovie, name: "BiMovie", library: "bi" },
	{ icon: BiMusic, name: "BiMusic", library: "bi" },
	{ icon: BiNavigation, name: "BiNavigation", library: "bi" },
	{ icon: BiNetworkChart, name: "BiNetworkChart", library: "bi" },
	{ icon: BiNews, name: "BiNews", library: "bi" },
	{ icon: BiNoEntry, name: "BiNoEntry", library: "bi" },
	{ icon: BiNote, name: "BiNote", library: "bi" },
	{ icon: BiNotepad, name: "BiNotepad", library: "bi" },
	{ icon: BiNotificationOff, name: "BiNotificationOff", library: "bi" },
	{ icon: BiNotification, name: "BiNotification", library: "bi" },
	{ icon: BiOutline, name: "BiOutline", library: "bi" },
	{ icon: BiPackage, name: "BiPackage", library: "bi" },
	{ icon: BiPaintRoll, name: "BiPaintRoll", library: "bi" },
	{ icon: BiPaint, name: "BiPaint", library: "bi" },
	{ icon: BiPalette, name: "BiPalette", library: "bi" },
	{ icon: BiPaperPlane, name: "BiPaperPlane", library: "bi" },
	{ icon: BiPaperclip, name: "BiPaperclip", library: "bi" },
	{ icon: BiParagraph, name: "BiParagraph", library: "bi" },
	{ icon: BiPaste, name: "BiPaste", library: "bi" },
	{ icon: BiPauseCircle, name: "BiPauseCircle", library: "bi" },
	{ icon: BiPause, name: "BiPause", library: "bi" },
	{ icon: BiPen, name: "BiPen", library: "bi" },
	{ icon: BiPencil, name: "BiPencil", library: "bi" },
	{ icon: BiPhoneCall, name: "BiPhoneCall", library: "bi" },
	{ icon: BiPhoneIncoming, name: "BiPhoneIncoming", library: "bi" },
	{ icon: BiPhoneOff, name: "BiPhoneOff", library: "bi" },
	{ icon: BiPhoneOutgoing, name: "BiPhoneOutgoing", library: "bi" },
	{ icon: BiPhone, name: "BiPhone", library: "bi" },
	{ icon: BiPhotoAlbum, name: "BiPhotoAlbum", library: "bi" },
	{ icon: BiPieChartAlt2, name: "BiPieChartAlt2", library: "bi" },
	{ icon: BiPieChartAlt, name: "BiPieChartAlt", library: "bi" },
	{ icon: BiPieChart, name: "BiPieChart", library: "bi" },
	{ icon: BiPin, name: "BiPin", library: "bi" },
	{ icon: BiPlanet, name: "BiPlanet", library: "bi" },
	{ icon: BiPlayCircle, name: "BiPlayCircle", library: "bi" },
	{ icon: BiPlay, name: "BiPlay", library: "bi" },
	{ icon: BiPlug, name: "BiPlug", library: "bi" },
	{ icon: BiPlusCircle, name: "BiPlusCircle", library: "bi" },
	{ icon: BiPlusMedical, name: "BiPlusMedical", library: "bi" },
	{ icon: BiPlus, name: "BiPlus", library: "bi" },
	{ icon: BiPodcast, name: "BiPodcast", library: "bi" },
	{ icon: BiPointer, name: "BiPointer", library: "bi" },
	{ icon: BiPoll, name: "BiPoll", library: "bi" },
	{ icon: BiPolygon, name: "BiPolygon", library: "bi" },
	{ icon: BiPound, name: "BiPound", library: "bi" },
	{ icon: BiPowerOff, name: "BiPowerOff", library: "bi" },
	{ icon: BiPrinter, name: "BiPrinter", library: "bi" },
	{ icon: BiPulse, name: "BiPulse", library: "bi" },
	{ icon: BiPurchaseTagAlt, name: "BiPurchaseTagAlt", library: "bi" },
	{ icon: BiPurchaseTag, name: "BiPurchaseTag", library: "bi" },
	{ icon: BiPyramid, name: "BiPyramid", library: "bi" },
	{ icon: BiQrScan, name: "BiQrScan", library: "bi" },
	{ icon: BiQr, name: "BiQr", library: "bi" },
	{ icon: BiQuestionMark, name: "BiQuestionMark", library: "bi" },
	{ icon: BiRadar, name: "BiRadar", library: "bi" },
	{ icon: BiRadioCircleMarked, name: "BiRadioCircleMarked", library: "bi" },
	{ icon: BiRadioCircle, name: "BiRadioCircle", library: "bi" },
	{ icon: BiRadio, name: "BiRadio", library: "bi" },
	{ icon: BiReceipt, name: "BiReceipt", library: "bi" },
	{ icon: BiRectangle, name: "BiRectangle", library: "bi" },
	{ icon: BiRecycle, name: "BiRecycle", library: "bi" },
	{ icon: BiRedo, name: "BiRedo", library: "bi" },
	{ icon: BiRefresh, name: "BiRefresh", library: "bi" },
	{ icon: BiRegistered, name: "BiRegistered", library: "bi" },
	{ icon: BiRename, name: "BiRename", library: "bi" },
	{ icon: BiRepeat, name: "BiRepeat", library: "bi" },
	{ icon: BiReplyAll, name: "BiReplyAll", library: "bi" },
	{ icon: BiReply, name: "BiReply", library: "bi" },
	{ icon: BiRepost, name: "BiRepost", library: "bi" },
	{ icon: BiReset, name: "BiReset", library: "bi" },
	{ icon: BiRestaurant, name: "BiRestaurant", library: "bi" },
	{ icon: BiRevision, name: "BiRevision", library: "bi" },
	{ icon: BiRewindCircle, name: "BiRewindCircle", library: "bi" },
	{ icon: BiRewind, name: "BiRewind", library: "bi" },
	{ icon: BiRightArrowAlt, name: "BiRightArrowAlt", library: "bi" },
	{ icon: BiRightArrowCircle, name: "BiRightArrowCircle", library: "bi" },
	{ icon: BiRightArrow, name: "BiRightArrow", library: "bi" },
	{ icon: BiRightDownArrowCircle, name: "BiRightDownArrowCircle", library: "bi" },
	{ icon: BiRightIndent, name: "BiRightIndent", library: "bi" },
	{ icon: BiRightTopArrowCircle, name: "BiRightTopArrowCircle", library: "bi" },
	{ icon: BiRocket, name: "BiRocket", library: "bi" },
	{ icon: BiRotateLeft, name: "BiRotateLeft", library: "bi" },
	{ icon: BiRotateRight, name: "BiRotateRight", library: "bi" },
	{ icon: BiRss, name: "BiRss", library: "bi" },
	{ icon: BiRuble, name: "BiRuble", library: "bi" },
	{ icon: BiRuler, name: "BiRuler", library: "bi" },
	{ icon: BiRun, name: "BiRun", library: "bi" },
	{ icon: BiRupee, name: "BiRupee", library: "bi" },
	{ icon: BiSad, name: "BiSad", library: "bi" },
	{ icon: BiSave, name: "BiSave", library: "bi" },
	{ icon: BiScan, name: "BiScan", library: "bi" },
	{ icon: BiScreenshot, name: "BiScreenshot", library: "bi" },
	{ icon: BiSearchAlt2, name: "BiSearchAlt2", library: "bi" },
	{ icon: BiSearchAlt, name: "BiSearchAlt", library: "bi" },
	{ icon: BiSearch, name: "BiSearch", library: "bi" },
	{ icon: BiSelectMultiple, name: "BiSelectMultiple", library: "bi" },
	{ icon: BiSelection, name: "BiSelection", library: "bi" },
	{ icon: BiSend, name: "BiSend", library: "bi" },
	{ icon: BiServer, name: "BiServer", library: "bi" },
	{ icon: BiShapeCircle, name: "BiShapeCircle", library: "bi" },
	{ icon: BiShapePolygon, name: "BiShapePolygon", library: "bi" },
	{ icon: BiShapeSquare, name: "BiShapeSquare", library: "bi" },
	{ icon: BiShapeTriangle, name: "BiShapeTriangle", library: "bi" },
	{ icon: BiShareAlt, name: "BiShareAlt", library: "bi" },
	{ icon: BiShare, name: "BiShare", library: "bi" },
	{ icon: BiShekel, name: "BiShekel", library: "bi" },
	{ icon: BiShieldAlt2, name: "BiShieldAlt2", library: "bi" },
	{ icon: BiShieldAlt, name: "BiShieldAlt", library: "bi" },
	{ icon: BiShieldQuarter, name: "BiShieldQuarter", library: "bi" },
	{ icon: BiShieldX, name: "BiShieldX", library: "bi" },
	{ icon: BiShield, name: "BiShield", library: "bi" },
	{ icon: BiShocked, name: "BiShocked", library: "bi" },
	{ icon: BiShoppingBag, name: "BiShoppingBag", library: "bi" },
	{ icon: BiShowAlt, name: "BiShowAlt", library: "bi" },
	{ icon: BiShow, name: "BiShow", library: "bi" },
	{ icon: BiShuffle, name: "BiShuffle", library: "bi" },
	{ icon: BiSidebar, name: "BiSidebar", library: "bi" },
	{ icon: BiSitemap, name: "BiSitemap", library: "bi" },
	{ icon: BiSkipNextCircle, name: "BiSkipNextCircle", library: "bi" },
	{ icon: BiSkipNext, name: "BiSkipNext", library: "bi" },
	{ icon: BiSkipPreviousCircle, name: "BiSkipPreviousCircle", library: "bi" },
	{ icon: BiSkipPrevious, name: "BiSkipPrevious", library: "bi" },
	{ icon: BiSleepy, name: "BiSleepy", library: "bi" },
	{ icon: BiSliderAlt, name: "BiSliderAlt", library: "bi" },
	{ icon: BiSlider, name: "BiSlider", library: "bi" },
	{ icon: BiSlideshow, name: "BiSlideshow", library: "bi" },
	{ icon: BiSmile, name: "BiSmile", library: "bi" },
	{ icon: BiSortAZ, name: "BiSortAZ", library: "bi" },
	{ icon: BiSortAlt2, name: "BiSortAlt2", library: "bi" },
	{ icon: BiSortDown, name: "BiSortDown", library: "bi" },
	{ icon: BiSortUp, name: "BiSortUp", library: "bi" },
	{ icon: BiSortZA, name: "BiSortZA", library: "bi" },
	{ icon: BiSort, name: "BiSort", library: "bi" },
	{ icon: BiSpa, name: "BiSpa", library: "bi" },
	{ icon: BiSpaceBar, name: "BiSpaceBar", library: "bi" },
	{ icon: BiSpeaker, name: "BiSpeaker", library: "bi" },
	{ icon: BiSprayCan, name: "BiSprayCan", library: "bi" },
	{ icon: BiSpreadsheet, name: "BiSpreadsheet", library: "bi" },
	{ icon: BiSquareRounded, name: "BiSquareRounded", library: "bi" },
	{ icon: BiSquare, name: "BiSquare", library: "bi" },
	{ icon: BiStar, name: "BiStar", library: "bi" },
	{ icon: BiStation, name: "BiStation", library: "bi" },
	{ icon: BiStats, name: "BiStats", library: "bi" },
	{ icon: BiSticker, name: "BiSticker", library: "bi" },
	{ icon: BiStopCircle, name: "BiStopCircle", library: "bi" },
	{ icon: BiStop, name: "BiStop", library: "bi" },
	{ icon: BiStopwatch, name: "BiStopwatch", library: "bi" },
	{ icon: BiStoreAlt, name: "BiStoreAlt", library: "bi" },
	{ icon: BiStore, name: "BiStore", library: "bi" },
	{ icon: BiStreetView, name: "BiStreetView", library: "bi" },
	{ icon: BiStrikethrough, name: "BiStrikethrough", library: "bi" },
	{ icon: BiSubdirectoryLeft, name: "BiSubdirectoryLeft", library: "bi" },
	{ icon: BiSubdirectoryRight, name: "BiSubdirectoryRight", library: "bi" },
	{ icon: BiSun, name: "BiSun", library: "bi" },
	{ icon: BiSupport, name: "BiSupport", library: "bi" },
	{ icon: BiSwim, name: "BiSwim", library: "bi" },
	{ icon: BiSync, name: "BiSync", library: "bi" },
	{ icon: BiTab, name: "BiTab", library: "bi" },
	{ icon: BiTable, name: "BiTable", library: "bi" },
	{ icon: BiTachometer, name: "BiTachometer", library: "bi" },
	{ icon: BiTagAlt, name: "BiTagAlt", library: "bi" },
	{ icon: BiTag, name: "BiTag", library: "bi" },
	{ icon: BiTargetLock, name: "BiTargetLock", library: "bi" },
	{ icon: BiTaskX, name: "BiTaskX", library: "bi" },
	{ icon: BiTask, name: "BiTask", library: "bi" },
	{ icon: BiTaxi, name: "BiTaxi", library: "bi" },
	{ icon: BiTennisBall, name: "BiTennisBall", library: "bi" },
	{ icon: BiTerminal, name: "BiTerminal", library: "bi" },
	{ icon: BiTestTube, name: "BiTestTube", library: "bi" },
	{ icon: BiText, name: "BiText", library: "bi" },
	{ icon: BiTimeFive, name: "BiTimeFive", library: "bi" },
	{ icon: BiTime, name: "BiTime", library: "bi" },
	{ icon: BiTimer, name: "BiTimer", library: "bi" },
	{ icon: BiTired, name: "BiTired", library: "bi" },
	{ icon: BiToggleLeft, name: "BiToggleLeft", library: "bi" },
	{ icon: BiToggleRight, name: "BiToggleRight", library: "bi" },
	{ icon: BiTone, name: "BiTone", library: "bi" },
	{ icon: BiTrafficCone, name: "BiTrafficCone", library: "bi" },
	{ icon: BiTrain, name: "BiTrain", library: "bi" },
	{ icon: BiTransferAlt, name: "BiTransferAlt", library: "bi" },
	{ icon: BiTransfer, name: "BiTransfer", library: "bi" },
	{ icon: BiTrashAlt, name: "BiTrashAlt", library: "bi" },
	{ icon: BiTrash, name: "BiTrash", library: "bi" },
	{ icon: BiTrendingDown, name: "BiTrendingDown", library: "bi" },
	{ icon: BiTrendingUp, name: "BiTrendingUp", library: "bi" },
	{ icon: BiTrim, name: "BiTrim", library: "bi" },
	{ icon: BiTrip, name: "BiTrip", library: "bi" },
	{ icon: BiTrophy, name: "BiTrophy", library: "bi" },
	{ icon: BiTv, name: "BiTv", library: "bi" },
	{ icon: BiUnderline, name: "BiUnderline", library: "bi" },
	{ icon: BiUndo, name: "BiUndo", library: "bi" },
	{ icon: BiUnite, name: "BiUnite", library: "bi" },
	{ icon: BiUnlink, name: "BiUnlink", library: "bi" },
	{ icon: BiUpArrowAlt, name: "BiUpArrowAlt", library: "bi" },
	{ icon: BiUpArrowCircle, name: "BiUpArrowCircle", library: "bi" },
	{ icon: BiUpArrow, name: "BiUpArrow", library: "bi" },
	{ icon: BiUpload, name: "BiUpload", library: "bi" },
	{ icon: BiUpsideDown, name: "BiUpsideDown", library: "bi" },
	{ icon: BiUpvote, name: "BiUpvote", library: "bi" },
	{ icon: BiUsb, name: "BiUsb", library: "bi" },
	{ icon: BiUserCheck, name: "BiUserCheck", library: "bi" },
	{ icon: BiUserCircle, name: "BiUserCircle", library: "bi" },
	{ icon: BiUserMinus, name: "BiUserMinus", library: "bi" },
	{ icon: BiUserPin, name: "BiUserPin", library: "bi" },
	{ icon: BiUserPlus, name: "BiUserPlus", library: "bi" },
	{ icon: BiUserVoice, name: "BiUserVoice", library: "bi" },
	{ icon: BiUserX, name: "BiUserX", library: "bi" },
	{ icon: BiUser, name: "BiUser", library: "bi" },
	{ icon: BiVector, name: "BiVector", library: "bi" },
	{ icon: BiVerticalCenter, name: "BiVerticalCenter", library: "bi" },
	{ icon: BiVial, name: "BiVial", library: "bi" },
	{ icon: BiVideoOff, name: "BiVideoOff", library: "bi" },
	{ icon: BiVideoPlus, name: "BiVideoPlus", library: "bi" },
	{ icon: BiVideoRecording, name: "BiVideoRecording", library: "bi" },
	{ icon: BiVideo, name: "BiVideo", library: "bi" },
	{ icon: BiVoicemail, name: "BiVoicemail", library: "bi" },
	{ icon: BiVolumeFull, name: "BiVolumeFull", library: "bi" },
	{ icon: BiVolumeLow, name: "BiVolumeLow", library: "bi" },
	{ icon: BiVolumeMute, name: "BiVolumeMute", library: "bi" },
	{ icon: BiVolume, name: "BiVolume", library: "bi" },
	{ icon: BiWalk, name: "BiWalk", library: "bi" },
	{ icon: BiWalletAlt, name: "BiWalletAlt", library: "bi" },
	{ icon: BiWallet, name: "BiWallet", library: "bi" },
	{ icon: BiWater, name: "BiWater", library: "bi" },
	{ icon: BiWebcam, name: "BiWebcam", library: "bi" },
	{ icon: BiWifi0, name: "BiWifi0", library: "bi" },
	{ icon: BiWifi1, name: "BiWifi1", library: "bi" },
	{ icon: BiWifi2, name: "BiWifi2", library: "bi" },
	{ icon: BiWifiOff, name: "BiWifiOff", library: "bi" },
	{ icon: BiWifi, name: "BiWifi", library: "bi" },
	{ icon: BiWind, name: "BiWind", library: "bi" },
	{ icon: BiWindowAlt, name: "BiWindowAlt", library: "bi" },
	{ icon: BiWindowClose, name: "BiWindowClose", library: "bi" },
	{ icon: BiWindowOpen, name: "BiWindowOpen", library: "bi" },
	{ icon: BiWindow, name: "BiWindow", library: "bi" },
	{ icon: BiWindows, name: "BiWindows", library: "bi" },
	{ icon: BiWine, name: "BiWine", library: "bi" },
	{ icon: BiWinkSmile, name: "BiWinkSmile", library: "bi" },
	{ icon: BiWinkTongue, name: "BiWinkTongue", library: "bi" },
	{ icon: BiWon, name: "BiWon", library: "bi" },
	{ icon: BiWorld, name: "BiWorld", library: "bi" },
	{ icon: BiWrench, name: "BiWrench", library: "bi" },
	{ icon: BiXCircle, name: "BiXCircle", library: "bi" },
	{ icon: BiX, name: "BiX", library: "bi" },
	{ icon: BiYen, name: "BiYen", library: "bi" },
	{ icon: BiZoomIn, name: "BiZoomIn", library: "bi" },
	{ icon: BiZoomOut, name: "BiZoomOut", library: "bi" },
];

export default result;
