import {
	FiActivity,
	FiAirplay,
	FiAlertCircle,
	FiAlertOctagon,
	FiAlertTriangle,
	FiAlignCenter,
	FiAlignJustify,
	FiAlignLeft,
	FiAlignRight,
	FiAnchor,
	FiAperture,
	FiArchive,
	FiArrowDownCircle,
	FiArrowDownLeft,
	FiArrowDownRight,
	FiArrowDown,
	FiArrowLeftCircle,
	FiArrowLeft,
	FiArrowRightCircle,
	FiArrowRight,
	FiArrowUpCircle,
	FiArrowUpLeft,
	FiArrowUpRight,
	FiArrowUp,
	FiAtSign,
	FiAward,
	FiBarChart2,
	FiBarChart,
	FiBatteryCharging,
	FiBattery,
	FiBellOff,
	FiBell,
	FiBluetooth,
	FiBold,
	FiBookOpen,
	FiBook,
	FiBookmark,
	FiBox,
	FiBriefcase,
	FiCalendar,
	FiCameraOff,
	FiCamera,
	FiCast,
	FiCheckCircle,
	FiCheckSquare,
	FiCheck,
	FiChevronDown,
	FiChevronLeft,
	FiChevronRight,
	FiChevronUp,
	FiChevronsDown,
	FiChevronsLeft,
	FiChevronsRight,
	FiChevronsUp,
	FiChrome,
	FiCircle,
	FiClipboard,
	FiClock,
	FiCloudDrizzle,
	FiCloudLightning,
	FiCloudOff,
	FiCloudRain,
	FiCloudSnow,
	FiCloud,
	FiCode,
	FiCodepen,
	FiCodesandbox,
	FiCoffee,
	FiColumns,
	FiCommand,
	FiCompass,
	FiCopy,
	FiCornerDownLeft,
	FiCornerDownRight,
	FiCornerLeftDown,
	FiCornerLeftUp,
	FiCornerRightDown,
	FiCornerRightUp,
	FiCornerUpLeft,
	FiCornerUpRight,
	FiCpu,
	FiCreditCard,
	FiCrop,
	FiCrosshair,
	FiDatabase,
	FiDelete,
	FiDisc,
	FiDivideCircle,
	FiDivideSquare,
	FiDivide,
	FiDollarSign,
	FiDownloadCloud,
	FiDownload,
	FiDribbble,
	FiDroplet,
	FiEdit2,
	FiEdit3,
	FiEdit,
	FiExternalLink,
	FiEyeOff,
	FiEye,
	FiFacebook,
	FiFastForward,
	FiFeather,
	FiFigma,
	FiFileMinus,
	FiFilePlus,
	FiFileText,
	FiFile,
	FiFilm,
	FiFilter,
	FiFlag,
	FiFolderMinus,
	FiFolderPlus,
	FiFolder,
	FiFramer,
	FiFrown,
	FiGift,
	FiGitBranch,
	FiGitCommit,
	FiGitMerge,
	FiGitPullRequest,
	FiGithub,
	FiGitlab,
	FiGlobe,
	FiGrid,
	FiHardDrive,
	FiHash,
	FiHeadphones,
	FiHeart,
	FiHelpCircle,
	FiHexagon,
	FiHome,
	FiImage,
	FiInbox,
	FiInfo,
	FiInstagram,
	FiItalic,
	FiKey,
	FiLayers,
	FiLayout,
	FiLifeBuoy,
	FiLink2,
	FiLink,
	FiLinkedin,
	FiList,
	FiLoader,
	FiLock,
	FiLogIn,
	FiLogOut,
	FiMail,
	FiMapPin,
	FiMap,
	FiMaximize2,
	FiMaximize,
	FiMeh,
	FiMenu,
	FiMessageCircle,
	FiMessageSquare,
	FiMicOff,
	FiMic,
	FiMinimize2,
	FiMinimize,
	FiMinusCircle,
	FiMinusSquare,
	FiMinus,
	FiMonitor,
	FiMoon,
	FiMoreHorizontal,
	FiMoreVertical,
	FiMousePointer,
	FiMove,
	FiMusic,
	FiNavigation2,
	FiNavigation,
	FiOctagon,
	FiPackage,
	FiPaperclip,
	FiPauseCircle,
	FiPause,
	FiPenTool,
	FiPercent,
	FiPhoneCall,
	FiPhoneForwarded,
	FiPhoneIncoming,
	FiPhoneMissed,
	FiPhoneOff,
	FiPhoneOutgoing,
	FiPhone,
	FiPieChart,
	FiPlayCircle,
	FiPlay,
	FiPlusCircle,
	FiPlusSquare,
	FiPlus,
	FiPocket,
	FiPower,
	FiPrinter,
	FiRadio,
	FiRefreshCcw,
	FiRefreshCw,
	FiRepeat,
	FiRewind,
	FiRotateCcw,
	FiRotateCw,
	FiRss,
	FiSave,
	FiScissors,
	FiSearch,
	FiSend,
	FiServer,
	FiSettings,
	FiShare2,
	FiShare,
	FiShieldOff,
	FiShield,
	FiShoppingBag,
	FiShoppingCart,
	FiShuffle,
	FiSidebar,
	FiSkipBack,
	FiSkipForward,
	FiSlack,
	FiSlash,
	FiSliders,
	FiSmartphone,
	FiSmile,
	FiSpeaker,
	FiSquare,
	FiStar,
	FiStopCircle,
	FiSun,
	FiSunrise,
	FiSunset,
	FiTablet,
	FiTag,
	FiTarget,
	FiTerminal,
	FiThermometer,
	FiThumbsDown,
	FiThumbsUp,
	FiToggleLeft,
	FiToggleRight,
	FiTool,
	FiTrash2,
	FiTrash,
	FiTrello,
	FiTrendingDown,
	FiTrendingUp,
	FiTriangle,
	FiTruck,
	FiTv,
	FiTwitch,
	FiTwitter,
	FiType,
	FiUmbrella,
	FiUnderline,
	FiUnlock,
	FiUploadCloud,
	FiUpload,
	FiUserCheck,
	FiUserMinus,
	FiUserPlus,
	FiUserX,
	FiUser,
	FiUsers,
	FiVideoOff,
	FiVideo,
	FiVoicemail,
	FiVolume1,
	FiVolume2,
	FiVolumeX,
	FiVolume,
	FiWatch,
	FiWifiOff,
	FiWifi,
	FiWind,
	FiXCircle,
	FiXOctagon,
	FiXSquare,
	FiX,
	FiYoutube,
	FiZapOff,
	FiZap,
	FiZoomIn,
	FiZoomOut,
} from "react-icons/fi";

const result = [
	{ icon: FiActivity, name: "FiActivity", library: "fi" },
	{ icon: FiAirplay, name: "FiAirplay", library: "fi" },
	{ icon: FiAlertCircle, name: "FiAlertCircle", library: "fi" },
	{ icon: FiAlertOctagon, name: "FiAlertOctagon", library: "fi" },
	{ icon: FiAlertTriangle, name: "FiAlertTriangle", library: "fi" },
	{ icon: FiAlignCenter, name: "FiAlignCenter", library: "fi" },
	{ icon: FiAlignJustify, name: "FiAlignJustify", library: "fi" },
	{ icon: FiAlignLeft, name: "FiAlignLeft", library: "fi" },
	{ icon: FiAlignRight, name: "FiAlignRight", library: "fi" },
	{ icon: FiAnchor, name: "FiAnchor", library: "fi" },
	{ icon: FiAperture, name: "FiAperture", library: "fi" },
	{ icon: FiArchive, name: "FiArchive", library: "fi" },
	{ icon: FiArrowDownCircle, name: "FiArrowDownCircle", library: "fi" },
	{ icon: FiArrowDownLeft, name: "FiArrowDownLeft", library: "fi" },
	{ icon: FiArrowDownRight, name: "FiArrowDownRight", library: "fi" },
	{ icon: FiArrowDown, name: "FiArrowDown", library: "fi" },
	{ icon: FiArrowLeftCircle, name: "FiArrowLeftCircle", library: "fi" },
	{ icon: FiArrowLeft, name: "FiArrowLeft", library: "fi" },
	{ icon: FiArrowRightCircle, name: "FiArrowRightCircle", library: "fi" },
	{ icon: FiArrowRight, name: "FiArrowRight", library: "fi" },
	{ icon: FiArrowUpCircle, name: "FiArrowUpCircle", library: "fi" },
	{ icon: FiArrowUpLeft, name: "FiArrowUpLeft", library: "fi" },
	{ icon: FiArrowUpRight, name: "FiArrowUpRight", library: "fi" },
	{ icon: FiArrowUp, name: "FiArrowUp", library: "fi" },
	{ icon: FiAtSign, name: "FiAtSign", library: "fi" },
	{ icon: FiAward, name: "FiAward", library: "fi" },
	{ icon: FiBarChart2, name: "FiBarChart2", library: "fi" },
	{ icon: FiBarChart, name: "FiBarChart", library: "fi" },
	{ icon: FiBatteryCharging, name: "FiBatteryCharging", library: "fi" },
	{ icon: FiBattery, name: "FiBattery", library: "fi" },
	{ icon: FiBellOff, name: "FiBellOff", library: "fi" },
	{ icon: FiBell, name: "FiBell", library: "fi" },
	{ icon: FiBluetooth, name: "FiBluetooth", library: "fi" },
	{ icon: FiBold, name: "FiBold", library: "fi" },
	{ icon: FiBookOpen, name: "FiBookOpen", library: "fi" },
	{ icon: FiBook, name: "FiBook", library: "fi" },
	{ icon: FiBookmark, name: "FiBookmark", library: "fi" },
	{ icon: FiBox, name: "FiBox", library: "fi" },
	{ icon: FiBriefcase, name: "FiBriefcase", library: "fi" },
	{ icon: FiCalendar, name: "FiCalendar", library: "fi" },
	{ icon: FiCameraOff, name: "FiCameraOff", library: "fi" },
	{ icon: FiCamera, name: "FiCamera", library: "fi" },
	{ icon: FiCast, name: "FiCast", library: "fi" },
	{ icon: FiCheckCircle, name: "FiCheckCircle", library: "fi" },
	{ icon: FiCheckSquare, name: "FiCheckSquare", library: "fi" },
	{ icon: FiCheck, name: "FiCheck", library: "fi" },
	{ icon: FiChevronDown, name: "FiChevronDown", library: "fi" },
	{ icon: FiChevronLeft, name: "FiChevronLeft", library: "fi" },
	{ icon: FiChevronRight, name: "FiChevronRight", library: "fi" },
	{ icon: FiChevronUp, name: "FiChevronUp", library: "fi" },
	{ icon: FiChevronsDown, name: "FiChevronsDown", library: "fi" },
	{ icon: FiChevronsLeft, name: "FiChevronsLeft", library: "fi" },
	{ icon: FiChevronsRight, name: "FiChevronsRight", library: "fi" },
	{ icon: FiChevronsUp, name: "FiChevronsUp", library: "fi" },
	{ icon: FiChrome, name: "FiChrome", library: "fi" },
	{ icon: FiCircle, name: "FiCircle", library: "fi" },
	{ icon: FiClipboard, name: "FiClipboard", library: "fi" },
	{ icon: FiClock, name: "FiClock", library: "fi" },
	{ icon: FiCloudDrizzle, name: "FiCloudDrizzle", library: "fi" },
	{ icon: FiCloudLightning, name: "FiCloudLightning", library: "fi" },
	{ icon: FiCloudOff, name: "FiCloudOff", library: "fi" },
	{ icon: FiCloudRain, name: "FiCloudRain", library: "fi" },
	{ icon: FiCloudSnow, name: "FiCloudSnow", library: "fi" },
	{ icon: FiCloud, name: "FiCloud", library: "fi" },
	{ icon: FiCode, name: "FiCode", library: "fi" },
	{ icon: FiCodepen, name: "FiCodepen", library: "fi" },
	{ icon: FiCodesandbox, name: "FiCodesandbox", library: "fi" },
	{ icon: FiCoffee, name: "FiCoffee", library: "fi" },
	{ icon: FiColumns, name: "FiColumns", library: "fi" },
	{ icon: FiCommand, name: "FiCommand", library: "fi" },
	{ icon: FiCompass, name: "FiCompass", library: "fi" },
	{ icon: FiCopy, name: "FiCopy", library: "fi" },
	{ icon: FiCornerDownLeft, name: "FiCornerDownLeft", library: "fi" },
	{ icon: FiCornerDownRight, name: "FiCornerDownRight", library: "fi" },
	{ icon: FiCornerLeftDown, name: "FiCornerLeftDown", library: "fi" },
	{ icon: FiCornerLeftUp, name: "FiCornerLeftUp", library: "fi" },
	{ icon: FiCornerRightDown, name: "FiCornerRightDown", library: "fi" },
	{ icon: FiCornerRightUp, name: "FiCornerRightUp", library: "fi" },
	{ icon: FiCornerUpLeft, name: "FiCornerUpLeft", library: "fi" },
	{ icon: FiCornerUpRight, name: "FiCornerUpRight", library: "fi" },
	{ icon: FiCpu, name: "FiCpu", library: "fi" },
	{ icon: FiCreditCard, name: "FiCreditCard", library: "fi" },
	{ icon: FiCrop, name: "FiCrop", library: "fi" },
	{ icon: FiCrosshair, name: "FiCrosshair", library: "fi" },
	{ icon: FiDatabase, name: "FiDatabase", library: "fi" },
	{ icon: FiDelete, name: "FiDelete", library: "fi" },
	{ icon: FiDisc, name: "FiDisc", library: "fi" },
	{ icon: FiDivideCircle, name: "FiDivideCircle", library: "fi" },
	{ icon: FiDivideSquare, name: "FiDivideSquare", library: "fi" },
	{ icon: FiDivide, name: "FiDivide", library: "fi" },
	{ icon: FiDollarSign, name: "FiDollarSign", library: "fi" },
	{ icon: FiDownloadCloud, name: "FiDownloadCloud", library: "fi" },
	{ icon: FiDownload, name: "FiDownload", library: "fi" },
	{ icon: FiDribbble, name: "FiDribbble", library: "fi" },
	{ icon: FiDroplet, name: "FiDroplet", library: "fi" },
	{ icon: FiEdit2, name: "FiEdit2", library: "fi" },
	{ icon: FiEdit3, name: "FiEdit3", library: "fi" },
	{ icon: FiEdit, name: "FiEdit", library: "fi" },
	{ icon: FiExternalLink, name: "FiExternalLink", library: "fi" },
	{ icon: FiEyeOff, name: "FiEyeOff", library: "fi" },
	{ icon: FiEye, name: "FiEye", library: "fi" },
	{ icon: FiFacebook, name: "FiFacebook", library: "fi" },
	{ icon: FiFastForward, name: "FiFastForward", library: "fi" },
	{ icon: FiFeather, name: "FiFeather", library: "fi" },
	{ icon: FiFigma, name: "FiFigma", library: "fi" },
	{ icon: FiFileMinus, name: "FiFileMinus", library: "fi" },
	{ icon: FiFilePlus, name: "FiFilePlus", library: "fi" },
	{ icon: FiFileText, name: "FiFileText", library: "fi" },
	{ icon: FiFile, name: "FiFile", library: "fi" },
	{ icon: FiFilm, name: "FiFilm", library: "fi" },
	{ icon: FiFilter, name: "FiFilter", library: "fi" },
	{ icon: FiFlag, name: "FiFlag", library: "fi" },
	{ icon: FiFolderMinus, name: "FiFolderMinus", library: "fi" },
	{ icon: FiFolderPlus, name: "FiFolderPlus", library: "fi" },
	{ icon: FiFolder, name: "FiFolder", library: "fi" },
	{ icon: FiFramer, name: "FiFramer", library: "fi" },
	{ icon: FiFrown, name: "FiFrown", library: "fi" },
	{ icon: FiGift, name: "FiGift", library: "fi" },
	{ icon: FiGitBranch, name: "FiGitBranch", library: "fi" },
	{ icon: FiGitCommit, name: "FiGitCommit", library: "fi" },
	{ icon: FiGitMerge, name: "FiGitMerge", library: "fi" },
	{ icon: FiGitPullRequest, name: "FiGitPullRequest", library: "fi" },
	{ icon: FiGithub, name: "FiGithub", library: "fi" },
	{ icon: FiGitlab, name: "FiGitlab", library: "fi" },
	{ icon: FiGlobe, name: "FiGlobe", library: "fi" },
	{ icon: FiGrid, name: "FiGrid", library: "fi" },
	{ icon: FiHardDrive, name: "FiHardDrive", library: "fi" },
	{ icon: FiHash, name: "FiHash", library: "fi" },
	{ icon: FiHeadphones, name: "FiHeadphones", library: "fi" },
	{ icon: FiHeart, name: "FiHeart", library: "fi" },
	{ icon: FiHelpCircle, name: "FiHelpCircle", library: "fi" },
	{ icon: FiHexagon, name: "FiHexagon", library: "fi" },
	{ icon: FiHome, name: "FiHome", library: "fi" },
	{ icon: FiImage, name: "FiImage", library: "fi" },
	{ icon: FiInbox, name: "FiInbox", library: "fi" },
	{ icon: FiInfo, name: "FiInfo", library: "fi" },
	{ icon: FiInstagram, name: "FiInstagram", library: "fi" },
	{ icon: FiItalic, name: "FiItalic", library: "fi" },
	{ icon: FiKey, name: "FiKey", library: "fi" },
	{ icon: FiLayers, name: "FiLayers", library: "fi" },
	{ icon: FiLayout, name: "FiLayout", library: "fi" },
	{ icon: FiLifeBuoy, name: "FiLifeBuoy", library: "fi" },
	{ icon: FiLink2, name: "FiLink2", library: "fi" },
	{ icon: FiLink, name: "FiLink", library: "fi" },
	{ icon: FiLinkedin, name: "FiLinkedin", library: "fi" },
	{ icon: FiList, name: "FiList", library: "fi" },
	{ icon: FiLoader, name: "FiLoader", library: "fi" },
	{ icon: FiLock, name: "FiLock", library: "fi" },
	{ icon: FiLogIn, name: "FiLogIn", library: "fi" },
	{ icon: FiLogOut, name: "FiLogOut", library: "fi" },
	{ icon: FiMail, name: "FiMail", library: "fi" },
	{ icon: FiMapPin, name: "FiMapPin", library: "fi" },
	{ icon: FiMap, name: "FiMap", library: "fi" },
	{ icon: FiMaximize2, name: "FiMaximize2", library: "fi" },
	{ icon: FiMaximize, name: "FiMaximize", library: "fi" },
	{ icon: FiMeh, name: "FiMeh", library: "fi" },
	{ icon: FiMenu, name: "FiMenu", library: "fi" },
	{ icon: FiMessageCircle, name: "FiMessageCircle", library: "fi" },
	{ icon: FiMessageSquare, name: "FiMessageSquare", library: "fi" },
	{ icon: FiMicOff, name: "FiMicOff", library: "fi" },
	{ icon: FiMic, name: "FiMic", library: "fi" },
	{ icon: FiMinimize2, name: "FiMinimize2", library: "fi" },
	{ icon: FiMinimize, name: "FiMinimize", library: "fi" },
	{ icon: FiMinusCircle, name: "FiMinusCircle", library: "fi" },
	{ icon: FiMinusSquare, name: "FiMinusSquare", library: "fi" },
	{ icon: FiMinus, name: "FiMinus", library: "fi" },
	{ icon: FiMonitor, name: "FiMonitor", library: "fi" },
	{ icon: FiMoon, name: "FiMoon", library: "fi" },
	{ icon: FiMoreHorizontal, name: "FiMoreHorizontal", library: "fi" },
	{ icon: FiMoreVertical, name: "FiMoreVertical", library: "fi" },
	{ icon: FiMousePointer, name: "FiMousePointer", library: "fi" },
	{ icon: FiMove, name: "FiMove", library: "fi" },
	{ icon: FiMusic, name: "FiMusic", library: "fi" },
	{ icon: FiNavigation2, name: "FiNavigation2", library: "fi" },
	{ icon: FiNavigation, name: "FiNavigation", library: "fi" },
	{ icon: FiOctagon, name: "FiOctagon", library: "fi" },
	{ icon: FiPackage, name: "FiPackage", library: "fi" },
	{ icon: FiPaperclip, name: "FiPaperclip", library: "fi" },
	{ icon: FiPauseCircle, name: "FiPauseCircle", library: "fi" },
	{ icon: FiPause, name: "FiPause", library: "fi" },
	{ icon: FiPenTool, name: "FiPenTool", library: "fi" },
	{ icon: FiPercent, name: "FiPercent", library: "fi" },
	{ icon: FiPhoneCall, name: "FiPhoneCall", library: "fi" },
	{ icon: FiPhoneForwarded, name: "FiPhoneForwarded", library: "fi" },
	{ icon: FiPhoneIncoming, name: "FiPhoneIncoming", library: "fi" },
	{ icon: FiPhoneMissed, name: "FiPhoneMissed", library: "fi" },
	{ icon: FiPhoneOff, name: "FiPhoneOff", library: "fi" },
	{ icon: FiPhoneOutgoing, name: "FiPhoneOutgoing", library: "fi" },
	{ icon: FiPhone, name: "FiPhone", library: "fi" },
	{ icon: FiPieChart, name: "FiPieChart", library: "fi" },
	{ icon: FiPlayCircle, name: "FiPlayCircle", library: "fi" },
	{ icon: FiPlay, name: "FiPlay", library: "fi" },
	{ icon: FiPlusCircle, name: "FiPlusCircle", library: "fi" },
	{ icon: FiPlusSquare, name: "FiPlusSquare", library: "fi" },
	{ icon: FiPlus, name: "FiPlus", library: "fi" },
	{ icon: FiPocket, name: "FiPocket", library: "fi" },
	{ icon: FiPower, name: "FiPower", library: "fi" },
	{ icon: FiPrinter, name: "FiPrinter", library: "fi" },
	{ icon: FiRadio, name: "FiRadio", library: "fi" },
	{ icon: FiRefreshCcw, name: "FiRefreshCcw", library: "fi" },
	{ icon: FiRefreshCw, name: "FiRefreshCw", library: "fi" },
	{ icon: FiRepeat, name: "FiRepeat", library: "fi" },
	{ icon: FiRewind, name: "FiRewind", library: "fi" },
	{ icon: FiRotateCcw, name: "FiRotateCcw", library: "fi" },
	{ icon: FiRotateCw, name: "FiRotateCw", library: "fi" },
	{ icon: FiRss, name: "FiRss", library: "fi" },
	{ icon: FiSave, name: "FiSave", library: "fi" },
	{ icon: FiScissors, name: "FiScissors", library: "fi" },
	{ icon: FiSearch, name: "FiSearch", library: "fi" },
	{ icon: FiSend, name: "FiSend", library: "fi" },
	{ icon: FiServer, name: "FiServer", library: "fi" },
	{ icon: FiSettings, name: "FiSettings", library: "fi" },
	{ icon: FiShare2, name: "FiShare2", library: "fi" },
	{ icon: FiShare, name: "FiShare", library: "fi" },
	{ icon: FiShieldOff, name: "FiShieldOff", library: "fi" },
	{ icon: FiShield, name: "FiShield", library: "fi" },
	{ icon: FiShoppingBag, name: "FiShoppingBag", library: "fi" },
	{ icon: FiShoppingCart, name: "FiShoppingCart", library: "fi" },
	{ icon: FiShuffle, name: "FiShuffle", library: "fi" },
	{ icon: FiSidebar, name: "FiSidebar", library: "fi" },
	{ icon: FiSkipBack, name: "FiSkipBack", library: "fi" },
	{ icon: FiSkipForward, name: "FiSkipForward", library: "fi" },
	{ icon: FiSlack, name: "FiSlack", library: "fi" },
	{ icon: FiSlash, name: "FiSlash", library: "fi" },
	{ icon: FiSliders, name: "FiSliders", library: "fi" },
	{ icon: FiSmartphone, name: "FiSmartphone", library: "fi" },
	{ icon: FiSmile, name: "FiSmile", library: "fi" },
	{ icon: FiSpeaker, name: "FiSpeaker", library: "fi" },
	{ icon: FiSquare, name: "FiSquare", library: "fi" },
	{ icon: FiStar, name: "FiStar", library: "fi" },
	{ icon: FiStopCircle, name: "FiStopCircle", library: "fi" },
	{ icon: FiSun, name: "FiSun", library: "fi" },
	{ icon: FiSunrise, name: "FiSunrise", library: "fi" },
	{ icon: FiSunset, name: "FiSunset", library: "fi" },
	{ icon: FiTablet, name: "FiTablet", library: "fi" },
	{ icon: FiTag, name: "FiTag", library: "fi" },
	{ icon: FiTarget, name: "FiTarget", library: "fi" },
	{ icon: FiTerminal, name: "FiTerminal", library: "fi" },
	{ icon: FiThermometer, name: "FiThermometer", library: "fi" },
	{ icon: FiThumbsDown, name: "FiThumbsDown", library: "fi" },
	{ icon: FiThumbsUp, name: "FiThumbsUp", library: "fi" },
	{ icon: FiToggleLeft, name: "FiToggleLeft", library: "fi" },
	{ icon: FiToggleRight, name: "FiToggleRight", library: "fi" },
	{ icon: FiTool, name: "FiTool", library: "fi" },
	{ icon: FiTrash2, name: "FiTrash2", library: "fi" },
	{ icon: FiTrash, name: "FiTrash", library: "fi" },
	{ icon: FiTrello, name: "FiTrello", library: "fi" },
	{ icon: FiTrendingDown, name: "FiTrendingDown", library: "fi" },
	{ icon: FiTrendingUp, name: "FiTrendingUp", library: "fi" },
	{ icon: FiTriangle, name: "FiTriangle", library: "fi" },
	{ icon: FiTruck, name: "FiTruck", library: "fi" },
	{ icon: FiTv, name: "FiTv", library: "fi" },
	{ icon: FiTwitch, name: "FiTwitch", library: "fi" },
	{ icon: FiTwitter, name: "FiTwitter", library: "fi" },
	{ icon: FiType, name: "FiType", library: "fi" },
	{ icon: FiUmbrella, name: "FiUmbrella", library: "fi" },
	{ icon: FiUnderline, name: "FiUnderline", library: "fi" },
	{ icon: FiUnlock, name: "FiUnlock", library: "fi" },
	{ icon: FiUploadCloud, name: "FiUploadCloud", library: "fi" },
	{ icon: FiUpload, name: "FiUpload", library: "fi" },
	{ icon: FiUserCheck, name: "FiUserCheck", library: "fi" },
	{ icon: FiUserMinus, name: "FiUserMinus", library: "fi" },
	{ icon: FiUserPlus, name: "FiUserPlus", library: "fi" },
	{ icon: FiUserX, name: "FiUserX", library: "fi" },
	{ icon: FiUser, name: "FiUser", library: "fi" },
	{ icon: FiUsers, name: "FiUsers", library: "fi" },
	{ icon: FiVideoOff, name: "FiVideoOff", library: "fi" },
	{ icon: FiVideo, name: "FiVideo", library: "fi" },
	{ icon: FiVoicemail, name: "FiVoicemail", library: "fi" },
	{ icon: FiVolume1, name: "FiVolume1", library: "fi" },
	{ icon: FiVolume2, name: "FiVolume2", library: "fi" },
	{ icon: FiVolumeX, name: "FiVolumeX", library: "fi" },
	{ icon: FiVolume, name: "FiVolume", library: "fi" },
	{ icon: FiWatch, name: "FiWatch", library: "fi" },
	{ icon: FiWifiOff, name: "FiWifiOff", library: "fi" },
	{ icon: FiWifi, name: "FiWifi", library: "fi" },
	{ icon: FiWind, name: "FiWind", library: "fi" },
	{ icon: FiXCircle, name: "FiXCircle", library: "fi" },
	{ icon: FiXOctagon, name: "FiXOctagon", library: "fi" },
	{ icon: FiXSquare, name: "FiXSquare", library: "fi" },
	{ icon: FiX, name: "FiX", library: "fi" },
	{ icon: FiYoutube, name: "FiYoutube", library: "fi" },
	{ icon: FiZapOff, name: "FiZapOff", library: "fi" },
	{ icon: FiZap, name: "FiZap", library: "fi" },
	{ icon: FiZoomIn, name: "FiZoomIn", library: "fi" },
	{ icon: FiZoomOut, name: "FiZoomOut", library: "fi" },
];

export default result;
