import {
FiActivity,
FiAirplay,
FiAlertCircle,
FiAlertOctagon,
FiAlertTriangle,
FiAlignCenter,
FiAlignJustify,
FiAlignLeft,
FiAlignRight,
FiAnchor,
FiAperture,
FiArchive,
FiArrowDownCircle,
FiArrowDownLeft,
FiArrowDownRight,
FiArrowDown,
FiArrowLeftCircle,
FiArrowLeft,
FiArrowRightCircle,
FiArrowRight,
FiArrowUpCircle,
FiArrowUpLeft,
FiArrowUpRight,
FiArrowUp,
FiAtSign,
FiAward,
FiBarChart2,
FiBarChart,
FiBatteryCharging,
FiBattery,
FiBellOff,
FiBell,
FiBluetooth,
FiBold,
FiBookOpen,
FiBook,
FiBookmark,
FiBox,
FiBriefcase,
FiCalendar,
FiCameraOff,
FiCamera,
FiCast,
FiCheckCircle,
FiCheckSquare,
FiCheck,
FiChevronDown,
FiChevronLeft,
FiChevronRight,
FiChevronUp,
FiChevronsDown,
FiChevronsLeft,
FiChevronsRight,
FiChevronsUp,
FiChrome,
FiCircle,
FiClipboard,
FiClock,
FiCloudDrizzle,
FiCloudLightning,
FiCloudOff,
FiCloudRain,
FiCloudSnow,
FiCloud,
FiCode,
FiCodepen,
FiCodesandbox,
FiCoffee,
FiColumns,
FiCommand,
FiCompass,
FiCopy,
FiCornerDownLeft,
FiCornerDownRight,
FiCornerLeftDown,
FiCornerLeftUp,
FiCornerRightDown,
FiCornerRightUp,
FiCornerUpLeft,
FiCornerUpRight,
FiCpu,
FiCreditCard,
FiCrop,
FiCrosshair,
FiDatabase,
FiDelete,
FiDisc,
FiDivideCircle,
FiDivideSquare,
FiDivide,
FiDollarSign,
FiDownloadCloud,
FiDownload,
FiDribbble,
FiDroplet,
FiEdit2,
FiEdit3,
FiEdit,
FiExternalLink,
FiEyeOff,
FiEye,
FiFacebook,
FiFastForward,
FiFeather,
FiFigma,
FiFileMinus,
FiFilePlus,
FiFileText,
FiFile,
FiFilm,
FiFilter,
FiFlag,
FiFolderMinus,
FiFolderPlus,
FiFolder,
FiFramer,
FiFrown,
FiGift,
FiGitBranch,
FiGitCommit,
FiGitMerge,
FiGitPullRequest,
FiGithub,
FiGitlab,
FiGlobe,
FiGrid,
FiHardDrive,
FiHash,
FiHeadphones,
FiHeart,
FiHelpCircle,
FiHexagon,
FiHome,
FiImage,
FiInbox,
FiInfo,
FiInstagram,
FiItalic,
FiKey,
FiLayers,
FiLayout,
FiLifeBuoy,
FiLink2,
FiLink,
FiLinkedin,
FiList,
FiLoader,
FiLock,
FiLogIn,
FiLogOut,
FiMail,
FiMapPin,
FiMap,
FiMaximize2,
FiMaximize,
FiMeh,
FiMenu,
FiMessageCircle,
FiMessageSquare,
FiMicOff,
FiMic,
FiMinimize2,
FiMinimize,
FiMinusCircle,
FiMinusSquare,
FiMinus,
FiMonitor,
FiMoon,
FiMoreHorizontal,
FiMoreVertical,
FiMousePointer,
FiMove,
FiMusic,
FiNavigation2,
FiNavigation,
FiOctagon,
FiPackage,
FiPaperclip,
FiPauseCircle,
FiPause,
FiPenTool,
FiPercent,
FiPhoneCall,
FiPhoneForwarded,
FiPhoneIncoming,
FiPhoneMissed,
FiPhoneOff,
FiPhoneOutgoing,
FiPhone,
FiPieChart,
FiPlayCircle,
FiPlay,
FiPlusCircle,
FiPlusSquare,
FiPlus,
FiPocket,
FiPower,
FiPrinter,
FiRadio,
FiRefreshCcw,
FiRefreshCw,
FiRepeat,
FiRewind,
FiRotateCcw,
FiRotateCw,
FiRss,
FiSave,
FiScissors,
FiSearch,
FiSend,
FiServer,
FiSettings,
FiShare2,
FiShare,
FiShieldOff,
FiShield,
FiShoppingBag,
FiShoppingCart,
FiShuffle,
FiSidebar,
FiSkipBack,
FiSkipForward,
FiSlack,
FiSlash,
FiSliders,
FiSmartphone,
FiSmile,
FiSpeaker,
FiSquare,
FiStar,
FiStopCircle,
FiSun,
FiSunrise,
FiSunset,
FiTablet,
FiTag,
FiTarget,
FiTerminal,
FiThermometer,
FiThumbsDown,
FiThumbsUp,
FiToggleLeft,
FiToggleRight,
FiTool,
FiTrash2,
FiTrash,
FiTrello,
FiTrendingDown,
FiTrendingUp,
FiTriangle,
FiTruck,
FiTv,
FiTwitch,
FiTwitter,
FiType,
FiUmbrella,
FiUnderline,
FiUnlock,
FiUploadCloud,
FiUpload,
FiUserCheck,
FiUserMinus,
FiUserPlus,
FiUserX,
FiUser,
FiUsers,
FiVideoOff,
FiVideo,
FiVoicemail,
FiVolume1,
FiVolume2,
FiVolumeX,
FiVolume,
FiWatch,
FiWifiOff,
FiWifi,
FiWind,
FiXCircle,
FiXOctagon,
FiXSquare,
FiX,
FiYoutube,
FiZapOff,
FiZap,
FiZoomIn,
FiZoomOut,
} from "react-icons/fi";

const result = [
{ icon: FiActivity, name: "FiActivity" },
{ icon: FiAirplay, name: "FiAirplay" },
{ icon: FiAlertCircle, name: "FiAlertCircle" },
{ icon: FiAlertOctagon, name: "FiAlertOctagon" },
{ icon: FiAlertTriangle, name: "FiAlertTriangle" },
{ icon: FiAlignCenter, name: "FiAlignCenter" },
{ icon: FiAlignJustify, name: "FiAlignJustify" },
{ icon: FiAlignLeft, name: "FiAlignLeft" },
{ icon: FiAlignRight, name: "FiAlignRight" },
{ icon: FiAnchor, name: "FiAnchor" },
{ icon: FiAperture, name: "FiAperture" },
{ icon: FiArchive, name: "FiArchive" },
{ icon: FiArrowDownCircle, name: "FiArrowDownCircle" },
{ icon: FiArrowDownLeft, name: "FiArrowDownLeft" },
{ icon: FiArrowDownRight, name: "FiArrowDownRight" },
{ icon: FiArrowDown, name: "FiArrowDown" },
{ icon: FiArrowLeftCircle, name: "FiArrowLeftCircle" },
{ icon: FiArrowLeft, name: "FiArrowLeft" },
{ icon: FiArrowRightCircle, name: "FiArrowRightCircle" },
{ icon: FiArrowRight, name: "FiArrowRight" },
{ icon: FiArrowUpCircle, name: "FiArrowUpCircle" },
{ icon: FiArrowUpLeft, name: "FiArrowUpLeft" },
{ icon: FiArrowUpRight, name: "FiArrowUpRight" },
{ icon: FiArrowUp, name: "FiArrowUp" },
{ icon: FiAtSign, name: "FiAtSign" },
{ icon: FiAward, name: "FiAward" },
{ icon: FiBarChart2, name: "FiBarChart2" },
{ icon: FiBarChart, name: "FiBarChart" },
{ icon: FiBatteryCharging, name: "FiBatteryCharging" },
{ icon: FiBattery, name: "FiBattery" },
{ icon: FiBellOff, name: "FiBellOff" },
{ icon: FiBell, name: "FiBell" },
{ icon: FiBluetooth, name: "FiBluetooth" },
{ icon: FiBold, name: "FiBold" },
{ icon: FiBookOpen, name: "FiBookOpen" },
{ icon: FiBook, name: "FiBook" },
{ icon: FiBookmark, name: "FiBookmark" },
{ icon: FiBox, name: "FiBox" },
{ icon: FiBriefcase, name: "FiBriefcase" },
{ icon: FiCalendar, name: "FiCalendar" },
{ icon: FiCameraOff, name: "FiCameraOff" },
{ icon: FiCamera, name: "FiCamera" },
{ icon: FiCast, name: "FiCast" },
{ icon: FiCheckCircle, name: "FiCheckCircle" },
{ icon: FiCheckSquare, name: "FiCheckSquare" },
{ icon: FiCheck, name: "FiCheck" },
{ icon: FiChevronDown, name: "FiChevronDown" },
{ icon: FiChevronLeft, name: "FiChevronLeft" },
{ icon: FiChevronRight, name: "FiChevronRight" },
{ icon: FiChevronUp, name: "FiChevronUp" },
{ icon: FiChevronsDown, name: "FiChevronsDown" },
{ icon: FiChevronsLeft, name: "FiChevronsLeft" },
{ icon: FiChevronsRight, name: "FiChevronsRight" },
{ icon: FiChevronsUp, name: "FiChevronsUp" },
{ icon: FiChrome, name: "FiChrome" },
{ icon: FiCircle, name: "FiCircle" },
{ icon: FiClipboard, name: "FiClipboard" },
{ icon: FiClock, name: "FiClock" },
{ icon: FiCloudDrizzle, name: "FiCloudDrizzle" },
{ icon: FiCloudLightning, name: "FiCloudLightning" },
{ icon: FiCloudOff, name: "FiCloudOff" },
{ icon: FiCloudRain, name: "FiCloudRain" },
{ icon: FiCloudSnow, name: "FiCloudSnow" },
{ icon: FiCloud, name: "FiCloud" },
{ icon: FiCode, name: "FiCode" },
{ icon: FiCodepen, name: "FiCodepen" },
{ icon: FiCodesandbox, name: "FiCodesandbox" },
{ icon: FiCoffee, name: "FiCoffee" },
{ icon: FiColumns, name: "FiColumns" },
{ icon: FiCommand, name: "FiCommand" },
{ icon: FiCompass, name: "FiCompass" },
{ icon: FiCopy, name: "FiCopy" },
{ icon: FiCornerDownLeft, name: "FiCornerDownLeft" },
{ icon: FiCornerDownRight, name: "FiCornerDownRight" },
{ icon: FiCornerLeftDown, name: "FiCornerLeftDown" },
{ icon: FiCornerLeftUp, name: "FiCornerLeftUp" },
{ icon: FiCornerRightDown, name: "FiCornerRightDown" },
{ icon: FiCornerRightUp, name: "FiCornerRightUp" },
{ icon: FiCornerUpLeft, name: "FiCornerUpLeft" },
{ icon: FiCornerUpRight, name: "FiCornerUpRight" },
{ icon: FiCpu, name: "FiCpu" },
{ icon: FiCreditCard, name: "FiCreditCard" },
{ icon: FiCrop, name: "FiCrop" },
{ icon: FiCrosshair, name: "FiCrosshair" },
{ icon: FiDatabase, name: "FiDatabase" },
{ icon: FiDelete, name: "FiDelete" },
{ icon: FiDisc, name: "FiDisc" },
{ icon: FiDivideCircle, name: "FiDivideCircle" },
{ icon: FiDivideSquare, name: "FiDivideSquare" },
{ icon: FiDivide, name: "FiDivide" },
{ icon: FiDollarSign, name: "FiDollarSign" },
{ icon: FiDownloadCloud, name: "FiDownloadCloud" },
{ icon: FiDownload, name: "FiDownload" },
{ icon: FiDribbble, name: "FiDribbble" },
{ icon: FiDroplet, name: "FiDroplet" },
{ icon: FiEdit2, name: "FiEdit2" },
{ icon: FiEdit3, name: "FiEdit3" },
{ icon: FiEdit, name: "FiEdit" },
{ icon: FiExternalLink, name: "FiExternalLink" },
{ icon: FiEyeOff, name: "FiEyeOff" },
{ icon: FiEye, name: "FiEye" },
{ icon: FiFacebook, name: "FiFacebook" },
{ icon: FiFastForward, name: "FiFastForward" },
{ icon: FiFeather, name: "FiFeather" },
{ icon: FiFigma, name: "FiFigma" },
{ icon: FiFileMinus, name: "FiFileMinus" },
{ icon: FiFilePlus, name: "FiFilePlus" },
{ icon: FiFileText, name: "FiFileText" },
{ icon: FiFile, name: "FiFile" },
{ icon: FiFilm, name: "FiFilm" },
{ icon: FiFilter, name: "FiFilter" },
{ icon: FiFlag, name: "FiFlag" },
{ icon: FiFolderMinus, name: "FiFolderMinus" },
{ icon: FiFolderPlus, name: "FiFolderPlus" },
{ icon: FiFolder, name: "FiFolder" },
{ icon: FiFramer, name: "FiFramer" },
{ icon: FiFrown, name: "FiFrown" },
{ icon: FiGift, name: "FiGift" },
{ icon: FiGitBranch, name: "FiGitBranch" },
{ icon: FiGitCommit, name: "FiGitCommit" },
{ icon: FiGitMerge, name: "FiGitMerge" },
{ icon: FiGitPullRequest, name: "FiGitPullRequest" },
{ icon: FiGithub, name: "FiGithub" },
{ icon: FiGitlab, name: "FiGitlab" },
{ icon: FiGlobe, name: "FiGlobe" },
{ icon: FiGrid, name: "FiGrid" },
{ icon: FiHardDrive, name: "FiHardDrive" },
{ icon: FiHash, name: "FiHash" },
{ icon: FiHeadphones, name: "FiHeadphones" },
{ icon: FiHeart, name: "FiHeart" },
{ icon: FiHelpCircle, name: "FiHelpCircle" },
{ icon: FiHexagon, name: "FiHexagon" },
{ icon: FiHome, name: "FiHome" },
{ icon: FiImage, name: "FiImage" },
{ icon: FiInbox, name: "FiInbox" },
{ icon: FiInfo, name: "FiInfo" },
{ icon: FiInstagram, name: "FiInstagram" },
{ icon: FiItalic, name: "FiItalic" },
{ icon: FiKey, name: "FiKey" },
{ icon: FiLayers, name: "FiLayers" },
{ icon: FiLayout, name: "FiLayout" },
{ icon: FiLifeBuoy, name: "FiLifeBuoy" },
{ icon: FiLink2, name: "FiLink2" },
{ icon: FiLink, name: "FiLink" },
{ icon: FiLinkedin, name: "FiLinkedin" },
{ icon: FiList, name: "FiList" },
{ icon: FiLoader, name: "FiLoader" },
{ icon: FiLock, name: "FiLock" },
{ icon: FiLogIn, name: "FiLogIn" },
{ icon: FiLogOut, name: "FiLogOut" },
{ icon: FiMail, name: "FiMail" },
{ icon: FiMapPin, name: "FiMapPin" },
{ icon: FiMap, name: "FiMap" },
{ icon: FiMaximize2, name: "FiMaximize2" },
{ icon: FiMaximize, name: "FiMaximize" },
{ icon: FiMeh, name: "FiMeh" },
{ icon: FiMenu, name: "FiMenu" },
{ icon: FiMessageCircle, name: "FiMessageCircle" },
{ icon: FiMessageSquare, name: "FiMessageSquare" },
{ icon: FiMicOff, name: "FiMicOff" },
{ icon: FiMic, name: "FiMic" },
{ icon: FiMinimize2, name: "FiMinimize2" },
{ icon: FiMinimize, name: "FiMinimize" },
{ icon: FiMinusCircle, name: "FiMinusCircle" },
{ icon: FiMinusSquare, name: "FiMinusSquare" },
{ icon: FiMinus, name: "FiMinus" },
{ icon: FiMonitor, name: "FiMonitor" },
{ icon: FiMoon, name: "FiMoon" },
{ icon: FiMoreHorizontal, name: "FiMoreHorizontal" },
{ icon: FiMoreVertical, name: "FiMoreVertical" },
{ icon: FiMousePointer, name: "FiMousePointer" },
{ icon: FiMove, name: "FiMove" },
{ icon: FiMusic, name: "FiMusic" },
{ icon: FiNavigation2, name: "FiNavigation2" },
{ icon: FiNavigation, name: "FiNavigation" },
{ icon: FiOctagon, name: "FiOctagon" },
{ icon: FiPackage, name: "FiPackage" },
{ icon: FiPaperclip, name: "FiPaperclip" },
{ icon: FiPauseCircle, name: "FiPauseCircle" },
{ icon: FiPause, name: "FiPause" },
{ icon: FiPenTool, name: "FiPenTool" },
{ icon: FiPercent, name: "FiPercent" },
{ icon: FiPhoneCall, name: "FiPhoneCall" },
{ icon: FiPhoneForwarded, name: "FiPhoneForwarded" },
{ icon: FiPhoneIncoming, name: "FiPhoneIncoming" },
{ icon: FiPhoneMissed, name: "FiPhoneMissed" },
{ icon: FiPhoneOff, name: "FiPhoneOff" },
{ icon: FiPhoneOutgoing, name: "FiPhoneOutgoing" },
{ icon: FiPhone, name: "FiPhone" },
{ icon: FiPieChart, name: "FiPieChart" },
{ icon: FiPlayCircle, name: "FiPlayCircle" },
{ icon: FiPlay, name: "FiPlay" },
{ icon: FiPlusCircle, name: "FiPlusCircle" },
{ icon: FiPlusSquare, name: "FiPlusSquare" },
{ icon: FiPlus, name: "FiPlus" },
{ icon: FiPocket, name: "FiPocket" },
{ icon: FiPower, name: "FiPower" },
{ icon: FiPrinter, name: "FiPrinter" },
{ icon: FiRadio, name: "FiRadio" },
{ icon: FiRefreshCcw, name: "FiRefreshCcw" },
{ icon: FiRefreshCw, name: "FiRefreshCw" },
{ icon: FiRepeat, name: "FiRepeat" },
{ icon: FiRewind, name: "FiRewind" },
{ icon: FiRotateCcw, name: "FiRotateCcw" },
{ icon: FiRotateCw, name: "FiRotateCw" },
{ icon: FiRss, name: "FiRss" },
{ icon: FiSave, name: "FiSave" },
{ icon: FiScissors, name: "FiScissors" },
{ icon: FiSearch, name: "FiSearch" },
{ icon: FiSend, name: "FiSend" },
{ icon: FiServer, name: "FiServer" },
{ icon: FiSettings, name: "FiSettings" },
{ icon: FiShare2, name: "FiShare2" },
{ icon: FiShare, name: "FiShare" },
{ icon: FiShieldOff, name: "FiShieldOff" },
{ icon: FiShield, name: "FiShield" },
{ icon: FiShoppingBag, name: "FiShoppingBag" },
{ icon: FiShoppingCart, name: "FiShoppingCart" },
{ icon: FiShuffle, name: "FiShuffle" },
{ icon: FiSidebar, name: "FiSidebar" },
{ icon: FiSkipBack, name: "FiSkipBack" },
{ icon: FiSkipForward, name: "FiSkipForward" },
{ icon: FiSlack, name: "FiSlack" },
{ icon: FiSlash, name: "FiSlash" },
{ icon: FiSliders, name: "FiSliders" },
{ icon: FiSmartphone, name: "FiSmartphone" },
{ icon: FiSmile, name: "FiSmile" },
{ icon: FiSpeaker, name: "FiSpeaker" },
{ icon: FiSquare, name: "FiSquare" },
{ icon: FiStar, name: "FiStar" },
{ icon: FiStopCircle, name: "FiStopCircle" },
{ icon: FiSun, name: "FiSun" },
{ icon: FiSunrise, name: "FiSunrise" },
{ icon: FiSunset, name: "FiSunset" },
{ icon: FiTablet, name: "FiTablet" },
{ icon: FiTag, name: "FiTag" },
{ icon: FiTarget, name: "FiTarget" },
{ icon: FiTerminal, name: "FiTerminal" },
{ icon: FiThermometer, name: "FiThermometer" },
{ icon: FiThumbsDown, name: "FiThumbsDown" },
{ icon: FiThumbsUp, name: "FiThumbsUp" },
{ icon: FiToggleLeft, name: "FiToggleLeft" },
{ icon: FiToggleRight, name: "FiToggleRight" },
{ icon: FiTool, name: "FiTool" },
{ icon: FiTrash2, name: "FiTrash2" },
{ icon: FiTrash, name: "FiTrash" },
{ icon: FiTrello, name: "FiTrello" },
{ icon: FiTrendingDown, name: "FiTrendingDown" },
{ icon: FiTrendingUp, name: "FiTrendingUp" },
{ icon: FiTriangle, name: "FiTriangle" },
{ icon: FiTruck, name: "FiTruck" },
{ icon: FiTv, name: "FiTv" },
{ icon: FiTwitch, name: "FiTwitch" },
{ icon: FiTwitter, name: "FiTwitter" },
{ icon: FiType, name: "FiType" },
{ icon: FiUmbrella, name: "FiUmbrella" },
{ icon: FiUnderline, name: "FiUnderline" },
{ icon: FiUnlock, name: "FiUnlock" },
{ icon: FiUploadCloud, name: "FiUploadCloud" },
{ icon: FiUpload, name: "FiUpload" },
{ icon: FiUserCheck, name: "FiUserCheck" },
{ icon: FiUserMinus, name: "FiUserMinus" },
{ icon: FiUserPlus, name: "FiUserPlus" },
{ icon: FiUserX, name: "FiUserX" },
{ icon: FiUser, name: "FiUser" },
{ icon: FiUsers, name: "FiUsers" },
{ icon: FiVideoOff, name: "FiVideoOff" },
{ icon: FiVideo, name: "FiVideo" },
{ icon: FiVoicemail, name: "FiVoicemail" },
{ icon: FiVolume1, name: "FiVolume1" },
{ icon: FiVolume2, name: "FiVolume2" },
{ icon: FiVolumeX, name: "FiVolumeX" },
{ icon: FiVolume, name: "FiVolume" },
{ icon: FiWatch, name: "FiWatch" },
{ icon: FiWifiOff, name: "FiWifiOff" },
{ icon: FiWifi, name: "FiWifi" },
{ icon: FiWind, name: "FiWind" },
{ icon: FiXCircle, name: "FiXCircle" },
{ icon: FiXOctagon, name: "FiXOctagon" },
{ icon: FiXSquare, name: "FiXSquare" },
{ icon: FiX, name: "FiX" },
{ icon: FiYoutube, name: "FiYoutube" },
{ icon: FiZapOff, name: "FiZapOff" },
{ icon: FiZap, name: "FiZap" },
{ icon: FiZoomIn, name: "FiZoomIn" },
{ icon: FiZoomOut, name: "FiZoomOut" },
];

export default result