import {
IoIosAddCircleOutline,
IoIosAddCircle,
IoIosAdd,
IoIosAirplane,
IoIosAlarm,
IoIosAlbums,
IoIosAlert,
IoIosAmericanFootball,
IoIosAnalytics,
IoIosAperture,
IoIosApps,
IoIosAppstore,
IoIosArchive,
IoIosArrowBack,
IoIosArrowDown,
IoIosArrowDropdownCircle,
IoIosArrowDropdown,
IoIosArrowDropleftCircle,
IoIosArrowDropleft,
IoIosArrowDroprightCircle,
IoIosArrowDropright,
IoIosArrowDropupCircle,
IoIosArrowDropup,
IoIosArrowForward,
IoIosArrowRoundBack,
IoIosArrowRoundDown,
IoIosArrowRoundForward,
IoIosArrowRoundUp,
IoIosArrowUp,
IoIosAt,
IoIosAttach,
IoIosBackspace,
IoIosBarcode,
IoIosBaseball,
IoIosBasket,
IoIosBasketball,
IoIosBatteryCharging,
IoIosBatteryDead,
IoIosBatteryFull,
IoIosBeaker,
IoIosBed,
IoIosBeer,
IoIosBicycle,
IoIosBluetooth,
IoIosBoat,
IoIosBody,
IoIosBonfire,
IoIosBook,
IoIosBookmark,
IoIosBookmarks,
IoIosBowtie,
IoIosBriefcase,
IoIosBrowsers,
IoIosBrush,
IoIosBug,
IoIosBuild,
IoIosBulb,
IoIosBus,
IoIosBusiness,
IoIosCafe,
IoIosCalculator,
IoIosCalendar,
IoIosCall,
IoIosCamera,
IoIosCar,
IoIosCard,
IoIosCart,
IoIosCash,
IoIosCellular,
IoIosChatboxes,
IoIosChatbubbles,
IoIosCheckboxOutline,
IoIosCheckbox,
IoIosCheckmarkCircleOutline,
IoIosCheckmarkCircle,
IoIosCheckmark,
IoIosClipboard,
IoIosClock,
IoIosCloseCircleOutline,
IoIosCloseCircle,
IoIosClose,
IoIosCloudCircle,
IoIosCloudDone,
IoIosCloudDownload,
IoIosCloudOutline,
IoIosCloudUpload,
IoIosCloud,
IoIosCloudyNight,
IoIosCloudy,
IoIosCodeDownload,
IoIosCodeWorking,
IoIosCode,
IoIosCog,
IoIosColorFill,
IoIosColorFilter,
IoIosColorPalette,
IoIosColorWand,
IoIosCompass,
IoIosConstruct,
IoIosContact,
IoIosContacts,
IoIosContract,
IoIosContrast,
IoIosCopy,
IoIosCreate,
IoIosCrop,
IoIosCube,
IoIosCut,
IoIosDesktop,
IoIosDisc,
IoIosDocument,
IoIosDoneAll,
IoIosDownload,
IoIosEasel,
IoIosEgg,
IoIosExit,
IoIosExpand,
IoIosEyeOff,
IoIosEye,
IoIosFastforward,
IoIosFemale,
IoIosFiling,
IoIosFilm,
IoIosFingerPrint,
IoIosFitness,
IoIosFlag,
IoIosFlame,
IoIosFlashOff,
IoIosFlash,
IoIosFlashlight,
IoIosFlask,
IoIosFlower,
IoIosFolderOpen,
IoIosFolder,
IoIosFootball,
IoIosFunnel,
IoIosGift,
IoIosGitBranch,
IoIosGitCommit,
IoIosGitCompare,
IoIosGitMerge,
IoIosGitNetwork,
IoIosGitPullRequest,
IoIosGlasses,
IoIosGlobe,
IoIosGrid,
IoIosHammer,
IoIosHand,
IoIosHappy,
IoIosHeadset,
IoIosHeartDislike,
IoIosHeartEmpty,
IoIosHeartHalf,
IoIosHeart,
IoIosHelpBuoy,
IoIosHelpCircleOutline,
IoIosHelpCircle,
IoIosHelp,
IoIosHome,
IoIosHourglass,
IoIosIceCream,
IoIosImage,
IoIosImages,
IoIosInfinite,
IoIosInformationCircleOutline,
IoIosInformationCircle,
IoIosInformation,
IoIosJet,
IoIosJournal,
IoIosKey,
IoIosKeypad,
IoIosLaptop,
IoIosLeaf,
IoIosLink,
IoIosListBox,
IoIosList,
IoIosLocate,
IoIosLock,
IoIosLogIn,
IoIosLogOut,
IoIosMagnet,
IoIosMailOpen,
IoIosMailUnread,
IoIosMail,
IoIosMale,
IoIosMan,
IoIosMap,
IoIosMedal,
IoIosMedical,
IoIosMedkit,
IoIosMegaphone,
IoIosMenu,
IoIosMicOff,
IoIosMic,
IoIosMicrophone,
IoIosMoon,
IoIosMore,
IoIosMove,
IoIosMusicalNote,
IoIosMusicalNotes,
IoIosNavigate,
IoIosNotificationsOff,
IoIosNotificationsOutline,
IoIosNotifications,
IoIosNuclear,
IoIosNutrition,
IoIosOpen,
IoIosOptions,
IoIosOutlet,
IoIosPaperPlane,
IoIosPaper,
IoIosPartlySunny,
IoIosPause,
IoIosPaw,
IoIosPeople,
IoIosPersonAdd,
IoIosPerson,
IoIosPhoneLandscape,
IoIosPhonePortrait,
IoIosPhotos,
IoIosPie,
IoIosPin,
IoIosPint,
IoIosPizza,
IoIosPlanet,
IoIosPlayCircle,
IoIosPlay,
IoIosPodium,
IoIosPower,
IoIosPricetag,
IoIosPricetags,
IoIosPrint,
IoIosPulse,
IoIosQrScanner,
IoIosQuote,
IoIosRadioButtonOff,
IoIosRadioButtonOn,
IoIosRadio,
IoIosRainy,
IoIosRecording,
IoIosRedo,
IoIosRefreshCircle,
IoIosRefresh,
IoIosRemoveCircleOutline,
IoIosRemoveCircle,
IoIosRemove,
IoIosReorder,
IoIosRepeat,
IoIosResize,
IoIosRestaurant,
IoIosReturnLeft,
IoIosReturnRight,
IoIosReverseCamera,
IoIosRewind,
IoIosRibbon,
IoIosRocket,
IoIosRose,
IoIosSad,
IoIosSave,
IoIosSchool,
IoIosSearch,
IoIosSend,
IoIosSettings,
IoIosShareAlt,
IoIosShare,
IoIosShirt,
IoIosShuffle,
IoIosSkipBackward,
IoIosSkipForward,
IoIosSnow,
IoIosSpeedometer,
IoIosSquareOutline,
IoIosSquare,
IoIosStarHalf,
IoIosStarOutline,
IoIosStar,
IoIosStats,
IoIosStopwatch,
IoIosSubway,
IoIosSunny,
IoIosSwap,
IoIosSwitch,
IoIosSync,
IoIosTabletLandscape,
IoIosTabletPortrait,
IoIosTennisball,
IoIosText,
IoIosThermometer,
IoIosThumbsDown,
IoIosThumbsUp,
IoIosThunderstorm,
IoIosTime,
IoIosTimer,
IoIosToday,
IoIosTrain,
IoIosTransgender,
IoIosTrash,
IoIosTrendingDown,
IoIosTrendingUp,
IoIosTrophy,
IoIosTv,
IoIosUmbrella,
IoIosUndo,
IoIosUnlock,
IoIosVideocam,
IoIosVolumeHigh,
IoIosVolumeLow,
IoIosVolumeMute,
IoIosVolumeOff,
IoIosWalk,
IoIosWallet,
IoIosWarning,
IoIosWatch,
IoIosWater,
IoIosWifi,
IoIosWine,
IoIosWoman,
IoLogoAndroid,
IoLogoAngular,
IoLogoApple,
IoLogoBitbucket,
IoLogoBitcoin,
IoLogoBuffer,
IoLogoChrome,
IoLogoClosedCaptioning,
IoLogoCodepen,
IoLogoCss3,
IoLogoDesignernews,
IoLogoDribbble,
IoLogoDropbox,
IoLogoEuro,
IoLogoFacebook,
IoLogoFlickr,
IoLogoFoursquare,
IoLogoFreebsdDevil,
IoLogoGameControllerA,
IoLogoGameControllerB,
IoLogoGithub,
IoLogoGoogle,
IoLogoGoogleplus,
IoLogoHackernews,
IoLogoHtml5,
IoLogoInstagram,
IoLogoIonic,
IoLogoIonitron,
IoLogoJavascript,
IoLogoLinkedin,
IoLogoMarkdown,
IoLogoModelS,
IoLogoNoSmoking,
IoLogoNodejs,
IoLogoNpm,
IoLogoOctocat,
IoLogoPinterest,
IoLogoPlaystation,
IoLogoPolymer,
IoLogoPython,
IoLogoReddit,
IoLogoRss,
IoLogoSass,
IoLogoSkype,
IoLogoSlack,
IoLogoSnapchat,
IoLogoSteam,
IoLogoTumblr,
IoLogoTux,
IoLogoTwitch,
IoLogoTwitter,
IoLogoUsd,
IoLogoVimeo,
IoLogoVk,
IoLogoWhatsapp,
IoLogoWindows,
IoLogoWordpress,
IoLogoXbox,
IoLogoXing,
IoLogoYahoo,
IoLogoYen,
IoLogoYoutube,
IoMdAddCircleOutline,
IoMdAddCircle,
IoMdAdd,
IoMdAirplane,
IoMdAlarm,
IoMdAlbums,
IoMdAlert,
IoMdAmericanFootball,
IoMdAnalytics,
IoMdAperture,
IoMdApps,
IoMdAppstore,
IoMdArchive,
IoMdArrowBack,
IoMdArrowDown,
IoMdArrowDropdownCircle,
IoMdArrowDropdown,
IoMdArrowDropleftCircle,
IoMdArrowDropleft,
IoMdArrowDroprightCircle,
IoMdArrowDropright,
IoMdArrowDropupCircle,
IoMdArrowDropup,
IoMdArrowForward,
IoMdArrowRoundBack,
IoMdArrowRoundDown,
IoMdArrowRoundForward,
IoMdArrowRoundUp,
IoMdArrowUp,
IoMdAt,
IoMdAttach,
IoMdBackspace,
IoMdBarcode,
IoMdBaseball,
IoMdBasket,
IoMdBasketball,
IoMdBatteryCharging,
IoMdBatteryDead,
IoMdBatteryFull,
IoMdBeaker,
IoMdBed,
IoMdBeer,
IoMdBicycle,
IoMdBluetooth,
IoMdBoat,
IoMdBody,
IoMdBonfire,
IoMdBook,
IoMdBookmark,
IoMdBookmarks,
IoMdBowtie,
IoMdBriefcase,
IoMdBrowsers,
IoMdBrush,
IoMdBug,
IoMdBuild,
IoMdBulb,
IoMdBus,
IoMdBusiness,
IoMdCafe,
IoMdCalculator,
IoMdCalendar,
IoMdCall,
IoMdCamera,
IoMdCar,
IoMdCard,
IoMdCart,
IoMdCash,
IoMdCellular,
IoMdChatboxes,
IoMdChatbubbles,
IoMdCheckboxOutline,
IoMdCheckbox,
IoMdCheckmarkCircleOutline,
IoMdCheckmarkCircle,
IoMdCheckmark,
IoMdClipboard,
IoMdClock,
IoMdCloseCircleOutline,
IoMdCloseCircle,
IoMdClose,
IoMdCloudCircle,
IoMdCloudDone,
IoMdCloudDownload,
IoMdCloudOutline,
IoMdCloudUpload,
IoMdCloud,
IoMdCloudyNight,
IoMdCloudy,
IoMdCodeDownload,
IoMdCodeWorking,
IoMdCode,
IoMdCog,
IoMdColorFill,
IoMdColorFilter,
IoMdColorPalette,
IoMdColorWand,
IoMdCompass,
IoMdConstruct,
IoMdContact,
IoMdContacts,
IoMdContract,
IoMdContrast,
IoMdCopy,
IoMdCreate,
IoMdCrop,
IoMdCube,
IoMdCut,
IoMdDesktop,
IoMdDisc,
IoMdDocument,
IoMdDoneAll,
IoMdDownload,
IoMdEasel,
IoMdEgg,
IoMdExit,
IoMdExpand,
IoMdEyeOff,
IoMdEye,
IoMdFastforward,
IoMdFemale,
IoMdFiling,
IoMdFilm,
IoMdFingerPrint,
IoMdFitness,
IoMdFlag,
IoMdFlame,
IoMdFlashOff,
IoMdFlash,
IoMdFlashlight,
IoMdFlask,
IoMdFlower,
IoMdFolderOpen,
IoMdFolder,
IoMdFootball,
IoMdFunnel,
IoMdGift,
IoMdGitBranch,
IoMdGitCommit,
IoMdGitCompare,
IoMdGitMerge,
IoMdGitNetwork,
IoMdGitPullRequest,
IoMdGlasses,
IoMdGlobe,
IoMdGrid,
IoMdHammer,
IoMdHand,
IoMdHappy,
IoMdHeadset,
IoMdHeartDislike,
IoMdHeartEmpty,
IoMdHeartHalf,
IoMdHeart,
IoMdHelpBuoy,
IoMdHelpCircleOutline,
IoMdHelpCircle,
IoMdHelp,
IoMdHome,
IoMdHourglass,
IoMdIceCream,
IoMdImage,
IoMdImages,
IoMdInfinite,
IoMdInformationCircleOutline,
IoMdInformationCircle,
IoMdInformation,
IoMdJet,
IoMdJournal,
IoMdKey,
IoMdKeypad,
IoMdLaptop,
IoMdLeaf,
IoMdLink,
IoMdListBox,
IoMdList,
IoMdLocate,
IoMdLock,
IoMdLogIn,
IoMdLogOut,
IoMdMagnet,
IoMdMailOpen,
IoMdMailUnread,
IoMdMail,
IoMdMale,
IoMdMan,
IoMdMap,
IoMdMedal,
IoMdMedical,
IoMdMedkit,
IoMdMegaphone,
IoMdMenu,
IoMdMicOff,
IoMdMic,
IoMdMicrophone,
IoMdMoon,
IoMdMore,
IoMdMove,
IoMdMusicalNote,
IoMdMusicalNotes,
IoMdNavigate,
IoMdNotificationsOff,
IoMdNotificationsOutline,
IoMdNotifications,
IoMdNuclear,
IoMdNutrition,
IoMdOpen,
IoMdOptions,
IoMdOutlet,
IoMdPaperPlane,
IoMdPaper,
IoMdPartlySunny,
IoMdPause,
IoMdPaw,
IoMdPeople,
IoMdPersonAdd,
IoMdPerson,
IoMdPhoneLandscape,
IoMdPhonePortrait,
IoMdPhotos,
IoMdPie,
IoMdPin,
IoMdPint,
IoMdPizza,
IoMdPlanet,
IoMdPlayCircle,
IoMdPlay,
IoMdPodium,
IoMdPower,
IoMdPricetag,
IoMdPricetags,
IoMdPrint,
IoMdPulse,
IoMdQrScanner,
IoMdQuote,
IoMdRadioButtonOff,
IoMdRadioButtonOn,
IoMdRadio,
IoMdRainy,
IoMdRecording,
IoMdRedo,
IoMdRefreshCircle,
IoMdRefresh,
IoMdRemoveCircleOutline,
IoMdRemoveCircle,
IoMdRemove,
IoMdReorder,
IoMdRepeat,
IoMdResize,
IoMdRestaurant,
IoMdReturnLeft,
IoMdReturnRight,
IoMdReverseCamera,
IoMdRewind,
IoMdRibbon,
IoMdRocket,
IoMdRose,
IoMdSad,
IoMdSave,
IoMdSchool,
IoMdSearch,
IoMdSend,
IoMdSettings,
IoMdShareAlt,
IoMdShare,
IoMdShirt,
IoMdShuffle,
IoMdSkipBackward,
IoMdSkipForward,
IoMdSnow,
IoMdSpeedometer,
IoMdSquareOutline,
IoMdSquare,
IoMdStarHalf,
IoMdStarOutline,
IoMdStar,
IoMdStats,
IoMdStopwatch,
IoMdSubway,
IoMdSunny,
IoMdSwap,
IoMdSwitch,
IoMdSync,
IoMdTabletLandscape,
IoMdTabletPortrait,
IoMdTennisball,
IoMdText,
IoMdThermometer,
IoMdThumbsDown,
IoMdThumbsUp,
IoMdThunderstorm,
IoMdTime,
IoMdTimer,
IoMdToday,
IoMdTrain,
IoMdTransgender,
IoMdTrash,
IoMdTrendingDown,
IoMdTrendingUp,
IoMdTrophy,
IoMdTv,
IoMdUmbrella,
IoMdUndo,
IoMdUnlock,
IoMdVideocam,
IoMdVolumeHigh,
IoMdVolumeLow,
IoMdVolumeMute,
IoMdVolumeOff,
IoMdWalk,
IoMdWallet,
IoMdWarning,
IoMdWatch,
IoMdWater,
IoMdWifi,
IoMdWine,
IoMdWoman,
} from "react-icons/io";

const result = [
{ icon: IoIosAddCircleOutline, name: "IoIosAddCircleOutline" },
{ icon: IoIosAddCircle, name: "IoIosAddCircle" },
{ icon: IoIosAdd, name: "IoIosAdd" },
{ icon: IoIosAirplane, name: "IoIosAirplane" },
{ icon: IoIosAlarm, name: "IoIosAlarm" },
{ icon: IoIosAlbums, name: "IoIosAlbums" },
{ icon: IoIosAlert, name: "IoIosAlert" },
{ icon: IoIosAmericanFootball, name: "IoIosAmericanFootball" },
{ icon: IoIosAnalytics, name: "IoIosAnalytics" },
{ icon: IoIosAperture, name: "IoIosAperture" },
{ icon: IoIosApps, name: "IoIosApps" },
{ icon: IoIosAppstore, name: "IoIosAppstore" },
{ icon: IoIosArchive, name: "IoIosArchive" },
{ icon: IoIosArrowBack, name: "IoIosArrowBack" },
{ icon: IoIosArrowDown, name: "IoIosArrowDown" },
{ icon: IoIosArrowDropdownCircle, name: "IoIosArrowDropdownCircle" },
{ icon: IoIosArrowDropdown, name: "IoIosArrowDropdown" },
{ icon: IoIosArrowDropleftCircle, name: "IoIosArrowDropleftCircle" },
{ icon: IoIosArrowDropleft, name: "IoIosArrowDropleft" },
{ icon: IoIosArrowDroprightCircle, name: "IoIosArrowDroprightCircle" },
{ icon: IoIosArrowDropright, name: "IoIosArrowDropright" },
{ icon: IoIosArrowDropupCircle, name: "IoIosArrowDropupCircle" },
{ icon: IoIosArrowDropup, name: "IoIosArrowDropup" },
{ icon: IoIosArrowForward, name: "IoIosArrowForward" },
{ icon: IoIosArrowRoundBack, name: "IoIosArrowRoundBack" },
{ icon: IoIosArrowRoundDown, name: "IoIosArrowRoundDown" },
{ icon: IoIosArrowRoundForward, name: "IoIosArrowRoundForward" },
{ icon: IoIosArrowRoundUp, name: "IoIosArrowRoundUp" },
{ icon: IoIosArrowUp, name: "IoIosArrowUp" },
{ icon: IoIosAt, name: "IoIosAt" },
{ icon: IoIosAttach, name: "IoIosAttach" },
{ icon: IoIosBackspace, name: "IoIosBackspace" },
{ icon: IoIosBarcode, name: "IoIosBarcode" },
{ icon: IoIosBaseball, name: "IoIosBaseball" },
{ icon: IoIosBasket, name: "IoIosBasket" },
{ icon: IoIosBasketball, name: "IoIosBasketball" },
{ icon: IoIosBatteryCharging, name: "IoIosBatteryCharging" },
{ icon: IoIosBatteryDead, name: "IoIosBatteryDead" },
{ icon: IoIosBatteryFull, name: "IoIosBatteryFull" },
{ icon: IoIosBeaker, name: "IoIosBeaker" },
{ icon: IoIosBed, name: "IoIosBed" },
{ icon: IoIosBeer, name: "IoIosBeer" },
{ icon: IoIosBicycle, name: "IoIosBicycle" },
{ icon: IoIosBluetooth, name: "IoIosBluetooth" },
{ icon: IoIosBoat, name: "IoIosBoat" },
{ icon: IoIosBody, name: "IoIosBody" },
{ icon: IoIosBonfire, name: "IoIosBonfire" },
{ icon: IoIosBook, name: "IoIosBook" },
{ icon: IoIosBookmark, name: "IoIosBookmark" },
{ icon: IoIosBookmarks, name: "IoIosBookmarks" },
{ icon: IoIosBowtie, name: "IoIosBowtie" },
{ icon: IoIosBriefcase, name: "IoIosBriefcase" },
{ icon: IoIosBrowsers, name: "IoIosBrowsers" },
{ icon: IoIosBrush, name: "IoIosBrush" },
{ icon: IoIosBug, name: "IoIosBug" },
{ icon: IoIosBuild, name: "IoIosBuild" },
{ icon: IoIosBulb, name: "IoIosBulb" },
{ icon: IoIosBus, name: "IoIosBus" },
{ icon: IoIosBusiness, name: "IoIosBusiness" },
{ icon: IoIosCafe, name: "IoIosCafe" },
{ icon: IoIosCalculator, name: "IoIosCalculator" },
{ icon: IoIosCalendar, name: "IoIosCalendar" },
{ icon: IoIosCall, name: "IoIosCall" },
{ icon: IoIosCamera, name: "IoIosCamera" },
{ icon: IoIosCar, name: "IoIosCar" },
{ icon: IoIosCard, name: "IoIosCard" },
{ icon: IoIosCart, name: "IoIosCart" },
{ icon: IoIosCash, name: "IoIosCash" },
{ icon: IoIosCellular, name: "IoIosCellular" },
{ icon: IoIosChatboxes, name: "IoIosChatboxes" },
{ icon: IoIosChatbubbles, name: "IoIosChatbubbles" },
{ icon: IoIosCheckboxOutline, name: "IoIosCheckboxOutline" },
{ icon: IoIosCheckbox, name: "IoIosCheckbox" },
{ icon: IoIosCheckmarkCircleOutline, name: "IoIosCheckmarkCircleOutline" },
{ icon: IoIosCheckmarkCircle, name: "IoIosCheckmarkCircle" },
{ icon: IoIosCheckmark, name: "IoIosCheckmark" },
{ icon: IoIosClipboard, name: "IoIosClipboard" },
{ icon: IoIosClock, name: "IoIosClock" },
{ icon: IoIosCloseCircleOutline, name: "IoIosCloseCircleOutline" },
{ icon: IoIosCloseCircle, name: "IoIosCloseCircle" },
{ icon: IoIosClose, name: "IoIosClose" },
{ icon: IoIosCloudCircle, name: "IoIosCloudCircle" },
{ icon: IoIosCloudDone, name: "IoIosCloudDone" },
{ icon: IoIosCloudDownload, name: "IoIosCloudDownload" },
{ icon: IoIosCloudOutline, name: "IoIosCloudOutline" },
{ icon: IoIosCloudUpload, name: "IoIosCloudUpload" },
{ icon: IoIosCloud, name: "IoIosCloud" },
{ icon: IoIosCloudyNight, name: "IoIosCloudyNight" },
{ icon: IoIosCloudy, name: "IoIosCloudy" },
{ icon: IoIosCodeDownload, name: "IoIosCodeDownload" },
{ icon: IoIosCodeWorking, name: "IoIosCodeWorking" },
{ icon: IoIosCode, name: "IoIosCode" },
{ icon: IoIosCog, name: "IoIosCog" },
{ icon: IoIosColorFill, name: "IoIosColorFill" },
{ icon: IoIosColorFilter, name: "IoIosColorFilter" },
{ icon: IoIosColorPalette, name: "IoIosColorPalette" },
{ icon: IoIosColorWand, name: "IoIosColorWand" },
{ icon: IoIosCompass, name: "IoIosCompass" },
{ icon: IoIosConstruct, name: "IoIosConstruct" },
{ icon: IoIosContact, name: "IoIosContact" },
{ icon: IoIosContacts, name: "IoIosContacts" },
{ icon: IoIosContract, name: "IoIosContract" },
{ icon: IoIosContrast, name: "IoIosContrast" },
{ icon: IoIosCopy, name: "IoIosCopy" },
{ icon: IoIosCreate, name: "IoIosCreate" },
{ icon: IoIosCrop, name: "IoIosCrop" },
{ icon: IoIosCube, name: "IoIosCube" },
{ icon: IoIosCut, name: "IoIosCut" },
{ icon: IoIosDesktop, name: "IoIosDesktop" },
{ icon: IoIosDisc, name: "IoIosDisc" },
{ icon: IoIosDocument, name: "IoIosDocument" },
{ icon: IoIosDoneAll, name: "IoIosDoneAll" },
{ icon: IoIosDownload, name: "IoIosDownload" },
{ icon: IoIosEasel, name: "IoIosEasel" },
{ icon: IoIosEgg, name: "IoIosEgg" },
{ icon: IoIosExit, name: "IoIosExit" },
{ icon: IoIosExpand, name: "IoIosExpand" },
{ icon: IoIosEyeOff, name: "IoIosEyeOff" },
{ icon: IoIosEye, name: "IoIosEye" },
{ icon: IoIosFastforward, name: "IoIosFastforward" },
{ icon: IoIosFemale, name: "IoIosFemale" },
{ icon: IoIosFiling, name: "IoIosFiling" },
{ icon: IoIosFilm, name: "IoIosFilm" },
{ icon: IoIosFingerPrint, name: "IoIosFingerPrint" },
{ icon: IoIosFitness, name: "IoIosFitness" },
{ icon: IoIosFlag, name: "IoIosFlag" },
{ icon: IoIosFlame, name: "IoIosFlame" },
{ icon: IoIosFlashOff, name: "IoIosFlashOff" },
{ icon: IoIosFlash, name: "IoIosFlash" },
{ icon: IoIosFlashlight, name: "IoIosFlashlight" },
{ icon: IoIosFlask, name: "IoIosFlask" },
{ icon: IoIosFlower, name: "IoIosFlower" },
{ icon: IoIosFolderOpen, name: "IoIosFolderOpen" },
{ icon: IoIosFolder, name: "IoIosFolder" },
{ icon: IoIosFootball, name: "IoIosFootball" },
{ icon: IoIosFunnel, name: "IoIosFunnel" },
{ icon: IoIosGift, name: "IoIosGift" },
{ icon: IoIosGitBranch, name: "IoIosGitBranch" },
{ icon: IoIosGitCommit, name: "IoIosGitCommit" },
{ icon: IoIosGitCompare, name: "IoIosGitCompare" },
{ icon: IoIosGitMerge, name: "IoIosGitMerge" },
{ icon: IoIosGitNetwork, name: "IoIosGitNetwork" },
{ icon: IoIosGitPullRequest, name: "IoIosGitPullRequest" },
{ icon: IoIosGlasses, name: "IoIosGlasses" },
{ icon: IoIosGlobe, name: "IoIosGlobe" },
{ icon: IoIosGrid, name: "IoIosGrid" },
{ icon: IoIosHammer, name: "IoIosHammer" },
{ icon: IoIosHand, name: "IoIosHand" },
{ icon: IoIosHappy, name: "IoIosHappy" },
{ icon: IoIosHeadset, name: "IoIosHeadset" },
{ icon: IoIosHeartDislike, name: "IoIosHeartDislike" },
{ icon: IoIosHeartEmpty, name: "IoIosHeartEmpty" },
{ icon: IoIosHeartHalf, name: "IoIosHeartHalf" },
{ icon: IoIosHeart, name: "IoIosHeart" },
{ icon: IoIosHelpBuoy, name: "IoIosHelpBuoy" },
{ icon: IoIosHelpCircleOutline, name: "IoIosHelpCircleOutline" },
{ icon: IoIosHelpCircle, name: "IoIosHelpCircle" },
{ icon: IoIosHelp, name: "IoIosHelp" },
{ icon: IoIosHome, name: "IoIosHome" },
{ icon: IoIosHourglass, name: "IoIosHourglass" },
{ icon: IoIosIceCream, name: "IoIosIceCream" },
{ icon: IoIosImage, name: "IoIosImage" },
{ icon: IoIosImages, name: "IoIosImages" },
{ icon: IoIosInfinite, name: "IoIosInfinite" },
{ icon: IoIosInformationCircleOutline, name: "IoIosInformationCircleOutline" },
{ icon: IoIosInformationCircle, name: "IoIosInformationCircle" },
{ icon: IoIosInformation, name: "IoIosInformation" },
{ icon: IoIosJet, name: "IoIosJet" },
{ icon: IoIosJournal, name: "IoIosJournal" },
{ icon: IoIosKey, name: "IoIosKey" },
{ icon: IoIosKeypad, name: "IoIosKeypad" },
{ icon: IoIosLaptop, name: "IoIosLaptop" },
{ icon: IoIosLeaf, name: "IoIosLeaf" },
{ icon: IoIosLink, name: "IoIosLink" },
{ icon: IoIosListBox, name: "IoIosListBox" },
{ icon: IoIosList, name: "IoIosList" },
{ icon: IoIosLocate, name: "IoIosLocate" },
{ icon: IoIosLock, name: "IoIosLock" },
{ icon: IoIosLogIn, name: "IoIosLogIn" },
{ icon: IoIosLogOut, name: "IoIosLogOut" },
{ icon: IoIosMagnet, name: "IoIosMagnet" },
{ icon: IoIosMailOpen, name: "IoIosMailOpen" },
{ icon: IoIosMailUnread, name: "IoIosMailUnread" },
{ icon: IoIosMail, name: "IoIosMail" },
{ icon: IoIosMale, name: "IoIosMale" },
{ icon: IoIosMan, name: "IoIosMan" },
{ icon: IoIosMap, name: "IoIosMap" },
{ icon: IoIosMedal, name: "IoIosMedal" },
{ icon: IoIosMedical, name: "IoIosMedical" },
{ icon: IoIosMedkit, name: "IoIosMedkit" },
{ icon: IoIosMegaphone, name: "IoIosMegaphone" },
{ icon: IoIosMenu, name: "IoIosMenu" },
{ icon: IoIosMicOff, name: "IoIosMicOff" },
{ icon: IoIosMic, name: "IoIosMic" },
{ icon: IoIosMicrophone, name: "IoIosMicrophone" },
{ icon: IoIosMoon, name: "IoIosMoon" },
{ icon: IoIosMore, name: "IoIosMore" },
{ icon: IoIosMove, name: "IoIosMove" },
{ icon: IoIosMusicalNote, name: "IoIosMusicalNote" },
{ icon: IoIosMusicalNotes, name: "IoIosMusicalNotes" },
{ icon: IoIosNavigate, name: "IoIosNavigate" },
{ icon: IoIosNotificationsOff, name: "IoIosNotificationsOff" },
{ icon: IoIosNotificationsOutline, name: "IoIosNotificationsOutline" },
{ icon: IoIosNotifications, name: "IoIosNotifications" },
{ icon: IoIosNuclear, name: "IoIosNuclear" },
{ icon: IoIosNutrition, name: "IoIosNutrition" },
{ icon: IoIosOpen, name: "IoIosOpen" },
{ icon: IoIosOptions, name: "IoIosOptions" },
{ icon: IoIosOutlet, name: "IoIosOutlet" },
{ icon: IoIosPaperPlane, name: "IoIosPaperPlane" },
{ icon: IoIosPaper, name: "IoIosPaper" },
{ icon: IoIosPartlySunny, name: "IoIosPartlySunny" },
{ icon: IoIosPause, name: "IoIosPause" },
{ icon: IoIosPaw, name: "IoIosPaw" },
{ icon: IoIosPeople, name: "IoIosPeople" },
{ icon: IoIosPersonAdd, name: "IoIosPersonAdd" },
{ icon: IoIosPerson, name: "IoIosPerson" },
{ icon: IoIosPhoneLandscape, name: "IoIosPhoneLandscape" },
{ icon: IoIosPhonePortrait, name: "IoIosPhonePortrait" },
{ icon: IoIosPhotos, name: "IoIosPhotos" },
{ icon: IoIosPie, name: "IoIosPie" },
{ icon: IoIosPin, name: "IoIosPin" },
{ icon: IoIosPint, name: "IoIosPint" },
{ icon: IoIosPizza, name: "IoIosPizza" },
{ icon: IoIosPlanet, name: "IoIosPlanet" },
{ icon: IoIosPlayCircle, name: "IoIosPlayCircle" },
{ icon: IoIosPlay, name: "IoIosPlay" },
{ icon: IoIosPodium, name: "IoIosPodium" },
{ icon: IoIosPower, name: "IoIosPower" },
{ icon: IoIosPricetag, name: "IoIosPricetag" },
{ icon: IoIosPricetags, name: "IoIosPricetags" },
{ icon: IoIosPrint, name: "IoIosPrint" },
{ icon: IoIosPulse, name: "IoIosPulse" },
{ icon: IoIosQrScanner, name: "IoIosQrScanner" },
{ icon: IoIosQuote, name: "IoIosQuote" },
{ icon: IoIosRadioButtonOff, name: "IoIosRadioButtonOff" },
{ icon: IoIosRadioButtonOn, name: "IoIosRadioButtonOn" },
{ icon: IoIosRadio, name: "IoIosRadio" },
{ icon: IoIosRainy, name: "IoIosRainy" },
{ icon: IoIosRecording, name: "IoIosRecording" },
{ icon: IoIosRedo, name: "IoIosRedo" },
{ icon: IoIosRefreshCircle, name: "IoIosRefreshCircle" },
{ icon: IoIosRefresh, name: "IoIosRefresh" },
{ icon: IoIosRemoveCircleOutline, name: "IoIosRemoveCircleOutline" },
{ icon: IoIosRemoveCircle, name: "IoIosRemoveCircle" },
{ icon: IoIosRemove, name: "IoIosRemove" },
{ icon: IoIosReorder, name: "IoIosReorder" },
{ icon: IoIosRepeat, name: "IoIosRepeat" },
{ icon: IoIosResize, name: "IoIosResize" },
{ icon: IoIosRestaurant, name: "IoIosRestaurant" },
{ icon: IoIosReturnLeft, name: "IoIosReturnLeft" },
{ icon: IoIosReturnRight, name: "IoIosReturnRight" },
{ icon: IoIosReverseCamera, name: "IoIosReverseCamera" },
{ icon: IoIosRewind, name: "IoIosRewind" },
{ icon: IoIosRibbon, name: "IoIosRibbon" },
{ icon: IoIosRocket, name: "IoIosRocket" },
{ icon: IoIosRose, name: "IoIosRose" },
{ icon: IoIosSad, name: "IoIosSad" },
{ icon: IoIosSave, name: "IoIosSave" },
{ icon: IoIosSchool, name: "IoIosSchool" },
{ icon: IoIosSearch, name: "IoIosSearch" },
{ icon: IoIosSend, name: "IoIosSend" },
{ icon: IoIosSettings, name: "IoIosSettings" },
{ icon: IoIosShareAlt, name: "IoIosShareAlt" },
{ icon: IoIosShare, name: "IoIosShare" },
{ icon: IoIosShirt, name: "IoIosShirt" },
{ icon: IoIosShuffle, name: "IoIosShuffle" },
{ icon: IoIosSkipBackward, name: "IoIosSkipBackward" },
{ icon: IoIosSkipForward, name: "IoIosSkipForward" },
{ icon: IoIosSnow, name: "IoIosSnow" },
{ icon: IoIosSpeedometer, name: "IoIosSpeedometer" },
{ icon: IoIosSquareOutline, name: "IoIosSquareOutline" },
{ icon: IoIosSquare, name: "IoIosSquare" },
{ icon: IoIosStarHalf, name: "IoIosStarHalf" },
{ icon: IoIosStarOutline, name: "IoIosStarOutline" },
{ icon: IoIosStar, name: "IoIosStar" },
{ icon: IoIosStats, name: "IoIosStats" },
{ icon: IoIosStopwatch, name: "IoIosStopwatch" },
{ icon: IoIosSubway, name: "IoIosSubway" },
{ icon: IoIosSunny, name: "IoIosSunny" },
{ icon: IoIosSwap, name: "IoIosSwap" },
{ icon: IoIosSwitch, name: "IoIosSwitch" },
{ icon: IoIosSync, name: "IoIosSync" },
{ icon: IoIosTabletLandscape, name: "IoIosTabletLandscape" },
{ icon: IoIosTabletPortrait, name: "IoIosTabletPortrait" },
{ icon: IoIosTennisball, name: "IoIosTennisball" },
{ icon: IoIosText, name: "IoIosText" },
{ icon: IoIosThermometer, name: "IoIosThermometer" },
{ icon: IoIosThumbsDown, name: "IoIosThumbsDown" },
{ icon: IoIosThumbsUp, name: "IoIosThumbsUp" },
{ icon: IoIosThunderstorm, name: "IoIosThunderstorm" },
{ icon: IoIosTime, name: "IoIosTime" },
{ icon: IoIosTimer, name: "IoIosTimer" },
{ icon: IoIosToday, name: "IoIosToday" },
{ icon: IoIosTrain, name: "IoIosTrain" },
{ icon: IoIosTransgender, name: "IoIosTransgender" },
{ icon: IoIosTrash, name: "IoIosTrash" },
{ icon: IoIosTrendingDown, name: "IoIosTrendingDown" },
{ icon: IoIosTrendingUp, name: "IoIosTrendingUp" },
{ icon: IoIosTrophy, name: "IoIosTrophy" },
{ icon: IoIosTv, name: "IoIosTv" },
{ icon: IoIosUmbrella, name: "IoIosUmbrella" },
{ icon: IoIosUndo, name: "IoIosUndo" },
{ icon: IoIosUnlock, name: "IoIosUnlock" },
{ icon: IoIosVideocam, name: "IoIosVideocam" },
{ icon: IoIosVolumeHigh, name: "IoIosVolumeHigh" },
{ icon: IoIosVolumeLow, name: "IoIosVolumeLow" },
{ icon: IoIosVolumeMute, name: "IoIosVolumeMute" },
{ icon: IoIosVolumeOff, name: "IoIosVolumeOff" },
{ icon: IoIosWalk, name: "IoIosWalk" },
{ icon: IoIosWallet, name: "IoIosWallet" },
{ icon: IoIosWarning, name: "IoIosWarning" },
{ icon: IoIosWatch, name: "IoIosWatch" },
{ icon: IoIosWater, name: "IoIosWater" },
{ icon: IoIosWifi, name: "IoIosWifi" },
{ icon: IoIosWine, name: "IoIosWine" },
{ icon: IoIosWoman, name: "IoIosWoman" },
{ icon: IoLogoAndroid, name: "IoLogoAndroid" },
{ icon: IoLogoAngular, name: "IoLogoAngular" },
{ icon: IoLogoApple, name: "IoLogoApple" },
{ icon: IoLogoBitbucket, name: "IoLogoBitbucket" },
{ icon: IoLogoBitcoin, name: "IoLogoBitcoin" },
{ icon: IoLogoBuffer, name: "IoLogoBuffer" },
{ icon: IoLogoChrome, name: "IoLogoChrome" },
{ icon: IoLogoClosedCaptioning, name: "IoLogoClosedCaptioning" },
{ icon: IoLogoCodepen, name: "IoLogoCodepen" },
{ icon: IoLogoCss3, name: "IoLogoCss3" },
{ icon: IoLogoDesignernews, name: "IoLogoDesignernews" },
{ icon: IoLogoDribbble, name: "IoLogoDribbble" },
{ icon: IoLogoDropbox, name: "IoLogoDropbox" },
{ icon: IoLogoEuro, name: "IoLogoEuro" },
{ icon: IoLogoFacebook, name: "IoLogoFacebook" },
{ icon: IoLogoFlickr, name: "IoLogoFlickr" },
{ icon: IoLogoFoursquare, name: "IoLogoFoursquare" },
{ icon: IoLogoFreebsdDevil, name: "IoLogoFreebsdDevil" },
{ icon: IoLogoGameControllerA, name: "IoLogoGameControllerA" },
{ icon: IoLogoGameControllerB, name: "IoLogoGameControllerB" },
{ icon: IoLogoGithub, name: "IoLogoGithub" },
{ icon: IoLogoGoogle, name: "IoLogoGoogle" },
{ icon: IoLogoGoogleplus, name: "IoLogoGoogleplus" },
{ icon: IoLogoHackernews, name: "IoLogoHackernews" },
{ icon: IoLogoHtml5, name: "IoLogoHtml5" },
{ icon: IoLogoInstagram, name: "IoLogoInstagram" },
{ icon: IoLogoIonic, name: "IoLogoIonic" },
{ icon: IoLogoIonitron, name: "IoLogoIonitron" },
{ icon: IoLogoJavascript, name: "IoLogoJavascript" },
{ icon: IoLogoLinkedin, name: "IoLogoLinkedin" },
{ icon: IoLogoMarkdown, name: "IoLogoMarkdown" },
{ icon: IoLogoModelS, name: "IoLogoModelS" },
{ icon: IoLogoNoSmoking, name: "IoLogoNoSmoking" },
{ icon: IoLogoNodejs, name: "IoLogoNodejs" },
{ icon: IoLogoNpm, name: "IoLogoNpm" },
{ icon: IoLogoOctocat, name: "IoLogoOctocat" },
{ icon: IoLogoPinterest, name: "IoLogoPinterest" },
{ icon: IoLogoPlaystation, name: "IoLogoPlaystation" },
{ icon: IoLogoPolymer, name: "IoLogoPolymer" },
{ icon: IoLogoPython, name: "IoLogoPython" },
{ icon: IoLogoReddit, name: "IoLogoReddit" },
{ icon: IoLogoRss, name: "IoLogoRss" },
{ icon: IoLogoSass, name: "IoLogoSass" },
{ icon: IoLogoSkype, name: "IoLogoSkype" },
{ icon: IoLogoSlack, name: "IoLogoSlack" },
{ icon: IoLogoSnapchat, name: "IoLogoSnapchat" },
{ icon: IoLogoSteam, name: "IoLogoSteam" },
{ icon: IoLogoTumblr, name: "IoLogoTumblr" },
{ icon: IoLogoTux, name: "IoLogoTux" },
{ icon: IoLogoTwitch, name: "IoLogoTwitch" },
{ icon: IoLogoTwitter, name: "IoLogoTwitter" },
{ icon: IoLogoUsd, name: "IoLogoUsd" },
{ icon: IoLogoVimeo, name: "IoLogoVimeo" },
{ icon: IoLogoVk, name: "IoLogoVk" },
{ icon: IoLogoWhatsapp, name: "IoLogoWhatsapp" },
{ icon: IoLogoWindows, name: "IoLogoWindows" },
{ icon: IoLogoWordpress, name: "IoLogoWordpress" },
{ icon: IoLogoXbox, name: "IoLogoXbox" },
{ icon: IoLogoXing, name: "IoLogoXing" },
{ icon: IoLogoYahoo, name: "IoLogoYahoo" },
{ icon: IoLogoYen, name: "IoLogoYen" },
{ icon: IoLogoYoutube, name: "IoLogoYoutube" },
{ icon: IoMdAddCircleOutline, name: "IoMdAddCircleOutline" },
{ icon: IoMdAddCircle, name: "IoMdAddCircle" },
{ icon: IoMdAdd, name: "IoMdAdd" },
{ icon: IoMdAirplane, name: "IoMdAirplane" },
{ icon: IoMdAlarm, name: "IoMdAlarm" },
{ icon: IoMdAlbums, name: "IoMdAlbums" },
{ icon: IoMdAlert, name: "IoMdAlert" },
{ icon: IoMdAmericanFootball, name: "IoMdAmericanFootball" },
{ icon: IoMdAnalytics, name: "IoMdAnalytics" },
{ icon: IoMdAperture, name: "IoMdAperture" },
{ icon: IoMdApps, name: "IoMdApps" },
{ icon: IoMdAppstore, name: "IoMdAppstore" },
{ icon: IoMdArchive, name: "IoMdArchive" },
{ icon: IoMdArrowBack, name: "IoMdArrowBack" },
{ icon: IoMdArrowDown, name: "IoMdArrowDown" },
{ icon: IoMdArrowDropdownCircle, name: "IoMdArrowDropdownCircle" },
{ icon: IoMdArrowDropdown, name: "IoMdArrowDropdown" },
{ icon: IoMdArrowDropleftCircle, name: "IoMdArrowDropleftCircle" },
{ icon: IoMdArrowDropleft, name: "IoMdArrowDropleft" },
{ icon: IoMdArrowDroprightCircle, name: "IoMdArrowDroprightCircle" },
{ icon: IoMdArrowDropright, name: "IoMdArrowDropright" },
{ icon: IoMdArrowDropupCircle, name: "IoMdArrowDropupCircle" },
{ icon: IoMdArrowDropup, name: "IoMdArrowDropup" },
{ icon: IoMdArrowForward, name: "IoMdArrowForward" },
{ icon: IoMdArrowRoundBack, name: "IoMdArrowRoundBack" },
{ icon: IoMdArrowRoundDown, name: "IoMdArrowRoundDown" },
{ icon: IoMdArrowRoundForward, name: "IoMdArrowRoundForward" },
{ icon: IoMdArrowRoundUp, name: "IoMdArrowRoundUp" },
{ icon: IoMdArrowUp, name: "IoMdArrowUp" },
{ icon: IoMdAt, name: "IoMdAt" },
{ icon: IoMdAttach, name: "IoMdAttach" },
{ icon: IoMdBackspace, name: "IoMdBackspace" },
{ icon: IoMdBarcode, name: "IoMdBarcode" },
{ icon: IoMdBaseball, name: "IoMdBaseball" },
{ icon: IoMdBasket, name: "IoMdBasket" },
{ icon: IoMdBasketball, name: "IoMdBasketball" },
{ icon: IoMdBatteryCharging, name: "IoMdBatteryCharging" },
{ icon: IoMdBatteryDead, name: "IoMdBatteryDead" },
{ icon: IoMdBatteryFull, name: "IoMdBatteryFull" },
{ icon: IoMdBeaker, name: "IoMdBeaker" },
{ icon: IoMdBed, name: "IoMdBed" },
{ icon: IoMdBeer, name: "IoMdBeer" },
{ icon: IoMdBicycle, name: "IoMdBicycle" },
{ icon: IoMdBluetooth, name: "IoMdBluetooth" },
{ icon: IoMdBoat, name: "IoMdBoat" },
{ icon: IoMdBody, name: "IoMdBody" },
{ icon: IoMdBonfire, name: "IoMdBonfire" },
{ icon: IoMdBook, name: "IoMdBook" },
{ icon: IoMdBookmark, name: "IoMdBookmark" },
{ icon: IoMdBookmarks, name: "IoMdBookmarks" },
{ icon: IoMdBowtie, name: "IoMdBowtie" },
{ icon: IoMdBriefcase, name: "IoMdBriefcase" },
{ icon: IoMdBrowsers, name: "IoMdBrowsers" },
{ icon: IoMdBrush, name: "IoMdBrush" },
{ icon: IoMdBug, name: "IoMdBug" },
{ icon: IoMdBuild, name: "IoMdBuild" },
{ icon: IoMdBulb, name: "IoMdBulb" },
{ icon: IoMdBus, name: "IoMdBus" },
{ icon: IoMdBusiness, name: "IoMdBusiness" },
{ icon: IoMdCafe, name: "IoMdCafe" },
{ icon: IoMdCalculator, name: "IoMdCalculator" },
{ icon: IoMdCalendar, name: "IoMdCalendar" },
{ icon: IoMdCall, name: "IoMdCall" },
{ icon: IoMdCamera, name: "IoMdCamera" },
{ icon: IoMdCar, name: "IoMdCar" },
{ icon: IoMdCard, name: "IoMdCard" },
{ icon: IoMdCart, name: "IoMdCart" },
{ icon: IoMdCash, name: "IoMdCash" },
{ icon: IoMdCellular, name: "IoMdCellular" },
{ icon: IoMdChatboxes, name: "IoMdChatboxes" },
{ icon: IoMdChatbubbles, name: "IoMdChatbubbles" },
{ icon: IoMdCheckboxOutline, name: "IoMdCheckboxOutline" },
{ icon: IoMdCheckbox, name: "IoMdCheckbox" },
{ icon: IoMdCheckmarkCircleOutline, name: "IoMdCheckmarkCircleOutline" },
{ icon: IoMdCheckmarkCircle, name: "IoMdCheckmarkCircle" },
{ icon: IoMdCheckmark, name: "IoMdCheckmark" },
{ icon: IoMdClipboard, name: "IoMdClipboard" },
{ icon: IoMdClock, name: "IoMdClock" },
{ icon: IoMdCloseCircleOutline, name: "IoMdCloseCircleOutline" },
{ icon: IoMdCloseCircle, name: "IoMdCloseCircle" },
{ icon: IoMdClose, name: "IoMdClose" },
{ icon: IoMdCloudCircle, name: "IoMdCloudCircle" },
{ icon: IoMdCloudDone, name: "IoMdCloudDone" },
{ icon: IoMdCloudDownload, name: "IoMdCloudDownload" },
{ icon: IoMdCloudOutline, name: "IoMdCloudOutline" },
{ icon: IoMdCloudUpload, name: "IoMdCloudUpload" },
{ icon: IoMdCloud, name: "IoMdCloud" },
{ icon: IoMdCloudyNight, name: "IoMdCloudyNight" },
{ icon: IoMdCloudy, name: "IoMdCloudy" },
{ icon: IoMdCodeDownload, name: "IoMdCodeDownload" },
{ icon: IoMdCodeWorking, name: "IoMdCodeWorking" },
{ icon: IoMdCode, name: "IoMdCode" },
{ icon: IoMdCog, name: "IoMdCog" },
{ icon: IoMdColorFill, name: "IoMdColorFill" },
{ icon: IoMdColorFilter, name: "IoMdColorFilter" },
{ icon: IoMdColorPalette, name: "IoMdColorPalette" },
{ icon: IoMdColorWand, name: "IoMdColorWand" },
{ icon: IoMdCompass, name: "IoMdCompass" },
{ icon: IoMdConstruct, name: "IoMdConstruct" },
{ icon: IoMdContact, name: "IoMdContact" },
{ icon: IoMdContacts, name: "IoMdContacts" },
{ icon: IoMdContract, name: "IoMdContract" },
{ icon: IoMdContrast, name: "IoMdContrast" },
{ icon: IoMdCopy, name: "IoMdCopy" },
{ icon: IoMdCreate, name: "IoMdCreate" },
{ icon: IoMdCrop, name: "IoMdCrop" },
{ icon: IoMdCube, name: "IoMdCube" },
{ icon: IoMdCut, name: "IoMdCut" },
{ icon: IoMdDesktop, name: "IoMdDesktop" },
{ icon: IoMdDisc, name: "IoMdDisc" },
{ icon: IoMdDocument, name: "IoMdDocument" },
{ icon: IoMdDoneAll, name: "IoMdDoneAll" },
{ icon: IoMdDownload, name: "IoMdDownload" },
{ icon: IoMdEasel, name: "IoMdEasel" },
{ icon: IoMdEgg, name: "IoMdEgg" },
{ icon: IoMdExit, name: "IoMdExit" },
{ icon: IoMdExpand, name: "IoMdExpand" },
{ icon: IoMdEyeOff, name: "IoMdEyeOff" },
{ icon: IoMdEye, name: "IoMdEye" },
{ icon: IoMdFastforward, name: "IoMdFastforward" },
{ icon: IoMdFemale, name: "IoMdFemale" },
{ icon: IoMdFiling, name: "IoMdFiling" },
{ icon: IoMdFilm, name: "IoMdFilm" },
{ icon: IoMdFingerPrint, name: "IoMdFingerPrint" },
{ icon: IoMdFitness, name: "IoMdFitness" },
{ icon: IoMdFlag, name: "IoMdFlag" },
{ icon: IoMdFlame, name: "IoMdFlame" },
{ icon: IoMdFlashOff, name: "IoMdFlashOff" },
{ icon: IoMdFlash, name: "IoMdFlash" },
{ icon: IoMdFlashlight, name: "IoMdFlashlight" },
{ icon: IoMdFlask, name: "IoMdFlask" },
{ icon: IoMdFlower, name: "IoMdFlower" },
{ icon: IoMdFolderOpen, name: "IoMdFolderOpen" },
{ icon: IoMdFolder, name: "IoMdFolder" },
{ icon: IoMdFootball, name: "IoMdFootball" },
{ icon: IoMdFunnel, name: "IoMdFunnel" },
{ icon: IoMdGift, name: "IoMdGift" },
{ icon: IoMdGitBranch, name: "IoMdGitBranch" },
{ icon: IoMdGitCommit, name: "IoMdGitCommit" },
{ icon: IoMdGitCompare, name: "IoMdGitCompare" },
{ icon: IoMdGitMerge, name: "IoMdGitMerge" },
{ icon: IoMdGitNetwork, name: "IoMdGitNetwork" },
{ icon: IoMdGitPullRequest, name: "IoMdGitPullRequest" },
{ icon: IoMdGlasses, name: "IoMdGlasses" },
{ icon: IoMdGlobe, name: "IoMdGlobe" },
{ icon: IoMdGrid, name: "IoMdGrid" },
{ icon: IoMdHammer, name: "IoMdHammer" },
{ icon: IoMdHand, name: "IoMdHand" },
{ icon: IoMdHappy, name: "IoMdHappy" },
{ icon: IoMdHeadset, name: "IoMdHeadset" },
{ icon: IoMdHeartDislike, name: "IoMdHeartDislike" },
{ icon: IoMdHeartEmpty, name: "IoMdHeartEmpty" },
{ icon: IoMdHeartHalf, name: "IoMdHeartHalf" },
{ icon: IoMdHeart, name: "IoMdHeart" },
{ icon: IoMdHelpBuoy, name: "IoMdHelpBuoy" },
{ icon: IoMdHelpCircleOutline, name: "IoMdHelpCircleOutline" },
{ icon: IoMdHelpCircle, name: "IoMdHelpCircle" },
{ icon: IoMdHelp, name: "IoMdHelp" },
{ icon: IoMdHome, name: "IoMdHome" },
{ icon: IoMdHourglass, name: "IoMdHourglass" },
{ icon: IoMdIceCream, name: "IoMdIceCream" },
{ icon: IoMdImage, name: "IoMdImage" },
{ icon: IoMdImages, name: "IoMdImages" },
{ icon: IoMdInfinite, name: "IoMdInfinite" },
{ icon: IoMdInformationCircleOutline, name: "IoMdInformationCircleOutline" },
{ icon: IoMdInformationCircle, name: "IoMdInformationCircle" },
{ icon: IoMdInformation, name: "IoMdInformation" },
{ icon: IoMdJet, name: "IoMdJet" },
{ icon: IoMdJournal, name: "IoMdJournal" },
{ icon: IoMdKey, name: "IoMdKey" },
{ icon: IoMdKeypad, name: "IoMdKeypad" },
{ icon: IoMdLaptop, name: "IoMdLaptop" },
{ icon: IoMdLeaf, name: "IoMdLeaf" },
{ icon: IoMdLink, name: "IoMdLink" },
{ icon: IoMdListBox, name: "IoMdListBox" },
{ icon: IoMdList, name: "IoMdList" },
{ icon: IoMdLocate, name: "IoMdLocate" },
{ icon: IoMdLock, name: "IoMdLock" },
{ icon: IoMdLogIn, name: "IoMdLogIn" },
{ icon: IoMdLogOut, name: "IoMdLogOut" },
{ icon: IoMdMagnet, name: "IoMdMagnet" },
{ icon: IoMdMailOpen, name: "IoMdMailOpen" },
{ icon: IoMdMailUnread, name: "IoMdMailUnread" },
{ icon: IoMdMail, name: "IoMdMail" },
{ icon: IoMdMale, name: "IoMdMale" },
{ icon: IoMdMan, name: "IoMdMan" },
{ icon: IoMdMap, name: "IoMdMap" },
{ icon: IoMdMedal, name: "IoMdMedal" },
{ icon: IoMdMedical, name: "IoMdMedical" },
{ icon: IoMdMedkit, name: "IoMdMedkit" },
{ icon: IoMdMegaphone, name: "IoMdMegaphone" },
{ icon: IoMdMenu, name: "IoMdMenu" },
{ icon: IoMdMicOff, name: "IoMdMicOff" },
{ icon: IoMdMic, name: "IoMdMic" },
{ icon: IoMdMicrophone, name: "IoMdMicrophone" },
{ icon: IoMdMoon, name: "IoMdMoon" },
{ icon: IoMdMore, name: "IoMdMore" },
{ icon: IoMdMove, name: "IoMdMove" },
{ icon: IoMdMusicalNote, name: "IoMdMusicalNote" },
{ icon: IoMdMusicalNotes, name: "IoMdMusicalNotes" },
{ icon: IoMdNavigate, name: "IoMdNavigate" },
{ icon: IoMdNotificationsOff, name: "IoMdNotificationsOff" },
{ icon: IoMdNotificationsOutline, name: "IoMdNotificationsOutline" },
{ icon: IoMdNotifications, name: "IoMdNotifications" },
{ icon: IoMdNuclear, name: "IoMdNuclear" },
{ icon: IoMdNutrition, name: "IoMdNutrition" },
{ icon: IoMdOpen, name: "IoMdOpen" },
{ icon: IoMdOptions, name: "IoMdOptions" },
{ icon: IoMdOutlet, name: "IoMdOutlet" },
{ icon: IoMdPaperPlane, name: "IoMdPaperPlane" },
{ icon: IoMdPaper, name: "IoMdPaper" },
{ icon: IoMdPartlySunny, name: "IoMdPartlySunny" },
{ icon: IoMdPause, name: "IoMdPause" },
{ icon: IoMdPaw, name: "IoMdPaw" },
{ icon: IoMdPeople, name: "IoMdPeople" },
{ icon: IoMdPersonAdd, name: "IoMdPersonAdd" },
{ icon: IoMdPerson, name: "IoMdPerson" },
{ icon: IoMdPhoneLandscape, name: "IoMdPhoneLandscape" },
{ icon: IoMdPhonePortrait, name: "IoMdPhonePortrait" },
{ icon: IoMdPhotos, name: "IoMdPhotos" },
{ icon: IoMdPie, name: "IoMdPie" },
{ icon: IoMdPin, name: "IoMdPin" },
{ icon: IoMdPint, name: "IoMdPint" },
{ icon: IoMdPizza, name: "IoMdPizza" },
{ icon: IoMdPlanet, name: "IoMdPlanet" },
{ icon: IoMdPlayCircle, name: "IoMdPlayCircle" },
{ icon: IoMdPlay, name: "IoMdPlay" },
{ icon: IoMdPodium, name: "IoMdPodium" },
{ icon: IoMdPower, name: "IoMdPower" },
{ icon: IoMdPricetag, name: "IoMdPricetag" },
{ icon: IoMdPricetags, name: "IoMdPricetags" },
{ icon: IoMdPrint, name: "IoMdPrint" },
{ icon: IoMdPulse, name: "IoMdPulse" },
{ icon: IoMdQrScanner, name: "IoMdQrScanner" },
{ icon: IoMdQuote, name: "IoMdQuote" },
{ icon: IoMdRadioButtonOff, name: "IoMdRadioButtonOff" },
{ icon: IoMdRadioButtonOn, name: "IoMdRadioButtonOn" },
{ icon: IoMdRadio, name: "IoMdRadio" },
{ icon: IoMdRainy, name: "IoMdRainy" },
{ icon: IoMdRecording, name: "IoMdRecording" },
{ icon: IoMdRedo, name: "IoMdRedo" },
{ icon: IoMdRefreshCircle, name: "IoMdRefreshCircle" },
{ icon: IoMdRefresh, name: "IoMdRefresh" },
{ icon: IoMdRemoveCircleOutline, name: "IoMdRemoveCircleOutline" },
{ icon: IoMdRemoveCircle, name: "IoMdRemoveCircle" },
{ icon: IoMdRemove, name: "IoMdRemove" },
{ icon: IoMdReorder, name: "IoMdReorder" },
{ icon: IoMdRepeat, name: "IoMdRepeat" },
{ icon: IoMdResize, name: "IoMdResize" },
{ icon: IoMdRestaurant, name: "IoMdRestaurant" },
{ icon: IoMdReturnLeft, name: "IoMdReturnLeft" },
{ icon: IoMdReturnRight, name: "IoMdReturnRight" },
{ icon: IoMdReverseCamera, name: "IoMdReverseCamera" },
{ icon: IoMdRewind, name: "IoMdRewind" },
{ icon: IoMdRibbon, name: "IoMdRibbon" },
{ icon: IoMdRocket, name: "IoMdRocket" },
{ icon: IoMdRose, name: "IoMdRose" },
{ icon: IoMdSad, name: "IoMdSad" },
{ icon: IoMdSave, name: "IoMdSave" },
{ icon: IoMdSchool, name: "IoMdSchool" },
{ icon: IoMdSearch, name: "IoMdSearch" },
{ icon: IoMdSend, name: "IoMdSend" },
{ icon: IoMdSettings, name: "IoMdSettings" },
{ icon: IoMdShareAlt, name: "IoMdShareAlt" },
{ icon: IoMdShare, name: "IoMdShare" },
{ icon: IoMdShirt, name: "IoMdShirt" },
{ icon: IoMdShuffle, name: "IoMdShuffle" },
{ icon: IoMdSkipBackward, name: "IoMdSkipBackward" },
{ icon: IoMdSkipForward, name: "IoMdSkipForward" },
{ icon: IoMdSnow, name: "IoMdSnow" },
{ icon: IoMdSpeedometer, name: "IoMdSpeedometer" },
{ icon: IoMdSquareOutline, name: "IoMdSquareOutline" },
{ icon: IoMdSquare, name: "IoMdSquare" },
{ icon: IoMdStarHalf, name: "IoMdStarHalf" },
{ icon: IoMdStarOutline, name: "IoMdStarOutline" },
{ icon: IoMdStar, name: "IoMdStar" },
{ icon: IoMdStats, name: "IoMdStats" },
{ icon: IoMdStopwatch, name: "IoMdStopwatch" },
{ icon: IoMdSubway, name: "IoMdSubway" },
{ icon: IoMdSunny, name: "IoMdSunny" },
{ icon: IoMdSwap, name: "IoMdSwap" },
{ icon: IoMdSwitch, name: "IoMdSwitch" },
{ icon: IoMdSync, name: "IoMdSync" },
{ icon: IoMdTabletLandscape, name: "IoMdTabletLandscape" },
{ icon: IoMdTabletPortrait, name: "IoMdTabletPortrait" },
{ icon: IoMdTennisball, name: "IoMdTennisball" },
{ icon: IoMdText, name: "IoMdText" },
{ icon: IoMdThermometer, name: "IoMdThermometer" },
{ icon: IoMdThumbsDown, name: "IoMdThumbsDown" },
{ icon: IoMdThumbsUp, name: "IoMdThumbsUp" },
{ icon: IoMdThunderstorm, name: "IoMdThunderstorm" },
{ icon: IoMdTime, name: "IoMdTime" },
{ icon: IoMdTimer, name: "IoMdTimer" },
{ icon: IoMdToday, name: "IoMdToday" },
{ icon: IoMdTrain, name: "IoMdTrain" },
{ icon: IoMdTransgender, name: "IoMdTransgender" },
{ icon: IoMdTrash, name: "IoMdTrash" },
{ icon: IoMdTrendingDown, name: "IoMdTrendingDown" },
{ icon: IoMdTrendingUp, name: "IoMdTrendingUp" },
{ icon: IoMdTrophy, name: "IoMdTrophy" },
{ icon: IoMdTv, name: "IoMdTv" },
{ icon: IoMdUmbrella, name: "IoMdUmbrella" },
{ icon: IoMdUndo, name: "IoMdUndo" },
{ icon: IoMdUnlock, name: "IoMdUnlock" },
{ icon: IoMdVideocam, name: "IoMdVideocam" },
{ icon: IoMdVolumeHigh, name: "IoMdVolumeHigh" },
{ icon: IoMdVolumeLow, name: "IoMdVolumeLow" },
{ icon: IoMdVolumeMute, name: "IoMdVolumeMute" },
{ icon: IoMdVolumeOff, name: "IoMdVolumeOff" },
{ icon: IoMdWalk, name: "IoMdWalk" },
{ icon: IoMdWallet, name: "IoMdWallet" },
{ icon: IoMdWarning, name: "IoMdWarning" },
{ icon: IoMdWatch, name: "IoMdWatch" },
{ icon: IoMdWater, name: "IoMdWater" },
{ icon: IoMdWifi, name: "IoMdWifi" },
{ icon: IoMdWine, name: "IoMdWine" },
{ icon: IoMdWoman, name: "IoMdWoman" },
];

export default result