import {
IoIosAddCircleOutline,
IoIosAddCircle,
IoIosAdd,
IoIosAirplane,
IoIosAlarm,
IoIosAlbums,
IoIosAlert,
IoIosAmericanFootball,
IoIosAnalytics,
IoIosAperture,
IoIosApps,
IoIosAppstore,
IoIosArchive,
IoIosArrowBack,
IoIosArrowDown,
IoIosArrowDropdownCircle,
IoIosArrowDropdown,
IoIosArrowDropleftCircle,
IoIosArrowDropleft,
IoIosArrowDroprightCircle,
IoIosArrowDropright,
IoIosArrowDropupCircle,
IoIosArrowDropup,
IoIosArrowForward,
IoIosArrowRoundBack,
IoIosArrowRoundDown,
IoIosArrowRoundForward,
IoIosArrowRoundUp,
IoIosArrowUp,
IoIosAt,
IoIosAttach,
IoIosBackspace,
IoIosBarcode,
IoIosBaseball,
IoIosBasket,
IoIosBasketball,
IoIosBatteryCharging,
IoIosBatteryDead,
IoIosBatteryFull,
IoIosBeaker,
IoIosBed,
IoIosBeer,
IoIosBicycle,
IoIosBluetooth,
IoIosBoat,
IoIosBody,
IoIosBonfire,
IoIosBook,
IoIosBookmark,
IoIosBookmarks,
IoIosBowtie,
IoIosBriefcase,
IoIosBrowsers,
IoIosBrush,
IoIosBug,
IoIosBuild,
IoIosBulb,
IoIosBus,
IoIosBusiness,
IoIosCafe,
IoIosCalculator,
IoIosCalendar,
IoIosCall,
IoIosCamera,
IoIosCar,
IoIosCard,
IoIosCart,
IoIosCash,
IoIosCellular,
IoIosChatboxes,
IoIosChatbubbles,
IoIosCheckboxOutline,
IoIosCheckbox,
IoIosCheckmarkCircleOutline,
IoIosCheckmarkCircle,
IoIosCheckmark,
IoIosClipboard,
IoIosClock,
IoIosCloseCircleOutline,
IoIosCloseCircle,
IoIosClose,
IoIosCloudCircle,
IoIosCloudDone,
IoIosCloudDownload,
IoIosCloudOutline,
IoIosCloudUpload,
IoIosCloud,
IoIosCloudyNight,
IoIosCloudy,
IoIosCodeDownload,
IoIosCodeWorking,
IoIosCode,
IoIosCog,
IoIosColorFill,
IoIosColorFilter,
IoIosColorPalette,
IoIosColorWand,
IoIosCompass,
IoIosConstruct,
IoIosContact,
IoIosContacts,
IoIosContract,
IoIosContrast,
IoIosCopy,
IoIosCreate,
IoIosCrop,
IoIosCube,
IoIosCut,
IoIosDesktop,
IoIosDisc,
IoIosDocument,
IoIosDoneAll,
IoIosDownload,
IoIosEasel,
IoIosEgg,
IoIosExit,
IoIosExpand,
IoIosEyeOff,
IoIosEye,
IoIosFastforward,
IoIosFemale,
IoIosFiling,
IoIosFilm,
IoIosFingerPrint,
IoIosFitness,
IoIosFlag,
IoIosFlame,
IoIosFlashOff,
IoIosFlash,
IoIosFlashlight,
IoIosFlask,
IoIosFlower,
IoIosFolderOpen,
IoIosFolder,
IoIosFootball,
IoIosFunnel,
IoIosGift,
IoIosGitBranch,
IoIosGitCommit,
IoIosGitCompare,
IoIosGitMerge,
IoIosGitNetwork,
IoIosGitPullRequest,
IoIosGlasses,
IoIosGlobe,
IoIosGrid,
IoIosHammer,
IoIosHand,
IoIosHappy,
IoIosHeadset,
IoIosHeartDislike,
IoIosHeartEmpty,
IoIosHeartHalf,
IoIosHeart,
IoIosHelpBuoy,
IoIosHelpCircleOutline,
IoIosHelpCircle,
IoIosHelp,
IoIosHome,
IoIosHourglass,
IoIosIceCream,
IoIosImage,
IoIosImages,
IoIosInfinite,
IoIosInformationCircleOutline,
IoIosInformationCircle,
IoIosInformation,
IoIosJet,
IoIosJournal,
IoIosKey,
IoIosKeypad,
IoIosLaptop,
IoIosLeaf,
IoIosLink,
IoIosListBox,
IoIosList,
IoIosLocate,
IoIosLock,
IoIosLogIn,
IoIosLogOut,
IoIosMagnet,
IoIosMailOpen,
IoIosMailUnread,
IoIosMail,
IoIosMale,
IoIosMan,
IoIosMap,
IoIosMedal,
IoIosMedical,
IoIosMedkit,
IoIosMegaphone,
IoIosMenu,
IoIosMicOff,
IoIosMic,
IoIosMicrophone,
IoIosMoon,
IoIosMore,
IoIosMove,
IoIosMusicalNote,
IoIosMusicalNotes,
IoIosNavigate,
IoIosNotificationsOff,
IoIosNotificationsOutline,
IoIosNotifications,
IoIosNuclear,
IoIosNutrition,
IoIosOpen,
IoIosOptions,
IoIosOutlet,
IoIosPaperPlane,
IoIosPaper,
IoIosPartlySunny,
IoIosPause,
IoIosPaw,
IoIosPeople,
IoIosPersonAdd,
IoIosPerson,
IoIosPhoneLandscape,
IoIosPhonePortrait,
IoIosPhotos,
IoIosPie,
IoIosPin,
IoIosPint,
IoIosPizza,
IoIosPlanet,
IoIosPlayCircle,
IoIosPlay,
IoIosPodium,
IoIosPower,
IoIosPricetag,
IoIosPricetags,
IoIosPrint,
IoIosPulse,
IoIosQrScanner,
IoIosQuote,
IoIosRadioButtonOff,
IoIosRadioButtonOn,
IoIosRadio,
IoIosRainy,
IoIosRecording,
IoIosRedo,
IoIosRefreshCircle,
IoIosRefresh,
IoIosRemoveCircleOutline,
IoIosRemoveCircle,
IoIosRemove,
IoIosReorder,
IoIosRepeat,
IoIosResize,
IoIosRestaurant,
IoIosReturnLeft,
IoIosReturnRight,
IoIosReverseCamera,
IoIosRewind,
IoIosRibbon,
IoIosRocket,
IoIosRose,
IoIosSad,
IoIosSave,
IoIosSchool,
IoIosSearch,
IoIosSend,
IoIosSettings,
IoIosShareAlt,
IoIosShare,
IoIosShirt,
IoIosShuffle,
IoIosSkipBackward,
IoIosSkipForward,
IoIosSnow,
IoIosSpeedometer,
IoIosSquareOutline,
IoIosSquare,
IoIosStarHalf,
IoIosStarOutline,
IoIosStar,
IoIosStats,
IoIosStopwatch,
IoIosSubway,
IoIosSunny,
IoIosSwap,
IoIosSwitch,
IoIosSync,
IoIosTabletLandscape,
IoIosTabletPortrait,
IoIosTennisball,
IoIosText,
IoIosThermometer,
IoIosThumbsDown,
IoIosThumbsUp,
IoIosThunderstorm,
IoIosTime,
IoIosTimer,
IoIosToday,
IoIosTrain,
IoIosTransgender,
IoIosTrash,
IoIosTrendingDown,
IoIosTrendingUp,
IoIosTrophy,
IoIosTv,
IoIosUmbrella,
IoIosUndo,
IoIosUnlock,
IoIosVideocam,
IoIosVolumeHigh,
IoIosVolumeLow,
IoIosVolumeMute,
IoIosVolumeOff,
IoIosWalk,
IoIosWallet,
IoIosWarning,
IoIosWatch,
IoIosWater,
IoIosWifi,
IoIosWine,
IoIosWoman,
IoLogoAndroid,
IoLogoAngular,
IoLogoApple,
IoLogoBitbucket,
IoLogoBitcoin,
IoLogoBuffer,
IoLogoChrome,
IoLogoClosedCaptioning,
IoLogoCodepen,
IoLogoCss3,
IoLogoDesignernews,
IoLogoDribbble,
IoLogoDropbox,
IoLogoEuro,
IoLogoFacebook,
IoLogoFlickr,
IoLogoFoursquare,
IoLogoFreebsdDevil,
IoLogoGameControllerA,
IoLogoGameControllerB,
IoLogoGithub,
IoLogoGoogle,
IoLogoGoogleplus,
IoLogoHackernews,
IoLogoHtml5,
IoLogoInstagram,
IoLogoIonic,
IoLogoIonitron,
IoLogoJavascript,
IoLogoLinkedin,
IoLogoMarkdown,
IoLogoModelS,
IoLogoNoSmoking,
IoLogoNodejs,
IoLogoNpm,
IoLogoOctocat,
IoLogoPinterest,
IoLogoPlaystation,
IoLogoPolymer,
IoLogoPython,
IoLogoReddit,
IoLogoRss,
IoLogoSass,
IoLogoSkype,
IoLogoSlack,
IoLogoSnapchat,
IoLogoSteam,
IoLogoTumblr,
IoLogoTux,
IoLogoTwitch,
IoLogoTwitter,
IoLogoUsd,
IoLogoVimeo,
IoLogoVk,
IoLogoWhatsapp,
IoLogoWindows,
IoLogoWordpress,
IoLogoXbox,
IoLogoXing,
IoLogoYahoo,
IoLogoYen,
IoLogoYoutube,
IoMdAddCircleOutline,
IoMdAddCircle,
IoMdAdd,
IoMdAirplane,
IoMdAlarm,
IoMdAlbums,
IoMdAlert,
IoMdAmericanFootball,
IoMdAnalytics,
IoMdAperture,
IoMdApps,
IoMdAppstore,
IoMdArchive,
IoMdArrowBack,
IoMdArrowDown,
IoMdArrowDropdownCircle,
IoMdArrowDropdown,
IoMdArrowDropleftCircle,
IoMdArrowDropleft,
IoMdArrowDroprightCircle,
IoMdArrowDropright,
IoMdArrowDropupCircle,
IoMdArrowDropup,
IoMdArrowForward,
IoMdArrowRoundBack,
IoMdArrowRoundDown,
IoMdArrowRoundForward,
IoMdArrowRoundUp,
IoMdArrowUp,
IoMdAt,
IoMdAttach,
IoMdBackspace,
IoMdBarcode,
IoMdBaseball,
IoMdBasket,
IoMdBasketball,
IoMdBatteryCharging,
IoMdBatteryDead,
IoMdBatteryFull,
IoMdBeaker,
IoMdBed,
IoMdBeer,
IoMdBicycle,
IoMdBluetooth,
IoMdBoat,
IoMdBody,
IoMdBonfire,
IoMdBook,
IoMdBookmark,
IoMdBookmarks,
IoMdBowtie,
IoMdBriefcase,
IoMdBrowsers,
IoMdBrush,
IoMdBug,
IoMdBuild,
IoMdBulb,
IoMdBus,
IoMdBusiness,
IoMdCafe,
IoMdCalculator,
IoMdCalendar,
IoMdCall,
IoMdCamera,
IoMdCar,
IoMdCard,
IoMdCart,
IoMdCash,
IoMdCellular,
IoMdChatboxes,
IoMdChatbubbles,
IoMdCheckboxOutline,
IoMdCheckbox,
IoMdCheckmarkCircleOutline,
IoMdCheckmarkCircle,
IoMdCheckmark,
IoMdClipboard,
IoMdClock,
IoMdCloseCircleOutline,
IoMdCloseCircle,
IoMdClose,
IoMdCloudCircle,
IoMdCloudDone,
IoMdCloudDownload,
IoMdCloudOutline,
IoMdCloudUpload,
IoMdCloud,
IoMdCloudyNight,
IoMdCloudy,
IoMdCodeDownload,
IoMdCodeWorking,
IoMdCode,
IoMdCog,
IoMdColorFill,
IoMdColorFilter,
IoMdColorPalette,
IoMdColorWand,
IoMdCompass,
IoMdConstruct,
IoMdContact,
IoMdContacts,
IoMdContract,
IoMdContrast,
IoMdCopy,
IoMdCreate,
IoMdCrop,
IoMdCube,
IoMdCut,
IoMdDesktop,
IoMdDisc,
IoMdDocument,
IoMdDoneAll,
IoMdDownload,
IoMdEasel,
IoMdEgg,
IoMdExit,
IoMdExpand,
IoMdEyeOff,
IoMdEye,
IoMdFastforward,
IoMdFemale,
IoMdFiling,
IoMdFilm,
IoMdFingerPrint,
IoMdFitness,
IoMdFlag,
IoMdFlame,
IoMdFlashOff,
IoMdFlash,
IoMdFlashlight,
IoMdFlask,
IoMdFlower,
IoMdFolderOpen,
IoMdFolder,
IoMdFootball,
IoMdFunnel,
IoMdGift,
IoMdGitBranch,
IoMdGitCommit,
IoMdGitCompare,
IoMdGitMerge,
IoMdGitNetwork,
IoMdGitPullRequest,
IoMdGlasses,
IoMdGlobe,
IoMdGrid,
IoMdHammer,
IoMdHand,
IoMdHappy,
IoMdHeadset,
IoMdHeartDislike,
IoMdHeartEmpty,
IoMdHeartHalf,
IoMdHeart,
IoMdHelpBuoy,
IoMdHelpCircleOutline,
IoMdHelpCircle,
IoMdHelp,
IoMdHome,
IoMdHourglass,
IoMdIceCream,
IoMdImage,
IoMdImages,
IoMdInfinite,
IoMdInformationCircleOutline,
IoMdInformationCircle,
IoMdInformation,
IoMdJet,
IoMdJournal,
IoMdKey,
IoMdKeypad,
IoMdLaptop,
IoMdLeaf,
IoMdLink,
IoMdListBox,
IoMdList,
IoMdLocate,
IoMdLock,
IoMdLogIn,
IoMdLogOut,
IoMdMagnet,
IoMdMailOpen,
IoMdMailUnread,
IoMdMail,
IoMdMale,
IoMdMan,
IoMdMap,
IoMdMedal,
IoMdMedical,
IoMdMedkit,
IoMdMegaphone,
IoMdMenu,
IoMdMicOff,
IoMdMic,
IoMdMicrophone,
IoMdMoon,
IoMdMore,
IoMdMove,
IoMdMusicalNote,
IoMdMusicalNotes,
IoMdNavigate,
IoMdNotificationsOff,
IoMdNotificationsOutline,
IoMdNotifications,
IoMdNuclear,
IoMdNutrition,
IoMdOpen,
IoMdOptions,
IoMdOutlet,
IoMdPaperPlane,
IoMdPaper,
IoMdPartlySunny,
IoMdPause,
IoMdPaw,
IoMdPeople,
IoMdPersonAdd,
IoMdPerson,
IoMdPhoneLandscape,
IoMdPhonePortrait,
IoMdPhotos,
IoMdPie,
IoMdPin,
IoMdPint,
IoMdPizza,
IoMdPlanet,
IoMdPlayCircle,
IoMdPlay,
IoMdPodium,
IoMdPower,
IoMdPricetag,
IoMdPricetags,
IoMdPrint,
IoMdPulse,
IoMdQrScanner,
IoMdQuote,
IoMdRadioButtonOff,
IoMdRadioButtonOn,
IoMdRadio,
IoMdRainy,
IoMdRecording,
IoMdRedo,
IoMdRefreshCircle,
IoMdRefresh,
IoMdRemoveCircleOutline,
IoMdRemoveCircle,
IoMdRemove,
IoMdReorder,
IoMdRepeat,
IoMdResize,
IoMdRestaurant,
IoMdReturnLeft,
IoMdReturnRight,
IoMdReverseCamera,
IoMdRewind,
IoMdRibbon,
IoMdRocket,
IoMdRose,
IoMdSad,
IoMdSave,
IoMdSchool,
IoMdSearch,
IoMdSend,
IoMdSettings,
IoMdShareAlt,
IoMdShare,
IoMdShirt,
IoMdShuffle,
IoMdSkipBackward,
IoMdSkipForward,
IoMdSnow,
IoMdSpeedometer,
IoMdSquareOutline,
IoMdSquare,
IoMdStarHalf,
IoMdStarOutline,
IoMdStar,
IoMdStats,
IoMdStopwatch,
IoMdSubway,
IoMdSunny,
IoMdSwap,
IoMdSwitch,
IoMdSync,
IoMdTabletLandscape,
IoMdTabletPortrait,
IoMdTennisball,
IoMdText,
IoMdThermometer,
IoMdThumbsDown,
IoMdThumbsUp,
IoMdThunderstorm,
IoMdTime,
IoMdTimer,
IoMdToday,
IoMdTrain,
IoMdTransgender,
IoMdTrash,
IoMdTrendingDown,
IoMdTrendingUp,
IoMdTrophy,
IoMdTv,
IoMdUmbrella,
IoMdUndo,
IoMdUnlock,
IoMdVideocam,
IoMdVolumeHigh,
IoMdVolumeLow,
IoMdVolumeMute,
IoMdVolumeOff,
IoMdWalk,
IoMdWallet,
IoMdWarning,
IoMdWatch,
IoMdWater,
IoMdWifi,
IoMdWine,
IoMdWoman,
} from "react-icons/io";

const result = [
{ icon: IoIosAddCircleOutline, name: "IoIosAddCircleOutline" ,library:"io" },
{ icon: IoIosAddCircle, name: "IoIosAddCircle" ,library:"io" },
{ icon: IoIosAdd, name: "IoIosAdd" ,library:"io" },
{ icon: IoIosAirplane, name: "IoIosAirplane" ,library:"io" },
{ icon: IoIosAlarm, name: "IoIosAlarm" ,library:"io" },
{ icon: IoIosAlbums, name: "IoIosAlbums" ,library:"io" },
{ icon: IoIosAlert, name: "IoIosAlert" ,library:"io" },
{ icon: IoIosAmericanFootball, name: "IoIosAmericanFootball" ,library:"io" },
{ icon: IoIosAnalytics, name: "IoIosAnalytics" ,library:"io" },
{ icon: IoIosAperture, name: "IoIosAperture" ,library:"io" },
{ icon: IoIosApps, name: "IoIosApps" ,library:"io" },
{ icon: IoIosAppstore, name: "IoIosAppstore" ,library:"io" },
{ icon: IoIosArchive, name: "IoIosArchive" ,library:"io" },
{ icon: IoIosArrowBack, name: "IoIosArrowBack" ,library:"io" },
{ icon: IoIosArrowDown, name: "IoIosArrowDown" ,library:"io" },
{ icon: IoIosArrowDropdownCircle, name: "IoIosArrowDropdownCircle" ,library:"io" },
{ icon: IoIosArrowDropdown, name: "IoIosArrowDropdown" ,library:"io" },
{ icon: IoIosArrowDropleftCircle, name: "IoIosArrowDropleftCircle" ,library:"io" },
{ icon: IoIosArrowDropleft, name: "IoIosArrowDropleft" ,library:"io" },
{ icon: IoIosArrowDroprightCircle, name: "IoIosArrowDroprightCircle" ,library:"io" },
{ icon: IoIosArrowDropright, name: "IoIosArrowDropright" ,library:"io" },
{ icon: IoIosArrowDropupCircle, name: "IoIosArrowDropupCircle" ,library:"io" },
{ icon: IoIosArrowDropup, name: "IoIosArrowDropup" ,library:"io" },
{ icon: IoIosArrowForward, name: "IoIosArrowForward" ,library:"io" },
{ icon: IoIosArrowRoundBack, name: "IoIosArrowRoundBack" ,library:"io" },
{ icon: IoIosArrowRoundDown, name: "IoIosArrowRoundDown" ,library:"io" },
{ icon: IoIosArrowRoundForward, name: "IoIosArrowRoundForward" ,library:"io" },
{ icon: IoIosArrowRoundUp, name: "IoIosArrowRoundUp" ,library:"io" },
{ icon: IoIosArrowUp, name: "IoIosArrowUp" ,library:"io" },
{ icon: IoIosAt, name: "IoIosAt" ,library:"io" },
{ icon: IoIosAttach, name: "IoIosAttach" ,library:"io" },
{ icon: IoIosBackspace, name: "IoIosBackspace" ,library:"io" },
{ icon: IoIosBarcode, name: "IoIosBarcode" ,library:"io" },
{ icon: IoIosBaseball, name: "IoIosBaseball" ,library:"io" },
{ icon: IoIosBasket, name: "IoIosBasket" ,library:"io" },
{ icon: IoIosBasketball, name: "IoIosBasketball" ,library:"io" },
{ icon: IoIosBatteryCharging, name: "IoIosBatteryCharging" ,library:"io" },
{ icon: IoIosBatteryDead, name: "IoIosBatteryDead" ,library:"io" },
{ icon: IoIosBatteryFull, name: "IoIosBatteryFull" ,library:"io" },
{ icon: IoIosBeaker, name: "IoIosBeaker" ,library:"io" },
{ icon: IoIosBed, name: "IoIosBed" ,library:"io" },
{ icon: IoIosBeer, name: "IoIosBeer" ,library:"io" },
{ icon: IoIosBicycle, name: "IoIosBicycle" ,library:"io" },
{ icon: IoIosBluetooth, name: "IoIosBluetooth" ,library:"io" },
{ icon: IoIosBoat, name: "IoIosBoat" ,library:"io" },
{ icon: IoIosBody, name: "IoIosBody" ,library:"io" },
{ icon: IoIosBonfire, name: "IoIosBonfire" ,library:"io" },
{ icon: IoIosBook, name: "IoIosBook" ,library:"io" },
{ icon: IoIosBookmark, name: "IoIosBookmark" ,library:"io" },
{ icon: IoIosBookmarks, name: "IoIosBookmarks" ,library:"io" },
{ icon: IoIosBowtie, name: "IoIosBowtie" ,library:"io" },
{ icon: IoIosBriefcase, name: "IoIosBriefcase" ,library:"io" },
{ icon: IoIosBrowsers, name: "IoIosBrowsers" ,library:"io" },
{ icon: IoIosBrush, name: "IoIosBrush" ,library:"io" },
{ icon: IoIosBug, name: "IoIosBug" ,library:"io" },
{ icon: IoIosBuild, name: "IoIosBuild" ,library:"io" },
{ icon: IoIosBulb, name: "IoIosBulb" ,library:"io" },
{ icon: IoIosBus, name: "IoIosBus" ,library:"io" },
{ icon: IoIosBusiness, name: "IoIosBusiness" ,library:"io" },
{ icon: IoIosCafe, name: "IoIosCafe" ,library:"io" },
{ icon: IoIosCalculator, name: "IoIosCalculator" ,library:"io" },
{ icon: IoIosCalendar, name: "IoIosCalendar" ,library:"io" },
{ icon: IoIosCall, name: "IoIosCall" ,library:"io" },
{ icon: IoIosCamera, name: "IoIosCamera" ,library:"io" },
{ icon: IoIosCar, name: "IoIosCar" ,library:"io" },
{ icon: IoIosCard, name: "IoIosCard" ,library:"io" },
{ icon: IoIosCart, name: "IoIosCart" ,library:"io" },
{ icon: IoIosCash, name: "IoIosCash" ,library:"io" },
{ icon: IoIosCellular, name: "IoIosCellular" ,library:"io" },
{ icon: IoIosChatboxes, name: "IoIosChatboxes" ,library:"io" },
{ icon: IoIosChatbubbles, name: "IoIosChatbubbles" ,library:"io" },
{ icon: IoIosCheckboxOutline, name: "IoIosCheckboxOutline" ,library:"io" },
{ icon: IoIosCheckbox, name: "IoIosCheckbox" ,library:"io" },
{ icon: IoIosCheckmarkCircleOutline, name: "IoIosCheckmarkCircleOutline" ,library:"io" },
{ icon: IoIosCheckmarkCircle, name: "IoIosCheckmarkCircle" ,library:"io" },
{ icon: IoIosCheckmark, name: "IoIosCheckmark" ,library:"io" },
{ icon: IoIosClipboard, name: "IoIosClipboard" ,library:"io" },
{ icon: IoIosClock, name: "IoIosClock" ,library:"io" },
{ icon: IoIosCloseCircleOutline, name: "IoIosCloseCircleOutline" ,library:"io" },
{ icon: IoIosCloseCircle, name: "IoIosCloseCircle" ,library:"io" },
{ icon: IoIosClose, name: "IoIosClose" ,library:"io" },
{ icon: IoIosCloudCircle, name: "IoIosCloudCircle" ,library:"io" },
{ icon: IoIosCloudDone, name: "IoIosCloudDone" ,library:"io" },
{ icon: IoIosCloudDownload, name: "IoIosCloudDownload" ,library:"io" },
{ icon: IoIosCloudOutline, name: "IoIosCloudOutline" ,library:"io" },
{ icon: IoIosCloudUpload, name: "IoIosCloudUpload" ,library:"io" },
{ icon: IoIosCloud, name: "IoIosCloud" ,library:"io" },
{ icon: IoIosCloudyNight, name: "IoIosCloudyNight" ,library:"io" },
{ icon: IoIosCloudy, name: "IoIosCloudy" ,library:"io" },
{ icon: IoIosCodeDownload, name: "IoIosCodeDownload" ,library:"io" },
{ icon: IoIosCodeWorking, name: "IoIosCodeWorking" ,library:"io" },
{ icon: IoIosCode, name: "IoIosCode" ,library:"io" },
{ icon: IoIosCog, name: "IoIosCog" ,library:"io" },
{ icon: IoIosColorFill, name: "IoIosColorFill" ,library:"io" },
{ icon: IoIosColorFilter, name: "IoIosColorFilter" ,library:"io" },
{ icon: IoIosColorPalette, name: "IoIosColorPalette" ,library:"io" },
{ icon: IoIosColorWand, name: "IoIosColorWand" ,library:"io" },
{ icon: IoIosCompass, name: "IoIosCompass" ,library:"io" },
{ icon: IoIosConstruct, name: "IoIosConstruct" ,library:"io" },
{ icon: IoIosContact, name: "IoIosContact" ,library:"io" },
{ icon: IoIosContacts, name: "IoIosContacts" ,library:"io" },
{ icon: IoIosContract, name: "IoIosContract" ,library:"io" },
{ icon: IoIosContrast, name: "IoIosContrast" ,library:"io" },
{ icon: IoIosCopy, name: "IoIosCopy" ,library:"io" },
{ icon: IoIosCreate, name: "IoIosCreate" ,library:"io" },
{ icon: IoIosCrop, name: "IoIosCrop" ,library:"io" },
{ icon: IoIosCube, name: "IoIosCube" ,library:"io" },
{ icon: IoIosCut, name: "IoIosCut" ,library:"io" },
{ icon: IoIosDesktop, name: "IoIosDesktop" ,library:"io" },
{ icon: IoIosDisc, name: "IoIosDisc" ,library:"io" },
{ icon: IoIosDocument, name: "IoIosDocument" ,library:"io" },
{ icon: IoIosDoneAll, name: "IoIosDoneAll" ,library:"io" },
{ icon: IoIosDownload, name: "IoIosDownload" ,library:"io" },
{ icon: IoIosEasel, name: "IoIosEasel" ,library:"io" },
{ icon: IoIosEgg, name: "IoIosEgg" ,library:"io" },
{ icon: IoIosExit, name: "IoIosExit" ,library:"io" },
{ icon: IoIosExpand, name: "IoIosExpand" ,library:"io" },
{ icon: IoIosEyeOff, name: "IoIosEyeOff" ,library:"io" },
{ icon: IoIosEye, name: "IoIosEye" ,library:"io" },
{ icon: IoIosFastforward, name: "IoIosFastforward" ,library:"io" },
{ icon: IoIosFemale, name: "IoIosFemale" ,library:"io" },
{ icon: IoIosFiling, name: "IoIosFiling" ,library:"io" },
{ icon: IoIosFilm, name: "IoIosFilm" ,library:"io" },
{ icon: IoIosFingerPrint, name: "IoIosFingerPrint" ,library:"io" },
{ icon: IoIosFitness, name: "IoIosFitness" ,library:"io" },
{ icon: IoIosFlag, name: "IoIosFlag" ,library:"io" },
{ icon: IoIosFlame, name: "IoIosFlame" ,library:"io" },
{ icon: IoIosFlashOff, name: "IoIosFlashOff" ,library:"io" },
{ icon: IoIosFlash, name: "IoIosFlash" ,library:"io" },
{ icon: IoIosFlashlight, name: "IoIosFlashlight" ,library:"io" },
{ icon: IoIosFlask, name: "IoIosFlask" ,library:"io" },
{ icon: IoIosFlower, name: "IoIosFlower" ,library:"io" },
{ icon: IoIosFolderOpen, name: "IoIosFolderOpen" ,library:"io" },
{ icon: IoIosFolder, name: "IoIosFolder" ,library:"io" },
{ icon: IoIosFootball, name: "IoIosFootball" ,library:"io" },
{ icon: IoIosFunnel, name: "IoIosFunnel" ,library:"io" },
{ icon: IoIosGift, name: "IoIosGift" ,library:"io" },
{ icon: IoIosGitBranch, name: "IoIosGitBranch" ,library:"io" },
{ icon: IoIosGitCommit, name: "IoIosGitCommit" ,library:"io" },
{ icon: IoIosGitCompare, name: "IoIosGitCompare" ,library:"io" },
{ icon: IoIosGitMerge, name: "IoIosGitMerge" ,library:"io" },
{ icon: IoIosGitNetwork, name: "IoIosGitNetwork" ,library:"io" },
{ icon: IoIosGitPullRequest, name: "IoIosGitPullRequest" ,library:"io" },
{ icon: IoIosGlasses, name: "IoIosGlasses" ,library:"io" },
{ icon: IoIosGlobe, name: "IoIosGlobe" ,library:"io" },
{ icon: IoIosGrid, name: "IoIosGrid" ,library:"io" },
{ icon: IoIosHammer, name: "IoIosHammer" ,library:"io" },
{ icon: IoIosHand, name: "IoIosHand" ,library:"io" },
{ icon: IoIosHappy, name: "IoIosHappy" ,library:"io" },
{ icon: IoIosHeadset, name: "IoIosHeadset" ,library:"io" },
{ icon: IoIosHeartDislike, name: "IoIosHeartDislike" ,library:"io" },
{ icon: IoIosHeartEmpty, name: "IoIosHeartEmpty" ,library:"io" },
{ icon: IoIosHeartHalf, name: "IoIosHeartHalf" ,library:"io" },
{ icon: IoIosHeart, name: "IoIosHeart" ,library:"io" },
{ icon: IoIosHelpBuoy, name: "IoIosHelpBuoy" ,library:"io" },
{ icon: IoIosHelpCircleOutline, name: "IoIosHelpCircleOutline" ,library:"io" },
{ icon: IoIosHelpCircle, name: "IoIosHelpCircle" ,library:"io" },
{ icon: IoIosHelp, name: "IoIosHelp" ,library:"io" },
{ icon: IoIosHome, name: "IoIosHome" ,library:"io" },
{ icon: IoIosHourglass, name: "IoIosHourglass" ,library:"io" },
{ icon: IoIosIceCream, name: "IoIosIceCream" ,library:"io" },
{ icon: IoIosImage, name: "IoIosImage" ,library:"io" },
{ icon: IoIosImages, name: "IoIosImages" ,library:"io" },
{ icon: IoIosInfinite, name: "IoIosInfinite" ,library:"io" },
{ icon: IoIosInformationCircleOutline, name: "IoIosInformationCircleOutline" ,library:"io" },
{ icon: IoIosInformationCircle, name: "IoIosInformationCircle" ,library:"io" },
{ icon: IoIosInformation, name: "IoIosInformation" ,library:"io" },
{ icon: IoIosJet, name: "IoIosJet" ,library:"io" },
{ icon: IoIosJournal, name: "IoIosJournal" ,library:"io" },
{ icon: IoIosKey, name: "IoIosKey" ,library:"io" },
{ icon: IoIosKeypad, name: "IoIosKeypad" ,library:"io" },
{ icon: IoIosLaptop, name: "IoIosLaptop" ,library:"io" },
{ icon: IoIosLeaf, name: "IoIosLeaf" ,library:"io" },
{ icon: IoIosLink, name: "IoIosLink" ,library:"io" },
{ icon: IoIosListBox, name: "IoIosListBox" ,library:"io" },
{ icon: IoIosList, name: "IoIosList" ,library:"io" },
{ icon: IoIosLocate, name: "IoIosLocate" ,library:"io" },
{ icon: IoIosLock, name: "IoIosLock" ,library:"io" },
{ icon: IoIosLogIn, name: "IoIosLogIn" ,library:"io" },
{ icon: IoIosLogOut, name: "IoIosLogOut" ,library:"io" },
{ icon: IoIosMagnet, name: "IoIosMagnet" ,library:"io" },
{ icon: IoIosMailOpen, name: "IoIosMailOpen" ,library:"io" },
{ icon: IoIosMailUnread, name: "IoIosMailUnread" ,library:"io" },
{ icon: IoIosMail, name: "IoIosMail" ,library:"io" },
{ icon: IoIosMale, name: "IoIosMale" ,library:"io" },
{ icon: IoIosMan, name: "IoIosMan" ,library:"io" },
{ icon: IoIosMap, name: "IoIosMap" ,library:"io" },
{ icon: IoIosMedal, name: "IoIosMedal" ,library:"io" },
{ icon: IoIosMedical, name: "IoIosMedical" ,library:"io" },
{ icon: IoIosMedkit, name: "IoIosMedkit" ,library:"io" },
{ icon: IoIosMegaphone, name: "IoIosMegaphone" ,library:"io" },
{ icon: IoIosMenu, name: "IoIosMenu" ,library:"io" },
{ icon: IoIosMicOff, name: "IoIosMicOff" ,library:"io" },
{ icon: IoIosMic, name: "IoIosMic" ,library:"io" },
{ icon: IoIosMicrophone, name: "IoIosMicrophone" ,library:"io" },
{ icon: IoIosMoon, name: "IoIosMoon" ,library:"io" },
{ icon: IoIosMore, name: "IoIosMore" ,library:"io" },
{ icon: IoIosMove, name: "IoIosMove" ,library:"io" },
{ icon: IoIosMusicalNote, name: "IoIosMusicalNote" ,library:"io" },
{ icon: IoIosMusicalNotes, name: "IoIosMusicalNotes" ,library:"io" },
{ icon: IoIosNavigate, name: "IoIosNavigate" ,library:"io" },
{ icon: IoIosNotificationsOff, name: "IoIosNotificationsOff" ,library:"io" },
{ icon: IoIosNotificationsOutline, name: "IoIosNotificationsOutline" ,library:"io" },
{ icon: IoIosNotifications, name: "IoIosNotifications" ,library:"io" },
{ icon: IoIosNuclear, name: "IoIosNuclear" ,library:"io" },
{ icon: IoIosNutrition, name: "IoIosNutrition" ,library:"io" },
{ icon: IoIosOpen, name: "IoIosOpen" ,library:"io" },
{ icon: IoIosOptions, name: "IoIosOptions" ,library:"io" },
{ icon: IoIosOutlet, name: "IoIosOutlet" ,library:"io" },
{ icon: IoIosPaperPlane, name: "IoIosPaperPlane" ,library:"io" },
{ icon: IoIosPaper, name: "IoIosPaper" ,library:"io" },
{ icon: IoIosPartlySunny, name: "IoIosPartlySunny" ,library:"io" },
{ icon: IoIosPause, name: "IoIosPause" ,library:"io" },
{ icon: IoIosPaw, name: "IoIosPaw" ,library:"io" },
{ icon: IoIosPeople, name: "IoIosPeople" ,library:"io" },
{ icon: IoIosPersonAdd, name: "IoIosPersonAdd" ,library:"io" },
{ icon: IoIosPerson, name: "IoIosPerson" ,library:"io" },
{ icon: IoIosPhoneLandscape, name: "IoIosPhoneLandscape" ,library:"io" },
{ icon: IoIosPhonePortrait, name: "IoIosPhonePortrait" ,library:"io" },
{ icon: IoIosPhotos, name: "IoIosPhotos" ,library:"io" },
{ icon: IoIosPie, name: "IoIosPie" ,library:"io" },
{ icon: IoIosPin, name: "IoIosPin" ,library:"io" },
{ icon: IoIosPint, name: "IoIosPint" ,library:"io" },
{ icon: IoIosPizza, name: "IoIosPizza" ,library:"io" },
{ icon: IoIosPlanet, name: "IoIosPlanet" ,library:"io" },
{ icon: IoIosPlayCircle, name: "IoIosPlayCircle" ,library:"io" },
{ icon: IoIosPlay, name: "IoIosPlay" ,library:"io" },
{ icon: IoIosPodium, name: "IoIosPodium" ,library:"io" },
{ icon: IoIosPower, name: "IoIosPower" ,library:"io" },
{ icon: IoIosPricetag, name: "IoIosPricetag" ,library:"io" },
{ icon: IoIosPricetags, name: "IoIosPricetags" ,library:"io" },
{ icon: IoIosPrint, name: "IoIosPrint" ,library:"io" },
{ icon: IoIosPulse, name: "IoIosPulse" ,library:"io" },
{ icon: IoIosQrScanner, name: "IoIosQrScanner" ,library:"io" },
{ icon: IoIosQuote, name: "IoIosQuote" ,library:"io" },
{ icon: IoIosRadioButtonOff, name: "IoIosRadioButtonOff" ,library:"io" },
{ icon: IoIosRadioButtonOn, name: "IoIosRadioButtonOn" ,library:"io" },
{ icon: IoIosRadio, name: "IoIosRadio" ,library:"io" },
{ icon: IoIosRainy, name: "IoIosRainy" ,library:"io" },
{ icon: IoIosRecording, name: "IoIosRecording" ,library:"io" },
{ icon: IoIosRedo, name: "IoIosRedo" ,library:"io" },
{ icon: IoIosRefreshCircle, name: "IoIosRefreshCircle" ,library:"io" },
{ icon: IoIosRefresh, name: "IoIosRefresh" ,library:"io" },
{ icon: IoIosRemoveCircleOutline, name: "IoIosRemoveCircleOutline" ,library:"io" },
{ icon: IoIosRemoveCircle, name: "IoIosRemoveCircle" ,library:"io" },
{ icon: IoIosRemove, name: "IoIosRemove" ,library:"io" },
{ icon: IoIosReorder, name: "IoIosReorder" ,library:"io" },
{ icon: IoIosRepeat, name: "IoIosRepeat" ,library:"io" },
{ icon: IoIosResize, name: "IoIosResize" ,library:"io" },
{ icon: IoIosRestaurant, name: "IoIosRestaurant" ,library:"io" },
{ icon: IoIosReturnLeft, name: "IoIosReturnLeft" ,library:"io" },
{ icon: IoIosReturnRight, name: "IoIosReturnRight" ,library:"io" },
{ icon: IoIosReverseCamera, name: "IoIosReverseCamera" ,library:"io" },
{ icon: IoIosRewind, name: "IoIosRewind" ,library:"io" },
{ icon: IoIosRibbon, name: "IoIosRibbon" ,library:"io" },
{ icon: IoIosRocket, name: "IoIosRocket" ,library:"io" },
{ icon: IoIosRose, name: "IoIosRose" ,library:"io" },
{ icon: IoIosSad, name: "IoIosSad" ,library:"io" },
{ icon: IoIosSave, name: "IoIosSave" ,library:"io" },
{ icon: IoIosSchool, name: "IoIosSchool" ,library:"io" },
{ icon: IoIosSearch, name: "IoIosSearch" ,library:"io" },
{ icon: IoIosSend, name: "IoIosSend" ,library:"io" },
{ icon: IoIosSettings, name: "IoIosSettings" ,library:"io" },
{ icon: IoIosShareAlt, name: "IoIosShareAlt" ,library:"io" },
{ icon: IoIosShare, name: "IoIosShare" ,library:"io" },
{ icon: IoIosShirt, name: "IoIosShirt" ,library:"io" },
{ icon: IoIosShuffle, name: "IoIosShuffle" ,library:"io" },
{ icon: IoIosSkipBackward, name: "IoIosSkipBackward" ,library:"io" },
{ icon: IoIosSkipForward, name: "IoIosSkipForward" ,library:"io" },
{ icon: IoIosSnow, name: "IoIosSnow" ,library:"io" },
{ icon: IoIosSpeedometer, name: "IoIosSpeedometer" ,library:"io" },
{ icon: IoIosSquareOutline, name: "IoIosSquareOutline" ,library:"io" },
{ icon: IoIosSquare, name: "IoIosSquare" ,library:"io" },
{ icon: IoIosStarHalf, name: "IoIosStarHalf" ,library:"io" },
{ icon: IoIosStarOutline, name: "IoIosStarOutline" ,library:"io" },
{ icon: IoIosStar, name: "IoIosStar" ,library:"io" },
{ icon: IoIosStats, name: "IoIosStats" ,library:"io" },
{ icon: IoIosStopwatch, name: "IoIosStopwatch" ,library:"io" },
{ icon: IoIosSubway, name: "IoIosSubway" ,library:"io" },
{ icon: IoIosSunny, name: "IoIosSunny" ,library:"io" },
{ icon: IoIosSwap, name: "IoIosSwap" ,library:"io" },
{ icon: IoIosSwitch, name: "IoIosSwitch" ,library:"io" },
{ icon: IoIosSync, name: "IoIosSync" ,library:"io" },
{ icon: IoIosTabletLandscape, name: "IoIosTabletLandscape" ,library:"io" },
{ icon: IoIosTabletPortrait, name: "IoIosTabletPortrait" ,library:"io" },
{ icon: IoIosTennisball, name: "IoIosTennisball" ,library:"io" },
{ icon: IoIosText, name: "IoIosText" ,library:"io" },
{ icon: IoIosThermometer, name: "IoIosThermometer" ,library:"io" },
{ icon: IoIosThumbsDown, name: "IoIosThumbsDown" ,library:"io" },
{ icon: IoIosThumbsUp, name: "IoIosThumbsUp" ,library:"io" },
{ icon: IoIosThunderstorm, name: "IoIosThunderstorm" ,library:"io" },
{ icon: IoIosTime, name: "IoIosTime" ,library:"io" },
{ icon: IoIosTimer, name: "IoIosTimer" ,library:"io" },
{ icon: IoIosToday, name: "IoIosToday" ,library:"io" },
{ icon: IoIosTrain, name: "IoIosTrain" ,library:"io" },
{ icon: IoIosTransgender, name: "IoIosTransgender" ,library:"io" },
{ icon: IoIosTrash, name: "IoIosTrash" ,library:"io" },
{ icon: IoIosTrendingDown, name: "IoIosTrendingDown" ,library:"io" },
{ icon: IoIosTrendingUp, name: "IoIosTrendingUp" ,library:"io" },
{ icon: IoIosTrophy, name: "IoIosTrophy" ,library:"io" },
{ icon: IoIosTv, name: "IoIosTv" ,library:"io" },
{ icon: IoIosUmbrella, name: "IoIosUmbrella" ,library:"io" },
{ icon: IoIosUndo, name: "IoIosUndo" ,library:"io" },
{ icon: IoIosUnlock, name: "IoIosUnlock" ,library:"io" },
{ icon: IoIosVideocam, name: "IoIosVideocam" ,library:"io" },
{ icon: IoIosVolumeHigh, name: "IoIosVolumeHigh" ,library:"io" },
{ icon: IoIosVolumeLow, name: "IoIosVolumeLow" ,library:"io" },
{ icon: IoIosVolumeMute, name: "IoIosVolumeMute" ,library:"io" },
{ icon: IoIosVolumeOff, name: "IoIosVolumeOff" ,library:"io" },
{ icon: IoIosWalk, name: "IoIosWalk" ,library:"io" },
{ icon: IoIosWallet, name: "IoIosWallet" ,library:"io" },
{ icon: IoIosWarning, name: "IoIosWarning" ,library:"io" },
{ icon: IoIosWatch, name: "IoIosWatch" ,library:"io" },
{ icon: IoIosWater, name: "IoIosWater" ,library:"io" },
{ icon: IoIosWifi, name: "IoIosWifi" ,library:"io" },
{ icon: IoIosWine, name: "IoIosWine" ,library:"io" },
{ icon: IoIosWoman, name: "IoIosWoman" ,library:"io" },
{ icon: IoLogoAndroid, name: "IoLogoAndroid" ,library:"io" },
{ icon: IoLogoAngular, name: "IoLogoAngular" ,library:"io" },
{ icon: IoLogoApple, name: "IoLogoApple" ,library:"io" },
{ icon: IoLogoBitbucket, name: "IoLogoBitbucket" ,library:"io" },
{ icon: IoLogoBitcoin, name: "IoLogoBitcoin" ,library:"io" },
{ icon: IoLogoBuffer, name: "IoLogoBuffer" ,library:"io" },
{ icon: IoLogoChrome, name: "IoLogoChrome" ,library:"io" },
{ icon: IoLogoClosedCaptioning, name: "IoLogoClosedCaptioning" ,library:"io" },
{ icon: IoLogoCodepen, name: "IoLogoCodepen" ,library:"io" },
{ icon: IoLogoCss3, name: "IoLogoCss3" ,library:"io" },
{ icon: IoLogoDesignernews, name: "IoLogoDesignernews" ,library:"io" },
{ icon: IoLogoDribbble, name: "IoLogoDribbble" ,library:"io" },
{ icon: IoLogoDropbox, name: "IoLogoDropbox" ,library:"io" },
{ icon: IoLogoEuro, name: "IoLogoEuro" ,library:"io" },
{ icon: IoLogoFacebook, name: "IoLogoFacebook" ,library:"io" },
{ icon: IoLogoFlickr, name: "IoLogoFlickr" ,library:"io" },
{ icon: IoLogoFoursquare, name: "IoLogoFoursquare" ,library:"io" },
{ icon: IoLogoFreebsdDevil, name: "IoLogoFreebsdDevil" ,library:"io" },
{ icon: IoLogoGameControllerA, name: "IoLogoGameControllerA" ,library:"io" },
{ icon: IoLogoGameControllerB, name: "IoLogoGameControllerB" ,library:"io" },
{ icon: IoLogoGithub, name: "IoLogoGithub" ,library:"io" },
{ icon: IoLogoGoogle, name: "IoLogoGoogle" ,library:"io" },
{ icon: IoLogoGoogleplus, name: "IoLogoGoogleplus" ,library:"io" },
{ icon: IoLogoHackernews, name: "IoLogoHackernews" ,library:"io" },
{ icon: IoLogoHtml5, name: "IoLogoHtml5" ,library:"io" },
{ icon: IoLogoInstagram, name: "IoLogoInstagram" ,library:"io" },
{ icon: IoLogoIonic, name: "IoLogoIonic" ,library:"io" },
{ icon: IoLogoIonitron, name: "IoLogoIonitron" ,library:"io" },
{ icon: IoLogoJavascript, name: "IoLogoJavascript" ,library:"io" },
{ icon: IoLogoLinkedin, name: "IoLogoLinkedin" ,library:"io" },
{ icon: IoLogoMarkdown, name: "IoLogoMarkdown" ,library:"io" },
{ icon: IoLogoModelS, name: "IoLogoModelS" ,library:"io" },
{ icon: IoLogoNoSmoking, name: "IoLogoNoSmoking" ,library:"io" },
{ icon: IoLogoNodejs, name: "IoLogoNodejs" ,library:"io" },
{ icon: IoLogoNpm, name: "IoLogoNpm" ,library:"io" },
{ icon: IoLogoOctocat, name: "IoLogoOctocat" ,library:"io" },
{ icon: IoLogoPinterest, name: "IoLogoPinterest" ,library:"io" },
{ icon: IoLogoPlaystation, name: "IoLogoPlaystation" ,library:"io" },
{ icon: IoLogoPolymer, name: "IoLogoPolymer" ,library:"io" },
{ icon: IoLogoPython, name: "IoLogoPython" ,library:"io" },
{ icon: IoLogoReddit, name: "IoLogoReddit" ,library:"io" },
{ icon: IoLogoRss, name: "IoLogoRss" ,library:"io" },
{ icon: IoLogoSass, name: "IoLogoSass" ,library:"io" },
{ icon: IoLogoSkype, name: "IoLogoSkype" ,library:"io" },
{ icon: IoLogoSlack, name: "IoLogoSlack" ,library:"io" },
{ icon: IoLogoSnapchat, name: "IoLogoSnapchat" ,library:"io" },
{ icon: IoLogoSteam, name: "IoLogoSteam" ,library:"io" },
{ icon: IoLogoTumblr, name: "IoLogoTumblr" ,library:"io" },
{ icon: IoLogoTux, name: "IoLogoTux" ,library:"io" },
{ icon: IoLogoTwitch, name: "IoLogoTwitch" ,library:"io" },
{ icon: IoLogoTwitter, name: "IoLogoTwitter" ,library:"io" },
{ icon: IoLogoUsd, name: "IoLogoUsd" ,library:"io" },
{ icon: IoLogoVimeo, name: "IoLogoVimeo" ,library:"io" },
{ icon: IoLogoVk, name: "IoLogoVk" ,library:"io" },
{ icon: IoLogoWhatsapp, name: "IoLogoWhatsapp" ,library:"io" },
{ icon: IoLogoWindows, name: "IoLogoWindows" ,library:"io" },
{ icon: IoLogoWordpress, name: "IoLogoWordpress" ,library:"io" },
{ icon: IoLogoXbox, name: "IoLogoXbox" ,library:"io" },
{ icon: IoLogoXing, name: "IoLogoXing" ,library:"io" },
{ icon: IoLogoYahoo, name: "IoLogoYahoo" ,library:"io" },
{ icon: IoLogoYen, name: "IoLogoYen" ,library:"io" },
{ icon: IoLogoYoutube, name: "IoLogoYoutube" ,library:"io" },
{ icon: IoMdAddCircleOutline, name: "IoMdAddCircleOutline" ,library:"io" },
{ icon: IoMdAddCircle, name: "IoMdAddCircle" ,library:"io" },
{ icon: IoMdAdd, name: "IoMdAdd" ,library:"io" },
{ icon: IoMdAirplane, name: "IoMdAirplane" ,library:"io" },
{ icon: IoMdAlarm, name: "IoMdAlarm" ,library:"io" },
{ icon: IoMdAlbums, name: "IoMdAlbums" ,library:"io" },
{ icon: IoMdAlert, name: "IoMdAlert" ,library:"io" },
{ icon: IoMdAmericanFootball, name: "IoMdAmericanFootball" ,library:"io" },
{ icon: IoMdAnalytics, name: "IoMdAnalytics" ,library:"io" },
{ icon: IoMdAperture, name: "IoMdAperture" ,library:"io" },
{ icon: IoMdApps, name: "IoMdApps" ,library:"io" },
{ icon: IoMdAppstore, name: "IoMdAppstore" ,library:"io" },
{ icon: IoMdArchive, name: "IoMdArchive" ,library:"io" },
{ icon: IoMdArrowBack, name: "IoMdArrowBack" ,library:"io" },
{ icon: IoMdArrowDown, name: "IoMdArrowDown" ,library:"io" },
{ icon: IoMdArrowDropdownCircle, name: "IoMdArrowDropdownCircle" ,library:"io" },
{ icon: IoMdArrowDropdown, name: "IoMdArrowDropdown" ,library:"io" },
{ icon: IoMdArrowDropleftCircle, name: "IoMdArrowDropleftCircle" ,library:"io" },
{ icon: IoMdArrowDropleft, name: "IoMdArrowDropleft" ,library:"io" },
{ icon: IoMdArrowDroprightCircle, name: "IoMdArrowDroprightCircle" ,library:"io" },
{ icon: IoMdArrowDropright, name: "IoMdArrowDropright" ,library:"io" },
{ icon: IoMdArrowDropupCircle, name: "IoMdArrowDropupCircle" ,library:"io" },
{ icon: IoMdArrowDropup, name: "IoMdArrowDropup" ,library:"io" },
{ icon: IoMdArrowForward, name: "IoMdArrowForward" ,library:"io" },
{ icon: IoMdArrowRoundBack, name: "IoMdArrowRoundBack" ,library:"io" },
{ icon: IoMdArrowRoundDown, name: "IoMdArrowRoundDown" ,library:"io" },
{ icon: IoMdArrowRoundForward, name: "IoMdArrowRoundForward" ,library:"io" },
{ icon: IoMdArrowRoundUp, name: "IoMdArrowRoundUp" ,library:"io" },
{ icon: IoMdArrowUp, name: "IoMdArrowUp" ,library:"io" },
{ icon: IoMdAt, name: "IoMdAt" ,library:"io" },
{ icon: IoMdAttach, name: "IoMdAttach" ,library:"io" },
{ icon: IoMdBackspace, name: "IoMdBackspace" ,library:"io" },
{ icon: IoMdBarcode, name: "IoMdBarcode" ,library:"io" },
{ icon: IoMdBaseball, name: "IoMdBaseball" ,library:"io" },
{ icon: IoMdBasket, name: "IoMdBasket" ,library:"io" },
{ icon: IoMdBasketball, name: "IoMdBasketball" ,library:"io" },
{ icon: IoMdBatteryCharging, name: "IoMdBatteryCharging" ,library:"io" },
{ icon: IoMdBatteryDead, name: "IoMdBatteryDead" ,library:"io" },
{ icon: IoMdBatteryFull, name: "IoMdBatteryFull" ,library:"io" },
{ icon: IoMdBeaker, name: "IoMdBeaker" ,library:"io" },
{ icon: IoMdBed, name: "IoMdBed" ,library:"io" },
{ icon: IoMdBeer, name: "IoMdBeer" ,library:"io" },
{ icon: IoMdBicycle, name: "IoMdBicycle" ,library:"io" },
{ icon: IoMdBluetooth, name: "IoMdBluetooth" ,library:"io" },
{ icon: IoMdBoat, name: "IoMdBoat" ,library:"io" },
{ icon: IoMdBody, name: "IoMdBody" ,library:"io" },
{ icon: IoMdBonfire, name: "IoMdBonfire" ,library:"io" },
{ icon: IoMdBook, name: "IoMdBook" ,library:"io" },
{ icon: IoMdBookmark, name: "IoMdBookmark" ,library:"io" },
{ icon: IoMdBookmarks, name: "IoMdBookmarks" ,library:"io" },
{ icon: IoMdBowtie, name: "IoMdBowtie" ,library:"io" },
{ icon: IoMdBriefcase, name: "IoMdBriefcase" ,library:"io" },
{ icon: IoMdBrowsers, name: "IoMdBrowsers" ,library:"io" },
{ icon: IoMdBrush, name: "IoMdBrush" ,library:"io" },
{ icon: IoMdBug, name: "IoMdBug" ,library:"io" },
{ icon: IoMdBuild, name: "IoMdBuild" ,library:"io" },
{ icon: IoMdBulb, name: "IoMdBulb" ,library:"io" },
{ icon: IoMdBus, name: "IoMdBus" ,library:"io" },
{ icon: IoMdBusiness, name: "IoMdBusiness" ,library:"io" },
{ icon: IoMdCafe, name: "IoMdCafe" ,library:"io" },
{ icon: IoMdCalculator, name: "IoMdCalculator" ,library:"io" },
{ icon: IoMdCalendar, name: "IoMdCalendar" ,library:"io" },
{ icon: IoMdCall, name: "IoMdCall" ,library:"io" },
{ icon: IoMdCamera, name: "IoMdCamera" ,library:"io" },
{ icon: IoMdCar, name: "IoMdCar" ,library:"io" },
{ icon: IoMdCard, name: "IoMdCard" ,library:"io" },
{ icon: IoMdCart, name: "IoMdCart" ,library:"io" },
{ icon: IoMdCash, name: "IoMdCash" ,library:"io" },
{ icon: IoMdCellular, name: "IoMdCellular" ,library:"io" },
{ icon: IoMdChatboxes, name: "IoMdChatboxes" ,library:"io" },
{ icon: IoMdChatbubbles, name: "IoMdChatbubbles" ,library:"io" },
{ icon: IoMdCheckboxOutline, name: "IoMdCheckboxOutline" ,library:"io" },
{ icon: IoMdCheckbox, name: "IoMdCheckbox" ,library:"io" },
{ icon: IoMdCheckmarkCircleOutline, name: "IoMdCheckmarkCircleOutline" ,library:"io" },
{ icon: IoMdCheckmarkCircle, name: "IoMdCheckmarkCircle" ,library:"io" },
{ icon: IoMdCheckmark, name: "IoMdCheckmark" ,library:"io" },
{ icon: IoMdClipboard, name: "IoMdClipboard" ,library:"io" },
{ icon: IoMdClock, name: "IoMdClock" ,library:"io" },
{ icon: IoMdCloseCircleOutline, name: "IoMdCloseCircleOutline" ,library:"io" },
{ icon: IoMdCloseCircle, name: "IoMdCloseCircle" ,library:"io" },
{ icon: IoMdClose, name: "IoMdClose" ,library:"io" },
{ icon: IoMdCloudCircle, name: "IoMdCloudCircle" ,library:"io" },
{ icon: IoMdCloudDone, name: "IoMdCloudDone" ,library:"io" },
{ icon: IoMdCloudDownload, name: "IoMdCloudDownload" ,library:"io" },
{ icon: IoMdCloudOutline, name: "IoMdCloudOutline" ,library:"io" },
{ icon: IoMdCloudUpload, name: "IoMdCloudUpload" ,library:"io" },
{ icon: IoMdCloud, name: "IoMdCloud" ,library:"io" },
{ icon: IoMdCloudyNight, name: "IoMdCloudyNight" ,library:"io" },
{ icon: IoMdCloudy, name: "IoMdCloudy" ,library:"io" },
{ icon: IoMdCodeDownload, name: "IoMdCodeDownload" ,library:"io" },
{ icon: IoMdCodeWorking, name: "IoMdCodeWorking" ,library:"io" },
{ icon: IoMdCode, name: "IoMdCode" ,library:"io" },
{ icon: IoMdCog, name: "IoMdCog" ,library:"io" },
{ icon: IoMdColorFill, name: "IoMdColorFill" ,library:"io" },
{ icon: IoMdColorFilter, name: "IoMdColorFilter" ,library:"io" },
{ icon: IoMdColorPalette, name: "IoMdColorPalette" ,library:"io" },
{ icon: IoMdColorWand, name: "IoMdColorWand" ,library:"io" },
{ icon: IoMdCompass, name: "IoMdCompass" ,library:"io" },
{ icon: IoMdConstruct, name: "IoMdConstruct" ,library:"io" },
{ icon: IoMdContact, name: "IoMdContact" ,library:"io" },
{ icon: IoMdContacts, name: "IoMdContacts" ,library:"io" },
{ icon: IoMdContract, name: "IoMdContract" ,library:"io" },
{ icon: IoMdContrast, name: "IoMdContrast" ,library:"io" },
{ icon: IoMdCopy, name: "IoMdCopy" ,library:"io" },
{ icon: IoMdCreate, name: "IoMdCreate" ,library:"io" },
{ icon: IoMdCrop, name: "IoMdCrop" ,library:"io" },
{ icon: IoMdCube, name: "IoMdCube" ,library:"io" },
{ icon: IoMdCut, name: "IoMdCut" ,library:"io" },
{ icon: IoMdDesktop, name: "IoMdDesktop" ,library:"io" },
{ icon: IoMdDisc, name: "IoMdDisc" ,library:"io" },
{ icon: IoMdDocument, name: "IoMdDocument" ,library:"io" },
{ icon: IoMdDoneAll, name: "IoMdDoneAll" ,library:"io" },
{ icon: IoMdDownload, name: "IoMdDownload" ,library:"io" },
{ icon: IoMdEasel, name: "IoMdEasel" ,library:"io" },
{ icon: IoMdEgg, name: "IoMdEgg" ,library:"io" },
{ icon: IoMdExit, name: "IoMdExit" ,library:"io" },
{ icon: IoMdExpand, name: "IoMdExpand" ,library:"io" },
{ icon: IoMdEyeOff, name: "IoMdEyeOff" ,library:"io" },
{ icon: IoMdEye, name: "IoMdEye" ,library:"io" },
{ icon: IoMdFastforward, name: "IoMdFastforward" ,library:"io" },
{ icon: IoMdFemale, name: "IoMdFemale" ,library:"io" },
{ icon: IoMdFiling, name: "IoMdFiling" ,library:"io" },
{ icon: IoMdFilm, name: "IoMdFilm" ,library:"io" },
{ icon: IoMdFingerPrint, name: "IoMdFingerPrint" ,library:"io" },
{ icon: IoMdFitness, name: "IoMdFitness" ,library:"io" },
{ icon: IoMdFlag, name: "IoMdFlag" ,library:"io" },
{ icon: IoMdFlame, name: "IoMdFlame" ,library:"io" },
{ icon: IoMdFlashOff, name: "IoMdFlashOff" ,library:"io" },
{ icon: IoMdFlash, name: "IoMdFlash" ,library:"io" },
{ icon: IoMdFlashlight, name: "IoMdFlashlight" ,library:"io" },
{ icon: IoMdFlask, name: "IoMdFlask" ,library:"io" },
{ icon: IoMdFlower, name: "IoMdFlower" ,library:"io" },
{ icon: IoMdFolderOpen, name: "IoMdFolderOpen" ,library:"io" },
{ icon: IoMdFolder, name: "IoMdFolder" ,library:"io" },
{ icon: IoMdFootball, name: "IoMdFootball" ,library:"io" },
{ icon: IoMdFunnel, name: "IoMdFunnel" ,library:"io" },
{ icon: IoMdGift, name: "IoMdGift" ,library:"io" },
{ icon: IoMdGitBranch, name: "IoMdGitBranch" ,library:"io" },
{ icon: IoMdGitCommit, name: "IoMdGitCommit" ,library:"io" },
{ icon: IoMdGitCompare, name: "IoMdGitCompare" ,library:"io" },
{ icon: IoMdGitMerge, name: "IoMdGitMerge" ,library:"io" },
{ icon: IoMdGitNetwork, name: "IoMdGitNetwork" ,library:"io" },
{ icon: IoMdGitPullRequest, name: "IoMdGitPullRequest" ,library:"io" },
{ icon: IoMdGlasses, name: "IoMdGlasses" ,library:"io" },
{ icon: IoMdGlobe, name: "IoMdGlobe" ,library:"io" },
{ icon: IoMdGrid, name: "IoMdGrid" ,library:"io" },
{ icon: IoMdHammer, name: "IoMdHammer" ,library:"io" },
{ icon: IoMdHand, name: "IoMdHand" ,library:"io" },
{ icon: IoMdHappy, name: "IoMdHappy" ,library:"io" },
{ icon: IoMdHeadset, name: "IoMdHeadset" ,library:"io" },
{ icon: IoMdHeartDislike, name: "IoMdHeartDislike" ,library:"io" },
{ icon: IoMdHeartEmpty, name: "IoMdHeartEmpty" ,library:"io" },
{ icon: IoMdHeartHalf, name: "IoMdHeartHalf" ,library:"io" },
{ icon: IoMdHeart, name: "IoMdHeart" ,library:"io" },
{ icon: IoMdHelpBuoy, name: "IoMdHelpBuoy" ,library:"io" },
{ icon: IoMdHelpCircleOutline, name: "IoMdHelpCircleOutline" ,library:"io" },
{ icon: IoMdHelpCircle, name: "IoMdHelpCircle" ,library:"io" },
{ icon: IoMdHelp, name: "IoMdHelp" ,library:"io" },
{ icon: IoMdHome, name: "IoMdHome" ,library:"io" },
{ icon: IoMdHourglass, name: "IoMdHourglass" ,library:"io" },
{ icon: IoMdIceCream, name: "IoMdIceCream" ,library:"io" },
{ icon: IoMdImage, name: "IoMdImage" ,library:"io" },
{ icon: IoMdImages, name: "IoMdImages" ,library:"io" },
{ icon: IoMdInfinite, name: "IoMdInfinite" ,library:"io" },
{ icon: IoMdInformationCircleOutline, name: "IoMdInformationCircleOutline" ,library:"io" },
{ icon: IoMdInformationCircle, name: "IoMdInformationCircle" ,library:"io" },
{ icon: IoMdInformation, name: "IoMdInformation" ,library:"io" },
{ icon: IoMdJet, name: "IoMdJet" ,library:"io" },
{ icon: IoMdJournal, name: "IoMdJournal" ,library:"io" },
{ icon: IoMdKey, name: "IoMdKey" ,library:"io" },
{ icon: IoMdKeypad, name: "IoMdKeypad" ,library:"io" },
{ icon: IoMdLaptop, name: "IoMdLaptop" ,library:"io" },
{ icon: IoMdLeaf, name: "IoMdLeaf" ,library:"io" },
{ icon: IoMdLink, name: "IoMdLink" ,library:"io" },
{ icon: IoMdListBox, name: "IoMdListBox" ,library:"io" },
{ icon: IoMdList, name: "IoMdList" ,library:"io" },
{ icon: IoMdLocate, name: "IoMdLocate" ,library:"io" },
{ icon: IoMdLock, name: "IoMdLock" ,library:"io" },
{ icon: IoMdLogIn, name: "IoMdLogIn" ,library:"io" },
{ icon: IoMdLogOut, name: "IoMdLogOut" ,library:"io" },
{ icon: IoMdMagnet, name: "IoMdMagnet" ,library:"io" },
{ icon: IoMdMailOpen, name: "IoMdMailOpen" ,library:"io" },
{ icon: IoMdMailUnread, name: "IoMdMailUnread" ,library:"io" },
{ icon: IoMdMail, name: "IoMdMail" ,library:"io" },
{ icon: IoMdMale, name: "IoMdMale" ,library:"io" },
{ icon: IoMdMan, name: "IoMdMan" ,library:"io" },
{ icon: IoMdMap, name: "IoMdMap" ,library:"io" },
{ icon: IoMdMedal, name: "IoMdMedal" ,library:"io" },
{ icon: IoMdMedical, name: "IoMdMedical" ,library:"io" },
{ icon: IoMdMedkit, name: "IoMdMedkit" ,library:"io" },
{ icon: IoMdMegaphone, name: "IoMdMegaphone" ,library:"io" },
{ icon: IoMdMenu, name: "IoMdMenu" ,library:"io" },
{ icon: IoMdMicOff, name: "IoMdMicOff" ,library:"io" },
{ icon: IoMdMic, name: "IoMdMic" ,library:"io" },
{ icon: IoMdMicrophone, name: "IoMdMicrophone" ,library:"io" },
{ icon: IoMdMoon, name: "IoMdMoon" ,library:"io" },
{ icon: IoMdMore, name: "IoMdMore" ,library:"io" },
{ icon: IoMdMove, name: "IoMdMove" ,library:"io" },
{ icon: IoMdMusicalNote, name: "IoMdMusicalNote" ,library:"io" },
{ icon: IoMdMusicalNotes, name: "IoMdMusicalNotes" ,library:"io" },
{ icon: IoMdNavigate, name: "IoMdNavigate" ,library:"io" },
{ icon: IoMdNotificationsOff, name: "IoMdNotificationsOff" ,library:"io" },
{ icon: IoMdNotificationsOutline, name: "IoMdNotificationsOutline" ,library:"io" },
{ icon: IoMdNotifications, name: "IoMdNotifications" ,library:"io" },
{ icon: IoMdNuclear, name: "IoMdNuclear" ,library:"io" },
{ icon: IoMdNutrition, name: "IoMdNutrition" ,library:"io" },
{ icon: IoMdOpen, name: "IoMdOpen" ,library:"io" },
{ icon: IoMdOptions, name: "IoMdOptions" ,library:"io" },
{ icon: IoMdOutlet, name: "IoMdOutlet" ,library:"io" },
{ icon: IoMdPaperPlane, name: "IoMdPaperPlane" ,library:"io" },
{ icon: IoMdPaper, name: "IoMdPaper" ,library:"io" },
{ icon: IoMdPartlySunny, name: "IoMdPartlySunny" ,library:"io" },
{ icon: IoMdPause, name: "IoMdPause" ,library:"io" },
{ icon: IoMdPaw, name: "IoMdPaw" ,library:"io" },
{ icon: IoMdPeople, name: "IoMdPeople" ,library:"io" },
{ icon: IoMdPersonAdd, name: "IoMdPersonAdd" ,library:"io" },
{ icon: IoMdPerson, name: "IoMdPerson" ,library:"io" },
{ icon: IoMdPhoneLandscape, name: "IoMdPhoneLandscape" ,library:"io" },
{ icon: IoMdPhonePortrait, name: "IoMdPhonePortrait" ,library:"io" },
{ icon: IoMdPhotos, name: "IoMdPhotos" ,library:"io" },
{ icon: IoMdPie, name: "IoMdPie" ,library:"io" },
{ icon: IoMdPin, name: "IoMdPin" ,library:"io" },
{ icon: IoMdPint, name: "IoMdPint" ,library:"io" },
{ icon: IoMdPizza, name: "IoMdPizza" ,library:"io" },
{ icon: IoMdPlanet, name: "IoMdPlanet" ,library:"io" },
{ icon: IoMdPlayCircle, name: "IoMdPlayCircle" ,library:"io" },
{ icon: IoMdPlay, name: "IoMdPlay" ,library:"io" },
{ icon: IoMdPodium, name: "IoMdPodium" ,library:"io" },
{ icon: IoMdPower, name: "IoMdPower" ,library:"io" },
{ icon: IoMdPricetag, name: "IoMdPricetag" ,library:"io" },
{ icon: IoMdPricetags, name: "IoMdPricetags" ,library:"io" },
{ icon: IoMdPrint, name: "IoMdPrint" ,library:"io" },
{ icon: IoMdPulse, name: "IoMdPulse" ,library:"io" },
{ icon: IoMdQrScanner, name: "IoMdQrScanner" ,library:"io" },
{ icon: IoMdQuote, name: "IoMdQuote" ,library:"io" },
{ icon: IoMdRadioButtonOff, name: "IoMdRadioButtonOff" ,library:"io" },
{ icon: IoMdRadioButtonOn, name: "IoMdRadioButtonOn" ,library:"io" },
{ icon: IoMdRadio, name: "IoMdRadio" ,library:"io" },
{ icon: IoMdRainy, name: "IoMdRainy" ,library:"io" },
{ icon: IoMdRecording, name: "IoMdRecording" ,library:"io" },
{ icon: IoMdRedo, name: "IoMdRedo" ,library:"io" },
{ icon: IoMdRefreshCircle, name: "IoMdRefreshCircle" ,library:"io" },
{ icon: IoMdRefresh, name: "IoMdRefresh" ,library:"io" },
{ icon: IoMdRemoveCircleOutline, name: "IoMdRemoveCircleOutline" ,library:"io" },
{ icon: IoMdRemoveCircle, name: "IoMdRemoveCircle" ,library:"io" },
{ icon: IoMdRemove, name: "IoMdRemove" ,library:"io" },
{ icon: IoMdReorder, name: "IoMdReorder" ,library:"io" },
{ icon: IoMdRepeat, name: "IoMdRepeat" ,library:"io" },
{ icon: IoMdResize, name: "IoMdResize" ,library:"io" },
{ icon: IoMdRestaurant, name: "IoMdRestaurant" ,library:"io" },
{ icon: IoMdReturnLeft, name: "IoMdReturnLeft" ,library:"io" },
{ icon: IoMdReturnRight, name: "IoMdReturnRight" ,library:"io" },
{ icon: IoMdReverseCamera, name: "IoMdReverseCamera" ,library:"io" },
{ icon: IoMdRewind, name: "IoMdRewind" ,library:"io" },
{ icon: IoMdRibbon, name: "IoMdRibbon" ,library:"io" },
{ icon: IoMdRocket, name: "IoMdRocket" ,library:"io" },
{ icon: IoMdRose, name: "IoMdRose" ,library:"io" },
{ icon: IoMdSad, name: "IoMdSad" ,library:"io" },
{ icon: IoMdSave, name: "IoMdSave" ,library:"io" },
{ icon: IoMdSchool, name: "IoMdSchool" ,library:"io" },
{ icon: IoMdSearch, name: "IoMdSearch" ,library:"io" },
{ icon: IoMdSend, name: "IoMdSend" ,library:"io" },
{ icon: IoMdSettings, name: "IoMdSettings" ,library:"io" },
{ icon: IoMdShareAlt, name: "IoMdShareAlt" ,library:"io" },
{ icon: IoMdShare, name: "IoMdShare" ,library:"io" },
{ icon: IoMdShirt, name: "IoMdShirt" ,library:"io" },
{ icon: IoMdShuffle, name: "IoMdShuffle" ,library:"io" },
{ icon: IoMdSkipBackward, name: "IoMdSkipBackward" ,library:"io" },
{ icon: IoMdSkipForward, name: "IoMdSkipForward" ,library:"io" },
{ icon: IoMdSnow, name: "IoMdSnow" ,library:"io" },
{ icon: IoMdSpeedometer, name: "IoMdSpeedometer" ,library:"io" },
{ icon: IoMdSquareOutline, name: "IoMdSquareOutline" ,library:"io" },
{ icon: IoMdSquare, name: "IoMdSquare" ,library:"io" },
{ icon: IoMdStarHalf, name: "IoMdStarHalf" ,library:"io" },
{ icon: IoMdStarOutline, name: "IoMdStarOutline" ,library:"io" },
{ icon: IoMdStar, name: "IoMdStar" ,library:"io" },
{ icon: IoMdStats, name: "IoMdStats" ,library:"io" },
{ icon: IoMdStopwatch, name: "IoMdStopwatch" ,library:"io" },
{ icon: IoMdSubway, name: "IoMdSubway" ,library:"io" },
{ icon: IoMdSunny, name: "IoMdSunny" ,library:"io" },
{ icon: IoMdSwap, name: "IoMdSwap" ,library:"io" },
{ icon: IoMdSwitch, name: "IoMdSwitch" ,library:"io" },
{ icon: IoMdSync, name: "IoMdSync" ,library:"io" },
{ icon: IoMdTabletLandscape, name: "IoMdTabletLandscape" ,library:"io" },
{ icon: IoMdTabletPortrait, name: "IoMdTabletPortrait" ,library:"io" },
{ icon: IoMdTennisball, name: "IoMdTennisball" ,library:"io" },
{ icon: IoMdText, name: "IoMdText" ,library:"io" },
{ icon: IoMdThermometer, name: "IoMdThermometer" ,library:"io" },
{ icon: IoMdThumbsDown, name: "IoMdThumbsDown" ,library:"io" },
{ icon: IoMdThumbsUp, name: "IoMdThumbsUp" ,library:"io" },
{ icon: IoMdThunderstorm, name: "IoMdThunderstorm" ,library:"io" },
{ icon: IoMdTime, name: "IoMdTime" ,library:"io" },
{ icon: IoMdTimer, name: "IoMdTimer" ,library:"io" },
{ icon: IoMdToday, name: "IoMdToday" ,library:"io" },
{ icon: IoMdTrain, name: "IoMdTrain" ,library:"io" },
{ icon: IoMdTransgender, name: "IoMdTransgender" ,library:"io" },
{ icon: IoMdTrash, name: "IoMdTrash" ,library:"io" },
{ icon: IoMdTrendingDown, name: "IoMdTrendingDown" ,library:"io" },
{ icon: IoMdTrendingUp, name: "IoMdTrendingUp" ,library:"io" },
{ icon: IoMdTrophy, name: "IoMdTrophy" ,library:"io" },
{ icon: IoMdTv, name: "IoMdTv" ,library:"io" },
{ icon: IoMdUmbrella, name: "IoMdUmbrella" ,library:"io" },
{ icon: IoMdUndo, name: "IoMdUndo" ,library:"io" },
{ icon: IoMdUnlock, name: "IoMdUnlock" ,library:"io" },
{ icon: IoMdVideocam, name: "IoMdVideocam" ,library:"io" },
{ icon: IoMdVolumeHigh, name: "IoMdVolumeHigh" ,library:"io" },
{ icon: IoMdVolumeLow, name: "IoMdVolumeLow" ,library:"io" },
{ icon: IoMdVolumeMute, name: "IoMdVolumeMute" ,library:"io" },
{ icon: IoMdVolumeOff, name: "IoMdVolumeOff" ,library:"io" },
{ icon: IoMdWalk, name: "IoMdWalk" ,library:"io" },
{ icon: IoMdWallet, name: "IoMdWallet" ,library:"io" },
{ icon: IoMdWarning, name: "IoMdWarning" ,library:"io" },
{ icon: IoMdWatch, name: "IoMdWatch" ,library:"io" },
{ icon: IoMdWater, name: "IoMdWater" ,library:"io" },
{ icon: IoMdWifi, name: "IoMdWifi" ,library:"io" },
{ icon: IoMdWine, name: "IoMdWine" ,library:"io" },
{ icon: IoMdWoman, name: "IoMdWoman" ,library:"io" },
];

export default result