import {
	GrAccessibility,
	GrAchievement,
	GrAction,
	GrActions,
	GrAd,
	GrAddCircle,
	GrAdd,
	GrAed,
	GrAggregate,
	GrAidOption,
	GrAid,
	GrAlarm,
	GrAlert,
	GrAmazon,
	GrAmex,
	GrAnalytics,
	GrAnchor,
	GrAndroid,
	GrAnnounce,
	GrAppleAppStore,
	GrApple,
	GrAppsRounded,
	GrApps,
	GrArchive,
	GrArchlinux,
	GrArticle,
	GrAruba,
	GrAscend,
	GrAscending,
	GrAssistListening,
	GrAtm,
	GrAttachment,
	GrAttraction,
	GrBaby,
	GrBackTen,
	GrBarChart,
	GrBar,
	GrBasket,
	GrBeacon,
	GrBike,
	GrBitcoin,
	GrBladesHorizontal,
	GrBladesVertical,
	GrBlockQuote,
	GrBlog,
	GrBluetooth,
	GrBold,
	GrBook,
	GrBookmark,
	GrBottomCorner,
	GrBraille,
	GrBriefcase,
	GrBrush,
	GrBug,
	GrBundle,
	GrBus,
	GrBusinessService,
	GrCafeteria,
	GrCalculator,
	GrCalendar,
	GrCamera,
	GrCapacity,
	GrCar,
	GrCaretDownFill,
	GrCaretDown,
	GrCaretLeftFill,
	GrCaretNext,
	GrCaretPrevious,
	GrCaretRightFill,
	GrCaretUpFill,
	GrCaretUp,
	GrCart,
	GrCatalogOption,
	GrCatalog,
	GrCentos,
	GrCertificate,
	GrChannel,
	GrChapterAdd,
	GrChapterNext,
	GrChapterPrevious,
	GrChatOption,
	GrChat,
	GrCheckboxSelected,
	GrCheckbox,
	GrCheckmark,
	GrChrome,
	GrCircleAlert,
	GrCircleInformation,
	GrCirclePlay,
	GrCircleQuestion,
	GrClearOption,
	GrClear,
	GrCli,
	GrClipboard,
	GrClock,
	GrClone,
	GrClose,
	GrClosedCaption,
	GrCloudComputer,
	GrCloudDownload,
	GrCloudSoftware,
	GrCloudUpload,
	GrCloud,
	GrCloudlinux,
	GrCluster,
	GrCoatCheck,
	GrCodeSandbox,
	GrCode,
	GrCodepen,
	GrCoffee,
	GrColumns,
	GrCommand,
	GrCompare,
	GrCompass,
	GrCompliance,
	GrConfigure,
	GrConnect,
	GrConnectivity,
	GrConsole,
	GrContactInfo,
	GrContact,
	GrContract,
	GrCopy,
	GrCpu,
	GrCreativeCommons,
	GrCreditCard,
	GrCss3,
	GrCube,
	GrCubes,
	GrCurrency,
	GrCursor,
	GrCut,
	GrCycle,
	GrDashboard,
	GrDatabase,
	GrDebian,
	GrDeliver,
	GrDeploy,
	GrDescend,
	GrDescending,
	GrDesktop,
	GrDetach,
	GrDevice,
	GrDiamond,
	GrDirections,
	GrDisabledOutline,
	GrDisc,
	GrDislike,
	GrDocker,
	GrDocumentCloud,
	GrDocumentConfig,
	GrDocumentCsv,
	GrDocumentDownload,
	GrDocumentExcel,
	GrDocumentImage,
	GrDocumentLocked,
	GrDocumentMissing,
	GrDocumentNotes,
	GrDocumentOutlook,
	GrDocumentPdf,
	GrDocumentPerformance,
	GrDocumentPpt,
	GrDocumentRtf,
	GrDocumentSound,
	GrDocumentStore,
	GrDocumentTest,
	GrDocumentText,
	GrDocumentThreat,
	GrDocumentTime,
	GrDocumentTransfer,
	GrDocumentTxt,
	GrDocumentUpdate,
	GrDocumentUpload,
	GrDocumentUser,
	GrDocumentVerified,
	GrDocumentVideo,
	GrDocumentWindows,
	GrDocumentWord,
	GrDocumentZip,
	GrDocument,
	GrDomain,
	GrDos,
	GrDown,
	GrDownloadOption,
	GrDownload,
	GrDrag,
	GrDrawer,
	GrDribbble,
	GrDriveCage,
	GrDropbox,
	GrDuplicate,
	GrDxc,
	GrEbay,
	GrEdge,
	GrEdit,
	GrEject,
	GrElevator,
	GrEmergency,
	GrEmoji,
	GrEmptyCircle,
	GrErase,
	GrEscalator,
	GrExpand,
	GrEzmeral,
	GrFacebookOption,
	GrFacebook,
	GrFanOption,
	GrFan,
	GrFastForward,
	GrFavorite,
	GrFedora,
	GrFigma,
	GrFilter,
	GrFingerPrint,
	GrFireball,
	GrFirefox,
	GrFirewall,
	GrFlagFill,
	GrFlag,
	GrFlows,
	GrFolderCycle,
	GrFolderOpen,
	GrFolder,
	GrFormAdd,
	GrFormAttachment,
	GrFormCalendar,
	GrFormCheckmark,
	GrFormClock,
	GrFormClose,
	GrFormCut,
	GrFormDown,
	GrFormEdit,
	GrFormFilter,
	GrFormFolder,
	GrFormLocation,
	GrFormLock,
	GrFormNextLink,
	GrFormNext,
	GrFormPreviousLink,
	GrFormPrevious,
	GrFormRefresh,
	GrFormSchedule,
	GrFormSearch,
	GrFormSubtract,
	GrFormTrash,
	GrFormUp,
	GrFormUpload,
	GrFormViewHide,
	GrFormView,
	GrForwardTen,
	GrFreebsd,
	GrGallery,
	GrGamepad,
	GrGateway,
	GrGatsbyjs,
	GrGem,
	GrGift,
	GrGithub,
	GrGlobe,
	GrGolang,
	GrGooglePlay,
	GrGooglePlus,
	GrGoogleWallet,
	GrGoogle,
	GrGraphQl,
	GrGremlin,
	GrGrid,
	GrGrommet,
	GrGroup,
	GrGrow,
	GrHadoop,
	GrHalt,
	GrHelpOption,
	GrHelp,
	GrHeroku,
	GrHide,
	GrHistory,
	GrHomeOption,
	GrHomeRounded,
	GrHome,
	GrHorton,
	GrHostMaintenance,
	GrHost,
	GrHp,
	GrHpeLabs,
	GrHpe,
	GrHpi,
	GrHtml5,
	GrIceCream,
	GrImage,
	GrImpact,
	GrInProgress,
	GrInbox,
	GrIndicator,
	GrInfo,
	GrInherit,
	GrInsecure,
	GrInspect,
	GrInstagram,
	GrInstallOption,
	GrInstall,
	GrIntegration,
	GrInternetExplorer,
	GrItalic,
	GrIteration,
	GrJava,
	GrJs,
	GrKey,
	GrKeyboard,
	GrLanguage,
	GrLastfm,
	GrLaunch,
	GrLayer,
	GrLicense,
	GrLike,
	GrLineChart,
	GrLinkBottom,
	GrLinkDown,
	GrLinkNext,
	GrLinkPrevious,
	GrLinkTop,
	GrLinkUp,
	GrLink,
	GrLinkedinOption,
	GrLinkedin,
	GrList,
	GrLocal,
	GrLocationPin,
	GrLocation,
	GrLock,
	GrLogin,
	GrLogout,
	GrLounge,
	GrMagic,
	GrMailOption,
	GrMail,
	GrMandriva,
	GrManual,
	GrMapLocation,
	GrMap,
	GrMastercard,
	GrMedium,
	GrMemory,
	GrMenu,
	GrMicrofocus,
	GrMicrophone,
	GrMoney,
	GrMonitor,
	GrMonospace,
	GrMoon,
	GrMoreVertical,
	GrMore,
	GrMouse,
	GrMultimedia,
	GrMultiple,
	GrMusic,
	GrMysql,
	GrNavigate,
	GrNetworkDrive,
	GrNetwork,
	GrNewWindow,
	GrNew,
	GrNext,
	GrNode,
	GrNodes,
	GrNorton,
	GrNote,
	GrNotes,
	GrNotification,
	GrNpm,
	GrObjectGroup,
	GrObjectUngroup,
	GrOfflineStorage,
	GrOnedrive,
	GrOpera,
	GrOptimize,
	GrOracle,
	GrOrderedList,
	GrOrganization,
	GrOverview,
	GrPackage,
	GrPaint,
	GrPan,
	GrPauseFill,
	GrPause,
	GrPaypal,
	GrPerformance,
	GrPersonalComputer,
	GrPhoneFlip,
	GrPhoneHorizontal,
	GrPhoneVertical,
	GrPhone,
	GrPieChart,
	GrPiedPiper,
	GrPin,
	GrPinterest,
	GrPlan,
	GrPlayFill,
	GrPlay,
	GrPlug,
	GrPocket,
	GrPowerCycle,
	GrPowerForceShutdown,
	GrPowerReset,
	GrPowerShutdown,
	GrPower,
	GrPrevious,
	GrPrint,
	GrProductHunt,
	GrProjects,
	GrQr,
	GrRadialSelected,
	GrRadial,
	GrRaspberry,
	GrReactjs,
	GrReddit,
	GrRedhat,
	GrRedo,
	GrRefresh,
	GrResources,
	GrRestaurant,
	GrRestroomMen,
	GrRestroomWomen,
	GrRestroom,
	GrResume,
	GrReturn,
	GrRevert,
	GrRewind,
	GrRisk,
	GrRobot,
	GrRotateLeft,
	GrRotateRight,
	GrRss,
	GrRun,
	GrSafariOption,
	GrSans,
	GrSatellite,
	GrSave,
	GrScan,
	GrScheduleNew,
	GrSchedulePlay,
	GrSchedule,
	GrSchedules,
	GrSco,
	GrScorecard,
	GrScript,
	GrSd,
	GrSearchAdvanced,
	GrSearch,
	GrSecure,
	GrSelect,
	GrSelection,
	GrSemantics,
	GrSend,
	GrServerCluster,
	GrServer,
	GrServers,
	GrServicePlay,
	GrServices,
	GrSettingsOption,
	GrShareOption,
	GrShareRounded,
	GrShare,
	GrShieldSecurity,
	GrShield,
	GrShift,
	GrShop,
	GrSidebar,
	GrSign,
	GrSkype,
	GrSlack,
	GrSnapchat,
	GrSolaris,
	GrSort,
	GrSoundcloud,
	GrSpa,
	GrSpectrum,
	GrSplit,
	GrSplits,
	GrSpotify,
	GrSquare,
	GrStackOverflow,
	GrStakeholder,
	GrStarHalf,
	GrStar,
	GrStatusCriticalSmall,
	GrStatusCritical,
	GrStatusDisabledSmall,
	GrStatusDisabled,
	GrStatusGoodSmall,
	GrStatusGood,
	GrStatusInfoSmall,
	GrStatusInfo,
	GrStatusPlaceholderSmall,
	GrStatusPlaceholder,
	GrStatusUnknownSmall,
	GrStatusUnknown,
	GrStatusWarningSmall,
	GrStatusWarning,
	GrStepsOption,
	GrSteps,
	GrStopFill,
	GrStop,
	GrStorage,
	GrStreetView,
	GrStrikeThrough,
	GrStripe,
	GrSubscript,
	GrSubtractCircle,
	GrSubtract,
	GrSun,
	GrSuperscript,
	GrSupport,
	GrSuse,
	GrSwift,
	GrSwim,
	GrSwitch,
	GrSync,
	GrSystem,
	GrTableAdd,
	GrTable,
	GrTag,
	GrTapeOption,
	GrTape,
	GrTarget,
	GrTask,
	GrTasks,
	GrTechnology,
	GrTemplate,
	GrTerminal,
	GrTestDesktop,
	GrTest,
	GrTextAlignCenter,
	GrTextAlignFull,
	GrTextAlignLeft,
	GrTextAlignRight,
	GrTextWrap,
	GrThreats,
	GrThreeDEffects,
	GrThreeD,
	GrTicket,
	GrTictok,
	GrTime,
	GrTip,
	GrToast,
	GrTools,
	GrTooltip,
	GrTopCorner,
	GrTrain,
	GrTransaction,
	GrTrash,
	GrTreeOption,
	GrTree,
	GrTrigger,
	GrTrophy,
	GrTroubleshoot,
	GrTty,
	GrTumblr,
	GrTurbolinux,
	GrTwitter,
	GrUbuntu,
	GrUnderline,
	GrUndo,
	GrUnlink,
	GrUnlock,
	GrUnorderedList,
	GrUnsorted,
	GrUp,
	GrUpdate,
	GrUpgrade,
	GrUploadOption,
	GrUpload,
	GrUsbKey,
	GrUserAdd,
	GrUserAdmin,
	GrUserExpert,
	GrUserFemale,
	GrUserManager,
	GrUserNew,
	GrUserPolice,
	GrUserSettings,
	GrUserWorker,
	GrUser,
	GrValidate,
	GrVend,
	GrVideo,
	GrView,
	GrVimeo,
	GrVirtualMachine,
	GrVirtualStorage,
	GrVisa,
	GrVmMaintenance,
	GrVmware,
	GrVolumeControl,
	GrVolumeLow,
	GrVolumeMute,
	GrVolume,
	GrVulnerability,
	GrWaypoint,
	GrWebcam,
	GrWheelchairActive,
	GrWheelchair,
	GrWifiLow,
	GrWifiMedium,
	GrWifiNone,
	GrWifi,
	GrWindowsLegacy,
	GrWindows,
	GrWordpress,
	GrWorkshop,
	GrYoga,
	GrYoutube,
	GrZoomIn,
	GrZoomOut,
	GrZoom,
} from "react-icons/gr";

const result = [
	{ icon: GrAccessibility, name: "GrAccessibility", library: "gr" },
	{ icon: GrAchievement, name: "GrAchievement", library: "gr" },
	{ icon: GrAction, name: "GrAction", library: "gr" },
	{ icon: GrActions, name: "GrActions", library: "gr" },
	{ icon: GrAd, name: "GrAd", library: "gr" },
	{ icon: GrAddCircle, name: "GrAddCircle", library: "gr" },
	{ icon: GrAdd, name: "GrAdd", library: "gr" },
	{ icon: GrAed, name: "GrAed", library: "gr" },
	{ icon: GrAggregate, name: "GrAggregate", library: "gr" },
	{ icon: GrAidOption, name: "GrAidOption", library: "gr" },
	{ icon: GrAid, name: "GrAid", library: "gr" },
	{ icon: GrAlarm, name: "GrAlarm", library: "gr" },
	{ icon: GrAlert, name: "GrAlert", library: "gr" },
	{ icon: GrAmazon, name: "GrAmazon", library: "gr" },
	{ icon: GrAmex, name: "GrAmex", library: "gr" },
	{ icon: GrAnalytics, name: "GrAnalytics", library: "gr" },
	{ icon: GrAnchor, name: "GrAnchor", library: "gr" },
	{ icon: GrAndroid, name: "GrAndroid", library: "gr" },
	{ icon: GrAnnounce, name: "GrAnnounce", library: "gr" },
	{ icon: GrAppleAppStore, name: "GrAppleAppStore", library: "gr" },
	{ icon: GrApple, name: "GrApple", library: "gr" },
	{ icon: GrAppsRounded, name: "GrAppsRounded", library: "gr" },
	{ icon: GrApps, name: "GrApps", library: "gr" },
	{ icon: GrArchive, name: "GrArchive", library: "gr" },
	{ icon: GrArchlinux, name: "GrArchlinux", library: "gr" },
	{ icon: GrArticle, name: "GrArticle", library: "gr" },
	{ icon: GrAruba, name: "GrAruba", library: "gr" },
	{ icon: GrAscend, name: "GrAscend", library: "gr" },
	{ icon: GrAscending, name: "GrAscending", library: "gr" },
	{ icon: GrAssistListening, name: "GrAssistListening", library: "gr" },
	{ icon: GrAtm, name: "GrAtm", library: "gr" },
	{ icon: GrAttachment, name: "GrAttachment", library: "gr" },
	{ icon: GrAttraction, name: "GrAttraction", library: "gr" },
	{ icon: GrBaby, name: "GrBaby", library: "gr" },
	{ icon: GrBackTen, name: "GrBackTen", library: "gr" },
	{ icon: GrBarChart, name: "GrBarChart", library: "gr" },
	{ icon: GrBar, name: "GrBar", library: "gr" },
	{ icon: GrBasket, name: "GrBasket", library: "gr" },
	{ icon: GrBeacon, name: "GrBeacon", library: "gr" },
	{ icon: GrBike, name: "GrBike", library: "gr" },
	{ icon: GrBitcoin, name: "GrBitcoin", library: "gr" },
	{ icon: GrBladesHorizontal, name: "GrBladesHorizontal", library: "gr" },
	{ icon: GrBladesVertical, name: "GrBladesVertical", library: "gr" },
	{ icon: GrBlockQuote, name: "GrBlockQuote", library: "gr" },
	{ icon: GrBlog, name: "GrBlog", library: "gr" },
	{ icon: GrBluetooth, name: "GrBluetooth", library: "gr" },
	{ icon: GrBold, name: "GrBold", library: "gr" },
	{ icon: GrBook, name: "GrBook", library: "gr" },
	{ icon: GrBookmark, name: "GrBookmark", library: "gr" },
	{ icon: GrBottomCorner, name: "GrBottomCorner", library: "gr" },
	{ icon: GrBraille, name: "GrBraille", library: "gr" },
	{ icon: GrBriefcase, name: "GrBriefcase", library: "gr" },
	{ icon: GrBrush, name: "GrBrush", library: "gr" },
	{ icon: GrBug, name: "GrBug", library: "gr" },
	{ icon: GrBundle, name: "GrBundle", library: "gr" },
	{ icon: GrBus, name: "GrBus", library: "gr" },
	{ icon: GrBusinessService, name: "GrBusinessService", library: "gr" },
	{ icon: GrCafeteria, name: "GrCafeteria", library: "gr" },
	{ icon: GrCalculator, name: "GrCalculator", library: "gr" },
	{ icon: GrCalendar, name: "GrCalendar", library: "gr" },
	{ icon: GrCamera, name: "GrCamera", library: "gr" },
	{ icon: GrCapacity, name: "GrCapacity", library: "gr" },
	{ icon: GrCar, name: "GrCar", library: "gr" },
	{ icon: GrCaretDownFill, name: "GrCaretDownFill", library: "gr" },
	{ icon: GrCaretDown, name: "GrCaretDown", library: "gr" },
	{ icon: GrCaretLeftFill, name: "GrCaretLeftFill", library: "gr" },
	{ icon: GrCaretNext, name: "GrCaretNext", library: "gr" },
	{ icon: GrCaretPrevious, name: "GrCaretPrevious", library: "gr" },
	{ icon: GrCaretRightFill, name: "GrCaretRightFill", library: "gr" },
	{ icon: GrCaretUpFill, name: "GrCaretUpFill", library: "gr" },
	{ icon: GrCaretUp, name: "GrCaretUp", library: "gr" },
	{ icon: GrCart, name: "GrCart", library: "gr" },
	{ icon: GrCatalogOption, name: "GrCatalogOption", library: "gr" },
	{ icon: GrCatalog, name: "GrCatalog", library: "gr" },
	{ icon: GrCentos, name: "GrCentos", library: "gr" },
	{ icon: GrCertificate, name: "GrCertificate", library: "gr" },
	{ icon: GrChannel, name: "GrChannel", library: "gr" },
	{ icon: GrChapterAdd, name: "GrChapterAdd", library: "gr" },
	{ icon: GrChapterNext, name: "GrChapterNext", library: "gr" },
	{ icon: GrChapterPrevious, name: "GrChapterPrevious", library: "gr" },
	{ icon: GrChatOption, name: "GrChatOption", library: "gr" },
	{ icon: GrChat, name: "GrChat", library: "gr" },
	{ icon: GrCheckboxSelected, name: "GrCheckboxSelected", library: "gr" },
	{ icon: GrCheckbox, name: "GrCheckbox", library: "gr" },
	{ icon: GrCheckmark, name: "GrCheckmark", library: "gr" },
	{ icon: GrChrome, name: "GrChrome", library: "gr" },
	{ icon: GrCircleAlert, name: "GrCircleAlert", library: "gr" },
	{ icon: GrCircleInformation, name: "GrCircleInformation", library: "gr" },
	{ icon: GrCirclePlay, name: "GrCirclePlay", library: "gr" },
	{ icon: GrCircleQuestion, name: "GrCircleQuestion", library: "gr" },
	{ icon: GrClearOption, name: "GrClearOption", library: "gr" },
	{ icon: GrClear, name: "GrClear", library: "gr" },
	{ icon: GrCli, name: "GrCli", library: "gr" },
	{ icon: GrClipboard, name: "GrClipboard", library: "gr" },
	{ icon: GrClock, name: "GrClock", library: "gr" },
	{ icon: GrClone, name: "GrClone", library: "gr" },
	{ icon: GrClose, name: "GrClose", library: "gr" },
	{ icon: GrClosedCaption, name: "GrClosedCaption", library: "gr" },
	{ icon: GrCloudComputer, name: "GrCloudComputer", library: "gr" },
	{ icon: GrCloudDownload, name: "GrCloudDownload", library: "gr" },
	{ icon: GrCloudSoftware, name: "GrCloudSoftware", library: "gr" },
	{ icon: GrCloudUpload, name: "GrCloudUpload", library: "gr" },
	{ icon: GrCloud, name: "GrCloud", library: "gr" },
	{ icon: GrCloudlinux, name: "GrCloudlinux", library: "gr" },
	{ icon: GrCluster, name: "GrCluster", library: "gr" },
	{ icon: GrCoatCheck, name: "GrCoatCheck", library: "gr" },
	{ icon: GrCodeSandbox, name: "GrCodeSandbox", library: "gr" },
	{ icon: GrCode, name: "GrCode", library: "gr" },
	{ icon: GrCodepen, name: "GrCodepen", library: "gr" },
	{ icon: GrCoffee, name: "GrCoffee", library: "gr" },
	{ icon: GrColumns, name: "GrColumns", library: "gr" },
	{ icon: GrCommand, name: "GrCommand", library: "gr" },
	{ icon: GrCompare, name: "GrCompare", library: "gr" },
	{ icon: GrCompass, name: "GrCompass", library: "gr" },
	{ icon: GrCompliance, name: "GrCompliance", library: "gr" },
	{ icon: GrConfigure, name: "GrConfigure", library: "gr" },
	{ icon: GrConnect, name: "GrConnect", library: "gr" },
	{ icon: GrConnectivity, name: "GrConnectivity", library: "gr" },
	{ icon: GrConsole, name: "GrConsole", library: "gr" },
	{ icon: GrContactInfo, name: "GrContactInfo", library: "gr" },
	{ icon: GrContact, name: "GrContact", library: "gr" },
	{ icon: GrContract, name: "GrContract", library: "gr" },
	{ icon: GrCopy, name: "GrCopy", library: "gr" },
	{ icon: GrCpu, name: "GrCpu", library: "gr" },
	{ icon: GrCreativeCommons, name: "GrCreativeCommons", library: "gr" },
	{ icon: GrCreditCard, name: "GrCreditCard", library: "gr" },
	{ icon: GrCss3, name: "GrCss3", library: "gr" },
	{ icon: GrCube, name: "GrCube", library: "gr" },
	{ icon: GrCubes, name: "GrCubes", library: "gr" },
	{ icon: GrCurrency, name: "GrCurrency", library: "gr" },
	{ icon: GrCursor, name: "GrCursor", library: "gr" },
	{ icon: GrCut, name: "GrCut", library: "gr" },
	{ icon: GrCycle, name: "GrCycle", library: "gr" },
	{ icon: GrDashboard, name: "GrDashboard", library: "gr" },
	{ icon: GrDatabase, name: "GrDatabase", library: "gr" },
	{ icon: GrDebian, name: "GrDebian", library: "gr" },
	{ icon: GrDeliver, name: "GrDeliver", library: "gr" },
	{ icon: GrDeploy, name: "GrDeploy", library: "gr" },
	{ icon: GrDescend, name: "GrDescend", library: "gr" },
	{ icon: GrDescending, name: "GrDescending", library: "gr" },
	{ icon: GrDesktop, name: "GrDesktop", library: "gr" },
	{ icon: GrDetach, name: "GrDetach", library: "gr" },
	{ icon: GrDevice, name: "GrDevice", library: "gr" },
	{ icon: GrDiamond, name: "GrDiamond", library: "gr" },
	{ icon: GrDirections, name: "GrDirections", library: "gr" },
	{ icon: GrDisabledOutline, name: "GrDisabledOutline", library: "gr" },
	{ icon: GrDisc, name: "GrDisc", library: "gr" },
	{ icon: GrDislike, name: "GrDislike", library: "gr" },
	{ icon: GrDocker, name: "GrDocker", library: "gr" },
	{ icon: GrDocumentCloud, name: "GrDocumentCloud", library: "gr" },
	{ icon: GrDocumentConfig, name: "GrDocumentConfig", library: "gr" },
	{ icon: GrDocumentCsv, name: "GrDocumentCsv", library: "gr" },
	{ icon: GrDocumentDownload, name: "GrDocumentDownload", library: "gr" },
	{ icon: GrDocumentExcel, name: "GrDocumentExcel", library: "gr" },
	{ icon: GrDocumentImage, name: "GrDocumentImage", library: "gr" },
	{ icon: GrDocumentLocked, name: "GrDocumentLocked", library: "gr" },
	{ icon: GrDocumentMissing, name: "GrDocumentMissing", library: "gr" },
	{ icon: GrDocumentNotes, name: "GrDocumentNotes", library: "gr" },
	{ icon: GrDocumentOutlook, name: "GrDocumentOutlook", library: "gr" },
	{ icon: GrDocumentPdf, name: "GrDocumentPdf", library: "gr" },
	{ icon: GrDocumentPerformance, name: "GrDocumentPerformance", library: "gr" },
	{ icon: GrDocumentPpt, name: "GrDocumentPpt", library: "gr" },
	{ icon: GrDocumentRtf, name: "GrDocumentRtf", library: "gr" },
	{ icon: GrDocumentSound, name: "GrDocumentSound", library: "gr" },
	{ icon: GrDocumentStore, name: "GrDocumentStore", library: "gr" },
	{ icon: GrDocumentTest, name: "GrDocumentTest", library: "gr" },
	{ icon: GrDocumentText, name: "GrDocumentText", library: "gr" },
	{ icon: GrDocumentThreat, name: "GrDocumentThreat", library: "gr" },
	{ icon: GrDocumentTime, name: "GrDocumentTime", library: "gr" },
	{ icon: GrDocumentTransfer, name: "GrDocumentTransfer", library: "gr" },
	{ icon: GrDocumentTxt, name: "GrDocumentTxt", library: "gr" },
	{ icon: GrDocumentUpdate, name: "GrDocumentUpdate", library: "gr" },
	{ icon: GrDocumentUpload, name: "GrDocumentUpload", library: "gr" },
	{ icon: GrDocumentUser, name: "GrDocumentUser", library: "gr" },
	{ icon: GrDocumentVerified, name: "GrDocumentVerified", library: "gr" },
	{ icon: GrDocumentVideo, name: "GrDocumentVideo", library: "gr" },
	{ icon: GrDocumentWindows, name: "GrDocumentWindows", library: "gr" },
	{ icon: GrDocumentWord, name: "GrDocumentWord", library: "gr" },
	{ icon: GrDocumentZip, name: "GrDocumentZip", library: "gr" },
	{ icon: GrDocument, name: "GrDocument", library: "gr" },
	{ icon: GrDomain, name: "GrDomain", library: "gr" },
	{ icon: GrDos, name: "GrDos", library: "gr" },
	{ icon: GrDown, name: "GrDown", library: "gr" },
	{ icon: GrDownloadOption, name: "GrDownloadOption", library: "gr" },
	{ icon: GrDownload, name: "GrDownload", library: "gr" },
	{ icon: GrDrag, name: "GrDrag", library: "gr" },
	{ icon: GrDrawer, name: "GrDrawer", library: "gr" },
	{ icon: GrDribbble, name: "GrDribbble", library: "gr" },
	{ icon: GrDriveCage, name: "GrDriveCage", library: "gr" },
	{ icon: GrDropbox, name: "GrDropbox", library: "gr" },
	{ icon: GrDuplicate, name: "GrDuplicate", library: "gr" },
	{ icon: GrDxc, name: "GrDxc", library: "gr" },
	{ icon: GrEbay, name: "GrEbay", library: "gr" },
	{ icon: GrEdge, name: "GrEdge", library: "gr" },
	{ icon: GrEdit, name: "GrEdit", library: "gr" },
	{ icon: GrEject, name: "GrEject", library: "gr" },
	{ icon: GrElevator, name: "GrElevator", library: "gr" },
	{ icon: GrEmergency, name: "GrEmergency", library: "gr" },
	{ icon: GrEmoji, name: "GrEmoji", library: "gr" },
	{ icon: GrEmptyCircle, name: "GrEmptyCircle", library: "gr" },
	{ icon: GrErase, name: "GrErase", library: "gr" },
	{ icon: GrEscalator, name: "GrEscalator", library: "gr" },
	{ icon: GrExpand, name: "GrExpand", library: "gr" },
	{ icon: GrEzmeral, name: "GrEzmeral", library: "gr" },
	{ icon: GrFacebookOption, name: "GrFacebookOption", library: "gr" },
	{ icon: GrFacebook, name: "GrFacebook", library: "gr" },
	{ icon: GrFanOption, name: "GrFanOption", library: "gr" },
	{ icon: GrFan, name: "GrFan", library: "gr" },
	{ icon: GrFastForward, name: "GrFastForward", library: "gr" },
	{ icon: GrFavorite, name: "GrFavorite", library: "gr" },
	{ icon: GrFedora, name: "GrFedora", library: "gr" },
	{ icon: GrFigma, name: "GrFigma", library: "gr" },
	{ icon: GrFilter, name: "GrFilter", library: "gr" },
	{ icon: GrFingerPrint, name: "GrFingerPrint", library: "gr" },
	{ icon: GrFireball, name: "GrFireball", library: "gr" },
	{ icon: GrFirefox, name: "GrFirefox", library: "gr" },
	{ icon: GrFirewall, name: "GrFirewall", library: "gr" },
	{ icon: GrFlagFill, name: "GrFlagFill", library: "gr" },
	{ icon: GrFlag, name: "GrFlag", library: "gr" },
	{ icon: GrFlows, name: "GrFlows", library: "gr" },
	{ icon: GrFolderCycle, name: "GrFolderCycle", library: "gr" },
	{ icon: GrFolderOpen, name: "GrFolderOpen", library: "gr" },
	{ icon: GrFolder, name: "GrFolder", library: "gr" },
	{ icon: GrFormAdd, name: "GrFormAdd", library: "gr" },
	{ icon: GrFormAttachment, name: "GrFormAttachment", library: "gr" },
	{ icon: GrFormCalendar, name: "GrFormCalendar", library: "gr" },
	{ icon: GrFormCheckmark, name: "GrFormCheckmark", library: "gr" },
	{ icon: GrFormClock, name: "GrFormClock", library: "gr" },
	{ icon: GrFormClose, name: "GrFormClose", library: "gr" },
	{ icon: GrFormCut, name: "GrFormCut", library: "gr" },
	{ icon: GrFormDown, name: "GrFormDown", library: "gr" },
	{ icon: GrFormEdit, name: "GrFormEdit", library: "gr" },
	{ icon: GrFormFilter, name: "GrFormFilter", library: "gr" },
	{ icon: GrFormFolder, name: "GrFormFolder", library: "gr" },
	{ icon: GrFormLocation, name: "GrFormLocation", library: "gr" },
	{ icon: GrFormLock, name: "GrFormLock", library: "gr" },
	{ icon: GrFormNextLink, name: "GrFormNextLink", library: "gr" },
	{ icon: GrFormNext, name: "GrFormNext", library: "gr" },
	{ icon: GrFormPreviousLink, name: "GrFormPreviousLink", library: "gr" },
	{ icon: GrFormPrevious, name: "GrFormPrevious", library: "gr" },
	{ icon: GrFormRefresh, name: "GrFormRefresh", library: "gr" },
	{ icon: GrFormSchedule, name: "GrFormSchedule", library: "gr" },
	{ icon: GrFormSearch, name: "GrFormSearch", library: "gr" },
	{ icon: GrFormSubtract, name: "GrFormSubtract", library: "gr" },
	{ icon: GrFormTrash, name: "GrFormTrash", library: "gr" },
	{ icon: GrFormUp, name: "GrFormUp", library: "gr" },
	{ icon: GrFormUpload, name: "GrFormUpload", library: "gr" },
	{ icon: GrFormViewHide, name: "GrFormViewHide", library: "gr" },
	{ icon: GrFormView, name: "GrFormView", library: "gr" },
	{ icon: GrForwardTen, name: "GrForwardTen", library: "gr" },
	{ icon: GrFreebsd, name: "GrFreebsd", library: "gr" },
	{ icon: GrGallery, name: "GrGallery", library: "gr" },
	{ icon: GrGamepad, name: "GrGamepad", library: "gr" },
	{ icon: GrGateway, name: "GrGateway", library: "gr" },
	{ icon: GrGatsbyjs, name: "GrGatsbyjs", library: "gr" },
	{ icon: GrGem, name: "GrGem", library: "gr" },
	{ icon: GrGift, name: "GrGift", library: "gr" },
	{ icon: GrGithub, name: "GrGithub", library: "gr" },
	{ icon: GrGlobe, name: "GrGlobe", library: "gr" },
	{ icon: GrGolang, name: "GrGolang", library: "gr" },
	{ icon: GrGooglePlay, name: "GrGooglePlay", library: "gr" },
	{ icon: GrGooglePlus, name: "GrGooglePlus", library: "gr" },
	{ icon: GrGoogleWallet, name: "GrGoogleWallet", library: "gr" },
	{ icon: GrGoogle, name: "GrGoogle", library: "gr" },
	{ icon: GrGraphQl, name: "GrGraphQl", library: "gr" },
	{ icon: GrGremlin, name: "GrGremlin", library: "gr" },
	{ icon: GrGrid, name: "GrGrid", library: "gr" },
	{ icon: GrGrommet, name: "GrGrommet", library: "gr" },
	{ icon: GrGroup, name: "GrGroup", library: "gr" },
	{ icon: GrGrow, name: "GrGrow", library: "gr" },
	{ icon: GrHadoop, name: "GrHadoop", library: "gr" },
	{ icon: GrHalt, name: "GrHalt", library: "gr" },
	{ icon: GrHelpOption, name: "GrHelpOption", library: "gr" },
	{ icon: GrHelp, name: "GrHelp", library: "gr" },
	{ icon: GrHeroku, name: "GrHeroku", library: "gr" },
	{ icon: GrHide, name: "GrHide", library: "gr" },
	{ icon: GrHistory, name: "GrHistory", library: "gr" },
	{ icon: GrHomeOption, name: "GrHomeOption", library: "gr" },
	{ icon: GrHomeRounded, name: "GrHomeRounded", library: "gr" },
	{ icon: GrHome, name: "GrHome", library: "gr" },
	{ icon: GrHorton, name: "GrHorton", library: "gr" },
	{ icon: GrHostMaintenance, name: "GrHostMaintenance", library: "gr" },
	{ icon: GrHost, name: "GrHost", library: "gr" },
	{ icon: GrHp, name: "GrHp", library: "gr" },
	{ icon: GrHpeLabs, name: "GrHpeLabs", library: "gr" },
	{ icon: GrHpe, name: "GrHpe", library: "gr" },
	{ icon: GrHpi, name: "GrHpi", library: "gr" },
	{ icon: GrHtml5, name: "GrHtml5", library: "gr" },
	{ icon: GrIceCream, name: "GrIceCream", library: "gr" },
	{ icon: GrImage, name: "GrImage", library: "gr" },
	{ icon: GrImpact, name: "GrImpact", library: "gr" },
	{ icon: GrInProgress, name: "GrInProgress", library: "gr" },
	{ icon: GrInbox, name: "GrInbox", library: "gr" },
	{ icon: GrIndicator, name: "GrIndicator", library: "gr" },
	{ icon: GrInfo, name: "GrInfo", library: "gr" },
	{ icon: GrInherit, name: "GrInherit", library: "gr" },
	{ icon: GrInsecure, name: "GrInsecure", library: "gr" },
	{ icon: GrInspect, name: "GrInspect", library: "gr" },
	{ icon: GrInstagram, name: "GrInstagram", library: "gr" },
	{ icon: GrInstallOption, name: "GrInstallOption", library: "gr" },
	{ icon: GrInstall, name: "GrInstall", library: "gr" },
	{ icon: GrIntegration, name: "GrIntegration", library: "gr" },
	{ icon: GrInternetExplorer, name: "GrInternetExplorer", library: "gr" },
	{ icon: GrItalic, name: "GrItalic", library: "gr" },
	{ icon: GrIteration, name: "GrIteration", library: "gr" },
	{ icon: GrJava, name: "GrJava", library: "gr" },
	{ icon: GrJs, name: "GrJs", library: "gr" },
	{ icon: GrKey, name: "GrKey", library: "gr" },
	{ icon: GrKeyboard, name: "GrKeyboard", library: "gr" },
	{ icon: GrLanguage, name: "GrLanguage", library: "gr" },
	{ icon: GrLastfm, name: "GrLastfm", library: "gr" },
	{ icon: GrLaunch, name: "GrLaunch", library: "gr" },
	{ icon: GrLayer, name: "GrLayer", library: "gr" },
	{ icon: GrLicense, name: "GrLicense", library: "gr" },
	{ icon: GrLike, name: "GrLike", library: "gr" },
	{ icon: GrLineChart, name: "GrLineChart", library: "gr" },
	{ icon: GrLinkBottom, name: "GrLinkBottom", library: "gr" },
	{ icon: GrLinkDown, name: "GrLinkDown", library: "gr" },
	{ icon: GrLinkNext, name: "GrLinkNext", library: "gr" },
	{ icon: GrLinkPrevious, name: "GrLinkPrevious", library: "gr" },
	{ icon: GrLinkTop, name: "GrLinkTop", library: "gr" },
	{ icon: GrLinkUp, name: "GrLinkUp", library: "gr" },
	{ icon: GrLink, name: "GrLink", library: "gr" },
	{ icon: GrLinkedinOption, name: "GrLinkedinOption", library: "gr" },
	{ icon: GrLinkedin, name: "GrLinkedin", library: "gr" },
	{ icon: GrList, name: "GrList", library: "gr" },
	{ icon: GrLocal, name: "GrLocal", library: "gr" },
	{ icon: GrLocationPin, name: "GrLocationPin", library: "gr" },
	{ icon: GrLocation, name: "GrLocation", library: "gr" },
	{ icon: GrLock, name: "GrLock", library: "gr" },
	{ icon: GrLogin, name: "GrLogin", library: "gr" },
	{ icon: GrLogout, name: "GrLogout", library: "gr" },
	{ icon: GrLounge, name: "GrLounge", library: "gr" },
	{ icon: GrMagic, name: "GrMagic", library: "gr" },
	{ icon: GrMailOption, name: "GrMailOption", library: "gr" },
	{ icon: GrMail, name: "GrMail", library: "gr" },
	{ icon: GrMandriva, name: "GrMandriva", library: "gr" },
	{ icon: GrManual, name: "GrManual", library: "gr" },
	{ icon: GrMapLocation, name: "GrMapLocation", library: "gr" },
	{ icon: GrMap, name: "GrMap", library: "gr" },
	{ icon: GrMastercard, name: "GrMastercard", library: "gr" },
	{ icon: GrMedium, name: "GrMedium", library: "gr" },
	{ icon: GrMemory, name: "GrMemory", library: "gr" },
	{ icon: GrMenu, name: "GrMenu", library: "gr" },
	{ icon: GrMicrofocus, name: "GrMicrofocus", library: "gr" },
	{ icon: GrMicrophone, name: "GrMicrophone", library: "gr" },
	{ icon: GrMoney, name: "GrMoney", library: "gr" },
	{ icon: GrMonitor, name: "GrMonitor", library: "gr" },
	{ icon: GrMonospace, name: "GrMonospace", library: "gr" },
	{ icon: GrMoon, name: "GrMoon", library: "gr" },
	{ icon: GrMoreVertical, name: "GrMoreVertical", library: "gr" },
	{ icon: GrMore, name: "GrMore", library: "gr" },
	{ icon: GrMouse, name: "GrMouse", library: "gr" },
	{ icon: GrMultimedia, name: "GrMultimedia", library: "gr" },
	{ icon: GrMultiple, name: "GrMultiple", library: "gr" },
	{ icon: GrMusic, name: "GrMusic", library: "gr" },
	{ icon: GrMysql, name: "GrMysql", library: "gr" },
	{ icon: GrNavigate, name: "GrNavigate", library: "gr" },
	{ icon: GrNetworkDrive, name: "GrNetworkDrive", library: "gr" },
	{ icon: GrNetwork, name: "GrNetwork", library: "gr" },
	{ icon: GrNewWindow, name: "GrNewWindow", library: "gr" },
	{ icon: GrNew, name: "GrNew", library: "gr" },
	{ icon: GrNext, name: "GrNext", library: "gr" },
	{ icon: GrNode, name: "GrNode", library: "gr" },
	{ icon: GrNodes, name: "GrNodes", library: "gr" },
	{ icon: GrNorton, name: "GrNorton", library: "gr" },
	{ icon: GrNote, name: "GrNote", library: "gr" },
	{ icon: GrNotes, name: "GrNotes", library: "gr" },
	{ icon: GrNotification, name: "GrNotification", library: "gr" },
	{ icon: GrNpm, name: "GrNpm", library: "gr" },
	{ icon: GrObjectGroup, name: "GrObjectGroup", library: "gr" },
	{ icon: GrObjectUngroup, name: "GrObjectUngroup", library: "gr" },
	{ icon: GrOfflineStorage, name: "GrOfflineStorage", library: "gr" },
	{ icon: GrOnedrive, name: "GrOnedrive", library: "gr" },
	{ icon: GrOpera, name: "GrOpera", library: "gr" },
	{ icon: GrOptimize, name: "GrOptimize", library: "gr" },
	{ icon: GrOracle, name: "GrOracle", library: "gr" },
	{ icon: GrOrderedList, name: "GrOrderedList", library: "gr" },
	{ icon: GrOrganization, name: "GrOrganization", library: "gr" },
	{ icon: GrOverview, name: "GrOverview", library: "gr" },
	{ icon: GrPackage, name: "GrPackage", library: "gr" },
	{ icon: GrPaint, name: "GrPaint", library: "gr" },
	{ icon: GrPan, name: "GrPan", library: "gr" },
	{ icon: GrPauseFill, name: "GrPauseFill", library: "gr" },
	{ icon: GrPause, name: "GrPause", library: "gr" },
	{ icon: GrPaypal, name: "GrPaypal", library: "gr" },
	{ icon: GrPerformance, name: "GrPerformance", library: "gr" },
	{ icon: GrPersonalComputer, name: "GrPersonalComputer", library: "gr" },
	{ icon: GrPhoneFlip, name: "GrPhoneFlip", library: "gr" },
	{ icon: GrPhoneHorizontal, name: "GrPhoneHorizontal", library: "gr" },
	{ icon: GrPhoneVertical, name: "GrPhoneVertical", library: "gr" },
	{ icon: GrPhone, name: "GrPhone", library: "gr" },
	{ icon: GrPieChart, name: "GrPieChart", library: "gr" },
	{ icon: GrPiedPiper, name: "GrPiedPiper", library: "gr" },
	{ icon: GrPin, name: "GrPin", library: "gr" },
	{ icon: GrPinterest, name: "GrPinterest", library: "gr" },
	{ icon: GrPlan, name: "GrPlan", library: "gr" },
	{ icon: GrPlayFill, name: "GrPlayFill", library: "gr" },
	{ icon: GrPlay, name: "GrPlay", library: "gr" },
	{ icon: GrPlug, name: "GrPlug", library: "gr" },
	{ icon: GrPocket, name: "GrPocket", library: "gr" },
	{ icon: GrPowerCycle, name: "GrPowerCycle", library: "gr" },
	{ icon: GrPowerForceShutdown, name: "GrPowerForceShutdown", library: "gr" },
	{ icon: GrPowerReset, name: "GrPowerReset", library: "gr" },
	{ icon: GrPowerShutdown, name: "GrPowerShutdown", library: "gr" },
	{ icon: GrPower, name: "GrPower", library: "gr" },
	{ icon: GrPrevious, name: "GrPrevious", library: "gr" },
	{ icon: GrPrint, name: "GrPrint", library: "gr" },
	{ icon: GrProductHunt, name: "GrProductHunt", library: "gr" },
	{ icon: GrProjects, name: "GrProjects", library: "gr" },
	{ icon: GrQr, name: "GrQr", library: "gr" },
	{ icon: GrRadialSelected, name: "GrRadialSelected", library: "gr" },
	{ icon: GrRadial, name: "GrRadial", library: "gr" },
	{ icon: GrRaspberry, name: "GrRaspberry", library: "gr" },
	{ icon: GrReactjs, name: "GrReactjs", library: "gr" },
	{ icon: GrReddit, name: "GrReddit", library: "gr" },
	{ icon: GrRedhat, name: "GrRedhat", library: "gr" },
	{ icon: GrRedo, name: "GrRedo", library: "gr" },
	{ icon: GrRefresh, name: "GrRefresh", library: "gr" },
	{ icon: GrResources, name: "GrResources", library: "gr" },
	{ icon: GrRestaurant, name: "GrRestaurant", library: "gr" },
	{ icon: GrRestroomMen, name: "GrRestroomMen", library: "gr" },
	{ icon: GrRestroomWomen, name: "GrRestroomWomen", library: "gr" },
	{ icon: GrRestroom, name: "GrRestroom", library: "gr" },
	{ icon: GrResume, name: "GrResume", library: "gr" },
	{ icon: GrReturn, name: "GrReturn", library: "gr" },
	{ icon: GrRevert, name: "GrRevert", library: "gr" },
	{ icon: GrRewind, name: "GrRewind", library: "gr" },
	{ icon: GrRisk, name: "GrRisk", library: "gr" },
	{ icon: GrRobot, name: "GrRobot", library: "gr" },
	{ icon: GrRotateLeft, name: "GrRotateLeft", library: "gr" },
	{ icon: GrRotateRight, name: "GrRotateRight", library: "gr" },
	{ icon: GrRss, name: "GrRss", library: "gr" },
	{ icon: GrRun, name: "GrRun", library: "gr" },
	{ icon: GrSafariOption, name: "GrSafariOption", library: "gr" },
	{ icon: GrSans, name: "GrSans", library: "gr" },
	{ icon: GrSatellite, name: "GrSatellite", library: "gr" },
	{ icon: GrSave, name: "GrSave", library: "gr" },
	{ icon: GrScan, name: "GrScan", library: "gr" },
	{ icon: GrScheduleNew, name: "GrScheduleNew", library: "gr" },
	{ icon: GrSchedulePlay, name: "GrSchedulePlay", library: "gr" },
	{ icon: GrSchedule, name: "GrSchedule", library: "gr" },
	{ icon: GrSchedules, name: "GrSchedules", library: "gr" },
	{ icon: GrSco, name: "GrSco", library: "gr" },
	{ icon: GrScorecard, name: "GrScorecard", library: "gr" },
	{ icon: GrScript, name: "GrScript", library: "gr" },
	{ icon: GrSd, name: "GrSd", library: "gr" },
	{ icon: GrSearchAdvanced, name: "GrSearchAdvanced", library: "gr" },
	{ icon: GrSearch, name: "GrSearch", library: "gr" },
	{ icon: GrSecure, name: "GrSecure", library: "gr" },
	{ icon: GrSelect, name: "GrSelect", library: "gr" },
	{ icon: GrSelection, name: "GrSelection", library: "gr" },
	{ icon: GrSemantics, name: "GrSemantics", library: "gr" },
	{ icon: GrSend, name: "GrSend", library: "gr" },
	{ icon: GrServerCluster, name: "GrServerCluster", library: "gr" },
	{ icon: GrServer, name: "GrServer", library: "gr" },
	{ icon: GrServers, name: "GrServers", library: "gr" },
	{ icon: GrServicePlay, name: "GrServicePlay", library: "gr" },
	{ icon: GrServices, name: "GrServices", library: "gr" },
	{ icon: GrSettingsOption, name: "GrSettingsOption", library: "gr" },
	{ icon: GrShareOption, name: "GrShareOption", library: "gr" },
	{ icon: GrShareRounded, name: "GrShareRounded", library: "gr" },
	{ icon: GrShare, name: "GrShare", library: "gr" },
	{ icon: GrShieldSecurity, name: "GrShieldSecurity", library: "gr" },
	{ icon: GrShield, name: "GrShield", library: "gr" },
	{ icon: GrShift, name: "GrShift", library: "gr" },
	{ icon: GrShop, name: "GrShop", library: "gr" },
	{ icon: GrSidebar, name: "GrSidebar", library: "gr" },
	{ icon: GrSign, name: "GrSign", library: "gr" },
	{ icon: GrSkype, name: "GrSkype", library: "gr" },
	{ icon: GrSlack, name: "GrSlack", library: "gr" },
	{ icon: GrSnapchat, name: "GrSnapchat", library: "gr" },
	{ icon: GrSolaris, name: "GrSolaris", library: "gr" },
	{ icon: GrSort, name: "GrSort", library: "gr" },
	{ icon: GrSoundcloud, name: "GrSoundcloud", library: "gr" },
	{ icon: GrSpa, name: "GrSpa", library: "gr" },
	{ icon: GrSpectrum, name: "GrSpectrum", library: "gr" },
	{ icon: GrSplit, name: "GrSplit", library: "gr" },
	{ icon: GrSplits, name: "GrSplits", library: "gr" },
	{ icon: GrSpotify, name: "GrSpotify", library: "gr" },
	{ icon: GrSquare, name: "GrSquare", library: "gr" },
	{ icon: GrStackOverflow, name: "GrStackOverflow", library: "gr" },
	{ icon: GrStakeholder, name: "GrStakeholder", library: "gr" },
	{ icon: GrStarHalf, name: "GrStarHalf", library: "gr" },
	{ icon: GrStar, name: "GrStar", library: "gr" },
	{ icon: GrStatusCriticalSmall, name: "GrStatusCriticalSmall", library: "gr" },
	{ icon: GrStatusCritical, name: "GrStatusCritical", library: "gr" },
	{ icon: GrStatusDisabledSmall, name: "GrStatusDisabledSmall", library: "gr" },
	{ icon: GrStatusDisabled, name: "GrStatusDisabled", library: "gr" },
	{ icon: GrStatusGoodSmall, name: "GrStatusGoodSmall", library: "gr" },
	{ icon: GrStatusGood, name: "GrStatusGood", library: "gr" },
	{ icon: GrStatusInfoSmall, name: "GrStatusInfoSmall", library: "gr" },
	{ icon: GrStatusInfo, name: "GrStatusInfo", library: "gr" },
	{ icon: GrStatusPlaceholderSmall, name: "GrStatusPlaceholderSmall", library: "gr" },
	{ icon: GrStatusPlaceholder, name: "GrStatusPlaceholder", library: "gr" },
	{ icon: GrStatusUnknownSmall, name: "GrStatusUnknownSmall", library: "gr" },
	{ icon: GrStatusUnknown, name: "GrStatusUnknown", library: "gr" },
	{ icon: GrStatusWarningSmall, name: "GrStatusWarningSmall", library: "gr" },
	{ icon: GrStatusWarning, name: "GrStatusWarning", library: "gr" },
	{ icon: GrStepsOption, name: "GrStepsOption", library: "gr" },
	{ icon: GrSteps, name: "GrSteps", library: "gr" },
	{ icon: GrStopFill, name: "GrStopFill", library: "gr" },
	{ icon: GrStop, name: "GrStop", library: "gr" },
	{ icon: GrStorage, name: "GrStorage", library: "gr" },
	{ icon: GrStreetView, name: "GrStreetView", library: "gr" },
	{ icon: GrStrikeThrough, name: "GrStrikeThrough", library: "gr" },
	{ icon: GrStripe, name: "GrStripe", library: "gr" },
	{ icon: GrSubscript, name: "GrSubscript", library: "gr" },
	{ icon: GrSubtractCircle, name: "GrSubtractCircle", library: "gr" },
	{ icon: GrSubtract, name: "GrSubtract", library: "gr" },
	{ icon: GrSun, name: "GrSun", library: "gr" },
	{ icon: GrSuperscript, name: "GrSuperscript", library: "gr" },
	{ icon: GrSupport, name: "GrSupport", library: "gr" },
	{ icon: GrSuse, name: "GrSuse", library: "gr" },
	{ icon: GrSwift, name: "GrSwift", library: "gr" },
	{ icon: GrSwim, name: "GrSwim", library: "gr" },
	{ icon: GrSwitch, name: "GrSwitch", library: "gr" },
	{ icon: GrSync, name: "GrSync", library: "gr" },
	{ icon: GrSystem, name: "GrSystem", library: "gr" },
	{ icon: GrTableAdd, name: "GrTableAdd", library: "gr" },
	{ icon: GrTable, name: "GrTable", library: "gr" },
	{ icon: GrTag, name: "GrTag", library: "gr" },
	{ icon: GrTapeOption, name: "GrTapeOption", library: "gr" },
	{ icon: GrTape, name: "GrTape", library: "gr" },
	{ icon: GrTarget, name: "GrTarget", library: "gr" },
	{ icon: GrTask, name: "GrTask", library: "gr" },
	{ icon: GrTasks, name: "GrTasks", library: "gr" },
	{ icon: GrTechnology, name: "GrTechnology", library: "gr" },
	{ icon: GrTemplate, name: "GrTemplate", library: "gr" },
	{ icon: GrTerminal, name: "GrTerminal", library: "gr" },
	{ icon: GrTestDesktop, name: "GrTestDesktop", library: "gr" },
	{ icon: GrTest, name: "GrTest", library: "gr" },
	{ icon: GrTextAlignCenter, name: "GrTextAlignCenter", library: "gr" },
	{ icon: GrTextAlignFull, name: "GrTextAlignFull", library: "gr" },
	{ icon: GrTextAlignLeft, name: "GrTextAlignLeft", library: "gr" },
	{ icon: GrTextAlignRight, name: "GrTextAlignRight", library: "gr" },
	{ icon: GrTextWrap, name: "GrTextWrap", library: "gr" },
	{ icon: GrThreats, name: "GrThreats", library: "gr" },
	{ icon: GrThreeDEffects, name: "GrThreeDEffects", library: "gr" },
	{ icon: GrThreeD, name: "GrThreeD", library: "gr" },
	{ icon: GrTicket, name: "GrTicket", library: "gr" },
	{ icon: GrTictok, name: "GrTictok", library: "gr" },
	{ icon: GrTime, name: "GrTime", library: "gr" },
	{ icon: GrTip, name: "GrTip", library: "gr" },
	{ icon: GrToast, name: "GrToast", library: "gr" },
	{ icon: GrTools, name: "GrTools", library: "gr" },
	{ icon: GrTooltip, name: "GrTooltip", library: "gr" },
	{ icon: GrTopCorner, name: "GrTopCorner", library: "gr" },
	{ icon: GrTrain, name: "GrTrain", library: "gr" },
	{ icon: GrTransaction, name: "GrTransaction", library: "gr" },
	{ icon: GrTrash, name: "GrTrash", library: "gr" },
	{ icon: GrTreeOption, name: "GrTreeOption", library: "gr" },
	{ icon: GrTree, name: "GrTree", library: "gr" },
	{ icon: GrTrigger, name: "GrTrigger", library: "gr" },
	{ icon: GrTrophy, name: "GrTrophy", library: "gr" },
	{ icon: GrTroubleshoot, name: "GrTroubleshoot", library: "gr" },
	{ icon: GrTty, name: "GrTty", library: "gr" },
	{ icon: GrTumblr, name: "GrTumblr", library: "gr" },
	{ icon: GrTurbolinux, name: "GrTurbolinux", library: "gr" },
	{ icon: GrTwitter, name: "GrTwitter", library: "gr" },
	{ icon: GrUbuntu, name: "GrUbuntu", library: "gr" },
	{ icon: GrUnderline, name: "GrUnderline", library: "gr" },
	{ icon: GrUndo, name: "GrUndo", library: "gr" },
	{ icon: GrUnlink, name: "GrUnlink", library: "gr" },
	{ icon: GrUnlock, name: "GrUnlock", library: "gr" },
	{ icon: GrUnorderedList, name: "GrUnorderedList", library: "gr" },
	{ icon: GrUnsorted, name: "GrUnsorted", library: "gr" },
	{ icon: GrUp, name: "GrUp", library: "gr" },
	{ icon: GrUpdate, name: "GrUpdate", library: "gr" },
	{ icon: GrUpgrade, name: "GrUpgrade", library: "gr" },
	{ icon: GrUploadOption, name: "GrUploadOption", library: "gr" },
	{ icon: GrUpload, name: "GrUpload", library: "gr" },
	{ icon: GrUsbKey, name: "GrUsbKey", library: "gr" },
	{ icon: GrUserAdd, name: "GrUserAdd", library: "gr" },
	{ icon: GrUserAdmin, name: "GrUserAdmin", library: "gr" },
	{ icon: GrUserExpert, name: "GrUserExpert", library: "gr" },
	{ icon: GrUserFemale, name: "GrUserFemale", library: "gr" },
	{ icon: GrUserManager, name: "GrUserManager", library: "gr" },
	{ icon: GrUserNew, name: "GrUserNew", library: "gr" },
	{ icon: GrUserPolice, name: "GrUserPolice", library: "gr" },
	{ icon: GrUserSettings, name: "GrUserSettings", library: "gr" },
	{ icon: GrUserWorker, name: "GrUserWorker", library: "gr" },
	{ icon: GrUser, name: "GrUser", library: "gr" },
	{ icon: GrValidate, name: "GrValidate", library: "gr" },
	{ icon: GrVend, name: "GrVend", library: "gr" },
	{ icon: GrVideo, name: "GrVideo", library: "gr" },
	{ icon: GrView, name: "GrView", library: "gr" },
	{ icon: GrVimeo, name: "GrVimeo", library: "gr" },
	{ icon: GrVirtualMachine, name: "GrVirtualMachine", library: "gr" },
	{ icon: GrVirtualStorage, name: "GrVirtualStorage", library: "gr" },
	{ icon: GrVisa, name: "GrVisa", library: "gr" },
	{ icon: GrVmMaintenance, name: "GrVmMaintenance", library: "gr" },
	{ icon: GrVmware, name: "GrVmware", library: "gr" },
	{ icon: GrVolumeControl, name: "GrVolumeControl", library: "gr" },
	{ icon: GrVolumeLow, name: "GrVolumeLow", library: "gr" },
	{ icon: GrVolumeMute, name: "GrVolumeMute", library: "gr" },
	{ icon: GrVolume, name: "GrVolume", library: "gr" },
	{ icon: GrVulnerability, name: "GrVulnerability", library: "gr" },
	{ icon: GrWaypoint, name: "GrWaypoint", library: "gr" },
	{ icon: GrWebcam, name: "GrWebcam", library: "gr" },
	{ icon: GrWheelchairActive, name: "GrWheelchairActive", library: "gr" },
	{ icon: GrWheelchair, name: "GrWheelchair", library: "gr" },
	{ icon: GrWifiLow, name: "GrWifiLow", library: "gr" },
	{ icon: GrWifiMedium, name: "GrWifiMedium", library: "gr" },
	{ icon: GrWifiNone, name: "GrWifiNone", library: "gr" },
	{ icon: GrWifi, name: "GrWifi", library: "gr" },
	{ icon: GrWindowsLegacy, name: "GrWindowsLegacy", library: "gr" },
	{ icon: GrWindows, name: "GrWindows", library: "gr" },
	{ icon: GrWordpress, name: "GrWordpress", library: "gr" },
	{ icon: GrWorkshop, name: "GrWorkshop", library: "gr" },
	{ icon: GrYoga, name: "GrYoga", library: "gr" },
	{ icon: GrYoutube, name: "GrYoutube", library: "gr" },
	{ icon: GrZoomIn, name: "GrZoomIn", library: "gr" },
	{ icon: GrZoomOut, name: "GrZoomOut", library: "gr" },
	{ icon: GrZoom, name: "GrZoom", library: "gr" },
];

export default result;
