import {
GrAccessibility,
GrAchievement,
GrAction,
GrActions,
GrAd,
GrAddCircle,
GrAdd,
GrAed,
GrAggregate,
GrAidOption,
GrAid,
GrAlarm,
GrAlert,
GrAmazon,
GrAmex,
GrAnalytics,
GrAnchor,
GrAndroid,
GrAnnounce,
GrAppleAppStore,
GrApple,
GrAppsRounded,
GrApps,
GrArchive,
GrArchlinux,
GrArticle,
GrAruba,
GrAscend,
GrAscending,
GrAssistListening,
GrAtm,
GrAttachment,
GrAttraction,
GrBaby,
GrBackTen,
GrBarChart,
GrBar,
GrBasket,
GrBeacon,
GrBike,
GrBitcoin,
GrBladesHorizontal,
GrBladesVertical,
GrBlockQuote,
GrBlog,
GrBluetooth,
GrBold,
GrBook,
GrBookmark,
GrBottomCorner,
GrBraille,
GrBriefcase,
GrBrush,
GrBug,
GrBundle,
GrBus,
GrBusinessService,
GrCafeteria,
GrCalculator,
GrCalendar,
GrCamera,
GrCapacity,
GrCar,
GrCaretDownFill,
GrCaretDown,
GrCaretLeftFill,
GrCaretNext,
GrCaretPrevious,
GrCaretRightFill,
GrCaretUpFill,
GrCaretUp,
GrCart,
GrCatalogOption,
GrCatalog,
GrCentos,
GrCertificate,
GrChannel,
GrChapterAdd,
GrChapterNext,
GrChapterPrevious,
GrChatOption,
GrChat,
GrCheckboxSelected,
GrCheckbox,
GrCheckmark,
GrChrome,
GrCircleAlert,
GrCircleInformation,
GrCirclePlay,
GrCircleQuestion,
GrClearOption,
GrClear,
GrCli,
GrClipboard,
GrClock,
GrClone,
GrClose,
GrClosedCaption,
GrCloudComputer,
GrCloudDownload,
GrCloudSoftware,
GrCloudUpload,
GrCloud,
GrCloudlinux,
GrCluster,
GrCoatCheck,
GrCodeSandbox,
GrCode,
GrCodepen,
GrCoffee,
GrColumns,
GrCommand,
GrCompare,
GrCompass,
GrCompliance,
GrConfigure,
GrConnect,
GrConnectivity,
GrConsole,
GrContactInfo,
GrContact,
GrContract,
GrCopy,
GrCpu,
GrCreativeCommons,
GrCreditCard,
GrCss3,
GrCube,
GrCubes,
GrCurrency,
GrCursor,
GrCut,
GrCycle,
GrDashboard,
GrDatabase,
GrDebian,
GrDeliver,
GrDeploy,
GrDescend,
GrDescending,
GrDesktop,
GrDetach,
GrDevice,
GrDiamond,
GrDirections,
GrDisabledOutline,
GrDisc,
GrDislike,
GrDocker,
GrDocumentCloud,
GrDocumentConfig,
GrDocumentCsv,
GrDocumentDownload,
GrDocumentExcel,
GrDocumentImage,
GrDocumentLocked,
GrDocumentMissing,
GrDocumentNotes,
GrDocumentOutlook,
GrDocumentPdf,
GrDocumentPerformance,
GrDocumentPpt,
GrDocumentRtf,
GrDocumentSound,
GrDocumentStore,
GrDocumentTest,
GrDocumentText,
GrDocumentThreat,
GrDocumentTime,
GrDocumentTransfer,
GrDocumentTxt,
GrDocumentUpdate,
GrDocumentUpload,
GrDocumentUser,
GrDocumentVerified,
GrDocumentVideo,
GrDocumentWindows,
GrDocumentWord,
GrDocumentZip,
GrDocument,
GrDomain,
GrDos,
GrDown,
GrDownloadOption,
GrDownload,
GrDrag,
GrDrawer,
GrDribbble,
GrDriveCage,
GrDropbox,
GrDuplicate,
GrDxc,
GrEbay,
GrEdge,
GrEdit,
GrEject,
GrElevator,
GrEmergency,
GrEmoji,
GrEmptyCircle,
GrErase,
GrEscalator,
GrExpand,
GrEzmeral,
GrFacebookOption,
GrFacebook,
GrFanOption,
GrFan,
GrFastForward,
GrFavorite,
GrFedora,
GrFigma,
GrFilter,
GrFingerPrint,
GrFireball,
GrFirefox,
GrFirewall,
GrFlagFill,
GrFlag,
GrFlows,
GrFolderCycle,
GrFolderOpen,
GrFolder,
GrFormAdd,
GrFormAttachment,
GrFormCalendar,
GrFormCheckmark,
GrFormClock,
GrFormClose,
GrFormCut,
GrFormDown,
GrFormEdit,
GrFormFilter,
GrFormFolder,
GrFormLocation,
GrFormLock,
GrFormNextLink,
GrFormNext,
GrFormPreviousLink,
GrFormPrevious,
GrFormRefresh,
GrFormSchedule,
GrFormSearch,
GrFormSubtract,
GrFormTrash,
GrFormUp,
GrFormUpload,
GrFormViewHide,
GrFormView,
GrForwardTen,
GrFreebsd,
GrGallery,
GrGamepad,
GrGateway,
GrGatsbyjs,
GrGem,
GrGift,
GrGithub,
GrGlobe,
GrGolang,
GrGooglePlay,
GrGooglePlus,
GrGoogleWallet,
GrGoogle,
GrGraphQl,
GrGremlin,
GrGrid,
GrGrommet,
GrGroup,
GrGrow,
GrHadoop,
GrHalt,
GrHelpOption,
GrHelp,
GrHeroku,
GrHide,
GrHistory,
GrHomeOption,
GrHomeRounded,
GrHome,
GrHorton,
GrHostMaintenance,
GrHost,
GrHp,
GrHpeLabs,
GrHpe,
GrHpi,
GrHtml5,
GrIceCream,
GrImage,
GrImpact,
GrInProgress,
GrInbox,
GrIndicator,
GrInfo,
GrInherit,
GrInsecure,
GrInspect,
GrInstagram,
GrInstallOption,
GrInstall,
GrIntegration,
GrInternetExplorer,
GrItalic,
GrIteration,
GrJava,
GrJs,
GrKey,
GrKeyboard,
GrLanguage,
GrLastfm,
GrLaunch,
GrLayer,
GrLicense,
GrLike,
GrLineChart,
GrLinkBottom,
GrLinkDown,
GrLinkNext,
GrLinkPrevious,
GrLinkTop,
GrLinkUp,
GrLink,
GrLinkedinOption,
GrLinkedin,
GrList,
GrLocal,
GrLocationPin,
GrLocation,
GrLock,
GrLogin,
GrLogout,
GrLounge,
GrMagic,
GrMailOption,
GrMail,
GrMandriva,
GrManual,
GrMapLocation,
GrMap,
GrMastercard,
GrMedium,
GrMemory,
GrMenu,
GrMicrofocus,
GrMicrophone,
GrMoney,
GrMonitor,
GrMonospace,
GrMoon,
GrMoreVertical,
GrMore,
GrMouse,
GrMultimedia,
GrMultiple,
GrMusic,
GrMysql,
GrNavigate,
GrNetworkDrive,
GrNetwork,
GrNewWindow,
GrNew,
GrNext,
GrNode,
GrNodes,
GrNorton,
GrNote,
GrNotes,
GrNotification,
GrNpm,
GrObjectGroup,
GrObjectUngroup,
GrOfflineStorage,
GrOnedrive,
GrOpera,
GrOptimize,
GrOracle,
GrOrderedList,
GrOrganization,
GrOverview,
GrPackage,
GrPaint,
GrPan,
GrPauseFill,
GrPause,
GrPaypal,
GrPerformance,
GrPersonalComputer,
GrPhoneFlip,
GrPhoneHorizontal,
GrPhoneVertical,
GrPhone,
GrPieChart,
GrPiedPiper,
GrPin,
GrPinterest,
GrPlan,
GrPlayFill,
GrPlay,
GrPlug,
GrPocket,
GrPowerCycle,
GrPowerForceShutdown,
GrPowerReset,
GrPowerShutdown,
GrPower,
GrPrevious,
GrPrint,
GrProductHunt,
GrProjects,
GrQr,
GrRadialSelected,
GrRadial,
GrRaspberry,
GrReactjs,
GrReddit,
GrRedhat,
GrRedo,
GrRefresh,
GrResources,
GrRestaurant,
GrRestroomMen,
GrRestroomWomen,
GrRestroom,
GrResume,
GrReturn,
GrRevert,
GrRewind,
GrRisk,
GrRobot,
GrRotateLeft,
GrRotateRight,
GrRss,
GrRun,
GrSafariOption,
GrSans,
GrSatellite,
GrSave,
GrScan,
GrScheduleNew,
GrSchedulePlay,
GrSchedule,
GrSchedules,
GrSco,
GrScorecard,
GrScript,
GrSd,
GrSearchAdvanced,
GrSearch,
GrSecure,
GrSelect,
GrSelection,
GrSemantics,
GrSend,
GrServerCluster,
GrServer,
GrServers,
GrServicePlay,
GrServices,
GrSettingsOption,
GrShareOption,
GrShareRounded,
GrShare,
GrShieldSecurity,
GrShield,
GrShift,
GrShop,
GrSidebar,
GrSign,
GrSkype,
GrSlack,
GrSnapchat,
GrSolaris,
GrSort,
GrSoundcloud,
GrSpa,
GrSpectrum,
GrSplit,
GrSplits,
GrSpotify,
GrSquare,
GrStackOverflow,
GrStakeholder,
GrStarHalf,
GrStar,
GrStatusCriticalSmall,
GrStatusCritical,
GrStatusDisabledSmall,
GrStatusDisabled,
GrStatusGoodSmall,
GrStatusGood,
GrStatusInfoSmall,
GrStatusInfo,
GrStatusPlaceholderSmall,
GrStatusPlaceholder,
GrStatusUnknownSmall,
GrStatusUnknown,
GrStatusWarningSmall,
GrStatusWarning,
GrStepsOption,
GrSteps,
GrStopFill,
GrStop,
GrStorage,
GrStreetView,
GrStrikeThrough,
GrStripe,
GrSubscript,
GrSubtractCircle,
GrSubtract,
GrSun,
GrSuperscript,
GrSupport,
GrSuse,
GrSwift,
GrSwim,
GrSwitch,
GrSync,
GrSystem,
GrTableAdd,
GrTable,
GrTag,
GrTapeOption,
GrTape,
GrTarget,
GrTask,
GrTasks,
GrTechnology,
GrTemplate,
GrTerminal,
GrTestDesktop,
GrTest,
GrTextAlignCenter,
GrTextAlignFull,
GrTextAlignLeft,
GrTextAlignRight,
GrTextWrap,
GrThreats,
GrThreeDEffects,
GrThreeD,
GrTicket,
GrTictok,
GrTime,
GrTip,
GrToast,
GrTools,
GrTooltip,
GrTopCorner,
GrTrain,
GrTransaction,
GrTrash,
GrTreeOption,
GrTree,
GrTrigger,
GrTrophy,
GrTroubleshoot,
GrTty,
GrTumblr,
GrTurbolinux,
GrTwitter,
GrUbuntu,
GrUnderline,
GrUndo,
GrUnlink,
GrUnlock,
GrUnorderedList,
GrUnsorted,
GrUp,
GrUpdate,
GrUpgrade,
GrUploadOption,
GrUpload,
GrUsbKey,
GrUserAdd,
GrUserAdmin,
GrUserExpert,
GrUserFemale,
GrUserManager,
GrUserNew,
GrUserPolice,
GrUserSettings,
GrUserWorker,
GrUser,
GrValidate,
GrVend,
GrVideo,
GrView,
GrVimeo,
GrVirtualMachine,
GrVirtualStorage,
GrVisa,
GrVmMaintenance,
GrVmware,
GrVolumeControl,
GrVolumeLow,
GrVolumeMute,
GrVolume,
GrVulnerability,
GrWaypoint,
GrWebcam,
GrWheelchairActive,
GrWheelchair,
GrWifiLow,
GrWifiMedium,
GrWifiNone,
GrWifi,
GrWindowsLegacy,
GrWindows,
GrWordpress,
GrWorkshop,
GrYoga,
GrYoutube,
GrZoomIn,
GrZoomOut,
GrZoom,
} from "react-icons/gr";

const result = [
{ icon: GrAccessibility, name: "GrAccessibility" },
{ icon: GrAchievement, name: "GrAchievement" },
{ icon: GrAction, name: "GrAction" },
{ icon: GrActions, name: "GrActions" },
{ icon: GrAd, name: "GrAd" },
{ icon: GrAddCircle, name: "GrAddCircle" },
{ icon: GrAdd, name: "GrAdd" },
{ icon: GrAed, name: "GrAed" },
{ icon: GrAggregate, name: "GrAggregate" },
{ icon: GrAidOption, name: "GrAidOption" },
{ icon: GrAid, name: "GrAid" },
{ icon: GrAlarm, name: "GrAlarm" },
{ icon: GrAlert, name: "GrAlert" },
{ icon: GrAmazon, name: "GrAmazon" },
{ icon: GrAmex, name: "GrAmex" },
{ icon: GrAnalytics, name: "GrAnalytics" },
{ icon: GrAnchor, name: "GrAnchor" },
{ icon: GrAndroid, name: "GrAndroid" },
{ icon: GrAnnounce, name: "GrAnnounce" },
{ icon: GrAppleAppStore, name: "GrAppleAppStore" },
{ icon: GrApple, name: "GrApple" },
{ icon: GrAppsRounded, name: "GrAppsRounded" },
{ icon: GrApps, name: "GrApps" },
{ icon: GrArchive, name: "GrArchive" },
{ icon: GrArchlinux, name: "GrArchlinux" },
{ icon: GrArticle, name: "GrArticle" },
{ icon: GrAruba, name: "GrAruba" },
{ icon: GrAscend, name: "GrAscend" },
{ icon: GrAscending, name: "GrAscending" },
{ icon: GrAssistListening, name: "GrAssistListening" },
{ icon: GrAtm, name: "GrAtm" },
{ icon: GrAttachment, name: "GrAttachment" },
{ icon: GrAttraction, name: "GrAttraction" },
{ icon: GrBaby, name: "GrBaby" },
{ icon: GrBackTen, name: "GrBackTen" },
{ icon: GrBarChart, name: "GrBarChart" },
{ icon: GrBar, name: "GrBar" },
{ icon: GrBasket, name: "GrBasket" },
{ icon: GrBeacon, name: "GrBeacon" },
{ icon: GrBike, name: "GrBike" },
{ icon: GrBitcoin, name: "GrBitcoin" },
{ icon: GrBladesHorizontal, name: "GrBladesHorizontal" },
{ icon: GrBladesVertical, name: "GrBladesVertical" },
{ icon: GrBlockQuote, name: "GrBlockQuote" },
{ icon: GrBlog, name: "GrBlog" },
{ icon: GrBluetooth, name: "GrBluetooth" },
{ icon: GrBold, name: "GrBold" },
{ icon: GrBook, name: "GrBook" },
{ icon: GrBookmark, name: "GrBookmark" },
{ icon: GrBottomCorner, name: "GrBottomCorner" },
{ icon: GrBraille, name: "GrBraille" },
{ icon: GrBriefcase, name: "GrBriefcase" },
{ icon: GrBrush, name: "GrBrush" },
{ icon: GrBug, name: "GrBug" },
{ icon: GrBundle, name: "GrBundle" },
{ icon: GrBus, name: "GrBus" },
{ icon: GrBusinessService, name: "GrBusinessService" },
{ icon: GrCafeteria, name: "GrCafeteria" },
{ icon: GrCalculator, name: "GrCalculator" },
{ icon: GrCalendar, name: "GrCalendar" },
{ icon: GrCamera, name: "GrCamera" },
{ icon: GrCapacity, name: "GrCapacity" },
{ icon: GrCar, name: "GrCar" },
{ icon: GrCaretDownFill, name: "GrCaretDownFill" },
{ icon: GrCaretDown, name: "GrCaretDown" },
{ icon: GrCaretLeftFill, name: "GrCaretLeftFill" },
{ icon: GrCaretNext, name: "GrCaretNext" },
{ icon: GrCaretPrevious, name: "GrCaretPrevious" },
{ icon: GrCaretRightFill, name: "GrCaretRightFill" },
{ icon: GrCaretUpFill, name: "GrCaretUpFill" },
{ icon: GrCaretUp, name: "GrCaretUp" },
{ icon: GrCart, name: "GrCart" },
{ icon: GrCatalogOption, name: "GrCatalogOption" },
{ icon: GrCatalog, name: "GrCatalog" },
{ icon: GrCentos, name: "GrCentos" },
{ icon: GrCertificate, name: "GrCertificate" },
{ icon: GrChannel, name: "GrChannel" },
{ icon: GrChapterAdd, name: "GrChapterAdd" },
{ icon: GrChapterNext, name: "GrChapterNext" },
{ icon: GrChapterPrevious, name: "GrChapterPrevious" },
{ icon: GrChatOption, name: "GrChatOption" },
{ icon: GrChat, name: "GrChat" },
{ icon: GrCheckboxSelected, name: "GrCheckboxSelected" },
{ icon: GrCheckbox, name: "GrCheckbox" },
{ icon: GrCheckmark, name: "GrCheckmark" },
{ icon: GrChrome, name: "GrChrome" },
{ icon: GrCircleAlert, name: "GrCircleAlert" },
{ icon: GrCircleInformation, name: "GrCircleInformation" },
{ icon: GrCirclePlay, name: "GrCirclePlay" },
{ icon: GrCircleQuestion, name: "GrCircleQuestion" },
{ icon: GrClearOption, name: "GrClearOption" },
{ icon: GrClear, name: "GrClear" },
{ icon: GrCli, name: "GrCli" },
{ icon: GrClipboard, name: "GrClipboard" },
{ icon: GrClock, name: "GrClock" },
{ icon: GrClone, name: "GrClone" },
{ icon: GrClose, name: "GrClose" },
{ icon: GrClosedCaption, name: "GrClosedCaption" },
{ icon: GrCloudComputer, name: "GrCloudComputer" },
{ icon: GrCloudDownload, name: "GrCloudDownload" },
{ icon: GrCloudSoftware, name: "GrCloudSoftware" },
{ icon: GrCloudUpload, name: "GrCloudUpload" },
{ icon: GrCloud, name: "GrCloud" },
{ icon: GrCloudlinux, name: "GrCloudlinux" },
{ icon: GrCluster, name: "GrCluster" },
{ icon: GrCoatCheck, name: "GrCoatCheck" },
{ icon: GrCodeSandbox, name: "GrCodeSandbox" },
{ icon: GrCode, name: "GrCode" },
{ icon: GrCodepen, name: "GrCodepen" },
{ icon: GrCoffee, name: "GrCoffee" },
{ icon: GrColumns, name: "GrColumns" },
{ icon: GrCommand, name: "GrCommand" },
{ icon: GrCompare, name: "GrCompare" },
{ icon: GrCompass, name: "GrCompass" },
{ icon: GrCompliance, name: "GrCompliance" },
{ icon: GrConfigure, name: "GrConfigure" },
{ icon: GrConnect, name: "GrConnect" },
{ icon: GrConnectivity, name: "GrConnectivity" },
{ icon: GrConsole, name: "GrConsole" },
{ icon: GrContactInfo, name: "GrContactInfo" },
{ icon: GrContact, name: "GrContact" },
{ icon: GrContract, name: "GrContract" },
{ icon: GrCopy, name: "GrCopy" },
{ icon: GrCpu, name: "GrCpu" },
{ icon: GrCreativeCommons, name: "GrCreativeCommons" },
{ icon: GrCreditCard, name: "GrCreditCard" },
{ icon: GrCss3, name: "GrCss3" },
{ icon: GrCube, name: "GrCube" },
{ icon: GrCubes, name: "GrCubes" },
{ icon: GrCurrency, name: "GrCurrency" },
{ icon: GrCursor, name: "GrCursor" },
{ icon: GrCut, name: "GrCut" },
{ icon: GrCycle, name: "GrCycle" },
{ icon: GrDashboard, name: "GrDashboard" },
{ icon: GrDatabase, name: "GrDatabase" },
{ icon: GrDebian, name: "GrDebian" },
{ icon: GrDeliver, name: "GrDeliver" },
{ icon: GrDeploy, name: "GrDeploy" },
{ icon: GrDescend, name: "GrDescend" },
{ icon: GrDescending, name: "GrDescending" },
{ icon: GrDesktop, name: "GrDesktop" },
{ icon: GrDetach, name: "GrDetach" },
{ icon: GrDevice, name: "GrDevice" },
{ icon: GrDiamond, name: "GrDiamond" },
{ icon: GrDirections, name: "GrDirections" },
{ icon: GrDisabledOutline, name: "GrDisabledOutline" },
{ icon: GrDisc, name: "GrDisc" },
{ icon: GrDislike, name: "GrDislike" },
{ icon: GrDocker, name: "GrDocker" },
{ icon: GrDocumentCloud, name: "GrDocumentCloud" },
{ icon: GrDocumentConfig, name: "GrDocumentConfig" },
{ icon: GrDocumentCsv, name: "GrDocumentCsv" },
{ icon: GrDocumentDownload, name: "GrDocumentDownload" },
{ icon: GrDocumentExcel, name: "GrDocumentExcel" },
{ icon: GrDocumentImage, name: "GrDocumentImage" },
{ icon: GrDocumentLocked, name: "GrDocumentLocked" },
{ icon: GrDocumentMissing, name: "GrDocumentMissing" },
{ icon: GrDocumentNotes, name: "GrDocumentNotes" },
{ icon: GrDocumentOutlook, name: "GrDocumentOutlook" },
{ icon: GrDocumentPdf, name: "GrDocumentPdf" },
{ icon: GrDocumentPerformance, name: "GrDocumentPerformance" },
{ icon: GrDocumentPpt, name: "GrDocumentPpt" },
{ icon: GrDocumentRtf, name: "GrDocumentRtf" },
{ icon: GrDocumentSound, name: "GrDocumentSound" },
{ icon: GrDocumentStore, name: "GrDocumentStore" },
{ icon: GrDocumentTest, name: "GrDocumentTest" },
{ icon: GrDocumentText, name: "GrDocumentText" },
{ icon: GrDocumentThreat, name: "GrDocumentThreat" },
{ icon: GrDocumentTime, name: "GrDocumentTime" },
{ icon: GrDocumentTransfer, name: "GrDocumentTransfer" },
{ icon: GrDocumentTxt, name: "GrDocumentTxt" },
{ icon: GrDocumentUpdate, name: "GrDocumentUpdate" },
{ icon: GrDocumentUpload, name: "GrDocumentUpload" },
{ icon: GrDocumentUser, name: "GrDocumentUser" },
{ icon: GrDocumentVerified, name: "GrDocumentVerified" },
{ icon: GrDocumentVideo, name: "GrDocumentVideo" },
{ icon: GrDocumentWindows, name: "GrDocumentWindows" },
{ icon: GrDocumentWord, name: "GrDocumentWord" },
{ icon: GrDocumentZip, name: "GrDocumentZip" },
{ icon: GrDocument, name: "GrDocument" },
{ icon: GrDomain, name: "GrDomain" },
{ icon: GrDos, name: "GrDos" },
{ icon: GrDown, name: "GrDown" },
{ icon: GrDownloadOption, name: "GrDownloadOption" },
{ icon: GrDownload, name: "GrDownload" },
{ icon: GrDrag, name: "GrDrag" },
{ icon: GrDrawer, name: "GrDrawer" },
{ icon: GrDribbble, name: "GrDribbble" },
{ icon: GrDriveCage, name: "GrDriveCage" },
{ icon: GrDropbox, name: "GrDropbox" },
{ icon: GrDuplicate, name: "GrDuplicate" },
{ icon: GrDxc, name: "GrDxc" },
{ icon: GrEbay, name: "GrEbay" },
{ icon: GrEdge, name: "GrEdge" },
{ icon: GrEdit, name: "GrEdit" },
{ icon: GrEject, name: "GrEject" },
{ icon: GrElevator, name: "GrElevator" },
{ icon: GrEmergency, name: "GrEmergency" },
{ icon: GrEmoji, name: "GrEmoji" },
{ icon: GrEmptyCircle, name: "GrEmptyCircle" },
{ icon: GrErase, name: "GrErase" },
{ icon: GrEscalator, name: "GrEscalator" },
{ icon: GrExpand, name: "GrExpand" },
{ icon: GrEzmeral, name: "GrEzmeral" },
{ icon: GrFacebookOption, name: "GrFacebookOption" },
{ icon: GrFacebook, name: "GrFacebook" },
{ icon: GrFanOption, name: "GrFanOption" },
{ icon: GrFan, name: "GrFan" },
{ icon: GrFastForward, name: "GrFastForward" },
{ icon: GrFavorite, name: "GrFavorite" },
{ icon: GrFedora, name: "GrFedora" },
{ icon: GrFigma, name: "GrFigma" },
{ icon: GrFilter, name: "GrFilter" },
{ icon: GrFingerPrint, name: "GrFingerPrint" },
{ icon: GrFireball, name: "GrFireball" },
{ icon: GrFirefox, name: "GrFirefox" },
{ icon: GrFirewall, name: "GrFirewall" },
{ icon: GrFlagFill, name: "GrFlagFill" },
{ icon: GrFlag, name: "GrFlag" },
{ icon: GrFlows, name: "GrFlows" },
{ icon: GrFolderCycle, name: "GrFolderCycle" },
{ icon: GrFolderOpen, name: "GrFolderOpen" },
{ icon: GrFolder, name: "GrFolder" },
{ icon: GrFormAdd, name: "GrFormAdd" },
{ icon: GrFormAttachment, name: "GrFormAttachment" },
{ icon: GrFormCalendar, name: "GrFormCalendar" },
{ icon: GrFormCheckmark, name: "GrFormCheckmark" },
{ icon: GrFormClock, name: "GrFormClock" },
{ icon: GrFormClose, name: "GrFormClose" },
{ icon: GrFormCut, name: "GrFormCut" },
{ icon: GrFormDown, name: "GrFormDown" },
{ icon: GrFormEdit, name: "GrFormEdit" },
{ icon: GrFormFilter, name: "GrFormFilter" },
{ icon: GrFormFolder, name: "GrFormFolder" },
{ icon: GrFormLocation, name: "GrFormLocation" },
{ icon: GrFormLock, name: "GrFormLock" },
{ icon: GrFormNextLink, name: "GrFormNextLink" },
{ icon: GrFormNext, name: "GrFormNext" },
{ icon: GrFormPreviousLink, name: "GrFormPreviousLink" },
{ icon: GrFormPrevious, name: "GrFormPrevious" },
{ icon: GrFormRefresh, name: "GrFormRefresh" },
{ icon: GrFormSchedule, name: "GrFormSchedule" },
{ icon: GrFormSearch, name: "GrFormSearch" },
{ icon: GrFormSubtract, name: "GrFormSubtract" },
{ icon: GrFormTrash, name: "GrFormTrash" },
{ icon: GrFormUp, name: "GrFormUp" },
{ icon: GrFormUpload, name: "GrFormUpload" },
{ icon: GrFormViewHide, name: "GrFormViewHide" },
{ icon: GrFormView, name: "GrFormView" },
{ icon: GrForwardTen, name: "GrForwardTen" },
{ icon: GrFreebsd, name: "GrFreebsd" },
{ icon: GrGallery, name: "GrGallery" },
{ icon: GrGamepad, name: "GrGamepad" },
{ icon: GrGateway, name: "GrGateway" },
{ icon: GrGatsbyjs, name: "GrGatsbyjs" },
{ icon: GrGem, name: "GrGem" },
{ icon: GrGift, name: "GrGift" },
{ icon: GrGithub, name: "GrGithub" },
{ icon: GrGlobe, name: "GrGlobe" },
{ icon: GrGolang, name: "GrGolang" },
{ icon: GrGooglePlay, name: "GrGooglePlay" },
{ icon: GrGooglePlus, name: "GrGooglePlus" },
{ icon: GrGoogleWallet, name: "GrGoogleWallet" },
{ icon: GrGoogle, name: "GrGoogle" },
{ icon: GrGraphQl, name: "GrGraphQl" },
{ icon: GrGremlin, name: "GrGremlin" },
{ icon: GrGrid, name: "GrGrid" },
{ icon: GrGrommet, name: "GrGrommet" },
{ icon: GrGroup, name: "GrGroup" },
{ icon: GrGrow, name: "GrGrow" },
{ icon: GrHadoop, name: "GrHadoop" },
{ icon: GrHalt, name: "GrHalt" },
{ icon: GrHelpOption, name: "GrHelpOption" },
{ icon: GrHelp, name: "GrHelp" },
{ icon: GrHeroku, name: "GrHeroku" },
{ icon: GrHide, name: "GrHide" },
{ icon: GrHistory, name: "GrHistory" },
{ icon: GrHomeOption, name: "GrHomeOption" },
{ icon: GrHomeRounded, name: "GrHomeRounded" },
{ icon: GrHome, name: "GrHome" },
{ icon: GrHorton, name: "GrHorton" },
{ icon: GrHostMaintenance, name: "GrHostMaintenance" },
{ icon: GrHost, name: "GrHost" },
{ icon: GrHp, name: "GrHp" },
{ icon: GrHpeLabs, name: "GrHpeLabs" },
{ icon: GrHpe, name: "GrHpe" },
{ icon: GrHpi, name: "GrHpi" },
{ icon: GrHtml5, name: "GrHtml5" },
{ icon: GrIceCream, name: "GrIceCream" },
{ icon: GrImage, name: "GrImage" },
{ icon: GrImpact, name: "GrImpact" },
{ icon: GrInProgress, name: "GrInProgress" },
{ icon: GrInbox, name: "GrInbox" },
{ icon: GrIndicator, name: "GrIndicator" },
{ icon: GrInfo, name: "GrInfo" },
{ icon: GrInherit, name: "GrInherit" },
{ icon: GrInsecure, name: "GrInsecure" },
{ icon: GrInspect, name: "GrInspect" },
{ icon: GrInstagram, name: "GrInstagram" },
{ icon: GrInstallOption, name: "GrInstallOption" },
{ icon: GrInstall, name: "GrInstall" },
{ icon: GrIntegration, name: "GrIntegration" },
{ icon: GrInternetExplorer, name: "GrInternetExplorer" },
{ icon: GrItalic, name: "GrItalic" },
{ icon: GrIteration, name: "GrIteration" },
{ icon: GrJava, name: "GrJava" },
{ icon: GrJs, name: "GrJs" },
{ icon: GrKey, name: "GrKey" },
{ icon: GrKeyboard, name: "GrKeyboard" },
{ icon: GrLanguage, name: "GrLanguage" },
{ icon: GrLastfm, name: "GrLastfm" },
{ icon: GrLaunch, name: "GrLaunch" },
{ icon: GrLayer, name: "GrLayer" },
{ icon: GrLicense, name: "GrLicense" },
{ icon: GrLike, name: "GrLike" },
{ icon: GrLineChart, name: "GrLineChart" },
{ icon: GrLinkBottom, name: "GrLinkBottom" },
{ icon: GrLinkDown, name: "GrLinkDown" },
{ icon: GrLinkNext, name: "GrLinkNext" },
{ icon: GrLinkPrevious, name: "GrLinkPrevious" },
{ icon: GrLinkTop, name: "GrLinkTop" },
{ icon: GrLinkUp, name: "GrLinkUp" },
{ icon: GrLink, name: "GrLink" },
{ icon: GrLinkedinOption, name: "GrLinkedinOption" },
{ icon: GrLinkedin, name: "GrLinkedin" },
{ icon: GrList, name: "GrList" },
{ icon: GrLocal, name: "GrLocal" },
{ icon: GrLocationPin, name: "GrLocationPin" },
{ icon: GrLocation, name: "GrLocation" },
{ icon: GrLock, name: "GrLock" },
{ icon: GrLogin, name: "GrLogin" },
{ icon: GrLogout, name: "GrLogout" },
{ icon: GrLounge, name: "GrLounge" },
{ icon: GrMagic, name: "GrMagic" },
{ icon: GrMailOption, name: "GrMailOption" },
{ icon: GrMail, name: "GrMail" },
{ icon: GrMandriva, name: "GrMandriva" },
{ icon: GrManual, name: "GrManual" },
{ icon: GrMapLocation, name: "GrMapLocation" },
{ icon: GrMap, name: "GrMap" },
{ icon: GrMastercard, name: "GrMastercard" },
{ icon: GrMedium, name: "GrMedium" },
{ icon: GrMemory, name: "GrMemory" },
{ icon: GrMenu, name: "GrMenu" },
{ icon: GrMicrofocus, name: "GrMicrofocus" },
{ icon: GrMicrophone, name: "GrMicrophone" },
{ icon: GrMoney, name: "GrMoney" },
{ icon: GrMonitor, name: "GrMonitor" },
{ icon: GrMonospace, name: "GrMonospace" },
{ icon: GrMoon, name: "GrMoon" },
{ icon: GrMoreVertical, name: "GrMoreVertical" },
{ icon: GrMore, name: "GrMore" },
{ icon: GrMouse, name: "GrMouse" },
{ icon: GrMultimedia, name: "GrMultimedia" },
{ icon: GrMultiple, name: "GrMultiple" },
{ icon: GrMusic, name: "GrMusic" },
{ icon: GrMysql, name: "GrMysql" },
{ icon: GrNavigate, name: "GrNavigate" },
{ icon: GrNetworkDrive, name: "GrNetworkDrive" },
{ icon: GrNetwork, name: "GrNetwork" },
{ icon: GrNewWindow, name: "GrNewWindow" },
{ icon: GrNew, name: "GrNew" },
{ icon: GrNext, name: "GrNext" },
{ icon: GrNode, name: "GrNode" },
{ icon: GrNodes, name: "GrNodes" },
{ icon: GrNorton, name: "GrNorton" },
{ icon: GrNote, name: "GrNote" },
{ icon: GrNotes, name: "GrNotes" },
{ icon: GrNotification, name: "GrNotification" },
{ icon: GrNpm, name: "GrNpm" },
{ icon: GrObjectGroup, name: "GrObjectGroup" },
{ icon: GrObjectUngroup, name: "GrObjectUngroup" },
{ icon: GrOfflineStorage, name: "GrOfflineStorage" },
{ icon: GrOnedrive, name: "GrOnedrive" },
{ icon: GrOpera, name: "GrOpera" },
{ icon: GrOptimize, name: "GrOptimize" },
{ icon: GrOracle, name: "GrOracle" },
{ icon: GrOrderedList, name: "GrOrderedList" },
{ icon: GrOrganization, name: "GrOrganization" },
{ icon: GrOverview, name: "GrOverview" },
{ icon: GrPackage, name: "GrPackage" },
{ icon: GrPaint, name: "GrPaint" },
{ icon: GrPan, name: "GrPan" },
{ icon: GrPauseFill, name: "GrPauseFill" },
{ icon: GrPause, name: "GrPause" },
{ icon: GrPaypal, name: "GrPaypal" },
{ icon: GrPerformance, name: "GrPerformance" },
{ icon: GrPersonalComputer, name: "GrPersonalComputer" },
{ icon: GrPhoneFlip, name: "GrPhoneFlip" },
{ icon: GrPhoneHorizontal, name: "GrPhoneHorizontal" },
{ icon: GrPhoneVertical, name: "GrPhoneVertical" },
{ icon: GrPhone, name: "GrPhone" },
{ icon: GrPieChart, name: "GrPieChart" },
{ icon: GrPiedPiper, name: "GrPiedPiper" },
{ icon: GrPin, name: "GrPin" },
{ icon: GrPinterest, name: "GrPinterest" },
{ icon: GrPlan, name: "GrPlan" },
{ icon: GrPlayFill, name: "GrPlayFill" },
{ icon: GrPlay, name: "GrPlay" },
{ icon: GrPlug, name: "GrPlug" },
{ icon: GrPocket, name: "GrPocket" },
{ icon: GrPowerCycle, name: "GrPowerCycle" },
{ icon: GrPowerForceShutdown, name: "GrPowerForceShutdown" },
{ icon: GrPowerReset, name: "GrPowerReset" },
{ icon: GrPowerShutdown, name: "GrPowerShutdown" },
{ icon: GrPower, name: "GrPower" },
{ icon: GrPrevious, name: "GrPrevious" },
{ icon: GrPrint, name: "GrPrint" },
{ icon: GrProductHunt, name: "GrProductHunt" },
{ icon: GrProjects, name: "GrProjects" },
{ icon: GrQr, name: "GrQr" },
{ icon: GrRadialSelected, name: "GrRadialSelected" },
{ icon: GrRadial, name: "GrRadial" },
{ icon: GrRaspberry, name: "GrRaspberry" },
{ icon: GrReactjs, name: "GrReactjs" },
{ icon: GrReddit, name: "GrReddit" },
{ icon: GrRedhat, name: "GrRedhat" },
{ icon: GrRedo, name: "GrRedo" },
{ icon: GrRefresh, name: "GrRefresh" },
{ icon: GrResources, name: "GrResources" },
{ icon: GrRestaurant, name: "GrRestaurant" },
{ icon: GrRestroomMen, name: "GrRestroomMen" },
{ icon: GrRestroomWomen, name: "GrRestroomWomen" },
{ icon: GrRestroom, name: "GrRestroom" },
{ icon: GrResume, name: "GrResume" },
{ icon: GrReturn, name: "GrReturn" },
{ icon: GrRevert, name: "GrRevert" },
{ icon: GrRewind, name: "GrRewind" },
{ icon: GrRisk, name: "GrRisk" },
{ icon: GrRobot, name: "GrRobot" },
{ icon: GrRotateLeft, name: "GrRotateLeft" },
{ icon: GrRotateRight, name: "GrRotateRight" },
{ icon: GrRss, name: "GrRss" },
{ icon: GrRun, name: "GrRun" },
{ icon: GrSafariOption, name: "GrSafariOption" },
{ icon: GrSans, name: "GrSans" },
{ icon: GrSatellite, name: "GrSatellite" },
{ icon: GrSave, name: "GrSave" },
{ icon: GrScan, name: "GrScan" },
{ icon: GrScheduleNew, name: "GrScheduleNew" },
{ icon: GrSchedulePlay, name: "GrSchedulePlay" },
{ icon: GrSchedule, name: "GrSchedule" },
{ icon: GrSchedules, name: "GrSchedules" },
{ icon: GrSco, name: "GrSco" },
{ icon: GrScorecard, name: "GrScorecard" },
{ icon: GrScript, name: "GrScript" },
{ icon: GrSd, name: "GrSd" },
{ icon: GrSearchAdvanced, name: "GrSearchAdvanced" },
{ icon: GrSearch, name: "GrSearch" },
{ icon: GrSecure, name: "GrSecure" },
{ icon: GrSelect, name: "GrSelect" },
{ icon: GrSelection, name: "GrSelection" },
{ icon: GrSemantics, name: "GrSemantics" },
{ icon: GrSend, name: "GrSend" },
{ icon: GrServerCluster, name: "GrServerCluster" },
{ icon: GrServer, name: "GrServer" },
{ icon: GrServers, name: "GrServers" },
{ icon: GrServicePlay, name: "GrServicePlay" },
{ icon: GrServices, name: "GrServices" },
{ icon: GrSettingsOption, name: "GrSettingsOption" },
{ icon: GrShareOption, name: "GrShareOption" },
{ icon: GrShareRounded, name: "GrShareRounded" },
{ icon: GrShare, name: "GrShare" },
{ icon: GrShieldSecurity, name: "GrShieldSecurity" },
{ icon: GrShield, name: "GrShield" },
{ icon: GrShift, name: "GrShift" },
{ icon: GrShop, name: "GrShop" },
{ icon: GrSidebar, name: "GrSidebar" },
{ icon: GrSign, name: "GrSign" },
{ icon: GrSkype, name: "GrSkype" },
{ icon: GrSlack, name: "GrSlack" },
{ icon: GrSnapchat, name: "GrSnapchat" },
{ icon: GrSolaris, name: "GrSolaris" },
{ icon: GrSort, name: "GrSort" },
{ icon: GrSoundcloud, name: "GrSoundcloud" },
{ icon: GrSpa, name: "GrSpa" },
{ icon: GrSpectrum, name: "GrSpectrum" },
{ icon: GrSplit, name: "GrSplit" },
{ icon: GrSplits, name: "GrSplits" },
{ icon: GrSpotify, name: "GrSpotify" },
{ icon: GrSquare, name: "GrSquare" },
{ icon: GrStackOverflow, name: "GrStackOverflow" },
{ icon: GrStakeholder, name: "GrStakeholder" },
{ icon: GrStarHalf, name: "GrStarHalf" },
{ icon: GrStar, name: "GrStar" },
{ icon: GrStatusCriticalSmall, name: "GrStatusCriticalSmall" },
{ icon: GrStatusCritical, name: "GrStatusCritical" },
{ icon: GrStatusDisabledSmall, name: "GrStatusDisabledSmall" },
{ icon: GrStatusDisabled, name: "GrStatusDisabled" },
{ icon: GrStatusGoodSmall, name: "GrStatusGoodSmall" },
{ icon: GrStatusGood, name: "GrStatusGood" },
{ icon: GrStatusInfoSmall, name: "GrStatusInfoSmall" },
{ icon: GrStatusInfo, name: "GrStatusInfo" },
{ icon: GrStatusPlaceholderSmall, name: "GrStatusPlaceholderSmall" },
{ icon: GrStatusPlaceholder, name: "GrStatusPlaceholder" },
{ icon: GrStatusUnknownSmall, name: "GrStatusUnknownSmall" },
{ icon: GrStatusUnknown, name: "GrStatusUnknown" },
{ icon: GrStatusWarningSmall, name: "GrStatusWarningSmall" },
{ icon: GrStatusWarning, name: "GrStatusWarning" },
{ icon: GrStepsOption, name: "GrStepsOption" },
{ icon: GrSteps, name: "GrSteps" },
{ icon: GrStopFill, name: "GrStopFill" },
{ icon: GrStop, name: "GrStop" },
{ icon: GrStorage, name: "GrStorage" },
{ icon: GrStreetView, name: "GrStreetView" },
{ icon: GrStrikeThrough, name: "GrStrikeThrough" },
{ icon: GrStripe, name: "GrStripe" },
{ icon: GrSubscript, name: "GrSubscript" },
{ icon: GrSubtractCircle, name: "GrSubtractCircle" },
{ icon: GrSubtract, name: "GrSubtract" },
{ icon: GrSun, name: "GrSun" },
{ icon: GrSuperscript, name: "GrSuperscript" },
{ icon: GrSupport, name: "GrSupport" },
{ icon: GrSuse, name: "GrSuse" },
{ icon: GrSwift, name: "GrSwift" },
{ icon: GrSwim, name: "GrSwim" },
{ icon: GrSwitch, name: "GrSwitch" },
{ icon: GrSync, name: "GrSync" },
{ icon: GrSystem, name: "GrSystem" },
{ icon: GrTableAdd, name: "GrTableAdd" },
{ icon: GrTable, name: "GrTable" },
{ icon: GrTag, name: "GrTag" },
{ icon: GrTapeOption, name: "GrTapeOption" },
{ icon: GrTape, name: "GrTape" },
{ icon: GrTarget, name: "GrTarget" },
{ icon: GrTask, name: "GrTask" },
{ icon: GrTasks, name: "GrTasks" },
{ icon: GrTechnology, name: "GrTechnology" },
{ icon: GrTemplate, name: "GrTemplate" },
{ icon: GrTerminal, name: "GrTerminal" },
{ icon: GrTestDesktop, name: "GrTestDesktop" },
{ icon: GrTest, name: "GrTest" },
{ icon: GrTextAlignCenter, name: "GrTextAlignCenter" },
{ icon: GrTextAlignFull, name: "GrTextAlignFull" },
{ icon: GrTextAlignLeft, name: "GrTextAlignLeft" },
{ icon: GrTextAlignRight, name: "GrTextAlignRight" },
{ icon: GrTextWrap, name: "GrTextWrap" },
{ icon: GrThreats, name: "GrThreats" },
{ icon: GrThreeDEffects, name: "GrThreeDEffects" },
{ icon: GrThreeD, name: "GrThreeD" },
{ icon: GrTicket, name: "GrTicket" },
{ icon: GrTictok, name: "GrTictok" },
{ icon: GrTime, name: "GrTime" },
{ icon: GrTip, name: "GrTip" },
{ icon: GrToast, name: "GrToast" },
{ icon: GrTools, name: "GrTools" },
{ icon: GrTooltip, name: "GrTooltip" },
{ icon: GrTopCorner, name: "GrTopCorner" },
{ icon: GrTrain, name: "GrTrain" },
{ icon: GrTransaction, name: "GrTransaction" },
{ icon: GrTrash, name: "GrTrash" },
{ icon: GrTreeOption, name: "GrTreeOption" },
{ icon: GrTree, name: "GrTree" },
{ icon: GrTrigger, name: "GrTrigger" },
{ icon: GrTrophy, name: "GrTrophy" },
{ icon: GrTroubleshoot, name: "GrTroubleshoot" },
{ icon: GrTty, name: "GrTty" },
{ icon: GrTumblr, name: "GrTumblr" },
{ icon: GrTurbolinux, name: "GrTurbolinux" },
{ icon: GrTwitter, name: "GrTwitter" },
{ icon: GrUbuntu, name: "GrUbuntu" },
{ icon: GrUnderline, name: "GrUnderline" },
{ icon: GrUndo, name: "GrUndo" },
{ icon: GrUnlink, name: "GrUnlink" },
{ icon: GrUnlock, name: "GrUnlock" },
{ icon: GrUnorderedList, name: "GrUnorderedList" },
{ icon: GrUnsorted, name: "GrUnsorted" },
{ icon: GrUp, name: "GrUp" },
{ icon: GrUpdate, name: "GrUpdate" },
{ icon: GrUpgrade, name: "GrUpgrade" },
{ icon: GrUploadOption, name: "GrUploadOption" },
{ icon: GrUpload, name: "GrUpload" },
{ icon: GrUsbKey, name: "GrUsbKey" },
{ icon: GrUserAdd, name: "GrUserAdd" },
{ icon: GrUserAdmin, name: "GrUserAdmin" },
{ icon: GrUserExpert, name: "GrUserExpert" },
{ icon: GrUserFemale, name: "GrUserFemale" },
{ icon: GrUserManager, name: "GrUserManager" },
{ icon: GrUserNew, name: "GrUserNew" },
{ icon: GrUserPolice, name: "GrUserPolice" },
{ icon: GrUserSettings, name: "GrUserSettings" },
{ icon: GrUserWorker, name: "GrUserWorker" },
{ icon: GrUser, name: "GrUser" },
{ icon: GrValidate, name: "GrValidate" },
{ icon: GrVend, name: "GrVend" },
{ icon: GrVideo, name: "GrVideo" },
{ icon: GrView, name: "GrView" },
{ icon: GrVimeo, name: "GrVimeo" },
{ icon: GrVirtualMachine, name: "GrVirtualMachine" },
{ icon: GrVirtualStorage, name: "GrVirtualStorage" },
{ icon: GrVisa, name: "GrVisa" },
{ icon: GrVmMaintenance, name: "GrVmMaintenance" },
{ icon: GrVmware, name: "GrVmware" },
{ icon: GrVolumeControl, name: "GrVolumeControl" },
{ icon: GrVolumeLow, name: "GrVolumeLow" },
{ icon: GrVolumeMute, name: "GrVolumeMute" },
{ icon: GrVolume, name: "GrVolume" },
{ icon: GrVulnerability, name: "GrVulnerability" },
{ icon: GrWaypoint, name: "GrWaypoint" },
{ icon: GrWebcam, name: "GrWebcam" },
{ icon: GrWheelchairActive, name: "GrWheelchairActive" },
{ icon: GrWheelchair, name: "GrWheelchair" },
{ icon: GrWifiLow, name: "GrWifiLow" },
{ icon: GrWifiMedium, name: "GrWifiMedium" },
{ icon: GrWifiNone, name: "GrWifiNone" },
{ icon: GrWifi, name: "GrWifi" },
{ icon: GrWindowsLegacy, name: "GrWindowsLegacy" },
{ icon: GrWindows, name: "GrWindows" },
{ icon: GrWordpress, name: "GrWordpress" },
{ icon: GrWorkshop, name: "GrWorkshop" },
{ icon: GrYoga, name: "GrYoga" },
{ icon: GrYoutube, name: "GrYoutube" },
{ icon: GrZoomIn, name: "GrZoomIn" },
{ icon: GrZoomOut, name: "GrZoomOut" },
{ icon: GrZoom, name: "GrZoom" },
];

export default result