import {
FcAbout,
FcAcceptDatabase,
FcAddColumn,
FcAddDatabase,
FcAddImage,
FcAddRow,
FcAddressBook,
FcAdvance,
FcAdvertising,
FcAlarmClock,
FcAlphabeticalSortingAz,
FcAlphabeticalSortingZa,
FcAndroidOs,
FcAnswers,
FcApproval,
FcApprove,
FcAreaChart,
FcAssistant,
FcAudioFile,
FcAutomatic,
FcAutomotive,
FcBadDecision,
FcBarChart,
FcBbc,
FcBearish,
FcBinoculars,
FcBiohazard,
FcBiomass,
FcBiotech,
FcBookmark,
FcBriefcase,
FcBrokenLink,
FcBullish,
FcBusinessContact,
FcBusiness,
FcBusinessman,
FcBusinesswoman,
FcButtingIn,
FcCableRelease,
FcCalculator,
FcCalendar,
FcCallTransfer,
FcCallback,
FcCamcorderPro,
FcCamcorder,
FcCameraAddon,
FcCameraIdentification,
FcCamera,
FcCancel,
FcCandleSticks,
FcCapacitor,
FcCdLogo,
FcCellPhone,
FcChargeBattery,
FcCheckmark,
FcCircuit,
FcClapperboard,
FcClearFilters,
FcClock,
FcCloseUpMode,
FcCloth,
FcCollaboration,
FcCollapse,
FcCollect,
FcComboChart,
FcCommandLine,
FcComments,
FcCompactCamera,
FcConferenceCall,
FcContacts,
FcCopyleft,
FcCopyright,
FcCrystalOscillator,
FcCurrencyExchange,
FcCursor,
FcCustomerSupport,
FcDam,
FcDataBackup,
FcDataConfiguration,
FcDataEncryption,
FcDataProtection,
FcDataRecovery,
FcDataSheet,
FcDatabase,
FcDebian,
FcDebt,
FcDecision,
FcDeleteColumn,
FcDeleteDatabase,
FcDeleteRow,
FcDepartment,
FcDeployment,
FcDiploma1,
FcDiploma2,
FcDisapprove,
FcDisclaimer,
FcDislike,
FcDisplay,
FcDoNotInhale,
FcDoNotInsert,
FcDoNotMix,
FcDocument,
FcDonate,
FcDoughnutChart,
FcDownLeft,
FcDownRight,
FcDown,
FcDownload,
FcDribbble,
FcDvdLogo,
FcEditImage,
FcElectricalSensor,
FcElectricalThreshold,
FcElectricity,
FcElectroDevices,
FcElectronics,
FcEmptyBattery,
FcEmptyFilter,
FcEmptyTrash,
FcEndCall,
FcEngineering,
FcEnteringHeavenAlive,
FcExpand,
FcExpired,
FcExport,
FcExternal,
FcFactoryBreakdown,
FcFactory,
FcFaq,
FcFeedIn,
FcFeedback,
FcFile,
FcFilingCabinet,
FcFilledFilter,
FcFilmReel,
FcFilm,
FcFinePrint,
FcFlashAuto,
FcFlashOff,
FcFlashOn,
FcFlowChart,
FcFolder,
FcFrame,
FcFullBattery,
FcFullTrash,
FcGallery,
FcGenealogy,
FcGenericSortingAsc,
FcGenericSortingDesc,
FcGlobe,
FcGoodDecision,
FcGoogle,
FcGraduationCap,
FcGrid,
FcHeadset,
FcHeatMap,
FcHighBattery,
FcHighPriority,
FcHome,
FcIcons8Cup,
FcIdea,
FcImageFile,
FcImport,
FcInTransit,
FcInfo,
FcInspection,
FcIntegratedWebcam,
FcInternal,
FcInvite,
FcIpad,
FcIphone,
FcKey,
FcKindle,
FcLandscape,
FcLeave,
FcLeftDown,
FcLeftDown2,
FcLeftUp,
FcLeftUp2,
FcLeft,
FcLibrary,
FcLightAtTheEndOfTunnel,
FcLikePlaceholder,
FcLike,
FcLineChart,
FcLink,
FcLinux,
FcList,
FcLockLandscape,
FcLockPortrait,
FcLock,
FcLowBattery,
FcLowPriority,
FcMakeDecision,
FcManager,
FcMediumPriority,
FcMenu,
FcMiddleBattery,
FcMindMap,
FcMinus,
FcMissedCall,
FcMms,
FcMoneyTransfer,
FcMultipleCameras,
FcMultipleDevices,
FcMultipleInputs,
FcMultipleSmartphones,
FcMusic,
FcNegativeDynamic,
FcNeutralDecision,
FcNeutralTrading,
FcNews,
FcNext,
FcNfcSign,
FcNightLandscape,
FcNightPortrait,
FcNoIdea,
FcNoVideo,
FcNook,
FcNumericalSorting12,
FcNumericalSorting21,
FcOk,
FcOldTimeCamera,
FcOnlineSupport,
FcOpenedFolder,
FcOrgUnit,
FcOrganization,
FcOvertime,
FcPackage,
FcPaid,
FcPanorama,
FcParallelTasks,
FcPhoneAndroid,
FcPhone,
FcPhotoReel,
FcPicture,
FcPieChart,
FcPlanner,
FcPlus,
FcPodiumWithAudience,
FcPodiumWithSpeaker,
FcPodiumWithoutSpeaker,
FcPortraitMode,
FcPositiveDynamic,
FcPrevious,
FcPrint,
FcPrivacy,
FcProcess,
FcPuzzle,
FcQuestions,
FcRadarPlot,
FcRating,
FcRatings,
FcReadingEbook,
FcReading,
FcReddit,
FcRedo,
FcRefresh,
FcRegisteredTrademark,
FcRemoveImage,
FcReuse,
FcRightDown,
FcRightDown2,
FcRightUp,
FcRightUp2,
FcRight,
FcRotateCamera,
FcRotateToLandscape,
FcRotateToPortrait,
FcRuler,
FcRules,
FcSafe,
FcSalesPerformance,
FcScatterPlot,
FcSearch,
FcSelfServiceKiosk,
FcSelfie,
FcSerialTasks,
FcServiceMark,
FcServices,
FcSettings,
FcShare,
FcShipped,
FcShop,
FcSignature,
FcSimCardChip,
FcSimCard,
FcSlrBackSide,
FcSmartphoneTablet,
FcSms,
FcSoundRecordingCopyright,
FcSpeaker,
FcSportsMode,
FcStackOfPhotos,
FcStart,
FcStatistics,
FcSteam,
FcStumbleupon,
FcSupport,
FcSurvey,
FcSwitchCamera,
FcSynchronize,
FcTabletAndroid,
FcTemplate,
FcTimeline,
FcTodoList,
FcTouchscreenSmartphone,
FcTrademark,
FcTreeStructure,
FcTwoSmartphones,
FcUndo,
FcUnlock,
FcUpLeft,
FcUpRight,
FcUp,
FcUpload,
FcUsb,
FcVideoCall,
FcVideoFile,
FcVideoProjector,
FcViewDetails,
FcVip,
FcVlc,
FcVoicePresentation,
FcVoicemail,
FcWebcam,
FcWiFiLogo,
FcWikipedia,
FcWorkflow,
} from "react-icons/fc";

const result = [
{ icon: FcAbout, name: "FcAbout" },
{ icon: FcAcceptDatabase, name: "FcAcceptDatabase" },
{ icon: FcAddColumn, name: "FcAddColumn" },
{ icon: FcAddDatabase, name: "FcAddDatabase" },
{ icon: FcAddImage, name: "FcAddImage" },
{ icon: FcAddRow, name: "FcAddRow" },
{ icon: FcAddressBook, name: "FcAddressBook" },
{ icon: FcAdvance, name: "FcAdvance" },
{ icon: FcAdvertising, name: "FcAdvertising" },
{ icon: FcAlarmClock, name: "FcAlarmClock" },
{ icon: FcAlphabeticalSortingAz, name: "FcAlphabeticalSortingAz" },
{ icon: FcAlphabeticalSortingZa, name: "FcAlphabeticalSortingZa" },
{ icon: FcAndroidOs, name: "FcAndroidOs" },
{ icon: FcAnswers, name: "FcAnswers" },
{ icon: FcApproval, name: "FcApproval" },
{ icon: FcApprove, name: "FcApprove" },
{ icon: FcAreaChart, name: "FcAreaChart" },
{ icon: FcAssistant, name: "FcAssistant" },
{ icon: FcAudioFile, name: "FcAudioFile" },
{ icon: FcAutomatic, name: "FcAutomatic" },
{ icon: FcAutomotive, name: "FcAutomotive" },
{ icon: FcBadDecision, name: "FcBadDecision" },
{ icon: FcBarChart, name: "FcBarChart" },
{ icon: FcBbc, name: "FcBbc" },
{ icon: FcBearish, name: "FcBearish" },
{ icon: FcBinoculars, name: "FcBinoculars" },
{ icon: FcBiohazard, name: "FcBiohazard" },
{ icon: FcBiomass, name: "FcBiomass" },
{ icon: FcBiotech, name: "FcBiotech" },
{ icon: FcBookmark, name: "FcBookmark" },
{ icon: FcBriefcase, name: "FcBriefcase" },
{ icon: FcBrokenLink, name: "FcBrokenLink" },
{ icon: FcBullish, name: "FcBullish" },
{ icon: FcBusinessContact, name: "FcBusinessContact" },
{ icon: FcBusiness, name: "FcBusiness" },
{ icon: FcBusinessman, name: "FcBusinessman" },
{ icon: FcBusinesswoman, name: "FcBusinesswoman" },
{ icon: FcButtingIn, name: "FcButtingIn" },
{ icon: FcCableRelease, name: "FcCableRelease" },
{ icon: FcCalculator, name: "FcCalculator" },
{ icon: FcCalendar, name: "FcCalendar" },
{ icon: FcCallTransfer, name: "FcCallTransfer" },
{ icon: FcCallback, name: "FcCallback" },
{ icon: FcCamcorderPro, name: "FcCamcorderPro" },
{ icon: FcCamcorder, name: "FcCamcorder" },
{ icon: FcCameraAddon, name: "FcCameraAddon" },
{ icon: FcCameraIdentification, name: "FcCameraIdentification" },
{ icon: FcCamera, name: "FcCamera" },
{ icon: FcCancel, name: "FcCancel" },
{ icon: FcCandleSticks, name: "FcCandleSticks" },
{ icon: FcCapacitor, name: "FcCapacitor" },
{ icon: FcCdLogo, name: "FcCdLogo" },
{ icon: FcCellPhone, name: "FcCellPhone" },
{ icon: FcChargeBattery, name: "FcChargeBattery" },
{ icon: FcCheckmark, name: "FcCheckmark" },
{ icon: FcCircuit, name: "FcCircuit" },
{ icon: FcClapperboard, name: "FcClapperboard" },
{ icon: FcClearFilters, name: "FcClearFilters" },
{ icon: FcClock, name: "FcClock" },
{ icon: FcCloseUpMode, name: "FcCloseUpMode" },
{ icon: FcCloth, name: "FcCloth" },
{ icon: FcCollaboration, name: "FcCollaboration" },
{ icon: FcCollapse, name: "FcCollapse" },
{ icon: FcCollect, name: "FcCollect" },
{ icon: FcComboChart, name: "FcComboChart" },
{ icon: FcCommandLine, name: "FcCommandLine" },
{ icon: FcComments, name: "FcComments" },
{ icon: FcCompactCamera, name: "FcCompactCamera" },
{ icon: FcConferenceCall, name: "FcConferenceCall" },
{ icon: FcContacts, name: "FcContacts" },
{ icon: FcCopyleft, name: "FcCopyleft" },
{ icon: FcCopyright, name: "FcCopyright" },
{ icon: FcCrystalOscillator, name: "FcCrystalOscillator" },
{ icon: FcCurrencyExchange, name: "FcCurrencyExchange" },
{ icon: FcCursor, name: "FcCursor" },
{ icon: FcCustomerSupport, name: "FcCustomerSupport" },
{ icon: FcDam, name: "FcDam" },
{ icon: FcDataBackup, name: "FcDataBackup" },
{ icon: FcDataConfiguration, name: "FcDataConfiguration" },
{ icon: FcDataEncryption, name: "FcDataEncryption" },
{ icon: FcDataProtection, name: "FcDataProtection" },
{ icon: FcDataRecovery, name: "FcDataRecovery" },
{ icon: FcDataSheet, name: "FcDataSheet" },
{ icon: FcDatabase, name: "FcDatabase" },
{ icon: FcDebian, name: "FcDebian" },
{ icon: FcDebt, name: "FcDebt" },
{ icon: FcDecision, name: "FcDecision" },
{ icon: FcDeleteColumn, name: "FcDeleteColumn" },
{ icon: FcDeleteDatabase, name: "FcDeleteDatabase" },
{ icon: FcDeleteRow, name: "FcDeleteRow" },
{ icon: FcDepartment, name: "FcDepartment" },
{ icon: FcDeployment, name: "FcDeployment" },
{ icon: FcDiploma1, name: "FcDiploma1" },
{ icon: FcDiploma2, name: "FcDiploma2" },
{ icon: FcDisapprove, name: "FcDisapprove" },
{ icon: FcDisclaimer, name: "FcDisclaimer" },
{ icon: FcDislike, name: "FcDislike" },
{ icon: FcDisplay, name: "FcDisplay" },
{ icon: FcDoNotInhale, name: "FcDoNotInhale" },
{ icon: FcDoNotInsert, name: "FcDoNotInsert" },
{ icon: FcDoNotMix, name: "FcDoNotMix" },
{ icon: FcDocument, name: "FcDocument" },
{ icon: FcDonate, name: "FcDonate" },
{ icon: FcDoughnutChart, name: "FcDoughnutChart" },
{ icon: FcDownLeft, name: "FcDownLeft" },
{ icon: FcDownRight, name: "FcDownRight" },
{ icon: FcDown, name: "FcDown" },
{ icon: FcDownload, name: "FcDownload" },
{ icon: FcDribbble, name: "FcDribbble" },
{ icon: FcDvdLogo, name: "FcDvdLogo" },
{ icon: FcEditImage, name: "FcEditImage" },
{ icon: FcElectricalSensor, name: "FcElectricalSensor" },
{ icon: FcElectricalThreshold, name: "FcElectricalThreshold" },
{ icon: FcElectricity, name: "FcElectricity" },
{ icon: FcElectroDevices, name: "FcElectroDevices" },
{ icon: FcElectronics, name: "FcElectronics" },
{ icon: FcEmptyBattery, name: "FcEmptyBattery" },
{ icon: FcEmptyFilter, name: "FcEmptyFilter" },
{ icon: FcEmptyTrash, name: "FcEmptyTrash" },
{ icon: FcEndCall, name: "FcEndCall" },
{ icon: FcEngineering, name: "FcEngineering" },
{ icon: FcEnteringHeavenAlive, name: "FcEnteringHeavenAlive" },
{ icon: FcExpand, name: "FcExpand" },
{ icon: FcExpired, name: "FcExpired" },
{ icon: FcExport, name: "FcExport" },
{ icon: FcExternal, name: "FcExternal" },
{ icon: FcFactoryBreakdown, name: "FcFactoryBreakdown" },
{ icon: FcFactory, name: "FcFactory" },
{ icon: FcFaq, name: "FcFaq" },
{ icon: FcFeedIn, name: "FcFeedIn" },
{ icon: FcFeedback, name: "FcFeedback" },
{ icon: FcFile, name: "FcFile" },
{ icon: FcFilingCabinet, name: "FcFilingCabinet" },
{ icon: FcFilledFilter, name: "FcFilledFilter" },
{ icon: FcFilmReel, name: "FcFilmReel" },
{ icon: FcFilm, name: "FcFilm" },
{ icon: FcFinePrint, name: "FcFinePrint" },
{ icon: FcFlashAuto, name: "FcFlashAuto" },
{ icon: FcFlashOff, name: "FcFlashOff" },
{ icon: FcFlashOn, name: "FcFlashOn" },
{ icon: FcFlowChart, name: "FcFlowChart" },
{ icon: FcFolder, name: "FcFolder" },
{ icon: FcFrame, name: "FcFrame" },
{ icon: FcFullBattery, name: "FcFullBattery" },
{ icon: FcFullTrash, name: "FcFullTrash" },
{ icon: FcGallery, name: "FcGallery" },
{ icon: FcGenealogy, name: "FcGenealogy" },
{ icon: FcGenericSortingAsc, name: "FcGenericSortingAsc" },
{ icon: FcGenericSortingDesc, name: "FcGenericSortingDesc" },
{ icon: FcGlobe, name: "FcGlobe" },
{ icon: FcGoodDecision, name: "FcGoodDecision" },
{ icon: FcGoogle, name: "FcGoogle" },
{ icon: FcGraduationCap, name: "FcGraduationCap" },
{ icon: FcGrid, name: "FcGrid" },
{ icon: FcHeadset, name: "FcHeadset" },
{ icon: FcHeatMap, name: "FcHeatMap" },
{ icon: FcHighBattery, name: "FcHighBattery" },
{ icon: FcHighPriority, name: "FcHighPriority" },
{ icon: FcHome, name: "FcHome" },
{ icon: FcIcons8Cup, name: "FcIcons8Cup" },
{ icon: FcIdea, name: "FcIdea" },
{ icon: FcImageFile, name: "FcImageFile" },
{ icon: FcImport, name: "FcImport" },
{ icon: FcInTransit, name: "FcInTransit" },
{ icon: FcInfo, name: "FcInfo" },
{ icon: FcInspection, name: "FcInspection" },
{ icon: FcIntegratedWebcam, name: "FcIntegratedWebcam" },
{ icon: FcInternal, name: "FcInternal" },
{ icon: FcInvite, name: "FcInvite" },
{ icon: FcIpad, name: "FcIpad" },
{ icon: FcIphone, name: "FcIphone" },
{ icon: FcKey, name: "FcKey" },
{ icon: FcKindle, name: "FcKindle" },
{ icon: FcLandscape, name: "FcLandscape" },
{ icon: FcLeave, name: "FcLeave" },
{ icon: FcLeftDown, name: "FcLeftDown" },
{ icon: FcLeftDown2, name: "FcLeftDown2" },
{ icon: FcLeftUp, name: "FcLeftUp" },
{ icon: FcLeftUp2, name: "FcLeftUp2" },
{ icon: FcLeft, name: "FcLeft" },
{ icon: FcLibrary, name: "FcLibrary" },
{ icon: FcLightAtTheEndOfTunnel, name: "FcLightAtTheEndOfTunnel" },
{ icon: FcLikePlaceholder, name: "FcLikePlaceholder" },
{ icon: FcLike, name: "FcLike" },
{ icon: FcLineChart, name: "FcLineChart" },
{ icon: FcLink, name: "FcLink" },
{ icon: FcLinux, name: "FcLinux" },
{ icon: FcList, name: "FcList" },
{ icon: FcLockLandscape, name: "FcLockLandscape" },
{ icon: FcLockPortrait, name: "FcLockPortrait" },
{ icon: FcLock, name: "FcLock" },
{ icon: FcLowBattery, name: "FcLowBattery" },
{ icon: FcLowPriority, name: "FcLowPriority" },
{ icon: FcMakeDecision, name: "FcMakeDecision" },
{ icon: FcManager, name: "FcManager" },
{ icon: FcMediumPriority, name: "FcMediumPriority" },
{ icon: FcMenu, name: "FcMenu" },
{ icon: FcMiddleBattery, name: "FcMiddleBattery" },
{ icon: FcMindMap, name: "FcMindMap" },
{ icon: FcMinus, name: "FcMinus" },
{ icon: FcMissedCall, name: "FcMissedCall" },
{ icon: FcMms, name: "FcMms" },
{ icon: FcMoneyTransfer, name: "FcMoneyTransfer" },
{ icon: FcMultipleCameras, name: "FcMultipleCameras" },
{ icon: FcMultipleDevices, name: "FcMultipleDevices" },
{ icon: FcMultipleInputs, name: "FcMultipleInputs" },
{ icon: FcMultipleSmartphones, name: "FcMultipleSmartphones" },
{ icon: FcMusic, name: "FcMusic" },
{ icon: FcNegativeDynamic, name: "FcNegativeDynamic" },
{ icon: FcNeutralDecision, name: "FcNeutralDecision" },
{ icon: FcNeutralTrading, name: "FcNeutralTrading" },
{ icon: FcNews, name: "FcNews" },
{ icon: FcNext, name: "FcNext" },
{ icon: FcNfcSign, name: "FcNfcSign" },
{ icon: FcNightLandscape, name: "FcNightLandscape" },
{ icon: FcNightPortrait, name: "FcNightPortrait" },
{ icon: FcNoIdea, name: "FcNoIdea" },
{ icon: FcNoVideo, name: "FcNoVideo" },
{ icon: FcNook, name: "FcNook" },
{ icon: FcNumericalSorting12, name: "FcNumericalSorting12" },
{ icon: FcNumericalSorting21, name: "FcNumericalSorting21" },
{ icon: FcOk, name: "FcOk" },
{ icon: FcOldTimeCamera, name: "FcOldTimeCamera" },
{ icon: FcOnlineSupport, name: "FcOnlineSupport" },
{ icon: FcOpenedFolder, name: "FcOpenedFolder" },
{ icon: FcOrgUnit, name: "FcOrgUnit" },
{ icon: FcOrganization, name: "FcOrganization" },
{ icon: FcOvertime, name: "FcOvertime" },
{ icon: FcPackage, name: "FcPackage" },
{ icon: FcPaid, name: "FcPaid" },
{ icon: FcPanorama, name: "FcPanorama" },
{ icon: FcParallelTasks, name: "FcParallelTasks" },
{ icon: FcPhoneAndroid, name: "FcPhoneAndroid" },
{ icon: FcPhone, name: "FcPhone" },
{ icon: FcPhotoReel, name: "FcPhotoReel" },
{ icon: FcPicture, name: "FcPicture" },
{ icon: FcPieChart, name: "FcPieChart" },
{ icon: FcPlanner, name: "FcPlanner" },
{ icon: FcPlus, name: "FcPlus" },
{ icon: FcPodiumWithAudience, name: "FcPodiumWithAudience" },
{ icon: FcPodiumWithSpeaker, name: "FcPodiumWithSpeaker" },
{ icon: FcPodiumWithoutSpeaker, name: "FcPodiumWithoutSpeaker" },
{ icon: FcPortraitMode, name: "FcPortraitMode" },
{ icon: FcPositiveDynamic, name: "FcPositiveDynamic" },
{ icon: FcPrevious, name: "FcPrevious" },
{ icon: FcPrint, name: "FcPrint" },
{ icon: FcPrivacy, name: "FcPrivacy" },
{ icon: FcProcess, name: "FcProcess" },
{ icon: FcPuzzle, name: "FcPuzzle" },
{ icon: FcQuestions, name: "FcQuestions" },
{ icon: FcRadarPlot, name: "FcRadarPlot" },
{ icon: FcRating, name: "FcRating" },
{ icon: FcRatings, name: "FcRatings" },
{ icon: FcReadingEbook, name: "FcReadingEbook" },
{ icon: FcReading, name: "FcReading" },
{ icon: FcReddit, name: "FcReddit" },
{ icon: FcRedo, name: "FcRedo" },
{ icon: FcRefresh, name: "FcRefresh" },
{ icon: FcRegisteredTrademark, name: "FcRegisteredTrademark" },
{ icon: FcRemoveImage, name: "FcRemoveImage" },
{ icon: FcReuse, name: "FcReuse" },
{ icon: FcRightDown, name: "FcRightDown" },
{ icon: FcRightDown2, name: "FcRightDown2" },
{ icon: FcRightUp, name: "FcRightUp" },
{ icon: FcRightUp2, name: "FcRightUp2" },
{ icon: FcRight, name: "FcRight" },
{ icon: FcRotateCamera, name: "FcRotateCamera" },
{ icon: FcRotateToLandscape, name: "FcRotateToLandscape" },
{ icon: FcRotateToPortrait, name: "FcRotateToPortrait" },
{ icon: FcRuler, name: "FcRuler" },
{ icon: FcRules, name: "FcRules" },
{ icon: FcSafe, name: "FcSafe" },
{ icon: FcSalesPerformance, name: "FcSalesPerformance" },
{ icon: FcScatterPlot, name: "FcScatterPlot" },
{ icon: FcSearch, name: "FcSearch" },
{ icon: FcSelfServiceKiosk, name: "FcSelfServiceKiosk" },
{ icon: FcSelfie, name: "FcSelfie" },
{ icon: FcSerialTasks, name: "FcSerialTasks" },
{ icon: FcServiceMark, name: "FcServiceMark" },
{ icon: FcServices, name: "FcServices" },
{ icon: FcSettings, name: "FcSettings" },
{ icon: FcShare, name: "FcShare" },
{ icon: FcShipped, name: "FcShipped" },
{ icon: FcShop, name: "FcShop" },
{ icon: FcSignature, name: "FcSignature" },
{ icon: FcSimCardChip, name: "FcSimCardChip" },
{ icon: FcSimCard, name: "FcSimCard" },
{ icon: FcSlrBackSide, name: "FcSlrBackSide" },
{ icon: FcSmartphoneTablet, name: "FcSmartphoneTablet" },
{ icon: FcSms, name: "FcSms" },
{ icon: FcSoundRecordingCopyright, name: "FcSoundRecordingCopyright" },
{ icon: FcSpeaker, name: "FcSpeaker" },
{ icon: FcSportsMode, name: "FcSportsMode" },
{ icon: FcStackOfPhotos, name: "FcStackOfPhotos" },
{ icon: FcStart, name: "FcStart" },
{ icon: FcStatistics, name: "FcStatistics" },
{ icon: FcSteam, name: "FcSteam" },
{ icon: FcStumbleupon, name: "FcStumbleupon" },
{ icon: FcSupport, name: "FcSupport" },
{ icon: FcSurvey, name: "FcSurvey" },
{ icon: FcSwitchCamera, name: "FcSwitchCamera" },
{ icon: FcSynchronize, name: "FcSynchronize" },
{ icon: FcTabletAndroid, name: "FcTabletAndroid" },
{ icon: FcTemplate, name: "FcTemplate" },
{ icon: FcTimeline, name: "FcTimeline" },
{ icon: FcTodoList, name: "FcTodoList" },
{ icon: FcTouchscreenSmartphone, name: "FcTouchscreenSmartphone" },
{ icon: FcTrademark, name: "FcTrademark" },
{ icon: FcTreeStructure, name: "FcTreeStructure" },
{ icon: FcTwoSmartphones, name: "FcTwoSmartphones" },
{ icon: FcUndo, name: "FcUndo" },
{ icon: FcUnlock, name: "FcUnlock" },
{ icon: FcUpLeft, name: "FcUpLeft" },
{ icon: FcUpRight, name: "FcUpRight" },
{ icon: FcUp, name: "FcUp" },
{ icon: FcUpload, name: "FcUpload" },
{ icon: FcUsb, name: "FcUsb" },
{ icon: FcVideoCall, name: "FcVideoCall" },
{ icon: FcVideoFile, name: "FcVideoFile" },
{ icon: FcVideoProjector, name: "FcVideoProjector" },
{ icon: FcViewDetails, name: "FcViewDetails" },
{ icon: FcVip, name: "FcVip" },
{ icon: FcVlc, name: "FcVlc" },
{ icon: FcVoicePresentation, name: "FcVoicePresentation" },
{ icon: FcVoicemail, name: "FcVoicemail" },
{ icon: FcWebcam, name: "FcWebcam" },
{ icon: FcWiFiLogo, name: "FcWiFiLogo" },
{ icon: FcWikipedia, name: "FcWikipedia" },
{ icon: FcWorkflow, name: "FcWorkflow" },
];

export default result