import {
	FcAbout,
	FcAcceptDatabase,
	FcAddColumn,
	FcAddDatabase,
	FcAddImage,
	FcAddRow,
	FcAddressBook,
	FcAdvance,
	FcAdvertising,
	FcAlarmClock,
	FcAlphabeticalSortingAz,
	FcAlphabeticalSortingZa,
	FcAndroidOs,
	FcAnswers,
	FcApproval,
	FcApprove,
	FcAreaChart,
	FcAssistant,
	FcAudioFile,
	FcAutomatic,
	FcAutomotive,
	FcBadDecision,
	FcBarChart,
	FcBbc,
	FcBearish,
	FcBinoculars,
	FcBiohazard,
	FcBiomass,
	FcBiotech,
	FcBookmark,
	FcBriefcase,
	FcBrokenLink,
	FcBullish,
	FcBusinessContact,
	FcBusiness,
	FcBusinessman,
	FcBusinesswoman,
	FcButtingIn,
	FcCableRelease,
	FcCalculator,
	FcCalendar,
	FcCallTransfer,
	FcCallback,
	FcCamcorderPro,
	FcCamcorder,
	FcCameraAddon,
	FcCameraIdentification,
	FcCamera,
	FcCancel,
	FcCandleSticks,
	FcCapacitor,
	FcCdLogo,
	FcCellPhone,
	FcChargeBattery,
	FcCheckmark,
	FcCircuit,
	FcClapperboard,
	FcClearFilters,
	FcClock,
	FcCloseUpMode,
	FcCloth,
	FcCollaboration,
	FcCollapse,
	FcCollect,
	FcComboChart,
	FcCommandLine,
	FcComments,
	FcCompactCamera,
	FcConferenceCall,
	FcContacts,
	FcCopyleft,
	FcCopyright,
	FcCrystalOscillator,
	FcCurrencyExchange,
	FcCursor,
	FcCustomerSupport,
	FcDam,
	FcDataBackup,
	FcDataConfiguration,
	FcDataEncryption,
	FcDataProtection,
	FcDataRecovery,
	FcDataSheet,
	FcDatabase,
	FcDebian,
	FcDebt,
	FcDecision,
	FcDeleteColumn,
	FcDeleteDatabase,
	FcDeleteRow,
	FcDepartment,
	FcDeployment,
	FcDiploma1,
	FcDiploma2,
	FcDisapprove,
	FcDisclaimer,
	FcDislike,
	FcDisplay,
	FcDoNotInhale,
	FcDoNotInsert,
	FcDoNotMix,
	FcDocument,
	FcDonate,
	FcDoughnutChart,
	FcDownLeft,
	FcDownRight,
	FcDown,
	FcDownload,
	FcDribbble,
	FcDvdLogo,
	FcEditImage,
	FcElectricalSensor,
	FcElectricalThreshold,
	FcElectricity,
	FcElectroDevices,
	FcElectronics,
	FcEmptyBattery,
	FcEmptyFilter,
	FcEmptyTrash,
	FcEndCall,
	FcEngineering,
	FcEnteringHeavenAlive,
	FcExpand,
	FcExpired,
	FcExport,
	FcExternal,
	FcFactoryBreakdown,
	FcFactory,
	FcFaq,
	FcFeedIn,
	FcFeedback,
	FcFile,
	FcFilingCabinet,
	FcFilledFilter,
	FcFilmReel,
	FcFilm,
	FcFinePrint,
	FcFlashAuto,
	FcFlashOff,
	FcFlashOn,
	FcFlowChart,
	FcFolder,
	FcFrame,
	FcFullBattery,
	FcFullTrash,
	FcGallery,
	FcGenealogy,
	FcGenericSortingAsc,
	FcGenericSortingDesc,
	FcGlobe,
	FcGoodDecision,
	FcGoogle,
	FcGraduationCap,
	FcGrid,
	FcHeadset,
	FcHeatMap,
	FcHighBattery,
	FcHighPriority,
	FcHome,
	FcIcons8Cup,
	FcIdea,
	FcImageFile,
	FcImport,
	FcInTransit,
	FcInfo,
	FcInspection,
	FcIntegratedWebcam,
	FcInternal,
	FcInvite,
	FcIpad,
	FcIphone,
	FcKey,
	FcKindle,
	FcLandscape,
	FcLeave,
	FcLeftDown,
	FcLeftDown2,
	FcLeftUp,
	FcLeftUp2,
	FcLeft,
	FcLibrary,
	FcLightAtTheEndOfTunnel,
	FcLikePlaceholder,
	FcLike,
	FcLineChart,
	FcLink,
	FcLinux,
	FcList,
	FcLockLandscape,
	FcLockPortrait,
	FcLock,
	FcLowBattery,
	FcLowPriority,
	FcMakeDecision,
	FcManager,
	FcMediumPriority,
	FcMenu,
	FcMiddleBattery,
	FcMindMap,
	FcMinus,
	FcMissedCall,
	FcMms,
	FcMoneyTransfer,
	FcMultipleCameras,
	FcMultipleDevices,
	FcMultipleInputs,
	FcMultipleSmartphones,
	FcMusic,
	FcNegativeDynamic,
	FcNeutralDecision,
	FcNeutralTrading,
	FcNews,
	FcNext,
	FcNfcSign,
	FcNightLandscape,
	FcNightPortrait,
	FcNoIdea,
	FcNoVideo,
	FcNook,
	FcNumericalSorting12,
	FcNumericalSorting21,
	FcOk,
	FcOldTimeCamera,
	FcOnlineSupport,
	FcOpenedFolder,
	FcOrgUnit,
	FcOrganization,
	FcOvertime,
	FcPackage,
	FcPaid,
	FcPanorama,
	FcParallelTasks,
	FcPhoneAndroid,
	FcPhone,
	FcPhotoReel,
	FcPicture,
	FcPieChart,
	FcPlanner,
	FcPlus,
	FcPodiumWithAudience,
	FcPodiumWithSpeaker,
	FcPodiumWithoutSpeaker,
	FcPortraitMode,
	FcPositiveDynamic,
	FcPrevious,
	FcPrint,
	FcPrivacy,
	FcProcess,
	FcPuzzle,
	FcQuestions,
	FcRadarPlot,
	FcRating,
	FcRatings,
	FcReadingEbook,
	FcReading,
	FcReddit,
	FcRedo,
	FcRefresh,
	FcRegisteredTrademark,
	FcRemoveImage,
	FcReuse,
	FcRightDown,
	FcRightDown2,
	FcRightUp,
	FcRightUp2,
	FcRight,
	FcRotateCamera,
	FcRotateToLandscape,
	FcRotateToPortrait,
	FcRuler,
	FcRules,
	FcSafe,
	FcSalesPerformance,
	FcScatterPlot,
	FcSearch,
	FcSelfServiceKiosk,
	FcSelfie,
	FcSerialTasks,
	FcServiceMark,
	FcServices,
	FcSettings,
	FcShare,
	FcShipped,
	FcShop,
	FcSignature,
	FcSimCardChip,
	FcSimCard,
	FcSlrBackSide,
	FcSmartphoneTablet,
	FcSms,
	FcSoundRecordingCopyright,
	FcSpeaker,
	FcSportsMode,
	FcStackOfPhotos,
	FcStart,
	FcStatistics,
	FcSteam,
	FcStumbleupon,
	FcSupport,
	FcSurvey,
	FcSwitchCamera,
	FcSynchronize,
	FcTabletAndroid,
	FcTemplate,
	FcTimeline,
	FcTodoList,
	FcTouchscreenSmartphone,
	FcTrademark,
	FcTreeStructure,
	FcTwoSmartphones,
	FcUndo,
	FcUnlock,
	FcUpLeft,
	FcUpRight,
	FcUp,
	FcUpload,
	FcUsb,
	FcVideoCall,
	FcVideoFile,
	FcVideoProjector,
	FcViewDetails,
	FcVip,
	FcVlc,
	FcVoicePresentation,
	FcVoicemail,
	FcWebcam,
	FcWiFiLogo,
	FcWikipedia,
	FcWorkflow,
} from "react-icons/fc";

const result = [
	{ icon: FcAbout, name: "FcAbout", library: "fc" },
	{ icon: FcAcceptDatabase, name: "FcAcceptDatabase", library: "fc" },
	{ icon: FcAddColumn, name: "FcAddColumn", library: "fc" },
	{ icon: FcAddDatabase, name: "FcAddDatabase", library: "fc" },
	{ icon: FcAddImage, name: "FcAddImage", library: "fc" },
	{ icon: FcAddRow, name: "FcAddRow", library: "fc" },
	{ icon: FcAddressBook, name: "FcAddressBook", library: "fc" },
	{ icon: FcAdvance, name: "FcAdvance", library: "fc" },
	{ icon: FcAdvertising, name: "FcAdvertising", library: "fc" },
	{ icon: FcAlarmClock, name: "FcAlarmClock", library: "fc" },
	{ icon: FcAlphabeticalSortingAz, name: "FcAlphabeticalSortingAz", library: "fc" },
	{ icon: FcAlphabeticalSortingZa, name: "FcAlphabeticalSortingZa", library: "fc" },
	{ icon: FcAndroidOs, name: "FcAndroidOs", library: "fc" },
	{ icon: FcAnswers, name: "FcAnswers", library: "fc" },
	{ icon: FcApproval, name: "FcApproval", library: "fc" },
	{ icon: FcApprove, name: "FcApprove", library: "fc" },
	{ icon: FcAreaChart, name: "FcAreaChart", library: "fc" },
	{ icon: FcAssistant, name: "FcAssistant", library: "fc" },
	{ icon: FcAudioFile, name: "FcAudioFile", library: "fc" },
	{ icon: FcAutomatic, name: "FcAutomatic", library: "fc" },
	{ icon: FcAutomotive, name: "FcAutomotive", library: "fc" },
	{ icon: FcBadDecision, name: "FcBadDecision", library: "fc" },
	{ icon: FcBarChart, name: "FcBarChart", library: "fc" },
	{ icon: FcBbc, name: "FcBbc", library: "fc" },
	{ icon: FcBearish, name: "FcBearish", library: "fc" },
	{ icon: FcBinoculars, name: "FcBinoculars", library: "fc" },
	{ icon: FcBiohazard, name: "FcBiohazard", library: "fc" },
	{ icon: FcBiomass, name: "FcBiomass", library: "fc" },
	{ icon: FcBiotech, name: "FcBiotech", library: "fc" },
	{ icon: FcBookmark, name: "FcBookmark", library: "fc" },
	{ icon: FcBriefcase, name: "FcBriefcase", library: "fc" },
	{ icon: FcBrokenLink, name: "FcBrokenLink", library: "fc" },
	{ icon: FcBullish, name: "FcBullish", library: "fc" },
	{ icon: FcBusinessContact, name: "FcBusinessContact", library: "fc" },
	{ icon: FcBusiness, name: "FcBusiness", library: "fc" },
	{ icon: FcBusinessman, name: "FcBusinessman", library: "fc" },
	{ icon: FcBusinesswoman, name: "FcBusinesswoman", library: "fc" },
	{ icon: FcButtingIn, name: "FcButtingIn", library: "fc" },
	{ icon: FcCableRelease, name: "FcCableRelease", library: "fc" },
	{ icon: FcCalculator, name: "FcCalculator", library: "fc" },
	{ icon: FcCalendar, name: "FcCalendar", library: "fc" },
	{ icon: FcCallTransfer, name: "FcCallTransfer", library: "fc" },
	{ icon: FcCallback, name: "FcCallback", library: "fc" },
	{ icon: FcCamcorderPro, name: "FcCamcorderPro", library: "fc" },
	{ icon: FcCamcorder, name: "FcCamcorder", library: "fc" },
	{ icon: FcCameraAddon, name: "FcCameraAddon", library: "fc" },
	{ icon: FcCameraIdentification, name: "FcCameraIdentification", library: "fc" },
	{ icon: FcCamera, name: "FcCamera", library: "fc" },
	{ icon: FcCancel, name: "FcCancel", library: "fc" },
	{ icon: FcCandleSticks, name: "FcCandleSticks", library: "fc" },
	{ icon: FcCapacitor, name: "FcCapacitor", library: "fc" },
	{ icon: FcCdLogo, name: "FcCdLogo", library: "fc" },
	{ icon: FcCellPhone, name: "FcCellPhone", library: "fc" },
	{ icon: FcChargeBattery, name: "FcChargeBattery", library: "fc" },
	{ icon: FcCheckmark, name: "FcCheckmark", library: "fc" },
	{ icon: FcCircuit, name: "FcCircuit", library: "fc" },
	{ icon: FcClapperboard, name: "FcClapperboard", library: "fc" },
	{ icon: FcClearFilters, name: "FcClearFilters", library: "fc" },
	{ icon: FcClock, name: "FcClock", library: "fc" },
	{ icon: FcCloseUpMode, name: "FcCloseUpMode", library: "fc" },
	{ icon: FcCloth, name: "FcCloth", library: "fc" },
	{ icon: FcCollaboration, name: "FcCollaboration", library: "fc" },
	{ icon: FcCollapse, name: "FcCollapse", library: "fc" },
	{ icon: FcCollect, name: "FcCollect", library: "fc" },
	{ icon: FcComboChart, name: "FcComboChart", library: "fc" },
	{ icon: FcCommandLine, name: "FcCommandLine", library: "fc" },
	{ icon: FcComments, name: "FcComments", library: "fc" },
	{ icon: FcCompactCamera, name: "FcCompactCamera", library: "fc" },
	{ icon: FcConferenceCall, name: "FcConferenceCall", library: "fc" },
	{ icon: FcContacts, name: "FcContacts", library: "fc" },
	{ icon: FcCopyleft, name: "FcCopyleft", library: "fc" },
	{ icon: FcCopyright, name: "FcCopyright", library: "fc" },
	{ icon: FcCrystalOscillator, name: "FcCrystalOscillator", library: "fc" },
	{ icon: FcCurrencyExchange, name: "FcCurrencyExchange", library: "fc" },
	{ icon: FcCursor, name: "FcCursor", library: "fc" },
	{ icon: FcCustomerSupport, name: "FcCustomerSupport", library: "fc" },
	{ icon: FcDam, name: "FcDam", library: "fc" },
	{ icon: FcDataBackup, name: "FcDataBackup", library: "fc" },
	{ icon: FcDataConfiguration, name: "FcDataConfiguration", library: "fc" },
	{ icon: FcDataEncryption, name: "FcDataEncryption", library: "fc" },
	{ icon: FcDataProtection, name: "FcDataProtection", library: "fc" },
	{ icon: FcDataRecovery, name: "FcDataRecovery", library: "fc" },
	{ icon: FcDataSheet, name: "FcDataSheet", library: "fc" },
	{ icon: FcDatabase, name: "FcDatabase", library: "fc" },
	{ icon: FcDebian, name: "FcDebian", library: "fc" },
	{ icon: FcDebt, name: "FcDebt", library: "fc" },
	{ icon: FcDecision, name: "FcDecision", library: "fc" },
	{ icon: FcDeleteColumn, name: "FcDeleteColumn", library: "fc" },
	{ icon: FcDeleteDatabase, name: "FcDeleteDatabase", library: "fc" },
	{ icon: FcDeleteRow, name: "FcDeleteRow", library: "fc" },
	{ icon: FcDepartment, name: "FcDepartment", library: "fc" },
	{ icon: FcDeployment, name: "FcDeployment", library: "fc" },
	{ icon: FcDiploma1, name: "FcDiploma1", library: "fc" },
	{ icon: FcDiploma2, name: "FcDiploma2", library: "fc" },
	{ icon: FcDisapprove, name: "FcDisapprove", library: "fc" },
	{ icon: FcDisclaimer, name: "FcDisclaimer", library: "fc" },
	{ icon: FcDislike, name: "FcDislike", library: "fc" },
	{ icon: FcDisplay, name: "FcDisplay", library: "fc" },
	{ icon: FcDoNotInhale, name: "FcDoNotInhale", library: "fc" },
	{ icon: FcDoNotInsert, name: "FcDoNotInsert", library: "fc" },
	{ icon: FcDoNotMix, name: "FcDoNotMix", library: "fc" },
	{ icon: FcDocument, name: "FcDocument", library: "fc" },
	{ icon: FcDonate, name: "FcDonate", library: "fc" },
	{ icon: FcDoughnutChart, name: "FcDoughnutChart", library: "fc" },
	{ icon: FcDownLeft, name: "FcDownLeft", library: "fc" },
	{ icon: FcDownRight, name: "FcDownRight", library: "fc" },
	{ icon: FcDown, name: "FcDown", library: "fc" },
	{ icon: FcDownload, name: "FcDownload", library: "fc" },
	{ icon: FcDribbble, name: "FcDribbble", library: "fc" },
	{ icon: FcDvdLogo, name: "FcDvdLogo", library: "fc" },
	{ icon: FcEditImage, name: "FcEditImage", library: "fc" },
	{ icon: FcElectricalSensor, name: "FcElectricalSensor", library: "fc" },
	{ icon: FcElectricalThreshold, name: "FcElectricalThreshold", library: "fc" },
	{ icon: FcElectricity, name: "FcElectricity", library: "fc" },
	{ icon: FcElectroDevices, name: "FcElectroDevices", library: "fc" },
	{ icon: FcElectronics, name: "FcElectronics", library: "fc" },
	{ icon: FcEmptyBattery, name: "FcEmptyBattery", library: "fc" },
	{ icon: FcEmptyFilter, name: "FcEmptyFilter", library: "fc" },
	{ icon: FcEmptyTrash, name: "FcEmptyTrash", library: "fc" },
	{ icon: FcEndCall, name: "FcEndCall", library: "fc" },
	{ icon: FcEngineering, name: "FcEngineering", library: "fc" },
	{ icon: FcEnteringHeavenAlive, name: "FcEnteringHeavenAlive", library: "fc" },
	{ icon: FcExpand, name: "FcExpand", library: "fc" },
	{ icon: FcExpired, name: "FcExpired", library: "fc" },
	{ icon: FcExport, name: "FcExport", library: "fc" },
	{ icon: FcExternal, name: "FcExternal", library: "fc" },
	{ icon: FcFactoryBreakdown, name: "FcFactoryBreakdown", library: "fc" },
	{ icon: FcFactory, name: "FcFactory", library: "fc" },
	{ icon: FcFaq, name: "FcFaq", library: "fc" },
	{ icon: FcFeedIn, name: "FcFeedIn", library: "fc" },
	{ icon: FcFeedback, name: "FcFeedback", library: "fc" },
	{ icon: FcFile, name: "FcFile", library: "fc" },
	{ icon: FcFilingCabinet, name: "FcFilingCabinet", library: "fc" },
	{ icon: FcFilledFilter, name: "FcFilledFilter", library: "fc" },
	{ icon: FcFilmReel, name: "FcFilmReel", library: "fc" },
	{ icon: FcFilm, name: "FcFilm", library: "fc" },
	{ icon: FcFinePrint, name: "FcFinePrint", library: "fc" },
	{ icon: FcFlashAuto, name: "FcFlashAuto", library: "fc" },
	{ icon: FcFlashOff, name: "FcFlashOff", library: "fc" },
	{ icon: FcFlashOn, name: "FcFlashOn", library: "fc" },
	{ icon: FcFlowChart, name: "FcFlowChart", library: "fc" },
	{ icon: FcFolder, name: "FcFolder", library: "fc" },
	{ icon: FcFrame, name: "FcFrame", library: "fc" },
	{ icon: FcFullBattery, name: "FcFullBattery", library: "fc" },
	{ icon: FcFullTrash, name: "FcFullTrash", library: "fc" },
	{ icon: FcGallery, name: "FcGallery", library: "fc" },
	{ icon: FcGenealogy, name: "FcGenealogy", library: "fc" },
	{ icon: FcGenericSortingAsc, name: "FcGenericSortingAsc", library: "fc" },
	{ icon: FcGenericSortingDesc, name: "FcGenericSortingDesc", library: "fc" },
	{ icon: FcGlobe, name: "FcGlobe", library: "fc" },
	{ icon: FcGoodDecision, name: "FcGoodDecision", library: "fc" },
	{ icon: FcGoogle, name: "FcGoogle", library: "fc" },
	{ icon: FcGraduationCap, name: "FcGraduationCap", library: "fc" },
	{ icon: FcGrid, name: "FcGrid", library: "fc" },
	{ icon: FcHeadset, name: "FcHeadset", library: "fc" },
	{ icon: FcHeatMap, name: "FcHeatMap", library: "fc" },
	{ icon: FcHighBattery, name: "FcHighBattery", library: "fc" },
	{ icon: FcHighPriority, name: "FcHighPriority", library: "fc" },
	{ icon: FcHome, name: "FcHome", library: "fc" },
	{ icon: FcIcons8Cup, name: "FcIcons8Cup", library: "fc" },
	{ icon: FcIdea, name: "FcIdea", library: "fc" },
	{ icon: FcImageFile, name: "FcImageFile", library: "fc" },
	{ icon: FcImport, name: "FcImport", library: "fc" },
	{ icon: FcInTransit, name: "FcInTransit", library: "fc" },
	{ icon: FcInfo, name: "FcInfo", library: "fc" },
	{ icon: FcInspection, name: "FcInspection", library: "fc" },
	{ icon: FcIntegratedWebcam, name: "FcIntegratedWebcam", library: "fc" },
	{ icon: FcInternal, name: "FcInternal", library: "fc" },
	{ icon: FcInvite, name: "FcInvite", library: "fc" },
	{ icon: FcIpad, name: "FcIpad", library: "fc" },
	{ icon: FcIphone, name: "FcIphone", library: "fc" },
	{ icon: FcKey, name: "FcKey", library: "fc" },
	{ icon: FcKindle, name: "FcKindle", library: "fc" },
	{ icon: FcLandscape, name: "FcLandscape", library: "fc" },
	{ icon: FcLeave, name: "FcLeave", library: "fc" },
	{ icon: FcLeftDown, name: "FcLeftDown", library: "fc" },
	{ icon: FcLeftDown2, name: "FcLeftDown2", library: "fc" },
	{ icon: FcLeftUp, name: "FcLeftUp", library: "fc" },
	{ icon: FcLeftUp2, name: "FcLeftUp2", library: "fc" },
	{ icon: FcLeft, name: "FcLeft", library: "fc" },
	{ icon: FcLibrary, name: "FcLibrary", library: "fc" },
	{ icon: FcLightAtTheEndOfTunnel, name: "FcLightAtTheEndOfTunnel", library: "fc" },
	{ icon: FcLikePlaceholder, name: "FcLikePlaceholder", library: "fc" },
	{ icon: FcLike, name: "FcLike", library: "fc" },
	{ icon: FcLineChart, name: "FcLineChart", library: "fc" },
	{ icon: FcLink, name: "FcLink", library: "fc" },
	{ icon: FcLinux, name: "FcLinux", library: "fc" },
	{ icon: FcList, name: "FcList", library: "fc" },
	{ icon: FcLockLandscape, name: "FcLockLandscape", library: "fc" },
	{ icon: FcLockPortrait, name: "FcLockPortrait", library: "fc" },
	{ icon: FcLock, name: "FcLock", library: "fc" },
	{ icon: FcLowBattery, name: "FcLowBattery", library: "fc" },
	{ icon: FcLowPriority, name: "FcLowPriority", library: "fc" },
	{ icon: FcMakeDecision, name: "FcMakeDecision", library: "fc" },
	{ icon: FcManager, name: "FcManager", library: "fc" },
	{ icon: FcMediumPriority, name: "FcMediumPriority", library: "fc" },
	{ icon: FcMenu, name: "FcMenu", library: "fc" },
	{ icon: FcMiddleBattery, name: "FcMiddleBattery", library: "fc" },
	{ icon: FcMindMap, name: "FcMindMap", library: "fc" },
	{ icon: FcMinus, name: "FcMinus", library: "fc" },
	{ icon: FcMissedCall, name: "FcMissedCall", library: "fc" },
	{ icon: FcMms, name: "FcMms", library: "fc" },
	{ icon: FcMoneyTransfer, name: "FcMoneyTransfer", library: "fc" },
	{ icon: FcMultipleCameras, name: "FcMultipleCameras", library: "fc" },
	{ icon: FcMultipleDevices, name: "FcMultipleDevices", library: "fc" },
	{ icon: FcMultipleInputs, name: "FcMultipleInputs", library: "fc" },
	{ icon: FcMultipleSmartphones, name: "FcMultipleSmartphones", library: "fc" },
	{ icon: FcMusic, name: "FcMusic", library: "fc" },
	{ icon: FcNegativeDynamic, name: "FcNegativeDynamic", library: "fc" },
	{ icon: FcNeutralDecision, name: "FcNeutralDecision", library: "fc" },
	{ icon: FcNeutralTrading, name: "FcNeutralTrading", library: "fc" },
	{ icon: FcNews, name: "FcNews", library: "fc" },
	{ icon: FcNext, name: "FcNext", library: "fc" },
	{ icon: FcNfcSign, name: "FcNfcSign", library: "fc" },
	{ icon: FcNightLandscape, name: "FcNightLandscape", library: "fc" },
	{ icon: FcNightPortrait, name: "FcNightPortrait", library: "fc" },
	{ icon: FcNoIdea, name: "FcNoIdea", library: "fc" },
	{ icon: FcNoVideo, name: "FcNoVideo", library: "fc" },
	{ icon: FcNook, name: "FcNook", library: "fc" },
	{ icon: FcNumericalSorting12, name: "FcNumericalSorting12", library: "fc" },
	{ icon: FcNumericalSorting21, name: "FcNumericalSorting21", library: "fc" },
	{ icon: FcOk, name: "FcOk", library: "fc" },
	{ icon: FcOldTimeCamera, name: "FcOldTimeCamera", library: "fc" },
	{ icon: FcOnlineSupport, name: "FcOnlineSupport", library: "fc" },
	{ icon: FcOpenedFolder, name: "FcOpenedFolder", library: "fc" },
	{ icon: FcOrgUnit, name: "FcOrgUnit", library: "fc" },
	{ icon: FcOrganization, name: "FcOrganization", library: "fc" },
	{ icon: FcOvertime, name: "FcOvertime", library: "fc" },
	{ icon: FcPackage, name: "FcPackage", library: "fc" },
	{ icon: FcPaid, name: "FcPaid", library: "fc" },
	{ icon: FcPanorama, name: "FcPanorama", library: "fc" },
	{ icon: FcParallelTasks, name: "FcParallelTasks", library: "fc" },
	{ icon: FcPhoneAndroid, name: "FcPhoneAndroid", library: "fc" },
	{ icon: FcPhone, name: "FcPhone", library: "fc" },
	{ icon: FcPhotoReel, name: "FcPhotoReel", library: "fc" },
	{ icon: FcPicture, name: "FcPicture", library: "fc" },
	{ icon: FcPieChart, name: "FcPieChart", library: "fc" },
	{ icon: FcPlanner, name: "FcPlanner", library: "fc" },
	{ icon: FcPlus, name: "FcPlus", library: "fc" },
	{ icon: FcPodiumWithAudience, name: "FcPodiumWithAudience", library: "fc" },
	{ icon: FcPodiumWithSpeaker, name: "FcPodiumWithSpeaker", library: "fc" },
	{ icon: FcPodiumWithoutSpeaker, name: "FcPodiumWithoutSpeaker", library: "fc" },
	{ icon: FcPortraitMode, name: "FcPortraitMode", library: "fc" },
	{ icon: FcPositiveDynamic, name: "FcPositiveDynamic", library: "fc" },
	{ icon: FcPrevious, name: "FcPrevious", library: "fc" },
	{ icon: FcPrint, name: "FcPrint", library: "fc" },
	{ icon: FcPrivacy, name: "FcPrivacy", library: "fc" },
	{ icon: FcProcess, name: "FcProcess", library: "fc" },
	{ icon: FcPuzzle, name: "FcPuzzle", library: "fc" },
	{ icon: FcQuestions, name: "FcQuestions", library: "fc" },
	{ icon: FcRadarPlot, name: "FcRadarPlot", library: "fc" },
	{ icon: FcRating, name: "FcRating", library: "fc" },
	{ icon: FcRatings, name: "FcRatings", library: "fc" },
	{ icon: FcReadingEbook, name: "FcReadingEbook", library: "fc" },
	{ icon: FcReading, name: "FcReading", library: "fc" },
	{ icon: FcReddit, name: "FcReddit", library: "fc" },
	{ icon: FcRedo, name: "FcRedo", library: "fc" },
	{ icon: FcRefresh, name: "FcRefresh", library: "fc" },
	{ icon: FcRegisteredTrademark, name: "FcRegisteredTrademark", library: "fc" },
	{ icon: FcRemoveImage, name: "FcRemoveImage", library: "fc" },
	{ icon: FcReuse, name: "FcReuse", library: "fc" },
	{ icon: FcRightDown, name: "FcRightDown", library: "fc" },
	{ icon: FcRightDown2, name: "FcRightDown2", library: "fc" },
	{ icon: FcRightUp, name: "FcRightUp", library: "fc" },
	{ icon: FcRightUp2, name: "FcRightUp2", library: "fc" },
	{ icon: FcRight, name: "FcRight", library: "fc" },
	{ icon: FcRotateCamera, name: "FcRotateCamera", library: "fc" },
	{ icon: FcRotateToLandscape, name: "FcRotateToLandscape", library: "fc" },
	{ icon: FcRotateToPortrait, name: "FcRotateToPortrait", library: "fc" },
	{ icon: FcRuler, name: "FcRuler", library: "fc" },
	{ icon: FcRules, name: "FcRules", library: "fc" },
	{ icon: FcSafe, name: "FcSafe", library: "fc" },
	{ icon: FcSalesPerformance, name: "FcSalesPerformance", library: "fc" },
	{ icon: FcScatterPlot, name: "FcScatterPlot", library: "fc" },
	{ icon: FcSearch, name: "FcSearch", library: "fc" },
	{ icon: FcSelfServiceKiosk, name: "FcSelfServiceKiosk", library: "fc" },
	{ icon: FcSelfie, name: "FcSelfie", library: "fc" },
	{ icon: FcSerialTasks, name: "FcSerialTasks", library: "fc" },
	{ icon: FcServiceMark, name: "FcServiceMark", library: "fc" },
	{ icon: FcServices, name: "FcServices", library: "fc" },
	{ icon: FcSettings, name: "FcSettings", library: "fc" },
	{ icon: FcShare, name: "FcShare", library: "fc" },
	{ icon: FcShipped, name: "FcShipped", library: "fc" },
	{ icon: FcShop, name: "FcShop", library: "fc" },
	{ icon: FcSignature, name: "FcSignature", library: "fc" },
	{ icon: FcSimCardChip, name: "FcSimCardChip", library: "fc" },
	{ icon: FcSimCard, name: "FcSimCard", library: "fc" },
	{ icon: FcSlrBackSide, name: "FcSlrBackSide", library: "fc" },
	{ icon: FcSmartphoneTablet, name: "FcSmartphoneTablet", library: "fc" },
	{ icon: FcSms, name: "FcSms", library: "fc" },
	{ icon: FcSoundRecordingCopyright, name: "FcSoundRecordingCopyright", library: "fc" },
	{ icon: FcSpeaker, name: "FcSpeaker", library: "fc" },
	{ icon: FcSportsMode, name: "FcSportsMode", library: "fc" },
	{ icon: FcStackOfPhotos, name: "FcStackOfPhotos", library: "fc" },
	{ icon: FcStart, name: "FcStart", library: "fc" },
	{ icon: FcStatistics, name: "FcStatistics", library: "fc" },
	{ icon: FcSteam, name: "FcSteam", library: "fc" },
	{ icon: FcStumbleupon, name: "FcStumbleupon", library: "fc" },
	{ icon: FcSupport, name: "FcSupport", library: "fc" },
	{ icon: FcSurvey, name: "FcSurvey", library: "fc" },
	{ icon: FcSwitchCamera, name: "FcSwitchCamera", library: "fc" },
	{ icon: FcSynchronize, name: "FcSynchronize", library: "fc" },
	{ icon: FcTabletAndroid, name: "FcTabletAndroid", library: "fc" },
	{ icon: FcTemplate, name: "FcTemplate", library: "fc" },
	{ icon: FcTimeline, name: "FcTimeline", library: "fc" },
	{ icon: FcTodoList, name: "FcTodoList", library: "fc" },
	{ icon: FcTouchscreenSmartphone, name: "FcTouchscreenSmartphone", library: "fc" },
	{ icon: FcTrademark, name: "FcTrademark", library: "fc" },
	{ icon: FcTreeStructure, name: "FcTreeStructure", library: "fc" },
	{ icon: FcTwoSmartphones, name: "FcTwoSmartphones", library: "fc" },
	{ icon: FcUndo, name: "FcUndo", library: "fc" },
	{ icon: FcUnlock, name: "FcUnlock", library: "fc" },
	{ icon: FcUpLeft, name: "FcUpLeft", library: "fc" },
	{ icon: FcUpRight, name: "FcUpRight", library: "fc" },
	{ icon: FcUp, name: "FcUp", library: "fc" },
	{ icon: FcUpload, name: "FcUpload", library: "fc" },
	{ icon: FcUsb, name: "FcUsb", library: "fc" },
	{ icon: FcVideoCall, name: "FcVideoCall", library: "fc" },
	{ icon: FcVideoFile, name: "FcVideoFile", library: "fc" },
	{ icon: FcVideoProjector, name: "FcVideoProjector", library: "fc" },
	{ icon: FcViewDetails, name: "FcViewDetails", library: "fc" },
	{ icon: FcVip, name: "FcVip", library: "fc" },
	{ icon: FcVlc, name: "FcVlc", library: "fc" },
	{ icon: FcVoicePresentation, name: "FcVoicePresentation", library: "fc" },
	{ icon: FcVoicemail, name: "FcVoicemail", library: "fc" },
	{ icon: FcWebcam, name: "FcWebcam", library: "fc" },
	{ icon: FcWiFiLogo, name: "FcWiFiLogo", library: "fc" },
	{ icon: FcWikipedia, name: "FcWikipedia", library: "fc" },
	{ icon: FcWorkflow, name: "FcWorkflow", library: "fc" },
];

export default result;
