import {
	ImHome,
	ImHome2,
	ImHome3,
	ImOffice,
	ImNewspaper,
	ImPencil,
	ImPencil2,
	ImQuill,
	ImPen,
	ImBlog,
	ImEyedropper,
	ImDroplet,
	ImPaintFormat,
	ImImage,
	ImImages,
	ImCamera,
	ImHeadphones,
	ImMusic,
	ImPlay,
	ImFilm,
	ImVideoCamera,
	ImDice,
	ImPacman,
	ImSpades,
	ImClubs,
	ImDiamonds,
	ImBullhorn,
	ImConnection,
	ImPodcast,
	ImFeed,
	ImMic,
	ImBook,
	ImBooks,
	ImLibrary,
	ImFileText,
	ImProfile,
	ImFileEmpty,
	ImFilesEmpty,
	ImFileText2,
	ImFilePicture,
	ImFileMusic,
	ImFilePlay,
	ImFileVideo,
	ImFileZip,
	ImCopy,
	ImPaste,
	ImStack,
	ImFolder,
	ImFolderOpen,
	ImFolderPlus,
	ImFolderMinus,
	ImFolderDownload,
	ImFolderUpload,
	ImPriceTag,
	ImPriceTags,
	ImBarcode,
	ImQrcode,
	ImTicket,
	ImCart,
	ImCoinDollar,
	ImCoinEuro,
	ImCoinPound,
	ImCoinYen,
	ImCreditCard,
	ImCalculator,
	ImLifebuoy,
	ImPhone,
	ImPhoneHangUp,
	ImAddressBook,
	ImEnvelop,
	ImPushpin,
	ImLocation,
	ImLocation2,
	ImCompass,
	ImCompass2,
	ImMap,
	ImMap2,
	ImHistory,
	ImClock,
	ImClock2,
	ImAlarm,
	ImBell,
	ImStopwatch,
	ImCalendar,
	ImPrinter,
	ImKeyboard,
	ImDisplay,
	ImLaptop,
	ImMobile,
	ImMobile2,
	ImTablet,
	ImTv,
	ImDrawer,
	ImDrawer2,
	ImBoxAdd,
	ImBoxRemove,
	ImDownload,
	ImUpload,
	ImFloppyDisk,
	ImDrive,
	ImDatabase,
	ImUndo,
	ImRedo,
	ImUndo2,
	ImRedo2,
	ImForward,
	ImReply,
	ImBubble,
	ImBubbles,
	ImBubbles2,
	ImBubble2,
	ImBubbles3,
	ImBubbles4,
	ImUser,
	ImUsers,
	ImUserPlus,
	ImUserMinus,
	ImUserCheck,
	ImUserTie,
	ImQuotesLeft,
	ImQuotesRight,
	ImHourGlass,
	ImSpinner,
	ImSpinner2,
	ImSpinner3,
	ImSpinner4,
	ImSpinner5,
	ImSpinner6,
	ImSpinner7,
	ImSpinner8,
	ImSpinner9,
	ImSpinner10,
	ImSpinner11,
	ImBinoculars,
	ImSearch,
	ImZoomIn,
	ImZoomOut,
	ImEnlarge,
	ImShrink,
	ImEnlarge2,
	ImShrink2,
	ImKey,
	ImKey2,
	ImLock,
	ImUnlocked,
	ImWrench,
	ImEqualizer,
	ImEqualizer2,
	ImCog,
	ImCogs,
	ImHammer,
	ImMagicWand,
	ImAidKit,
	ImBug,
	ImPieChart,
	ImStatsDots,
	ImStatsBars,
	ImStatsBars2,
	ImTrophy,
	ImGift,
	ImGlass,
	ImGlass2,
	ImMug,
	ImSpoonKnife,
	ImLeaf,
	ImRocket,
	ImMeter,
	ImMeter2,
	ImHammer2,
	ImFire,
	ImLab,
	ImMagnet,
	ImBin,
	ImBin2,
	ImBriefcase,
	ImAirplane,
	ImTruck,
	ImRoad,
	ImAccessibility,
	ImTarget,
	ImShield,
	ImPower,
	ImSwitch,
	ImPowerCord,
	ImClipboard,
	ImListNumbered,
	ImList,
	ImList2,
	ImTree,
	ImMenu,
	ImMenu2,
	ImMenu3,
	ImMenu4,
	ImCloud,
	ImCloudDownload,
	ImCloudUpload,
	ImCloudCheck,
	ImDownload2,
	ImUpload2,
	ImDownload3,
	ImUpload3,
	ImSphere,
	ImEarth,
	ImLink,
	ImFlag,
	ImAttachment,
	ImEye,
	ImEyePlus,
	ImEyeMinus,
	ImEyeBlocked,
	ImBookmark,
	ImBookmarks,
	ImSun,
	ImContrast,
	ImBrightnessContrast,
	ImStarEmpty,
	ImStarHalf,
	ImStarFull,
	ImHeart,
	ImHeartBroken,
	ImMan,
	ImWoman,
	ImManWoman,
	ImHappy,
	ImHappy2,
	ImSmile,
	ImSmile2,
	ImTongue,
	ImTongue2,
	ImSad,
	ImSad2,
	ImWink,
	ImWink2,
	ImGrin,
	ImGrin2,
	ImCool,
	ImCool2,
	ImAngry,
	ImAngry2,
	ImEvil,
	ImEvil2,
	ImShocked,
	ImShocked2,
	ImBaffled,
	ImBaffled2,
	ImConfused,
	ImConfused2,
	ImNeutral,
	ImNeutral2,
	ImHipster,
	ImHipster2,
	ImWondering,
	ImWondering2,
	ImSleepy,
	ImSleepy2,
	ImFrustrated,
	ImFrustrated2,
	ImCrying,
	ImCrying2,
	ImPointUp,
	ImPointRight,
	ImPointDown,
	ImPointLeft,
	ImWarning,
	ImNotification,
	ImQuestion,
	ImPlus,
	ImMinus,
	ImInfo,
	ImCancelCircle,
	ImBlocked,
	ImCross,
	ImCheckmark,
	ImCheckmark2,
	ImSpellCheck,
	ImEnter,
	ImExit,
	ImPlay2,
	ImPause,
	ImStop,
	ImPrevious,
	ImNext,
	ImBackward,
	ImForward2,
	ImPlay3,
	ImPause2,
	ImStop2,
	ImBackward2,
	ImForward3,
	ImFirst,
	ImLast,
	ImPrevious2,
	ImNext2,
	ImEject,
	ImVolumeHigh,
	ImVolumeMedium,
	ImVolumeLow,
	ImVolumeMute,
	ImVolumeMute2,
	ImVolumeIncrease,
	ImVolumeDecrease,
	ImLoop,
	ImLoop2,
	ImInfinite,
	ImShuffle,
	ImArrowUpLeft,
	ImArrowUp,
	ImArrowUpRight,
	ImArrowRight,
	ImArrowDownRight,
	ImArrowDown,
	ImArrowDownLeft,
	ImArrowLeft,
	ImArrowUpLeft2,
	ImArrowUp2,
	ImArrowUpRight2,
	ImArrowRight2,
	ImArrowDownRight2,
	ImArrowDown2,
	ImArrowDownLeft2,
	ImArrowLeft2,
	ImCircleUp,
	ImCircleRight,
	ImCircleDown,
	ImCircleLeft,
	ImTab,
	ImMoveUp,
	ImMoveDown,
	ImSortAlphaAsc,
	ImSortAlphaDesc,
	ImSortNumericAsc,
	ImSortNumbericDesc,
	ImSortAmountAsc,
	ImSortAmountDesc,
	ImCommand,
	ImShift,
	ImCtrl,
	ImOpt,
	ImCheckboxChecked,
	ImCheckboxUnchecked,
	ImRadioChecked,
	ImRadioChecked2,
	ImRadioUnchecked,
	ImCrop,
	ImMakeGroup,
	ImUngroup,
	ImScissors,
	ImFilter,
	ImFont,
	ImLigature,
	ImLigature2,
	ImTextHeight,
	ImTextWidth,
	ImFontSize,
	ImBold,
	ImUnderline,
	ImItalic,
	ImStrikethrough,
	ImOmega,
	ImSigma,
	ImPageBreak,
	ImSuperscript,
	ImSubscript,
	ImSuperscript2,
	ImSubscript2,
	ImTextColor,
	ImPagebreak,
	ImClearFormatting,
	ImTable,
	ImTable2,
	ImInsertTemplate,
	ImPilcrow,
	ImLtr,
	ImRtl,
	ImSection,
	ImParagraphLeft,
	ImParagraphCenter,
	ImParagraphRight,
	ImParagraphJustify,
	ImIndentIncrease,
	ImIndentDecrease,
	ImShare,
	ImNewTab,
	ImEmbed,
	ImEmbed2,
	ImTerminal,
	ImShare2,
	ImMail,
	ImMail2,
	ImMail3,
	ImMail4,
	ImAmazon,
	ImGoogle,
	ImGoogle2,
	ImGoogle3,
	ImGooglePlus,
	ImGooglePlus2,
	ImGooglePlus3,
	ImHangouts,
	ImGoogleDrive,
	ImFacebook,
	ImFacebook2,
	ImInstagram,
	ImWhatsapp,
	ImSpotify,
	ImTelegram,
	ImTwitter,
	ImVine,
	ImVk,
	ImRenren,
	ImSinaWeibo,
	ImRss,
	ImRss2,
	ImYoutube,
	ImYoutube2,
	ImTwitch,
	ImVimeo,
	ImVimeo2,
	ImLanyrd,
	ImFlickr,
	ImFlickr2,
	ImFlickr3,
	ImFlickr4,
	ImDribbble,
	ImBehance,
	ImBehance2,
	ImDeviantart,
	Im500Px,
	ImSteam,
	ImSteam2,
	ImDropbox,
	ImOnedrive,
	ImGithub,
	ImNpm,
	ImBasecamp,
	ImTrello,
	ImWordpress,
	ImJoomla,
	ImEllo,
	ImBlogger,
	ImBlogger2,
	ImTumblr,
	ImTumblr2,
	ImYahoo,
	ImYahoo2,
	ImTux,
	ImAppleinc,
	ImFinder,
	ImAndroid,
	ImWindows,
	ImWindows8,
	ImSoundcloud,
	ImSoundcloud2,
	ImSkype,
	ImReddit,
	ImHackernews,
	ImWikipedia,
	ImLinkedin,
	ImLinkedin2,
	ImLastfm,
	ImLastfm2,
	ImDelicious,
	ImStumbleupon,
	ImStumbleupon2,
	ImStackoverflow,
	ImPinterest,
	ImPinterest2,
	ImXing,
	ImXing2,
	ImFlattr,
	ImFoursquare,
	ImYelp,
	ImPaypal,
	ImChrome,
	ImFirefox,
	ImIe,
	ImEdge,
	ImSafari,
	ImOpera,
	ImFilePdf,
	ImFileOpenoffice,
	ImFileWord,
	ImFileExcel,
	ImLibreoffice,
	ImHtmlFive,
	ImHtmlFive2,
	ImCss3,
	ImGit,
	ImCodepen,
	ImSvg,
	ImIcoMoon,
} from "react-icons/im";

const result = [
	{ icon: ImHome, name: "ImHome", library: "im" },
	{ icon: ImHome2, name: "ImHome2", library: "im" },
	{ icon: ImHome3, name: "ImHome3", library: "im" },
	{ icon: ImOffice, name: "ImOffice", library: "im" },
	{ icon: ImNewspaper, name: "ImNewspaper", library: "im" },
	{ icon: ImPencil, name: "ImPencil", library: "im" },
	{ icon: ImPencil2, name: "ImPencil2", library: "im" },
	{ icon: ImQuill, name: "ImQuill", library: "im" },
	{ icon: ImPen, name: "ImPen", library: "im" },
	{ icon: ImBlog, name: "ImBlog", library: "im" },
	{ icon: ImEyedropper, name: "ImEyedropper", library: "im" },
	{ icon: ImDroplet, name: "ImDroplet", library: "im" },
	{ icon: ImPaintFormat, name: "ImPaintFormat", library: "im" },
	{ icon: ImImage, name: "ImImage", library: "im" },
	{ icon: ImImages, name: "ImImages", library: "im" },
	{ icon: ImCamera, name: "ImCamera", library: "im" },
	{ icon: ImHeadphones, name: "ImHeadphones", library: "im" },
	{ icon: ImMusic, name: "ImMusic", library: "im" },
	{ icon: ImPlay, name: "ImPlay", library: "im" },
	{ icon: ImFilm, name: "ImFilm", library: "im" },
	{ icon: ImVideoCamera, name: "ImVideoCamera", library: "im" },
	{ icon: ImDice, name: "ImDice", library: "im" },
	{ icon: ImPacman, name: "ImPacman", library: "im" },
	{ icon: ImSpades, name: "ImSpades", library: "im" },
	{ icon: ImClubs, name: "ImClubs", library: "im" },
	{ icon: ImDiamonds, name: "ImDiamonds", library: "im" },
	{ icon: ImBullhorn, name: "ImBullhorn", library: "im" },
	{ icon: ImConnection, name: "ImConnection", library: "im" },
	{ icon: ImPodcast, name: "ImPodcast", library: "im" },
	{ icon: ImFeed, name: "ImFeed", library: "im" },
	{ icon: ImMic, name: "ImMic", library: "im" },
	{ icon: ImBook, name: "ImBook", library: "im" },
	{ icon: ImBooks, name: "ImBooks", library: "im" },
	{ icon: ImLibrary, name: "ImLibrary", library: "im" },
	{ icon: ImFileText, name: "ImFileText", library: "im" },
	{ icon: ImProfile, name: "ImProfile", library: "im" },
	{ icon: ImFileEmpty, name: "ImFileEmpty", library: "im" },
	{ icon: ImFilesEmpty, name: "ImFilesEmpty", library: "im" },
	{ icon: ImFileText2, name: "ImFileText2", library: "im" },
	{ icon: ImFilePicture, name: "ImFilePicture", library: "im" },
	{ icon: ImFileMusic, name: "ImFileMusic", library: "im" },
	{ icon: ImFilePlay, name: "ImFilePlay", library: "im" },
	{ icon: ImFileVideo, name: "ImFileVideo", library: "im" },
	{ icon: ImFileZip, name: "ImFileZip", library: "im" },
	{ icon: ImCopy, name: "ImCopy", library: "im" },
	{ icon: ImPaste, name: "ImPaste", library: "im" },
	{ icon: ImStack, name: "ImStack", library: "im" },
	{ icon: ImFolder, name: "ImFolder", library: "im" },
	{ icon: ImFolderOpen, name: "ImFolderOpen", library: "im" },
	{ icon: ImFolderPlus, name: "ImFolderPlus", library: "im" },
	{ icon: ImFolderMinus, name: "ImFolderMinus", library: "im" },
	{ icon: ImFolderDownload, name: "ImFolderDownload", library: "im" },
	{ icon: ImFolderUpload, name: "ImFolderUpload", library: "im" },
	{ icon: ImPriceTag, name: "ImPriceTag", library: "im" },
	{ icon: ImPriceTags, name: "ImPriceTags", library: "im" },
	{ icon: ImBarcode, name: "ImBarcode", library: "im" },
	{ icon: ImQrcode, name: "ImQrcode", library: "im" },
	{ icon: ImTicket, name: "ImTicket", library: "im" },
	{ icon: ImCart, name: "ImCart", library: "im" },
	{ icon: ImCoinDollar, name: "ImCoinDollar", library: "im" },
	{ icon: ImCoinEuro, name: "ImCoinEuro", library: "im" },
	{ icon: ImCoinPound, name: "ImCoinPound", library: "im" },
	{ icon: ImCoinYen, name: "ImCoinYen", library: "im" },
	{ icon: ImCreditCard, name: "ImCreditCard", library: "im" },
	{ icon: ImCalculator, name: "ImCalculator", library: "im" },
	{ icon: ImLifebuoy, name: "ImLifebuoy", library: "im" },
	{ icon: ImPhone, name: "ImPhone", library: "im" },
	{ icon: ImPhoneHangUp, name: "ImPhoneHangUp", library: "im" },
	{ icon: ImAddressBook, name: "ImAddressBook", library: "im" },
	{ icon: ImEnvelop, name: "ImEnvelop", library: "im" },
	{ icon: ImPushpin, name: "ImPushpin", library: "im" },
	{ icon: ImLocation, name: "ImLocation", library: "im" },
	{ icon: ImLocation2, name: "ImLocation2", library: "im" },
	{ icon: ImCompass, name: "ImCompass", library: "im" },
	{ icon: ImCompass2, name: "ImCompass2", library: "im" },
	{ icon: ImMap, name: "ImMap", library: "im" },
	{ icon: ImMap2, name: "ImMap2", library: "im" },
	{ icon: ImHistory, name: "ImHistory", library: "im" },
	{ icon: ImClock, name: "ImClock", library: "im" },
	{ icon: ImClock2, name: "ImClock2", library: "im" },
	{ icon: ImAlarm, name: "ImAlarm", library: "im" },
	{ icon: ImBell, name: "ImBell", library: "im" },
	{ icon: ImStopwatch, name: "ImStopwatch", library: "im" },
	{ icon: ImCalendar, name: "ImCalendar", library: "im" },
	{ icon: ImPrinter, name: "ImPrinter", library: "im" },
	{ icon: ImKeyboard, name: "ImKeyboard", library: "im" },
	{ icon: ImDisplay, name: "ImDisplay", library: "im" },
	{ icon: ImLaptop, name: "ImLaptop", library: "im" },
	{ icon: ImMobile, name: "ImMobile", library: "im" },
	{ icon: ImMobile2, name: "ImMobile2", library: "im" },
	{ icon: ImTablet, name: "ImTablet", library: "im" },
	{ icon: ImTv, name: "ImTv", library: "im" },
	{ icon: ImDrawer, name: "ImDrawer", library: "im" },
	{ icon: ImDrawer2, name: "ImDrawer2", library: "im" },
	{ icon: ImBoxAdd, name: "ImBoxAdd", library: "im" },
	{ icon: ImBoxRemove, name: "ImBoxRemove", library: "im" },
	{ icon: ImDownload, name: "ImDownload", library: "im" },
	{ icon: ImUpload, name: "ImUpload", library: "im" },
	{ icon: ImFloppyDisk, name: "ImFloppyDisk", library: "im" },
	{ icon: ImDrive, name: "ImDrive", library: "im" },
	{ icon: ImDatabase, name: "ImDatabase", library: "im" },
	{ icon: ImUndo, name: "ImUndo", library: "im" },
	{ icon: ImRedo, name: "ImRedo", library: "im" },
	{ icon: ImUndo2, name: "ImUndo2", library: "im" },
	{ icon: ImRedo2, name: "ImRedo2", library: "im" },
	{ icon: ImForward, name: "ImForward", library: "im" },
	{ icon: ImReply, name: "ImReply", library: "im" },
	{ icon: ImBubble, name: "ImBubble", library: "im" },
	{ icon: ImBubbles, name: "ImBubbles", library: "im" },
	{ icon: ImBubbles2, name: "ImBubbles2", library: "im" },
	{ icon: ImBubble2, name: "ImBubble2", library: "im" },
	{ icon: ImBubbles3, name: "ImBubbles3", library: "im" },
	{ icon: ImBubbles4, name: "ImBubbles4", library: "im" },
	{ icon: ImUser, name: "ImUser", library: "im" },
	{ icon: ImUsers, name: "ImUsers", library: "im" },
	{ icon: ImUserPlus, name: "ImUserPlus", library: "im" },
	{ icon: ImUserMinus, name: "ImUserMinus", library: "im" },
	{ icon: ImUserCheck, name: "ImUserCheck", library: "im" },
	{ icon: ImUserTie, name: "ImUserTie", library: "im" },
	{ icon: ImQuotesLeft, name: "ImQuotesLeft", library: "im" },
	{ icon: ImQuotesRight, name: "ImQuotesRight", library: "im" },
	{ icon: ImHourGlass, name: "ImHourGlass", library: "im" },
	{ icon: ImSpinner, name: "ImSpinner", library: "im" },
	{ icon: ImSpinner2, name: "ImSpinner2", library: "im" },
	{ icon: ImSpinner3, name: "ImSpinner3", library: "im" },
	{ icon: ImSpinner4, name: "ImSpinner4", library: "im" },
	{ icon: ImSpinner5, name: "ImSpinner5", library: "im" },
	{ icon: ImSpinner6, name: "ImSpinner6", library: "im" },
	{ icon: ImSpinner7, name: "ImSpinner7", library: "im" },
	{ icon: ImSpinner8, name: "ImSpinner8", library: "im" },
	{ icon: ImSpinner9, name: "ImSpinner9", library: "im" },
	{ icon: ImSpinner10, name: "ImSpinner10", library: "im" },
	{ icon: ImSpinner11, name: "ImSpinner11", library: "im" },
	{ icon: ImBinoculars, name: "ImBinoculars", library: "im" },
	{ icon: ImSearch, name: "ImSearch", library: "im" },
	{ icon: ImZoomIn, name: "ImZoomIn", library: "im" },
	{ icon: ImZoomOut, name: "ImZoomOut", library: "im" },
	{ icon: ImEnlarge, name: "ImEnlarge", library: "im" },
	{ icon: ImShrink, name: "ImShrink", library: "im" },
	{ icon: ImEnlarge2, name: "ImEnlarge2", library: "im" },
	{ icon: ImShrink2, name: "ImShrink2", library: "im" },
	{ icon: ImKey, name: "ImKey", library: "im" },
	{ icon: ImKey2, name: "ImKey2", library: "im" },
	{ icon: ImLock, name: "ImLock", library: "im" },
	{ icon: ImUnlocked, name: "ImUnlocked", library: "im" },
	{ icon: ImWrench, name: "ImWrench", library: "im" },
	{ icon: ImEqualizer, name: "ImEqualizer", library: "im" },
	{ icon: ImEqualizer2, name: "ImEqualizer2", library: "im" },
	{ icon: ImCog, name: "ImCog", library: "im" },
	{ icon: ImCogs, name: "ImCogs", library: "im" },
	{ icon: ImHammer, name: "ImHammer", library: "im" },
	{ icon: ImMagicWand, name: "ImMagicWand", library: "im" },
	{ icon: ImAidKit, name: "ImAidKit", library: "im" },
	{ icon: ImBug, name: "ImBug", library: "im" },
	{ icon: ImPieChart, name: "ImPieChart", library: "im" },
	{ icon: ImStatsDots, name: "ImStatsDots", library: "im" },
	{ icon: ImStatsBars, name: "ImStatsBars", library: "im" },
	{ icon: ImStatsBars2, name: "ImStatsBars2", library: "im" },
	{ icon: ImTrophy, name: "ImTrophy", library: "im" },
	{ icon: ImGift, name: "ImGift", library: "im" },
	{ icon: ImGlass, name: "ImGlass", library: "im" },
	{ icon: ImGlass2, name: "ImGlass2", library: "im" },
	{ icon: ImMug, name: "ImMug", library: "im" },
	{ icon: ImSpoonKnife, name: "ImSpoonKnife", library: "im" },
	{ icon: ImLeaf, name: "ImLeaf", library: "im" },
	{ icon: ImRocket, name: "ImRocket", library: "im" },
	{ icon: ImMeter, name: "ImMeter", library: "im" },
	{ icon: ImMeter2, name: "ImMeter2", library: "im" },
	{ icon: ImHammer2, name: "ImHammer2", library: "im" },
	{ icon: ImFire, name: "ImFire", library: "im" },
	{ icon: ImLab, name: "ImLab", library: "im" },
	{ icon: ImMagnet, name: "ImMagnet", library: "im" },
	{ icon: ImBin, name: "ImBin", library: "im" },
	{ icon: ImBin2, name: "ImBin2", library: "im" },
	{ icon: ImBriefcase, name: "ImBriefcase", library: "im" },
	{ icon: ImAirplane, name: "ImAirplane", library: "im" },
	{ icon: ImTruck, name: "ImTruck", library: "im" },
	{ icon: ImRoad, name: "ImRoad", library: "im" },
	{ icon: ImAccessibility, name: "ImAccessibility", library: "im" },
	{ icon: ImTarget, name: "ImTarget", library: "im" },
	{ icon: ImShield, name: "ImShield", library: "im" },
	{ icon: ImPower, name: "ImPower", library: "im" },
	{ icon: ImSwitch, name: "ImSwitch", library: "im" },
	{ icon: ImPowerCord, name: "ImPowerCord", library: "im" },
	{ icon: ImClipboard, name: "ImClipboard", library: "im" },
	{ icon: ImListNumbered, name: "ImListNumbered", library: "im" },
	{ icon: ImList, name: "ImList", library: "im" },
	{ icon: ImList2, name: "ImList2", library: "im" },
	{ icon: ImTree, name: "ImTree", library: "im" },
	{ icon: ImMenu, name: "ImMenu", library: "im" },
	{ icon: ImMenu2, name: "ImMenu2", library: "im" },
	{ icon: ImMenu3, name: "ImMenu3", library: "im" },
	{ icon: ImMenu4, name: "ImMenu4", library: "im" },
	{ icon: ImCloud, name: "ImCloud", library: "im" },
	{ icon: ImCloudDownload, name: "ImCloudDownload", library: "im" },
	{ icon: ImCloudUpload, name: "ImCloudUpload", library: "im" },
	{ icon: ImCloudCheck, name: "ImCloudCheck", library: "im" },
	{ icon: ImDownload2, name: "ImDownload2", library: "im" },
	{ icon: ImUpload2, name: "ImUpload2", library: "im" },
	{ icon: ImDownload3, name: "ImDownload3", library: "im" },
	{ icon: ImUpload3, name: "ImUpload3", library: "im" },
	{ icon: ImSphere, name: "ImSphere", library: "im" },
	{ icon: ImEarth, name: "ImEarth", library: "im" },
	{ icon: ImLink, name: "ImLink", library: "im" },
	{ icon: ImFlag, name: "ImFlag", library: "im" },
	{ icon: ImAttachment, name: "ImAttachment", library: "im" },
	{ icon: ImEye, name: "ImEye", library: "im" },
	{ icon: ImEyePlus, name: "ImEyePlus", library: "im" },
	{ icon: ImEyeMinus, name: "ImEyeMinus", library: "im" },
	{ icon: ImEyeBlocked, name: "ImEyeBlocked", library: "im" },
	{ icon: ImBookmark, name: "ImBookmark", library: "im" },
	{ icon: ImBookmarks, name: "ImBookmarks", library: "im" },
	{ icon: ImSun, name: "ImSun", library: "im" },
	{ icon: ImContrast, name: "ImContrast", library: "im" },
	{ icon: ImBrightnessContrast, name: "ImBrightnessContrast", library: "im" },
	{ icon: ImStarEmpty, name: "ImStarEmpty", library: "im" },
	{ icon: ImStarHalf, name: "ImStarHalf", library: "im" },
	{ icon: ImStarFull, name: "ImStarFull", library: "im" },
	{ icon: ImHeart, name: "ImHeart", library: "im" },
	{ icon: ImHeartBroken, name: "ImHeartBroken", library: "im" },
	{ icon: ImMan, name: "ImMan", library: "im" },
	{ icon: ImWoman, name: "ImWoman", library: "im" },
	{ icon: ImManWoman, name: "ImManWoman", library: "im" },
	{ icon: ImHappy, name: "ImHappy", library: "im" },
	{ icon: ImHappy2, name: "ImHappy2", library: "im" },
	{ icon: ImSmile, name: "ImSmile", library: "im" },
	{ icon: ImSmile2, name: "ImSmile2", library: "im" },
	{ icon: ImTongue, name: "ImTongue", library: "im" },
	{ icon: ImTongue2, name: "ImTongue2", library: "im" },
	{ icon: ImSad, name: "ImSad", library: "im" },
	{ icon: ImSad2, name: "ImSad2", library: "im" },
	{ icon: ImWink, name: "ImWink", library: "im" },
	{ icon: ImWink2, name: "ImWink2", library: "im" },
	{ icon: ImGrin, name: "ImGrin", library: "im" },
	{ icon: ImGrin2, name: "ImGrin2", library: "im" },
	{ icon: ImCool, name: "ImCool", library: "im" },
	{ icon: ImCool2, name: "ImCool2", library: "im" },
	{ icon: ImAngry, name: "ImAngry", library: "im" },
	{ icon: ImAngry2, name: "ImAngry2", library: "im" },
	{ icon: ImEvil, name: "ImEvil", library: "im" },
	{ icon: ImEvil2, name: "ImEvil2", library: "im" },
	{ icon: ImShocked, name: "ImShocked", library: "im" },
	{ icon: ImShocked2, name: "ImShocked2", library: "im" },
	{ icon: ImBaffled, name: "ImBaffled", library: "im" },
	{ icon: ImBaffled2, name: "ImBaffled2", library: "im" },
	{ icon: ImConfused, name: "ImConfused", library: "im" },
	{ icon: ImConfused2, name: "ImConfused2", library: "im" },
	{ icon: ImNeutral, name: "ImNeutral", library: "im" },
	{ icon: ImNeutral2, name: "ImNeutral2", library: "im" },
	{ icon: ImHipster, name: "ImHipster", library: "im" },
	{ icon: ImHipster2, name: "ImHipster2", library: "im" },
	{ icon: ImWondering, name: "ImWondering", library: "im" },
	{ icon: ImWondering2, name: "ImWondering2", library: "im" },
	{ icon: ImSleepy, name: "ImSleepy", library: "im" },
	{ icon: ImSleepy2, name: "ImSleepy2", library: "im" },
	{ icon: ImFrustrated, name: "ImFrustrated", library: "im" },
	{ icon: ImFrustrated2, name: "ImFrustrated2", library: "im" },
	{ icon: ImCrying, name: "ImCrying", library: "im" },
	{ icon: ImCrying2, name: "ImCrying2", library: "im" },
	{ icon: ImPointUp, name: "ImPointUp", library: "im" },
	{ icon: ImPointRight, name: "ImPointRight", library: "im" },
	{ icon: ImPointDown, name: "ImPointDown", library: "im" },
	{ icon: ImPointLeft, name: "ImPointLeft", library: "im" },
	{ icon: ImWarning, name: "ImWarning", library: "im" },
	{ icon: ImNotification, name: "ImNotification", library: "im" },
	{ icon: ImQuestion, name: "ImQuestion", library: "im" },
	{ icon: ImPlus, name: "ImPlus", library: "im" },
	{ icon: ImMinus, name: "ImMinus", library: "im" },
	{ icon: ImInfo, name: "ImInfo", library: "im" },
	{ icon: ImCancelCircle, name: "ImCancelCircle", library: "im" },
	{ icon: ImBlocked, name: "ImBlocked", library: "im" },
	{ icon: ImCross, name: "ImCross", library: "im" },
	{ icon: ImCheckmark, name: "ImCheckmark", library: "im" },
	{ icon: ImCheckmark2, name: "ImCheckmark2", library: "im" },
	{ icon: ImSpellCheck, name: "ImSpellCheck", library: "im" },
	{ icon: ImEnter, name: "ImEnter", library: "im" },
	{ icon: ImExit, name: "ImExit", library: "im" },
	{ icon: ImPlay2, name: "ImPlay2", library: "im" },
	{ icon: ImPause, name: "ImPause", library: "im" },
	{ icon: ImStop, name: "ImStop", library: "im" },
	{ icon: ImPrevious, name: "ImPrevious", library: "im" },
	{ icon: ImNext, name: "ImNext", library: "im" },
	{ icon: ImBackward, name: "ImBackward", library: "im" },
	{ icon: ImForward2, name: "ImForward2", library: "im" },
	{ icon: ImPlay3, name: "ImPlay3", library: "im" },
	{ icon: ImPause2, name: "ImPause2", library: "im" },
	{ icon: ImStop2, name: "ImStop2", library: "im" },
	{ icon: ImBackward2, name: "ImBackward2", library: "im" },
	{ icon: ImForward3, name: "ImForward3", library: "im" },
	{ icon: ImFirst, name: "ImFirst", library: "im" },
	{ icon: ImLast, name: "ImLast", library: "im" },
	{ icon: ImPrevious2, name: "ImPrevious2", library: "im" },
	{ icon: ImNext2, name: "ImNext2", library: "im" },
	{ icon: ImEject, name: "ImEject", library: "im" },
	{ icon: ImVolumeHigh, name: "ImVolumeHigh", library: "im" },
	{ icon: ImVolumeMedium, name: "ImVolumeMedium", library: "im" },
	{ icon: ImVolumeLow, name: "ImVolumeLow", library: "im" },
	{ icon: ImVolumeMute, name: "ImVolumeMute", library: "im" },
	{ icon: ImVolumeMute2, name: "ImVolumeMute2", library: "im" },
	{ icon: ImVolumeIncrease, name: "ImVolumeIncrease", library: "im" },
	{ icon: ImVolumeDecrease, name: "ImVolumeDecrease", library: "im" },
	{ icon: ImLoop, name: "ImLoop", library: "im" },
	{ icon: ImLoop2, name: "ImLoop2", library: "im" },
	{ icon: ImInfinite, name: "ImInfinite", library: "im" },
	{ icon: ImShuffle, name: "ImShuffle", library: "im" },
	{ icon: ImArrowUpLeft, name: "ImArrowUpLeft", library: "im" },
	{ icon: ImArrowUp, name: "ImArrowUp", library: "im" },
	{ icon: ImArrowUpRight, name: "ImArrowUpRight", library: "im" },
	{ icon: ImArrowRight, name: "ImArrowRight", library: "im" },
	{ icon: ImArrowDownRight, name: "ImArrowDownRight", library: "im" },
	{ icon: ImArrowDown, name: "ImArrowDown", library: "im" },
	{ icon: ImArrowDownLeft, name: "ImArrowDownLeft", library: "im" },
	{ icon: ImArrowLeft, name: "ImArrowLeft", library: "im" },
	{ icon: ImArrowUpLeft2, name: "ImArrowUpLeft2", library: "im" },
	{ icon: ImArrowUp2, name: "ImArrowUp2", library: "im" },
	{ icon: ImArrowUpRight2, name: "ImArrowUpRight2", library: "im" },
	{ icon: ImArrowRight2, name: "ImArrowRight2", library: "im" },
	{ icon: ImArrowDownRight2, name: "ImArrowDownRight2", library: "im" },
	{ icon: ImArrowDown2, name: "ImArrowDown2", library: "im" },
	{ icon: ImArrowDownLeft2, name: "ImArrowDownLeft2", library: "im" },
	{ icon: ImArrowLeft2, name: "ImArrowLeft2", library: "im" },
	{ icon: ImCircleUp, name: "ImCircleUp", library: "im" },
	{ icon: ImCircleRight, name: "ImCircleRight", library: "im" },
	{ icon: ImCircleDown, name: "ImCircleDown", library: "im" },
	{ icon: ImCircleLeft, name: "ImCircleLeft", library: "im" },
	{ icon: ImTab, name: "ImTab", library: "im" },
	{ icon: ImMoveUp, name: "ImMoveUp", library: "im" },
	{ icon: ImMoveDown, name: "ImMoveDown", library: "im" },
	{ icon: ImSortAlphaAsc, name: "ImSortAlphaAsc", library: "im" },
	{ icon: ImSortAlphaDesc, name: "ImSortAlphaDesc", library: "im" },
	{ icon: ImSortNumericAsc, name: "ImSortNumericAsc", library: "im" },
	{ icon: ImSortNumbericDesc, name: "ImSortNumbericDesc", library: "im" },
	{ icon: ImSortAmountAsc, name: "ImSortAmountAsc", library: "im" },
	{ icon: ImSortAmountDesc, name: "ImSortAmountDesc", library: "im" },
	{ icon: ImCommand, name: "ImCommand", library: "im" },
	{ icon: ImShift, name: "ImShift", library: "im" },
	{ icon: ImCtrl, name: "ImCtrl", library: "im" },
	{ icon: ImOpt, name: "ImOpt", library: "im" },
	{ icon: ImCheckboxChecked, name: "ImCheckboxChecked", library: "im" },
	{ icon: ImCheckboxUnchecked, name: "ImCheckboxUnchecked", library: "im" },
	{ icon: ImRadioChecked, name: "ImRadioChecked", library: "im" },
	{ icon: ImRadioChecked2, name: "ImRadioChecked2", library: "im" },
	{ icon: ImRadioUnchecked, name: "ImRadioUnchecked", library: "im" },
	{ icon: ImCrop, name: "ImCrop", library: "im" },
	{ icon: ImMakeGroup, name: "ImMakeGroup", library: "im" },
	{ icon: ImUngroup, name: "ImUngroup", library: "im" },
	{ icon: ImScissors, name: "ImScissors", library: "im" },
	{ icon: ImFilter, name: "ImFilter", library: "im" },
	{ icon: ImFont, name: "ImFont", library: "im" },
	{ icon: ImLigature, name: "ImLigature", library: "im" },
	{ icon: ImLigature2, name: "ImLigature2", library: "im" },
	{ icon: ImTextHeight, name: "ImTextHeight", library: "im" },
	{ icon: ImTextWidth, name: "ImTextWidth", library: "im" },
	{ icon: ImFontSize, name: "ImFontSize", library: "im" },
	{ icon: ImBold, name: "ImBold", library: "im" },
	{ icon: ImUnderline, name: "ImUnderline", library: "im" },
	{ icon: ImItalic, name: "ImItalic", library: "im" },
	{ icon: ImStrikethrough, name: "ImStrikethrough", library: "im" },
	{ icon: ImOmega, name: "ImOmega", library: "im" },
	{ icon: ImSigma, name: "ImSigma", library: "im" },
	{ icon: ImPageBreak, name: "ImPageBreak", library: "im" },
	{ icon: ImSuperscript, name: "ImSuperscript", library: "im" },
	{ icon: ImSubscript, name: "ImSubscript", library: "im" },
	{ icon: ImSuperscript2, name: "ImSuperscript2", library: "im" },
	{ icon: ImSubscript2, name: "ImSubscript2", library: "im" },
	{ icon: ImTextColor, name: "ImTextColor", library: "im" },
	{ icon: ImPagebreak, name: "ImPagebreak", library: "im" },
	{ icon: ImClearFormatting, name: "ImClearFormatting", library: "im" },
	{ icon: ImTable, name: "ImTable", library: "im" },
	{ icon: ImTable2, name: "ImTable2", library: "im" },
	{ icon: ImInsertTemplate, name: "ImInsertTemplate", library: "im" },
	{ icon: ImPilcrow, name: "ImPilcrow", library: "im" },
	{ icon: ImLtr, name: "ImLtr", library: "im" },
	{ icon: ImRtl, name: "ImRtl", library: "im" },
	{ icon: ImSection, name: "ImSection", library: "im" },
	{ icon: ImParagraphLeft, name: "ImParagraphLeft", library: "im" },
	{ icon: ImParagraphCenter, name: "ImParagraphCenter", library: "im" },
	{ icon: ImParagraphRight, name: "ImParagraphRight", library: "im" },
	{ icon: ImParagraphJustify, name: "ImParagraphJustify", library: "im" },
	{ icon: ImIndentIncrease, name: "ImIndentIncrease", library: "im" },
	{ icon: ImIndentDecrease, name: "ImIndentDecrease", library: "im" },
	{ icon: ImShare, name: "ImShare", library: "im" },
	{ icon: ImNewTab, name: "ImNewTab", library: "im" },
	{ icon: ImEmbed, name: "ImEmbed", library: "im" },
	{ icon: ImEmbed2, name: "ImEmbed2", library: "im" },
	{ icon: ImTerminal, name: "ImTerminal", library: "im" },
	{ icon: ImShare2, name: "ImShare2", library: "im" },
	{ icon: ImMail, name: "ImMail", library: "im" },
	{ icon: ImMail2, name: "ImMail2", library: "im" },
	{ icon: ImMail3, name: "ImMail3", library: "im" },
	{ icon: ImMail4, name: "ImMail4", library: "im" },
	{ icon: ImAmazon, name: "ImAmazon", library: "im" },
	{ icon: ImGoogle, name: "ImGoogle", library: "im" },
	{ icon: ImGoogle2, name: "ImGoogle2", library: "im" },
	{ icon: ImGoogle3, name: "ImGoogle3", library: "im" },
	{ icon: ImGooglePlus, name: "ImGooglePlus", library: "im" },
	{ icon: ImGooglePlus2, name: "ImGooglePlus2", library: "im" },
	{ icon: ImGooglePlus3, name: "ImGooglePlus3", library: "im" },
	{ icon: ImHangouts, name: "ImHangouts", library: "im" },
	{ icon: ImGoogleDrive, name: "ImGoogleDrive", library: "im" },
	{ icon: ImFacebook, name: "ImFacebook", library: "im" },
	{ icon: ImFacebook2, name: "ImFacebook2", library: "im" },
	{ icon: ImInstagram, name: "ImInstagram", library: "im" },
	{ icon: ImWhatsapp, name: "ImWhatsapp", library: "im" },
	{ icon: ImSpotify, name: "ImSpotify", library: "im" },
	{ icon: ImTelegram, name: "ImTelegram", library: "im" },
	{ icon: ImTwitter, name: "ImTwitter", library: "im" },
	{ icon: ImVine, name: "ImVine", library: "im" },
	{ icon: ImVk, name: "ImVk", library: "im" },
	{ icon: ImRenren, name: "ImRenren", library: "im" },
	{ icon: ImSinaWeibo, name: "ImSinaWeibo", library: "im" },
	{ icon: ImRss, name: "ImRss", library: "im" },
	{ icon: ImRss2, name: "ImRss2", library: "im" },
	{ icon: ImYoutube, name: "ImYoutube", library: "im" },
	{ icon: ImYoutube2, name: "ImYoutube2", library: "im" },
	{ icon: ImTwitch, name: "ImTwitch", library: "im" },
	{ icon: ImVimeo, name: "ImVimeo", library: "im" },
	{ icon: ImVimeo2, name: "ImVimeo2", library: "im" },
	{ icon: ImLanyrd, name: "ImLanyrd", library: "im" },
	{ icon: ImFlickr, name: "ImFlickr", library: "im" },
	{ icon: ImFlickr2, name: "ImFlickr2", library: "im" },
	{ icon: ImFlickr3, name: "ImFlickr3", library: "im" },
	{ icon: ImFlickr4, name: "ImFlickr4", library: "im" },
	{ icon: ImDribbble, name: "ImDribbble", library: "im" },
	{ icon: ImBehance, name: "ImBehance", library: "im" },
	{ icon: ImBehance2, name: "ImBehance2", library: "im" },
	{ icon: ImDeviantart, name: "ImDeviantart", library: "im" },
	{ icon: Im500Px, name: "Im500Px", library: "im" },
	{ icon: ImSteam, name: "ImSteam", library: "im" },
	{ icon: ImSteam2, name: "ImSteam2", library: "im" },
	{ icon: ImDropbox, name: "ImDropbox", library: "im" },
	{ icon: ImOnedrive, name: "ImOnedrive", library: "im" },
	{ icon: ImGithub, name: "ImGithub", library: "im" },
	{ icon: ImNpm, name: "ImNpm", library: "im" },
	{ icon: ImBasecamp, name: "ImBasecamp", library: "im" },
	{ icon: ImTrello, name: "ImTrello", library: "im" },
	{ icon: ImWordpress, name: "ImWordpress", library: "im" },
	{ icon: ImJoomla, name: "ImJoomla", library: "im" },
	{ icon: ImEllo, name: "ImEllo", library: "im" },
	{ icon: ImBlogger, name: "ImBlogger", library: "im" },
	{ icon: ImBlogger2, name: "ImBlogger2", library: "im" },
	{ icon: ImTumblr, name: "ImTumblr", library: "im" },
	{ icon: ImTumblr2, name: "ImTumblr2", library: "im" },
	{ icon: ImYahoo, name: "ImYahoo", library: "im" },
	{ icon: ImYahoo2, name: "ImYahoo2", library: "im" },
	{ icon: ImTux, name: "ImTux", library: "im" },
	{ icon: ImAppleinc, name: "ImAppleinc", library: "im" },
	{ icon: ImFinder, name: "ImFinder", library: "im" },
	{ icon: ImAndroid, name: "ImAndroid", library: "im" },
	{ icon: ImWindows, name: "ImWindows", library: "im" },
	{ icon: ImWindows8, name: "ImWindows8", library: "im" },
	{ icon: ImSoundcloud, name: "ImSoundcloud", library: "im" },
	{ icon: ImSoundcloud2, name: "ImSoundcloud2", library: "im" },
	{ icon: ImSkype, name: "ImSkype", library: "im" },
	{ icon: ImReddit, name: "ImReddit", library: "im" },
	{ icon: ImHackernews, name: "ImHackernews", library: "im" },
	{ icon: ImWikipedia, name: "ImWikipedia", library: "im" },
	{ icon: ImLinkedin, name: "ImLinkedin", library: "im" },
	{ icon: ImLinkedin2, name: "ImLinkedin2", library: "im" },
	{ icon: ImLastfm, name: "ImLastfm", library: "im" },
	{ icon: ImLastfm2, name: "ImLastfm2", library: "im" },
	{ icon: ImDelicious, name: "ImDelicious", library: "im" },
	{ icon: ImStumbleupon, name: "ImStumbleupon", library: "im" },
	{ icon: ImStumbleupon2, name: "ImStumbleupon2", library: "im" },
	{ icon: ImStackoverflow, name: "ImStackoverflow", library: "im" },
	{ icon: ImPinterest, name: "ImPinterest", library: "im" },
	{ icon: ImPinterest2, name: "ImPinterest2", library: "im" },
	{ icon: ImXing, name: "ImXing", library: "im" },
	{ icon: ImXing2, name: "ImXing2", library: "im" },
	{ icon: ImFlattr, name: "ImFlattr", library: "im" },
	{ icon: ImFoursquare, name: "ImFoursquare", library: "im" },
	{ icon: ImYelp, name: "ImYelp", library: "im" },
	{ icon: ImPaypal, name: "ImPaypal", library: "im" },
	{ icon: ImChrome, name: "ImChrome", library: "im" },
	{ icon: ImFirefox, name: "ImFirefox", library: "im" },
	{ icon: ImIe, name: "ImIe", library: "im" },
	{ icon: ImEdge, name: "ImEdge", library: "im" },
	{ icon: ImSafari, name: "ImSafari", library: "im" },
	{ icon: ImOpera, name: "ImOpera", library: "im" },
	{ icon: ImFilePdf, name: "ImFilePdf", library: "im" },
	{ icon: ImFileOpenoffice, name: "ImFileOpenoffice", library: "im" },
	{ icon: ImFileWord, name: "ImFileWord", library: "im" },
	{ icon: ImFileExcel, name: "ImFileExcel", library: "im" },
	{ icon: ImLibreoffice, name: "ImLibreoffice", library: "im" },
	{ icon: ImHtmlFive, name: "ImHtmlFive", library: "im" },
	{ icon: ImHtmlFive2, name: "ImHtmlFive2", library: "im" },
	{ icon: ImCss3, name: "ImCss3", library: "im" },
	{ icon: ImGit, name: "ImGit", library: "im" },
	{ icon: ImCodepen, name: "ImCodepen", library: "im" },
	{ icon: ImSvg, name: "ImSvg", library: "im" },
	{ icon: ImIcoMoon, name: "ImIcoMoon", library: "im" },
];

export default result;
