import {
ImHome,
ImHome2,
ImHome3,
ImOffice,
ImNewspaper,
ImPencil,
ImPencil2,
ImQuill,
ImPen,
ImBlog,
ImEyedropper,
ImDroplet,
ImPaintFormat,
ImImage,
ImImages,
ImCamera,
ImHeadphones,
ImMusic,
ImPlay,
ImFilm,
ImVideoCamera,
ImDice,
ImPacman,
ImSpades,
ImClubs,
ImDiamonds,
ImBullhorn,
ImConnection,
ImPodcast,
ImFeed,
ImMic,
ImBook,
ImBooks,
ImLibrary,
ImFileText,
ImProfile,
ImFileEmpty,
ImFilesEmpty,
ImFileText2,
ImFilePicture,
ImFileMusic,
ImFilePlay,
ImFileVideo,
ImFileZip,
ImCopy,
ImPaste,
ImStack,
ImFolder,
ImFolderOpen,
ImFolderPlus,
ImFolderMinus,
ImFolderDownload,
ImFolderUpload,
ImPriceTag,
ImPriceTags,
ImBarcode,
ImQrcode,
ImTicket,
ImCart,
ImCoinDollar,
ImCoinEuro,
ImCoinPound,
ImCoinYen,
ImCreditCard,
ImCalculator,
ImLifebuoy,
ImPhone,
ImPhoneHangUp,
ImAddressBook,
ImEnvelop,
ImPushpin,
ImLocation,
ImLocation2,
ImCompass,
ImCompass2,
ImMap,
ImMap2,
ImHistory,
ImClock,
ImClock2,
ImAlarm,
ImBell,
ImStopwatch,
ImCalendar,
ImPrinter,
ImKeyboard,
ImDisplay,
ImLaptop,
ImMobile,
ImMobile2,
ImTablet,
ImTv,
ImDrawer,
ImDrawer2,
ImBoxAdd,
ImBoxRemove,
ImDownload,
ImUpload,
ImFloppyDisk,
ImDrive,
ImDatabase,
ImUndo,
ImRedo,
ImUndo2,
ImRedo2,
ImForward,
ImReply,
ImBubble,
ImBubbles,
ImBubbles2,
ImBubble2,
ImBubbles3,
ImBubbles4,
ImUser,
ImUsers,
ImUserPlus,
ImUserMinus,
ImUserCheck,
ImUserTie,
ImQuotesLeft,
ImQuotesRight,
ImHourGlass,
ImSpinner,
ImSpinner2,
ImSpinner3,
ImSpinner4,
ImSpinner5,
ImSpinner6,
ImSpinner7,
ImSpinner8,
ImSpinner9,
ImSpinner10,
ImSpinner11,
ImBinoculars,
ImSearch,
ImZoomIn,
ImZoomOut,
ImEnlarge,
ImShrink,
ImEnlarge2,
ImShrink2,
ImKey,
ImKey2,
ImLock,
ImUnlocked,
ImWrench,
ImEqualizer,
ImEqualizer2,
ImCog,
ImCogs,
ImHammer,
ImMagicWand,
ImAidKit,
ImBug,
ImPieChart,
ImStatsDots,
ImStatsBars,
ImStatsBars2,
ImTrophy,
ImGift,
ImGlass,
ImGlass2,
ImMug,
ImSpoonKnife,
ImLeaf,
ImRocket,
ImMeter,
ImMeter2,
ImHammer2,
ImFire,
ImLab,
ImMagnet,
ImBin,
ImBin2,
ImBriefcase,
ImAirplane,
ImTruck,
ImRoad,
ImAccessibility,
ImTarget,
ImShield,
ImPower,
ImSwitch,
ImPowerCord,
ImClipboard,
ImListNumbered,
ImList,
ImList2,
ImTree,
ImMenu,
ImMenu2,
ImMenu3,
ImMenu4,
ImCloud,
ImCloudDownload,
ImCloudUpload,
ImCloudCheck,
ImDownload2,
ImUpload2,
ImDownload3,
ImUpload3,
ImSphere,
ImEarth,
ImLink,
ImFlag,
ImAttachment,
ImEye,
ImEyePlus,
ImEyeMinus,
ImEyeBlocked,
ImBookmark,
ImBookmarks,
ImSun,
ImContrast,
ImBrightnessContrast,
ImStarEmpty,
ImStarHalf,
ImStarFull,
ImHeart,
ImHeartBroken,
ImMan,
ImWoman,
ImManWoman,
ImHappy,
ImHappy2,
ImSmile,
ImSmile2,
ImTongue,
ImTongue2,
ImSad,
ImSad2,
ImWink,
ImWink2,
ImGrin,
ImGrin2,
ImCool,
ImCool2,
ImAngry,
ImAngry2,
ImEvil,
ImEvil2,
ImShocked,
ImShocked2,
ImBaffled,
ImBaffled2,
ImConfused,
ImConfused2,
ImNeutral,
ImNeutral2,
ImHipster,
ImHipster2,
ImWondering,
ImWondering2,
ImSleepy,
ImSleepy2,
ImFrustrated,
ImFrustrated2,
ImCrying,
ImCrying2,
ImPointUp,
ImPointRight,
ImPointDown,
ImPointLeft,
ImWarning,
ImNotification,
ImQuestion,
ImPlus,
ImMinus,
ImInfo,
ImCancelCircle,
ImBlocked,
ImCross,
ImCheckmark,
ImCheckmark2,
ImSpellCheck,
ImEnter,
ImExit,
ImPlay2,
ImPause,
ImStop,
ImPrevious,
ImNext,
ImBackward,
ImForward2,
ImPlay3,
ImPause2,
ImStop2,
ImBackward2,
ImForward3,
ImFirst,
ImLast,
ImPrevious2,
ImNext2,
ImEject,
ImVolumeHigh,
ImVolumeMedium,
ImVolumeLow,
ImVolumeMute,
ImVolumeMute2,
ImVolumeIncrease,
ImVolumeDecrease,
ImLoop,
ImLoop2,
ImInfinite,
ImShuffle,
ImArrowUpLeft,
ImArrowUp,
ImArrowUpRight,
ImArrowRight,
ImArrowDownRight,
ImArrowDown,
ImArrowDownLeft,
ImArrowLeft,
ImArrowUpLeft2,
ImArrowUp2,
ImArrowUpRight2,
ImArrowRight2,
ImArrowDownRight2,
ImArrowDown2,
ImArrowDownLeft2,
ImArrowLeft2,
ImCircleUp,
ImCircleRight,
ImCircleDown,
ImCircleLeft,
ImTab,
ImMoveUp,
ImMoveDown,
ImSortAlphaAsc,
ImSortAlphaDesc,
ImSortNumericAsc,
ImSortNumbericDesc,
ImSortAmountAsc,
ImSortAmountDesc,
ImCommand,
ImShift,
ImCtrl,
ImOpt,
ImCheckboxChecked,
ImCheckboxUnchecked,
ImRadioChecked,
ImRadioChecked2,
ImRadioUnchecked,
ImCrop,
ImMakeGroup,
ImUngroup,
ImScissors,
ImFilter,
ImFont,
ImLigature,
ImLigature2,
ImTextHeight,
ImTextWidth,
ImFontSize,
ImBold,
ImUnderline,
ImItalic,
ImStrikethrough,
ImOmega,
ImSigma,
ImPageBreak,
ImSuperscript,
ImSubscript,
ImSuperscript2,
ImSubscript2,
ImTextColor,
ImPagebreak,
ImClearFormatting,
ImTable,
ImTable2,
ImInsertTemplate,
ImPilcrow,
ImLtr,
ImRtl,
ImSection,
ImParagraphLeft,
ImParagraphCenter,
ImParagraphRight,
ImParagraphJustify,
ImIndentIncrease,
ImIndentDecrease,
ImShare,
ImNewTab,
ImEmbed,
ImEmbed2,
ImTerminal,
ImShare2,
ImMail,
ImMail2,
ImMail3,
ImMail4,
ImAmazon,
ImGoogle,
ImGoogle2,
ImGoogle3,
ImGooglePlus,
ImGooglePlus2,
ImGooglePlus3,
ImHangouts,
ImGoogleDrive,
ImFacebook,
ImFacebook2,
ImInstagram,
ImWhatsapp,
ImSpotify,
ImTelegram,
ImTwitter,
ImVine,
ImVk,
ImRenren,
ImSinaWeibo,
ImRss,
ImRss2,
ImYoutube,
ImYoutube2,
ImTwitch,
ImVimeo,
ImVimeo2,
ImLanyrd,
ImFlickr,
ImFlickr2,
ImFlickr3,
ImFlickr4,
ImDribbble,
ImBehance,
ImBehance2,
ImDeviantart,
Im500Px,
ImSteam,
ImSteam2,
ImDropbox,
ImOnedrive,
ImGithub,
ImNpm,
ImBasecamp,
ImTrello,
ImWordpress,
ImJoomla,
ImEllo,
ImBlogger,
ImBlogger2,
ImTumblr,
ImTumblr2,
ImYahoo,
ImYahoo2,
ImTux,
ImAppleinc,
ImFinder,
ImAndroid,
ImWindows,
ImWindows8,
ImSoundcloud,
ImSoundcloud2,
ImSkype,
ImReddit,
ImHackernews,
ImWikipedia,
ImLinkedin,
ImLinkedin2,
ImLastfm,
ImLastfm2,
ImDelicious,
ImStumbleupon,
ImStumbleupon2,
ImStackoverflow,
ImPinterest,
ImPinterest2,
ImXing,
ImXing2,
ImFlattr,
ImFoursquare,
ImYelp,
ImPaypal,
ImChrome,
ImFirefox,
ImIe,
ImEdge,
ImSafari,
ImOpera,
ImFilePdf,
ImFileOpenoffice,
ImFileWord,
ImFileExcel,
ImLibreoffice,
ImHtmlFive,
ImHtmlFive2,
ImCss3,
ImGit,
ImCodepen,
ImSvg,
ImIcoMoon,
} from "react-icons/im";

const result = [
{ icon: ImHome, name: "ImHome" },
{ icon: ImHome2, name: "ImHome2" },
{ icon: ImHome3, name: "ImHome3" },
{ icon: ImOffice, name: "ImOffice" },
{ icon: ImNewspaper, name: "ImNewspaper" },
{ icon: ImPencil, name: "ImPencil" },
{ icon: ImPencil2, name: "ImPencil2" },
{ icon: ImQuill, name: "ImQuill" },
{ icon: ImPen, name: "ImPen" },
{ icon: ImBlog, name: "ImBlog" },
{ icon: ImEyedropper, name: "ImEyedropper" },
{ icon: ImDroplet, name: "ImDroplet" },
{ icon: ImPaintFormat, name: "ImPaintFormat" },
{ icon: ImImage, name: "ImImage" },
{ icon: ImImages, name: "ImImages" },
{ icon: ImCamera, name: "ImCamera" },
{ icon: ImHeadphones, name: "ImHeadphones" },
{ icon: ImMusic, name: "ImMusic" },
{ icon: ImPlay, name: "ImPlay" },
{ icon: ImFilm, name: "ImFilm" },
{ icon: ImVideoCamera, name: "ImVideoCamera" },
{ icon: ImDice, name: "ImDice" },
{ icon: ImPacman, name: "ImPacman" },
{ icon: ImSpades, name: "ImSpades" },
{ icon: ImClubs, name: "ImClubs" },
{ icon: ImDiamonds, name: "ImDiamonds" },
{ icon: ImBullhorn, name: "ImBullhorn" },
{ icon: ImConnection, name: "ImConnection" },
{ icon: ImPodcast, name: "ImPodcast" },
{ icon: ImFeed, name: "ImFeed" },
{ icon: ImMic, name: "ImMic" },
{ icon: ImBook, name: "ImBook" },
{ icon: ImBooks, name: "ImBooks" },
{ icon: ImLibrary, name: "ImLibrary" },
{ icon: ImFileText, name: "ImFileText" },
{ icon: ImProfile, name: "ImProfile" },
{ icon: ImFileEmpty, name: "ImFileEmpty" },
{ icon: ImFilesEmpty, name: "ImFilesEmpty" },
{ icon: ImFileText2, name: "ImFileText2" },
{ icon: ImFilePicture, name: "ImFilePicture" },
{ icon: ImFileMusic, name: "ImFileMusic" },
{ icon: ImFilePlay, name: "ImFilePlay" },
{ icon: ImFileVideo, name: "ImFileVideo" },
{ icon: ImFileZip, name: "ImFileZip" },
{ icon: ImCopy, name: "ImCopy" },
{ icon: ImPaste, name: "ImPaste" },
{ icon: ImStack, name: "ImStack" },
{ icon: ImFolder, name: "ImFolder" },
{ icon: ImFolderOpen, name: "ImFolderOpen" },
{ icon: ImFolderPlus, name: "ImFolderPlus" },
{ icon: ImFolderMinus, name: "ImFolderMinus" },
{ icon: ImFolderDownload, name: "ImFolderDownload" },
{ icon: ImFolderUpload, name: "ImFolderUpload" },
{ icon: ImPriceTag, name: "ImPriceTag" },
{ icon: ImPriceTags, name: "ImPriceTags" },
{ icon: ImBarcode, name: "ImBarcode" },
{ icon: ImQrcode, name: "ImQrcode" },
{ icon: ImTicket, name: "ImTicket" },
{ icon: ImCart, name: "ImCart" },
{ icon: ImCoinDollar, name: "ImCoinDollar" },
{ icon: ImCoinEuro, name: "ImCoinEuro" },
{ icon: ImCoinPound, name: "ImCoinPound" },
{ icon: ImCoinYen, name: "ImCoinYen" },
{ icon: ImCreditCard, name: "ImCreditCard" },
{ icon: ImCalculator, name: "ImCalculator" },
{ icon: ImLifebuoy, name: "ImLifebuoy" },
{ icon: ImPhone, name: "ImPhone" },
{ icon: ImPhoneHangUp, name: "ImPhoneHangUp" },
{ icon: ImAddressBook, name: "ImAddressBook" },
{ icon: ImEnvelop, name: "ImEnvelop" },
{ icon: ImPushpin, name: "ImPushpin" },
{ icon: ImLocation, name: "ImLocation" },
{ icon: ImLocation2, name: "ImLocation2" },
{ icon: ImCompass, name: "ImCompass" },
{ icon: ImCompass2, name: "ImCompass2" },
{ icon: ImMap, name: "ImMap" },
{ icon: ImMap2, name: "ImMap2" },
{ icon: ImHistory, name: "ImHistory" },
{ icon: ImClock, name: "ImClock" },
{ icon: ImClock2, name: "ImClock2" },
{ icon: ImAlarm, name: "ImAlarm" },
{ icon: ImBell, name: "ImBell" },
{ icon: ImStopwatch, name: "ImStopwatch" },
{ icon: ImCalendar, name: "ImCalendar" },
{ icon: ImPrinter, name: "ImPrinter" },
{ icon: ImKeyboard, name: "ImKeyboard" },
{ icon: ImDisplay, name: "ImDisplay" },
{ icon: ImLaptop, name: "ImLaptop" },
{ icon: ImMobile, name: "ImMobile" },
{ icon: ImMobile2, name: "ImMobile2" },
{ icon: ImTablet, name: "ImTablet" },
{ icon: ImTv, name: "ImTv" },
{ icon: ImDrawer, name: "ImDrawer" },
{ icon: ImDrawer2, name: "ImDrawer2" },
{ icon: ImBoxAdd, name: "ImBoxAdd" },
{ icon: ImBoxRemove, name: "ImBoxRemove" },
{ icon: ImDownload, name: "ImDownload" },
{ icon: ImUpload, name: "ImUpload" },
{ icon: ImFloppyDisk, name: "ImFloppyDisk" },
{ icon: ImDrive, name: "ImDrive" },
{ icon: ImDatabase, name: "ImDatabase" },
{ icon: ImUndo, name: "ImUndo" },
{ icon: ImRedo, name: "ImRedo" },
{ icon: ImUndo2, name: "ImUndo2" },
{ icon: ImRedo2, name: "ImRedo2" },
{ icon: ImForward, name: "ImForward" },
{ icon: ImReply, name: "ImReply" },
{ icon: ImBubble, name: "ImBubble" },
{ icon: ImBubbles, name: "ImBubbles" },
{ icon: ImBubbles2, name: "ImBubbles2" },
{ icon: ImBubble2, name: "ImBubble2" },
{ icon: ImBubbles3, name: "ImBubbles3" },
{ icon: ImBubbles4, name: "ImBubbles4" },
{ icon: ImUser, name: "ImUser" },
{ icon: ImUsers, name: "ImUsers" },
{ icon: ImUserPlus, name: "ImUserPlus" },
{ icon: ImUserMinus, name: "ImUserMinus" },
{ icon: ImUserCheck, name: "ImUserCheck" },
{ icon: ImUserTie, name: "ImUserTie" },
{ icon: ImQuotesLeft, name: "ImQuotesLeft" },
{ icon: ImQuotesRight, name: "ImQuotesRight" },
{ icon: ImHourGlass, name: "ImHourGlass" },
{ icon: ImSpinner, name: "ImSpinner" },
{ icon: ImSpinner2, name: "ImSpinner2" },
{ icon: ImSpinner3, name: "ImSpinner3" },
{ icon: ImSpinner4, name: "ImSpinner4" },
{ icon: ImSpinner5, name: "ImSpinner5" },
{ icon: ImSpinner6, name: "ImSpinner6" },
{ icon: ImSpinner7, name: "ImSpinner7" },
{ icon: ImSpinner8, name: "ImSpinner8" },
{ icon: ImSpinner9, name: "ImSpinner9" },
{ icon: ImSpinner10, name: "ImSpinner10" },
{ icon: ImSpinner11, name: "ImSpinner11" },
{ icon: ImBinoculars, name: "ImBinoculars" },
{ icon: ImSearch, name: "ImSearch" },
{ icon: ImZoomIn, name: "ImZoomIn" },
{ icon: ImZoomOut, name: "ImZoomOut" },
{ icon: ImEnlarge, name: "ImEnlarge" },
{ icon: ImShrink, name: "ImShrink" },
{ icon: ImEnlarge2, name: "ImEnlarge2" },
{ icon: ImShrink2, name: "ImShrink2" },
{ icon: ImKey, name: "ImKey" },
{ icon: ImKey2, name: "ImKey2" },
{ icon: ImLock, name: "ImLock" },
{ icon: ImUnlocked, name: "ImUnlocked" },
{ icon: ImWrench, name: "ImWrench" },
{ icon: ImEqualizer, name: "ImEqualizer" },
{ icon: ImEqualizer2, name: "ImEqualizer2" },
{ icon: ImCog, name: "ImCog" },
{ icon: ImCogs, name: "ImCogs" },
{ icon: ImHammer, name: "ImHammer" },
{ icon: ImMagicWand, name: "ImMagicWand" },
{ icon: ImAidKit, name: "ImAidKit" },
{ icon: ImBug, name: "ImBug" },
{ icon: ImPieChart, name: "ImPieChart" },
{ icon: ImStatsDots, name: "ImStatsDots" },
{ icon: ImStatsBars, name: "ImStatsBars" },
{ icon: ImStatsBars2, name: "ImStatsBars2" },
{ icon: ImTrophy, name: "ImTrophy" },
{ icon: ImGift, name: "ImGift" },
{ icon: ImGlass, name: "ImGlass" },
{ icon: ImGlass2, name: "ImGlass2" },
{ icon: ImMug, name: "ImMug" },
{ icon: ImSpoonKnife, name: "ImSpoonKnife" },
{ icon: ImLeaf, name: "ImLeaf" },
{ icon: ImRocket, name: "ImRocket" },
{ icon: ImMeter, name: "ImMeter" },
{ icon: ImMeter2, name: "ImMeter2" },
{ icon: ImHammer2, name: "ImHammer2" },
{ icon: ImFire, name: "ImFire" },
{ icon: ImLab, name: "ImLab" },
{ icon: ImMagnet, name: "ImMagnet" },
{ icon: ImBin, name: "ImBin" },
{ icon: ImBin2, name: "ImBin2" },
{ icon: ImBriefcase, name: "ImBriefcase" },
{ icon: ImAirplane, name: "ImAirplane" },
{ icon: ImTruck, name: "ImTruck" },
{ icon: ImRoad, name: "ImRoad" },
{ icon: ImAccessibility, name: "ImAccessibility" },
{ icon: ImTarget, name: "ImTarget" },
{ icon: ImShield, name: "ImShield" },
{ icon: ImPower, name: "ImPower" },
{ icon: ImSwitch, name: "ImSwitch" },
{ icon: ImPowerCord, name: "ImPowerCord" },
{ icon: ImClipboard, name: "ImClipboard" },
{ icon: ImListNumbered, name: "ImListNumbered" },
{ icon: ImList, name: "ImList" },
{ icon: ImList2, name: "ImList2" },
{ icon: ImTree, name: "ImTree" },
{ icon: ImMenu, name: "ImMenu" },
{ icon: ImMenu2, name: "ImMenu2" },
{ icon: ImMenu3, name: "ImMenu3" },
{ icon: ImMenu4, name: "ImMenu4" },
{ icon: ImCloud, name: "ImCloud" },
{ icon: ImCloudDownload, name: "ImCloudDownload" },
{ icon: ImCloudUpload, name: "ImCloudUpload" },
{ icon: ImCloudCheck, name: "ImCloudCheck" },
{ icon: ImDownload2, name: "ImDownload2" },
{ icon: ImUpload2, name: "ImUpload2" },
{ icon: ImDownload3, name: "ImDownload3" },
{ icon: ImUpload3, name: "ImUpload3" },
{ icon: ImSphere, name: "ImSphere" },
{ icon: ImEarth, name: "ImEarth" },
{ icon: ImLink, name: "ImLink" },
{ icon: ImFlag, name: "ImFlag" },
{ icon: ImAttachment, name: "ImAttachment" },
{ icon: ImEye, name: "ImEye" },
{ icon: ImEyePlus, name: "ImEyePlus" },
{ icon: ImEyeMinus, name: "ImEyeMinus" },
{ icon: ImEyeBlocked, name: "ImEyeBlocked" },
{ icon: ImBookmark, name: "ImBookmark" },
{ icon: ImBookmarks, name: "ImBookmarks" },
{ icon: ImSun, name: "ImSun" },
{ icon: ImContrast, name: "ImContrast" },
{ icon: ImBrightnessContrast, name: "ImBrightnessContrast" },
{ icon: ImStarEmpty, name: "ImStarEmpty" },
{ icon: ImStarHalf, name: "ImStarHalf" },
{ icon: ImStarFull, name: "ImStarFull" },
{ icon: ImHeart, name: "ImHeart" },
{ icon: ImHeartBroken, name: "ImHeartBroken" },
{ icon: ImMan, name: "ImMan" },
{ icon: ImWoman, name: "ImWoman" },
{ icon: ImManWoman, name: "ImManWoman" },
{ icon: ImHappy, name: "ImHappy" },
{ icon: ImHappy2, name: "ImHappy2" },
{ icon: ImSmile, name: "ImSmile" },
{ icon: ImSmile2, name: "ImSmile2" },
{ icon: ImTongue, name: "ImTongue" },
{ icon: ImTongue2, name: "ImTongue2" },
{ icon: ImSad, name: "ImSad" },
{ icon: ImSad2, name: "ImSad2" },
{ icon: ImWink, name: "ImWink" },
{ icon: ImWink2, name: "ImWink2" },
{ icon: ImGrin, name: "ImGrin" },
{ icon: ImGrin2, name: "ImGrin2" },
{ icon: ImCool, name: "ImCool" },
{ icon: ImCool2, name: "ImCool2" },
{ icon: ImAngry, name: "ImAngry" },
{ icon: ImAngry2, name: "ImAngry2" },
{ icon: ImEvil, name: "ImEvil" },
{ icon: ImEvil2, name: "ImEvil2" },
{ icon: ImShocked, name: "ImShocked" },
{ icon: ImShocked2, name: "ImShocked2" },
{ icon: ImBaffled, name: "ImBaffled" },
{ icon: ImBaffled2, name: "ImBaffled2" },
{ icon: ImConfused, name: "ImConfused" },
{ icon: ImConfused2, name: "ImConfused2" },
{ icon: ImNeutral, name: "ImNeutral" },
{ icon: ImNeutral2, name: "ImNeutral2" },
{ icon: ImHipster, name: "ImHipster" },
{ icon: ImHipster2, name: "ImHipster2" },
{ icon: ImWondering, name: "ImWondering" },
{ icon: ImWondering2, name: "ImWondering2" },
{ icon: ImSleepy, name: "ImSleepy" },
{ icon: ImSleepy2, name: "ImSleepy2" },
{ icon: ImFrustrated, name: "ImFrustrated" },
{ icon: ImFrustrated2, name: "ImFrustrated2" },
{ icon: ImCrying, name: "ImCrying" },
{ icon: ImCrying2, name: "ImCrying2" },
{ icon: ImPointUp, name: "ImPointUp" },
{ icon: ImPointRight, name: "ImPointRight" },
{ icon: ImPointDown, name: "ImPointDown" },
{ icon: ImPointLeft, name: "ImPointLeft" },
{ icon: ImWarning, name: "ImWarning" },
{ icon: ImNotification, name: "ImNotification" },
{ icon: ImQuestion, name: "ImQuestion" },
{ icon: ImPlus, name: "ImPlus" },
{ icon: ImMinus, name: "ImMinus" },
{ icon: ImInfo, name: "ImInfo" },
{ icon: ImCancelCircle, name: "ImCancelCircle" },
{ icon: ImBlocked, name: "ImBlocked" },
{ icon: ImCross, name: "ImCross" },
{ icon: ImCheckmark, name: "ImCheckmark" },
{ icon: ImCheckmark2, name: "ImCheckmark2" },
{ icon: ImSpellCheck, name: "ImSpellCheck" },
{ icon: ImEnter, name: "ImEnter" },
{ icon: ImExit, name: "ImExit" },
{ icon: ImPlay2, name: "ImPlay2" },
{ icon: ImPause, name: "ImPause" },
{ icon: ImStop, name: "ImStop" },
{ icon: ImPrevious, name: "ImPrevious" },
{ icon: ImNext, name: "ImNext" },
{ icon: ImBackward, name: "ImBackward" },
{ icon: ImForward2, name: "ImForward2" },
{ icon: ImPlay3, name: "ImPlay3" },
{ icon: ImPause2, name: "ImPause2" },
{ icon: ImStop2, name: "ImStop2" },
{ icon: ImBackward2, name: "ImBackward2" },
{ icon: ImForward3, name: "ImForward3" },
{ icon: ImFirst, name: "ImFirst" },
{ icon: ImLast, name: "ImLast" },
{ icon: ImPrevious2, name: "ImPrevious2" },
{ icon: ImNext2, name: "ImNext2" },
{ icon: ImEject, name: "ImEject" },
{ icon: ImVolumeHigh, name: "ImVolumeHigh" },
{ icon: ImVolumeMedium, name: "ImVolumeMedium" },
{ icon: ImVolumeLow, name: "ImVolumeLow" },
{ icon: ImVolumeMute, name: "ImVolumeMute" },
{ icon: ImVolumeMute2, name: "ImVolumeMute2" },
{ icon: ImVolumeIncrease, name: "ImVolumeIncrease" },
{ icon: ImVolumeDecrease, name: "ImVolumeDecrease" },
{ icon: ImLoop, name: "ImLoop" },
{ icon: ImLoop2, name: "ImLoop2" },
{ icon: ImInfinite, name: "ImInfinite" },
{ icon: ImShuffle, name: "ImShuffle" },
{ icon: ImArrowUpLeft, name: "ImArrowUpLeft" },
{ icon: ImArrowUp, name: "ImArrowUp" },
{ icon: ImArrowUpRight, name: "ImArrowUpRight" },
{ icon: ImArrowRight, name: "ImArrowRight" },
{ icon: ImArrowDownRight, name: "ImArrowDownRight" },
{ icon: ImArrowDown, name: "ImArrowDown" },
{ icon: ImArrowDownLeft, name: "ImArrowDownLeft" },
{ icon: ImArrowLeft, name: "ImArrowLeft" },
{ icon: ImArrowUpLeft2, name: "ImArrowUpLeft2" },
{ icon: ImArrowUp2, name: "ImArrowUp2" },
{ icon: ImArrowUpRight2, name: "ImArrowUpRight2" },
{ icon: ImArrowRight2, name: "ImArrowRight2" },
{ icon: ImArrowDownRight2, name: "ImArrowDownRight2" },
{ icon: ImArrowDown2, name: "ImArrowDown2" },
{ icon: ImArrowDownLeft2, name: "ImArrowDownLeft2" },
{ icon: ImArrowLeft2, name: "ImArrowLeft2" },
{ icon: ImCircleUp, name: "ImCircleUp" },
{ icon: ImCircleRight, name: "ImCircleRight" },
{ icon: ImCircleDown, name: "ImCircleDown" },
{ icon: ImCircleLeft, name: "ImCircleLeft" },
{ icon: ImTab, name: "ImTab" },
{ icon: ImMoveUp, name: "ImMoveUp" },
{ icon: ImMoveDown, name: "ImMoveDown" },
{ icon: ImSortAlphaAsc, name: "ImSortAlphaAsc" },
{ icon: ImSortAlphaDesc, name: "ImSortAlphaDesc" },
{ icon: ImSortNumericAsc, name: "ImSortNumericAsc" },
{ icon: ImSortNumbericDesc, name: "ImSortNumbericDesc" },
{ icon: ImSortAmountAsc, name: "ImSortAmountAsc" },
{ icon: ImSortAmountDesc, name: "ImSortAmountDesc" },
{ icon: ImCommand, name: "ImCommand" },
{ icon: ImShift, name: "ImShift" },
{ icon: ImCtrl, name: "ImCtrl" },
{ icon: ImOpt, name: "ImOpt" },
{ icon: ImCheckboxChecked, name: "ImCheckboxChecked" },
{ icon: ImCheckboxUnchecked, name: "ImCheckboxUnchecked" },
{ icon: ImRadioChecked, name: "ImRadioChecked" },
{ icon: ImRadioChecked2, name: "ImRadioChecked2" },
{ icon: ImRadioUnchecked, name: "ImRadioUnchecked" },
{ icon: ImCrop, name: "ImCrop" },
{ icon: ImMakeGroup, name: "ImMakeGroup" },
{ icon: ImUngroup, name: "ImUngroup" },
{ icon: ImScissors, name: "ImScissors" },
{ icon: ImFilter, name: "ImFilter" },
{ icon: ImFont, name: "ImFont" },
{ icon: ImLigature, name: "ImLigature" },
{ icon: ImLigature2, name: "ImLigature2" },
{ icon: ImTextHeight, name: "ImTextHeight" },
{ icon: ImTextWidth, name: "ImTextWidth" },
{ icon: ImFontSize, name: "ImFontSize" },
{ icon: ImBold, name: "ImBold" },
{ icon: ImUnderline, name: "ImUnderline" },
{ icon: ImItalic, name: "ImItalic" },
{ icon: ImStrikethrough, name: "ImStrikethrough" },
{ icon: ImOmega, name: "ImOmega" },
{ icon: ImSigma, name: "ImSigma" },
{ icon: ImPageBreak, name: "ImPageBreak" },
{ icon: ImSuperscript, name: "ImSuperscript" },
{ icon: ImSubscript, name: "ImSubscript" },
{ icon: ImSuperscript2, name: "ImSuperscript2" },
{ icon: ImSubscript2, name: "ImSubscript2" },
{ icon: ImTextColor, name: "ImTextColor" },
{ icon: ImPagebreak, name: "ImPagebreak" },
{ icon: ImClearFormatting, name: "ImClearFormatting" },
{ icon: ImTable, name: "ImTable" },
{ icon: ImTable2, name: "ImTable2" },
{ icon: ImInsertTemplate, name: "ImInsertTemplate" },
{ icon: ImPilcrow, name: "ImPilcrow" },
{ icon: ImLtr, name: "ImLtr" },
{ icon: ImRtl, name: "ImRtl" },
{ icon: ImSection, name: "ImSection" },
{ icon: ImParagraphLeft, name: "ImParagraphLeft" },
{ icon: ImParagraphCenter, name: "ImParagraphCenter" },
{ icon: ImParagraphRight, name: "ImParagraphRight" },
{ icon: ImParagraphJustify, name: "ImParagraphJustify" },
{ icon: ImIndentIncrease, name: "ImIndentIncrease" },
{ icon: ImIndentDecrease, name: "ImIndentDecrease" },
{ icon: ImShare, name: "ImShare" },
{ icon: ImNewTab, name: "ImNewTab" },
{ icon: ImEmbed, name: "ImEmbed" },
{ icon: ImEmbed2, name: "ImEmbed2" },
{ icon: ImTerminal, name: "ImTerminal" },
{ icon: ImShare2, name: "ImShare2" },
{ icon: ImMail, name: "ImMail" },
{ icon: ImMail2, name: "ImMail2" },
{ icon: ImMail3, name: "ImMail3" },
{ icon: ImMail4, name: "ImMail4" },
{ icon: ImAmazon, name: "ImAmazon" },
{ icon: ImGoogle, name: "ImGoogle" },
{ icon: ImGoogle2, name: "ImGoogle2" },
{ icon: ImGoogle3, name: "ImGoogle3" },
{ icon: ImGooglePlus, name: "ImGooglePlus" },
{ icon: ImGooglePlus2, name: "ImGooglePlus2" },
{ icon: ImGooglePlus3, name: "ImGooglePlus3" },
{ icon: ImHangouts, name: "ImHangouts" },
{ icon: ImGoogleDrive, name: "ImGoogleDrive" },
{ icon: ImFacebook, name: "ImFacebook" },
{ icon: ImFacebook2, name: "ImFacebook2" },
{ icon: ImInstagram, name: "ImInstagram" },
{ icon: ImWhatsapp, name: "ImWhatsapp" },
{ icon: ImSpotify, name: "ImSpotify" },
{ icon: ImTelegram, name: "ImTelegram" },
{ icon: ImTwitter, name: "ImTwitter" },
{ icon: ImVine, name: "ImVine" },
{ icon: ImVk, name: "ImVk" },
{ icon: ImRenren, name: "ImRenren" },
{ icon: ImSinaWeibo, name: "ImSinaWeibo" },
{ icon: ImRss, name: "ImRss" },
{ icon: ImRss2, name: "ImRss2" },
{ icon: ImYoutube, name: "ImYoutube" },
{ icon: ImYoutube2, name: "ImYoutube2" },
{ icon: ImTwitch, name: "ImTwitch" },
{ icon: ImVimeo, name: "ImVimeo" },
{ icon: ImVimeo2, name: "ImVimeo2" },
{ icon: ImLanyrd, name: "ImLanyrd" },
{ icon: ImFlickr, name: "ImFlickr" },
{ icon: ImFlickr2, name: "ImFlickr2" },
{ icon: ImFlickr3, name: "ImFlickr3" },
{ icon: ImFlickr4, name: "ImFlickr4" },
{ icon: ImDribbble, name: "ImDribbble" },
{ icon: ImBehance, name: "ImBehance" },
{ icon: ImBehance2, name: "ImBehance2" },
{ icon: ImDeviantart, name: "ImDeviantart" },
{ icon: Im500Px, name: "Im500Px" },
{ icon: ImSteam, name: "ImSteam" },
{ icon: ImSteam2, name: "ImSteam2" },
{ icon: ImDropbox, name: "ImDropbox" },
{ icon: ImOnedrive, name: "ImOnedrive" },
{ icon: ImGithub, name: "ImGithub" },
{ icon: ImNpm, name: "ImNpm" },
{ icon: ImBasecamp, name: "ImBasecamp" },
{ icon: ImTrello, name: "ImTrello" },
{ icon: ImWordpress, name: "ImWordpress" },
{ icon: ImJoomla, name: "ImJoomla" },
{ icon: ImEllo, name: "ImEllo" },
{ icon: ImBlogger, name: "ImBlogger" },
{ icon: ImBlogger2, name: "ImBlogger2" },
{ icon: ImTumblr, name: "ImTumblr" },
{ icon: ImTumblr2, name: "ImTumblr2" },
{ icon: ImYahoo, name: "ImYahoo" },
{ icon: ImYahoo2, name: "ImYahoo2" },
{ icon: ImTux, name: "ImTux" },
{ icon: ImAppleinc, name: "ImAppleinc" },
{ icon: ImFinder, name: "ImFinder" },
{ icon: ImAndroid, name: "ImAndroid" },
{ icon: ImWindows, name: "ImWindows" },
{ icon: ImWindows8, name: "ImWindows8" },
{ icon: ImSoundcloud, name: "ImSoundcloud" },
{ icon: ImSoundcloud2, name: "ImSoundcloud2" },
{ icon: ImSkype, name: "ImSkype" },
{ icon: ImReddit, name: "ImReddit" },
{ icon: ImHackernews, name: "ImHackernews" },
{ icon: ImWikipedia, name: "ImWikipedia" },
{ icon: ImLinkedin, name: "ImLinkedin" },
{ icon: ImLinkedin2, name: "ImLinkedin2" },
{ icon: ImLastfm, name: "ImLastfm" },
{ icon: ImLastfm2, name: "ImLastfm2" },
{ icon: ImDelicious, name: "ImDelicious" },
{ icon: ImStumbleupon, name: "ImStumbleupon" },
{ icon: ImStumbleupon2, name: "ImStumbleupon2" },
{ icon: ImStackoverflow, name: "ImStackoverflow" },
{ icon: ImPinterest, name: "ImPinterest" },
{ icon: ImPinterest2, name: "ImPinterest2" },
{ icon: ImXing, name: "ImXing" },
{ icon: ImXing2, name: "ImXing2" },
{ icon: ImFlattr, name: "ImFlattr" },
{ icon: ImFoursquare, name: "ImFoursquare" },
{ icon: ImYelp, name: "ImYelp" },
{ icon: ImPaypal, name: "ImPaypal" },
{ icon: ImChrome, name: "ImChrome" },
{ icon: ImFirefox, name: "ImFirefox" },
{ icon: ImIe, name: "ImIe" },
{ icon: ImEdge, name: "ImEdge" },
{ icon: ImSafari, name: "ImSafari" },
{ icon: ImOpera, name: "ImOpera" },
{ icon: ImFilePdf, name: "ImFilePdf" },
{ icon: ImFileOpenoffice, name: "ImFileOpenoffice" },
{ icon: ImFileWord, name: "ImFileWord" },
{ icon: ImFileExcel, name: "ImFileExcel" },
{ icon: ImLibreoffice, name: "ImLibreoffice" },
{ icon: ImHtmlFive, name: "ImHtmlFive" },
{ icon: ImHtmlFive2, name: "ImHtmlFive2" },
{ icon: ImCss3, name: "ImCss3" },
{ icon: ImGit, name: "ImGit" },
{ icon: ImCodepen, name: "ImCodepen" },
{ icon: ImSvg, name: "ImSvg" },
{ icon: ImIcoMoon, name: "ImIcoMoon" },
];

export default result