import {
VscAccount,
VscActivateBreakpoints,
VscAdd,
VscArchive,
VscArrowBoth,
VscArrowDown,
VscArrowLeft,
VscArrowRight,
VscArrowSmallDown,
VscArrowSmallLeft,
VscArrowSmallRight,
VscArrowSmallUp,
VscArrowSwap,
VscArrowUp,
VscAzure,
VscBeakerStop,
VscBeaker,
VscBellDot,
VscBell,
VscBold,
VscBook,
VscBookmark,
VscBracketDot,
VscBracketError,
VscBriefcase,
VscBroadcast,
VscBrowser,
VscBug,
VscCalendar,
VscCallIncoming,
VscCallOutgoing,
VscCaseSensitive,
VscCheckAll,
VscCheck,
VscChecklist,
VscChevronDown,
VscChevronLeft,
VscChevronRight,
VscChevronUp,
VscChromeClose,
VscChromeMaximize,
VscChromeMinimize,
VscChromeRestore,
VscCircleFilled,
VscCircleLargeFilled,
VscCircleLargeOutline,
VscCircleOutline,
VscCircleSlash,
VscCircuitBoard,
VscClearAll,
VscClippy,
VscCloseAll,
VscClose,
VscCloudDownload,
VscCloudUpload,
VscCloud,
VscCode,
VscCollapseAll,
VscColorMode,
VscCombine,
VscCommentDiscussion,
VscComment,
VscCompassActive,
VscCompassDot,
VscCompass,
VscCopy,
VscCreditCard,
VscDash,
VscDashboard,
VscDatabase,
VscDebugAll,
VscDebugAltSmall,
VscDebugAlt,
VscDebugBreakpointConditionalUnverified,
VscDebugBreakpointConditional,
VscDebugBreakpointDataUnverified,
VscDebugBreakpointData,
VscDebugBreakpointFunctionUnverified,
VscDebugBreakpointFunction,
VscDebugBreakpointLogUnverified,
VscDebugBreakpointLog,
VscDebugBreakpointUnsupported,
VscDebugConsole,
VscDebugContinueSmall,
VscDebugContinue,
VscDebugCoverage,
VscDebugDisconnect,
VscDebugLineByLine,
VscDebugPause,
VscDebugRerun,
VscDebugRestartFrame,
VscDebugRestart,
VscDebugReverseContinue,
VscDebugStackframeActive,
VscDebugStackframeDot,
VscDebugStackframe,
VscDebugStart,
VscDebugStepBack,
VscDebugStepInto,
VscDebugStepOut,
VscDebugStepOver,
VscDebugStop,
VscDebug,
VscDesktopDownload,
VscDeviceCameraVideo,
VscDeviceCamera,
VscDeviceMobile,
VscDiffAdded,
VscDiffIgnored,
VscDiffModified,
VscDiffRemoved,
VscDiffRenamed,
VscDiff,
VscDiscard,
VscEdit,
VscEditorLayout,
VscEllipsis,
VscEmptyWindow,
VscError,
VscExclude,
VscExpandAll,
VscExport,
VscExtensions,
VscEyeClosed,
VscEye,
VscFeedback,
VscFileBinary,
VscFileCode,
VscFileMedia,
VscFilePdf,
VscFileSubmodule,
VscFileSymlinkDirectory,
VscFileSymlinkFile,
VscFileZip,
VscFile,
VscFiles,
VscFilterFilled,
VscFilter,
VscFlame,
VscFoldDown,
VscFoldUp,
VscFold,
VscFolderActive,
VscFolderLibrary,
VscFolderOpened,
VscFolder,
VscGear,
VscGift,
VscGistSecret,
VscGist,
VscGitCommit,
VscGitCompare,
VscGitMerge,
VscGitPullRequestClosed,
VscGitPullRequestCreate,
VscGitPullRequestDraft,
VscGitPullRequest,
VscGithubAction,
VscGithubAlt,
VscGithubInverted,
VscGithub,
VscGlobe,
VscGoToFile,
VscGrabber,
VscGraphLeft,
VscGraphLine,
VscGraphScatter,
VscGraph,
VscGripper,
VscGroupByRefType,
VscHeart,
VscHistory,
VscHome,
VscHorizontalRule,
VscHubot,
VscInbox,
VscInfo,
VscInspect,
VscIssueDraft,
VscIssueReopened,
VscIssues,
VscItalic,
VscJersey,
VscJson,
VscKebabVertical,
VscKey,
VscLaw,
VscLayersActive,
VscLayersDot,
VscLayers,
VscLibrary,
VscLightbulbAutofix,
VscLightbulb,
VscLinkExternal,
VscLink,
VscListFilter,
VscListFlat,
VscListOrdered,
VscListSelection,
VscListTree,
VscListUnordered,
VscLiveShare,
VscLoading,
VscLocation,
VscLock,
VscMagnet,
VscMailRead,
VscMail,
VscMarkdown,
VscMegaphone,
VscMention,
VscMenu,
VscMerge,
VscMilestone,
VscMirror,
VscMortarBoard,
VscMove,
VscMultipleWindows,
VscMute,
VscNewFile,
VscNewFolder,
VscNoNewline,
VscNote,
VscNotebookTemplate,
VscNotebook,
VscOctoface,
VscOpenPreview,
VscOrganization,
VscOutput,
VscPackage,
VscPaintcan,
VscPassFilled,
VscPass,
VscPersonAdd,
VscPerson,
VscPieChart,
VscPin,
VscPinnedDirty,
VscPinned,
VscPlayCircle,
VscPlay,
VscPlug,
VscPreserveCase,
VscPreview,
VscPrimitiveSquare,
VscProject,
VscPulse,
VscQuestion,
VscQuote,
VscRadioTower,
VscReactions,
VscRecordKeys,
VscRecord,
VscRedo,
VscReferences,
VscRefresh,
VscRegex,
VscRemoteExplorer,
VscRemote,
VscRemove,
VscReplaceAll,
VscReplace,
VscReply,
VscRepoClone,
VscRepoForcePush,
VscRepoForked,
VscRepoPull,
VscRepoPush,
VscRepo,
VscReport,
VscRequestChanges,
VscRocket,
VscRootFolderOpened,
VscRootFolder,
VscRss,
VscRuby,
VscRunAbove,
VscRunAll,
VscRunBelow,
VscRunErrors,
VscSaveAll,
VscSaveAs,
VscSave,
VscScreenFull,
VscScreenNormal,
VscSearchStop,
VscSearch,
VscServerEnvironment,
VscServerProcess,
VscServer,
VscSettingsGear,
VscSettings,
VscShield,
VscSignIn,
VscSignOut,
VscSmiley,
VscSortPrecedence,
VscSourceControl,
VscSplitHorizontal,
VscSplitVertical,
VscSquirrel,
VscStarEmpty,
VscStarFull,
VscStarHalf,
VscStopCircle,
VscSymbolArray,
VscSymbolBoolean,
VscSymbolClass,
VscSymbolColor,
VscSymbolConstant,
VscSymbolEnumMember,
VscSymbolEnum,
VscSymbolEvent,
VscSymbolField,
VscSymbolFile,
VscSymbolInterface,
VscSymbolKey,
VscSymbolKeyword,
VscSymbolMethod,
VscSymbolMisc,
VscSymbolNamespace,
VscSymbolNumeric,
VscSymbolOperator,
VscSymbolParameter,
VscSymbolProperty,
VscSymbolRuler,
VscSymbolSnippet,
VscSymbolString,
VscSymbolStructure,
VscSymbolVariable,
VscSyncIgnored,
VscSync,
VscTable,
VscTag,
VscTasklist,
VscTelescope,
VscTerminalBash,
VscTerminalCmd,
VscTerminalDebian,
VscTerminalLinux,
VscTerminalPowershell,
VscTerminalTmux,
VscTerminalUbuntu,
VscTerminal,
VscTextSize,
VscThreeBars,
VscThumbsdown,
VscThumbsup,
VscTools,
VscTrash,
VscTriangleDown,
VscTriangleLeft,
VscTriangleRight,
VscTriangleUp,
VscTwitter,
VscTypeHierarchySub,
VscTypeHierarchySuper,
VscTypeHierarchy,
VscUnfold,
VscUngroupByRefType,
VscUnlock,
VscUnmute,
VscUnverified,
VscVariableGroup,
VscVerified,
VscVersions,
VscVmActive,
VscVmConnect,
VscVmOutline,
VscVmRunning,
VscVm,
VscWand,
VscWarning,
VscWatch,
VscWhitespace,
VscWholeWord,
VscWindow,
VscWordWrap,
VscWorkspaceTrusted,
VscWorkspaceUnknown,
VscWorkspaceUntrusted,
VscZoomIn,
VscZoomOut,
} from "react-icons/vsc";

const result = [
{ icon: VscAccount, name: "VscAccount" },
{ icon: VscActivateBreakpoints, name: "VscActivateBreakpoints" },
{ icon: VscAdd, name: "VscAdd" },
{ icon: VscArchive, name: "VscArchive" },
{ icon: VscArrowBoth, name: "VscArrowBoth" },
{ icon: VscArrowDown, name: "VscArrowDown" },
{ icon: VscArrowLeft, name: "VscArrowLeft" },
{ icon: VscArrowRight, name: "VscArrowRight" },
{ icon: VscArrowSmallDown, name: "VscArrowSmallDown" },
{ icon: VscArrowSmallLeft, name: "VscArrowSmallLeft" },
{ icon: VscArrowSmallRight, name: "VscArrowSmallRight" },
{ icon: VscArrowSmallUp, name: "VscArrowSmallUp" },
{ icon: VscArrowSwap, name: "VscArrowSwap" },
{ icon: VscArrowUp, name: "VscArrowUp" },
{ icon: VscAzure, name: "VscAzure" },
{ icon: VscBeakerStop, name: "VscBeakerStop" },
{ icon: VscBeaker, name: "VscBeaker" },
{ icon: VscBellDot, name: "VscBellDot" },
{ icon: VscBell, name: "VscBell" },
{ icon: VscBold, name: "VscBold" },
{ icon: VscBook, name: "VscBook" },
{ icon: VscBookmark, name: "VscBookmark" },
{ icon: VscBracketDot, name: "VscBracketDot" },
{ icon: VscBracketError, name: "VscBracketError" },
{ icon: VscBriefcase, name: "VscBriefcase" },
{ icon: VscBroadcast, name: "VscBroadcast" },
{ icon: VscBrowser, name: "VscBrowser" },
{ icon: VscBug, name: "VscBug" },
{ icon: VscCalendar, name: "VscCalendar" },
{ icon: VscCallIncoming, name: "VscCallIncoming" },
{ icon: VscCallOutgoing, name: "VscCallOutgoing" },
{ icon: VscCaseSensitive, name: "VscCaseSensitive" },
{ icon: VscCheckAll, name: "VscCheckAll" },
{ icon: VscCheck, name: "VscCheck" },
{ icon: VscChecklist, name: "VscChecklist" },
{ icon: VscChevronDown, name: "VscChevronDown" },
{ icon: VscChevronLeft, name: "VscChevronLeft" },
{ icon: VscChevronRight, name: "VscChevronRight" },
{ icon: VscChevronUp, name: "VscChevronUp" },
{ icon: VscChromeClose, name: "VscChromeClose" },
{ icon: VscChromeMaximize, name: "VscChromeMaximize" },
{ icon: VscChromeMinimize, name: "VscChromeMinimize" },
{ icon: VscChromeRestore, name: "VscChromeRestore" },
{ icon: VscCircleFilled, name: "VscCircleFilled" },
{ icon: VscCircleLargeFilled, name: "VscCircleLargeFilled" },
{ icon: VscCircleLargeOutline, name: "VscCircleLargeOutline" },
{ icon: VscCircleOutline, name: "VscCircleOutline" },
{ icon: VscCircleSlash, name: "VscCircleSlash" },
{ icon: VscCircuitBoard, name: "VscCircuitBoard" },
{ icon: VscClearAll, name: "VscClearAll" },
{ icon: VscClippy, name: "VscClippy" },
{ icon: VscCloseAll, name: "VscCloseAll" },
{ icon: VscClose, name: "VscClose" },
{ icon: VscCloudDownload, name: "VscCloudDownload" },
{ icon: VscCloudUpload, name: "VscCloudUpload" },
{ icon: VscCloud, name: "VscCloud" },
{ icon: VscCode, name: "VscCode" },
{ icon: VscCollapseAll, name: "VscCollapseAll" },
{ icon: VscColorMode, name: "VscColorMode" },
{ icon: VscCombine, name: "VscCombine" },
{ icon: VscCommentDiscussion, name: "VscCommentDiscussion" },
{ icon: VscComment, name: "VscComment" },
{ icon: VscCompassActive, name: "VscCompassActive" },
{ icon: VscCompassDot, name: "VscCompassDot" },
{ icon: VscCompass, name: "VscCompass" },
{ icon: VscCopy, name: "VscCopy" },
{ icon: VscCreditCard, name: "VscCreditCard" },
{ icon: VscDash, name: "VscDash" },
{ icon: VscDashboard, name: "VscDashboard" },
{ icon: VscDatabase, name: "VscDatabase" },
{ icon: VscDebugAll, name: "VscDebugAll" },
{ icon: VscDebugAltSmall, name: "VscDebugAltSmall" },
{ icon: VscDebugAlt, name: "VscDebugAlt" },
{ icon: VscDebugBreakpointConditionalUnverified, name: "VscDebugBreakpointConditionalUnverified" },
{ icon: VscDebugBreakpointConditional, name: "VscDebugBreakpointConditional" },
{ icon: VscDebugBreakpointDataUnverified, name: "VscDebugBreakpointDataUnverified" },
{ icon: VscDebugBreakpointData, name: "VscDebugBreakpointData" },
{ icon: VscDebugBreakpointFunctionUnverified, name: "VscDebugBreakpointFunctionUnverified" },
{ icon: VscDebugBreakpointFunction, name: "VscDebugBreakpointFunction" },
{ icon: VscDebugBreakpointLogUnverified, name: "VscDebugBreakpointLogUnverified" },
{ icon: VscDebugBreakpointLog, name: "VscDebugBreakpointLog" },
{ icon: VscDebugBreakpointUnsupported, name: "VscDebugBreakpointUnsupported" },
{ icon: VscDebugConsole, name: "VscDebugConsole" },
{ icon: VscDebugContinueSmall, name: "VscDebugContinueSmall" },
{ icon: VscDebugContinue, name: "VscDebugContinue" },
{ icon: VscDebugCoverage, name: "VscDebugCoverage" },
{ icon: VscDebugDisconnect, name: "VscDebugDisconnect" },
{ icon: VscDebugLineByLine, name: "VscDebugLineByLine" },
{ icon: VscDebugPause, name: "VscDebugPause" },
{ icon: VscDebugRerun, name: "VscDebugRerun" },
{ icon: VscDebugRestartFrame, name: "VscDebugRestartFrame" },
{ icon: VscDebugRestart, name: "VscDebugRestart" },
{ icon: VscDebugReverseContinue, name: "VscDebugReverseContinue" },
{ icon: VscDebugStackframeActive, name: "VscDebugStackframeActive" },
{ icon: VscDebugStackframeDot, name: "VscDebugStackframeDot" },
{ icon: VscDebugStackframe, name: "VscDebugStackframe" },
{ icon: VscDebugStart, name: "VscDebugStart" },
{ icon: VscDebugStepBack, name: "VscDebugStepBack" },
{ icon: VscDebugStepInto, name: "VscDebugStepInto" },
{ icon: VscDebugStepOut, name: "VscDebugStepOut" },
{ icon: VscDebugStepOver, name: "VscDebugStepOver" },
{ icon: VscDebugStop, name: "VscDebugStop" },
{ icon: VscDebug, name: "VscDebug" },
{ icon: VscDesktopDownload, name: "VscDesktopDownload" },
{ icon: VscDeviceCameraVideo, name: "VscDeviceCameraVideo" },
{ icon: VscDeviceCamera, name: "VscDeviceCamera" },
{ icon: VscDeviceMobile, name: "VscDeviceMobile" },
{ icon: VscDiffAdded, name: "VscDiffAdded" },
{ icon: VscDiffIgnored, name: "VscDiffIgnored" },
{ icon: VscDiffModified, name: "VscDiffModified" },
{ icon: VscDiffRemoved, name: "VscDiffRemoved" },
{ icon: VscDiffRenamed, name: "VscDiffRenamed" },
{ icon: VscDiff, name: "VscDiff" },
{ icon: VscDiscard, name: "VscDiscard" },
{ icon: VscEdit, name: "VscEdit" },
{ icon: VscEditorLayout, name: "VscEditorLayout" },
{ icon: VscEllipsis, name: "VscEllipsis" },
{ icon: VscEmptyWindow, name: "VscEmptyWindow" },
{ icon: VscError, name: "VscError" },
{ icon: VscExclude, name: "VscExclude" },
{ icon: VscExpandAll, name: "VscExpandAll" },
{ icon: VscExport, name: "VscExport" },
{ icon: VscExtensions, name: "VscExtensions" },
{ icon: VscEyeClosed, name: "VscEyeClosed" },
{ icon: VscEye, name: "VscEye" },
{ icon: VscFeedback, name: "VscFeedback" },
{ icon: VscFileBinary, name: "VscFileBinary" },
{ icon: VscFileCode, name: "VscFileCode" },
{ icon: VscFileMedia, name: "VscFileMedia" },
{ icon: VscFilePdf, name: "VscFilePdf" },
{ icon: VscFileSubmodule, name: "VscFileSubmodule" },
{ icon: VscFileSymlinkDirectory, name: "VscFileSymlinkDirectory" },
{ icon: VscFileSymlinkFile, name: "VscFileSymlinkFile" },
{ icon: VscFileZip, name: "VscFileZip" },
{ icon: VscFile, name: "VscFile" },
{ icon: VscFiles, name: "VscFiles" },
{ icon: VscFilterFilled, name: "VscFilterFilled" },
{ icon: VscFilter, name: "VscFilter" },
{ icon: VscFlame, name: "VscFlame" },
{ icon: VscFoldDown, name: "VscFoldDown" },
{ icon: VscFoldUp, name: "VscFoldUp" },
{ icon: VscFold, name: "VscFold" },
{ icon: VscFolderActive, name: "VscFolderActive" },
{ icon: VscFolderLibrary, name: "VscFolderLibrary" },
{ icon: VscFolderOpened, name: "VscFolderOpened" },
{ icon: VscFolder, name: "VscFolder" },
{ icon: VscGear, name: "VscGear" },
{ icon: VscGift, name: "VscGift" },
{ icon: VscGistSecret, name: "VscGistSecret" },
{ icon: VscGist, name: "VscGist" },
{ icon: VscGitCommit, name: "VscGitCommit" },
{ icon: VscGitCompare, name: "VscGitCompare" },
{ icon: VscGitMerge, name: "VscGitMerge" },
{ icon: VscGitPullRequestClosed, name: "VscGitPullRequestClosed" },
{ icon: VscGitPullRequestCreate, name: "VscGitPullRequestCreate" },
{ icon: VscGitPullRequestDraft, name: "VscGitPullRequestDraft" },
{ icon: VscGitPullRequest, name: "VscGitPullRequest" },
{ icon: VscGithubAction, name: "VscGithubAction" },
{ icon: VscGithubAlt, name: "VscGithubAlt" },
{ icon: VscGithubInverted, name: "VscGithubInverted" },
{ icon: VscGithub, name: "VscGithub" },
{ icon: VscGlobe, name: "VscGlobe" },
{ icon: VscGoToFile, name: "VscGoToFile" },
{ icon: VscGrabber, name: "VscGrabber" },
{ icon: VscGraphLeft, name: "VscGraphLeft" },
{ icon: VscGraphLine, name: "VscGraphLine" },
{ icon: VscGraphScatter, name: "VscGraphScatter" },
{ icon: VscGraph, name: "VscGraph" },
{ icon: VscGripper, name: "VscGripper" },
{ icon: VscGroupByRefType, name: "VscGroupByRefType" },
{ icon: VscHeart, name: "VscHeart" },
{ icon: VscHistory, name: "VscHistory" },
{ icon: VscHome, name: "VscHome" },
{ icon: VscHorizontalRule, name: "VscHorizontalRule" },
{ icon: VscHubot, name: "VscHubot" },
{ icon: VscInbox, name: "VscInbox" },
{ icon: VscInfo, name: "VscInfo" },
{ icon: VscInspect, name: "VscInspect" },
{ icon: VscIssueDraft, name: "VscIssueDraft" },
{ icon: VscIssueReopened, name: "VscIssueReopened" },
{ icon: VscIssues, name: "VscIssues" },
{ icon: VscItalic, name: "VscItalic" },
{ icon: VscJersey, name: "VscJersey" },
{ icon: VscJson, name: "VscJson" },
{ icon: VscKebabVertical, name: "VscKebabVertical" },
{ icon: VscKey, name: "VscKey" },
{ icon: VscLaw, name: "VscLaw" },
{ icon: VscLayersActive, name: "VscLayersActive" },
{ icon: VscLayersDot, name: "VscLayersDot" },
{ icon: VscLayers, name: "VscLayers" },
{ icon: VscLibrary, name: "VscLibrary" },
{ icon: VscLightbulbAutofix, name: "VscLightbulbAutofix" },
{ icon: VscLightbulb, name: "VscLightbulb" },
{ icon: VscLinkExternal, name: "VscLinkExternal" },
{ icon: VscLink, name: "VscLink" },
{ icon: VscListFilter, name: "VscListFilter" },
{ icon: VscListFlat, name: "VscListFlat" },
{ icon: VscListOrdered, name: "VscListOrdered" },
{ icon: VscListSelection, name: "VscListSelection" },
{ icon: VscListTree, name: "VscListTree" },
{ icon: VscListUnordered, name: "VscListUnordered" },
{ icon: VscLiveShare, name: "VscLiveShare" },
{ icon: VscLoading, name: "VscLoading" },
{ icon: VscLocation, name: "VscLocation" },
{ icon: VscLock, name: "VscLock" },
{ icon: VscMagnet, name: "VscMagnet" },
{ icon: VscMailRead, name: "VscMailRead" },
{ icon: VscMail, name: "VscMail" },
{ icon: VscMarkdown, name: "VscMarkdown" },
{ icon: VscMegaphone, name: "VscMegaphone" },
{ icon: VscMention, name: "VscMention" },
{ icon: VscMenu, name: "VscMenu" },
{ icon: VscMerge, name: "VscMerge" },
{ icon: VscMilestone, name: "VscMilestone" },
{ icon: VscMirror, name: "VscMirror" },
{ icon: VscMortarBoard, name: "VscMortarBoard" },
{ icon: VscMove, name: "VscMove" },
{ icon: VscMultipleWindows, name: "VscMultipleWindows" },
{ icon: VscMute, name: "VscMute" },
{ icon: VscNewFile, name: "VscNewFile" },
{ icon: VscNewFolder, name: "VscNewFolder" },
{ icon: VscNoNewline, name: "VscNoNewline" },
{ icon: VscNote, name: "VscNote" },
{ icon: VscNotebookTemplate, name: "VscNotebookTemplate" },
{ icon: VscNotebook, name: "VscNotebook" },
{ icon: VscOctoface, name: "VscOctoface" },
{ icon: VscOpenPreview, name: "VscOpenPreview" },
{ icon: VscOrganization, name: "VscOrganization" },
{ icon: VscOutput, name: "VscOutput" },
{ icon: VscPackage, name: "VscPackage" },
{ icon: VscPaintcan, name: "VscPaintcan" },
{ icon: VscPassFilled, name: "VscPassFilled" },
{ icon: VscPass, name: "VscPass" },
{ icon: VscPersonAdd, name: "VscPersonAdd" },
{ icon: VscPerson, name: "VscPerson" },
{ icon: VscPieChart, name: "VscPieChart" },
{ icon: VscPin, name: "VscPin" },
{ icon: VscPinnedDirty, name: "VscPinnedDirty" },
{ icon: VscPinned, name: "VscPinned" },
{ icon: VscPlayCircle, name: "VscPlayCircle" },
{ icon: VscPlay, name: "VscPlay" },
{ icon: VscPlug, name: "VscPlug" },
{ icon: VscPreserveCase, name: "VscPreserveCase" },
{ icon: VscPreview, name: "VscPreview" },
{ icon: VscPrimitiveSquare, name: "VscPrimitiveSquare" },
{ icon: VscProject, name: "VscProject" },
{ icon: VscPulse, name: "VscPulse" },
{ icon: VscQuestion, name: "VscQuestion" },
{ icon: VscQuote, name: "VscQuote" },
{ icon: VscRadioTower, name: "VscRadioTower" },
{ icon: VscReactions, name: "VscReactions" },
{ icon: VscRecordKeys, name: "VscRecordKeys" },
{ icon: VscRecord, name: "VscRecord" },
{ icon: VscRedo, name: "VscRedo" },
{ icon: VscReferences, name: "VscReferences" },
{ icon: VscRefresh, name: "VscRefresh" },
{ icon: VscRegex, name: "VscRegex" },
{ icon: VscRemoteExplorer, name: "VscRemoteExplorer" },
{ icon: VscRemote, name: "VscRemote" },
{ icon: VscRemove, name: "VscRemove" },
{ icon: VscReplaceAll, name: "VscReplaceAll" },
{ icon: VscReplace, name: "VscReplace" },
{ icon: VscReply, name: "VscReply" },
{ icon: VscRepoClone, name: "VscRepoClone" },
{ icon: VscRepoForcePush, name: "VscRepoForcePush" },
{ icon: VscRepoForked, name: "VscRepoForked" },
{ icon: VscRepoPull, name: "VscRepoPull" },
{ icon: VscRepoPush, name: "VscRepoPush" },
{ icon: VscRepo, name: "VscRepo" },
{ icon: VscReport, name: "VscReport" },
{ icon: VscRequestChanges, name: "VscRequestChanges" },
{ icon: VscRocket, name: "VscRocket" },
{ icon: VscRootFolderOpened, name: "VscRootFolderOpened" },
{ icon: VscRootFolder, name: "VscRootFolder" },
{ icon: VscRss, name: "VscRss" },
{ icon: VscRuby, name: "VscRuby" },
{ icon: VscRunAbove, name: "VscRunAbove" },
{ icon: VscRunAll, name: "VscRunAll" },
{ icon: VscRunBelow, name: "VscRunBelow" },
{ icon: VscRunErrors, name: "VscRunErrors" },
{ icon: VscSaveAll, name: "VscSaveAll" },
{ icon: VscSaveAs, name: "VscSaveAs" },
{ icon: VscSave, name: "VscSave" },
{ icon: VscScreenFull, name: "VscScreenFull" },
{ icon: VscScreenNormal, name: "VscScreenNormal" },
{ icon: VscSearchStop, name: "VscSearchStop" },
{ icon: VscSearch, name: "VscSearch" },
{ icon: VscServerEnvironment, name: "VscServerEnvironment" },
{ icon: VscServerProcess, name: "VscServerProcess" },
{ icon: VscServer, name: "VscServer" },
{ icon: VscSettingsGear, name: "VscSettingsGear" },
{ icon: VscSettings, name: "VscSettings" },
{ icon: VscShield, name: "VscShield" },
{ icon: VscSignIn, name: "VscSignIn" },
{ icon: VscSignOut, name: "VscSignOut" },
{ icon: VscSmiley, name: "VscSmiley" },
{ icon: VscSortPrecedence, name: "VscSortPrecedence" },
{ icon: VscSourceControl, name: "VscSourceControl" },
{ icon: VscSplitHorizontal, name: "VscSplitHorizontal" },
{ icon: VscSplitVertical, name: "VscSplitVertical" },
{ icon: VscSquirrel, name: "VscSquirrel" },
{ icon: VscStarEmpty, name: "VscStarEmpty" },
{ icon: VscStarFull, name: "VscStarFull" },
{ icon: VscStarHalf, name: "VscStarHalf" },
{ icon: VscStopCircle, name: "VscStopCircle" },
{ icon: VscSymbolArray, name: "VscSymbolArray" },
{ icon: VscSymbolBoolean, name: "VscSymbolBoolean" },
{ icon: VscSymbolClass, name: "VscSymbolClass" },
{ icon: VscSymbolColor, name: "VscSymbolColor" },
{ icon: VscSymbolConstant, name: "VscSymbolConstant" },
{ icon: VscSymbolEnumMember, name: "VscSymbolEnumMember" },
{ icon: VscSymbolEnum, name: "VscSymbolEnum" },
{ icon: VscSymbolEvent, name: "VscSymbolEvent" },
{ icon: VscSymbolField, name: "VscSymbolField" },
{ icon: VscSymbolFile, name: "VscSymbolFile" },
{ icon: VscSymbolInterface, name: "VscSymbolInterface" },
{ icon: VscSymbolKey, name: "VscSymbolKey" },
{ icon: VscSymbolKeyword, name: "VscSymbolKeyword" },
{ icon: VscSymbolMethod, name: "VscSymbolMethod" },
{ icon: VscSymbolMisc, name: "VscSymbolMisc" },
{ icon: VscSymbolNamespace, name: "VscSymbolNamespace" },
{ icon: VscSymbolNumeric, name: "VscSymbolNumeric" },
{ icon: VscSymbolOperator, name: "VscSymbolOperator" },
{ icon: VscSymbolParameter, name: "VscSymbolParameter" },
{ icon: VscSymbolProperty, name: "VscSymbolProperty" },
{ icon: VscSymbolRuler, name: "VscSymbolRuler" },
{ icon: VscSymbolSnippet, name: "VscSymbolSnippet" },
{ icon: VscSymbolString, name: "VscSymbolString" },
{ icon: VscSymbolStructure, name: "VscSymbolStructure" },
{ icon: VscSymbolVariable, name: "VscSymbolVariable" },
{ icon: VscSyncIgnored, name: "VscSyncIgnored" },
{ icon: VscSync, name: "VscSync" },
{ icon: VscTable, name: "VscTable" },
{ icon: VscTag, name: "VscTag" },
{ icon: VscTasklist, name: "VscTasklist" },
{ icon: VscTelescope, name: "VscTelescope" },
{ icon: VscTerminalBash, name: "VscTerminalBash" },
{ icon: VscTerminalCmd, name: "VscTerminalCmd" },
{ icon: VscTerminalDebian, name: "VscTerminalDebian" },
{ icon: VscTerminalLinux, name: "VscTerminalLinux" },
{ icon: VscTerminalPowershell, name: "VscTerminalPowershell" },
{ icon: VscTerminalTmux, name: "VscTerminalTmux" },
{ icon: VscTerminalUbuntu, name: "VscTerminalUbuntu" },
{ icon: VscTerminal, name: "VscTerminal" },
{ icon: VscTextSize, name: "VscTextSize" },
{ icon: VscThreeBars, name: "VscThreeBars" },
{ icon: VscThumbsdown, name: "VscThumbsdown" },
{ icon: VscThumbsup, name: "VscThumbsup" },
{ icon: VscTools, name: "VscTools" },
{ icon: VscTrash, name: "VscTrash" },
{ icon: VscTriangleDown, name: "VscTriangleDown" },
{ icon: VscTriangleLeft, name: "VscTriangleLeft" },
{ icon: VscTriangleRight, name: "VscTriangleRight" },
{ icon: VscTriangleUp, name: "VscTriangleUp" },
{ icon: VscTwitter, name: "VscTwitter" },
{ icon: VscTypeHierarchySub, name: "VscTypeHierarchySub" },
{ icon: VscTypeHierarchySuper, name: "VscTypeHierarchySuper" },
{ icon: VscTypeHierarchy, name: "VscTypeHierarchy" },
{ icon: VscUnfold, name: "VscUnfold" },
{ icon: VscUngroupByRefType, name: "VscUngroupByRefType" },
{ icon: VscUnlock, name: "VscUnlock" },
{ icon: VscUnmute, name: "VscUnmute" },
{ icon: VscUnverified, name: "VscUnverified" },
{ icon: VscVariableGroup, name: "VscVariableGroup" },
{ icon: VscVerified, name: "VscVerified" },
{ icon: VscVersions, name: "VscVersions" },
{ icon: VscVmActive, name: "VscVmActive" },
{ icon: VscVmConnect, name: "VscVmConnect" },
{ icon: VscVmOutline, name: "VscVmOutline" },
{ icon: VscVmRunning, name: "VscVmRunning" },
{ icon: VscVm, name: "VscVm" },
{ icon: VscWand, name: "VscWand" },
{ icon: VscWarning, name: "VscWarning" },
{ icon: VscWatch, name: "VscWatch" },
{ icon: VscWhitespace, name: "VscWhitespace" },
{ icon: VscWholeWord, name: "VscWholeWord" },
{ icon: VscWindow, name: "VscWindow" },
{ icon: VscWordWrap, name: "VscWordWrap" },
{ icon: VscWorkspaceTrusted, name: "VscWorkspaceTrusted" },
{ icon: VscWorkspaceUnknown, name: "VscWorkspaceUnknown" },
{ icon: VscWorkspaceUntrusted, name: "VscWorkspaceUntrusted" },
{ icon: VscZoomIn, name: "VscZoomIn" },
{ icon: VscZoomOut, name: "VscZoomOut" },
];

export default result