import {
	VscAccount,
	VscActivateBreakpoints,
	VscAdd,
	VscArchive,
	VscArrowBoth,
	VscArrowDown,
	VscArrowLeft,
	VscArrowRight,
	VscArrowSmallDown,
	VscArrowSmallLeft,
	VscArrowSmallRight,
	VscArrowSmallUp,
	VscArrowSwap,
	VscArrowUp,
	VscAzure,
	VscBeakerStop,
	VscBeaker,
	VscBellDot,
	VscBell,
	VscBold,
	VscBook,
	VscBookmark,
	VscBracketDot,
	VscBracketError,
	VscBriefcase,
	VscBroadcast,
	VscBrowser,
	VscBug,
	VscCalendar,
	VscCallIncoming,
	VscCallOutgoing,
	VscCaseSensitive,
	VscCheckAll,
	VscCheck,
	VscChecklist,
	VscChevronDown,
	VscChevronLeft,
	VscChevronRight,
	VscChevronUp,
	VscChromeClose,
	VscChromeMaximize,
	VscChromeMinimize,
	VscChromeRestore,
	VscCircleFilled,
	VscCircleLargeFilled,
	VscCircleLargeOutline,
	VscCircleOutline,
	VscCircleSlash,
	VscCircuitBoard,
	VscClearAll,
	VscClippy,
	VscCloseAll,
	VscClose,
	VscCloudDownload,
	VscCloudUpload,
	VscCloud,
	VscCode,
	VscCollapseAll,
	VscColorMode,
	VscCombine,
	VscCommentDiscussion,
	VscComment,
	VscCompassActive,
	VscCompassDot,
	VscCompass,
	VscCopy,
	VscCreditCard,
	VscDash,
	VscDashboard,
	VscDatabase,
	VscDebugAll,
	VscDebugAltSmall,
	VscDebugAlt,
	VscDebugBreakpointConditionalUnverified,
	VscDebugBreakpointConditional,
	VscDebugBreakpointDataUnverified,
	VscDebugBreakpointData,
	VscDebugBreakpointFunctionUnverified,
	VscDebugBreakpointFunction,
	VscDebugBreakpointLogUnverified,
	VscDebugBreakpointLog,
	VscDebugBreakpointUnsupported,
	VscDebugConsole,
	VscDebugContinueSmall,
	VscDebugContinue,
	VscDebugCoverage,
	VscDebugDisconnect,
	VscDebugLineByLine,
	VscDebugPause,
	VscDebugRerun,
	VscDebugRestartFrame,
	VscDebugRestart,
	VscDebugReverseContinue,
	VscDebugStackframeActive,
	VscDebugStackframeDot,
	VscDebugStackframe,
	VscDebugStart,
	VscDebugStepBack,
	VscDebugStepInto,
	VscDebugStepOut,
	VscDebugStepOver,
	VscDebugStop,
	VscDebug,
	VscDesktopDownload,
	VscDeviceCameraVideo,
	VscDeviceCamera,
	VscDeviceMobile,
	VscDiffAdded,
	VscDiffIgnored,
	VscDiffModified,
	VscDiffRemoved,
	VscDiffRenamed,
	VscDiff,
	VscDiscard,
	VscEdit,
	VscEditorLayout,
	VscEllipsis,
	VscEmptyWindow,
	VscError,
	VscExclude,
	VscExpandAll,
	VscExport,
	VscExtensions,
	VscEyeClosed,
	VscEye,
	VscFeedback,
	VscFileBinary,
	VscFileCode,
	VscFileMedia,
	VscFilePdf,
	VscFileSubmodule,
	VscFileSymlinkDirectory,
	VscFileSymlinkFile,
	VscFileZip,
	VscFile,
	VscFiles,
	VscFilterFilled,
	VscFilter,
	VscFlame,
	VscFoldDown,
	VscFoldUp,
	VscFold,
	VscFolderActive,
	VscFolderLibrary,
	VscFolderOpened,
	VscFolder,
	VscGear,
	VscGift,
	VscGistSecret,
	VscGist,
	VscGitCommit,
	VscGitCompare,
	VscGitMerge,
	VscGitPullRequestClosed,
	VscGitPullRequestCreate,
	VscGitPullRequestDraft,
	VscGitPullRequest,
	VscGithubAction,
	VscGithubAlt,
	VscGithubInverted,
	VscGithub,
	VscGlobe,
	VscGoToFile,
	VscGrabber,
	VscGraphLeft,
	VscGraphLine,
	VscGraphScatter,
	VscGraph,
	VscGripper,
	VscGroupByRefType,
	VscHeart,
	VscHistory,
	VscHome,
	VscHorizontalRule,
	VscHubot,
	VscInbox,
	VscInfo,
	VscInspect,
	VscIssueDraft,
	VscIssueReopened,
	VscIssues,
	VscItalic,
	VscJersey,
	VscJson,
	VscKebabVertical,
	VscKey,
	VscLaw,
	VscLayersActive,
	VscLayersDot,
	VscLayers,
	VscLibrary,
	VscLightbulbAutofix,
	VscLightbulb,
	VscLinkExternal,
	VscLink,
	VscListFilter,
	VscListFlat,
	VscListOrdered,
	VscListSelection,
	VscListTree,
	VscListUnordered,
	VscLiveShare,
	VscLoading,
	VscLocation,
	VscLock,
	VscMagnet,
	VscMailRead,
	VscMail,
	VscMarkdown,
	VscMegaphone,
	VscMention,
	VscMenu,
	VscMerge,
	VscMilestone,
	VscMirror,
	VscMortarBoard,
	VscMove,
	VscMultipleWindows,
	VscMute,
	VscNewFile,
	VscNewFolder,
	VscNoNewline,
	VscNote,
	VscNotebookTemplate,
	VscNotebook,
	VscOctoface,
	VscOpenPreview,
	VscOrganization,
	VscOutput,
	VscPackage,
	VscPaintcan,
	VscPassFilled,
	VscPass,
	VscPersonAdd,
	VscPerson,
	VscPieChart,
	VscPin,
	VscPinnedDirty,
	VscPinned,
	VscPlayCircle,
	VscPlay,
	VscPlug,
	VscPreserveCase,
	VscPreview,
	VscPrimitiveSquare,
	VscProject,
	VscPulse,
	VscQuestion,
	VscQuote,
	VscRadioTower,
	VscReactions,
	VscRecordKeys,
	VscRecord,
	VscRedo,
	VscReferences,
	VscRefresh,
	VscRegex,
	VscRemoteExplorer,
	VscRemote,
	VscRemove,
	VscReplaceAll,
	VscReplace,
	VscReply,
	VscRepoClone,
	VscRepoForcePush,
	VscRepoForked,
	VscRepoPull,
	VscRepoPush,
	VscRepo,
	VscReport,
	VscRequestChanges,
	VscRocket,
	VscRootFolderOpened,
	VscRootFolder,
	VscRss,
	VscRuby,
	VscRunAbove,
	VscRunAll,
	VscRunBelow,
	VscRunErrors,
	VscSaveAll,
	VscSaveAs,
	VscSave,
	VscScreenFull,
	VscScreenNormal,
	VscSearchStop,
	VscSearch,
	VscServerEnvironment,
	VscServerProcess,
	VscServer,
	VscSettingsGear,
	VscSettings,
	VscShield,
	VscSignIn,
	VscSignOut,
	VscSmiley,
	VscSortPrecedence,
	VscSourceControl,
	VscSplitHorizontal,
	VscSplitVertical,
	VscSquirrel,
	VscStarEmpty,
	VscStarFull,
	VscStarHalf,
	VscStopCircle,
	VscSymbolArray,
	VscSymbolBoolean,
	VscSymbolClass,
	VscSymbolColor,
	VscSymbolConstant,
	VscSymbolEnumMember,
	VscSymbolEnum,
	VscSymbolEvent,
	VscSymbolField,
	VscSymbolFile,
	VscSymbolInterface,
	VscSymbolKey,
	VscSymbolKeyword,
	VscSymbolMethod,
	VscSymbolMisc,
	VscSymbolNamespace,
	VscSymbolNumeric,
	VscSymbolOperator,
	VscSymbolParameter,
	VscSymbolProperty,
	VscSymbolRuler,
	VscSymbolSnippet,
	VscSymbolString,
	VscSymbolStructure,
	VscSymbolVariable,
	VscSyncIgnored,
	VscSync,
	VscTable,
	VscTag,
	VscTasklist,
	VscTelescope,
	VscTerminalBash,
	VscTerminalCmd,
	VscTerminalDebian,
	VscTerminalLinux,
	VscTerminalPowershell,
	VscTerminalTmux,
	VscTerminalUbuntu,
	VscTerminal,
	VscTextSize,
	VscThreeBars,
	VscThumbsdown,
	VscThumbsup,
	VscTools,
	VscTrash,
	VscTriangleDown,
	VscTriangleLeft,
	VscTriangleRight,
	VscTriangleUp,
	VscTwitter,
	VscTypeHierarchySub,
	VscTypeHierarchySuper,
	VscTypeHierarchy,
	VscUnfold,
	VscUngroupByRefType,
	VscUnlock,
	VscUnmute,
	VscUnverified,
	VscVariableGroup,
	VscVerified,
	VscVersions,
	VscVmActive,
	VscVmConnect,
	VscVmOutline,
	VscVmRunning,
	VscVm,
	VscWand,
	VscWarning,
	VscWatch,
	VscWhitespace,
	VscWholeWord,
	VscWindow,
	VscWordWrap,
	VscWorkspaceTrusted,
	VscWorkspaceUnknown,
	VscWorkspaceUntrusted,
	VscZoomIn,
	VscZoomOut,
} from "react-icons/vsc";

const result = [
	{ icon: VscAccount, name: "VscAccount", library: "vsc" },
	{ icon: VscActivateBreakpoints, name: "VscActivateBreakpoints", library: "vsc" },
	{ icon: VscAdd, name: "VscAdd", library: "vsc" },
	{ icon: VscArchive, name: "VscArchive", library: "vsc" },
	{ icon: VscArrowBoth, name: "VscArrowBoth", library: "vsc" },
	{ icon: VscArrowDown, name: "VscArrowDown", library: "vsc" },
	{ icon: VscArrowLeft, name: "VscArrowLeft", library: "vsc" },
	{ icon: VscArrowRight, name: "VscArrowRight", library: "vsc" },
	{ icon: VscArrowSmallDown, name: "VscArrowSmallDown", library: "vsc" },
	{ icon: VscArrowSmallLeft, name: "VscArrowSmallLeft", library: "vsc" },
	{ icon: VscArrowSmallRight, name: "VscArrowSmallRight", library: "vsc" },
	{ icon: VscArrowSmallUp, name: "VscArrowSmallUp", library: "vsc" },
	{ icon: VscArrowSwap, name: "VscArrowSwap", library: "vsc" },
	{ icon: VscArrowUp, name: "VscArrowUp", library: "vsc" },
	{ icon: VscAzure, name: "VscAzure", library: "vsc" },
	{ icon: VscBeakerStop, name: "VscBeakerStop", library: "vsc" },
	{ icon: VscBeaker, name: "VscBeaker", library: "vsc" },
	{ icon: VscBellDot, name: "VscBellDot", library: "vsc" },
	{ icon: VscBell, name: "VscBell", library: "vsc" },
	{ icon: VscBold, name: "VscBold", library: "vsc" },
	{ icon: VscBook, name: "VscBook", library: "vsc" },
	{ icon: VscBookmark, name: "VscBookmark", library: "vsc" },
	{ icon: VscBracketDot, name: "VscBracketDot", library: "vsc" },
	{ icon: VscBracketError, name: "VscBracketError", library: "vsc" },
	{ icon: VscBriefcase, name: "VscBriefcase", library: "vsc" },
	{ icon: VscBroadcast, name: "VscBroadcast", library: "vsc" },
	{ icon: VscBrowser, name: "VscBrowser", library: "vsc" },
	{ icon: VscBug, name: "VscBug", library: "vsc" },
	{ icon: VscCalendar, name: "VscCalendar", library: "vsc" },
	{ icon: VscCallIncoming, name: "VscCallIncoming", library: "vsc" },
	{ icon: VscCallOutgoing, name: "VscCallOutgoing", library: "vsc" },
	{ icon: VscCaseSensitive, name: "VscCaseSensitive", library: "vsc" },
	{ icon: VscCheckAll, name: "VscCheckAll", library: "vsc" },
	{ icon: VscCheck, name: "VscCheck", library: "vsc" },
	{ icon: VscChecklist, name: "VscChecklist", library: "vsc" },
	{ icon: VscChevronDown, name: "VscChevronDown", library: "vsc" },
	{ icon: VscChevronLeft, name: "VscChevronLeft", library: "vsc" },
	{ icon: VscChevronRight, name: "VscChevronRight", library: "vsc" },
	{ icon: VscChevronUp, name: "VscChevronUp", library: "vsc" },
	{ icon: VscChromeClose, name: "VscChromeClose", library: "vsc" },
	{ icon: VscChromeMaximize, name: "VscChromeMaximize", library: "vsc" },
	{ icon: VscChromeMinimize, name: "VscChromeMinimize", library: "vsc" },
	{ icon: VscChromeRestore, name: "VscChromeRestore", library: "vsc" },
	{ icon: VscCircleFilled, name: "VscCircleFilled", library: "vsc" },
	{ icon: VscCircleLargeFilled, name: "VscCircleLargeFilled", library: "vsc" },
	{ icon: VscCircleLargeOutline, name: "VscCircleLargeOutline", library: "vsc" },
	{ icon: VscCircleOutline, name: "VscCircleOutline", library: "vsc" },
	{ icon: VscCircleSlash, name: "VscCircleSlash", library: "vsc" },
	{ icon: VscCircuitBoard, name: "VscCircuitBoard", library: "vsc" },
	{ icon: VscClearAll, name: "VscClearAll", library: "vsc" },
	{ icon: VscClippy, name: "VscClippy", library: "vsc" },
	{ icon: VscCloseAll, name: "VscCloseAll", library: "vsc" },
	{ icon: VscClose, name: "VscClose", library: "vsc" },
	{ icon: VscCloudDownload, name: "VscCloudDownload", library: "vsc" },
	{ icon: VscCloudUpload, name: "VscCloudUpload", library: "vsc" },
	{ icon: VscCloud, name: "VscCloud", library: "vsc" },
	{ icon: VscCode, name: "VscCode", library: "vsc" },
	{ icon: VscCollapseAll, name: "VscCollapseAll", library: "vsc" },
	{ icon: VscColorMode, name: "VscColorMode", library: "vsc" },
	{ icon: VscCombine, name: "VscCombine", library: "vsc" },
	{ icon: VscCommentDiscussion, name: "VscCommentDiscussion", library: "vsc" },
	{ icon: VscComment, name: "VscComment", library: "vsc" },
	{ icon: VscCompassActive, name: "VscCompassActive", library: "vsc" },
	{ icon: VscCompassDot, name: "VscCompassDot", library: "vsc" },
	{ icon: VscCompass, name: "VscCompass", library: "vsc" },
	{ icon: VscCopy, name: "VscCopy", library: "vsc" },
	{ icon: VscCreditCard, name: "VscCreditCard", library: "vsc" },
	{ icon: VscDash, name: "VscDash", library: "vsc" },
	{ icon: VscDashboard, name: "VscDashboard", library: "vsc" },
	{ icon: VscDatabase, name: "VscDatabase", library: "vsc" },
	{ icon: VscDebugAll, name: "VscDebugAll", library: "vsc" },
	{ icon: VscDebugAltSmall, name: "VscDebugAltSmall", library: "vsc" },
	{ icon: VscDebugAlt, name: "VscDebugAlt", library: "vsc" },
	{
		icon: VscDebugBreakpointConditionalUnverified,
		name: "VscDebugBreakpointConditionalUnverified",
		library: "vsc",
	},
	{
		icon: VscDebugBreakpointConditional,
		name: "VscDebugBreakpointConditional",
		library: "vsc",
	},
	{
		icon: VscDebugBreakpointDataUnverified,
		name: "VscDebugBreakpointDataUnverified",
		library: "vsc",
	},
	{ icon: VscDebugBreakpointData, name: "VscDebugBreakpointData", library: "vsc" },
	{
		icon: VscDebugBreakpointFunctionUnverified,
		name: "VscDebugBreakpointFunctionUnverified",
		library: "vsc",
	},
	{
		icon: VscDebugBreakpointFunction,
		name: "VscDebugBreakpointFunction",
		library: "vsc",
	},
	{
		icon: VscDebugBreakpointLogUnverified,
		name: "VscDebugBreakpointLogUnverified",
		library: "vsc",
	},
	{ icon: VscDebugBreakpointLog, name: "VscDebugBreakpointLog", library: "vsc" },
	{
		icon: VscDebugBreakpointUnsupported,
		name: "VscDebugBreakpointUnsupported",
		library: "vsc",
	},
	{ icon: VscDebugConsole, name: "VscDebugConsole", library: "vsc" },
	{ icon: VscDebugContinueSmall, name: "VscDebugContinueSmall", library: "vsc" },
	{ icon: VscDebugContinue, name: "VscDebugContinue", library: "vsc" },
	{ icon: VscDebugCoverage, name: "VscDebugCoverage", library: "vsc" },
	{ icon: VscDebugDisconnect, name: "VscDebugDisconnect", library: "vsc" },
	{ icon: VscDebugLineByLine, name: "VscDebugLineByLine", library: "vsc" },
	{ icon: VscDebugPause, name: "VscDebugPause", library: "vsc" },
	{ icon: VscDebugRerun, name: "VscDebugRerun", library: "vsc" },
	{ icon: VscDebugRestartFrame, name: "VscDebugRestartFrame", library: "vsc" },
	{ icon: VscDebugRestart, name: "VscDebugRestart", library: "vsc" },
	{ icon: VscDebugReverseContinue, name: "VscDebugReverseContinue", library: "vsc" },
	{ icon: VscDebugStackframeActive, name: "VscDebugStackframeActive", library: "vsc" },
	{ icon: VscDebugStackframeDot, name: "VscDebugStackframeDot", library: "vsc" },
	{ icon: VscDebugStackframe, name: "VscDebugStackframe", library: "vsc" },
	{ icon: VscDebugStart, name: "VscDebugStart", library: "vsc" },
	{ icon: VscDebugStepBack, name: "VscDebugStepBack", library: "vsc" },
	{ icon: VscDebugStepInto, name: "VscDebugStepInto", library: "vsc" },
	{ icon: VscDebugStepOut, name: "VscDebugStepOut", library: "vsc" },
	{ icon: VscDebugStepOver, name: "VscDebugStepOver", library: "vsc" },
	{ icon: VscDebugStop, name: "VscDebugStop", library: "vsc" },
	{ icon: VscDebug, name: "VscDebug", library: "vsc" },
	{ icon: VscDesktopDownload, name: "VscDesktopDownload", library: "vsc" },
	{ icon: VscDeviceCameraVideo, name: "VscDeviceCameraVideo", library: "vsc" },
	{ icon: VscDeviceCamera, name: "VscDeviceCamera", library: "vsc" },
	{ icon: VscDeviceMobile, name: "VscDeviceMobile", library: "vsc" },
	{ icon: VscDiffAdded, name: "VscDiffAdded", library: "vsc" },
	{ icon: VscDiffIgnored, name: "VscDiffIgnored", library: "vsc" },
	{ icon: VscDiffModified, name: "VscDiffModified", library: "vsc" },
	{ icon: VscDiffRemoved, name: "VscDiffRemoved", library: "vsc" },
	{ icon: VscDiffRenamed, name: "VscDiffRenamed", library: "vsc" },
	{ icon: VscDiff, name: "VscDiff", library: "vsc" },
	{ icon: VscDiscard, name: "VscDiscard", library: "vsc" },
	{ icon: VscEdit, name: "VscEdit", library: "vsc" },
	{ icon: VscEditorLayout, name: "VscEditorLayout", library: "vsc" },
	{ icon: VscEllipsis, name: "VscEllipsis", library: "vsc" },
	{ icon: VscEmptyWindow, name: "VscEmptyWindow", library: "vsc" },
	{ icon: VscError, name: "VscError", library: "vsc" },
	{ icon: VscExclude, name: "VscExclude", library: "vsc" },
	{ icon: VscExpandAll, name: "VscExpandAll", library: "vsc" },
	{ icon: VscExport, name: "VscExport", library: "vsc" },
	{ icon: VscExtensions, name: "VscExtensions", library: "vsc" },
	{ icon: VscEyeClosed, name: "VscEyeClosed", library: "vsc" },
	{ icon: VscEye, name: "VscEye", library: "vsc" },
	{ icon: VscFeedback, name: "VscFeedback", library: "vsc" },
	{ icon: VscFileBinary, name: "VscFileBinary", library: "vsc" },
	{ icon: VscFileCode, name: "VscFileCode", library: "vsc" },
	{ icon: VscFileMedia, name: "VscFileMedia", library: "vsc" },
	{ icon: VscFilePdf, name: "VscFilePdf", library: "vsc" },
	{ icon: VscFileSubmodule, name: "VscFileSubmodule", library: "vsc" },
	{ icon: VscFileSymlinkDirectory, name: "VscFileSymlinkDirectory", library: "vsc" },
	{ icon: VscFileSymlinkFile, name: "VscFileSymlinkFile", library: "vsc" },
	{ icon: VscFileZip, name: "VscFileZip", library: "vsc" },
	{ icon: VscFile, name: "VscFile", library: "vsc" },
	{ icon: VscFiles, name: "VscFiles", library: "vsc" },
	{ icon: VscFilterFilled, name: "VscFilterFilled", library: "vsc" },
	{ icon: VscFilter, name: "VscFilter", library: "vsc" },
	{ icon: VscFlame, name: "VscFlame", library: "vsc" },
	{ icon: VscFoldDown, name: "VscFoldDown", library: "vsc" },
	{ icon: VscFoldUp, name: "VscFoldUp", library: "vsc" },
	{ icon: VscFold, name: "VscFold", library: "vsc" },
	{ icon: VscFolderActive, name: "VscFolderActive", library: "vsc" },
	{ icon: VscFolderLibrary, name: "VscFolderLibrary", library: "vsc" },
	{ icon: VscFolderOpened, name: "VscFolderOpened", library: "vsc" },
	{ icon: VscFolder, name: "VscFolder", library: "vsc" },
	{ icon: VscGear, name: "VscGear", library: "vsc" },
	{ icon: VscGift, name: "VscGift", library: "vsc" },
	{ icon: VscGistSecret, name: "VscGistSecret", library: "vsc" },
	{ icon: VscGist, name: "VscGist", library: "vsc" },
	{ icon: VscGitCommit, name: "VscGitCommit", library: "vsc" },
	{ icon: VscGitCompare, name: "VscGitCompare", library: "vsc" },
	{ icon: VscGitMerge, name: "VscGitMerge", library: "vsc" },
	{ icon: VscGitPullRequestClosed, name: "VscGitPullRequestClosed", library: "vsc" },
	{ icon: VscGitPullRequestCreate, name: "VscGitPullRequestCreate", library: "vsc" },
	{ icon: VscGitPullRequestDraft, name: "VscGitPullRequestDraft", library: "vsc" },
	{ icon: VscGitPullRequest, name: "VscGitPullRequest", library: "vsc" },
	{ icon: VscGithubAction, name: "VscGithubAction", library: "vsc" },
	{ icon: VscGithubAlt, name: "VscGithubAlt", library: "vsc" },
	{ icon: VscGithubInverted, name: "VscGithubInverted", library: "vsc" },
	{ icon: VscGithub, name: "VscGithub", library: "vsc" },
	{ icon: VscGlobe, name: "VscGlobe", library: "vsc" },
	{ icon: VscGoToFile, name: "VscGoToFile", library: "vsc" },
	{ icon: VscGrabber, name: "VscGrabber", library: "vsc" },
	{ icon: VscGraphLeft, name: "VscGraphLeft", library: "vsc" },
	{ icon: VscGraphLine, name: "VscGraphLine", library: "vsc" },
	{ icon: VscGraphScatter, name: "VscGraphScatter", library: "vsc" },
	{ icon: VscGraph, name: "VscGraph", library: "vsc" },
	{ icon: VscGripper, name: "VscGripper", library: "vsc" },
	{ icon: VscGroupByRefType, name: "VscGroupByRefType", library: "vsc" },
	{ icon: VscHeart, name: "VscHeart", library: "vsc" },
	{ icon: VscHistory, name: "VscHistory", library: "vsc" },
	{ icon: VscHome, name: "VscHome", library: "vsc" },
	{ icon: VscHorizontalRule, name: "VscHorizontalRule", library: "vsc" },
	{ icon: VscHubot, name: "VscHubot", library: "vsc" },
	{ icon: VscInbox, name: "VscInbox", library: "vsc" },
	{ icon: VscInfo, name: "VscInfo", library: "vsc" },
	{ icon: VscInspect, name: "VscInspect", library: "vsc" },
	{ icon: VscIssueDraft, name: "VscIssueDraft", library: "vsc" },
	{ icon: VscIssueReopened, name: "VscIssueReopened", library: "vsc" },
	{ icon: VscIssues, name: "VscIssues", library: "vsc" },
	{ icon: VscItalic, name: "VscItalic", library: "vsc" },
	{ icon: VscJersey, name: "VscJersey", library: "vsc" },
	{ icon: VscJson, name: "VscJson", library: "vsc" },
	{ icon: VscKebabVertical, name: "VscKebabVertical", library: "vsc" },
	{ icon: VscKey, name: "VscKey", library: "vsc" },
	{ icon: VscLaw, name: "VscLaw", library: "vsc" },
	{ icon: VscLayersActive, name: "VscLayersActive", library: "vsc" },
	{ icon: VscLayersDot, name: "VscLayersDot", library: "vsc" },
	{ icon: VscLayers, name: "VscLayers", library: "vsc" },
	{ icon: VscLibrary, name: "VscLibrary", library: "vsc" },
	{ icon: VscLightbulbAutofix, name: "VscLightbulbAutofix", library: "vsc" },
	{ icon: VscLightbulb, name: "VscLightbulb", library: "vsc" },
	{ icon: VscLinkExternal, name: "VscLinkExternal", library: "vsc" },
	{ icon: VscLink, name: "VscLink", library: "vsc" },
	{ icon: VscListFilter, name: "VscListFilter", library: "vsc" },
	{ icon: VscListFlat, name: "VscListFlat", library: "vsc" },
	{ icon: VscListOrdered, name: "VscListOrdered", library: "vsc" },
	{ icon: VscListSelection, name: "VscListSelection", library: "vsc" },
	{ icon: VscListTree, name: "VscListTree", library: "vsc" },
	{ icon: VscListUnordered, name: "VscListUnordered", library: "vsc" },
	{ icon: VscLiveShare, name: "VscLiveShare", library: "vsc" },
	{ icon: VscLoading, name: "VscLoading", library: "vsc" },
	{ icon: VscLocation, name: "VscLocation", library: "vsc" },
	{ icon: VscLock, name: "VscLock", library: "vsc" },
	{ icon: VscMagnet, name: "VscMagnet", library: "vsc" },
	{ icon: VscMailRead, name: "VscMailRead", library: "vsc" },
	{ icon: VscMail, name: "VscMail", library: "vsc" },
	{ icon: VscMarkdown, name: "VscMarkdown", library: "vsc" },
	{ icon: VscMegaphone, name: "VscMegaphone", library: "vsc" },
	{ icon: VscMention, name: "VscMention", library: "vsc" },
	{ icon: VscMenu, name: "VscMenu", library: "vsc" },
	{ icon: VscMerge, name: "VscMerge", library: "vsc" },
	{ icon: VscMilestone, name: "VscMilestone", library: "vsc" },
	{ icon: VscMirror, name: "VscMirror", library: "vsc" },
	{ icon: VscMortarBoard, name: "VscMortarBoard", library: "vsc" },
	{ icon: VscMove, name: "VscMove", library: "vsc" },
	{ icon: VscMultipleWindows, name: "VscMultipleWindows", library: "vsc" },
	{ icon: VscMute, name: "VscMute", library: "vsc" },
	{ icon: VscNewFile, name: "VscNewFile", library: "vsc" },
	{ icon: VscNewFolder, name: "VscNewFolder", library: "vsc" },
	{ icon: VscNoNewline, name: "VscNoNewline", library: "vsc" },
	{ icon: VscNote, name: "VscNote", library: "vsc" },
	{ icon: VscNotebookTemplate, name: "VscNotebookTemplate", library: "vsc" },
	{ icon: VscNotebook, name: "VscNotebook", library: "vsc" },
	{ icon: VscOctoface, name: "VscOctoface", library: "vsc" },
	{ icon: VscOpenPreview, name: "VscOpenPreview", library: "vsc" },
	{ icon: VscOrganization, name: "VscOrganization", library: "vsc" },
	{ icon: VscOutput, name: "VscOutput", library: "vsc" },
	{ icon: VscPackage, name: "VscPackage", library: "vsc" },
	{ icon: VscPaintcan, name: "VscPaintcan", library: "vsc" },
	{ icon: VscPassFilled, name: "VscPassFilled", library: "vsc" },
	{ icon: VscPass, name: "VscPass", library: "vsc" },
	{ icon: VscPersonAdd, name: "VscPersonAdd", library: "vsc" },
	{ icon: VscPerson, name: "VscPerson", library: "vsc" },
	{ icon: VscPieChart, name: "VscPieChart", library: "vsc" },
	{ icon: VscPin, name: "VscPin", library: "vsc" },
	{ icon: VscPinnedDirty, name: "VscPinnedDirty", library: "vsc" },
	{ icon: VscPinned, name: "VscPinned", library: "vsc" },
	{ icon: VscPlayCircle, name: "VscPlayCircle", library: "vsc" },
	{ icon: VscPlay, name: "VscPlay", library: "vsc" },
	{ icon: VscPlug, name: "VscPlug", library: "vsc" },
	{ icon: VscPreserveCase, name: "VscPreserveCase", library: "vsc" },
	{ icon: VscPreview, name: "VscPreview", library: "vsc" },
	{ icon: VscPrimitiveSquare, name: "VscPrimitiveSquare", library: "vsc" },
	{ icon: VscProject, name: "VscProject", library: "vsc" },
	{ icon: VscPulse, name: "VscPulse", library: "vsc" },
	{ icon: VscQuestion, name: "VscQuestion", library: "vsc" },
	{ icon: VscQuote, name: "VscQuote", library: "vsc" },
	{ icon: VscRadioTower, name: "VscRadioTower", library: "vsc" },
	{ icon: VscReactions, name: "VscReactions", library: "vsc" },
	{ icon: VscRecordKeys, name: "VscRecordKeys", library: "vsc" },
	{ icon: VscRecord, name: "VscRecord", library: "vsc" },
	{ icon: VscRedo, name: "VscRedo", library: "vsc" },
	{ icon: VscReferences, name: "VscReferences", library: "vsc" },
	{ icon: VscRefresh, name: "VscRefresh", library: "vsc" },
	{ icon: VscRegex, name: "VscRegex", library: "vsc" },
	{ icon: VscRemoteExplorer, name: "VscRemoteExplorer", library: "vsc" },
	{ icon: VscRemote, name: "VscRemote", library: "vsc" },
	{ icon: VscRemove, name: "VscRemove", library: "vsc" },
	{ icon: VscReplaceAll, name: "VscReplaceAll", library: "vsc" },
	{ icon: VscReplace, name: "VscReplace", library: "vsc" },
	{ icon: VscReply, name: "VscReply", library: "vsc" },
	{ icon: VscRepoClone, name: "VscRepoClone", library: "vsc" },
	{ icon: VscRepoForcePush, name: "VscRepoForcePush", library: "vsc" },
	{ icon: VscRepoForked, name: "VscRepoForked", library: "vsc" },
	{ icon: VscRepoPull, name: "VscRepoPull", library: "vsc" },
	{ icon: VscRepoPush, name: "VscRepoPush", library: "vsc" },
	{ icon: VscRepo, name: "VscRepo", library: "vsc" },
	{ icon: VscReport, name: "VscReport", library: "vsc" },
	{ icon: VscRequestChanges, name: "VscRequestChanges", library: "vsc" },
	{ icon: VscRocket, name: "VscRocket", library: "vsc" },
	{ icon: VscRootFolderOpened, name: "VscRootFolderOpened", library: "vsc" },
	{ icon: VscRootFolder, name: "VscRootFolder", library: "vsc" },
	{ icon: VscRss, name: "VscRss", library: "vsc" },
	{ icon: VscRuby, name: "VscRuby", library: "vsc" },
	{ icon: VscRunAbove, name: "VscRunAbove", library: "vsc" },
	{ icon: VscRunAll, name: "VscRunAll", library: "vsc" },
	{ icon: VscRunBelow, name: "VscRunBelow", library: "vsc" },
	{ icon: VscRunErrors, name: "VscRunErrors", library: "vsc" },
	{ icon: VscSaveAll, name: "VscSaveAll", library: "vsc" },
	{ icon: VscSaveAs, name: "VscSaveAs", library: "vsc" },
	{ icon: VscSave, name: "VscSave", library: "vsc" },
	{ icon: VscScreenFull, name: "VscScreenFull", library: "vsc" },
	{ icon: VscScreenNormal, name: "VscScreenNormal", library: "vsc" },
	{ icon: VscSearchStop, name: "VscSearchStop", library: "vsc" },
	{ icon: VscSearch, name: "VscSearch", library: "vsc" },
	{ icon: VscServerEnvironment, name: "VscServerEnvironment", library: "vsc" },
	{ icon: VscServerProcess, name: "VscServerProcess", library: "vsc" },
	{ icon: VscServer, name: "VscServer", library: "vsc" },
	{ icon: VscSettingsGear, name: "VscSettingsGear", library: "vsc" },
	{ icon: VscSettings, name: "VscSettings", library: "vsc" },
	{ icon: VscShield, name: "VscShield", library: "vsc" },
	{ icon: VscSignIn, name: "VscSignIn", library: "vsc" },
	{ icon: VscSignOut, name: "VscSignOut", library: "vsc" },
	{ icon: VscSmiley, name: "VscSmiley", library: "vsc" },
	{ icon: VscSortPrecedence, name: "VscSortPrecedence", library: "vsc" },
	{ icon: VscSourceControl, name: "VscSourceControl", library: "vsc" },
	{ icon: VscSplitHorizontal, name: "VscSplitHorizontal", library: "vsc" },
	{ icon: VscSplitVertical, name: "VscSplitVertical", library: "vsc" },
	{ icon: VscSquirrel, name: "VscSquirrel", library: "vsc" },
	{ icon: VscStarEmpty, name: "VscStarEmpty", library: "vsc" },
	{ icon: VscStarFull, name: "VscStarFull", library: "vsc" },
	{ icon: VscStarHalf, name: "VscStarHalf", library: "vsc" },
	{ icon: VscStopCircle, name: "VscStopCircle", library: "vsc" },
	{ icon: VscSymbolArray, name: "VscSymbolArray", library: "vsc" },
	{ icon: VscSymbolBoolean, name: "VscSymbolBoolean", library: "vsc" },
	{ icon: VscSymbolClass, name: "VscSymbolClass", library: "vsc" },
	{ icon: VscSymbolColor, name: "VscSymbolColor", library: "vsc" },
	{ icon: VscSymbolConstant, name: "VscSymbolConstant", library: "vsc" },
	{ icon: VscSymbolEnumMember, name: "VscSymbolEnumMember", library: "vsc" },
	{ icon: VscSymbolEnum, name: "VscSymbolEnum", library: "vsc" },
	{ icon: VscSymbolEvent, name: "VscSymbolEvent", library: "vsc" },
	{ icon: VscSymbolField, name: "VscSymbolField", library: "vsc" },
	{ icon: VscSymbolFile, name: "VscSymbolFile", library: "vsc" },
	{ icon: VscSymbolInterface, name: "VscSymbolInterface", library: "vsc" },
	{ icon: VscSymbolKey, name: "VscSymbolKey", library: "vsc" },
	{ icon: VscSymbolKeyword, name: "VscSymbolKeyword", library: "vsc" },
	{ icon: VscSymbolMethod, name: "VscSymbolMethod", library: "vsc" },
	{ icon: VscSymbolMisc, name: "VscSymbolMisc", library: "vsc" },
	{ icon: VscSymbolNamespace, name: "VscSymbolNamespace", library: "vsc" },
	{ icon: VscSymbolNumeric, name: "VscSymbolNumeric", library: "vsc" },
	{ icon: VscSymbolOperator, name: "VscSymbolOperator", library: "vsc" },
	{ icon: VscSymbolParameter, name: "VscSymbolParameter", library: "vsc" },
	{ icon: VscSymbolProperty, name: "VscSymbolProperty", library: "vsc" },
	{ icon: VscSymbolRuler, name: "VscSymbolRuler", library: "vsc" },
	{ icon: VscSymbolSnippet, name: "VscSymbolSnippet", library: "vsc" },
	{ icon: VscSymbolString, name: "VscSymbolString", library: "vsc" },
	{ icon: VscSymbolStructure, name: "VscSymbolStructure", library: "vsc" },
	{ icon: VscSymbolVariable, name: "VscSymbolVariable", library: "vsc" },
	{ icon: VscSyncIgnored, name: "VscSyncIgnored", library: "vsc" },
	{ icon: VscSync, name: "VscSync", library: "vsc" },
	{ icon: VscTable, name: "VscTable", library: "vsc" },
	{ icon: VscTag, name: "VscTag", library: "vsc" },
	{ icon: VscTasklist, name: "VscTasklist", library: "vsc" },
	{ icon: VscTelescope, name: "VscTelescope", library: "vsc" },
	{ icon: VscTerminalBash, name: "VscTerminalBash", library: "vsc" },
	{ icon: VscTerminalCmd, name: "VscTerminalCmd", library: "vsc" },
	{ icon: VscTerminalDebian, name: "VscTerminalDebian", library: "vsc" },
	{ icon: VscTerminalLinux, name: "VscTerminalLinux", library: "vsc" },
	{ icon: VscTerminalPowershell, name: "VscTerminalPowershell", library: "vsc" },
	{ icon: VscTerminalTmux, name: "VscTerminalTmux", library: "vsc" },
	{ icon: VscTerminalUbuntu, name: "VscTerminalUbuntu", library: "vsc" },
	{ icon: VscTerminal, name: "VscTerminal", library: "vsc" },
	{ icon: VscTextSize, name: "VscTextSize", library: "vsc" },
	{ icon: VscThreeBars, name: "VscThreeBars", library: "vsc" },
	{ icon: VscThumbsdown, name: "VscThumbsdown", library: "vsc" },
	{ icon: VscThumbsup, name: "VscThumbsup", library: "vsc" },
	{ icon: VscTools, name: "VscTools", library: "vsc" },
	{ icon: VscTrash, name: "VscTrash", library: "vsc" },
	{ icon: VscTriangleDown, name: "VscTriangleDown", library: "vsc" },
	{ icon: VscTriangleLeft, name: "VscTriangleLeft", library: "vsc" },
	{ icon: VscTriangleRight, name: "VscTriangleRight", library: "vsc" },
	{ icon: VscTriangleUp, name: "VscTriangleUp", library: "vsc" },
	{ icon: VscTwitter, name: "VscTwitter", library: "vsc" },
	{ icon: VscTypeHierarchySub, name: "VscTypeHierarchySub", library: "vsc" },
	{ icon: VscTypeHierarchySuper, name: "VscTypeHierarchySuper", library: "vsc" },
	{ icon: VscTypeHierarchy, name: "VscTypeHierarchy", library: "vsc" },
	{ icon: VscUnfold, name: "VscUnfold", library: "vsc" },
	{ icon: VscUngroupByRefType, name: "VscUngroupByRefType", library: "vsc" },
	{ icon: VscUnlock, name: "VscUnlock", library: "vsc" },
	{ icon: VscUnmute, name: "VscUnmute", library: "vsc" },
	{ icon: VscUnverified, name: "VscUnverified", library: "vsc" },
	{ icon: VscVariableGroup, name: "VscVariableGroup", library: "vsc" },
	{ icon: VscVerified, name: "VscVerified", library: "vsc" },
	{ icon: VscVersions, name: "VscVersions", library: "vsc" },
	{ icon: VscVmActive, name: "VscVmActive", library: "vsc" },
	{ icon: VscVmConnect, name: "VscVmConnect", library: "vsc" },
	{ icon: VscVmOutline, name: "VscVmOutline", library: "vsc" },
	{ icon: VscVmRunning, name: "VscVmRunning", library: "vsc" },
	{ icon: VscVm, name: "VscVm", library: "vsc" },
	{ icon: VscWand, name: "VscWand", library: "vsc" },
	{ icon: VscWarning, name: "VscWarning", library: "vsc" },
	{ icon: VscWatch, name: "VscWatch", library: "vsc" },
	{ icon: VscWhitespace, name: "VscWhitespace", library: "vsc" },
	{ icon: VscWholeWord, name: "VscWholeWord", library: "vsc" },
	{ icon: VscWindow, name: "VscWindow", library: "vsc" },
	{ icon: VscWordWrap, name: "VscWordWrap", library: "vsc" },
	{ icon: VscWorkspaceTrusted, name: "VscWorkspaceTrusted", library: "vsc" },
	{ icon: VscWorkspaceUnknown, name: "VscWorkspaceUnknown", library: "vsc" },
	{ icon: VscWorkspaceUntrusted, name: "VscWorkspaceUntrusted", library: "vsc" },
	{ icon: VscZoomIn, name: "VscZoomIn", library: "vsc" },
	{ icon: VscZoomOut, name: "VscZoomOut", library: "vsc" },
];

export default result;
