import {
	CgAbstract,
	CgAddR,
	CgAdd,
	CgAdidas,
	CgAirplane,
	CgAlarm,
	CgAlbum,
	CgAlignBottom,
	CgAlignCenter,
	CgAlignLeft,
	CgAlignMiddle,
	CgAlignRight,
	CgAlignTop,
	CgAnchor,
	CgAppleWatch,
	CgArrangeBack,
	CgArrangeFront,
	CgArrowAlignH,
	CgArrowAlignV,
	CgArrowBottomLeftO,
	CgArrowBottomLeftR,
	CgArrowBottomLeft,
	CgArrowBottomRightO,
	CgArrowBottomRightR,
	CgArrowBottomRight,
	CgArrowDownO,
	CgArrowDownR,
	CgArrowDown,
	CgArrowLeftO,
	CgArrowLeftR,
	CgArrowLeft,
	CgArrowLongDownC,
	CgArrowLongDownE,
	CgArrowLongDownL,
	CgArrowLongDownR,
	CgArrowLongDown,
	CgArrowLongLeftC,
	CgArrowLongLeftE,
	CgArrowLongLeftL,
	CgArrowLongLeftR,
	CgArrowLongLeft,
	CgArrowLongRightC,
	CgArrowLongRightE,
	CgArrowLongRightL,
	CgArrowLongRightR,
	CgArrowLongRight,
	CgArrowLongUpC,
	CgArrowLongUpE,
	CgArrowLongUpL,
	CgArrowLongUpR,
	CgArrowLongUp,
	CgArrowRightO,
	CgArrowRightR,
	CgArrowRight,
	CgArrowTopLeftO,
	CgArrowTopLeftR,
	CgArrowTopLeft,
	CgArrowTopRightO,
	CgArrowTopRightR,
	CgArrowTopRight,
	CgArrowUpO,
	CgArrowUpR,
	CgArrowUp,
	CgArrowsBreakeH,
	CgArrowsBreakeV,
	CgArrowsExchangeAltV,
	CgArrowsExchangeAlt,
	CgArrowsExchangeV,
	CgArrowsExchange,
	CgArrowsExpandDownLeft,
	CgArrowsExpandDownRight,
	CgArrowsExpandLeftAlt,
	CgArrowsExpandLeft,
	CgArrowsExpandRightAlt,
	CgArrowsExpandRight,
	CgArrowsExpandUpLeft,
	CgArrowsExpandUpRight,
	CgArrowsHAlt,
	CgArrowsH,
	CgArrowsMergeAltH,
	CgArrowsMergeAltV,
	CgArrowsScrollH,
	CgArrowsScrollV,
	CgArrowsShrinkH,
	CgArrowsShrinkV,
	CgArrowsVAlt,
	CgArrowsV,
	CgAssign,
	CgAsterisk,
	CgAtlasian,
	CgAttachment,
	CgAttribution,
	CgAwards,
	CgBackspace,
	CgBandAid,
	CgBatteryEmpty,
	CgBatteryFull,
	CgBattery,
	CgBee,
	CgBell,
	CgBitbucket,
	CgBlock,
	CgBmw,
	CgBoard,
	CgBolt,
	CgBookmark,
	CgBorderAll,
	CgBorderBottom,
	CgBorderLeft,
	CgBorderRight,
	CgBorderStyleDashed,
	CgBorderStyleDotted,
	CgBorderStyleSolid,
	CgBorderTop,
	CgBot,
	CgBowl,
	CgBox,
	CgBoy,
	CgBrackets,
	CgBriefcase,
	CgBrowse,
	CgBrowser,
	CgBrush,
	CgBulb,
	CgCPlusPlus,
	CgCalculator,
	CgCalendarDates,
	CgCalendarDue,
	CgCalendarNext,
	CgCalendarToday,
	CgCalendarTwo,
	CgCalendar,
	CgCalibrate,
	CgCamera,
	CgCap,
	CgCaptions,
	CgCardClubs,
	CgCardDiamonds,
	CgCardHearts,
	CgCardSpades,
	CgCarousel,
	CgCast,
	CgChanel,
	CgChart,
	CgCheckO,
	CgCheckR,
	CgCheck,
	CgChevronDoubleDownO,
	CgChevronDoubleDownR,
	CgChevronDoubleDown,
	CgChevronDoubleLeftO,
	CgChevronDoubleLeftR,
	CgChevronDoubleLeft,
	CgChevronDoubleRightO,
	CgChevronDoubleRightR,
	CgChevronDoubleRight,
	CgChevronDoubleUpO,
	CgChevronDoubleUpR,
	CgChevronDoubleUp,
	CgChevronDownO,
	CgChevronDownR,
	CgChevronDown,
	CgChevronLeftO,
	CgChevronLeftR,
	CgChevronLeft,
	CgChevronRightO,
	CgChevronRightR,
	CgChevronRight,
	CgChevronUpO,
	CgChevronUpR,
	CgChevronUp,
	CgCircleci,
	CgClapperBoard,
	CgClipboard,
	CgCloseO,
	CgCloseR,
	CgClose,
	CgCloud,
	CgCodeClimate,
	CgCodeSlash,
	CgCode,
	CgCoffee,
	CgCollage,
	CgColorBucket,
	CgColorPicker,
	CgComedyCentral,
	CgComment,
	CgCommunity,
	CgComponents,
	CgCompressLeft,
	CgCompressRight,
	CgCompressV,
	CgCompress,
	CgController,
	CgCopy,
	CgCopyright,
	CgCornerDoubleDownLeft,
	CgCornerDoubleDownRight,
	CgCornerDoubleLeftDown,
	CgCornerDoubleLeftUp,
	CgCornerDoubleRightDown,
	CgCornerDoubleRightUp,
	CgCornerDoubleUpLeft,
	CgCornerDoubleUpRight,
	CgCornerDownLeft,
	CgCornerDownRight,
	CgCornerLeftDown,
	CgCornerLeftUp,
	CgCornerRightDown,
	CgCornerRightUp,
	CgCornerUpLeft,
	CgCornerUpRight,
	CgCreditCard,
	CgCrop,
	CgCross,
	CgCrowdfire,
	CgCrown,
	CgDanger,
	CgDarkMode,
	CgData,
	CgDatabase,
	CgDebug,
	CgDesignmodo,
	CgDesktop,
	CgDetailsLess,
	CgDetailsMore,
	CgDialpad,
	CgDice1,
	CgDice2,
	CgDice3,
	CgDice4,
	CgDice5,
	CgDice6,
	CgDigitalocean,
	CgDisc,
	CgDisplayFlex,
	CgDisplayFullwidth,
	CgDisplayGrid,
	CgDisplaySpacing,
	CgDistributeHorizontal,
	CgDistributeVertical,
	CgDockBottom,
	CgDockLeft,
	CgDockRight,
	CgDockWindow,
	CgDolby,
	CgDollar,
	CgDribbble,
	CgDrive,
	CgDropInvert,
	CgDropOpacity,
	CgDrop,
	CgDuplicate,
	CgEditBlackPoint,
	CgEditContrast,
	CgEditExposure,
	CgEditFade,
	CgEditFlipH,
	CgEditFlipV,
	CgEditHighlight,
	CgEditMarkup,
	CgEditMask,
	CgEditNoise,
	CgEditShadows,
	CgEditStraight,
	CgEditUnmask,
	CgEject,
	CgEnter,
	CgErase,
	CgEreader,
	CgEricsson,
	CgEthernet,
	CgEuro,
	CgEventbrite,
	CgExpand,
	CgExport,
	CgExtensionAdd,
	CgExtensionAlt,
	CgExtensionRemove,
	CgExtension,
	CgExternal,
	CgEyeAlt,
	CgEye,
	CgFacebook,
	CgFeed,
	CgFigma,
	CgFileAdd,
	CgFileDocument,
	CgFileRemove,
	CgFile,
	CgFilm,
	CgFilters,
	CgFlagAlt,
	CgFlag,
	CgFolderAdd,
	CgFolderRemove,
	CgFolder,
	CgFontHeight,
	CgFontSpacing,
	CgFormatBold,
	CgFormatCenter,
	CgFormatColor,
	CgFormatHeading,
	CgFormatIndentDecrease,
	CgFormatIndentIncrease,
	CgFormatItalic,
	CgFormatJustify,
	CgFormatLeft,
	CgFormatLineHeight,
	CgFormatRight,
	CgFormatSeparator,
	CgFormatSlash,
	CgFormatStrike,
	CgFormatText,
	CgFormatUnderline,
	CgFormatUppercase,
	CgFramer,
	CgGames,
	CgGenderFemale,
	CgGenderMale,
	CgGhostCharacter,
	CgGhost,
	CgGift,
	CgGirl,
	CgGitBranch,
	CgGitCommit,
	CgGitFork,
	CgGitPull,
	CgGitter,
	CgGlassAlt,
	CgGlass,
	CgGlobeAlt,
	CgGlobe,
	CgGoogleTasks,
	CgGoogle,
	CgGym,
	CgHashtag,
	CgHeadset,
	CgHeart,
	CgHello,
	CgHomeAlt,
	CgHomeScreen,
	CgHome,
	CgIcecream,
	CgIfDesign,
	CgImage,
	CgImport,
	CgInbox,
	CgIndieHackers,
	CgInfinity,
	CgInfo,
	CgInpicture,
	CgInsertAfterO,
	CgInsertAfterR,
	CgInsertAfter,
	CgInsertBeforeO,
	CgInsertBeforeR,
	CgInsertBefore,
	CgInsights,
	CgInstagram,
	CgInternal,
	CgKey,
	CgKeyboard,
	CgKeyhole,
	CgLaptop,
	CgLastpass,
	CgLayoutGridSmall,
	CgLayoutGrid,
	CgLayoutList,
	CgLayoutPin,
	CgLinear,
	CgLink,
	CgListTree,
	CgList,
	CgLivePhoto,
	CgLoadbarAlt,
	CgLoadbarDoc,
	CgLoadbarSound,
	CgLoadbar,
	CgLockUnlock,
	CgLock,
	CgLogIn,
	CgLogOff,
	CgLogOut,
	CgLoupe,
	CgMagnet,
	CgMailForward,
	CgMailOpen,
	CgMailReply,
	CgMail,
	CgMathDivide,
	CgMathEqual,
	CgMathMinus,
	CgMathPercent,
	CgMathPlus,
	CgMaximizeAlt,
	CgMaximize,
	CgMaze,
	CgMediaLive,
	CgMediaPodcast,
	CgMenuBoxed,
	CgMenuCake,
	CgMenuCheese,
	CgMenuGridO,
	CgMenuGridR,
	CgMenuHotdog,
	CgMenuLeftAlt,
	CgMenuLeft,
	CgMenuMotion,
	CgMenuOreos,
	CgMenuRightAlt,
	CgMenuRight,
	CgMenuRound,
	CgMenu,
	CgMergeHorizontal,
	CgMergeVertical,
	CgMic,
	CgMicrobit,
	CgMicrosoft,
	CgMiniPlayer,
	CgMinimizeAlt,
	CgMinimize,
	CgModem,
	CgMonday,
	CgMoon,
	CgMoreAlt,
	CgMoreO,
	CgMoreR,
	CgMoreVerticalAlt,
	CgMoreVerticalO,
	CgMoreVerticalR,
	CgMoreVertical,
	CgMore,
	CgMouse,
	CgMoveDown,
	CgMoveLeft,
	CgMoveRight,
	CgMoveTask,
	CgMoveUp,
	CgMusicNote,
	CgMusicSpeaker,
	CgMusic,
	CgNametag,
	CgNotes,
	CgNotifications,
	CgNpm,
	CgOculus,
	CgOpenCollective,
	CgOptions,
	CgOrganisation,
	CgOverflow,
	CgPacman,
	CgPassword,
	CgPathBack,
	CgPathCrop,
	CgPathDivide,
	CgPathExclude,
	CgPathFront,
	CgPathIntersect,
	CgPathOutline,
	CgPathTrim,
	CgPathUnite,
	CgPatreon,
	CgPaypal,
	CgPen,
	CgPentagonBottomLeft,
	CgPentagonBottomRight,
	CgPentagonDown,
	CgPentagonLeft,
	CgPentagonRight,
	CgPentagonTopLeft,
	CgPentagonTopRight,
	CgPentagonUp,
	CgPerformance,
	CgPexels,
	CgPhone,
	CgPhotoscan,
	CgPiano,
	CgPill,
	CgPinAlt,
	CgPinBottom,
	CgPinTop,
	CgPin,
	CgPlayBackwards,
	CgPlayButtonO,
	CgPlayButtonR,
	CgPlayButton,
	CgPlayForwards,
	CgPlayListAdd,
	CgPlayListCheck,
	CgPlayListRemove,
	CgPlayListSearch,
	CgPlayList,
	CgPlayPauseO,
	CgPlayPauseR,
	CgPlayPause,
	CgPlayStopO,
	CgPlayStopR,
	CgPlayStop,
	CgPlayTrackNextO,
	CgPlayTrackNextR,
	CgPlayTrackNext,
	CgPlayTrackPrevO,
	CgPlayTrackPrevR,
	CgPlayTrackPrev,
	CgPlug,
	CgPocket,
	CgPokemon,
	CgPolaroid,
	CgPoll,
	CgPresentation,
	CgPrinter,
	CgProductHunt,
	CgProfile,
	CgPullClear,
	CgPushChevronDownO,
	CgPushChevronDownR,
	CgPushChevronDown,
	CgPushChevronLeftO,
	CgPushChevronLeftR,
	CgPushChevronLeft,
	CgPushChevronRightO,
	CgPushChevronRightR,
	CgPushChevronRight,
	CgPushChevronUpO,
	CgPushChevronUpR,
	CgPushChevronUp,
	CgPushDown,
	CgPushLeft,
	CgPushRight,
	CgPushUp,
	CgQr,
	CgQuoteO,
	CgQuote,
	CgRadioCheck,
	CgRadioChecked,
	CgRatio,
	CgRead,
	CgReadme,
	CgRecord,
	CgRedo,
	CgRemote,
	CgRemoveR,
	CgRemove,
	CgRename,
	CgReorder,
	CgRepeat,
	CgRing,
	CgRowFirst,
	CgRowLast,
	CgRuler,
	CgSandClock,
	CgScan,
	CgScreenMirror,
	CgScreenShot,
	CgScreenWide,
	CgScreen,
	CgScrollH,
	CgScrollV,
	CgSearchFound,
	CgSearchLoading,
	CgSearch,
	CgSelectO,
	CgSelectR,
	CgSelect,
	CgServer,
	CgServerless,
	CgShapeCircle,
	CgShapeHalfCircle,
	CgShapeHexagon,
	CgShapeRhombus,
	CgShapeSquare,
	CgShapeTriangle,
	CgShapeZigzag,
	CgShare,
	CgShield,
	CgShoppingBag,
	CgShoppingCart,
	CgShortcut,
	CgShutterstock,
	CgSidebarOpen,
	CgSidebarRight,
	CgSidebar,
	CgSignal,
	CgSize,
	CgSketch,
	CgSlack,
	CgSleep,
	CgSmartHomeBoiler,
	CgSmartHomeCooker,
	CgSmartHomeHeat,
	CgSmartHomeLight,
	CgSmartHomeRefrigerator,
	CgSmartHomeWashMachine,
	CgSmartphoneChip,
	CgSmartphoneRam,
	CgSmartphoneShake,
	CgSmartphone,
	CgSmileMouthOpen,
	CgSmileNeutral,
	CgSmileNoMouth,
	CgSmileNone,
	CgSmileSad,
	CgSmileUpside,
	CgSmile,
	CgSoftwareDownload,
	CgSoftwareUpload,
	CgSortAz,
	CgSortZa,
	CgSpaceBetweenV,
	CgSpaceBetween,
	CgSpectrum,
	CgSpinnerAlt,
	CgSpinnerTwoAlt,
	CgSpinnerTwo,
	CgSpinner,
	CgSquare,
	CgStack,
	CgStark,
	CgStopwatch,
	CgStories,
	CgStudio,
	CgStyle,
	CgSun,
	CgSupport,
	CgSwapVertical,
	CgSwap,
	CgSweden,
	CgSwiss,
	CgSync,
	CgTab,
	CgTag,
	CgTally,
	CgTapDouble,
	CgTapSingle,
	CgTemplate,
	CgTennis,
	CgTerminal,
	CgTerrain,
	CgThermometer,
	CgThermostat,
	CgTikcode,
	CgTime,
	CgTimelapse,
	CgTimer,
	CgToday,
	CgToggleOff,
	CgToggleOn,
	CgToggleSquareOff,
	CgToggleSquare,
	CgToolbarBottom,
	CgToolbarLeft,
	CgToolbarRight,
	CgToolbarTop,
	CgToolbox,
	CgTouchpad,
	CgTrack,
	CgTranscript,
	CgTrashEmpty,
	CgTrash,
	CgTree,
	CgTrees,
	CgTrello,
	CgTrendingDown,
	CgTrending,
	CgTrophy,
	CgTv,
	CgTwilio,
	CgTwitter,
	CgUiKit,
	CgUmbrella,
	CgUnavailable,
	CgUnblock,
	CgUndo,
	CgUnfold,
	CgUnsplash,
	CgUsbC,
	CgUsb,
	CgUserAdd,
	CgUserList,
	CgUserRemove,
	CgUser,
	CgUserlane,
	CgViewCols,
	CgViewComfortable,
	CgViewDay,
	CgViewGrid,
	CgViewList,
	CgViewMonth,
	CgViewSplit,
	CgVinyl,
	CgVoicemailO,
	CgVoicemailR,
	CgVoicemail,
	CgVolume,
	CgWebcam,
	CgWebsite,
	CgWindows,
	CgWorkAlt,
	CgYinyang,
	CgYoutube,
	CgZeit,
	CgZoomIn,
	CgZoomOut,
} from "react-icons/cg";

const result = [
	{ icon: CgAbstract, name: "CgAbstract", library: "cg" },
	{ icon: CgAddR, name: "CgAddR", library: "cg" },
	{ icon: CgAdd, name: "CgAdd", library: "cg" },
	{ icon: CgAdidas, name: "CgAdidas", library: "cg" },
	{ icon: CgAirplane, name: "CgAirplane", library: "cg" },
	{ icon: CgAlarm, name: "CgAlarm", library: "cg" },
	{ icon: CgAlbum, name: "CgAlbum", library: "cg" },
	{ icon: CgAlignBottom, name: "CgAlignBottom", library: "cg" },
	{ icon: CgAlignCenter, name: "CgAlignCenter", library: "cg" },
	{ icon: CgAlignLeft, name: "CgAlignLeft", library: "cg" },
	{ icon: CgAlignMiddle, name: "CgAlignMiddle", library: "cg" },
	{ icon: CgAlignRight, name: "CgAlignRight", library: "cg" },
	{ icon: CgAlignTop, name: "CgAlignTop", library: "cg" },
	{ icon: CgAnchor, name: "CgAnchor", library: "cg" },
	{ icon: CgAppleWatch, name: "CgAppleWatch", library: "cg" },
	{ icon: CgArrangeBack, name: "CgArrangeBack", library: "cg" },
	{ icon: CgArrangeFront, name: "CgArrangeFront", library: "cg" },
	{ icon: CgArrowAlignH, name: "CgArrowAlignH", library: "cg" },
	{ icon: CgArrowAlignV, name: "CgArrowAlignV", library: "cg" },
	{ icon: CgArrowBottomLeftO, name: "CgArrowBottomLeftO", library: "cg" },
	{ icon: CgArrowBottomLeftR, name: "CgArrowBottomLeftR", library: "cg" },
	{ icon: CgArrowBottomLeft, name: "CgArrowBottomLeft", library: "cg" },
	{ icon: CgArrowBottomRightO, name: "CgArrowBottomRightO", library: "cg" },
	{ icon: CgArrowBottomRightR, name: "CgArrowBottomRightR", library: "cg" },
	{ icon: CgArrowBottomRight, name: "CgArrowBottomRight", library: "cg" },
	{ icon: CgArrowDownO, name: "CgArrowDownO", library: "cg" },
	{ icon: CgArrowDownR, name: "CgArrowDownR", library: "cg" },
	{ icon: CgArrowDown, name: "CgArrowDown", library: "cg" },
	{ icon: CgArrowLeftO, name: "CgArrowLeftO", library: "cg" },
	{ icon: CgArrowLeftR, name: "CgArrowLeftR", library: "cg" },
	{ icon: CgArrowLeft, name: "CgArrowLeft", library: "cg" },
	{ icon: CgArrowLongDownC, name: "CgArrowLongDownC", library: "cg" },
	{ icon: CgArrowLongDownE, name: "CgArrowLongDownE", library: "cg" },
	{ icon: CgArrowLongDownL, name: "CgArrowLongDownL", library: "cg" },
	{ icon: CgArrowLongDownR, name: "CgArrowLongDownR", library: "cg" },
	{ icon: CgArrowLongDown, name: "CgArrowLongDown", library: "cg" },
	{ icon: CgArrowLongLeftC, name: "CgArrowLongLeftC", library: "cg" },
	{ icon: CgArrowLongLeftE, name: "CgArrowLongLeftE", library: "cg" },
	{ icon: CgArrowLongLeftL, name: "CgArrowLongLeftL", library: "cg" },
	{ icon: CgArrowLongLeftR, name: "CgArrowLongLeftR", library: "cg" },
	{ icon: CgArrowLongLeft, name: "CgArrowLongLeft", library: "cg" },
	{ icon: CgArrowLongRightC, name: "CgArrowLongRightC", library: "cg" },
	{ icon: CgArrowLongRightE, name: "CgArrowLongRightE", library: "cg" },
	{ icon: CgArrowLongRightL, name: "CgArrowLongRightL", library: "cg" },
	{ icon: CgArrowLongRightR, name: "CgArrowLongRightR", library: "cg" },
	{ icon: CgArrowLongRight, name: "CgArrowLongRight", library: "cg" },
	{ icon: CgArrowLongUpC, name: "CgArrowLongUpC", library: "cg" },
	{ icon: CgArrowLongUpE, name: "CgArrowLongUpE", library: "cg" },
	{ icon: CgArrowLongUpL, name: "CgArrowLongUpL", library: "cg" },
	{ icon: CgArrowLongUpR, name: "CgArrowLongUpR", library: "cg" },
	{ icon: CgArrowLongUp, name: "CgArrowLongUp", library: "cg" },
	{ icon: CgArrowRightO, name: "CgArrowRightO", library: "cg" },
	{ icon: CgArrowRightR, name: "CgArrowRightR", library: "cg" },
	{ icon: CgArrowRight, name: "CgArrowRight", library: "cg" },
	{ icon: CgArrowTopLeftO, name: "CgArrowTopLeftO", library: "cg" },
	{ icon: CgArrowTopLeftR, name: "CgArrowTopLeftR", library: "cg" },
	{ icon: CgArrowTopLeft, name: "CgArrowTopLeft", library: "cg" },
	{ icon: CgArrowTopRightO, name: "CgArrowTopRightO", library: "cg" },
	{ icon: CgArrowTopRightR, name: "CgArrowTopRightR", library: "cg" },
	{ icon: CgArrowTopRight, name: "CgArrowTopRight", library: "cg" },
	{ icon: CgArrowUpO, name: "CgArrowUpO", library: "cg" },
	{ icon: CgArrowUpR, name: "CgArrowUpR", library: "cg" },
	{ icon: CgArrowUp, name: "CgArrowUp", library: "cg" },
	{ icon: CgArrowsBreakeH, name: "CgArrowsBreakeH", library: "cg" },
	{ icon: CgArrowsBreakeV, name: "CgArrowsBreakeV", library: "cg" },
	{ icon: CgArrowsExchangeAltV, name: "CgArrowsExchangeAltV", library: "cg" },
	{ icon: CgArrowsExchangeAlt, name: "CgArrowsExchangeAlt", library: "cg" },
	{ icon: CgArrowsExchangeV, name: "CgArrowsExchangeV", library: "cg" },
	{ icon: CgArrowsExchange, name: "CgArrowsExchange", library: "cg" },
	{ icon: CgArrowsExpandDownLeft, name: "CgArrowsExpandDownLeft", library: "cg" },
	{ icon: CgArrowsExpandDownRight, name: "CgArrowsExpandDownRight", library: "cg" },
	{ icon: CgArrowsExpandLeftAlt, name: "CgArrowsExpandLeftAlt", library: "cg" },
	{ icon: CgArrowsExpandLeft, name: "CgArrowsExpandLeft", library: "cg" },
	{ icon: CgArrowsExpandRightAlt, name: "CgArrowsExpandRightAlt", library: "cg" },
	{ icon: CgArrowsExpandRight, name: "CgArrowsExpandRight", library: "cg" },
	{ icon: CgArrowsExpandUpLeft, name: "CgArrowsExpandUpLeft", library: "cg" },
	{ icon: CgArrowsExpandUpRight, name: "CgArrowsExpandUpRight", library: "cg" },
	{ icon: CgArrowsHAlt, name: "CgArrowsHAlt", library: "cg" },
	{ icon: CgArrowsH, name: "CgArrowsH", library: "cg" },
	{ icon: CgArrowsMergeAltH, name: "CgArrowsMergeAltH", library: "cg" },
	{ icon: CgArrowsMergeAltV, name: "CgArrowsMergeAltV", library: "cg" },
	{ icon: CgArrowsScrollH, name: "CgArrowsScrollH", library: "cg" },
	{ icon: CgArrowsScrollV, name: "CgArrowsScrollV", library: "cg" },
	{ icon: CgArrowsShrinkH, name: "CgArrowsShrinkH", library: "cg" },
	{ icon: CgArrowsShrinkV, name: "CgArrowsShrinkV", library: "cg" },
	{ icon: CgArrowsVAlt, name: "CgArrowsVAlt", library: "cg" },
	{ icon: CgArrowsV, name: "CgArrowsV", library: "cg" },
	{ icon: CgAssign, name: "CgAssign", library: "cg" },
	{ icon: CgAsterisk, name: "CgAsterisk", library: "cg" },
	{ icon: CgAtlasian, name: "CgAtlasian", library: "cg" },
	{ icon: CgAttachment, name: "CgAttachment", library: "cg" },
	{ icon: CgAttribution, name: "CgAttribution", library: "cg" },
	{ icon: CgAwards, name: "CgAwards", library: "cg" },
	{ icon: CgBackspace, name: "CgBackspace", library: "cg" },
	{ icon: CgBandAid, name: "CgBandAid", library: "cg" },
	{ icon: CgBatteryEmpty, name: "CgBatteryEmpty", library: "cg" },
	{ icon: CgBatteryFull, name: "CgBatteryFull", library: "cg" },
	{ icon: CgBattery, name: "CgBattery", library: "cg" },
	{ icon: CgBee, name: "CgBee", library: "cg" },
	{ icon: CgBell, name: "CgBell", library: "cg" },
	{ icon: CgBitbucket, name: "CgBitbucket", library: "cg" },
	{ icon: CgBlock, name: "CgBlock", library: "cg" },
	{ icon: CgBmw, name: "CgBmw", library: "cg" },
	{ icon: CgBoard, name: "CgBoard", library: "cg" },
	{ icon: CgBolt, name: "CgBolt", library: "cg" },
	{ icon: CgBookmark, name: "CgBookmark", library: "cg" },
	{ icon: CgBorderAll, name: "CgBorderAll", library: "cg" },
	{ icon: CgBorderBottom, name: "CgBorderBottom", library: "cg" },
	{ icon: CgBorderLeft, name: "CgBorderLeft", library: "cg" },
	{ icon: CgBorderRight, name: "CgBorderRight", library: "cg" },
	{ icon: CgBorderStyleDashed, name: "CgBorderStyleDashed", library: "cg" },
	{ icon: CgBorderStyleDotted, name: "CgBorderStyleDotted", library: "cg" },
	{ icon: CgBorderStyleSolid, name: "CgBorderStyleSolid", library: "cg" },
	{ icon: CgBorderTop, name: "CgBorderTop", library: "cg" },
	{ icon: CgBot, name: "CgBot", library: "cg" },
	{ icon: CgBowl, name: "CgBowl", library: "cg" },
	{ icon: CgBox, name: "CgBox", library: "cg" },
	{ icon: CgBoy, name: "CgBoy", library: "cg" },
	{ icon: CgBrackets, name: "CgBrackets", library: "cg" },
	{ icon: CgBriefcase, name: "CgBriefcase", library: "cg" },
	{ icon: CgBrowse, name: "CgBrowse", library: "cg" },
	{ icon: CgBrowser, name: "CgBrowser", library: "cg" },
	{ icon: CgBrush, name: "CgBrush", library: "cg" },
	{ icon: CgBulb, name: "CgBulb", library: "cg" },
	{ icon: CgCPlusPlus, name: "CgCPlusPlus", library: "cg" },
	{ icon: CgCalculator, name: "CgCalculator", library: "cg" },
	{ icon: CgCalendarDates, name: "CgCalendarDates", library: "cg" },
	{ icon: CgCalendarDue, name: "CgCalendarDue", library: "cg" },
	{ icon: CgCalendarNext, name: "CgCalendarNext", library: "cg" },
	{ icon: CgCalendarToday, name: "CgCalendarToday", library: "cg" },
	{ icon: CgCalendarTwo, name: "CgCalendarTwo", library: "cg" },
	{ icon: CgCalendar, name: "CgCalendar", library: "cg" },
	{ icon: CgCalibrate, name: "CgCalibrate", library: "cg" },
	{ icon: CgCamera, name: "CgCamera", library: "cg" },
	{ icon: CgCap, name: "CgCap", library: "cg" },
	{ icon: CgCaptions, name: "CgCaptions", library: "cg" },
	{ icon: CgCardClubs, name: "CgCardClubs", library: "cg" },
	{ icon: CgCardDiamonds, name: "CgCardDiamonds", library: "cg" },
	{ icon: CgCardHearts, name: "CgCardHearts", library: "cg" },
	{ icon: CgCardSpades, name: "CgCardSpades", library: "cg" },
	{ icon: CgCarousel, name: "CgCarousel", library: "cg" },
	{ icon: CgCast, name: "CgCast", library: "cg" },
	{ icon: CgChanel, name: "CgChanel", library: "cg" },
	{ icon: CgChart, name: "CgChart", library: "cg" },
	{ icon: CgCheckO, name: "CgCheckO", library: "cg" },
	{ icon: CgCheckR, name: "CgCheckR", library: "cg" },
	{ icon: CgCheck, name: "CgCheck", library: "cg" },
	{ icon: CgChevronDoubleDownO, name: "CgChevronDoubleDownO", library: "cg" },
	{ icon: CgChevronDoubleDownR, name: "CgChevronDoubleDownR", library: "cg" },
	{ icon: CgChevronDoubleDown, name: "CgChevronDoubleDown", library: "cg" },
	{ icon: CgChevronDoubleLeftO, name: "CgChevronDoubleLeftO", library: "cg" },
	{ icon: CgChevronDoubleLeftR, name: "CgChevronDoubleLeftR", library: "cg" },
	{ icon: CgChevronDoubleLeft, name: "CgChevronDoubleLeft", library: "cg" },
	{ icon: CgChevronDoubleRightO, name: "CgChevronDoubleRightO", library: "cg" },
	{ icon: CgChevronDoubleRightR, name: "CgChevronDoubleRightR", library: "cg" },
	{ icon: CgChevronDoubleRight, name: "CgChevronDoubleRight", library: "cg" },
	{ icon: CgChevronDoubleUpO, name: "CgChevronDoubleUpO", library: "cg" },
	{ icon: CgChevronDoubleUpR, name: "CgChevronDoubleUpR", library: "cg" },
	{ icon: CgChevronDoubleUp, name: "CgChevronDoubleUp", library: "cg" },
	{ icon: CgChevronDownO, name: "CgChevronDownO", library: "cg" },
	{ icon: CgChevronDownR, name: "CgChevronDownR", library: "cg" },
	{ icon: CgChevronDown, name: "CgChevronDown", library: "cg" },
	{ icon: CgChevronLeftO, name: "CgChevronLeftO", library: "cg" },
	{ icon: CgChevronLeftR, name: "CgChevronLeftR", library: "cg" },
	{ icon: CgChevronLeft, name: "CgChevronLeft", library: "cg" },
	{ icon: CgChevronRightO, name: "CgChevronRightO", library: "cg" },
	{ icon: CgChevronRightR, name: "CgChevronRightR", library: "cg" },
	{ icon: CgChevronRight, name: "CgChevronRight", library: "cg" },
	{ icon: CgChevronUpO, name: "CgChevronUpO", library: "cg" },
	{ icon: CgChevronUpR, name: "CgChevronUpR", library: "cg" },
	{ icon: CgChevronUp, name: "CgChevronUp", library: "cg" },
	{ icon: CgCircleci, name: "CgCircleci", library: "cg" },
	{ icon: CgClapperBoard, name: "CgClapperBoard", library: "cg" },
	{ icon: CgClipboard, name: "CgClipboard", library: "cg" },
	{ icon: CgCloseO, name: "CgCloseO", library: "cg" },
	{ icon: CgCloseR, name: "CgCloseR", library: "cg" },
	{ icon: CgClose, name: "CgClose", library: "cg" },
	{ icon: CgCloud, name: "CgCloud", library: "cg" },
	{ icon: CgCodeClimate, name: "CgCodeClimate", library: "cg" },
	{ icon: CgCodeSlash, name: "CgCodeSlash", library: "cg" },
	{ icon: CgCode, name: "CgCode", library: "cg" },
	{ icon: CgCoffee, name: "CgCoffee", library: "cg" },
	{ icon: CgCollage, name: "CgCollage", library: "cg" },
	{ icon: CgColorBucket, name: "CgColorBucket", library: "cg" },
	{ icon: CgColorPicker, name: "CgColorPicker", library: "cg" },
	{ icon: CgComedyCentral, name: "CgComedyCentral", library: "cg" },
	{ icon: CgComment, name: "CgComment", library: "cg" },
	{ icon: CgCommunity, name: "CgCommunity", library: "cg" },
	{ icon: CgComponents, name: "CgComponents", library: "cg" },
	{ icon: CgCompressLeft, name: "CgCompressLeft", library: "cg" },
	{ icon: CgCompressRight, name: "CgCompressRight", library: "cg" },
	{ icon: CgCompressV, name: "CgCompressV", library: "cg" },
	{ icon: CgCompress, name: "CgCompress", library: "cg" },
	{ icon: CgController, name: "CgController", library: "cg" },
	{ icon: CgCopy, name: "CgCopy", library: "cg" },
	{ icon: CgCopyright, name: "CgCopyright", library: "cg" },
	{ icon: CgCornerDoubleDownLeft, name: "CgCornerDoubleDownLeft", library: "cg" },
	{ icon: CgCornerDoubleDownRight, name: "CgCornerDoubleDownRight", library: "cg" },
	{ icon: CgCornerDoubleLeftDown, name: "CgCornerDoubleLeftDown", library: "cg" },
	{ icon: CgCornerDoubleLeftUp, name: "CgCornerDoubleLeftUp", library: "cg" },
	{ icon: CgCornerDoubleRightDown, name: "CgCornerDoubleRightDown", library: "cg" },
	{ icon: CgCornerDoubleRightUp, name: "CgCornerDoubleRightUp", library: "cg" },
	{ icon: CgCornerDoubleUpLeft, name: "CgCornerDoubleUpLeft", library: "cg" },
	{ icon: CgCornerDoubleUpRight, name: "CgCornerDoubleUpRight", library: "cg" },
	{ icon: CgCornerDownLeft, name: "CgCornerDownLeft", library: "cg" },
	{ icon: CgCornerDownRight, name: "CgCornerDownRight", library: "cg" },
	{ icon: CgCornerLeftDown, name: "CgCornerLeftDown", library: "cg" },
	{ icon: CgCornerLeftUp, name: "CgCornerLeftUp", library: "cg" },
	{ icon: CgCornerRightDown, name: "CgCornerRightDown", library: "cg" },
	{ icon: CgCornerRightUp, name: "CgCornerRightUp", library: "cg" },
	{ icon: CgCornerUpLeft, name: "CgCornerUpLeft", library: "cg" },
	{ icon: CgCornerUpRight, name: "CgCornerUpRight", library: "cg" },
	{ icon: CgCreditCard, name: "CgCreditCard", library: "cg" },
	{ icon: CgCrop, name: "CgCrop", library: "cg" },
	{ icon: CgCross, name: "CgCross", library: "cg" },
	{ icon: CgCrowdfire, name: "CgCrowdfire", library: "cg" },
	{ icon: CgCrown, name: "CgCrown", library: "cg" },
	{ icon: CgDanger, name: "CgDanger", library: "cg" },
	{ icon: CgDarkMode, name: "CgDarkMode", library: "cg" },
	{ icon: CgData, name: "CgData", library: "cg" },
	{ icon: CgDatabase, name: "CgDatabase", library: "cg" },
	{ icon: CgDebug, name: "CgDebug", library: "cg" },
	{ icon: CgDesignmodo, name: "CgDesignmodo", library: "cg" },
	{ icon: CgDesktop, name: "CgDesktop", library: "cg" },
	{ icon: CgDetailsLess, name: "CgDetailsLess", library: "cg" },
	{ icon: CgDetailsMore, name: "CgDetailsMore", library: "cg" },
	{ icon: CgDialpad, name: "CgDialpad", library: "cg" },
	{ icon: CgDice1, name: "CgDice1", library: "cg" },
	{ icon: CgDice2, name: "CgDice2", library: "cg" },
	{ icon: CgDice3, name: "CgDice3", library: "cg" },
	{ icon: CgDice4, name: "CgDice4", library: "cg" },
	{ icon: CgDice5, name: "CgDice5", library: "cg" },
	{ icon: CgDice6, name: "CgDice6", library: "cg" },
	{ icon: CgDigitalocean, name: "CgDigitalocean", library: "cg" },
	{ icon: CgDisc, name: "CgDisc", library: "cg" },
	{ icon: CgDisplayFlex, name: "CgDisplayFlex", library: "cg" },
	{ icon: CgDisplayFullwidth, name: "CgDisplayFullwidth", library: "cg" },
	{ icon: CgDisplayGrid, name: "CgDisplayGrid", library: "cg" },
	{ icon: CgDisplaySpacing, name: "CgDisplaySpacing", library: "cg" },
	{ icon: CgDistributeHorizontal, name: "CgDistributeHorizontal", library: "cg" },
	{ icon: CgDistributeVertical, name: "CgDistributeVertical", library: "cg" },
	{ icon: CgDockBottom, name: "CgDockBottom", library: "cg" },
	{ icon: CgDockLeft, name: "CgDockLeft", library: "cg" },
	{ icon: CgDockRight, name: "CgDockRight", library: "cg" },
	{ icon: CgDockWindow, name: "CgDockWindow", library: "cg" },
	{ icon: CgDolby, name: "CgDolby", library: "cg" },
	{ icon: CgDollar, name: "CgDollar", library: "cg" },
	{ icon: CgDribbble, name: "CgDribbble", library: "cg" },
	{ icon: CgDrive, name: "CgDrive", library: "cg" },
	{ icon: CgDropInvert, name: "CgDropInvert", library: "cg" },
	{ icon: CgDropOpacity, name: "CgDropOpacity", library: "cg" },
	{ icon: CgDrop, name: "CgDrop", library: "cg" },
	{ icon: CgDuplicate, name: "CgDuplicate", library: "cg" },
	{ icon: CgEditBlackPoint, name: "CgEditBlackPoint", library: "cg" },
	{ icon: CgEditContrast, name: "CgEditContrast", library: "cg" },
	{ icon: CgEditExposure, name: "CgEditExposure", library: "cg" },
	{ icon: CgEditFade, name: "CgEditFade", library: "cg" },
	{ icon: CgEditFlipH, name: "CgEditFlipH", library: "cg" },
	{ icon: CgEditFlipV, name: "CgEditFlipV", library: "cg" },
	{ icon: CgEditHighlight, name: "CgEditHighlight", library: "cg" },
	{ icon: CgEditMarkup, name: "CgEditMarkup", library: "cg" },
	{ icon: CgEditMask, name: "CgEditMask", library: "cg" },
	{ icon: CgEditNoise, name: "CgEditNoise", library: "cg" },
	{ icon: CgEditShadows, name: "CgEditShadows", library: "cg" },
	{ icon: CgEditStraight, name: "CgEditStraight", library: "cg" },
	{ icon: CgEditUnmask, name: "CgEditUnmask", library: "cg" },
	{ icon: CgEject, name: "CgEject", library: "cg" },
	{ icon: CgEnter, name: "CgEnter", library: "cg" },
	{ icon: CgErase, name: "CgErase", library: "cg" },
	{ icon: CgEreader, name: "CgEreader", library: "cg" },
	{ icon: CgEricsson, name: "CgEricsson", library: "cg" },
	{ icon: CgEthernet, name: "CgEthernet", library: "cg" },
	{ icon: CgEuro, name: "CgEuro", library: "cg" },
	{ icon: CgEventbrite, name: "CgEventbrite", library: "cg" },
	{ icon: CgExpand, name: "CgExpand", library: "cg" },
	{ icon: CgExport, name: "CgExport", library: "cg" },
	{ icon: CgExtensionAdd, name: "CgExtensionAdd", library: "cg" },
	{ icon: CgExtensionAlt, name: "CgExtensionAlt", library: "cg" },
	{ icon: CgExtensionRemove, name: "CgExtensionRemove", library: "cg" },
	{ icon: CgExtension, name: "CgExtension", library: "cg" },
	{ icon: CgExternal, name: "CgExternal", library: "cg" },
	{ icon: CgEyeAlt, name: "CgEyeAlt", library: "cg" },
	{ icon: CgEye, name: "CgEye", library: "cg" },
	{ icon: CgFacebook, name: "CgFacebook", library: "cg" },
	{ icon: CgFeed, name: "CgFeed", library: "cg" },
	{ icon: CgFigma, name: "CgFigma", library: "cg" },
	{ icon: CgFileAdd, name: "CgFileAdd", library: "cg" },
	{ icon: CgFileDocument, name: "CgFileDocument", library: "cg" },
	{ icon: CgFileRemove, name: "CgFileRemove", library: "cg" },
	{ icon: CgFile, name: "CgFile", library: "cg" },
	{ icon: CgFilm, name: "CgFilm", library: "cg" },
	{ icon: CgFilters, name: "CgFilters", library: "cg" },
	{ icon: CgFlagAlt, name: "CgFlagAlt", library: "cg" },
	{ icon: CgFlag, name: "CgFlag", library: "cg" },
	{ icon: CgFolderAdd, name: "CgFolderAdd", library: "cg" },
	{ icon: CgFolderRemove, name: "CgFolderRemove", library: "cg" },
	{ icon: CgFolder, name: "CgFolder", library: "cg" },
	{ icon: CgFontHeight, name: "CgFontHeight", library: "cg" },
	{ icon: CgFontSpacing, name: "CgFontSpacing", library: "cg" },
	{ icon: CgFormatBold, name: "CgFormatBold", library: "cg" },
	{ icon: CgFormatCenter, name: "CgFormatCenter", library: "cg" },
	{ icon: CgFormatColor, name: "CgFormatColor", library: "cg" },
	{ icon: CgFormatHeading, name: "CgFormatHeading", library: "cg" },
	{ icon: CgFormatIndentDecrease, name: "CgFormatIndentDecrease", library: "cg" },
	{ icon: CgFormatIndentIncrease, name: "CgFormatIndentIncrease", library: "cg" },
	{ icon: CgFormatItalic, name: "CgFormatItalic", library: "cg" },
	{ icon: CgFormatJustify, name: "CgFormatJustify", library: "cg" },
	{ icon: CgFormatLeft, name: "CgFormatLeft", library: "cg" },
	{ icon: CgFormatLineHeight, name: "CgFormatLineHeight", library: "cg" },
	{ icon: CgFormatRight, name: "CgFormatRight", library: "cg" },
	{ icon: CgFormatSeparator, name: "CgFormatSeparator", library: "cg" },
	{ icon: CgFormatSlash, name: "CgFormatSlash", library: "cg" },
	{ icon: CgFormatStrike, name: "CgFormatStrike", library: "cg" },
	{ icon: CgFormatText, name: "CgFormatText", library: "cg" },
	{ icon: CgFormatUnderline, name: "CgFormatUnderline", library: "cg" },
	{ icon: CgFormatUppercase, name: "CgFormatUppercase", library: "cg" },
	{ icon: CgFramer, name: "CgFramer", library: "cg" },
	{ icon: CgGames, name: "CgGames", library: "cg" },
	{ icon: CgGenderFemale, name: "CgGenderFemale", library: "cg" },
	{ icon: CgGenderMale, name: "CgGenderMale", library: "cg" },
	{ icon: CgGhostCharacter, name: "CgGhostCharacter", library: "cg" },
	{ icon: CgGhost, name: "CgGhost", library: "cg" },
	{ icon: CgGift, name: "CgGift", library: "cg" },
	{ icon: CgGirl, name: "CgGirl", library: "cg" },
	{ icon: CgGitBranch, name: "CgGitBranch", library: "cg" },
	{ icon: CgGitCommit, name: "CgGitCommit", library: "cg" },
	{ icon: CgGitFork, name: "CgGitFork", library: "cg" },
	{ icon: CgGitPull, name: "CgGitPull", library: "cg" },
	{ icon: CgGitter, name: "CgGitter", library: "cg" },
	{ icon: CgGlassAlt, name: "CgGlassAlt", library: "cg" },
	{ icon: CgGlass, name: "CgGlass", library: "cg" },
	{ icon: CgGlobeAlt, name: "CgGlobeAlt", library: "cg" },
	{ icon: CgGlobe, name: "CgGlobe", library: "cg" },
	{ icon: CgGoogleTasks, name: "CgGoogleTasks", library: "cg" },
	{ icon: CgGoogle, name: "CgGoogle", library: "cg" },
	{ icon: CgGym, name: "CgGym", library: "cg" },
	{ icon: CgHashtag, name: "CgHashtag", library: "cg" },
	{ icon: CgHeadset, name: "CgHeadset", library: "cg" },
	{ icon: CgHeart, name: "CgHeart", library: "cg" },
	{ icon: CgHello, name: "CgHello", library: "cg" },
	{ icon: CgHomeAlt, name: "CgHomeAlt", library: "cg" },
	{ icon: CgHomeScreen, name: "CgHomeScreen", library: "cg" },
	{ icon: CgHome, name: "CgHome", library: "cg" },
	{ icon: CgIcecream, name: "CgIcecream", library: "cg" },
	{ icon: CgIfDesign, name: "CgIfDesign", library: "cg" },
	{ icon: CgImage, name: "CgImage", library: "cg" },
	{ icon: CgImport, name: "CgImport", library: "cg" },
	{ icon: CgInbox, name: "CgInbox", library: "cg" },
	{ icon: CgIndieHackers, name: "CgIndieHackers", library: "cg" },
	{ icon: CgInfinity, name: "CgInfinity", library: "cg" },
	{ icon: CgInfo, name: "CgInfo", library: "cg" },
	{ icon: CgInpicture, name: "CgInpicture", library: "cg" },
	{ icon: CgInsertAfterO, name: "CgInsertAfterO", library: "cg" },
	{ icon: CgInsertAfterR, name: "CgInsertAfterR", library: "cg" },
	{ icon: CgInsertAfter, name: "CgInsertAfter", library: "cg" },
	{ icon: CgInsertBeforeO, name: "CgInsertBeforeO", library: "cg" },
	{ icon: CgInsertBeforeR, name: "CgInsertBeforeR", library: "cg" },
	{ icon: CgInsertBefore, name: "CgInsertBefore", library: "cg" },
	{ icon: CgInsights, name: "CgInsights", library: "cg" },
	{ icon: CgInstagram, name: "CgInstagram", library: "cg" },
	{ icon: CgInternal, name: "CgInternal", library: "cg" },
	{ icon: CgKey, name: "CgKey", library: "cg" },
	{ icon: CgKeyboard, name: "CgKeyboard", library: "cg" },
	{ icon: CgKeyhole, name: "CgKeyhole", library: "cg" },
	{ icon: CgLaptop, name: "CgLaptop", library: "cg" },
	{ icon: CgLastpass, name: "CgLastpass", library: "cg" },
	{ icon: CgLayoutGridSmall, name: "CgLayoutGridSmall", library: "cg" },
	{ icon: CgLayoutGrid, name: "CgLayoutGrid", library: "cg" },
	{ icon: CgLayoutList, name: "CgLayoutList", library: "cg" },
	{ icon: CgLayoutPin, name: "CgLayoutPin", library: "cg" },
	{ icon: CgLinear, name: "CgLinear", library: "cg" },
	{ icon: CgLink, name: "CgLink", library: "cg" },
	{ icon: CgListTree, name: "CgListTree", library: "cg" },
	{ icon: CgList, name: "CgList", library: "cg" },
	{ icon: CgLivePhoto, name: "CgLivePhoto", library: "cg" },
	{ icon: CgLoadbarAlt, name: "CgLoadbarAlt", library: "cg" },
	{ icon: CgLoadbarDoc, name: "CgLoadbarDoc", library: "cg" },
	{ icon: CgLoadbarSound, name: "CgLoadbarSound", library: "cg" },
	{ icon: CgLoadbar, name: "CgLoadbar", library: "cg" },
	{ icon: CgLockUnlock, name: "CgLockUnlock", library: "cg" },
	{ icon: CgLock, name: "CgLock", library: "cg" },
	{ icon: CgLogIn, name: "CgLogIn", library: "cg" },
	{ icon: CgLogOff, name: "CgLogOff", library: "cg" },
	{ icon: CgLogOut, name: "CgLogOut", library: "cg" },
	{ icon: CgLoupe, name: "CgLoupe", library: "cg" },
	{ icon: CgMagnet, name: "CgMagnet", library: "cg" },
	{ icon: CgMailForward, name: "CgMailForward", library: "cg" },
	{ icon: CgMailOpen, name: "CgMailOpen", library: "cg" },
	{ icon: CgMailReply, name: "CgMailReply", library: "cg" },
	{ icon: CgMail, name: "CgMail", library: "cg" },
	{ icon: CgMathDivide, name: "CgMathDivide", library: "cg" },
	{ icon: CgMathEqual, name: "CgMathEqual", library: "cg" },
	{ icon: CgMathMinus, name: "CgMathMinus", library: "cg" },
	{ icon: CgMathPercent, name: "CgMathPercent", library: "cg" },
	{ icon: CgMathPlus, name: "CgMathPlus", library: "cg" },
	{ icon: CgMaximizeAlt, name: "CgMaximizeAlt", library: "cg" },
	{ icon: CgMaximize, name: "CgMaximize", library: "cg" },
	{ icon: CgMaze, name: "CgMaze", library: "cg" },
	{ icon: CgMediaLive, name: "CgMediaLive", library: "cg" },
	{ icon: CgMediaPodcast, name: "CgMediaPodcast", library: "cg" },
	{ icon: CgMenuBoxed, name: "CgMenuBoxed", library: "cg" },
	{ icon: CgMenuCake, name: "CgMenuCake", library: "cg" },
	{ icon: CgMenuCheese, name: "CgMenuCheese", library: "cg" },
	{ icon: CgMenuGridO, name: "CgMenuGridO", library: "cg" },
	{ icon: CgMenuGridR, name: "CgMenuGridR", library: "cg" },
	{ icon: CgMenuHotdog, name: "CgMenuHotdog", library: "cg" },
	{ icon: CgMenuLeftAlt, name: "CgMenuLeftAlt", library: "cg" },
	{ icon: CgMenuLeft, name: "CgMenuLeft", library: "cg" },
	{ icon: CgMenuMotion, name: "CgMenuMotion", library: "cg" },
	{ icon: CgMenuOreos, name: "CgMenuOreos", library: "cg" },
	{ icon: CgMenuRightAlt, name: "CgMenuRightAlt", library: "cg" },
	{ icon: CgMenuRight, name: "CgMenuRight", library: "cg" },
	{ icon: CgMenuRound, name: "CgMenuRound", library: "cg" },
	{ icon: CgMenu, name: "CgMenu", library: "cg" },
	{ icon: CgMergeHorizontal, name: "CgMergeHorizontal", library: "cg" },
	{ icon: CgMergeVertical, name: "CgMergeVertical", library: "cg" },
	{ icon: CgMic, name: "CgMic", library: "cg" },
	{ icon: CgMicrobit, name: "CgMicrobit", library: "cg" },
	{ icon: CgMicrosoft, name: "CgMicrosoft", library: "cg" },
	{ icon: CgMiniPlayer, name: "CgMiniPlayer", library: "cg" },
	{ icon: CgMinimizeAlt, name: "CgMinimizeAlt", library: "cg" },
	{ icon: CgMinimize, name: "CgMinimize", library: "cg" },
	{ icon: CgModem, name: "CgModem", library: "cg" },
	{ icon: CgMonday, name: "CgMonday", library: "cg" },
	{ icon: CgMoon, name: "CgMoon", library: "cg" },
	{ icon: CgMoreAlt, name: "CgMoreAlt", library: "cg" },
	{ icon: CgMoreO, name: "CgMoreO", library: "cg" },
	{ icon: CgMoreR, name: "CgMoreR", library: "cg" },
	{ icon: CgMoreVerticalAlt, name: "CgMoreVerticalAlt", library: "cg" },
	{ icon: CgMoreVerticalO, name: "CgMoreVerticalO", library: "cg" },
	{ icon: CgMoreVerticalR, name: "CgMoreVerticalR", library: "cg" },
	{ icon: CgMoreVertical, name: "CgMoreVertical", library: "cg" },
	{ icon: CgMore, name: "CgMore", library: "cg" },
	{ icon: CgMouse, name: "CgMouse", library: "cg" },
	{ icon: CgMoveDown, name: "CgMoveDown", library: "cg" },
	{ icon: CgMoveLeft, name: "CgMoveLeft", library: "cg" },
	{ icon: CgMoveRight, name: "CgMoveRight", library: "cg" },
	{ icon: CgMoveTask, name: "CgMoveTask", library: "cg" },
	{ icon: CgMoveUp, name: "CgMoveUp", library: "cg" },
	{ icon: CgMusicNote, name: "CgMusicNote", library: "cg" },
	{ icon: CgMusicSpeaker, name: "CgMusicSpeaker", library: "cg" },
	{ icon: CgMusic, name: "CgMusic", library: "cg" },
	{ icon: CgNametag, name: "CgNametag", library: "cg" },
	{ icon: CgNotes, name: "CgNotes", library: "cg" },
	{ icon: CgNotifications, name: "CgNotifications", library: "cg" },
	{ icon: CgNpm, name: "CgNpm", library: "cg" },
	{ icon: CgOculus, name: "CgOculus", library: "cg" },
	{ icon: CgOpenCollective, name: "CgOpenCollective", library: "cg" },
	{ icon: CgOptions, name: "CgOptions", library: "cg" },
	{ icon: CgOrganisation, name: "CgOrganisation", library: "cg" },
	{ icon: CgOverflow, name: "CgOverflow", library: "cg" },
	{ icon: CgPacman, name: "CgPacman", library: "cg" },
	{ icon: CgPassword, name: "CgPassword", library: "cg" },
	{ icon: CgPathBack, name: "CgPathBack", library: "cg" },
	{ icon: CgPathCrop, name: "CgPathCrop", library: "cg" },
	{ icon: CgPathDivide, name: "CgPathDivide", library: "cg" },
	{ icon: CgPathExclude, name: "CgPathExclude", library: "cg" },
	{ icon: CgPathFront, name: "CgPathFront", library: "cg" },
	{ icon: CgPathIntersect, name: "CgPathIntersect", library: "cg" },
	{ icon: CgPathOutline, name: "CgPathOutline", library: "cg" },
	{ icon: CgPathTrim, name: "CgPathTrim", library: "cg" },
	{ icon: CgPathUnite, name: "CgPathUnite", library: "cg" },
	{ icon: CgPatreon, name: "CgPatreon", library: "cg" },
	{ icon: CgPaypal, name: "CgPaypal", library: "cg" },
	{ icon: CgPen, name: "CgPen", library: "cg" },
	{ icon: CgPentagonBottomLeft, name: "CgPentagonBottomLeft", library: "cg" },
	{ icon: CgPentagonBottomRight, name: "CgPentagonBottomRight", library: "cg" },
	{ icon: CgPentagonDown, name: "CgPentagonDown", library: "cg" },
	{ icon: CgPentagonLeft, name: "CgPentagonLeft", library: "cg" },
	{ icon: CgPentagonRight, name: "CgPentagonRight", library: "cg" },
	{ icon: CgPentagonTopLeft, name: "CgPentagonTopLeft", library: "cg" },
	{ icon: CgPentagonTopRight, name: "CgPentagonTopRight", library: "cg" },
	{ icon: CgPentagonUp, name: "CgPentagonUp", library: "cg" },
	{ icon: CgPerformance, name: "CgPerformance", library: "cg" },
	{ icon: CgPexels, name: "CgPexels", library: "cg" },
	{ icon: CgPhone, name: "CgPhone", library: "cg" },
	{ icon: CgPhotoscan, name: "CgPhotoscan", library: "cg" },
	{ icon: CgPiano, name: "CgPiano", library: "cg" },
	{ icon: CgPill, name: "CgPill", library: "cg" },
	{ icon: CgPinAlt, name: "CgPinAlt", library: "cg" },
	{ icon: CgPinBottom, name: "CgPinBottom", library: "cg" },
	{ icon: CgPinTop, name: "CgPinTop", library: "cg" },
	{ icon: CgPin, name: "CgPin", library: "cg" },
	{ icon: CgPlayBackwards, name: "CgPlayBackwards", library: "cg" },
	{ icon: CgPlayButtonO, name: "CgPlayButtonO", library: "cg" },
	{ icon: CgPlayButtonR, name: "CgPlayButtonR", library: "cg" },
	{ icon: CgPlayButton, name: "CgPlayButton", library: "cg" },
	{ icon: CgPlayForwards, name: "CgPlayForwards", library: "cg" },
	{ icon: CgPlayListAdd, name: "CgPlayListAdd", library: "cg" },
	{ icon: CgPlayListCheck, name: "CgPlayListCheck", library: "cg" },
	{ icon: CgPlayListRemove, name: "CgPlayListRemove", library: "cg" },
	{ icon: CgPlayListSearch, name: "CgPlayListSearch", library: "cg" },
	{ icon: CgPlayList, name: "CgPlayList", library: "cg" },
	{ icon: CgPlayPauseO, name: "CgPlayPauseO", library: "cg" },
	{ icon: CgPlayPauseR, name: "CgPlayPauseR", library: "cg" },
	{ icon: CgPlayPause, name: "CgPlayPause", library: "cg" },
	{ icon: CgPlayStopO, name: "CgPlayStopO", library: "cg" },
	{ icon: CgPlayStopR, name: "CgPlayStopR", library: "cg" },
	{ icon: CgPlayStop, name: "CgPlayStop", library: "cg" },
	{ icon: CgPlayTrackNextO, name: "CgPlayTrackNextO", library: "cg" },
	{ icon: CgPlayTrackNextR, name: "CgPlayTrackNextR", library: "cg" },
	{ icon: CgPlayTrackNext, name: "CgPlayTrackNext", library: "cg" },
	{ icon: CgPlayTrackPrevO, name: "CgPlayTrackPrevO", library: "cg" },
	{ icon: CgPlayTrackPrevR, name: "CgPlayTrackPrevR", library: "cg" },
	{ icon: CgPlayTrackPrev, name: "CgPlayTrackPrev", library: "cg" },
	{ icon: CgPlug, name: "CgPlug", library: "cg" },
	{ icon: CgPocket, name: "CgPocket", library: "cg" },
	{ icon: CgPokemon, name: "CgPokemon", library: "cg" },
	{ icon: CgPolaroid, name: "CgPolaroid", library: "cg" },
	{ icon: CgPoll, name: "CgPoll", library: "cg" },
	{ icon: CgPresentation, name: "CgPresentation", library: "cg" },
	{ icon: CgPrinter, name: "CgPrinter", library: "cg" },
	{ icon: CgProductHunt, name: "CgProductHunt", library: "cg" },
	{ icon: CgProfile, name: "CgProfile", library: "cg" },
	{ icon: CgPullClear, name: "CgPullClear", library: "cg" },
	{ icon: CgPushChevronDownO, name: "CgPushChevronDownO", library: "cg" },
	{ icon: CgPushChevronDownR, name: "CgPushChevronDownR", library: "cg" },
	{ icon: CgPushChevronDown, name: "CgPushChevronDown", library: "cg" },
	{ icon: CgPushChevronLeftO, name: "CgPushChevronLeftO", library: "cg" },
	{ icon: CgPushChevronLeftR, name: "CgPushChevronLeftR", library: "cg" },
	{ icon: CgPushChevronLeft, name: "CgPushChevronLeft", library: "cg" },
	{ icon: CgPushChevronRightO, name: "CgPushChevronRightO", library: "cg" },
	{ icon: CgPushChevronRightR, name: "CgPushChevronRightR", library: "cg" },
	{ icon: CgPushChevronRight, name: "CgPushChevronRight", library: "cg" },
	{ icon: CgPushChevronUpO, name: "CgPushChevronUpO", library: "cg" },
	{ icon: CgPushChevronUpR, name: "CgPushChevronUpR", library: "cg" },
	{ icon: CgPushChevronUp, name: "CgPushChevronUp", library: "cg" },
	{ icon: CgPushDown, name: "CgPushDown", library: "cg" },
	{ icon: CgPushLeft, name: "CgPushLeft", library: "cg" },
	{ icon: CgPushRight, name: "CgPushRight", library: "cg" },
	{ icon: CgPushUp, name: "CgPushUp", library: "cg" },
	{ icon: CgQr, name: "CgQr", library: "cg" },
	{ icon: CgQuoteO, name: "CgQuoteO", library: "cg" },
	{ icon: CgQuote, name: "CgQuote", library: "cg" },
	{ icon: CgRadioCheck, name: "CgRadioCheck", library: "cg" },
	{ icon: CgRadioChecked, name: "CgRadioChecked", library: "cg" },
	{ icon: CgRatio, name: "CgRatio", library: "cg" },
	{ icon: CgRead, name: "CgRead", library: "cg" },
	{ icon: CgReadme, name: "CgReadme", library: "cg" },
	{ icon: CgRecord, name: "CgRecord", library: "cg" },
	{ icon: CgRedo, name: "CgRedo", library: "cg" },
	{ icon: CgRemote, name: "CgRemote", library: "cg" },
	{ icon: CgRemoveR, name: "CgRemoveR", library: "cg" },
	{ icon: CgRemove, name: "CgRemove", library: "cg" },
	{ icon: CgRename, name: "CgRename", library: "cg" },
	{ icon: CgReorder, name: "CgReorder", library: "cg" },
	{ icon: CgRepeat, name: "CgRepeat", library: "cg" },
	{ icon: CgRing, name: "CgRing", library: "cg" },
	{ icon: CgRowFirst, name: "CgRowFirst", library: "cg" },
	{ icon: CgRowLast, name: "CgRowLast", library: "cg" },
	{ icon: CgRuler, name: "CgRuler", library: "cg" },
	{ icon: CgSandClock, name: "CgSandClock", library: "cg" },
	{ icon: CgScan, name: "CgScan", library: "cg" },
	{ icon: CgScreenMirror, name: "CgScreenMirror", library: "cg" },
	{ icon: CgScreenShot, name: "CgScreenShot", library: "cg" },
	{ icon: CgScreenWide, name: "CgScreenWide", library: "cg" },
	{ icon: CgScreen, name: "CgScreen", library: "cg" },
	{ icon: CgScrollH, name: "CgScrollH", library: "cg" },
	{ icon: CgScrollV, name: "CgScrollV", library: "cg" },
	{ icon: CgSearchFound, name: "CgSearchFound", library: "cg" },
	{ icon: CgSearchLoading, name: "CgSearchLoading", library: "cg" },
	{ icon: CgSearch, name: "CgSearch", library: "cg" },
	{ icon: CgSelectO, name: "CgSelectO", library: "cg" },
	{ icon: CgSelectR, name: "CgSelectR", library: "cg" },
	{ icon: CgSelect, name: "CgSelect", library: "cg" },
	{ icon: CgServer, name: "CgServer", library: "cg" },
	{ icon: CgServerless, name: "CgServerless", library: "cg" },
	{ icon: CgShapeCircle, name: "CgShapeCircle", library: "cg" },
	{ icon: CgShapeHalfCircle, name: "CgShapeHalfCircle", library: "cg" },
	{ icon: CgShapeHexagon, name: "CgShapeHexagon", library: "cg" },
	{ icon: CgShapeRhombus, name: "CgShapeRhombus", library: "cg" },
	{ icon: CgShapeSquare, name: "CgShapeSquare", library: "cg" },
	{ icon: CgShapeTriangle, name: "CgShapeTriangle", library: "cg" },
	{ icon: CgShapeZigzag, name: "CgShapeZigzag", library: "cg" },
	{ icon: CgShare, name: "CgShare", library: "cg" },
	{ icon: CgShield, name: "CgShield", library: "cg" },
	{ icon: CgShoppingBag, name: "CgShoppingBag", library: "cg" },
	{ icon: CgShoppingCart, name: "CgShoppingCart", library: "cg" },
	{ icon: CgShortcut, name: "CgShortcut", library: "cg" },
	{ icon: CgShutterstock, name: "CgShutterstock", library: "cg" },
	{ icon: CgSidebarOpen, name: "CgSidebarOpen", library: "cg" },
	{ icon: CgSidebarRight, name: "CgSidebarRight", library: "cg" },
	{ icon: CgSidebar, name: "CgSidebar", library: "cg" },
	{ icon: CgSignal, name: "CgSignal", library: "cg" },
	{ icon: CgSize, name: "CgSize", library: "cg" },
	{ icon: CgSketch, name: "CgSketch", library: "cg" },
	{ icon: CgSlack, name: "CgSlack", library: "cg" },
	{ icon: CgSleep, name: "CgSleep", library: "cg" },
	{ icon: CgSmartHomeBoiler, name: "CgSmartHomeBoiler", library: "cg" },
	{ icon: CgSmartHomeCooker, name: "CgSmartHomeCooker", library: "cg" },
	{ icon: CgSmartHomeHeat, name: "CgSmartHomeHeat", library: "cg" },
	{ icon: CgSmartHomeLight, name: "CgSmartHomeLight", library: "cg" },
	{ icon: CgSmartHomeRefrigerator, name: "CgSmartHomeRefrigerator", library: "cg" },
	{ icon: CgSmartHomeWashMachine, name: "CgSmartHomeWashMachine", library: "cg" },
	{ icon: CgSmartphoneChip, name: "CgSmartphoneChip", library: "cg" },
	{ icon: CgSmartphoneRam, name: "CgSmartphoneRam", library: "cg" },
	{ icon: CgSmartphoneShake, name: "CgSmartphoneShake", library: "cg" },
	{ icon: CgSmartphone, name: "CgSmartphone", library: "cg" },
	{ icon: CgSmileMouthOpen, name: "CgSmileMouthOpen", library: "cg" },
	{ icon: CgSmileNeutral, name: "CgSmileNeutral", library: "cg" },
	{ icon: CgSmileNoMouth, name: "CgSmileNoMouth", library: "cg" },
	{ icon: CgSmileNone, name: "CgSmileNone", library: "cg" },
	{ icon: CgSmileSad, name: "CgSmileSad", library: "cg" },
	{ icon: CgSmileUpside, name: "CgSmileUpside", library: "cg" },
	{ icon: CgSmile, name: "CgSmile", library: "cg" },
	{ icon: CgSoftwareDownload, name: "CgSoftwareDownload", library: "cg" },
	{ icon: CgSoftwareUpload, name: "CgSoftwareUpload", library: "cg" },
	{ icon: CgSortAz, name: "CgSortAz", library: "cg" },
	{ icon: CgSortZa, name: "CgSortZa", library: "cg" },
	{ icon: CgSpaceBetweenV, name: "CgSpaceBetweenV", library: "cg" },
	{ icon: CgSpaceBetween, name: "CgSpaceBetween", library: "cg" },
	{ icon: CgSpectrum, name: "CgSpectrum", library: "cg" },
	{ icon: CgSpinnerAlt, name: "CgSpinnerAlt", library: "cg" },
	{ icon: CgSpinnerTwoAlt, name: "CgSpinnerTwoAlt", library: "cg" },
	{ icon: CgSpinnerTwo, name: "CgSpinnerTwo", library: "cg" },
	{ icon: CgSpinner, name: "CgSpinner", library: "cg" },
	{ icon: CgSquare, name: "CgSquare", library: "cg" },
	{ icon: CgStack, name: "CgStack", library: "cg" },
	{ icon: CgStark, name: "CgStark", library: "cg" },
	{ icon: CgStopwatch, name: "CgStopwatch", library: "cg" },
	{ icon: CgStories, name: "CgStories", library: "cg" },
	{ icon: CgStudio, name: "CgStudio", library: "cg" },
	{ icon: CgStyle, name: "CgStyle", library: "cg" },
	{ icon: CgSun, name: "CgSun", library: "cg" },
	{ icon: CgSupport, name: "CgSupport", library: "cg" },
	{ icon: CgSwapVertical, name: "CgSwapVertical", library: "cg" },
	{ icon: CgSwap, name: "CgSwap", library: "cg" },
	{ icon: CgSweden, name: "CgSweden", library: "cg" },
	{ icon: CgSwiss, name: "CgSwiss", library: "cg" },
	{ icon: CgSync, name: "CgSync", library: "cg" },
	{ icon: CgTab, name: "CgTab", library: "cg" },
	{ icon: CgTag, name: "CgTag", library: "cg" },
	{ icon: CgTally, name: "CgTally", library: "cg" },
	{ icon: CgTapDouble, name: "CgTapDouble", library: "cg" },
	{ icon: CgTapSingle, name: "CgTapSingle", library: "cg" },
	{ icon: CgTemplate, name: "CgTemplate", library: "cg" },
	{ icon: CgTennis, name: "CgTennis", library: "cg" },
	{ icon: CgTerminal, name: "CgTerminal", library: "cg" },
	{ icon: CgTerrain, name: "CgTerrain", library: "cg" },
	{ icon: CgThermometer, name: "CgThermometer", library: "cg" },
	{ icon: CgThermostat, name: "CgThermostat", library: "cg" },
	{ icon: CgTikcode, name: "CgTikcode", library: "cg" },
	{ icon: CgTime, name: "CgTime", library: "cg" },
	{ icon: CgTimelapse, name: "CgTimelapse", library: "cg" },
	{ icon: CgTimer, name: "CgTimer", library: "cg" },
	{ icon: CgToday, name: "CgToday", library: "cg" },
	{ icon: CgToggleOff, name: "CgToggleOff", library: "cg" },
	{ icon: CgToggleOn, name: "CgToggleOn", library: "cg" },
	{ icon: CgToggleSquareOff, name: "CgToggleSquareOff", library: "cg" },
	{ icon: CgToggleSquare, name: "CgToggleSquare", library: "cg" },
	{ icon: CgToolbarBottom, name: "CgToolbarBottom", library: "cg" },
	{ icon: CgToolbarLeft, name: "CgToolbarLeft", library: "cg" },
	{ icon: CgToolbarRight, name: "CgToolbarRight", library: "cg" },
	{ icon: CgToolbarTop, name: "CgToolbarTop", library: "cg" },
	{ icon: CgToolbox, name: "CgToolbox", library: "cg" },
	{ icon: CgTouchpad, name: "CgTouchpad", library: "cg" },
	{ icon: CgTrack, name: "CgTrack", library: "cg" },
	{ icon: CgTranscript, name: "CgTranscript", library: "cg" },
	{ icon: CgTrashEmpty, name: "CgTrashEmpty", library: "cg" },
	{ icon: CgTrash, name: "CgTrash", library: "cg" },
	{ icon: CgTree, name: "CgTree", library: "cg" },
	{ icon: CgTrees, name: "CgTrees", library: "cg" },
	{ icon: CgTrello, name: "CgTrello", library: "cg" },
	{ icon: CgTrendingDown, name: "CgTrendingDown", library: "cg" },
	{ icon: CgTrending, name: "CgTrending", library: "cg" },
	{ icon: CgTrophy, name: "CgTrophy", library: "cg" },
	{ icon: CgTv, name: "CgTv", library: "cg" },
	{ icon: CgTwilio, name: "CgTwilio", library: "cg" },
	{ icon: CgTwitter, name: "CgTwitter", library: "cg" },
	{ icon: CgUiKit, name: "CgUiKit", library: "cg" },
	{ icon: CgUmbrella, name: "CgUmbrella", library: "cg" },
	{ icon: CgUnavailable, name: "CgUnavailable", library: "cg" },
	{ icon: CgUnblock, name: "CgUnblock", library: "cg" },
	{ icon: CgUndo, name: "CgUndo", library: "cg" },
	{ icon: CgUnfold, name: "CgUnfold", library: "cg" },
	{ icon: CgUnsplash, name: "CgUnsplash", library: "cg" },
	{ icon: CgUsbC, name: "CgUsbC", library: "cg" },
	{ icon: CgUsb, name: "CgUsb", library: "cg" },
	{ icon: CgUserAdd, name: "CgUserAdd", library: "cg" },
	{ icon: CgUserList, name: "CgUserList", library: "cg" },
	{ icon: CgUserRemove, name: "CgUserRemove", library: "cg" },
	{ icon: CgUser, name: "CgUser", library: "cg" },
	{ icon: CgUserlane, name: "CgUserlane", library: "cg" },
	{ icon: CgViewCols, name: "CgViewCols", library: "cg" },
	{ icon: CgViewComfortable, name: "CgViewComfortable", library: "cg" },
	{ icon: CgViewDay, name: "CgViewDay", library: "cg" },
	{ icon: CgViewGrid, name: "CgViewGrid", library: "cg" },
	{ icon: CgViewList, name: "CgViewList", library: "cg" },
	{ icon: CgViewMonth, name: "CgViewMonth", library: "cg" },
	{ icon: CgViewSplit, name: "CgViewSplit", library: "cg" },
	{ icon: CgVinyl, name: "CgVinyl", library: "cg" },
	{ icon: CgVoicemailO, name: "CgVoicemailO", library: "cg" },
	{ icon: CgVoicemailR, name: "CgVoicemailR", library: "cg" },
	{ icon: CgVoicemail, name: "CgVoicemail", library: "cg" },
	{ icon: CgVolume, name: "CgVolume", library: "cg" },
	{ icon: CgWebcam, name: "CgWebcam", library: "cg" },
	{ icon: CgWebsite, name: "CgWebsite", library: "cg" },
	{ icon: CgWindows, name: "CgWindows", library: "cg" },
	{ icon: CgWorkAlt, name: "CgWorkAlt", library: "cg" },
	{ icon: CgYinyang, name: "CgYinyang", library: "cg" },
	{ icon: CgYoutube, name: "CgYoutube", library: "cg" },
	{ icon: CgZeit, name: "CgZeit", library: "cg" },
	{ icon: CgZoomIn, name: "CgZoomIn", library: "cg" },
	{ icon: CgZoomOut, name: "CgZoomOut", library: "cg" },
];

export default result;
