import {
CgAbstract,
CgAddR,
CgAdd,
CgAdidas,
CgAirplane,
CgAlarm,
CgAlbum,
CgAlignBottom,
CgAlignCenter,
CgAlignLeft,
CgAlignMiddle,
CgAlignRight,
CgAlignTop,
CgAnchor,
CgAppleWatch,
CgArrangeBack,
CgArrangeFront,
CgArrowAlignH,
CgArrowAlignV,
CgArrowBottomLeftO,
CgArrowBottomLeftR,
CgArrowBottomLeft,
CgArrowBottomRightO,
CgArrowBottomRightR,
CgArrowBottomRight,
CgArrowDownO,
CgArrowDownR,
CgArrowDown,
CgArrowLeftO,
CgArrowLeftR,
CgArrowLeft,
CgArrowLongDownC,
CgArrowLongDownE,
CgArrowLongDownL,
CgArrowLongDownR,
CgArrowLongDown,
CgArrowLongLeftC,
CgArrowLongLeftE,
CgArrowLongLeftL,
CgArrowLongLeftR,
CgArrowLongLeft,
CgArrowLongRightC,
CgArrowLongRightE,
CgArrowLongRightL,
CgArrowLongRightR,
CgArrowLongRight,
CgArrowLongUpC,
CgArrowLongUpE,
CgArrowLongUpL,
CgArrowLongUpR,
CgArrowLongUp,
CgArrowRightO,
CgArrowRightR,
CgArrowRight,
CgArrowTopLeftO,
CgArrowTopLeftR,
CgArrowTopLeft,
CgArrowTopRightO,
CgArrowTopRightR,
CgArrowTopRight,
CgArrowUpO,
CgArrowUpR,
CgArrowUp,
CgArrowsBreakeH,
CgArrowsBreakeV,
CgArrowsExchangeAltV,
CgArrowsExchangeAlt,
CgArrowsExchangeV,
CgArrowsExchange,
CgArrowsExpandDownLeft,
CgArrowsExpandDownRight,
CgArrowsExpandLeftAlt,
CgArrowsExpandLeft,
CgArrowsExpandRightAlt,
CgArrowsExpandRight,
CgArrowsExpandUpLeft,
CgArrowsExpandUpRight,
CgArrowsHAlt,
CgArrowsH,
CgArrowsMergeAltH,
CgArrowsMergeAltV,
CgArrowsScrollH,
CgArrowsScrollV,
CgArrowsShrinkH,
CgArrowsShrinkV,
CgArrowsVAlt,
CgArrowsV,
CgAssign,
CgAsterisk,
CgAtlasian,
CgAttachment,
CgAttribution,
CgAwards,
CgBackspace,
CgBandAid,
CgBatteryEmpty,
CgBatteryFull,
CgBattery,
CgBee,
CgBell,
CgBitbucket,
CgBlock,
CgBmw,
CgBoard,
CgBolt,
CgBookmark,
CgBorderAll,
CgBorderBottom,
CgBorderLeft,
CgBorderRight,
CgBorderStyleDashed,
CgBorderStyleDotted,
CgBorderStyleSolid,
CgBorderTop,
CgBot,
CgBowl,
CgBox,
CgBoy,
CgBrackets,
CgBriefcase,
CgBrowse,
CgBrowser,
CgBrush,
CgBulb,
CgCPlusPlus,
CgCalculator,
CgCalendarDates,
CgCalendarDue,
CgCalendarNext,
CgCalendarToday,
CgCalendarTwo,
CgCalendar,
CgCalibrate,
CgCamera,
CgCap,
CgCaptions,
CgCardClubs,
CgCardDiamonds,
CgCardHearts,
CgCardSpades,
CgCarousel,
CgCast,
CgChanel,
CgChart,
CgCheckO,
CgCheckR,
CgCheck,
CgChevronDoubleDownO,
CgChevronDoubleDownR,
CgChevronDoubleDown,
CgChevronDoubleLeftO,
CgChevronDoubleLeftR,
CgChevronDoubleLeft,
CgChevronDoubleRightO,
CgChevronDoubleRightR,
CgChevronDoubleRight,
CgChevronDoubleUpO,
CgChevronDoubleUpR,
CgChevronDoubleUp,
CgChevronDownO,
CgChevronDownR,
CgChevronDown,
CgChevronLeftO,
CgChevronLeftR,
CgChevronLeft,
CgChevronRightO,
CgChevronRightR,
CgChevronRight,
CgChevronUpO,
CgChevronUpR,
CgChevronUp,
CgCircleci,
CgClapperBoard,
CgClipboard,
CgCloseO,
CgCloseR,
CgClose,
CgCloud,
CgCodeClimate,
CgCodeSlash,
CgCode,
CgCoffee,
CgCollage,
CgColorBucket,
CgColorPicker,
CgComedyCentral,
CgComment,
CgCommunity,
CgComponents,
CgCompressLeft,
CgCompressRight,
CgCompressV,
CgCompress,
CgController,
CgCopy,
CgCopyright,
CgCornerDoubleDownLeft,
CgCornerDoubleDownRight,
CgCornerDoubleLeftDown,
CgCornerDoubleLeftUp,
CgCornerDoubleRightDown,
CgCornerDoubleRightUp,
CgCornerDoubleUpLeft,
CgCornerDoubleUpRight,
CgCornerDownLeft,
CgCornerDownRight,
CgCornerLeftDown,
CgCornerLeftUp,
CgCornerRightDown,
CgCornerRightUp,
CgCornerUpLeft,
CgCornerUpRight,
CgCreditCard,
CgCrop,
CgCross,
CgCrowdfire,
CgCrown,
CgDanger,
CgDarkMode,
CgData,
CgDatabase,
CgDebug,
CgDesignmodo,
CgDesktop,
CgDetailsLess,
CgDetailsMore,
CgDialpad,
CgDice1,
CgDice2,
CgDice3,
CgDice4,
CgDice5,
CgDice6,
CgDigitalocean,
CgDisc,
CgDisplayFlex,
CgDisplayFullwidth,
CgDisplayGrid,
CgDisplaySpacing,
CgDistributeHorizontal,
CgDistributeVertical,
CgDockBottom,
CgDockLeft,
CgDockRight,
CgDockWindow,
CgDolby,
CgDollar,
CgDribbble,
CgDrive,
CgDropInvert,
CgDropOpacity,
CgDrop,
CgDuplicate,
CgEditBlackPoint,
CgEditContrast,
CgEditExposure,
CgEditFade,
CgEditFlipH,
CgEditFlipV,
CgEditHighlight,
CgEditMarkup,
CgEditMask,
CgEditNoise,
CgEditShadows,
CgEditStraight,
CgEditUnmask,
CgEject,
CgEnter,
CgErase,
CgEreader,
CgEricsson,
CgEthernet,
CgEuro,
CgEventbrite,
CgExpand,
CgExport,
CgExtensionAdd,
CgExtensionAlt,
CgExtensionRemove,
CgExtension,
CgExternal,
CgEyeAlt,
CgEye,
CgFacebook,
CgFeed,
CgFigma,
CgFileAdd,
CgFileDocument,
CgFileRemove,
CgFile,
CgFilm,
CgFilters,
CgFlagAlt,
CgFlag,
CgFolderAdd,
CgFolderRemove,
CgFolder,
CgFontHeight,
CgFontSpacing,
CgFormatBold,
CgFormatCenter,
CgFormatColor,
CgFormatHeading,
CgFormatIndentDecrease,
CgFormatIndentIncrease,
CgFormatItalic,
CgFormatJustify,
CgFormatLeft,
CgFormatLineHeight,
CgFormatRight,
CgFormatSeparator,
CgFormatSlash,
CgFormatStrike,
CgFormatText,
CgFormatUnderline,
CgFormatUppercase,
CgFramer,
CgGames,
CgGenderFemale,
CgGenderMale,
CgGhostCharacter,
CgGhost,
CgGift,
CgGirl,
CgGitBranch,
CgGitCommit,
CgGitFork,
CgGitPull,
CgGitter,
CgGlassAlt,
CgGlass,
CgGlobeAlt,
CgGlobe,
CgGoogleTasks,
CgGoogle,
CgGym,
CgHashtag,
CgHeadset,
CgHeart,
CgHello,
CgHomeAlt,
CgHomeScreen,
CgHome,
CgIcecream,
CgIfDesign,
CgImage,
CgImport,
CgInbox,
CgIndieHackers,
CgInfinity,
CgInfo,
CgInpicture,
CgInsertAfterO,
CgInsertAfterR,
CgInsertAfter,
CgInsertBeforeO,
CgInsertBeforeR,
CgInsertBefore,
CgInsights,
CgInstagram,
CgInternal,
CgKey,
CgKeyboard,
CgKeyhole,
CgLaptop,
CgLastpass,
CgLayoutGridSmall,
CgLayoutGrid,
CgLayoutList,
CgLayoutPin,
CgLinear,
CgLink,
CgListTree,
CgList,
CgLivePhoto,
CgLoadbarAlt,
CgLoadbarDoc,
CgLoadbarSound,
CgLoadbar,
CgLockUnlock,
CgLock,
CgLogIn,
CgLogOff,
CgLogOut,
CgLoupe,
CgMagnet,
CgMailForward,
CgMailOpen,
CgMailReply,
CgMail,
CgMathDivide,
CgMathEqual,
CgMathMinus,
CgMathPercent,
CgMathPlus,
CgMaximizeAlt,
CgMaximize,
CgMaze,
CgMediaLive,
CgMediaPodcast,
CgMenuBoxed,
CgMenuCake,
CgMenuCheese,
CgMenuGridO,
CgMenuGridR,
CgMenuHotdog,
CgMenuLeftAlt,
CgMenuLeft,
CgMenuMotion,
CgMenuOreos,
CgMenuRightAlt,
CgMenuRight,
CgMenuRound,
CgMenu,
CgMergeHorizontal,
CgMergeVertical,
CgMic,
CgMicrobit,
CgMicrosoft,
CgMiniPlayer,
CgMinimizeAlt,
CgMinimize,
CgModem,
CgMonday,
CgMoon,
CgMoreAlt,
CgMoreO,
CgMoreR,
CgMoreVerticalAlt,
CgMoreVerticalO,
CgMoreVerticalR,
CgMoreVertical,
CgMore,
CgMouse,
CgMoveDown,
CgMoveLeft,
CgMoveRight,
CgMoveTask,
CgMoveUp,
CgMusicNote,
CgMusicSpeaker,
CgMusic,
CgNametag,
CgNotes,
CgNotifications,
CgNpm,
CgOculus,
CgOpenCollective,
CgOptions,
CgOrganisation,
CgOverflow,
CgPacman,
CgPassword,
CgPathBack,
CgPathCrop,
CgPathDivide,
CgPathExclude,
CgPathFront,
CgPathIntersect,
CgPathOutline,
CgPathTrim,
CgPathUnite,
CgPatreon,
CgPaypal,
CgPen,
CgPentagonBottomLeft,
CgPentagonBottomRight,
CgPentagonDown,
CgPentagonLeft,
CgPentagonRight,
CgPentagonTopLeft,
CgPentagonTopRight,
CgPentagonUp,
CgPerformance,
CgPexels,
CgPhone,
CgPhotoscan,
CgPiano,
CgPill,
CgPinAlt,
CgPinBottom,
CgPinTop,
CgPin,
CgPlayBackwards,
CgPlayButtonO,
CgPlayButtonR,
CgPlayButton,
CgPlayForwards,
CgPlayListAdd,
CgPlayListCheck,
CgPlayListRemove,
CgPlayListSearch,
CgPlayList,
CgPlayPauseO,
CgPlayPauseR,
CgPlayPause,
CgPlayStopO,
CgPlayStopR,
CgPlayStop,
CgPlayTrackNextO,
CgPlayTrackNextR,
CgPlayTrackNext,
CgPlayTrackPrevO,
CgPlayTrackPrevR,
CgPlayTrackPrev,
CgPlug,
CgPocket,
CgPokemon,
CgPolaroid,
CgPoll,
CgPresentation,
CgPrinter,
CgProductHunt,
CgProfile,
CgPullClear,
CgPushChevronDownO,
CgPushChevronDownR,
CgPushChevronDown,
CgPushChevronLeftO,
CgPushChevronLeftR,
CgPushChevronLeft,
CgPushChevronRightO,
CgPushChevronRightR,
CgPushChevronRight,
CgPushChevronUpO,
CgPushChevronUpR,
CgPushChevronUp,
CgPushDown,
CgPushLeft,
CgPushRight,
CgPushUp,
CgQr,
CgQuoteO,
CgQuote,
CgRadioCheck,
CgRadioChecked,
CgRatio,
CgRead,
CgReadme,
CgRecord,
CgRedo,
CgRemote,
CgRemoveR,
CgRemove,
CgRename,
CgReorder,
CgRepeat,
CgRing,
CgRowFirst,
CgRowLast,
CgRuler,
CgSandClock,
CgScan,
CgScreenMirror,
CgScreenShot,
CgScreenWide,
CgScreen,
CgScrollH,
CgScrollV,
CgSearchFound,
CgSearchLoading,
CgSearch,
CgSelectO,
CgSelectR,
CgSelect,
CgServer,
CgServerless,
CgShapeCircle,
CgShapeHalfCircle,
CgShapeHexagon,
CgShapeRhombus,
CgShapeSquare,
CgShapeTriangle,
CgShapeZigzag,
CgShare,
CgShield,
CgShoppingBag,
CgShoppingCart,
CgShortcut,
CgShutterstock,
CgSidebarOpen,
CgSidebarRight,
CgSidebar,
CgSignal,
CgSize,
CgSketch,
CgSlack,
CgSleep,
CgSmartHomeBoiler,
CgSmartHomeCooker,
CgSmartHomeHeat,
CgSmartHomeLight,
CgSmartHomeRefrigerator,
CgSmartHomeWashMachine,
CgSmartphoneChip,
CgSmartphoneRam,
CgSmartphoneShake,
CgSmartphone,
CgSmileMouthOpen,
CgSmileNeutral,
CgSmileNoMouth,
CgSmileNone,
CgSmileSad,
CgSmileUpside,
CgSmile,
CgSoftwareDownload,
CgSoftwareUpload,
CgSortAz,
CgSortZa,
CgSpaceBetweenV,
CgSpaceBetween,
CgSpectrum,
CgSpinnerAlt,
CgSpinnerTwoAlt,
CgSpinnerTwo,
CgSpinner,
CgSquare,
CgStack,
CgStark,
CgStopwatch,
CgStories,
CgStudio,
CgStyle,
CgSun,
CgSupport,
CgSwapVertical,
CgSwap,
CgSweden,
CgSwiss,
CgSync,
CgTab,
CgTag,
CgTally,
CgTapDouble,
CgTapSingle,
CgTemplate,
CgTennis,
CgTerminal,
CgTerrain,
CgThermometer,
CgThermostat,
CgTikcode,
CgTime,
CgTimelapse,
CgTimer,
CgToday,
CgToggleOff,
CgToggleOn,
CgToggleSquareOff,
CgToggleSquare,
CgToolbarBottom,
CgToolbarLeft,
CgToolbarRight,
CgToolbarTop,
CgToolbox,
CgTouchpad,
CgTrack,
CgTranscript,
CgTrashEmpty,
CgTrash,
CgTree,
CgTrees,
CgTrello,
CgTrendingDown,
CgTrending,
CgTrophy,
CgTv,
CgTwilio,
CgTwitter,
CgUiKit,
CgUmbrella,
CgUnavailable,
CgUnblock,
CgUndo,
CgUnfold,
CgUnsplash,
CgUsbC,
CgUsb,
CgUserAdd,
CgUserList,
CgUserRemove,
CgUser,
CgUserlane,
CgViewCols,
CgViewComfortable,
CgViewDay,
CgViewGrid,
CgViewList,
CgViewMonth,
CgViewSplit,
CgVinyl,
CgVoicemailO,
CgVoicemailR,
CgVoicemail,
CgVolume,
CgWebcam,
CgWebsite,
CgWindows,
CgWorkAlt,
CgYinyang,
CgYoutube,
CgZeit,
CgZoomIn,
CgZoomOut,
} from "react-icons/cg";

const result = [
{ icon: CgAbstract, name: "CgAbstract" },
{ icon: CgAddR, name: "CgAddR" },
{ icon: CgAdd, name: "CgAdd" },
{ icon: CgAdidas, name: "CgAdidas" },
{ icon: CgAirplane, name: "CgAirplane" },
{ icon: CgAlarm, name: "CgAlarm" },
{ icon: CgAlbum, name: "CgAlbum" },
{ icon: CgAlignBottom, name: "CgAlignBottom" },
{ icon: CgAlignCenter, name: "CgAlignCenter" },
{ icon: CgAlignLeft, name: "CgAlignLeft" },
{ icon: CgAlignMiddle, name: "CgAlignMiddle" },
{ icon: CgAlignRight, name: "CgAlignRight" },
{ icon: CgAlignTop, name: "CgAlignTop" },
{ icon: CgAnchor, name: "CgAnchor" },
{ icon: CgAppleWatch, name: "CgAppleWatch" },
{ icon: CgArrangeBack, name: "CgArrangeBack" },
{ icon: CgArrangeFront, name: "CgArrangeFront" },
{ icon: CgArrowAlignH, name: "CgArrowAlignH" },
{ icon: CgArrowAlignV, name: "CgArrowAlignV" },
{ icon: CgArrowBottomLeftO, name: "CgArrowBottomLeftO" },
{ icon: CgArrowBottomLeftR, name: "CgArrowBottomLeftR" },
{ icon: CgArrowBottomLeft, name: "CgArrowBottomLeft" },
{ icon: CgArrowBottomRightO, name: "CgArrowBottomRightO" },
{ icon: CgArrowBottomRightR, name: "CgArrowBottomRightR" },
{ icon: CgArrowBottomRight, name: "CgArrowBottomRight" },
{ icon: CgArrowDownO, name: "CgArrowDownO" },
{ icon: CgArrowDownR, name: "CgArrowDownR" },
{ icon: CgArrowDown, name: "CgArrowDown" },
{ icon: CgArrowLeftO, name: "CgArrowLeftO" },
{ icon: CgArrowLeftR, name: "CgArrowLeftR" },
{ icon: CgArrowLeft, name: "CgArrowLeft" },
{ icon: CgArrowLongDownC, name: "CgArrowLongDownC" },
{ icon: CgArrowLongDownE, name: "CgArrowLongDownE" },
{ icon: CgArrowLongDownL, name: "CgArrowLongDownL" },
{ icon: CgArrowLongDownR, name: "CgArrowLongDownR" },
{ icon: CgArrowLongDown, name: "CgArrowLongDown" },
{ icon: CgArrowLongLeftC, name: "CgArrowLongLeftC" },
{ icon: CgArrowLongLeftE, name: "CgArrowLongLeftE" },
{ icon: CgArrowLongLeftL, name: "CgArrowLongLeftL" },
{ icon: CgArrowLongLeftR, name: "CgArrowLongLeftR" },
{ icon: CgArrowLongLeft, name: "CgArrowLongLeft" },
{ icon: CgArrowLongRightC, name: "CgArrowLongRightC" },
{ icon: CgArrowLongRightE, name: "CgArrowLongRightE" },
{ icon: CgArrowLongRightL, name: "CgArrowLongRightL" },
{ icon: CgArrowLongRightR, name: "CgArrowLongRightR" },
{ icon: CgArrowLongRight, name: "CgArrowLongRight" },
{ icon: CgArrowLongUpC, name: "CgArrowLongUpC" },
{ icon: CgArrowLongUpE, name: "CgArrowLongUpE" },
{ icon: CgArrowLongUpL, name: "CgArrowLongUpL" },
{ icon: CgArrowLongUpR, name: "CgArrowLongUpR" },
{ icon: CgArrowLongUp, name: "CgArrowLongUp" },
{ icon: CgArrowRightO, name: "CgArrowRightO" },
{ icon: CgArrowRightR, name: "CgArrowRightR" },
{ icon: CgArrowRight, name: "CgArrowRight" },
{ icon: CgArrowTopLeftO, name: "CgArrowTopLeftO" },
{ icon: CgArrowTopLeftR, name: "CgArrowTopLeftR" },
{ icon: CgArrowTopLeft, name: "CgArrowTopLeft" },
{ icon: CgArrowTopRightO, name: "CgArrowTopRightO" },
{ icon: CgArrowTopRightR, name: "CgArrowTopRightR" },
{ icon: CgArrowTopRight, name: "CgArrowTopRight" },
{ icon: CgArrowUpO, name: "CgArrowUpO" },
{ icon: CgArrowUpR, name: "CgArrowUpR" },
{ icon: CgArrowUp, name: "CgArrowUp" },
{ icon: CgArrowsBreakeH, name: "CgArrowsBreakeH" },
{ icon: CgArrowsBreakeV, name: "CgArrowsBreakeV" },
{ icon: CgArrowsExchangeAltV, name: "CgArrowsExchangeAltV" },
{ icon: CgArrowsExchangeAlt, name: "CgArrowsExchangeAlt" },
{ icon: CgArrowsExchangeV, name: "CgArrowsExchangeV" },
{ icon: CgArrowsExchange, name: "CgArrowsExchange" },
{ icon: CgArrowsExpandDownLeft, name: "CgArrowsExpandDownLeft" },
{ icon: CgArrowsExpandDownRight, name: "CgArrowsExpandDownRight" },
{ icon: CgArrowsExpandLeftAlt, name: "CgArrowsExpandLeftAlt" },
{ icon: CgArrowsExpandLeft, name: "CgArrowsExpandLeft" },
{ icon: CgArrowsExpandRightAlt, name: "CgArrowsExpandRightAlt" },
{ icon: CgArrowsExpandRight, name: "CgArrowsExpandRight" },
{ icon: CgArrowsExpandUpLeft, name: "CgArrowsExpandUpLeft" },
{ icon: CgArrowsExpandUpRight, name: "CgArrowsExpandUpRight" },
{ icon: CgArrowsHAlt, name: "CgArrowsHAlt" },
{ icon: CgArrowsH, name: "CgArrowsH" },
{ icon: CgArrowsMergeAltH, name: "CgArrowsMergeAltH" },
{ icon: CgArrowsMergeAltV, name: "CgArrowsMergeAltV" },
{ icon: CgArrowsScrollH, name: "CgArrowsScrollH" },
{ icon: CgArrowsScrollV, name: "CgArrowsScrollV" },
{ icon: CgArrowsShrinkH, name: "CgArrowsShrinkH" },
{ icon: CgArrowsShrinkV, name: "CgArrowsShrinkV" },
{ icon: CgArrowsVAlt, name: "CgArrowsVAlt" },
{ icon: CgArrowsV, name: "CgArrowsV" },
{ icon: CgAssign, name: "CgAssign" },
{ icon: CgAsterisk, name: "CgAsterisk" },
{ icon: CgAtlasian, name: "CgAtlasian" },
{ icon: CgAttachment, name: "CgAttachment" },
{ icon: CgAttribution, name: "CgAttribution" },
{ icon: CgAwards, name: "CgAwards" },
{ icon: CgBackspace, name: "CgBackspace" },
{ icon: CgBandAid, name: "CgBandAid" },
{ icon: CgBatteryEmpty, name: "CgBatteryEmpty" },
{ icon: CgBatteryFull, name: "CgBatteryFull" },
{ icon: CgBattery, name: "CgBattery" },
{ icon: CgBee, name: "CgBee" },
{ icon: CgBell, name: "CgBell" },
{ icon: CgBitbucket, name: "CgBitbucket" },
{ icon: CgBlock, name: "CgBlock" },
{ icon: CgBmw, name: "CgBmw" },
{ icon: CgBoard, name: "CgBoard" },
{ icon: CgBolt, name: "CgBolt" },
{ icon: CgBookmark, name: "CgBookmark" },
{ icon: CgBorderAll, name: "CgBorderAll" },
{ icon: CgBorderBottom, name: "CgBorderBottom" },
{ icon: CgBorderLeft, name: "CgBorderLeft" },
{ icon: CgBorderRight, name: "CgBorderRight" },
{ icon: CgBorderStyleDashed, name: "CgBorderStyleDashed" },
{ icon: CgBorderStyleDotted, name: "CgBorderStyleDotted" },
{ icon: CgBorderStyleSolid, name: "CgBorderStyleSolid" },
{ icon: CgBorderTop, name: "CgBorderTop" },
{ icon: CgBot, name: "CgBot" },
{ icon: CgBowl, name: "CgBowl" },
{ icon: CgBox, name: "CgBox" },
{ icon: CgBoy, name: "CgBoy" },
{ icon: CgBrackets, name: "CgBrackets" },
{ icon: CgBriefcase, name: "CgBriefcase" },
{ icon: CgBrowse, name: "CgBrowse" },
{ icon: CgBrowser, name: "CgBrowser" },
{ icon: CgBrush, name: "CgBrush" },
{ icon: CgBulb, name: "CgBulb" },
{ icon: CgCPlusPlus, name: "CgCPlusPlus" },
{ icon: CgCalculator, name: "CgCalculator" },
{ icon: CgCalendarDates, name: "CgCalendarDates" },
{ icon: CgCalendarDue, name: "CgCalendarDue" },
{ icon: CgCalendarNext, name: "CgCalendarNext" },
{ icon: CgCalendarToday, name: "CgCalendarToday" },
{ icon: CgCalendarTwo, name: "CgCalendarTwo" },
{ icon: CgCalendar, name: "CgCalendar" },
{ icon: CgCalibrate, name: "CgCalibrate" },
{ icon: CgCamera, name: "CgCamera" },
{ icon: CgCap, name: "CgCap" },
{ icon: CgCaptions, name: "CgCaptions" },
{ icon: CgCardClubs, name: "CgCardClubs" },
{ icon: CgCardDiamonds, name: "CgCardDiamonds" },
{ icon: CgCardHearts, name: "CgCardHearts" },
{ icon: CgCardSpades, name: "CgCardSpades" },
{ icon: CgCarousel, name: "CgCarousel" },
{ icon: CgCast, name: "CgCast" },
{ icon: CgChanel, name: "CgChanel" },
{ icon: CgChart, name: "CgChart" },
{ icon: CgCheckO, name: "CgCheckO" },
{ icon: CgCheckR, name: "CgCheckR" },
{ icon: CgCheck, name: "CgCheck" },
{ icon: CgChevronDoubleDownO, name: "CgChevronDoubleDownO" },
{ icon: CgChevronDoubleDownR, name: "CgChevronDoubleDownR" },
{ icon: CgChevronDoubleDown, name: "CgChevronDoubleDown" },
{ icon: CgChevronDoubleLeftO, name: "CgChevronDoubleLeftO" },
{ icon: CgChevronDoubleLeftR, name: "CgChevronDoubleLeftR" },
{ icon: CgChevronDoubleLeft, name: "CgChevronDoubleLeft" },
{ icon: CgChevronDoubleRightO, name: "CgChevronDoubleRightO" },
{ icon: CgChevronDoubleRightR, name: "CgChevronDoubleRightR" },
{ icon: CgChevronDoubleRight, name: "CgChevronDoubleRight" },
{ icon: CgChevronDoubleUpO, name: "CgChevronDoubleUpO" },
{ icon: CgChevronDoubleUpR, name: "CgChevronDoubleUpR" },
{ icon: CgChevronDoubleUp, name: "CgChevronDoubleUp" },
{ icon: CgChevronDownO, name: "CgChevronDownO" },
{ icon: CgChevronDownR, name: "CgChevronDownR" },
{ icon: CgChevronDown, name: "CgChevronDown" },
{ icon: CgChevronLeftO, name: "CgChevronLeftO" },
{ icon: CgChevronLeftR, name: "CgChevronLeftR" },
{ icon: CgChevronLeft, name: "CgChevronLeft" },
{ icon: CgChevronRightO, name: "CgChevronRightO" },
{ icon: CgChevronRightR, name: "CgChevronRightR" },
{ icon: CgChevronRight, name: "CgChevronRight" },
{ icon: CgChevronUpO, name: "CgChevronUpO" },
{ icon: CgChevronUpR, name: "CgChevronUpR" },
{ icon: CgChevronUp, name: "CgChevronUp" },
{ icon: CgCircleci, name: "CgCircleci" },
{ icon: CgClapperBoard, name: "CgClapperBoard" },
{ icon: CgClipboard, name: "CgClipboard" },
{ icon: CgCloseO, name: "CgCloseO" },
{ icon: CgCloseR, name: "CgCloseR" },
{ icon: CgClose, name: "CgClose" },
{ icon: CgCloud, name: "CgCloud" },
{ icon: CgCodeClimate, name: "CgCodeClimate" },
{ icon: CgCodeSlash, name: "CgCodeSlash" },
{ icon: CgCode, name: "CgCode" },
{ icon: CgCoffee, name: "CgCoffee" },
{ icon: CgCollage, name: "CgCollage" },
{ icon: CgColorBucket, name: "CgColorBucket" },
{ icon: CgColorPicker, name: "CgColorPicker" },
{ icon: CgComedyCentral, name: "CgComedyCentral" },
{ icon: CgComment, name: "CgComment" },
{ icon: CgCommunity, name: "CgCommunity" },
{ icon: CgComponents, name: "CgComponents" },
{ icon: CgCompressLeft, name: "CgCompressLeft" },
{ icon: CgCompressRight, name: "CgCompressRight" },
{ icon: CgCompressV, name: "CgCompressV" },
{ icon: CgCompress, name: "CgCompress" },
{ icon: CgController, name: "CgController" },
{ icon: CgCopy, name: "CgCopy" },
{ icon: CgCopyright, name: "CgCopyright" },
{ icon: CgCornerDoubleDownLeft, name: "CgCornerDoubleDownLeft" },
{ icon: CgCornerDoubleDownRight, name: "CgCornerDoubleDownRight" },
{ icon: CgCornerDoubleLeftDown, name: "CgCornerDoubleLeftDown" },
{ icon: CgCornerDoubleLeftUp, name: "CgCornerDoubleLeftUp" },
{ icon: CgCornerDoubleRightDown, name: "CgCornerDoubleRightDown" },
{ icon: CgCornerDoubleRightUp, name: "CgCornerDoubleRightUp" },
{ icon: CgCornerDoubleUpLeft, name: "CgCornerDoubleUpLeft" },
{ icon: CgCornerDoubleUpRight, name: "CgCornerDoubleUpRight" },
{ icon: CgCornerDownLeft, name: "CgCornerDownLeft" },
{ icon: CgCornerDownRight, name: "CgCornerDownRight" },
{ icon: CgCornerLeftDown, name: "CgCornerLeftDown" },
{ icon: CgCornerLeftUp, name: "CgCornerLeftUp" },
{ icon: CgCornerRightDown, name: "CgCornerRightDown" },
{ icon: CgCornerRightUp, name: "CgCornerRightUp" },
{ icon: CgCornerUpLeft, name: "CgCornerUpLeft" },
{ icon: CgCornerUpRight, name: "CgCornerUpRight" },
{ icon: CgCreditCard, name: "CgCreditCard" },
{ icon: CgCrop, name: "CgCrop" },
{ icon: CgCross, name: "CgCross" },
{ icon: CgCrowdfire, name: "CgCrowdfire" },
{ icon: CgCrown, name: "CgCrown" },
{ icon: CgDanger, name: "CgDanger" },
{ icon: CgDarkMode, name: "CgDarkMode" },
{ icon: CgData, name: "CgData" },
{ icon: CgDatabase, name: "CgDatabase" },
{ icon: CgDebug, name: "CgDebug" },
{ icon: CgDesignmodo, name: "CgDesignmodo" },
{ icon: CgDesktop, name: "CgDesktop" },
{ icon: CgDetailsLess, name: "CgDetailsLess" },
{ icon: CgDetailsMore, name: "CgDetailsMore" },
{ icon: CgDialpad, name: "CgDialpad" },
{ icon: CgDice1, name: "CgDice1" },
{ icon: CgDice2, name: "CgDice2" },
{ icon: CgDice3, name: "CgDice3" },
{ icon: CgDice4, name: "CgDice4" },
{ icon: CgDice5, name: "CgDice5" },
{ icon: CgDice6, name: "CgDice6" },
{ icon: CgDigitalocean, name: "CgDigitalocean" },
{ icon: CgDisc, name: "CgDisc" },
{ icon: CgDisplayFlex, name: "CgDisplayFlex" },
{ icon: CgDisplayFullwidth, name: "CgDisplayFullwidth" },
{ icon: CgDisplayGrid, name: "CgDisplayGrid" },
{ icon: CgDisplaySpacing, name: "CgDisplaySpacing" },
{ icon: CgDistributeHorizontal, name: "CgDistributeHorizontal" },
{ icon: CgDistributeVertical, name: "CgDistributeVertical" },
{ icon: CgDockBottom, name: "CgDockBottom" },
{ icon: CgDockLeft, name: "CgDockLeft" },
{ icon: CgDockRight, name: "CgDockRight" },
{ icon: CgDockWindow, name: "CgDockWindow" },
{ icon: CgDolby, name: "CgDolby" },
{ icon: CgDollar, name: "CgDollar" },
{ icon: CgDribbble, name: "CgDribbble" },
{ icon: CgDrive, name: "CgDrive" },
{ icon: CgDropInvert, name: "CgDropInvert" },
{ icon: CgDropOpacity, name: "CgDropOpacity" },
{ icon: CgDrop, name: "CgDrop" },
{ icon: CgDuplicate, name: "CgDuplicate" },
{ icon: CgEditBlackPoint, name: "CgEditBlackPoint" },
{ icon: CgEditContrast, name: "CgEditContrast" },
{ icon: CgEditExposure, name: "CgEditExposure" },
{ icon: CgEditFade, name: "CgEditFade" },
{ icon: CgEditFlipH, name: "CgEditFlipH" },
{ icon: CgEditFlipV, name: "CgEditFlipV" },
{ icon: CgEditHighlight, name: "CgEditHighlight" },
{ icon: CgEditMarkup, name: "CgEditMarkup" },
{ icon: CgEditMask, name: "CgEditMask" },
{ icon: CgEditNoise, name: "CgEditNoise" },
{ icon: CgEditShadows, name: "CgEditShadows" },
{ icon: CgEditStraight, name: "CgEditStraight" },
{ icon: CgEditUnmask, name: "CgEditUnmask" },
{ icon: CgEject, name: "CgEject" },
{ icon: CgEnter, name: "CgEnter" },
{ icon: CgErase, name: "CgErase" },
{ icon: CgEreader, name: "CgEreader" },
{ icon: CgEricsson, name: "CgEricsson" },
{ icon: CgEthernet, name: "CgEthernet" },
{ icon: CgEuro, name: "CgEuro" },
{ icon: CgEventbrite, name: "CgEventbrite" },
{ icon: CgExpand, name: "CgExpand" },
{ icon: CgExport, name: "CgExport" },
{ icon: CgExtensionAdd, name: "CgExtensionAdd" },
{ icon: CgExtensionAlt, name: "CgExtensionAlt" },
{ icon: CgExtensionRemove, name: "CgExtensionRemove" },
{ icon: CgExtension, name: "CgExtension" },
{ icon: CgExternal, name: "CgExternal" },
{ icon: CgEyeAlt, name: "CgEyeAlt" },
{ icon: CgEye, name: "CgEye" },
{ icon: CgFacebook, name: "CgFacebook" },
{ icon: CgFeed, name: "CgFeed" },
{ icon: CgFigma, name: "CgFigma" },
{ icon: CgFileAdd, name: "CgFileAdd" },
{ icon: CgFileDocument, name: "CgFileDocument" },
{ icon: CgFileRemove, name: "CgFileRemove" },
{ icon: CgFile, name: "CgFile" },
{ icon: CgFilm, name: "CgFilm" },
{ icon: CgFilters, name: "CgFilters" },
{ icon: CgFlagAlt, name: "CgFlagAlt" },
{ icon: CgFlag, name: "CgFlag" },
{ icon: CgFolderAdd, name: "CgFolderAdd" },
{ icon: CgFolderRemove, name: "CgFolderRemove" },
{ icon: CgFolder, name: "CgFolder" },
{ icon: CgFontHeight, name: "CgFontHeight" },
{ icon: CgFontSpacing, name: "CgFontSpacing" },
{ icon: CgFormatBold, name: "CgFormatBold" },
{ icon: CgFormatCenter, name: "CgFormatCenter" },
{ icon: CgFormatColor, name: "CgFormatColor" },
{ icon: CgFormatHeading, name: "CgFormatHeading" },
{ icon: CgFormatIndentDecrease, name: "CgFormatIndentDecrease" },
{ icon: CgFormatIndentIncrease, name: "CgFormatIndentIncrease" },
{ icon: CgFormatItalic, name: "CgFormatItalic" },
{ icon: CgFormatJustify, name: "CgFormatJustify" },
{ icon: CgFormatLeft, name: "CgFormatLeft" },
{ icon: CgFormatLineHeight, name: "CgFormatLineHeight" },
{ icon: CgFormatRight, name: "CgFormatRight" },
{ icon: CgFormatSeparator, name: "CgFormatSeparator" },
{ icon: CgFormatSlash, name: "CgFormatSlash" },
{ icon: CgFormatStrike, name: "CgFormatStrike" },
{ icon: CgFormatText, name: "CgFormatText" },
{ icon: CgFormatUnderline, name: "CgFormatUnderline" },
{ icon: CgFormatUppercase, name: "CgFormatUppercase" },
{ icon: CgFramer, name: "CgFramer" },
{ icon: CgGames, name: "CgGames" },
{ icon: CgGenderFemale, name: "CgGenderFemale" },
{ icon: CgGenderMale, name: "CgGenderMale" },
{ icon: CgGhostCharacter, name: "CgGhostCharacter" },
{ icon: CgGhost, name: "CgGhost" },
{ icon: CgGift, name: "CgGift" },
{ icon: CgGirl, name: "CgGirl" },
{ icon: CgGitBranch, name: "CgGitBranch" },
{ icon: CgGitCommit, name: "CgGitCommit" },
{ icon: CgGitFork, name: "CgGitFork" },
{ icon: CgGitPull, name: "CgGitPull" },
{ icon: CgGitter, name: "CgGitter" },
{ icon: CgGlassAlt, name: "CgGlassAlt" },
{ icon: CgGlass, name: "CgGlass" },
{ icon: CgGlobeAlt, name: "CgGlobeAlt" },
{ icon: CgGlobe, name: "CgGlobe" },
{ icon: CgGoogleTasks, name: "CgGoogleTasks" },
{ icon: CgGoogle, name: "CgGoogle" },
{ icon: CgGym, name: "CgGym" },
{ icon: CgHashtag, name: "CgHashtag" },
{ icon: CgHeadset, name: "CgHeadset" },
{ icon: CgHeart, name: "CgHeart" },
{ icon: CgHello, name: "CgHello" },
{ icon: CgHomeAlt, name: "CgHomeAlt" },
{ icon: CgHomeScreen, name: "CgHomeScreen" },
{ icon: CgHome, name: "CgHome" },
{ icon: CgIcecream, name: "CgIcecream" },
{ icon: CgIfDesign, name: "CgIfDesign" },
{ icon: CgImage, name: "CgImage" },
{ icon: CgImport, name: "CgImport" },
{ icon: CgInbox, name: "CgInbox" },
{ icon: CgIndieHackers, name: "CgIndieHackers" },
{ icon: CgInfinity, name: "CgInfinity" },
{ icon: CgInfo, name: "CgInfo" },
{ icon: CgInpicture, name: "CgInpicture" },
{ icon: CgInsertAfterO, name: "CgInsertAfterO" },
{ icon: CgInsertAfterR, name: "CgInsertAfterR" },
{ icon: CgInsertAfter, name: "CgInsertAfter" },
{ icon: CgInsertBeforeO, name: "CgInsertBeforeO" },
{ icon: CgInsertBeforeR, name: "CgInsertBeforeR" },
{ icon: CgInsertBefore, name: "CgInsertBefore" },
{ icon: CgInsights, name: "CgInsights" },
{ icon: CgInstagram, name: "CgInstagram" },
{ icon: CgInternal, name: "CgInternal" },
{ icon: CgKey, name: "CgKey" },
{ icon: CgKeyboard, name: "CgKeyboard" },
{ icon: CgKeyhole, name: "CgKeyhole" },
{ icon: CgLaptop, name: "CgLaptop" },
{ icon: CgLastpass, name: "CgLastpass" },
{ icon: CgLayoutGridSmall, name: "CgLayoutGridSmall" },
{ icon: CgLayoutGrid, name: "CgLayoutGrid" },
{ icon: CgLayoutList, name: "CgLayoutList" },
{ icon: CgLayoutPin, name: "CgLayoutPin" },
{ icon: CgLinear, name: "CgLinear" },
{ icon: CgLink, name: "CgLink" },
{ icon: CgListTree, name: "CgListTree" },
{ icon: CgList, name: "CgList" },
{ icon: CgLivePhoto, name: "CgLivePhoto" },
{ icon: CgLoadbarAlt, name: "CgLoadbarAlt" },
{ icon: CgLoadbarDoc, name: "CgLoadbarDoc" },
{ icon: CgLoadbarSound, name: "CgLoadbarSound" },
{ icon: CgLoadbar, name: "CgLoadbar" },
{ icon: CgLockUnlock, name: "CgLockUnlock" },
{ icon: CgLock, name: "CgLock" },
{ icon: CgLogIn, name: "CgLogIn" },
{ icon: CgLogOff, name: "CgLogOff" },
{ icon: CgLogOut, name: "CgLogOut" },
{ icon: CgLoupe, name: "CgLoupe" },
{ icon: CgMagnet, name: "CgMagnet" },
{ icon: CgMailForward, name: "CgMailForward" },
{ icon: CgMailOpen, name: "CgMailOpen" },
{ icon: CgMailReply, name: "CgMailReply" },
{ icon: CgMail, name: "CgMail" },
{ icon: CgMathDivide, name: "CgMathDivide" },
{ icon: CgMathEqual, name: "CgMathEqual" },
{ icon: CgMathMinus, name: "CgMathMinus" },
{ icon: CgMathPercent, name: "CgMathPercent" },
{ icon: CgMathPlus, name: "CgMathPlus" },
{ icon: CgMaximizeAlt, name: "CgMaximizeAlt" },
{ icon: CgMaximize, name: "CgMaximize" },
{ icon: CgMaze, name: "CgMaze" },
{ icon: CgMediaLive, name: "CgMediaLive" },
{ icon: CgMediaPodcast, name: "CgMediaPodcast" },
{ icon: CgMenuBoxed, name: "CgMenuBoxed" },
{ icon: CgMenuCake, name: "CgMenuCake" },
{ icon: CgMenuCheese, name: "CgMenuCheese" },
{ icon: CgMenuGridO, name: "CgMenuGridO" },
{ icon: CgMenuGridR, name: "CgMenuGridR" },
{ icon: CgMenuHotdog, name: "CgMenuHotdog" },
{ icon: CgMenuLeftAlt, name: "CgMenuLeftAlt" },
{ icon: CgMenuLeft, name: "CgMenuLeft" },
{ icon: CgMenuMotion, name: "CgMenuMotion" },
{ icon: CgMenuOreos, name: "CgMenuOreos" },
{ icon: CgMenuRightAlt, name: "CgMenuRightAlt" },
{ icon: CgMenuRight, name: "CgMenuRight" },
{ icon: CgMenuRound, name: "CgMenuRound" },
{ icon: CgMenu, name: "CgMenu" },
{ icon: CgMergeHorizontal, name: "CgMergeHorizontal" },
{ icon: CgMergeVertical, name: "CgMergeVertical" },
{ icon: CgMic, name: "CgMic" },
{ icon: CgMicrobit, name: "CgMicrobit" },
{ icon: CgMicrosoft, name: "CgMicrosoft" },
{ icon: CgMiniPlayer, name: "CgMiniPlayer" },
{ icon: CgMinimizeAlt, name: "CgMinimizeAlt" },
{ icon: CgMinimize, name: "CgMinimize" },
{ icon: CgModem, name: "CgModem" },
{ icon: CgMonday, name: "CgMonday" },
{ icon: CgMoon, name: "CgMoon" },
{ icon: CgMoreAlt, name: "CgMoreAlt" },
{ icon: CgMoreO, name: "CgMoreO" },
{ icon: CgMoreR, name: "CgMoreR" },
{ icon: CgMoreVerticalAlt, name: "CgMoreVerticalAlt" },
{ icon: CgMoreVerticalO, name: "CgMoreVerticalO" },
{ icon: CgMoreVerticalR, name: "CgMoreVerticalR" },
{ icon: CgMoreVertical, name: "CgMoreVertical" },
{ icon: CgMore, name: "CgMore" },
{ icon: CgMouse, name: "CgMouse" },
{ icon: CgMoveDown, name: "CgMoveDown" },
{ icon: CgMoveLeft, name: "CgMoveLeft" },
{ icon: CgMoveRight, name: "CgMoveRight" },
{ icon: CgMoveTask, name: "CgMoveTask" },
{ icon: CgMoveUp, name: "CgMoveUp" },
{ icon: CgMusicNote, name: "CgMusicNote" },
{ icon: CgMusicSpeaker, name: "CgMusicSpeaker" },
{ icon: CgMusic, name: "CgMusic" },
{ icon: CgNametag, name: "CgNametag" },
{ icon: CgNotes, name: "CgNotes" },
{ icon: CgNotifications, name: "CgNotifications" },
{ icon: CgNpm, name: "CgNpm" },
{ icon: CgOculus, name: "CgOculus" },
{ icon: CgOpenCollective, name: "CgOpenCollective" },
{ icon: CgOptions, name: "CgOptions" },
{ icon: CgOrganisation, name: "CgOrganisation" },
{ icon: CgOverflow, name: "CgOverflow" },
{ icon: CgPacman, name: "CgPacman" },
{ icon: CgPassword, name: "CgPassword" },
{ icon: CgPathBack, name: "CgPathBack" },
{ icon: CgPathCrop, name: "CgPathCrop" },
{ icon: CgPathDivide, name: "CgPathDivide" },
{ icon: CgPathExclude, name: "CgPathExclude" },
{ icon: CgPathFront, name: "CgPathFront" },
{ icon: CgPathIntersect, name: "CgPathIntersect" },
{ icon: CgPathOutline, name: "CgPathOutline" },
{ icon: CgPathTrim, name: "CgPathTrim" },
{ icon: CgPathUnite, name: "CgPathUnite" },
{ icon: CgPatreon, name: "CgPatreon" },
{ icon: CgPaypal, name: "CgPaypal" },
{ icon: CgPen, name: "CgPen" },
{ icon: CgPentagonBottomLeft, name: "CgPentagonBottomLeft" },
{ icon: CgPentagonBottomRight, name: "CgPentagonBottomRight" },
{ icon: CgPentagonDown, name: "CgPentagonDown" },
{ icon: CgPentagonLeft, name: "CgPentagonLeft" },
{ icon: CgPentagonRight, name: "CgPentagonRight" },
{ icon: CgPentagonTopLeft, name: "CgPentagonTopLeft" },
{ icon: CgPentagonTopRight, name: "CgPentagonTopRight" },
{ icon: CgPentagonUp, name: "CgPentagonUp" },
{ icon: CgPerformance, name: "CgPerformance" },
{ icon: CgPexels, name: "CgPexels" },
{ icon: CgPhone, name: "CgPhone" },
{ icon: CgPhotoscan, name: "CgPhotoscan" },
{ icon: CgPiano, name: "CgPiano" },
{ icon: CgPill, name: "CgPill" },
{ icon: CgPinAlt, name: "CgPinAlt" },
{ icon: CgPinBottom, name: "CgPinBottom" },
{ icon: CgPinTop, name: "CgPinTop" },
{ icon: CgPin, name: "CgPin" },
{ icon: CgPlayBackwards, name: "CgPlayBackwards" },
{ icon: CgPlayButtonO, name: "CgPlayButtonO" },
{ icon: CgPlayButtonR, name: "CgPlayButtonR" },
{ icon: CgPlayButton, name: "CgPlayButton" },
{ icon: CgPlayForwards, name: "CgPlayForwards" },
{ icon: CgPlayListAdd, name: "CgPlayListAdd" },
{ icon: CgPlayListCheck, name: "CgPlayListCheck" },
{ icon: CgPlayListRemove, name: "CgPlayListRemove" },
{ icon: CgPlayListSearch, name: "CgPlayListSearch" },
{ icon: CgPlayList, name: "CgPlayList" },
{ icon: CgPlayPauseO, name: "CgPlayPauseO" },
{ icon: CgPlayPauseR, name: "CgPlayPauseR" },
{ icon: CgPlayPause, name: "CgPlayPause" },
{ icon: CgPlayStopO, name: "CgPlayStopO" },
{ icon: CgPlayStopR, name: "CgPlayStopR" },
{ icon: CgPlayStop, name: "CgPlayStop" },
{ icon: CgPlayTrackNextO, name: "CgPlayTrackNextO" },
{ icon: CgPlayTrackNextR, name: "CgPlayTrackNextR" },
{ icon: CgPlayTrackNext, name: "CgPlayTrackNext" },
{ icon: CgPlayTrackPrevO, name: "CgPlayTrackPrevO" },
{ icon: CgPlayTrackPrevR, name: "CgPlayTrackPrevR" },
{ icon: CgPlayTrackPrev, name: "CgPlayTrackPrev" },
{ icon: CgPlug, name: "CgPlug" },
{ icon: CgPocket, name: "CgPocket" },
{ icon: CgPokemon, name: "CgPokemon" },
{ icon: CgPolaroid, name: "CgPolaroid" },
{ icon: CgPoll, name: "CgPoll" },
{ icon: CgPresentation, name: "CgPresentation" },
{ icon: CgPrinter, name: "CgPrinter" },
{ icon: CgProductHunt, name: "CgProductHunt" },
{ icon: CgProfile, name: "CgProfile" },
{ icon: CgPullClear, name: "CgPullClear" },
{ icon: CgPushChevronDownO, name: "CgPushChevronDownO" },
{ icon: CgPushChevronDownR, name: "CgPushChevronDownR" },
{ icon: CgPushChevronDown, name: "CgPushChevronDown" },
{ icon: CgPushChevronLeftO, name: "CgPushChevronLeftO" },
{ icon: CgPushChevronLeftR, name: "CgPushChevronLeftR" },
{ icon: CgPushChevronLeft, name: "CgPushChevronLeft" },
{ icon: CgPushChevronRightO, name: "CgPushChevronRightO" },
{ icon: CgPushChevronRightR, name: "CgPushChevronRightR" },
{ icon: CgPushChevronRight, name: "CgPushChevronRight" },
{ icon: CgPushChevronUpO, name: "CgPushChevronUpO" },
{ icon: CgPushChevronUpR, name: "CgPushChevronUpR" },
{ icon: CgPushChevronUp, name: "CgPushChevronUp" },
{ icon: CgPushDown, name: "CgPushDown" },
{ icon: CgPushLeft, name: "CgPushLeft" },
{ icon: CgPushRight, name: "CgPushRight" },
{ icon: CgPushUp, name: "CgPushUp" },
{ icon: CgQr, name: "CgQr" },
{ icon: CgQuoteO, name: "CgQuoteO" },
{ icon: CgQuote, name: "CgQuote" },
{ icon: CgRadioCheck, name: "CgRadioCheck" },
{ icon: CgRadioChecked, name: "CgRadioChecked" },
{ icon: CgRatio, name: "CgRatio" },
{ icon: CgRead, name: "CgRead" },
{ icon: CgReadme, name: "CgReadme" },
{ icon: CgRecord, name: "CgRecord" },
{ icon: CgRedo, name: "CgRedo" },
{ icon: CgRemote, name: "CgRemote" },
{ icon: CgRemoveR, name: "CgRemoveR" },
{ icon: CgRemove, name: "CgRemove" },
{ icon: CgRename, name: "CgRename" },
{ icon: CgReorder, name: "CgReorder" },
{ icon: CgRepeat, name: "CgRepeat" },
{ icon: CgRing, name: "CgRing" },
{ icon: CgRowFirst, name: "CgRowFirst" },
{ icon: CgRowLast, name: "CgRowLast" },
{ icon: CgRuler, name: "CgRuler" },
{ icon: CgSandClock, name: "CgSandClock" },
{ icon: CgScan, name: "CgScan" },
{ icon: CgScreenMirror, name: "CgScreenMirror" },
{ icon: CgScreenShot, name: "CgScreenShot" },
{ icon: CgScreenWide, name: "CgScreenWide" },
{ icon: CgScreen, name: "CgScreen" },
{ icon: CgScrollH, name: "CgScrollH" },
{ icon: CgScrollV, name: "CgScrollV" },
{ icon: CgSearchFound, name: "CgSearchFound" },
{ icon: CgSearchLoading, name: "CgSearchLoading" },
{ icon: CgSearch, name: "CgSearch" },
{ icon: CgSelectO, name: "CgSelectO" },
{ icon: CgSelectR, name: "CgSelectR" },
{ icon: CgSelect, name: "CgSelect" },
{ icon: CgServer, name: "CgServer" },
{ icon: CgServerless, name: "CgServerless" },
{ icon: CgShapeCircle, name: "CgShapeCircle" },
{ icon: CgShapeHalfCircle, name: "CgShapeHalfCircle" },
{ icon: CgShapeHexagon, name: "CgShapeHexagon" },
{ icon: CgShapeRhombus, name: "CgShapeRhombus" },
{ icon: CgShapeSquare, name: "CgShapeSquare" },
{ icon: CgShapeTriangle, name: "CgShapeTriangle" },
{ icon: CgShapeZigzag, name: "CgShapeZigzag" },
{ icon: CgShare, name: "CgShare" },
{ icon: CgShield, name: "CgShield" },
{ icon: CgShoppingBag, name: "CgShoppingBag" },
{ icon: CgShoppingCart, name: "CgShoppingCart" },
{ icon: CgShortcut, name: "CgShortcut" },
{ icon: CgShutterstock, name: "CgShutterstock" },
{ icon: CgSidebarOpen, name: "CgSidebarOpen" },
{ icon: CgSidebarRight, name: "CgSidebarRight" },
{ icon: CgSidebar, name: "CgSidebar" },
{ icon: CgSignal, name: "CgSignal" },
{ icon: CgSize, name: "CgSize" },
{ icon: CgSketch, name: "CgSketch" },
{ icon: CgSlack, name: "CgSlack" },
{ icon: CgSleep, name: "CgSleep" },
{ icon: CgSmartHomeBoiler, name: "CgSmartHomeBoiler" },
{ icon: CgSmartHomeCooker, name: "CgSmartHomeCooker" },
{ icon: CgSmartHomeHeat, name: "CgSmartHomeHeat" },
{ icon: CgSmartHomeLight, name: "CgSmartHomeLight" },
{ icon: CgSmartHomeRefrigerator, name: "CgSmartHomeRefrigerator" },
{ icon: CgSmartHomeWashMachine, name: "CgSmartHomeWashMachine" },
{ icon: CgSmartphoneChip, name: "CgSmartphoneChip" },
{ icon: CgSmartphoneRam, name: "CgSmartphoneRam" },
{ icon: CgSmartphoneShake, name: "CgSmartphoneShake" },
{ icon: CgSmartphone, name: "CgSmartphone" },
{ icon: CgSmileMouthOpen, name: "CgSmileMouthOpen" },
{ icon: CgSmileNeutral, name: "CgSmileNeutral" },
{ icon: CgSmileNoMouth, name: "CgSmileNoMouth" },
{ icon: CgSmileNone, name: "CgSmileNone" },
{ icon: CgSmileSad, name: "CgSmileSad" },
{ icon: CgSmileUpside, name: "CgSmileUpside" },
{ icon: CgSmile, name: "CgSmile" },
{ icon: CgSoftwareDownload, name: "CgSoftwareDownload" },
{ icon: CgSoftwareUpload, name: "CgSoftwareUpload" },
{ icon: CgSortAz, name: "CgSortAz" },
{ icon: CgSortZa, name: "CgSortZa" },
{ icon: CgSpaceBetweenV, name: "CgSpaceBetweenV" },
{ icon: CgSpaceBetween, name: "CgSpaceBetween" },
{ icon: CgSpectrum, name: "CgSpectrum" },
{ icon: CgSpinnerAlt, name: "CgSpinnerAlt" },
{ icon: CgSpinnerTwoAlt, name: "CgSpinnerTwoAlt" },
{ icon: CgSpinnerTwo, name: "CgSpinnerTwo" },
{ icon: CgSpinner, name: "CgSpinner" },
{ icon: CgSquare, name: "CgSquare" },
{ icon: CgStack, name: "CgStack" },
{ icon: CgStark, name: "CgStark" },
{ icon: CgStopwatch, name: "CgStopwatch" },
{ icon: CgStories, name: "CgStories" },
{ icon: CgStudio, name: "CgStudio" },
{ icon: CgStyle, name: "CgStyle" },
{ icon: CgSun, name: "CgSun" },
{ icon: CgSupport, name: "CgSupport" },
{ icon: CgSwapVertical, name: "CgSwapVertical" },
{ icon: CgSwap, name: "CgSwap" },
{ icon: CgSweden, name: "CgSweden" },
{ icon: CgSwiss, name: "CgSwiss" },
{ icon: CgSync, name: "CgSync" },
{ icon: CgTab, name: "CgTab" },
{ icon: CgTag, name: "CgTag" },
{ icon: CgTally, name: "CgTally" },
{ icon: CgTapDouble, name: "CgTapDouble" },
{ icon: CgTapSingle, name: "CgTapSingle" },
{ icon: CgTemplate, name: "CgTemplate" },
{ icon: CgTennis, name: "CgTennis" },
{ icon: CgTerminal, name: "CgTerminal" },
{ icon: CgTerrain, name: "CgTerrain" },
{ icon: CgThermometer, name: "CgThermometer" },
{ icon: CgThermostat, name: "CgThermostat" },
{ icon: CgTikcode, name: "CgTikcode" },
{ icon: CgTime, name: "CgTime" },
{ icon: CgTimelapse, name: "CgTimelapse" },
{ icon: CgTimer, name: "CgTimer" },
{ icon: CgToday, name: "CgToday" },
{ icon: CgToggleOff, name: "CgToggleOff" },
{ icon: CgToggleOn, name: "CgToggleOn" },
{ icon: CgToggleSquareOff, name: "CgToggleSquareOff" },
{ icon: CgToggleSquare, name: "CgToggleSquare" },
{ icon: CgToolbarBottom, name: "CgToolbarBottom" },
{ icon: CgToolbarLeft, name: "CgToolbarLeft" },
{ icon: CgToolbarRight, name: "CgToolbarRight" },
{ icon: CgToolbarTop, name: "CgToolbarTop" },
{ icon: CgToolbox, name: "CgToolbox" },
{ icon: CgTouchpad, name: "CgTouchpad" },
{ icon: CgTrack, name: "CgTrack" },
{ icon: CgTranscript, name: "CgTranscript" },
{ icon: CgTrashEmpty, name: "CgTrashEmpty" },
{ icon: CgTrash, name: "CgTrash" },
{ icon: CgTree, name: "CgTree" },
{ icon: CgTrees, name: "CgTrees" },
{ icon: CgTrello, name: "CgTrello" },
{ icon: CgTrendingDown, name: "CgTrendingDown" },
{ icon: CgTrending, name: "CgTrending" },
{ icon: CgTrophy, name: "CgTrophy" },
{ icon: CgTv, name: "CgTv" },
{ icon: CgTwilio, name: "CgTwilio" },
{ icon: CgTwitter, name: "CgTwitter" },
{ icon: CgUiKit, name: "CgUiKit" },
{ icon: CgUmbrella, name: "CgUmbrella" },
{ icon: CgUnavailable, name: "CgUnavailable" },
{ icon: CgUnblock, name: "CgUnblock" },
{ icon: CgUndo, name: "CgUndo" },
{ icon: CgUnfold, name: "CgUnfold" },
{ icon: CgUnsplash, name: "CgUnsplash" },
{ icon: CgUsbC, name: "CgUsbC" },
{ icon: CgUsb, name: "CgUsb" },
{ icon: CgUserAdd, name: "CgUserAdd" },
{ icon: CgUserList, name: "CgUserList" },
{ icon: CgUserRemove, name: "CgUserRemove" },
{ icon: CgUser, name: "CgUser" },
{ icon: CgUserlane, name: "CgUserlane" },
{ icon: CgViewCols, name: "CgViewCols" },
{ icon: CgViewComfortable, name: "CgViewComfortable" },
{ icon: CgViewDay, name: "CgViewDay" },
{ icon: CgViewGrid, name: "CgViewGrid" },
{ icon: CgViewList, name: "CgViewList" },
{ icon: CgViewMonth, name: "CgViewMonth" },
{ icon: CgViewSplit, name: "CgViewSplit" },
{ icon: CgVinyl, name: "CgVinyl" },
{ icon: CgVoicemailO, name: "CgVoicemailO" },
{ icon: CgVoicemailR, name: "CgVoicemailR" },
{ icon: CgVoicemail, name: "CgVoicemail" },
{ icon: CgVolume, name: "CgVolume" },
{ icon: CgWebcam, name: "CgWebcam" },
{ icon: CgWebsite, name: "CgWebsite" },
{ icon: CgWindows, name: "CgWindows" },
{ icon: CgWorkAlt, name: "CgWorkAlt" },
{ icon: CgYinyang, name: "CgYinyang" },
{ icon: CgYoutube, name: "CgYoutube" },
{ icon: CgZeit, name: "CgZeit" },
{ icon: CgZoomIn, name: "CgZoomIn" },
{ icon: CgZoomOut, name: "CgZoomOut" },
];

export default result