import {
	DiAndroid,
	DiAngularSimple,
	DiAppcelerator,
	DiApple,
	DiAppstore,
	DiAptana,
	DiAsterisk,
	DiAtlassian,
	DiAtom,
	DiAws,
	DiBackbone,
	DiBingSmall,
	DiBintray,
	DiBitbucket,
	DiBlackberry,
	DiBootstrap,
	DiBower,
	DiBrackets,
	DiBugsense,
	DiCelluloid,
	DiChrome,
	DiCisco,
	DiClojureAlt,
	DiClojure,
	DiCloud9,
	DiCoda,
	DiCodeBadge,
	DiCode,
	DiCodeigniter,
	DiCodepen,
	DiCodrops,
	DiCoffeescript,
	DiCompass,
	DiComposer,
	DiCreativecommonsBadge,
	DiCreativecommons,
	DiCssTricks,
	DiCss3Full,
	DiCss3,
	DiCssdeck,
	DiDart,
	DiDatabase,
	DiDebian,
	DiDigitalOcean,
	DiDjango,
	DiDlang,
	DiDocker,
	DiDoctrine,
	DiDojo,
	DiDotnet,
	DiDreamweaver,
	DiDropbox,
	DiDrupal,
	DiEclipse,
	DiEmber,
	DiEnvato,
	DiErlang,
	DiExtjs,
	DiFirebase,
	DiFirefox,
	DiFsharp,
	DiGhostSmall,
	DiGhost,
	DiGitBranch,
	DiGitCommit,
	DiGitCompare,
	DiGitMerge,
	DiGitPullRequest,
	DiGit,
	DiGithubAlt,
	DiGithubBadge,
	DiGithubFull,
	DiGithub,
	DiGnu,
	DiGo,
	DiGoogleAnalytics,
	DiGoogleDrive,
	DiGoogleCloudPlatform,
	DiGrails,
	DiGroovy,
	DiGrunt,
	DiGulp,
	DiHackernews,
	DiHaskell,
	DiHeroku,
	DiHtml53DEffects,
	DiHtml5Connectivity,
	DiHtml5DeviceAccess,
	DiHtml5Multimedia,
	DiHtml5,
	DiIe,
	DiIllustrator,
	DiIntellij,
	DiIonic,
	DiJava,
	DiJavascript1,
	DiJavascript,
	DiJekyllSmall,
	DiJenkins,
	DiJira,
	DiJoomla,
	DiJqueryLogo,
	DiJqueryUiLogo,
	DiJsBadge,
	DiKomodo,
	DiKrakenjsBadge,
	DiKrakenjs,
	DiLaravel,
	DiLess,
	DiLinux,
	DiMagento,
	DiMailchimp,
	DiMarkdown,
	DiMaterializecss,
	DiMeteor,
	DiMeteorfull,
	DiMitlicence,
	DiModernizr,
	DiMongodb,
	DiMootoolsBadge,
	DiMootools,
	DiMozilla,
	DiMsqlServer,
	DiMysql,
	DiNancy,
	DiNetbeans,
	DiNetmagazine,
	DiNginx,
	DiNodejsSmall,
	DiNodejs,
	DiNpm,
	DiOnedrive,
	DiOpenshift,
	DiOpensource,
	DiOpera,
	DiPerl,
	DiPhonegap,
	DiPhotoshop,
	DiPhp,
	DiPostgresql,
	DiProlog,
	DiPython,
	DiRackspace,
	DiRaphael,
	DiRasberryPi,
	DiReact,
	DiRedhat,
	DiRedis,
	DiRequirejs,
	DiResponsive,
	DiRor,
	DiRubyRough,
	DiRuby,
	DiRust,
	DiSafari,
	DiSass,
	DiScala,
	DiScriptcs,
	DiScrum,
	DiSenchatouch,
	DiSizzlejs,
	DiSmashingMagazine,
	DiSnapSvg,
	DiSpark,
	DiSqllite,
	DiStackoverflow,
	DiStreamline,
	DiStylus,
	DiSublime,
	DiSwift,
	DiSymfonyBadge,
	DiSymfony,
	DiTechcrunch,
	DiTerminalBadge,
	DiTerminal,
	DiTravis,
	DiTrello,
	DiTypo3,
	DiUbuntu,
	DiUikit,
	DiUnitySmall,
	DiVim,
	DiVisualstudio,
	DiW3C,
	DiWebplatform,
	DiWindows,
	DiWordpress,
	DiYahooSmall,
	DiYahoo,
	DiYeoman,
	DiYii,
	DiZend,
} from "react-icons/di";

const result = [
	{ icon: DiAndroid, name: "DiAndroid", library: "di" },
	{ icon: DiAngularSimple, name: "DiAngularSimple", library: "di" },
	{ icon: DiAppcelerator, name: "DiAppcelerator", library: "di" },
	{ icon: DiApple, name: "DiApple", library: "di" },
	{ icon: DiAppstore, name: "DiAppstore", library: "di" },
	{ icon: DiAptana, name: "DiAptana", library: "di" },
	{ icon: DiAsterisk, name: "DiAsterisk", library: "di" },
	{ icon: DiAtlassian, name: "DiAtlassian", library: "di" },
	{ icon: DiAtom, name: "DiAtom", library: "di" },
	{ icon: DiAws, name: "DiAws", library: "di" },
	{ icon: DiBackbone, name: "DiBackbone", library: "di" },
	{ icon: DiBingSmall, name: "DiBingSmall", library: "di" },
	{ icon: DiBintray, name: "DiBintray", library: "di" },
	{ icon: DiBitbucket, name: "DiBitbucket", library: "di" },
	{ icon: DiBlackberry, name: "DiBlackberry", library: "di" },
	{ icon: DiBootstrap, name: "DiBootstrap", library: "di" },
	{ icon: DiBower, name: "DiBower", library: "di" },
	{ icon: DiBrackets, name: "DiBrackets", library: "di" },
	{ icon: DiBugsense, name: "DiBugsense", library: "di" },
	{ icon: DiCelluloid, name: "DiCelluloid", library: "di" },
	{ icon: DiChrome, name: "DiChrome", library: "di" },
	{ icon: DiCisco, name: "DiCisco", library: "di" },
	{ icon: DiClojureAlt, name: "DiClojureAlt", library: "di" },
	{ icon: DiClojure, name: "DiClojure", library: "di" },
	{ icon: DiCloud9, name: "DiCloud9", library: "di" },
	{ icon: DiCoda, name: "DiCoda", library: "di" },
	{ icon: DiCodeBadge, name: "DiCodeBadge", library: "di" },
	{ icon: DiCode, name: "DiCode", library: "di" },
	{ icon: DiCodeigniter, name: "DiCodeigniter", library: "di" },
	{ icon: DiCodepen, name: "DiCodepen", library: "di" },
	{ icon: DiCodrops, name: "DiCodrops", library: "di" },
	{ icon: DiCoffeescript, name: "DiCoffeescript", library: "di" },
	{ icon: DiCompass, name: "DiCompass", library: "di" },
	{ icon: DiComposer, name: "DiComposer", library: "di" },
	{ icon: DiCreativecommonsBadge, name: "DiCreativecommonsBadge", library: "di" },
	{ icon: DiCreativecommons, name: "DiCreativecommons", library: "di" },
	{ icon: DiCssTricks, name: "DiCssTricks", library: "di" },
	{ icon: DiCss3Full, name: "DiCss3Full", library: "di" },
	{ icon: DiCss3, name: "DiCss3", library: "di" },
	{ icon: DiCssdeck, name: "DiCssdeck", library: "di" },
	{ icon: DiDart, name: "DiDart", library: "di" },
	{ icon: DiDatabase, name: "DiDatabase", library: "di" },
	{ icon: DiDebian, name: "DiDebian", library: "di" },
	{ icon: DiDigitalOcean, name: "DiDigitalOcean", library: "di" },
	{ icon: DiDjango, name: "DiDjango", library: "di" },
	{ icon: DiDlang, name: "DiDlang", library: "di" },
	{ icon: DiDocker, name: "DiDocker", library: "di" },
	{ icon: DiDoctrine, name: "DiDoctrine", library: "di" },
	{ icon: DiDojo, name: "DiDojo", library: "di" },
	{ icon: DiDotnet, name: "DiDotnet", library: "di" },
	{ icon: DiDreamweaver, name: "DiDreamweaver", library: "di" },
	{ icon: DiDropbox, name: "DiDropbox", library: "di" },
	{ icon: DiDrupal, name: "DiDrupal", library: "di" },
	{ icon: DiEclipse, name: "DiEclipse", library: "di" },
	{ icon: DiEmber, name: "DiEmber", library: "di" },
	{ icon: DiEnvato, name: "DiEnvato", library: "di" },
	{ icon: DiErlang, name: "DiErlang", library: "di" },
	{ icon: DiExtjs, name: "DiExtjs", library: "di" },
	{ icon: DiFirebase, name: "DiFirebase", library: "di" },
	{ icon: DiFirefox, name: "DiFirefox", library: "di" },
	{ icon: DiFsharp, name: "DiFsharp", library: "di" },
	{ icon: DiGhostSmall, name: "DiGhostSmall", library: "di" },
	{ icon: DiGhost, name: "DiGhost", library: "di" },
	{ icon: DiGitBranch, name: "DiGitBranch", library: "di" },
	{ icon: DiGitCommit, name: "DiGitCommit", library: "di" },
	{ icon: DiGitCompare, name: "DiGitCompare", library: "di" },
	{ icon: DiGitMerge, name: "DiGitMerge", library: "di" },
	{ icon: DiGitPullRequest, name: "DiGitPullRequest", library: "di" },
	{ icon: DiGit, name: "DiGit", library: "di" },
	{ icon: DiGithubAlt, name: "DiGithubAlt", library: "di" },
	{ icon: DiGithubBadge, name: "DiGithubBadge", library: "di" },
	{ icon: DiGithubFull, name: "DiGithubFull", library: "di" },
	{ icon: DiGithub, name: "DiGithub", library: "di" },
	{ icon: DiGnu, name: "DiGnu", library: "di" },
	{ icon: DiGo, name: "DiGo", library: "di" },
	{ icon: DiGoogleAnalytics, name: "DiGoogleAnalytics", library: "di" },
	{ icon: DiGoogleDrive, name: "DiGoogleDrive", library: "di" },
	{ icon: DiGoogleCloudPlatform, name: "DiGoogleCloudPlatform", library: "di" },
	{ icon: DiGrails, name: "DiGrails", library: "di" },
	{ icon: DiGroovy, name: "DiGroovy", library: "di" },
	{ icon: DiGrunt, name: "DiGrunt", library: "di" },
	{ icon: DiGulp, name: "DiGulp", library: "di" },
	{ icon: DiHackernews, name: "DiHackernews", library: "di" },
	{ icon: DiHaskell, name: "DiHaskell", library: "di" },
	{ icon: DiHeroku, name: "DiHeroku", library: "di" },
	{ icon: DiHtml53DEffects, name: "DiHtml53DEffects", library: "di" },
	{ icon: DiHtml5Connectivity, name: "DiHtml5Connectivity", library: "di" },
	{ icon: DiHtml5DeviceAccess, name: "DiHtml5DeviceAccess", library: "di" },
	{ icon: DiHtml5Multimedia, name: "DiHtml5Multimedia", library: "di" },
	{ icon: DiHtml5, name: "DiHtml5", library: "di" },
	{ icon: DiIe, name: "DiIe", library: "di" },
	{ icon: DiIllustrator, name: "DiIllustrator", library: "di" },
	{ icon: DiIntellij, name: "DiIntellij", library: "di" },
	{ icon: DiIonic, name: "DiIonic", library: "di" },
	{ icon: DiJava, name: "DiJava", library: "di" },
	{ icon: DiJavascript1, name: "DiJavascript1", library: "di" },
	{ icon: DiJavascript, name: "DiJavascript", library: "di" },
	{ icon: DiJekyllSmall, name: "DiJekyllSmall", library: "di" },
	{ icon: DiJenkins, name: "DiJenkins", library: "di" },
	{ icon: DiJira, name: "DiJira", library: "di" },
	{ icon: DiJoomla, name: "DiJoomla", library: "di" },
	{ icon: DiJqueryLogo, name: "DiJqueryLogo", library: "di" },
	{ icon: DiJqueryUiLogo, name: "DiJqueryUiLogo", library: "di" },
	{ icon: DiJsBadge, name: "DiJsBadge", library: "di" },
	{ icon: DiKomodo, name: "DiKomodo", library: "di" },
	{ icon: DiKrakenjsBadge, name: "DiKrakenjsBadge", library: "di" },
	{ icon: DiKrakenjs, name: "DiKrakenjs", library: "di" },
	{ icon: DiLaravel, name: "DiLaravel", library: "di" },
	{ icon: DiLess, name: "DiLess", library: "di" },
	{ icon: DiLinux, name: "DiLinux", library: "di" },
	{ icon: DiMagento, name: "DiMagento", library: "di" },
	{ icon: DiMailchimp, name: "DiMailchimp", library: "di" },
	{ icon: DiMarkdown, name: "DiMarkdown", library: "di" },
	{ icon: DiMaterializecss, name: "DiMaterializecss", library: "di" },
	{ icon: DiMeteor, name: "DiMeteor", library: "di" },
	{ icon: DiMeteorfull, name: "DiMeteorfull", library: "di" },
	{ icon: DiMitlicence, name: "DiMitlicence", library: "di" },
	{ icon: DiModernizr, name: "DiModernizr", library: "di" },
	{ icon: DiMongodb, name: "DiMongodb", library: "di" },
	{ icon: DiMootoolsBadge, name: "DiMootoolsBadge", library: "di" },
	{ icon: DiMootools, name: "DiMootools", library: "di" },
	{ icon: DiMozilla, name: "DiMozilla", library: "di" },
	{ icon: DiMsqlServer, name: "DiMsqlServer", library: "di" },
	{ icon: DiMysql, name: "DiMysql", library: "di" },
	{ icon: DiNancy, name: "DiNancy", library: "di" },
	{ icon: DiNetbeans, name: "DiNetbeans", library: "di" },
	{ icon: DiNetmagazine, name: "DiNetmagazine", library: "di" },
	{ icon: DiNginx, name: "DiNginx", library: "di" },
	{ icon: DiNodejsSmall, name: "DiNodejsSmall", library: "di" },
	{ icon: DiNodejs, name: "DiNodejs", library: "di" },
	{ icon: DiNpm, name: "DiNpm", library: "di" },
	{ icon: DiOnedrive, name: "DiOnedrive", library: "di" },
	{ icon: DiOpenshift, name: "DiOpenshift", library: "di" },
	{ icon: DiOpensource, name: "DiOpensource", library: "di" },
	{ icon: DiOpera, name: "DiOpera", library: "di" },
	{ icon: DiPerl, name: "DiPerl", library: "di" },
	{ icon: DiPhonegap, name: "DiPhonegap", library: "di" },
	{ icon: DiPhotoshop, name: "DiPhotoshop", library: "di" },
	{ icon: DiPhp, name: "DiPhp", library: "di" },
	{ icon: DiPostgresql, name: "DiPostgresql", library: "di" },
	{ icon: DiProlog, name: "DiProlog", library: "di" },
	{ icon: DiPython, name: "DiPython", library: "di" },
	{ icon: DiRackspace, name: "DiRackspace", library: "di" },
	{ icon: DiRaphael, name: "DiRaphael", library: "di" },
	{ icon: DiRasberryPi, name: "DiRasberryPi", library: "di" },
	{ icon: DiReact, name: "DiReact", library: "di" },
	{ icon: DiRedhat, name: "DiRedhat", library: "di" },
	{ icon: DiRedis, name: "DiRedis", library: "di" },
	{ icon: DiRequirejs, name: "DiRequirejs", library: "di" },
	{ icon: DiResponsive, name: "DiResponsive", library: "di" },
	{ icon: DiRor, name: "DiRor", library: "di" },
	{ icon: DiRubyRough, name: "DiRubyRough", library: "di" },
	{ icon: DiRuby, name: "DiRuby", library: "di" },
	{ icon: DiRust, name: "DiRust", library: "di" },
	{ icon: DiSafari, name: "DiSafari", library: "di" },
	{ icon: DiSass, name: "DiSass", library: "di" },
	{ icon: DiScala, name: "DiScala", library: "di" },
	{ icon: DiScriptcs, name: "DiScriptcs", library: "di" },
	{ icon: DiScrum, name: "DiScrum", library: "di" },
	{ icon: DiSenchatouch, name: "DiSenchatouch", library: "di" },
	{ icon: DiSizzlejs, name: "DiSizzlejs", library: "di" },
	{ icon: DiSmashingMagazine, name: "DiSmashingMagazine", library: "di" },
	{ icon: DiSnapSvg, name: "DiSnapSvg", library: "di" },
	{ icon: DiSpark, name: "DiSpark", library: "di" },
	{ icon: DiSqllite, name: "DiSqllite", library: "di" },
	{ icon: DiStackoverflow, name: "DiStackoverflow", library: "di" },
	{ icon: DiStreamline, name: "DiStreamline", library: "di" },
	{ icon: DiStylus, name: "DiStylus", library: "di" },
	{ icon: DiSublime, name: "DiSublime", library: "di" },
	{ icon: DiSwift, name: "DiSwift", library: "di" },
	{ icon: DiSymfonyBadge, name: "DiSymfonyBadge", library: "di" },
	{ icon: DiSymfony, name: "DiSymfony", library: "di" },
	{ icon: DiTechcrunch, name: "DiTechcrunch", library: "di" },
	{ icon: DiTerminalBadge, name: "DiTerminalBadge", library: "di" },
	{ icon: DiTerminal, name: "DiTerminal", library: "di" },
	{ icon: DiTravis, name: "DiTravis", library: "di" },
	{ icon: DiTrello, name: "DiTrello", library: "di" },
	{ icon: DiTypo3, name: "DiTypo3", library: "di" },
	{ icon: DiUbuntu, name: "DiUbuntu", library: "di" },
	{ icon: DiUikit, name: "DiUikit", library: "di" },
	{ icon: DiUnitySmall, name: "DiUnitySmall", library: "di" },
	{ icon: DiVim, name: "DiVim", library: "di" },
	{ icon: DiVisualstudio, name: "DiVisualstudio", library: "di" },
	{ icon: DiW3C, name: "DiW3C", library: "di" },
	{ icon: DiWebplatform, name: "DiWebplatform", library: "di" },
	{ icon: DiWindows, name: "DiWindows", library: "di" },
	{ icon: DiWordpress, name: "DiWordpress", library: "di" },
	{ icon: DiYahooSmall, name: "DiYahooSmall", library: "di" },
	{ icon: DiYahoo, name: "DiYahoo", library: "di" },
	{ icon: DiYeoman, name: "DiYeoman", library: "di" },
	{ icon: DiYii, name: "DiYii", library: "di" },
	{ icon: DiZend, name: "DiZend", library: "di" },
];

export default result;
