import {
DiAndroid,
DiAngularSimple,
DiAppcelerator,
DiApple,
DiAppstore,
DiAptana,
DiAsterisk,
DiAtlassian,
DiAtom,
DiAws,
DiBackbone,
DiBingSmall,
DiBintray,
DiBitbucket,
DiBlackberry,
DiBootstrap,
DiBower,
DiBrackets,
DiBugsense,
DiCelluloid,
DiChrome,
DiCisco,
DiClojureAlt,
DiClojure,
DiCloud9,
DiCoda,
DiCodeBadge,
DiCode,
DiCodeigniter,
DiCodepen,
DiCodrops,
DiCoffeescript,
DiCompass,
DiComposer,
DiCreativecommonsBadge,
DiCreativecommons,
DiCssTricks,
DiCss3Full,
DiCss3,
DiCssdeck,
DiDart,
DiDatabase,
DiDebian,
DiDigitalOcean,
DiDjango,
DiDlang,
DiDocker,
DiDoctrine,
DiDojo,
DiDotnet,
DiDreamweaver,
DiDropbox,
DiDrupal,
DiEclipse,
DiEmber,
DiEnvato,
DiErlang,
DiExtjs,
DiFirebase,
DiFirefox,
DiFsharp,
DiGhostSmall,
DiGhost,
DiGitBranch,
DiGitCommit,
DiGitCompare,
DiGitMerge,
DiGitPullRequest,
DiGit,
DiGithubAlt,
DiGithubBadge,
DiGithubFull,
DiGithub,
DiGnu,
DiGo,
DiGoogleAnalytics,
DiGoogleDrive,
DiGoogleCloudPlatform,
DiGrails,
DiGroovy,
DiGrunt,
DiGulp,
DiHackernews,
DiHaskell,
DiHeroku,
DiHtml53DEffects,
DiHtml5Connectivity,
DiHtml5DeviceAccess,
DiHtml5Multimedia,
DiHtml5,
DiIe,
DiIllustrator,
DiIntellij,
DiIonic,
DiJava,
DiJavascript1,
DiJavascript,
DiJekyllSmall,
DiJenkins,
DiJira,
DiJoomla,
DiJqueryLogo,
DiJqueryUiLogo,
DiJsBadge,
DiKomodo,
DiKrakenjsBadge,
DiKrakenjs,
DiLaravel,
DiLess,
DiLinux,
DiMagento,
DiMailchimp,
DiMarkdown,
DiMaterializecss,
DiMeteor,
DiMeteorfull,
DiMitlicence,
DiModernizr,
DiMongodb,
DiMootoolsBadge,
DiMootools,
DiMozilla,
DiMsqlServer,
DiMysql,
DiNancy,
DiNetbeans,
DiNetmagazine,
DiNginx,
DiNodejsSmall,
DiNodejs,
DiNpm,
DiOnedrive,
DiOpenshift,
DiOpensource,
DiOpera,
DiPerl,
DiPhonegap,
DiPhotoshop,
DiPhp,
DiPostgresql,
DiProlog,
DiPython,
DiRackspace,
DiRaphael,
DiRasberryPi,
DiReact,
DiRedhat,
DiRedis,
DiRequirejs,
DiResponsive,
DiRor,
DiRubyRough,
DiRuby,
DiRust,
DiSafari,
DiSass,
DiScala,
DiScriptcs,
DiScrum,
DiSenchatouch,
DiSizzlejs,
DiSmashingMagazine,
DiSnapSvg,
DiSpark,
DiSqllite,
DiStackoverflow,
DiStreamline,
DiStylus,
DiSublime,
DiSwift,
DiSymfonyBadge,
DiSymfony,
DiTechcrunch,
DiTerminalBadge,
DiTerminal,
DiTravis,
DiTrello,
DiTypo3,
DiUbuntu,
DiUikit,
DiUnitySmall,
DiVim,
DiVisualstudio,
DiW3C,
DiWebplatform,
DiWindows,
DiWordpress,
DiYahooSmall,
DiYahoo,
DiYeoman,
DiYii,
DiZend,
} from "react-icons/di";

const result = [
{ icon: DiAndroid, name: "DiAndroid" },
{ icon: DiAngularSimple, name: "DiAngularSimple" },
{ icon: DiAppcelerator, name: "DiAppcelerator" },
{ icon: DiApple, name: "DiApple" },
{ icon: DiAppstore, name: "DiAppstore" },
{ icon: DiAptana, name: "DiAptana" },
{ icon: DiAsterisk, name: "DiAsterisk" },
{ icon: DiAtlassian, name: "DiAtlassian" },
{ icon: DiAtom, name: "DiAtom" },
{ icon: DiAws, name: "DiAws" },
{ icon: DiBackbone, name: "DiBackbone" },
{ icon: DiBingSmall, name: "DiBingSmall" },
{ icon: DiBintray, name: "DiBintray" },
{ icon: DiBitbucket, name: "DiBitbucket" },
{ icon: DiBlackberry, name: "DiBlackberry" },
{ icon: DiBootstrap, name: "DiBootstrap" },
{ icon: DiBower, name: "DiBower" },
{ icon: DiBrackets, name: "DiBrackets" },
{ icon: DiBugsense, name: "DiBugsense" },
{ icon: DiCelluloid, name: "DiCelluloid" },
{ icon: DiChrome, name: "DiChrome" },
{ icon: DiCisco, name: "DiCisco" },
{ icon: DiClojureAlt, name: "DiClojureAlt" },
{ icon: DiClojure, name: "DiClojure" },
{ icon: DiCloud9, name: "DiCloud9" },
{ icon: DiCoda, name: "DiCoda" },
{ icon: DiCodeBadge, name: "DiCodeBadge" },
{ icon: DiCode, name: "DiCode" },
{ icon: DiCodeigniter, name: "DiCodeigniter" },
{ icon: DiCodepen, name: "DiCodepen" },
{ icon: DiCodrops, name: "DiCodrops" },
{ icon: DiCoffeescript, name: "DiCoffeescript" },
{ icon: DiCompass, name: "DiCompass" },
{ icon: DiComposer, name: "DiComposer" },
{ icon: DiCreativecommonsBadge, name: "DiCreativecommonsBadge" },
{ icon: DiCreativecommons, name: "DiCreativecommons" },
{ icon: DiCssTricks, name: "DiCssTricks" },
{ icon: DiCss3Full, name: "DiCss3Full" },
{ icon: DiCss3, name: "DiCss3" },
{ icon: DiCssdeck, name: "DiCssdeck" },
{ icon: DiDart, name: "DiDart" },
{ icon: DiDatabase, name: "DiDatabase" },
{ icon: DiDebian, name: "DiDebian" },
{ icon: DiDigitalOcean, name: "DiDigitalOcean" },
{ icon: DiDjango, name: "DiDjango" },
{ icon: DiDlang, name: "DiDlang" },
{ icon: DiDocker, name: "DiDocker" },
{ icon: DiDoctrine, name: "DiDoctrine" },
{ icon: DiDojo, name: "DiDojo" },
{ icon: DiDotnet, name: "DiDotnet" },
{ icon: DiDreamweaver, name: "DiDreamweaver" },
{ icon: DiDropbox, name: "DiDropbox" },
{ icon: DiDrupal, name: "DiDrupal" },
{ icon: DiEclipse, name: "DiEclipse" },
{ icon: DiEmber, name: "DiEmber" },
{ icon: DiEnvato, name: "DiEnvato" },
{ icon: DiErlang, name: "DiErlang" },
{ icon: DiExtjs, name: "DiExtjs" },
{ icon: DiFirebase, name: "DiFirebase" },
{ icon: DiFirefox, name: "DiFirefox" },
{ icon: DiFsharp, name: "DiFsharp" },
{ icon: DiGhostSmall, name: "DiGhostSmall" },
{ icon: DiGhost, name: "DiGhost" },
{ icon: DiGitBranch, name: "DiGitBranch" },
{ icon: DiGitCommit, name: "DiGitCommit" },
{ icon: DiGitCompare, name: "DiGitCompare" },
{ icon: DiGitMerge, name: "DiGitMerge" },
{ icon: DiGitPullRequest, name: "DiGitPullRequest" },
{ icon: DiGit, name: "DiGit" },
{ icon: DiGithubAlt, name: "DiGithubAlt" },
{ icon: DiGithubBadge, name: "DiGithubBadge" },
{ icon: DiGithubFull, name: "DiGithubFull" },
{ icon: DiGithub, name: "DiGithub" },
{ icon: DiGnu, name: "DiGnu" },
{ icon: DiGo, name: "DiGo" },
{ icon: DiGoogleAnalytics, name: "DiGoogleAnalytics" },
{ icon: DiGoogleDrive, name: "DiGoogleDrive" },
{ icon: DiGoogleCloudPlatform, name: "DiGoogleCloudPlatform" },
{ icon: DiGrails, name: "DiGrails" },
{ icon: DiGroovy, name: "DiGroovy" },
{ icon: DiGrunt, name: "DiGrunt" },
{ icon: DiGulp, name: "DiGulp" },
{ icon: DiHackernews, name: "DiHackernews" },
{ icon: DiHaskell, name: "DiHaskell" },
{ icon: DiHeroku, name: "DiHeroku" },
{ icon: DiHtml53DEffects, name: "DiHtml53DEffects" },
{ icon: DiHtml5Connectivity, name: "DiHtml5Connectivity" },
{ icon: DiHtml5DeviceAccess, name: "DiHtml5DeviceAccess" },
{ icon: DiHtml5Multimedia, name: "DiHtml5Multimedia" },
{ icon: DiHtml5, name: "DiHtml5" },
{ icon: DiIe, name: "DiIe" },
{ icon: DiIllustrator, name: "DiIllustrator" },
{ icon: DiIntellij, name: "DiIntellij" },
{ icon: DiIonic, name: "DiIonic" },
{ icon: DiJava, name: "DiJava" },
{ icon: DiJavascript1, name: "DiJavascript1" },
{ icon: DiJavascript, name: "DiJavascript" },
{ icon: DiJekyllSmall, name: "DiJekyllSmall" },
{ icon: DiJenkins, name: "DiJenkins" },
{ icon: DiJira, name: "DiJira" },
{ icon: DiJoomla, name: "DiJoomla" },
{ icon: DiJqueryLogo, name: "DiJqueryLogo" },
{ icon: DiJqueryUiLogo, name: "DiJqueryUiLogo" },
{ icon: DiJsBadge, name: "DiJsBadge" },
{ icon: DiKomodo, name: "DiKomodo" },
{ icon: DiKrakenjsBadge, name: "DiKrakenjsBadge" },
{ icon: DiKrakenjs, name: "DiKrakenjs" },
{ icon: DiLaravel, name: "DiLaravel" },
{ icon: DiLess, name: "DiLess" },
{ icon: DiLinux, name: "DiLinux" },
{ icon: DiMagento, name: "DiMagento" },
{ icon: DiMailchimp, name: "DiMailchimp" },
{ icon: DiMarkdown, name: "DiMarkdown" },
{ icon: DiMaterializecss, name: "DiMaterializecss" },
{ icon: DiMeteor, name: "DiMeteor" },
{ icon: DiMeteorfull, name: "DiMeteorfull" },
{ icon: DiMitlicence, name: "DiMitlicence" },
{ icon: DiModernizr, name: "DiModernizr" },
{ icon: DiMongodb, name: "DiMongodb" },
{ icon: DiMootoolsBadge, name: "DiMootoolsBadge" },
{ icon: DiMootools, name: "DiMootools" },
{ icon: DiMozilla, name: "DiMozilla" },
{ icon: DiMsqlServer, name: "DiMsqlServer" },
{ icon: DiMysql, name: "DiMysql" },
{ icon: DiNancy, name: "DiNancy" },
{ icon: DiNetbeans, name: "DiNetbeans" },
{ icon: DiNetmagazine, name: "DiNetmagazine" },
{ icon: DiNginx, name: "DiNginx" },
{ icon: DiNodejsSmall, name: "DiNodejsSmall" },
{ icon: DiNodejs, name: "DiNodejs" },
{ icon: DiNpm, name: "DiNpm" },
{ icon: DiOnedrive, name: "DiOnedrive" },
{ icon: DiOpenshift, name: "DiOpenshift" },
{ icon: DiOpensource, name: "DiOpensource" },
{ icon: DiOpera, name: "DiOpera" },
{ icon: DiPerl, name: "DiPerl" },
{ icon: DiPhonegap, name: "DiPhonegap" },
{ icon: DiPhotoshop, name: "DiPhotoshop" },
{ icon: DiPhp, name: "DiPhp" },
{ icon: DiPostgresql, name: "DiPostgresql" },
{ icon: DiProlog, name: "DiProlog" },
{ icon: DiPython, name: "DiPython" },
{ icon: DiRackspace, name: "DiRackspace" },
{ icon: DiRaphael, name: "DiRaphael" },
{ icon: DiRasberryPi, name: "DiRasberryPi" },
{ icon: DiReact, name: "DiReact" },
{ icon: DiRedhat, name: "DiRedhat" },
{ icon: DiRedis, name: "DiRedis" },
{ icon: DiRequirejs, name: "DiRequirejs" },
{ icon: DiResponsive, name: "DiResponsive" },
{ icon: DiRor, name: "DiRor" },
{ icon: DiRubyRough, name: "DiRubyRough" },
{ icon: DiRuby, name: "DiRuby" },
{ icon: DiRust, name: "DiRust" },
{ icon: DiSafari, name: "DiSafari" },
{ icon: DiSass, name: "DiSass" },
{ icon: DiScala, name: "DiScala" },
{ icon: DiScriptcs, name: "DiScriptcs" },
{ icon: DiScrum, name: "DiScrum" },
{ icon: DiSenchatouch, name: "DiSenchatouch" },
{ icon: DiSizzlejs, name: "DiSizzlejs" },
{ icon: DiSmashingMagazine, name: "DiSmashingMagazine" },
{ icon: DiSnapSvg, name: "DiSnapSvg" },
{ icon: DiSpark, name: "DiSpark" },
{ icon: DiSqllite, name: "DiSqllite" },
{ icon: DiStackoverflow, name: "DiStackoverflow" },
{ icon: DiStreamline, name: "DiStreamline" },
{ icon: DiStylus, name: "DiStylus" },
{ icon: DiSublime, name: "DiSublime" },
{ icon: DiSwift, name: "DiSwift" },
{ icon: DiSymfonyBadge, name: "DiSymfonyBadge" },
{ icon: DiSymfony, name: "DiSymfony" },
{ icon: DiTechcrunch, name: "DiTechcrunch" },
{ icon: DiTerminalBadge, name: "DiTerminalBadge" },
{ icon: DiTerminal, name: "DiTerminal" },
{ icon: DiTravis, name: "DiTravis" },
{ icon: DiTrello, name: "DiTrello" },
{ icon: DiTypo3, name: "DiTypo3" },
{ icon: DiUbuntu, name: "DiUbuntu" },
{ icon: DiUikit, name: "DiUikit" },
{ icon: DiUnitySmall, name: "DiUnitySmall" },
{ icon: DiVim, name: "DiVim" },
{ icon: DiVisualstudio, name: "DiVisualstudio" },
{ icon: DiW3C, name: "DiW3C" },
{ icon: DiWebplatform, name: "DiWebplatform" },
{ icon: DiWindows, name: "DiWindows" },
{ icon: DiWordpress, name: "DiWordpress" },
{ icon: DiYahooSmall, name: "DiYahooSmall" },
{ icon: DiYahoo, name: "DiYahoo" },
{ icon: DiYeoman, name: "DiYeoman" },
{ icon: DiYii, name: "DiYii" },
{ icon: DiZend, name: "DiZend" },
];

export default result