import {
TiAdjustBrightness,
TiAdjustContrast,
TiAnchorOutline,
TiAnchor,
TiArchive,
TiArrowBackOutline,
TiArrowBack,
TiArrowDownOutline,
TiArrowDownThick,
TiArrowDown,
TiArrowForwardOutline,
TiArrowForward,
TiArrowLeftOutline,
TiArrowLeftThick,
TiArrowLeft,
TiArrowLoopOutline,
TiArrowLoop,
TiArrowMaximiseOutline,
TiArrowMaximise,
TiArrowMinimiseOutline,
TiArrowMinimise,
TiArrowMoveOutline,
TiArrowMove,
TiArrowRepeatOutline,
TiArrowRepeat,
TiArrowRightOutline,
TiArrowRightThick,
TiArrowRight,
TiArrowShuffle,
TiArrowSortedDown,
TiArrowSortedUp,
TiArrowSyncOutline,
TiArrowSync,
TiArrowUnsorted,
TiArrowUpOutline,
TiArrowUpThick,
TiArrowUp,
TiAt,
TiAttachmentOutline,
TiAttachment,
TiBackspaceOutline,
TiBackspace,
TiBatteryCharge,
TiBatteryFull,
TiBatteryHigh,
TiBatteryLow,
TiBatteryMid,
TiBeaker,
TiBeer,
TiBell,
TiBook,
TiBookmark,
TiBriefcase,
TiBrush,
TiBusinessCard,
TiCalculator,
TiCalendarOutline,
TiCalendar,
TiCameraOutline,
TiCamera,
TiCancelOutline,
TiCancel,
TiChartAreaOutline,
TiChartArea,
TiChartBarOutline,
TiChartBar,
TiChartLineOutline,
TiChartLine,
TiChartPieOutline,
TiChartPie,
TiChevronLeftOutline,
TiChevronLeft,
TiChevronRightOutline,
TiChevronRight,
TiClipboard,
TiCloudStorageOutline,
TiCloudStorage,
TiCodeOutline,
TiCode,
TiCoffee,
TiCogOutline,
TiCog,
TiCompass,
TiContacts,
TiCreditCard,
TiCss3,
TiDatabase,
TiDeleteOutline,
TiDelete,
TiDeviceDesktop,
TiDeviceLaptop,
TiDevicePhone,
TiDeviceTablet,
TiDirections,
TiDivideOutline,
TiDivide,
TiDocumentAdd,
TiDocumentDelete,
TiDocumentText,
TiDocument,
TiDownloadOutline,
TiDownload,
TiDropbox,
TiEdit,
TiEjectOutline,
TiEject,
TiEqualsOutline,
TiEquals,
TiExportOutline,
TiExport,
TiEyeOutline,
TiEye,
TiFeather,
TiFilm,
TiFilter,
TiFlagOutline,
TiFlag,
TiFlashOutline,
TiFlash,
TiFlowChildren,
TiFlowMerge,
TiFlowParallel,
TiFlowSwitch,
TiFolderAdd,
TiFolderDelete,
TiFolderOpen,
TiFolder,
TiGift,
TiGlobeOutline,
TiGlobe,
TiGroupOutline,
TiGroup,
TiHeadphones,
TiHeartFullOutline,
TiHeartHalfOutline,
TiHeartOutline,
TiHeart,
TiHomeOutline,
TiHome,
TiHtml5,
TiImageOutline,
TiImage,
TiInfinityOutline,
TiInfinity,
TiInfoLargeOutline,
TiInfoLarge,
TiInfoOutline,
TiInfo,
TiInputCheckedOutline,
TiInputChecked,
TiKeyOutline,
TiKey,
TiKeyboard,
TiLeaf,
TiLightbulb,
TiLinkOutline,
TiLink,
TiLocationArrowOutline,
TiLocationArrow,
TiLocationOutline,
TiLocation,
TiLockClosedOutline,
TiLockClosed,
TiLockOpenOutline,
TiLockOpen,
TiMail,
TiMap,
TiMediaEjectOutline,
TiMediaEject,
TiMediaFastForwardOutline,
TiMediaFastForward,
TiMediaPauseOutline,
TiMediaPause,
TiMediaPlayOutline,
TiMediaPlayReverseOutline,
TiMediaPlayReverse,
TiMediaPlay,
TiMediaRecordOutline,
TiMediaRecord,
TiMediaRewindOutline,
TiMediaRewind,
TiMediaStopOutline,
TiMediaStop,
TiMessageTyping,
TiMessage,
TiMessages,
TiMicrophoneOutline,
TiMicrophone,
TiMinusOutline,
TiMinus,
TiMortarBoard,
TiNews,
TiNotesOutline,
TiNotes,
TiPen,
TiPencil,
TiPhoneOutline,
TiPhone,
TiPiOutline,
TiPi,
TiPinOutline,
TiPin,
TiPipette,
TiPlaneOutline,
TiPlane,
TiPlug,
TiPlusOutline,
TiPlus,
TiPointOfInterestOutline,
TiPointOfInterest,
TiPowerOutline,
TiPower,
TiPrinter,
TiPuzzleOutline,
TiPuzzle,
TiRadarOutline,
TiRadar,
TiRefreshOutline,
TiRefresh,
TiRssOutline,
TiRss,
TiScissorsOutline,
TiScissors,
TiShoppingBag,
TiShoppingCart,
TiSocialAtCircular,
TiSocialDribbbleCircular,
TiSocialDribbble,
TiSocialFacebookCircular,
TiSocialFacebook,
TiSocialFlickrCircular,
TiSocialFlickr,
TiSocialGithubCircular,
TiSocialGithub,
TiSocialGooglePlusCircular,
TiSocialGooglePlus,
TiSocialInstagramCircular,
TiSocialInstagram,
TiSocialLastFmCircular,
TiSocialLastFm,
TiSocialLinkedinCircular,
TiSocialLinkedin,
TiSocialPinterestCircular,
TiSocialPinterest,
TiSocialSkypeOutline,
TiSocialSkype,
TiSocialTumblerCircular,
TiSocialTumbler,
TiSocialTwitterCircular,
TiSocialTwitter,
TiSocialVimeoCircular,
TiSocialVimeo,
TiSocialYoutubeCircular,
TiSocialYoutube,
TiSortAlphabeticallyOutline,
TiSortAlphabetically,
TiSortNumericallyOutline,
TiSortNumerically,
TiSpannerOutline,
TiSpanner,
TiSpiral,
TiStarFullOutline,
TiStarHalfOutline,
TiStarHalf,
TiStarOutline,
TiStar,
TiStarburstOutline,
TiStarburst,
TiStopwatch,
TiSupport,
TiTabsOutline,
TiTag,
TiTags,
TiThLargeOutline,
TiThLarge,
TiThListOutline,
TiThList,
TiThMenuOutline,
TiThMenu,
TiThSmallOutline,
TiThSmall,
TiThermometer,
TiThumbsDown,
TiThumbsOk,
TiThumbsUp,
TiTickOutline,
TiTick,
TiTicket,
TiTime,
TiTimesOutline,
TiTimes,
TiTrash,
TiTree,
TiUploadOutline,
TiUpload,
TiUserAddOutline,
TiUserAdd,
TiUserDeleteOutline,
TiUserDelete,
TiUserOutline,
TiUser,
TiVendorAndroid,
TiVendorApple,
TiVendorMicrosoft,
TiVideoOutline,
TiVideo,
TiVolumeDown,
TiVolumeMute,
TiVolumeUp,
TiVolume,
TiWarningOutline,
TiWarning,
TiWatch,
TiWavesOutline,
TiWaves,
TiWeatherCloudy,
TiWeatherDownpour,
TiWeatherNight,
TiWeatherPartlySunny,
TiWeatherShower,
TiWeatherSnow,
TiWeatherStormy,
TiWeatherSunny,
TiWeatherWindyCloudy,
TiWeatherWindy,
TiWiFiOutline,
TiWiFi,
TiWine,
TiWorldOutline,
TiWorld,
TiZoomInOutline,
TiZoomIn,
TiZoomOutOutline,
TiZoomOut,
TiZoomOutline,
TiZoom,
} from "react-icons/ti";

const result = [
{ icon: TiAdjustBrightness, name: "TiAdjustBrightness" },
{ icon: TiAdjustContrast, name: "TiAdjustContrast" },
{ icon: TiAnchorOutline, name: "TiAnchorOutline" },
{ icon: TiAnchor, name: "TiAnchor" },
{ icon: TiArchive, name: "TiArchive" },
{ icon: TiArrowBackOutline, name: "TiArrowBackOutline" },
{ icon: TiArrowBack, name: "TiArrowBack" },
{ icon: TiArrowDownOutline, name: "TiArrowDownOutline" },
{ icon: TiArrowDownThick, name: "TiArrowDownThick" },
{ icon: TiArrowDown, name: "TiArrowDown" },
{ icon: TiArrowForwardOutline, name: "TiArrowForwardOutline" },
{ icon: TiArrowForward, name: "TiArrowForward" },
{ icon: TiArrowLeftOutline, name: "TiArrowLeftOutline" },
{ icon: TiArrowLeftThick, name: "TiArrowLeftThick" },
{ icon: TiArrowLeft, name: "TiArrowLeft" },
{ icon: TiArrowLoopOutline, name: "TiArrowLoopOutline" },
{ icon: TiArrowLoop, name: "TiArrowLoop" },
{ icon: TiArrowMaximiseOutline, name: "TiArrowMaximiseOutline" },
{ icon: TiArrowMaximise, name: "TiArrowMaximise" },
{ icon: TiArrowMinimiseOutline, name: "TiArrowMinimiseOutline" },
{ icon: TiArrowMinimise, name: "TiArrowMinimise" },
{ icon: TiArrowMoveOutline, name: "TiArrowMoveOutline" },
{ icon: TiArrowMove, name: "TiArrowMove" },
{ icon: TiArrowRepeatOutline, name: "TiArrowRepeatOutline" },
{ icon: TiArrowRepeat, name: "TiArrowRepeat" },
{ icon: TiArrowRightOutline, name: "TiArrowRightOutline" },
{ icon: TiArrowRightThick, name: "TiArrowRightThick" },
{ icon: TiArrowRight, name: "TiArrowRight" },
{ icon: TiArrowShuffle, name: "TiArrowShuffle" },
{ icon: TiArrowSortedDown, name: "TiArrowSortedDown" },
{ icon: TiArrowSortedUp, name: "TiArrowSortedUp" },
{ icon: TiArrowSyncOutline, name: "TiArrowSyncOutline" },
{ icon: TiArrowSync, name: "TiArrowSync" },
{ icon: TiArrowUnsorted, name: "TiArrowUnsorted" },
{ icon: TiArrowUpOutline, name: "TiArrowUpOutline" },
{ icon: TiArrowUpThick, name: "TiArrowUpThick" },
{ icon: TiArrowUp, name: "TiArrowUp" },
{ icon: TiAt, name: "TiAt" },
{ icon: TiAttachmentOutline, name: "TiAttachmentOutline" },
{ icon: TiAttachment, name: "TiAttachment" },
{ icon: TiBackspaceOutline, name: "TiBackspaceOutline" },
{ icon: TiBackspace, name: "TiBackspace" },
{ icon: TiBatteryCharge, name: "TiBatteryCharge" },
{ icon: TiBatteryFull, name: "TiBatteryFull" },
{ icon: TiBatteryHigh, name: "TiBatteryHigh" },
{ icon: TiBatteryLow, name: "TiBatteryLow" },
{ icon: TiBatteryMid, name: "TiBatteryMid" },
{ icon: TiBeaker, name: "TiBeaker" },
{ icon: TiBeer, name: "TiBeer" },
{ icon: TiBell, name: "TiBell" },
{ icon: TiBook, name: "TiBook" },
{ icon: TiBookmark, name: "TiBookmark" },
{ icon: TiBriefcase, name: "TiBriefcase" },
{ icon: TiBrush, name: "TiBrush" },
{ icon: TiBusinessCard, name: "TiBusinessCard" },
{ icon: TiCalculator, name: "TiCalculator" },
{ icon: TiCalendarOutline, name: "TiCalendarOutline" },
{ icon: TiCalendar, name: "TiCalendar" },
{ icon: TiCameraOutline, name: "TiCameraOutline" },
{ icon: TiCamera, name: "TiCamera" },
{ icon: TiCancelOutline, name: "TiCancelOutline" },
{ icon: TiCancel, name: "TiCancel" },
{ icon: TiChartAreaOutline, name: "TiChartAreaOutline" },
{ icon: TiChartArea, name: "TiChartArea" },
{ icon: TiChartBarOutline, name: "TiChartBarOutline" },
{ icon: TiChartBar, name: "TiChartBar" },
{ icon: TiChartLineOutline, name: "TiChartLineOutline" },
{ icon: TiChartLine, name: "TiChartLine" },
{ icon: TiChartPieOutline, name: "TiChartPieOutline" },
{ icon: TiChartPie, name: "TiChartPie" },
{ icon: TiChevronLeftOutline, name: "TiChevronLeftOutline" },
{ icon: TiChevronLeft, name: "TiChevronLeft" },
{ icon: TiChevronRightOutline, name: "TiChevronRightOutline" },
{ icon: TiChevronRight, name: "TiChevronRight" },
{ icon: TiClipboard, name: "TiClipboard" },
{ icon: TiCloudStorageOutline, name: "TiCloudStorageOutline" },
{ icon: TiCloudStorage, name: "TiCloudStorage" },
{ icon: TiCodeOutline, name: "TiCodeOutline" },
{ icon: TiCode, name: "TiCode" },
{ icon: TiCoffee, name: "TiCoffee" },
{ icon: TiCogOutline, name: "TiCogOutline" },
{ icon: TiCog, name: "TiCog" },
{ icon: TiCompass, name: "TiCompass" },
{ icon: TiContacts, name: "TiContacts" },
{ icon: TiCreditCard, name: "TiCreditCard" },
{ icon: TiCss3, name: "TiCss3" },
{ icon: TiDatabase, name: "TiDatabase" },
{ icon: TiDeleteOutline, name: "TiDeleteOutline" },
{ icon: TiDelete, name: "TiDelete" },
{ icon: TiDeviceDesktop, name: "TiDeviceDesktop" },
{ icon: TiDeviceLaptop, name: "TiDeviceLaptop" },
{ icon: TiDevicePhone, name: "TiDevicePhone" },
{ icon: TiDeviceTablet, name: "TiDeviceTablet" },
{ icon: TiDirections, name: "TiDirections" },
{ icon: TiDivideOutline, name: "TiDivideOutline" },
{ icon: TiDivide, name: "TiDivide" },
{ icon: TiDocumentAdd, name: "TiDocumentAdd" },
{ icon: TiDocumentDelete, name: "TiDocumentDelete" },
{ icon: TiDocumentText, name: "TiDocumentText" },
{ icon: TiDocument, name: "TiDocument" },
{ icon: TiDownloadOutline, name: "TiDownloadOutline" },
{ icon: TiDownload, name: "TiDownload" },
{ icon: TiDropbox, name: "TiDropbox" },
{ icon: TiEdit, name: "TiEdit" },
{ icon: TiEjectOutline, name: "TiEjectOutline" },
{ icon: TiEject, name: "TiEject" },
{ icon: TiEqualsOutline, name: "TiEqualsOutline" },
{ icon: TiEquals, name: "TiEquals" },
{ icon: TiExportOutline, name: "TiExportOutline" },
{ icon: TiExport, name: "TiExport" },
{ icon: TiEyeOutline, name: "TiEyeOutline" },
{ icon: TiEye, name: "TiEye" },
{ icon: TiFeather, name: "TiFeather" },
{ icon: TiFilm, name: "TiFilm" },
{ icon: TiFilter, name: "TiFilter" },
{ icon: TiFlagOutline, name: "TiFlagOutline" },
{ icon: TiFlag, name: "TiFlag" },
{ icon: TiFlashOutline, name: "TiFlashOutline" },
{ icon: TiFlash, name: "TiFlash" },
{ icon: TiFlowChildren, name: "TiFlowChildren" },
{ icon: TiFlowMerge, name: "TiFlowMerge" },
{ icon: TiFlowParallel, name: "TiFlowParallel" },
{ icon: TiFlowSwitch, name: "TiFlowSwitch" },
{ icon: TiFolderAdd, name: "TiFolderAdd" },
{ icon: TiFolderDelete, name: "TiFolderDelete" },
{ icon: TiFolderOpen, name: "TiFolderOpen" },
{ icon: TiFolder, name: "TiFolder" },
{ icon: TiGift, name: "TiGift" },
{ icon: TiGlobeOutline, name: "TiGlobeOutline" },
{ icon: TiGlobe, name: "TiGlobe" },
{ icon: TiGroupOutline, name: "TiGroupOutline" },
{ icon: TiGroup, name: "TiGroup" },
{ icon: TiHeadphones, name: "TiHeadphones" },
{ icon: TiHeartFullOutline, name: "TiHeartFullOutline" },
{ icon: TiHeartHalfOutline, name: "TiHeartHalfOutline" },
{ icon: TiHeartOutline, name: "TiHeartOutline" },
{ icon: TiHeart, name: "TiHeart" },
{ icon: TiHomeOutline, name: "TiHomeOutline" },
{ icon: TiHome, name: "TiHome" },
{ icon: TiHtml5, name: "TiHtml5" },
{ icon: TiImageOutline, name: "TiImageOutline" },
{ icon: TiImage, name: "TiImage" },
{ icon: TiInfinityOutline, name: "TiInfinityOutline" },
{ icon: TiInfinity, name: "TiInfinity" },
{ icon: TiInfoLargeOutline, name: "TiInfoLargeOutline" },
{ icon: TiInfoLarge, name: "TiInfoLarge" },
{ icon: TiInfoOutline, name: "TiInfoOutline" },
{ icon: TiInfo, name: "TiInfo" },
{ icon: TiInputCheckedOutline, name: "TiInputCheckedOutline" },
{ icon: TiInputChecked, name: "TiInputChecked" },
{ icon: TiKeyOutline, name: "TiKeyOutline" },
{ icon: TiKey, name: "TiKey" },
{ icon: TiKeyboard, name: "TiKeyboard" },
{ icon: TiLeaf, name: "TiLeaf" },
{ icon: TiLightbulb, name: "TiLightbulb" },
{ icon: TiLinkOutline, name: "TiLinkOutline" },
{ icon: TiLink, name: "TiLink" },
{ icon: TiLocationArrowOutline, name: "TiLocationArrowOutline" },
{ icon: TiLocationArrow, name: "TiLocationArrow" },
{ icon: TiLocationOutline, name: "TiLocationOutline" },
{ icon: TiLocation, name: "TiLocation" },
{ icon: TiLockClosedOutline, name: "TiLockClosedOutline" },
{ icon: TiLockClosed, name: "TiLockClosed" },
{ icon: TiLockOpenOutline, name: "TiLockOpenOutline" },
{ icon: TiLockOpen, name: "TiLockOpen" },
{ icon: TiMail, name: "TiMail" },
{ icon: TiMap, name: "TiMap" },
{ icon: TiMediaEjectOutline, name: "TiMediaEjectOutline" },
{ icon: TiMediaEject, name: "TiMediaEject" },
{ icon: TiMediaFastForwardOutline, name: "TiMediaFastForwardOutline" },
{ icon: TiMediaFastForward, name: "TiMediaFastForward" },
{ icon: TiMediaPauseOutline, name: "TiMediaPauseOutline" },
{ icon: TiMediaPause, name: "TiMediaPause" },
{ icon: TiMediaPlayOutline, name: "TiMediaPlayOutline" },
{ icon: TiMediaPlayReverseOutline, name: "TiMediaPlayReverseOutline" },
{ icon: TiMediaPlayReverse, name: "TiMediaPlayReverse" },
{ icon: TiMediaPlay, name: "TiMediaPlay" },
{ icon: TiMediaRecordOutline, name: "TiMediaRecordOutline" },
{ icon: TiMediaRecord, name: "TiMediaRecord" },
{ icon: TiMediaRewindOutline, name: "TiMediaRewindOutline" },
{ icon: TiMediaRewind, name: "TiMediaRewind" },
{ icon: TiMediaStopOutline, name: "TiMediaStopOutline" },
{ icon: TiMediaStop, name: "TiMediaStop" },
{ icon: TiMessageTyping, name: "TiMessageTyping" },
{ icon: TiMessage, name: "TiMessage" },
{ icon: TiMessages, name: "TiMessages" },
{ icon: TiMicrophoneOutline, name: "TiMicrophoneOutline" },
{ icon: TiMicrophone, name: "TiMicrophone" },
{ icon: TiMinusOutline, name: "TiMinusOutline" },
{ icon: TiMinus, name: "TiMinus" },
{ icon: TiMortarBoard, name: "TiMortarBoard" },
{ icon: TiNews, name: "TiNews" },
{ icon: TiNotesOutline, name: "TiNotesOutline" },
{ icon: TiNotes, name: "TiNotes" },
{ icon: TiPen, name: "TiPen" },
{ icon: TiPencil, name: "TiPencil" },
{ icon: TiPhoneOutline, name: "TiPhoneOutline" },
{ icon: TiPhone, name: "TiPhone" },
{ icon: TiPiOutline, name: "TiPiOutline" },
{ icon: TiPi, name: "TiPi" },
{ icon: TiPinOutline, name: "TiPinOutline" },
{ icon: TiPin, name: "TiPin" },
{ icon: TiPipette, name: "TiPipette" },
{ icon: TiPlaneOutline, name: "TiPlaneOutline" },
{ icon: TiPlane, name: "TiPlane" },
{ icon: TiPlug, name: "TiPlug" },
{ icon: TiPlusOutline, name: "TiPlusOutline" },
{ icon: TiPlus, name: "TiPlus" },
{ icon: TiPointOfInterestOutline, name: "TiPointOfInterestOutline" },
{ icon: TiPointOfInterest, name: "TiPointOfInterest" },
{ icon: TiPowerOutline, name: "TiPowerOutline" },
{ icon: TiPower, name: "TiPower" },
{ icon: TiPrinter, name: "TiPrinter" },
{ icon: TiPuzzleOutline, name: "TiPuzzleOutline" },
{ icon: TiPuzzle, name: "TiPuzzle" },
{ icon: TiRadarOutline, name: "TiRadarOutline" },
{ icon: TiRadar, name: "TiRadar" },
{ icon: TiRefreshOutline, name: "TiRefreshOutline" },
{ icon: TiRefresh, name: "TiRefresh" },
{ icon: TiRssOutline, name: "TiRssOutline" },
{ icon: TiRss, name: "TiRss" },
{ icon: TiScissorsOutline, name: "TiScissorsOutline" },
{ icon: TiScissors, name: "TiScissors" },
{ icon: TiShoppingBag, name: "TiShoppingBag" },
{ icon: TiShoppingCart, name: "TiShoppingCart" },
{ icon: TiSocialAtCircular, name: "TiSocialAtCircular" },
{ icon: TiSocialDribbbleCircular, name: "TiSocialDribbbleCircular" },
{ icon: TiSocialDribbble, name: "TiSocialDribbble" },
{ icon: TiSocialFacebookCircular, name: "TiSocialFacebookCircular" },
{ icon: TiSocialFacebook, name: "TiSocialFacebook" },
{ icon: TiSocialFlickrCircular, name: "TiSocialFlickrCircular" },
{ icon: TiSocialFlickr, name: "TiSocialFlickr" },
{ icon: TiSocialGithubCircular, name: "TiSocialGithubCircular" },
{ icon: TiSocialGithub, name: "TiSocialGithub" },
{ icon: TiSocialGooglePlusCircular, name: "TiSocialGooglePlusCircular" },
{ icon: TiSocialGooglePlus, name: "TiSocialGooglePlus" },
{ icon: TiSocialInstagramCircular, name: "TiSocialInstagramCircular" },
{ icon: TiSocialInstagram, name: "TiSocialInstagram" },
{ icon: TiSocialLastFmCircular, name: "TiSocialLastFmCircular" },
{ icon: TiSocialLastFm, name: "TiSocialLastFm" },
{ icon: TiSocialLinkedinCircular, name: "TiSocialLinkedinCircular" },
{ icon: TiSocialLinkedin, name: "TiSocialLinkedin" },
{ icon: TiSocialPinterestCircular, name: "TiSocialPinterestCircular" },
{ icon: TiSocialPinterest, name: "TiSocialPinterest" },
{ icon: TiSocialSkypeOutline, name: "TiSocialSkypeOutline" },
{ icon: TiSocialSkype, name: "TiSocialSkype" },
{ icon: TiSocialTumblerCircular, name: "TiSocialTumblerCircular" },
{ icon: TiSocialTumbler, name: "TiSocialTumbler" },
{ icon: TiSocialTwitterCircular, name: "TiSocialTwitterCircular" },
{ icon: TiSocialTwitter, name: "TiSocialTwitter" },
{ icon: TiSocialVimeoCircular, name: "TiSocialVimeoCircular" },
{ icon: TiSocialVimeo, name: "TiSocialVimeo" },
{ icon: TiSocialYoutubeCircular, name: "TiSocialYoutubeCircular" },
{ icon: TiSocialYoutube, name: "TiSocialYoutube" },
{ icon: TiSortAlphabeticallyOutline, name: "TiSortAlphabeticallyOutline" },
{ icon: TiSortAlphabetically, name: "TiSortAlphabetically" },
{ icon: TiSortNumericallyOutline, name: "TiSortNumericallyOutline" },
{ icon: TiSortNumerically, name: "TiSortNumerically" },
{ icon: TiSpannerOutline, name: "TiSpannerOutline" },
{ icon: TiSpanner, name: "TiSpanner" },
{ icon: TiSpiral, name: "TiSpiral" },
{ icon: TiStarFullOutline, name: "TiStarFullOutline" },
{ icon: TiStarHalfOutline, name: "TiStarHalfOutline" },
{ icon: TiStarHalf, name: "TiStarHalf" },
{ icon: TiStarOutline, name: "TiStarOutline" },
{ icon: TiStar, name: "TiStar" },
{ icon: TiStarburstOutline, name: "TiStarburstOutline" },
{ icon: TiStarburst, name: "TiStarburst" },
{ icon: TiStopwatch, name: "TiStopwatch" },
{ icon: TiSupport, name: "TiSupport" },
{ icon: TiTabsOutline, name: "TiTabsOutline" },
{ icon: TiTag, name: "TiTag" },
{ icon: TiTags, name: "TiTags" },
{ icon: TiThLargeOutline, name: "TiThLargeOutline" },
{ icon: TiThLarge, name: "TiThLarge" },
{ icon: TiThListOutline, name: "TiThListOutline" },
{ icon: TiThList, name: "TiThList" },
{ icon: TiThMenuOutline, name: "TiThMenuOutline" },
{ icon: TiThMenu, name: "TiThMenu" },
{ icon: TiThSmallOutline, name: "TiThSmallOutline" },
{ icon: TiThSmall, name: "TiThSmall" },
{ icon: TiThermometer, name: "TiThermometer" },
{ icon: TiThumbsDown, name: "TiThumbsDown" },
{ icon: TiThumbsOk, name: "TiThumbsOk" },
{ icon: TiThumbsUp, name: "TiThumbsUp" },
{ icon: TiTickOutline, name: "TiTickOutline" },
{ icon: TiTick, name: "TiTick" },
{ icon: TiTicket, name: "TiTicket" },
{ icon: TiTime, name: "TiTime" },
{ icon: TiTimesOutline, name: "TiTimesOutline" },
{ icon: TiTimes, name: "TiTimes" },
{ icon: TiTrash, name: "TiTrash" },
{ icon: TiTree, name: "TiTree" },
{ icon: TiUploadOutline, name: "TiUploadOutline" },
{ icon: TiUpload, name: "TiUpload" },
{ icon: TiUserAddOutline, name: "TiUserAddOutline" },
{ icon: TiUserAdd, name: "TiUserAdd" },
{ icon: TiUserDeleteOutline, name: "TiUserDeleteOutline" },
{ icon: TiUserDelete, name: "TiUserDelete" },
{ icon: TiUserOutline, name: "TiUserOutline" },
{ icon: TiUser, name: "TiUser" },
{ icon: TiVendorAndroid, name: "TiVendorAndroid" },
{ icon: TiVendorApple, name: "TiVendorApple" },
{ icon: TiVendorMicrosoft, name: "TiVendorMicrosoft" },
{ icon: TiVideoOutline, name: "TiVideoOutline" },
{ icon: TiVideo, name: "TiVideo" },
{ icon: TiVolumeDown, name: "TiVolumeDown" },
{ icon: TiVolumeMute, name: "TiVolumeMute" },
{ icon: TiVolumeUp, name: "TiVolumeUp" },
{ icon: TiVolume, name: "TiVolume" },
{ icon: TiWarningOutline, name: "TiWarningOutline" },
{ icon: TiWarning, name: "TiWarning" },
{ icon: TiWatch, name: "TiWatch" },
{ icon: TiWavesOutline, name: "TiWavesOutline" },
{ icon: TiWaves, name: "TiWaves" },
{ icon: TiWeatherCloudy, name: "TiWeatherCloudy" },
{ icon: TiWeatherDownpour, name: "TiWeatherDownpour" },
{ icon: TiWeatherNight, name: "TiWeatherNight" },
{ icon: TiWeatherPartlySunny, name: "TiWeatherPartlySunny" },
{ icon: TiWeatherShower, name: "TiWeatherShower" },
{ icon: TiWeatherSnow, name: "TiWeatherSnow" },
{ icon: TiWeatherStormy, name: "TiWeatherStormy" },
{ icon: TiWeatherSunny, name: "TiWeatherSunny" },
{ icon: TiWeatherWindyCloudy, name: "TiWeatherWindyCloudy" },
{ icon: TiWeatherWindy, name: "TiWeatherWindy" },
{ icon: TiWiFiOutline, name: "TiWiFiOutline" },
{ icon: TiWiFi, name: "TiWiFi" },
{ icon: TiWine, name: "TiWine" },
{ icon: TiWorldOutline, name: "TiWorldOutline" },
{ icon: TiWorld, name: "TiWorld" },
{ icon: TiZoomInOutline, name: "TiZoomInOutline" },
{ icon: TiZoomIn, name: "TiZoomIn" },
{ icon: TiZoomOutOutline, name: "TiZoomOutOutline" },
{ icon: TiZoomOut, name: "TiZoomOut" },
{ icon: TiZoomOutline, name: "TiZoomOutline" },
{ icon: TiZoom, name: "TiZoom" },
];

export default result