import {
	TiAdjustBrightness,
	TiAdjustContrast,
	TiAnchorOutline,
	TiAnchor,
	TiArchive,
	TiArrowBackOutline,
	TiArrowBack,
	TiArrowDownOutline,
	TiArrowDownThick,
	TiArrowDown,
	TiArrowForwardOutline,
	TiArrowForward,
	TiArrowLeftOutline,
	TiArrowLeftThick,
	TiArrowLeft,
	TiArrowLoopOutline,
	TiArrowLoop,
	TiArrowMaximiseOutline,
	TiArrowMaximise,
	TiArrowMinimiseOutline,
	TiArrowMinimise,
	TiArrowMoveOutline,
	TiArrowMove,
	TiArrowRepeatOutline,
	TiArrowRepeat,
	TiArrowRightOutline,
	TiArrowRightThick,
	TiArrowRight,
	TiArrowShuffle,
	TiArrowSortedDown,
	TiArrowSortedUp,
	TiArrowSyncOutline,
	TiArrowSync,
	TiArrowUnsorted,
	TiArrowUpOutline,
	TiArrowUpThick,
	TiArrowUp,
	TiAt,
	TiAttachmentOutline,
	TiAttachment,
	TiBackspaceOutline,
	TiBackspace,
	TiBatteryCharge,
	TiBatteryFull,
	TiBatteryHigh,
	TiBatteryLow,
	TiBatteryMid,
	TiBeaker,
	TiBeer,
	TiBell,
	TiBook,
	TiBookmark,
	TiBriefcase,
	TiBrush,
	TiBusinessCard,
	TiCalculator,
	TiCalendarOutline,
	TiCalendar,
	TiCameraOutline,
	TiCamera,
	TiCancelOutline,
	TiCancel,
	TiChartAreaOutline,
	TiChartArea,
	TiChartBarOutline,
	TiChartBar,
	TiChartLineOutline,
	TiChartLine,
	TiChartPieOutline,
	TiChartPie,
	TiChevronLeftOutline,
	TiChevronLeft,
	TiChevronRightOutline,
	TiChevronRight,
	TiClipboard,
	TiCloudStorageOutline,
	TiCloudStorage,
	TiCodeOutline,
	TiCode,
	TiCoffee,
	TiCogOutline,
	TiCog,
	TiCompass,
	TiContacts,
	TiCreditCard,
	TiCss3,
	TiDatabase,
	TiDeleteOutline,
	TiDelete,
	TiDeviceDesktop,
	TiDeviceLaptop,
	TiDevicePhone,
	TiDeviceTablet,
	TiDirections,
	TiDivideOutline,
	TiDivide,
	TiDocumentAdd,
	TiDocumentDelete,
	TiDocumentText,
	TiDocument,
	TiDownloadOutline,
	TiDownload,
	TiDropbox,
	TiEdit,
	TiEjectOutline,
	TiEject,
	TiEqualsOutline,
	TiEquals,
	TiExportOutline,
	TiExport,
	TiEyeOutline,
	TiEye,
	TiFeather,
	TiFilm,
	TiFilter,
	TiFlagOutline,
	TiFlag,
	TiFlashOutline,
	TiFlash,
	TiFlowChildren,
	TiFlowMerge,
	TiFlowParallel,
	TiFlowSwitch,
	TiFolderAdd,
	TiFolderDelete,
	TiFolderOpen,
	TiFolder,
	TiGift,
	TiGlobeOutline,
	TiGlobe,
	TiGroupOutline,
	TiGroup,
	TiHeadphones,
	TiHeartFullOutline,
	TiHeartHalfOutline,
	TiHeartOutline,
	TiHeart,
	TiHomeOutline,
	TiHome,
	TiHtml5,
	TiImageOutline,
	TiImage,
	TiInfinityOutline,
	TiInfinity,
	TiInfoLargeOutline,
	TiInfoLarge,
	TiInfoOutline,
	TiInfo,
	TiInputCheckedOutline,
	TiInputChecked,
	TiKeyOutline,
	TiKey,
	TiKeyboard,
	TiLeaf,
	TiLightbulb,
	TiLinkOutline,
	TiLink,
	TiLocationArrowOutline,
	TiLocationArrow,
	TiLocationOutline,
	TiLocation,
	TiLockClosedOutline,
	TiLockClosed,
	TiLockOpenOutline,
	TiLockOpen,
	TiMail,
	TiMap,
	TiMediaEjectOutline,
	TiMediaEject,
	TiMediaFastForwardOutline,
	TiMediaFastForward,
	TiMediaPauseOutline,
	TiMediaPause,
	TiMediaPlayOutline,
	TiMediaPlayReverseOutline,
	TiMediaPlayReverse,
	TiMediaPlay,
	TiMediaRecordOutline,
	TiMediaRecord,
	TiMediaRewindOutline,
	TiMediaRewind,
	TiMediaStopOutline,
	TiMediaStop,
	TiMessageTyping,
	TiMessage,
	TiMessages,
	TiMicrophoneOutline,
	TiMicrophone,
	TiMinusOutline,
	TiMinus,
	TiMortarBoard,
	TiNews,
	TiNotesOutline,
	TiNotes,
	TiPen,
	TiPencil,
	TiPhoneOutline,
	TiPhone,
	TiPiOutline,
	TiPi,
	TiPinOutline,
	TiPin,
	TiPipette,
	TiPlaneOutline,
	TiPlane,
	TiPlug,
	TiPlusOutline,
	TiPlus,
	TiPointOfInterestOutline,
	TiPointOfInterest,
	TiPowerOutline,
	TiPower,
	TiPrinter,
	TiPuzzleOutline,
	TiPuzzle,
	TiRadarOutline,
	TiRadar,
	TiRefreshOutline,
	TiRefresh,
	TiRssOutline,
	TiRss,
	TiScissorsOutline,
	TiScissors,
	TiShoppingBag,
	TiShoppingCart,
	TiSocialAtCircular,
	TiSocialDribbbleCircular,
	TiSocialDribbble,
	TiSocialFacebookCircular,
	TiSocialFacebook,
	TiSocialFlickrCircular,
	TiSocialFlickr,
	TiSocialGithubCircular,
	TiSocialGithub,
	TiSocialGooglePlusCircular,
	TiSocialGooglePlus,
	TiSocialInstagramCircular,
	TiSocialInstagram,
	TiSocialLastFmCircular,
	TiSocialLastFm,
	TiSocialLinkedinCircular,
	TiSocialLinkedin,
	TiSocialPinterestCircular,
	TiSocialPinterest,
	TiSocialSkypeOutline,
	TiSocialSkype,
	TiSocialTumblerCircular,
	TiSocialTumbler,
	TiSocialTwitterCircular,
	TiSocialTwitter,
	TiSocialVimeoCircular,
	TiSocialVimeo,
	TiSocialYoutubeCircular,
	TiSocialYoutube,
	TiSortAlphabeticallyOutline,
	TiSortAlphabetically,
	TiSortNumericallyOutline,
	TiSortNumerically,
	TiSpannerOutline,
	TiSpanner,
	TiSpiral,
	TiStarFullOutline,
	TiStarHalfOutline,
	TiStarHalf,
	TiStarOutline,
	TiStar,
	TiStarburstOutline,
	TiStarburst,
	TiStopwatch,
	TiSupport,
	TiTabsOutline,
	TiTag,
	TiTags,
	TiThLargeOutline,
	TiThLarge,
	TiThListOutline,
	TiThList,
	TiThMenuOutline,
	TiThMenu,
	TiThSmallOutline,
	TiThSmall,
	TiThermometer,
	TiThumbsDown,
	TiThumbsOk,
	TiThumbsUp,
	TiTickOutline,
	TiTick,
	TiTicket,
	TiTime,
	TiTimesOutline,
	TiTimes,
	TiTrash,
	TiTree,
	TiUploadOutline,
	TiUpload,
	TiUserAddOutline,
	TiUserAdd,
	TiUserDeleteOutline,
	TiUserDelete,
	TiUserOutline,
	TiUser,
	TiVendorAndroid,
	TiVendorApple,
	TiVendorMicrosoft,
	TiVideoOutline,
	TiVideo,
	TiVolumeDown,
	TiVolumeMute,
	TiVolumeUp,
	TiVolume,
	TiWarningOutline,
	TiWarning,
	TiWatch,
	TiWavesOutline,
	TiWaves,
	TiWeatherCloudy,
	TiWeatherDownpour,
	TiWeatherNight,
	TiWeatherPartlySunny,
	TiWeatherShower,
	TiWeatherSnow,
	TiWeatherStormy,
	TiWeatherSunny,
	TiWeatherWindyCloudy,
	TiWeatherWindy,
	TiWiFiOutline,
	TiWiFi,
	TiWine,
	TiWorldOutline,
	TiWorld,
	TiZoomInOutline,
	TiZoomIn,
	TiZoomOutOutline,
	TiZoomOut,
	TiZoomOutline,
	TiZoom,
} from "react-icons/ti";

const result = [
	{ icon: TiAdjustBrightness, name: "TiAdjustBrightness", library: "ti" },
	{ icon: TiAdjustContrast, name: "TiAdjustContrast", library: "ti" },
	{ icon: TiAnchorOutline, name: "TiAnchorOutline", library: "ti" },
	{ icon: TiAnchor, name: "TiAnchor", library: "ti" },
	{ icon: TiArchive, name: "TiArchive", library: "ti" },
	{ icon: TiArrowBackOutline, name: "TiArrowBackOutline", library: "ti" },
	{ icon: TiArrowBack, name: "TiArrowBack", library: "ti" },
	{ icon: TiArrowDownOutline, name: "TiArrowDownOutline", library: "ti" },
	{ icon: TiArrowDownThick, name: "TiArrowDownThick", library: "ti" },
	{ icon: TiArrowDown, name: "TiArrowDown", library: "ti" },
	{ icon: TiArrowForwardOutline, name: "TiArrowForwardOutline", library: "ti" },
	{ icon: TiArrowForward, name: "TiArrowForward", library: "ti" },
	{ icon: TiArrowLeftOutline, name: "TiArrowLeftOutline", library: "ti" },
	{ icon: TiArrowLeftThick, name: "TiArrowLeftThick", library: "ti" },
	{ icon: TiArrowLeft, name: "TiArrowLeft", library: "ti" },
	{ icon: TiArrowLoopOutline, name: "TiArrowLoopOutline", library: "ti" },
	{ icon: TiArrowLoop, name: "TiArrowLoop", library: "ti" },
	{ icon: TiArrowMaximiseOutline, name: "TiArrowMaximiseOutline", library: "ti" },
	{ icon: TiArrowMaximise, name: "TiArrowMaximise", library: "ti" },
	{ icon: TiArrowMinimiseOutline, name: "TiArrowMinimiseOutline", library: "ti" },
	{ icon: TiArrowMinimise, name: "TiArrowMinimise", library: "ti" },
	{ icon: TiArrowMoveOutline, name: "TiArrowMoveOutline", library: "ti" },
	{ icon: TiArrowMove, name: "TiArrowMove", library: "ti" },
	{ icon: TiArrowRepeatOutline, name: "TiArrowRepeatOutline", library: "ti" },
	{ icon: TiArrowRepeat, name: "TiArrowRepeat", library: "ti" },
	{ icon: TiArrowRightOutline, name: "TiArrowRightOutline", library: "ti" },
	{ icon: TiArrowRightThick, name: "TiArrowRightThick", library: "ti" },
	{ icon: TiArrowRight, name: "TiArrowRight", library: "ti" },
	{ icon: TiArrowShuffle, name: "TiArrowShuffle", library: "ti" },
	{ icon: TiArrowSortedDown, name: "TiArrowSortedDown", library: "ti" },
	{ icon: TiArrowSortedUp, name: "TiArrowSortedUp", library: "ti" },
	{ icon: TiArrowSyncOutline, name: "TiArrowSyncOutline", library: "ti" },
	{ icon: TiArrowSync, name: "TiArrowSync", library: "ti" },
	{ icon: TiArrowUnsorted, name: "TiArrowUnsorted", library: "ti" },
	{ icon: TiArrowUpOutline, name: "TiArrowUpOutline", library: "ti" },
	{ icon: TiArrowUpThick, name: "TiArrowUpThick", library: "ti" },
	{ icon: TiArrowUp, name: "TiArrowUp", library: "ti" },
	{ icon: TiAt, name: "TiAt", library: "ti" },
	{ icon: TiAttachmentOutline, name: "TiAttachmentOutline", library: "ti" },
	{ icon: TiAttachment, name: "TiAttachment", library: "ti" },
	{ icon: TiBackspaceOutline, name: "TiBackspaceOutline", library: "ti" },
	{ icon: TiBackspace, name: "TiBackspace", library: "ti" },
	{ icon: TiBatteryCharge, name: "TiBatteryCharge", library: "ti" },
	{ icon: TiBatteryFull, name: "TiBatteryFull", library: "ti" },
	{ icon: TiBatteryHigh, name: "TiBatteryHigh", library: "ti" },
	{ icon: TiBatteryLow, name: "TiBatteryLow", library: "ti" },
	{ icon: TiBatteryMid, name: "TiBatteryMid", library: "ti" },
	{ icon: TiBeaker, name: "TiBeaker", library: "ti" },
	{ icon: TiBeer, name: "TiBeer", library: "ti" },
	{ icon: TiBell, name: "TiBell", library: "ti" },
	{ icon: TiBook, name: "TiBook", library: "ti" },
	{ icon: TiBookmark, name: "TiBookmark", library: "ti" },
	{ icon: TiBriefcase, name: "TiBriefcase", library: "ti" },
	{ icon: TiBrush, name: "TiBrush", library: "ti" },
	{ icon: TiBusinessCard, name: "TiBusinessCard", library: "ti" },
	{ icon: TiCalculator, name: "TiCalculator", library: "ti" },
	{ icon: TiCalendarOutline, name: "TiCalendarOutline", library: "ti" },
	{ icon: TiCalendar, name: "TiCalendar", library: "ti" },
	{ icon: TiCameraOutline, name: "TiCameraOutline", library: "ti" },
	{ icon: TiCamera, name: "TiCamera", library: "ti" },
	{ icon: TiCancelOutline, name: "TiCancelOutline", library: "ti" },
	{ icon: TiCancel, name: "TiCancel", library: "ti" },
	{ icon: TiChartAreaOutline, name: "TiChartAreaOutline", library: "ti" },
	{ icon: TiChartArea, name: "TiChartArea", library: "ti" },
	{ icon: TiChartBarOutline, name: "TiChartBarOutline", library: "ti" },
	{ icon: TiChartBar, name: "TiChartBar", library: "ti" },
	{ icon: TiChartLineOutline, name: "TiChartLineOutline", library: "ti" },
	{ icon: TiChartLine, name: "TiChartLine", library: "ti" },
	{ icon: TiChartPieOutline, name: "TiChartPieOutline", library: "ti" },
	{ icon: TiChartPie, name: "TiChartPie", library: "ti" },
	{ icon: TiChevronLeftOutline, name: "TiChevronLeftOutline", library: "ti" },
	{ icon: TiChevronLeft, name: "TiChevronLeft", library: "ti" },
	{ icon: TiChevronRightOutline, name: "TiChevronRightOutline", library: "ti" },
	{ icon: TiChevronRight, name: "TiChevronRight", library: "ti" },
	{ icon: TiClipboard, name: "TiClipboard", library: "ti" },
	{ icon: TiCloudStorageOutline, name: "TiCloudStorageOutline", library: "ti" },
	{ icon: TiCloudStorage, name: "TiCloudStorage", library: "ti" },
	{ icon: TiCodeOutline, name: "TiCodeOutline", library: "ti" },
	{ icon: TiCode, name: "TiCode", library: "ti" },
	{ icon: TiCoffee, name: "TiCoffee", library: "ti" },
	{ icon: TiCogOutline, name: "TiCogOutline", library: "ti" },
	{ icon: TiCog, name: "TiCog", library: "ti" },
	{ icon: TiCompass, name: "TiCompass", library: "ti" },
	{ icon: TiContacts, name: "TiContacts", library: "ti" },
	{ icon: TiCreditCard, name: "TiCreditCard", library: "ti" },
	{ icon: TiCss3, name: "TiCss3", library: "ti" },
	{ icon: TiDatabase, name: "TiDatabase", library: "ti" },
	{ icon: TiDeleteOutline, name: "TiDeleteOutline", library: "ti" },
	{ icon: TiDelete, name: "TiDelete", library: "ti" },
	{ icon: TiDeviceDesktop, name: "TiDeviceDesktop", library: "ti" },
	{ icon: TiDeviceLaptop, name: "TiDeviceLaptop", library: "ti" },
	{ icon: TiDevicePhone, name: "TiDevicePhone", library: "ti" },
	{ icon: TiDeviceTablet, name: "TiDeviceTablet", library: "ti" },
	{ icon: TiDirections, name: "TiDirections", library: "ti" },
	{ icon: TiDivideOutline, name: "TiDivideOutline", library: "ti" },
	{ icon: TiDivide, name: "TiDivide", library: "ti" },
	{ icon: TiDocumentAdd, name: "TiDocumentAdd", library: "ti" },
	{ icon: TiDocumentDelete, name: "TiDocumentDelete", library: "ti" },
	{ icon: TiDocumentText, name: "TiDocumentText", library: "ti" },
	{ icon: TiDocument, name: "TiDocument", library: "ti" },
	{ icon: TiDownloadOutline, name: "TiDownloadOutline", library: "ti" },
	{ icon: TiDownload, name: "TiDownload", library: "ti" },
	{ icon: TiDropbox, name: "TiDropbox", library: "ti" },
	{ icon: TiEdit, name: "TiEdit", library: "ti" },
	{ icon: TiEjectOutline, name: "TiEjectOutline", library: "ti" },
	{ icon: TiEject, name: "TiEject", library: "ti" },
	{ icon: TiEqualsOutline, name: "TiEqualsOutline", library: "ti" },
	{ icon: TiEquals, name: "TiEquals", library: "ti" },
	{ icon: TiExportOutline, name: "TiExportOutline", library: "ti" },
	{ icon: TiExport, name: "TiExport", library: "ti" },
	{ icon: TiEyeOutline, name: "TiEyeOutline", library: "ti" },
	{ icon: TiEye, name: "TiEye", library: "ti" },
	{ icon: TiFeather, name: "TiFeather", library: "ti" },
	{ icon: TiFilm, name: "TiFilm", library: "ti" },
	{ icon: TiFilter, name: "TiFilter", library: "ti" },
	{ icon: TiFlagOutline, name: "TiFlagOutline", library: "ti" },
	{ icon: TiFlag, name: "TiFlag", library: "ti" },
	{ icon: TiFlashOutline, name: "TiFlashOutline", library: "ti" },
	{ icon: TiFlash, name: "TiFlash", library: "ti" },
	{ icon: TiFlowChildren, name: "TiFlowChildren", library: "ti" },
	{ icon: TiFlowMerge, name: "TiFlowMerge", library: "ti" },
	{ icon: TiFlowParallel, name: "TiFlowParallel", library: "ti" },
	{ icon: TiFlowSwitch, name: "TiFlowSwitch", library: "ti" },
	{ icon: TiFolderAdd, name: "TiFolderAdd", library: "ti" },
	{ icon: TiFolderDelete, name: "TiFolderDelete", library: "ti" },
	{ icon: TiFolderOpen, name: "TiFolderOpen", library: "ti" },
	{ icon: TiFolder, name: "TiFolder", library: "ti" },
	{ icon: TiGift, name: "TiGift", library: "ti" },
	{ icon: TiGlobeOutline, name: "TiGlobeOutline", library: "ti" },
	{ icon: TiGlobe, name: "TiGlobe", library: "ti" },
	{ icon: TiGroupOutline, name: "TiGroupOutline", library: "ti" },
	{ icon: TiGroup, name: "TiGroup", library: "ti" },
	{ icon: TiHeadphones, name: "TiHeadphones", library: "ti" },
	{ icon: TiHeartFullOutline, name: "TiHeartFullOutline", library: "ti" },
	{ icon: TiHeartHalfOutline, name: "TiHeartHalfOutline", library: "ti" },
	{ icon: TiHeartOutline, name: "TiHeartOutline", library: "ti" },
	{ icon: TiHeart, name: "TiHeart", library: "ti" },
	{ icon: TiHomeOutline, name: "TiHomeOutline", library: "ti" },
	{ icon: TiHome, name: "TiHome", library: "ti" },
	{ icon: TiHtml5, name: "TiHtml5", library: "ti" },
	{ icon: TiImageOutline, name: "TiImageOutline", library: "ti" },
	{ icon: TiImage, name: "TiImage", library: "ti" },
	{ icon: TiInfinityOutline, name: "TiInfinityOutline", library: "ti" },
	{ icon: TiInfinity, name: "TiInfinity", library: "ti" },
	{ icon: TiInfoLargeOutline, name: "TiInfoLargeOutline", library: "ti" },
	{ icon: TiInfoLarge, name: "TiInfoLarge", library: "ti" },
	{ icon: TiInfoOutline, name: "TiInfoOutline", library: "ti" },
	{ icon: TiInfo, name: "TiInfo", library: "ti" },
	{ icon: TiInputCheckedOutline, name: "TiInputCheckedOutline", library: "ti" },
	{ icon: TiInputChecked, name: "TiInputChecked", library: "ti" },
	{ icon: TiKeyOutline, name: "TiKeyOutline", library: "ti" },
	{ icon: TiKey, name: "TiKey", library: "ti" },
	{ icon: TiKeyboard, name: "TiKeyboard", library: "ti" },
	{ icon: TiLeaf, name: "TiLeaf", library: "ti" },
	{ icon: TiLightbulb, name: "TiLightbulb", library: "ti" },
	{ icon: TiLinkOutline, name: "TiLinkOutline", library: "ti" },
	{ icon: TiLink, name: "TiLink", library: "ti" },
	{ icon: TiLocationArrowOutline, name: "TiLocationArrowOutline", library: "ti" },
	{ icon: TiLocationArrow, name: "TiLocationArrow", library: "ti" },
	{ icon: TiLocationOutline, name: "TiLocationOutline", library: "ti" },
	{ icon: TiLocation, name: "TiLocation", library: "ti" },
	{ icon: TiLockClosedOutline, name: "TiLockClosedOutline", library: "ti" },
	{ icon: TiLockClosed, name: "TiLockClosed", library: "ti" },
	{ icon: TiLockOpenOutline, name: "TiLockOpenOutline", library: "ti" },
	{ icon: TiLockOpen, name: "TiLockOpen", library: "ti" },
	{ icon: TiMail, name: "TiMail", library: "ti" },
	{ icon: TiMap, name: "TiMap", library: "ti" },
	{ icon: TiMediaEjectOutline, name: "TiMediaEjectOutline", library: "ti" },
	{ icon: TiMediaEject, name: "TiMediaEject", library: "ti" },
	{ icon: TiMediaFastForwardOutline, name: "TiMediaFastForwardOutline", library: "ti" },
	{ icon: TiMediaFastForward, name: "TiMediaFastForward", library: "ti" },
	{ icon: TiMediaPauseOutline, name: "TiMediaPauseOutline", library: "ti" },
	{ icon: TiMediaPause, name: "TiMediaPause", library: "ti" },
	{ icon: TiMediaPlayOutline, name: "TiMediaPlayOutline", library: "ti" },
	{ icon: TiMediaPlayReverseOutline, name: "TiMediaPlayReverseOutline", library: "ti" },
	{ icon: TiMediaPlayReverse, name: "TiMediaPlayReverse", library: "ti" },
	{ icon: TiMediaPlay, name: "TiMediaPlay", library: "ti" },
	{ icon: TiMediaRecordOutline, name: "TiMediaRecordOutline", library: "ti" },
	{ icon: TiMediaRecord, name: "TiMediaRecord", library: "ti" },
	{ icon: TiMediaRewindOutline, name: "TiMediaRewindOutline", library: "ti" },
	{ icon: TiMediaRewind, name: "TiMediaRewind", library: "ti" },
	{ icon: TiMediaStopOutline, name: "TiMediaStopOutline", library: "ti" },
	{ icon: TiMediaStop, name: "TiMediaStop", library: "ti" },
	{ icon: TiMessageTyping, name: "TiMessageTyping", library: "ti" },
	{ icon: TiMessage, name: "TiMessage", library: "ti" },
	{ icon: TiMessages, name: "TiMessages", library: "ti" },
	{ icon: TiMicrophoneOutline, name: "TiMicrophoneOutline", library: "ti" },
	{ icon: TiMicrophone, name: "TiMicrophone", library: "ti" },
	{ icon: TiMinusOutline, name: "TiMinusOutline", library: "ti" },
	{ icon: TiMinus, name: "TiMinus", library: "ti" },
	{ icon: TiMortarBoard, name: "TiMortarBoard", library: "ti" },
	{ icon: TiNews, name: "TiNews", library: "ti" },
	{ icon: TiNotesOutline, name: "TiNotesOutline", library: "ti" },
	{ icon: TiNotes, name: "TiNotes", library: "ti" },
	{ icon: TiPen, name: "TiPen", library: "ti" },
	{ icon: TiPencil, name: "TiPencil", library: "ti" },
	{ icon: TiPhoneOutline, name: "TiPhoneOutline", library: "ti" },
	{ icon: TiPhone, name: "TiPhone", library: "ti" },
	{ icon: TiPiOutline, name: "TiPiOutline", library: "ti" },
	{ icon: TiPi, name: "TiPi", library: "ti" },
	{ icon: TiPinOutline, name: "TiPinOutline", library: "ti" },
	{ icon: TiPin, name: "TiPin", library: "ti" },
	{ icon: TiPipette, name: "TiPipette", library: "ti" },
	{ icon: TiPlaneOutline, name: "TiPlaneOutline", library: "ti" },
	{ icon: TiPlane, name: "TiPlane", library: "ti" },
	{ icon: TiPlug, name: "TiPlug", library: "ti" },
	{ icon: TiPlusOutline, name: "TiPlusOutline", library: "ti" },
	{ icon: TiPlus, name: "TiPlus", library: "ti" },
	{ icon: TiPointOfInterestOutline, name: "TiPointOfInterestOutline", library: "ti" },
	{ icon: TiPointOfInterest, name: "TiPointOfInterest", library: "ti" },
	{ icon: TiPowerOutline, name: "TiPowerOutline", library: "ti" },
	{ icon: TiPower, name: "TiPower", library: "ti" },
	{ icon: TiPrinter, name: "TiPrinter", library: "ti" },
	{ icon: TiPuzzleOutline, name: "TiPuzzleOutline", library: "ti" },
	{ icon: TiPuzzle, name: "TiPuzzle", library: "ti" },
	{ icon: TiRadarOutline, name: "TiRadarOutline", library: "ti" },
	{ icon: TiRadar, name: "TiRadar", library: "ti" },
	{ icon: TiRefreshOutline, name: "TiRefreshOutline", library: "ti" },
	{ icon: TiRefresh, name: "TiRefresh", library: "ti" },
	{ icon: TiRssOutline, name: "TiRssOutline", library: "ti" },
	{ icon: TiRss, name: "TiRss", library: "ti" },
	{ icon: TiScissorsOutline, name: "TiScissorsOutline", library: "ti" },
	{ icon: TiScissors, name: "TiScissors", library: "ti" },
	{ icon: TiShoppingBag, name: "TiShoppingBag", library: "ti" },
	{ icon: TiShoppingCart, name: "TiShoppingCart", library: "ti" },
	{ icon: TiSocialAtCircular, name: "TiSocialAtCircular", library: "ti" },
	{ icon: TiSocialDribbbleCircular, name: "TiSocialDribbbleCircular", library: "ti" },
	{ icon: TiSocialDribbble, name: "TiSocialDribbble", library: "ti" },
	{ icon: TiSocialFacebookCircular, name: "TiSocialFacebookCircular", library: "ti" },
	{ icon: TiSocialFacebook, name: "TiSocialFacebook", library: "ti" },
	{ icon: TiSocialFlickrCircular, name: "TiSocialFlickrCircular", library: "ti" },
	{ icon: TiSocialFlickr, name: "TiSocialFlickr", library: "ti" },
	{ icon: TiSocialGithubCircular, name: "TiSocialGithubCircular", library: "ti" },
	{ icon: TiSocialGithub, name: "TiSocialGithub", library: "ti" },
	{
		icon: TiSocialGooglePlusCircular,
		name: "TiSocialGooglePlusCircular",
		library: "ti",
	},
	{ icon: TiSocialGooglePlus, name: "TiSocialGooglePlus", library: "ti" },
	{ icon: TiSocialInstagramCircular, name: "TiSocialInstagramCircular", library: "ti" },
	{ icon: TiSocialInstagram, name: "TiSocialInstagram", library: "ti" },
	{ icon: TiSocialLastFmCircular, name: "TiSocialLastFmCircular", library: "ti" },
	{ icon: TiSocialLastFm, name: "TiSocialLastFm", library: "ti" },
	{ icon: TiSocialLinkedinCircular, name: "TiSocialLinkedinCircular", library: "ti" },
	{ icon: TiSocialLinkedin, name: "TiSocialLinkedin", library: "ti" },
	{ icon: TiSocialPinterestCircular, name: "TiSocialPinterestCircular", library: "ti" },
	{ icon: TiSocialPinterest, name: "TiSocialPinterest", library: "ti" },
	{ icon: TiSocialSkypeOutline, name: "TiSocialSkypeOutline", library: "ti" },
	{ icon: TiSocialSkype, name: "TiSocialSkype", library: "ti" },
	{ icon: TiSocialTumblerCircular, name: "TiSocialTumblerCircular", library: "ti" },
	{ icon: TiSocialTumbler, name: "TiSocialTumbler", library: "ti" },
	{ icon: TiSocialTwitterCircular, name: "TiSocialTwitterCircular", library: "ti" },
	{ icon: TiSocialTwitter, name: "TiSocialTwitter", library: "ti" },
	{ icon: TiSocialVimeoCircular, name: "TiSocialVimeoCircular", library: "ti" },
	{ icon: TiSocialVimeo, name: "TiSocialVimeo", library: "ti" },
	{ icon: TiSocialYoutubeCircular, name: "TiSocialYoutubeCircular", library: "ti" },
	{ icon: TiSocialYoutube, name: "TiSocialYoutube", library: "ti" },
	{
		icon: TiSortAlphabeticallyOutline,
		name: "TiSortAlphabeticallyOutline",
		library: "ti",
	},
	{ icon: TiSortAlphabetically, name: "TiSortAlphabetically", library: "ti" },
	{ icon: TiSortNumericallyOutline, name: "TiSortNumericallyOutline", library: "ti" },
	{ icon: TiSortNumerically, name: "TiSortNumerically", library: "ti" },
	{ icon: TiSpannerOutline, name: "TiSpannerOutline", library: "ti" },
	{ icon: TiSpanner, name: "TiSpanner", library: "ti" },
	{ icon: TiSpiral, name: "TiSpiral", library: "ti" },
	{ icon: TiStarFullOutline, name: "TiStarFullOutline", library: "ti" },
	{ icon: TiStarHalfOutline, name: "TiStarHalfOutline", library: "ti" },
	{ icon: TiStarHalf, name: "TiStarHalf", library: "ti" },
	{ icon: TiStarOutline, name: "TiStarOutline", library: "ti" },
	{ icon: TiStar, name: "TiStar", library: "ti" },
	{ icon: TiStarburstOutline, name: "TiStarburstOutline", library: "ti" },
	{ icon: TiStarburst, name: "TiStarburst", library: "ti" },
	{ icon: TiStopwatch, name: "TiStopwatch", library: "ti" },
	{ icon: TiSupport, name: "TiSupport", library: "ti" },
	{ icon: TiTabsOutline, name: "TiTabsOutline", library: "ti" },
	{ icon: TiTag, name: "TiTag", library: "ti" },
	{ icon: TiTags, name: "TiTags", library: "ti" },
	{ icon: TiThLargeOutline, name: "TiThLargeOutline", library: "ti" },
	{ icon: TiThLarge, name: "TiThLarge", library: "ti" },
	{ icon: TiThListOutline, name: "TiThListOutline", library: "ti" },
	{ icon: TiThList, name: "TiThList", library: "ti" },
	{ icon: TiThMenuOutline, name: "TiThMenuOutline", library: "ti" },
	{ icon: TiThMenu, name: "TiThMenu", library: "ti" },
	{ icon: TiThSmallOutline, name: "TiThSmallOutline", library: "ti" },
	{ icon: TiThSmall, name: "TiThSmall", library: "ti" },
	{ icon: TiThermometer, name: "TiThermometer", library: "ti" },
	{ icon: TiThumbsDown, name: "TiThumbsDown", library: "ti" },
	{ icon: TiThumbsOk, name: "TiThumbsOk", library: "ti" },
	{ icon: TiThumbsUp, name: "TiThumbsUp", library: "ti" },
	{ icon: TiTickOutline, name: "TiTickOutline", library: "ti" },
	{ icon: TiTick, name: "TiTick", library: "ti" },
	{ icon: TiTicket, name: "TiTicket", library: "ti" },
	{ icon: TiTime, name: "TiTime", library: "ti" },
	{ icon: TiTimesOutline, name: "TiTimesOutline", library: "ti" },
	{ icon: TiTimes, name: "TiTimes", library: "ti" },
	{ icon: TiTrash, name: "TiTrash", library: "ti" },
	{ icon: TiTree, name: "TiTree", library: "ti" },
	{ icon: TiUploadOutline, name: "TiUploadOutline", library: "ti" },
	{ icon: TiUpload, name: "TiUpload", library: "ti" },
	{ icon: TiUserAddOutline, name: "TiUserAddOutline", library: "ti" },
	{ icon: TiUserAdd, name: "TiUserAdd", library: "ti" },
	{ icon: TiUserDeleteOutline, name: "TiUserDeleteOutline", library: "ti" },
	{ icon: TiUserDelete, name: "TiUserDelete", library: "ti" },
	{ icon: TiUserOutline, name: "TiUserOutline", library: "ti" },
	{ icon: TiUser, name: "TiUser", library: "ti" },
	{ icon: TiVendorAndroid, name: "TiVendorAndroid", library: "ti" },
	{ icon: TiVendorApple, name: "TiVendorApple", library: "ti" },
	{ icon: TiVendorMicrosoft, name: "TiVendorMicrosoft", library: "ti" },
	{ icon: TiVideoOutline, name: "TiVideoOutline", library: "ti" },
	{ icon: TiVideo, name: "TiVideo", library: "ti" },
	{ icon: TiVolumeDown, name: "TiVolumeDown", library: "ti" },
	{ icon: TiVolumeMute, name: "TiVolumeMute", library: "ti" },
	{ icon: TiVolumeUp, name: "TiVolumeUp", library: "ti" },
	{ icon: TiVolume, name: "TiVolume", library: "ti" },
	{ icon: TiWarningOutline, name: "TiWarningOutline", library: "ti" },
	{ icon: TiWarning, name: "TiWarning", library: "ti" },
	{ icon: TiWatch, name: "TiWatch", library: "ti" },
	{ icon: TiWavesOutline, name: "TiWavesOutline", library: "ti" },
	{ icon: TiWaves, name: "TiWaves", library: "ti" },
	{ icon: TiWeatherCloudy, name: "TiWeatherCloudy", library: "ti" },
	{ icon: TiWeatherDownpour, name: "TiWeatherDownpour", library: "ti" },
	{ icon: TiWeatherNight, name: "TiWeatherNight", library: "ti" },
	{ icon: TiWeatherPartlySunny, name: "TiWeatherPartlySunny", library: "ti" },
	{ icon: TiWeatherShower, name: "TiWeatherShower", library: "ti" },
	{ icon: TiWeatherSnow, name: "TiWeatherSnow", library: "ti" },
	{ icon: TiWeatherStormy, name: "TiWeatherStormy", library: "ti" },
	{ icon: TiWeatherSunny, name: "TiWeatherSunny", library: "ti" },
	{ icon: TiWeatherWindyCloudy, name: "TiWeatherWindyCloudy", library: "ti" },
	{ icon: TiWeatherWindy, name: "TiWeatherWindy", library: "ti" },
	{ icon: TiWiFiOutline, name: "TiWiFiOutline", library: "ti" },
	{ icon: TiWiFi, name: "TiWiFi", library: "ti" },
	{ icon: TiWine, name: "TiWine", library: "ti" },
	{ icon: TiWorldOutline, name: "TiWorldOutline", library: "ti" },
	{ icon: TiWorld, name: "TiWorld", library: "ti" },
	{ icon: TiZoomInOutline, name: "TiZoomInOutline", library: "ti" },
	{ icon: TiZoomIn, name: "TiZoomIn", library: "ti" },
	{ icon: TiZoomOutOutline, name: "TiZoomOutOutline", library: "ti" },
	{ icon: TiZoomOut, name: "TiZoomOut", library: "ti" },
	{ icon: TiZoomOutline, name: "TiZoomOutline", library: "ti" },
	{ icon: TiZoom, name: "TiZoom", library: "ti" },
];

export default result;
