import {
GoAlert,
GoArchive,
GoArrowBoth,
GoArrowDown,
GoArrowLeft,
GoArrowRight,
GoArrowSmallDown,
GoArrowSmallLeft,
GoArrowSmallRight,
GoArrowSmallUp,
GoArrowUp,
GoBeaker,
GoBell,
GoBold,
GoBook,
GoBookmark,
GoBriefcase,
GoBroadcast,
GoBrowser,
GoBug,
GoCalendar,
GoCheck,
GoChecklist,
GoChevronDown,
GoChevronLeft,
GoChevronRight,
GoChevronUp,
GoCircleSlash,
GoCircuitBoard,
GoClippy,
GoClock,
GoCloudDownload,
GoCloudUpload,
GoCode,
GoCommentDiscussion,
GoComment,
GoCreditCard,
GoDash,
GoDashboard,
GoDatabase,
GoDesktopDownload,
GoDeviceCameraVideo,
GoDeviceCamera,
GoDeviceDesktop,
GoDeviceMobile,
GoDiffAdded,
GoDiffIgnored,
GoDiffModified,
GoDiffRemoved,
GoDiffRenamed,
GoDiff,
GoEllipsis,
GoEyeClosed,
GoEye,
GoFileBinary,
GoFileCode,
GoFileDirectory,
GoFileMedia,
GoFilePdf,
GoFileSubmodule,
GoFileSymlinkDirectory,
GoFileSymlinkFile,
GoFileZip,
GoFile,
GoFlame,
GoFoldDown,
GoFoldUp,
GoFold,
GoGear,
GoGift,
GoGistSecret,
GoGist,
GoGitBranch,
GoGitCommit,
GoGitCompare,
GoGitMerge,
GoGitPullRequest,
GoGithubAction,
GoGlobe,
GoGrabber,
GoGraph,
GoHeart,
GoHistory,
GoHome,
GoHorizontalRule,
GoHubot,
GoInbox,
GoInfo,
GoIssueClosed,
GoIssueOpened,
GoIssueReopened,
GoItalic,
GoJersey,
GoKebabHorizontal,
GoKebabVertical,
GoKey,
GoKeyboard,
GoLaw,
GoLightBulb,
GoLinkExternal,
GoLink,
GoListOrdered,
GoListUnordered,
GoLocation,
GoLock,
GoLogoGist,
GoLogoGithub,
GoMailRead,
GoMail,
GoMarkGithub,
GoMarkdown,
GoMegaphone,
GoMention,
GoMilestone,
GoMirror,
GoMortarBoard,
GoMute,
GoNoNewline,
GoNote,
GoOctoface,
GoOrganization,
GoPackage,
GoPaintcan,
GoPencil,
GoPerson,
GoPin,
GoPlay,
GoPlug,
GoPlusSmall,
GoPlus,
GoPrimitiveDot,
GoPrimitiveSquare,
GoProject,
GoPulse,
GoQuestion,
GoQuote,
GoRadioTower,
GoReply,
GoRepoClone,
GoRepoForcePush,
GoRepoForked,
GoRepoPull,
GoRepoPush,
GoRepo,
GoReport,
GoRequestChanges,
GoRocket,
GoRss,
GoRuby,
GoScreenFull,
GoScreenNormal,
GoSearch,
GoServer,
GoSettings,
GoShield,
GoSignIn,
GoSignOut,
GoSmiley,
GoSquirrel,
GoStar,
GoStop,
GoSync,
GoTag,
GoTasklist,
GoTelescope,
GoTerminal,
GoTextSize,
GoThreeBars,
GoThumbsdown,
GoThumbsup,
GoTools,
GoTrashcan,
GoTriangleDown,
GoTriangleLeft,
GoTriangleRight,
GoTriangleUp,
GoUnfold,
GoUnmute,
GoUnverified,
GoVerified,
GoVersions,
GoWatch,
GoX,
GoZap,
} from "react-icons/go";

const result = [
{ icon: GoAlert, name: "GoAlert" },
{ icon: GoArchive, name: "GoArchive" },
{ icon: GoArrowBoth, name: "GoArrowBoth" },
{ icon: GoArrowDown, name: "GoArrowDown" },
{ icon: GoArrowLeft, name: "GoArrowLeft" },
{ icon: GoArrowRight, name: "GoArrowRight" },
{ icon: GoArrowSmallDown, name: "GoArrowSmallDown" },
{ icon: GoArrowSmallLeft, name: "GoArrowSmallLeft" },
{ icon: GoArrowSmallRight, name: "GoArrowSmallRight" },
{ icon: GoArrowSmallUp, name: "GoArrowSmallUp" },
{ icon: GoArrowUp, name: "GoArrowUp" },
{ icon: GoBeaker, name: "GoBeaker" },
{ icon: GoBell, name: "GoBell" },
{ icon: GoBold, name: "GoBold" },
{ icon: GoBook, name: "GoBook" },
{ icon: GoBookmark, name: "GoBookmark" },
{ icon: GoBriefcase, name: "GoBriefcase" },
{ icon: GoBroadcast, name: "GoBroadcast" },
{ icon: GoBrowser, name: "GoBrowser" },
{ icon: GoBug, name: "GoBug" },
{ icon: GoCalendar, name: "GoCalendar" },
{ icon: GoCheck, name: "GoCheck" },
{ icon: GoChecklist, name: "GoChecklist" },
{ icon: GoChevronDown, name: "GoChevronDown" },
{ icon: GoChevronLeft, name: "GoChevronLeft" },
{ icon: GoChevronRight, name: "GoChevronRight" },
{ icon: GoChevronUp, name: "GoChevronUp" },
{ icon: GoCircleSlash, name: "GoCircleSlash" },
{ icon: GoCircuitBoard, name: "GoCircuitBoard" },
{ icon: GoClippy, name: "GoClippy" },
{ icon: GoClock, name: "GoClock" },
{ icon: GoCloudDownload, name: "GoCloudDownload" },
{ icon: GoCloudUpload, name: "GoCloudUpload" },
{ icon: GoCode, name: "GoCode" },
{ icon: GoCommentDiscussion, name: "GoCommentDiscussion" },
{ icon: GoComment, name: "GoComment" },
{ icon: GoCreditCard, name: "GoCreditCard" },
{ icon: GoDash, name: "GoDash" },
{ icon: GoDashboard, name: "GoDashboard" },
{ icon: GoDatabase, name: "GoDatabase" },
{ icon: GoDesktopDownload, name: "GoDesktopDownload" },
{ icon: GoDeviceCameraVideo, name: "GoDeviceCameraVideo" },
{ icon: GoDeviceCamera, name: "GoDeviceCamera" },
{ icon: GoDeviceDesktop, name: "GoDeviceDesktop" },
{ icon: GoDeviceMobile, name: "GoDeviceMobile" },
{ icon: GoDiffAdded, name: "GoDiffAdded" },
{ icon: GoDiffIgnored, name: "GoDiffIgnored" },
{ icon: GoDiffModified, name: "GoDiffModified" },
{ icon: GoDiffRemoved, name: "GoDiffRemoved" },
{ icon: GoDiffRenamed, name: "GoDiffRenamed" },
{ icon: GoDiff, name: "GoDiff" },
{ icon: GoEllipsis, name: "GoEllipsis" },
{ icon: GoEyeClosed, name: "GoEyeClosed" },
{ icon: GoEye, name: "GoEye" },
{ icon: GoFileBinary, name: "GoFileBinary" },
{ icon: GoFileCode, name: "GoFileCode" },
{ icon: GoFileDirectory, name: "GoFileDirectory" },
{ icon: GoFileMedia, name: "GoFileMedia" },
{ icon: GoFilePdf, name: "GoFilePdf" },
{ icon: GoFileSubmodule, name: "GoFileSubmodule" },
{ icon: GoFileSymlinkDirectory, name: "GoFileSymlinkDirectory" },
{ icon: GoFileSymlinkFile, name: "GoFileSymlinkFile" },
{ icon: GoFileZip, name: "GoFileZip" },
{ icon: GoFile, name: "GoFile" },
{ icon: GoFlame, name: "GoFlame" },
{ icon: GoFoldDown, name: "GoFoldDown" },
{ icon: GoFoldUp, name: "GoFoldUp" },
{ icon: GoFold, name: "GoFold" },
{ icon: GoGear, name: "GoGear" },
{ icon: GoGift, name: "GoGift" },
{ icon: GoGistSecret, name: "GoGistSecret" },
{ icon: GoGist, name: "GoGist" },
{ icon: GoGitBranch, name: "GoGitBranch" },
{ icon: GoGitCommit, name: "GoGitCommit" },
{ icon: GoGitCompare, name: "GoGitCompare" },
{ icon: GoGitMerge, name: "GoGitMerge" },
{ icon: GoGitPullRequest, name: "GoGitPullRequest" },
{ icon: GoGithubAction, name: "GoGithubAction" },
{ icon: GoGlobe, name: "GoGlobe" },
{ icon: GoGrabber, name: "GoGrabber" },
{ icon: GoGraph, name: "GoGraph" },
{ icon: GoHeart, name: "GoHeart" },
{ icon: GoHistory, name: "GoHistory" },
{ icon: GoHome, name: "GoHome" },
{ icon: GoHorizontalRule, name: "GoHorizontalRule" },
{ icon: GoHubot, name: "GoHubot" },
{ icon: GoInbox, name: "GoInbox" },
{ icon: GoInfo, name: "GoInfo" },
{ icon: GoIssueClosed, name: "GoIssueClosed" },
{ icon: GoIssueOpened, name: "GoIssueOpened" },
{ icon: GoIssueReopened, name: "GoIssueReopened" },
{ icon: GoItalic, name: "GoItalic" },
{ icon: GoJersey, name: "GoJersey" },
{ icon: GoKebabHorizontal, name: "GoKebabHorizontal" },
{ icon: GoKebabVertical, name: "GoKebabVertical" },
{ icon: GoKey, name: "GoKey" },
{ icon: GoKeyboard, name: "GoKeyboard" },
{ icon: GoLaw, name: "GoLaw" },
{ icon: GoLightBulb, name: "GoLightBulb" },
{ icon: GoLinkExternal, name: "GoLinkExternal" },
{ icon: GoLink, name: "GoLink" },
{ icon: GoListOrdered, name: "GoListOrdered" },
{ icon: GoListUnordered, name: "GoListUnordered" },
{ icon: GoLocation, name: "GoLocation" },
{ icon: GoLock, name: "GoLock" },
{ icon: GoLogoGist, name: "GoLogoGist" },
{ icon: GoLogoGithub, name: "GoLogoGithub" },
{ icon: GoMailRead, name: "GoMailRead" },
{ icon: GoMail, name: "GoMail" },
{ icon: GoMarkGithub, name: "GoMarkGithub" },
{ icon: GoMarkdown, name: "GoMarkdown" },
{ icon: GoMegaphone, name: "GoMegaphone" },
{ icon: GoMention, name: "GoMention" },
{ icon: GoMilestone, name: "GoMilestone" },
{ icon: GoMirror, name: "GoMirror" },
{ icon: GoMortarBoard, name: "GoMortarBoard" },
{ icon: GoMute, name: "GoMute" },
{ icon: GoNoNewline, name: "GoNoNewline" },
{ icon: GoNote, name: "GoNote" },
{ icon: GoOctoface, name: "GoOctoface" },
{ icon: GoOrganization, name: "GoOrganization" },
{ icon: GoPackage, name: "GoPackage" },
{ icon: GoPaintcan, name: "GoPaintcan" },
{ icon: GoPencil, name: "GoPencil" },
{ icon: GoPerson, name: "GoPerson" },
{ icon: GoPin, name: "GoPin" },
{ icon: GoPlay, name: "GoPlay" },
{ icon: GoPlug, name: "GoPlug" },
{ icon: GoPlusSmall, name: "GoPlusSmall" },
{ icon: GoPlus, name: "GoPlus" },
{ icon: GoPrimitiveDot, name: "GoPrimitiveDot" },
{ icon: GoPrimitiveSquare, name: "GoPrimitiveSquare" },
{ icon: GoProject, name: "GoProject" },
{ icon: GoPulse, name: "GoPulse" },
{ icon: GoQuestion, name: "GoQuestion" },
{ icon: GoQuote, name: "GoQuote" },
{ icon: GoRadioTower, name: "GoRadioTower" },
{ icon: GoReply, name: "GoReply" },
{ icon: GoRepoClone, name: "GoRepoClone" },
{ icon: GoRepoForcePush, name: "GoRepoForcePush" },
{ icon: GoRepoForked, name: "GoRepoForked" },
{ icon: GoRepoPull, name: "GoRepoPull" },
{ icon: GoRepoPush, name: "GoRepoPush" },
{ icon: GoRepo, name: "GoRepo" },
{ icon: GoReport, name: "GoReport" },
{ icon: GoRequestChanges, name: "GoRequestChanges" },
{ icon: GoRocket, name: "GoRocket" },
{ icon: GoRss, name: "GoRss" },
{ icon: GoRuby, name: "GoRuby" },
{ icon: GoScreenFull, name: "GoScreenFull" },
{ icon: GoScreenNormal, name: "GoScreenNormal" },
{ icon: GoSearch, name: "GoSearch" },
{ icon: GoServer, name: "GoServer" },
{ icon: GoSettings, name: "GoSettings" },
{ icon: GoShield, name: "GoShield" },
{ icon: GoSignIn, name: "GoSignIn" },
{ icon: GoSignOut, name: "GoSignOut" },
{ icon: GoSmiley, name: "GoSmiley" },
{ icon: GoSquirrel, name: "GoSquirrel" },
{ icon: GoStar, name: "GoStar" },
{ icon: GoStop, name: "GoStop" },
{ icon: GoSync, name: "GoSync" },
{ icon: GoTag, name: "GoTag" },
{ icon: GoTasklist, name: "GoTasklist" },
{ icon: GoTelescope, name: "GoTelescope" },
{ icon: GoTerminal, name: "GoTerminal" },
{ icon: GoTextSize, name: "GoTextSize" },
{ icon: GoThreeBars, name: "GoThreeBars" },
{ icon: GoThumbsdown, name: "GoThumbsdown" },
{ icon: GoThumbsup, name: "GoThumbsup" },
{ icon: GoTools, name: "GoTools" },
{ icon: GoTrashcan, name: "GoTrashcan" },
{ icon: GoTriangleDown, name: "GoTriangleDown" },
{ icon: GoTriangleLeft, name: "GoTriangleLeft" },
{ icon: GoTriangleRight, name: "GoTriangleRight" },
{ icon: GoTriangleUp, name: "GoTriangleUp" },
{ icon: GoUnfold, name: "GoUnfold" },
{ icon: GoUnmute, name: "GoUnmute" },
{ icon: GoUnverified, name: "GoUnverified" },
{ icon: GoVerified, name: "GoVerified" },
{ icon: GoVersions, name: "GoVersions" },
{ icon: GoWatch, name: "GoWatch" },
{ icon: GoX, name: "GoX" },
{ icon: GoZap, name: "GoZap" },
];

export default result