import {
	GoAlert,
	GoArchive,
	GoArrowBoth,
	GoArrowDown,
	GoArrowLeft,
	GoArrowRight,
	GoArrowSmallDown,
	GoArrowSmallLeft,
	GoArrowSmallRight,
	GoArrowSmallUp,
	GoArrowUp,
	GoBeaker,
	GoBell,
	GoBold,
	GoBook,
	GoBookmark,
	GoBriefcase,
	GoBroadcast,
	GoBrowser,
	GoBug,
	GoCalendar,
	GoCheck,
	GoChecklist,
	GoChevronDown,
	GoChevronLeft,
	GoChevronRight,
	GoChevronUp,
	GoCircleSlash,
	GoCircuitBoard,
	GoClippy,
	GoClock,
	GoCloudDownload,
	GoCloudUpload,
	GoCode,
	GoCommentDiscussion,
	GoComment,
	GoCreditCard,
	GoDash,
	GoDashboard,
	GoDatabase,
	GoDesktopDownload,
	GoDeviceCameraVideo,
	GoDeviceCamera,
	GoDeviceDesktop,
	GoDeviceMobile,
	GoDiffAdded,
	GoDiffIgnored,
	GoDiffModified,
	GoDiffRemoved,
	GoDiffRenamed,
	GoDiff,
	GoEllipsis,
	GoEyeClosed,
	GoEye,
	GoFileBinary,
	GoFileCode,
	GoFileDirectory,
	GoFileMedia,
	GoFilePdf,
	GoFileSubmodule,
	GoFileSymlinkDirectory,
	GoFileSymlinkFile,
	GoFileZip,
	GoFile,
	GoFlame,
	GoFoldDown,
	GoFoldUp,
	GoFold,
	GoGear,
	GoGift,
	GoGistSecret,
	GoGist,
	GoGitBranch,
	GoGitCommit,
	GoGitCompare,
	GoGitMerge,
	GoGitPullRequest,
	GoGithubAction,
	GoGlobe,
	GoGrabber,
	GoGraph,
	GoHeart,
	GoHistory,
	GoHome,
	GoHorizontalRule,
	GoHubot,
	GoInbox,
	GoInfo,
	GoIssueClosed,
	GoIssueOpened,
	GoIssueReopened,
	GoItalic,
	GoJersey,
	GoKebabHorizontal,
	GoKebabVertical,
	GoKey,
	GoKeyboard,
	GoLaw,
	GoLightBulb,
	GoLinkExternal,
	GoLink,
	GoListOrdered,
	GoListUnordered,
	GoLocation,
	GoLock,
	GoLogoGist,
	GoLogoGithub,
	GoMailRead,
	GoMail,
	GoMarkGithub,
	GoMarkdown,
	GoMegaphone,
	GoMention,
	GoMilestone,
	GoMirror,
	GoMortarBoard,
	GoMute,
	GoNoNewline,
	GoNote,
	GoOctoface,
	GoOrganization,
	GoPackage,
	GoPaintcan,
	GoPencil,
	GoPerson,
	GoPin,
	GoPlay,
	GoPlug,
	GoPlusSmall,
	GoPlus,
	GoPrimitiveDot,
	GoPrimitiveSquare,
	GoProject,
	GoPulse,
	GoQuestion,
	GoQuote,
	GoRadioTower,
	GoReply,
	GoRepoClone,
	GoRepoForcePush,
	GoRepoForked,
	GoRepoPull,
	GoRepoPush,
	GoRepo,
	GoReport,
	GoRequestChanges,
	GoRocket,
	GoRss,
	GoRuby,
	GoScreenFull,
	GoScreenNormal,
	GoSearch,
	GoServer,
	GoSettings,
	GoShield,
	GoSignIn,
	GoSignOut,
	GoSmiley,
	GoSquirrel,
	GoStar,
	GoStop,
	GoSync,
	GoTag,
	GoTasklist,
	GoTelescope,
	GoTerminal,
	GoTextSize,
	GoThreeBars,
	GoThumbsdown,
	GoThumbsup,
	GoTools,
	GoTrashcan,
	GoTriangleDown,
	GoTriangleLeft,
	GoTriangleRight,
	GoTriangleUp,
	GoUnfold,
	GoUnmute,
	GoUnverified,
	GoVerified,
	GoVersions,
	GoWatch,
	GoX,
	GoZap,
} from "react-icons/go";

const result = [
	{ icon: GoAlert, name: "GoAlert", library: "go" },
	{ icon: GoArchive, name: "GoArchive", library: "go" },
	{ icon: GoArrowBoth, name: "GoArrowBoth", library: "go" },
	{ icon: GoArrowDown, name: "GoArrowDown", library: "go" },
	{ icon: GoArrowLeft, name: "GoArrowLeft", library: "go" },
	{ icon: GoArrowRight, name: "GoArrowRight", library: "go" },
	{ icon: GoArrowSmallDown, name: "GoArrowSmallDown", library: "go" },
	{ icon: GoArrowSmallLeft, name: "GoArrowSmallLeft", library: "go" },
	{ icon: GoArrowSmallRight, name: "GoArrowSmallRight", library: "go" },
	{ icon: GoArrowSmallUp, name: "GoArrowSmallUp", library: "go" },
	{ icon: GoArrowUp, name: "GoArrowUp", library: "go" },
	{ icon: GoBeaker, name: "GoBeaker", library: "go" },
	{ icon: GoBell, name: "GoBell", library: "go" },
	{ icon: GoBold, name: "GoBold", library: "go" },
	{ icon: GoBook, name: "GoBook", library: "go" },
	{ icon: GoBookmark, name: "GoBookmark", library: "go" },
	{ icon: GoBriefcase, name: "GoBriefcase", library: "go" },
	{ icon: GoBroadcast, name: "GoBroadcast", library: "go" },
	{ icon: GoBrowser, name: "GoBrowser", library: "go" },
	{ icon: GoBug, name: "GoBug", library: "go" },
	{ icon: GoCalendar, name: "GoCalendar", library: "go" },
	{ icon: GoCheck, name: "GoCheck", library: "go" },
	{ icon: GoChecklist, name: "GoChecklist", library: "go" },
	{ icon: GoChevronDown, name: "GoChevronDown", library: "go" },
	{ icon: GoChevronLeft, name: "GoChevronLeft", library: "go" },
	{ icon: GoChevronRight, name: "GoChevronRight", library: "go" },
	{ icon: GoChevronUp, name: "GoChevronUp", library: "go" },
	{ icon: GoCircleSlash, name: "GoCircleSlash", library: "go" },
	{ icon: GoCircuitBoard, name: "GoCircuitBoard", library: "go" },
	{ icon: GoClippy, name: "GoClippy", library: "go" },
	{ icon: GoClock, name: "GoClock", library: "go" },
	{ icon: GoCloudDownload, name: "GoCloudDownload", library: "go" },
	{ icon: GoCloudUpload, name: "GoCloudUpload", library: "go" },
	{ icon: GoCode, name: "GoCode", library: "go" },
	{ icon: GoCommentDiscussion, name: "GoCommentDiscussion", library: "go" },
	{ icon: GoComment, name: "GoComment", library: "go" },
	{ icon: GoCreditCard, name: "GoCreditCard", library: "go" },
	{ icon: GoDash, name: "GoDash", library: "go" },
	{ icon: GoDashboard, name: "GoDashboard", library: "go" },
	{ icon: GoDatabase, name: "GoDatabase", library: "go" },
	{ icon: GoDesktopDownload, name: "GoDesktopDownload", library: "go" },
	{ icon: GoDeviceCameraVideo, name: "GoDeviceCameraVideo", library: "go" },
	{ icon: GoDeviceCamera, name: "GoDeviceCamera", library: "go" },
	{ icon: GoDeviceDesktop, name: "GoDeviceDesktop", library: "go" },
	{ icon: GoDeviceMobile, name: "GoDeviceMobile", library: "go" },
	{ icon: GoDiffAdded, name: "GoDiffAdded", library: "go" },
	{ icon: GoDiffIgnored, name: "GoDiffIgnored", library: "go" },
	{ icon: GoDiffModified, name: "GoDiffModified", library: "go" },
	{ icon: GoDiffRemoved, name: "GoDiffRemoved", library: "go" },
	{ icon: GoDiffRenamed, name: "GoDiffRenamed", library: "go" },
	{ icon: GoDiff, name: "GoDiff", library: "go" },
	{ icon: GoEllipsis, name: "GoEllipsis", library: "go" },
	{ icon: GoEyeClosed, name: "GoEyeClosed", library: "go" },
	{ icon: GoEye, name: "GoEye", library: "go" },
	{ icon: GoFileBinary, name: "GoFileBinary", library: "go" },
	{ icon: GoFileCode, name: "GoFileCode", library: "go" },
	{ icon: GoFileDirectory, name: "GoFileDirectory", library: "go" },
	{ icon: GoFileMedia, name: "GoFileMedia", library: "go" },
	{ icon: GoFilePdf, name: "GoFilePdf", library: "go" },
	{ icon: GoFileSubmodule, name: "GoFileSubmodule", library: "go" },
	{ icon: GoFileSymlinkDirectory, name: "GoFileSymlinkDirectory", library: "go" },
	{ icon: GoFileSymlinkFile, name: "GoFileSymlinkFile", library: "go" },
	{ icon: GoFileZip, name: "GoFileZip", library: "go" },
	{ icon: GoFile, name: "GoFile", library: "go" },
	{ icon: GoFlame, name: "GoFlame", library: "go" },
	{ icon: GoFoldDown, name: "GoFoldDown", library: "go" },
	{ icon: GoFoldUp, name: "GoFoldUp", library: "go" },
	{ icon: GoFold, name: "GoFold", library: "go" },
	{ icon: GoGear, name: "GoGear", library: "go" },
	{ icon: GoGift, name: "GoGift", library: "go" },
	{ icon: GoGistSecret, name: "GoGistSecret", library: "go" },
	{ icon: GoGist, name: "GoGist", library: "go" },
	{ icon: GoGitBranch, name: "GoGitBranch", library: "go" },
	{ icon: GoGitCommit, name: "GoGitCommit", library: "go" },
	{ icon: GoGitCompare, name: "GoGitCompare", library: "go" },
	{ icon: GoGitMerge, name: "GoGitMerge", library: "go" },
	{ icon: GoGitPullRequest, name: "GoGitPullRequest", library: "go" },
	{ icon: GoGithubAction, name: "GoGithubAction", library: "go" },
	{ icon: GoGlobe, name: "GoGlobe", library: "go" },
	{ icon: GoGrabber, name: "GoGrabber", library: "go" },
	{ icon: GoGraph, name: "GoGraph", library: "go" },
	{ icon: GoHeart, name: "GoHeart", library: "go" },
	{ icon: GoHistory, name: "GoHistory", library: "go" },
	{ icon: GoHome, name: "GoHome", library: "go" },
	{ icon: GoHorizontalRule, name: "GoHorizontalRule", library: "go" },
	{ icon: GoHubot, name: "GoHubot", library: "go" },
	{ icon: GoInbox, name: "GoInbox", library: "go" },
	{ icon: GoInfo, name: "GoInfo", library: "go" },
	{ icon: GoIssueClosed, name: "GoIssueClosed", library: "go" },
	{ icon: GoIssueOpened, name: "GoIssueOpened", library: "go" },
	{ icon: GoIssueReopened, name: "GoIssueReopened", library: "go" },
	{ icon: GoItalic, name: "GoItalic", library: "go" },
	{ icon: GoJersey, name: "GoJersey", library: "go" },
	{ icon: GoKebabHorizontal, name: "GoKebabHorizontal", library: "go" },
	{ icon: GoKebabVertical, name: "GoKebabVertical", library: "go" },
	{ icon: GoKey, name: "GoKey", library: "go" },
	{ icon: GoKeyboard, name: "GoKeyboard", library: "go" },
	{ icon: GoLaw, name: "GoLaw", library: "go" },
	{ icon: GoLightBulb, name: "GoLightBulb", library: "go" },
	{ icon: GoLinkExternal, name: "GoLinkExternal", library: "go" },
	{ icon: GoLink, name: "GoLink", library: "go" },
	{ icon: GoListOrdered, name: "GoListOrdered", library: "go" },
	{ icon: GoListUnordered, name: "GoListUnordered", library: "go" },
	{ icon: GoLocation, name: "GoLocation", library: "go" },
	{ icon: GoLock, name: "GoLock", library: "go" },
	{ icon: GoLogoGist, name: "GoLogoGist", library: "go" },
	{ icon: GoLogoGithub, name: "GoLogoGithub", library: "go" },
	{ icon: GoMailRead, name: "GoMailRead", library: "go" },
	{ icon: GoMail, name: "GoMail", library: "go" },
	{ icon: GoMarkGithub, name: "GoMarkGithub", library: "go" },
	{ icon: GoMarkdown, name: "GoMarkdown", library: "go" },
	{ icon: GoMegaphone, name: "GoMegaphone", library: "go" },
	{ icon: GoMention, name: "GoMention", library: "go" },
	{ icon: GoMilestone, name: "GoMilestone", library: "go" },
	{ icon: GoMirror, name: "GoMirror", library: "go" },
	{ icon: GoMortarBoard, name: "GoMortarBoard", library: "go" },
	{ icon: GoMute, name: "GoMute", library: "go" },
	{ icon: GoNoNewline, name: "GoNoNewline", library: "go" },
	{ icon: GoNote, name: "GoNote", library: "go" },
	{ icon: GoOctoface, name: "GoOctoface", library: "go" },
	{ icon: GoOrganization, name: "GoOrganization", library: "go" },
	{ icon: GoPackage, name: "GoPackage", library: "go" },
	{ icon: GoPaintcan, name: "GoPaintcan", library: "go" },
	{ icon: GoPencil, name: "GoPencil", library: "go" },
	{ icon: GoPerson, name: "GoPerson", library: "go" },
	{ icon: GoPin, name: "GoPin", library: "go" },
	{ icon: GoPlay, name: "GoPlay", library: "go" },
	{ icon: GoPlug, name: "GoPlug", library: "go" },
	{ icon: GoPlusSmall, name: "GoPlusSmall", library: "go" },
	{ icon: GoPlus, name: "GoPlus", library: "go" },
	{ icon: GoPrimitiveDot, name: "GoPrimitiveDot", library: "go" },
	{ icon: GoPrimitiveSquare, name: "GoPrimitiveSquare", library: "go" },
	{ icon: GoProject, name: "GoProject", library: "go" },
	{ icon: GoPulse, name: "GoPulse", library: "go" },
	{ icon: GoQuestion, name: "GoQuestion", library: "go" },
	{ icon: GoQuote, name: "GoQuote", library: "go" },
	{ icon: GoRadioTower, name: "GoRadioTower", library: "go" },
	{ icon: GoReply, name: "GoReply", library: "go" },
	{ icon: GoRepoClone, name: "GoRepoClone", library: "go" },
	{ icon: GoRepoForcePush, name: "GoRepoForcePush", library: "go" },
	{ icon: GoRepoForked, name: "GoRepoForked", library: "go" },
	{ icon: GoRepoPull, name: "GoRepoPull", library: "go" },
	{ icon: GoRepoPush, name: "GoRepoPush", library: "go" },
	{ icon: GoRepo, name: "GoRepo", library: "go" },
	{ icon: GoReport, name: "GoReport", library: "go" },
	{ icon: GoRequestChanges, name: "GoRequestChanges", library: "go" },
	{ icon: GoRocket, name: "GoRocket", library: "go" },
	{ icon: GoRss, name: "GoRss", library: "go" },
	{ icon: GoRuby, name: "GoRuby", library: "go" },
	{ icon: GoScreenFull, name: "GoScreenFull", library: "go" },
	{ icon: GoScreenNormal, name: "GoScreenNormal", library: "go" },
	{ icon: GoSearch, name: "GoSearch", library: "go" },
	{ icon: GoServer, name: "GoServer", library: "go" },
	{ icon: GoSettings, name: "GoSettings", library: "go" },
	{ icon: GoShield, name: "GoShield", library: "go" },
	{ icon: GoSignIn, name: "GoSignIn", library: "go" },
	{ icon: GoSignOut, name: "GoSignOut", library: "go" },
	{ icon: GoSmiley, name: "GoSmiley", library: "go" },
	{ icon: GoSquirrel, name: "GoSquirrel", library: "go" },
	{ icon: GoStar, name: "GoStar", library: "go" },
	{ icon: GoStop, name: "GoStop", library: "go" },
	{ icon: GoSync, name: "GoSync", library: "go" },
	{ icon: GoTag, name: "GoTag", library: "go" },
	{ icon: GoTasklist, name: "GoTasklist", library: "go" },
	{ icon: GoTelescope, name: "GoTelescope", library: "go" },
	{ icon: GoTerminal, name: "GoTerminal", library: "go" },
	{ icon: GoTextSize, name: "GoTextSize", library: "go" },
	{ icon: GoThreeBars, name: "GoThreeBars", library: "go" },
	{ icon: GoThumbsdown, name: "GoThumbsdown", library: "go" },
	{ icon: GoThumbsup, name: "GoThumbsup", library: "go" },
	{ icon: GoTools, name: "GoTools", library: "go" },
	{ icon: GoTrashcan, name: "GoTrashcan", library: "go" },
	{ icon: GoTriangleDown, name: "GoTriangleDown", library: "go" },
	{ icon: GoTriangleLeft, name: "GoTriangleLeft", library: "go" },
	{ icon: GoTriangleRight, name: "GoTriangleRight", library: "go" },
	{ icon: GoTriangleUp, name: "GoTriangleUp", library: "go" },
	{ icon: GoUnfold, name: "GoUnfold", library: "go" },
	{ icon: GoUnmute, name: "GoUnmute", library: "go" },
	{ icon: GoUnverified, name: "GoUnverified", library: "go" },
	{ icon: GoVerified, name: "GoVerified", library: "go" },
	{ icon: GoVersions, name: "GoVersions", library: "go" },
	{ icon: GoWatch, name: "GoWatch", library: "go" },
	{ icon: GoX, name: "GoX", library: "go" },
	{ icon: GoZap, name: "GoZap", library: "go" },
];

export default result;
